import Link from 'next/link'
import {requireAdminPageAccess} from '@/lib/admin/guards'
import {CONTRACT_ORIGINAL_KINDS,listContractOriginalSources,readContractOriginalSource} from '@/lib/ediel/production/contractOriginalSourceIntake'
import {archiveContractOriginalAction,prepareContractOriginalAction,reviewContractOriginalAction} from './actions'
const labels={masterdata_declaration:'Kunduppgifter i signerat avtal',contract_requested_method:'Begärd mätmetod i signerat avtal',metering_method_event:'Avtalad ändring av mätmetod',production_contract_event:'Produktionsavtalets start eller slut'}
export default async function ContractOriginalPage({searchParams}:{searchParams:Promise<{artifactId?:string;contractId?:string}>}){
 await requireAdminPageAccess({allOf:['communication.read','customers.read','contracts.read']})
 const query=await searchParams,[selected,items]=await Promise.all([query.artifactId?readContractOriginalSource(query.artifactId):Promise.resolve(null),query.contractId?listContractOriginalSources(query.contractId):Promise.resolve([])])
 return <main className="mx-auto max-w-5xl space-y-6 p-6"><Link href="/admin/ediel">Till Ediel</Link><h1 className="text-2xl font-semibold">Avtalsoriginal och källgranskning</h1><p>Arkivera det signerade PDF-avtalet och utgivarens signerade källoriginal. En annan behörig granskare måste godkänna samma original innan de används i Ediel-processen.</p>
 <form method="get" className="space-x-2"><label>Avtals-ID <input name="contractId" defaultValue={query.contractId} required className="rounded border p-2"/></label><button className="rounded border p-2">Läs arkiv</button></form>
 {items.length>0&&<ul>{items.map(item=><li key={item.artifactId}><Link href={'?artifactId='+item.artifactId}>{labels[item.kind]} · {item.status} · {item.capturedAt}</Link></li>)}</ul>}
 <section className="space-y-3 rounded border p-4"><h2 className="text-lg font-semibold">Arkivera original</h2><form action={archiveContractOriginalAction} className="grid gap-3"><label>Avtals-ID <input name="contractId" defaultValue={query.contractId??selected?.contractId} required className="ml-2 rounded border p-2"/></label><label>Ändamål <select name="kind" className="ml-2 rounded border p-2">{CONTRACT_ORIGINAL_KINDS.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Miljö <select name="environment" className="ml-2 rounded border p-2"><option value="test">Test</option><option value="production">Produktion</option></select></label><label>Signerad avtals-PDF (högst 10 MiB) <input name="agreement" type="file" accept="application/pdf" required/></label><label>Utgivarens källoriginal (JSON, högst 10 MiB) <input name="source" type="file" accept="application/json" required/></label><label>Registrerad utgivarnyckel <input name="issuerKeyId" className="ml-2 rounded border p-2"/></label><label>Registrerat representationsmandat <input name="representationId" className="ml-2 rounded border p-2"/></label><label>Utgivarens signatur <input name="signatureHex" className="ml-2 rounded border p-2"/></label><button className="rounded border p-2">Arkivera för granskning</button></form></section>
 {selected&&<section className="space-y-3 rounded border p-4"><h2 className="text-lg font-semibold">{labels[selected.kind]} · {selected.status}</h2><p>Original: {selected.artifactId}<br/>Avtal: {selected.contractId}<br/>Källhash: {selected.sourceHash}<br/>Avtalshash: {selected.agreementHash}{selected.sourceId&&<><br/>Granskad källpost: {selected.sourceId}</>}</p>{selected.missing.length>0&&<p role="status">Återstår: {selected.missing.join(', ')}</p>}<details><summary>Källans signerade uppgifter och avtalets omfattning</summary><pre className="overflow-auto whitespace-pre-wrap">{JSON.stringify({scope:selected.nativeScope,claims:selected.claims},null,2)}</pre></details>
 {selected.status!=='authorized'&&<form action={reviewContractOriginalAction} className="grid gap-3"><input type="hidden" name="artifactId" value={selected.artifactId}/><input type="hidden" name="sourceHash" value={selected.sourceHash}/><input type="hidden" name="agreementHash" value={selected.agreementHash}/><input type="hidden" name="claimsHash" value={selected.claimsHash}/><label>Beslut <select name="decision" className="ml-2 rounded border p-2"><option value="hold">Avvakta</option><option value="approve">Godkänn</option><option value="reject">Avvisa</option></select></label><label>Motivering <textarea name="reason" required maxLength={4000} className="block w-full rounded border p-2"/></label><button className="rounded border p-2">Registrera oberoende granskning</button></form>}
 {selected.status==='authorized'&&<form action={prepareContractOriginalAction}><input type="hidden" name="artifactId" value={selected.artifactId}/><button className="rounded border p-2">{selected.kind==='metering_method_event'||selected.kind==='production_contract_event'?'Förbered meddelande genom Ediel-processen':'Bekräfta tillgänglighet för avtalsprocessen'}</button></form>}</section>}</main>
}
