"use client"
import {useEffect,useState,type FormEvent} from 'react'
import type {BilateralCustomerSourceArtifact} from '@/lib/ediel/production/bilateralCustomerSource'
type Choice={id:string;label:string}
type Props={messages:Choice[];periods:(Choice&{contractId:string})[];agreements:Choice[];initialArtifactId:string;canArchive:boolean;canReview:boolean;canApply:boolean}
const api='/api/ediel/customer-source-agreements',maxBytes=8*1024*1024
const field='block w-full min-w-0 rounded border border-slate-400 bg-white p-2 text-slate-950',button='rounded bg-emerald-800 px-4 py-2 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-800 disabled:opacity-50'
async function json(response:Response){const body=await response.json();if(!response.ok&&response.status!==409)throw Error(body.error??'Åtgärden kunde inte genomföras.');return body}
async function base64(file:File){if(!file.size||file.size>maxBytes)throw Error('Välj ett PDF-original på högst 8 MiB.');const bytes=new Uint8Array(await file.arrayBuffer());let value='';for(let n=0;n<bytes.length;n+=8192)value+=String.fromCharCode(...bytes.subarray(n,n+8192));return btoa(value)}
export default function BilateralCustomerWorkspace({messages,periods,agreements,initialArtifactId,canArchive,canReview,canApply}:Props){
 const [source,setSource]=useState(messages[0]?.id??''),[period,setPeriod]=useState(periods[0]?.id??''),[agreement,setAgreement]=useState(agreements[0]?.id??''),[reference,setReference]=useState(''),[version,setVersion]=useState(''),[file,setFile]=useState<File|null>(null),[receipt,setReceipt]=useState(''),[artifactId,setArtifactId]=useState(initialArtifactId),[artifact,setArtifact]=useState<BilateralCustomerSourceArtifact|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[decision,setDecision]=useState('hold'),[reason,setReason]=useState(''),[locator,setLocator]=useState(''),[quote,setQuote]=useState('')
 async function load(id:string){const result=await json(await fetch(`${api}/${encodeURIComponent(id)}`,{cache:'no-store'}));setArtifact(result);setArtifactId(result.artifactId)}
 async function act(work:()=>Promise<void>){setBusy(true);setFeedback('');try{await work()}catch(error){setFeedback(error instanceof Error?error.message:'Åtgärden kunde inte genomföras.')}finally{setBusy(false)}}
 useEffect(()=>{if(initialArtifactId)void fetch(`${api}/${encodeURIComponent(initialArtifactId)}`,{cache:'no-store'}).then(json).then(setArtifact).catch(()=>setFeedback('Underlaget kunde inte läsas med aktuell behörighet.'))},[initialArtifactId])
 async function archive(event:FormEvent){event.preventDefault();await act(async()=>{const selected=periods.find(p=>p.id===period);if(!selected||!source||!agreement||!file)throw Error('Välj mottaget meddelande, leveransperiod, bilateralt avtal och PDF-original.');if(receipt.length>65536)throw Error('Utfärdarkvittot är för stort.');const result=await json(await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceMessageId:source,agreementId:agreement,supplyPeriodId:period,contractId:selected.contractId,source:{bytesBase64:await base64(file),mimeType:'application/pdf',reference,version},...(receipt.trim()?{issuerReceipt:JSON.parse(receipt)}:{})})}));await load(result.artifactId);setFeedback('Originalet är arkiverat. Separat granskning återstår.')})}
 async function review(event:FormEvent){event.preventDefault();if(!artifact)return;await act(async()=>{const result=await json(await fetch(`${api}/${artifact.artifactId}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceHash:artifact.sourceHash,claimsHash:artifact.claimsHash,decision,reason,...(locator||quote?{clause:{locator,quote}}:{})})}));await load(artifact.artifactId);setFeedback(result.status==='authorized'?'Underlaget är godkänt för den mottagna kundändringen.':`Underlaget är ${result.status==='held'?'hållet':'avvisat'}: ${(result.missing??[]).join(', ')}`)})}
 return <section className="space-y-6" aria-label="Bilateralt kundunderlag">
 {canArchive&&<form onSubmit={archive} className="space-y-4 rounded border border-slate-300 p-4"><h2 className="text-lg font-semibold">Arkivera original</h2><label className="block">Mottaget kundändringsmeddelande<select aria-label="Mottaget kundändringsmeddelande" className={field} value={source} onChange={e=>setSource(e.target.value)} required>{messages.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="block">Leveransperiod<select aria-label="Leveransperiod" className={field} value={period} onChange={e=>setPeriod(e.target.value)} required>{periods.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="block">Bilateralt avtal<select aria-label="Bilateralt avtal" className={field} value={agreement} onChange={e=>setAgreement(e.target.value)} required>{agreements.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="block">Källreferens<input aria-label="Källreferens" className={field} value={reference} onChange={e=>setReference(e.target.value)} maxLength={2000} required/></label><label className="block">Källversion<input aria-label="Källversion" className={field} value={version} onChange={e=>setVersion(e.target.value)} maxLength={200} required/></label><label className="block">PDF-original, högst 8 MiB<input aria-label="PDF-original, högst 8 MiB" className={field} type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)} required/></label><label className="block">Utfärdarkvitto (JSON)<textarea aria-label="Utfärdarkvitto (JSON)" className={field} value={receipt} onChange={e=>setReceipt(e.target.value)} maxLength={65536} rows={4}/></label><button className={button} disabled={busy} type="submit">Arkivera original</button></form>}
 <form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void act(()=>load(artifactId))}}><label className="min-w-0 grow">Arkiverat underlags-ID<input aria-label="Arkiverat underlags-ID" className={field} value={artifactId} onChange={e=>setArtifactId(e.target.value)} required/></label><button className={button} disabled={busy} type="submit">Läs underlag</button></form>
 {artifact&&<div className="space-y-4 rounded border border-slate-300 p-4"><h2 className="text-lg font-semibold">Arkiverat underlag</h2><dl className="space-y-2 break-all"><div><dt>Status</dt><dd>{artifact.status}</dd></div><div><dt>Källreferens och version</dt><dd>{artifact.sourceReference} · {artifact.sourceVersion}</dd></div><div><dt>Originalets SHA-256</dt><dd>{artifact.sourceHash}</dd></div><div><dt>Granskningsinnehållets SHA-256</dt><dd>{artifact.claimsHash}</dd></div><div><dt>Återstående underlag</dt><dd>{artifact.missing.join(', ')||'Inga rapporterade luckor.'}</dd></div></dl><a className="underline" href={`${api}/${artifact.artifactId}/source`}>Ladda ned arkiverat PDF-original</a>
 {canReview&&<form onSubmit={review} className="space-y-3"><h3 className="font-semibold">Separat granskning</h3><label className="block">Beslut<select aria-label="Beslut" className={field} value={decision} onChange={e=>setDecision(e.target.value)}><option value="hold">Håll för komplettering</option><option value="approve">Godkänn underlaget</option><option value="reject">Avvisa underlaget</option></select></label><label className="block">Skäl<textarea aria-label="Skäl" className={field} value={reason} onChange={e=>setReason(e.target.value)} maxLength={4000} required/></label><label className="block">Klausulens plats<input aria-label="Klausulens plats" className={field} value={locator} onChange={e=>setLocator(e.target.value)} maxLength={1000} required={decision==='approve'}/></label><label className="block">Ordagrant klausulcitat<textarea aria-label="Ordagrant klausulcitat" className={field} value={quote} onChange={e=>setQuote(e.target.value)} maxLength={10000} required={decision==='approve'}/></label><button className={button} disabled={busy} type="submit">Spara granskning</button></form>}
 {canApply&&artifact.status==='authorized'&&<button className={button} disabled={busy} onClick={()=>void act(async()=>{const result=await json(await fetch(`${api}/${artifact.artifactId}/apply`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}));setFeedback(result.status==='applied'?`Kundversionen är tillämpad (${result.appliedCount} ändringar).`:'Kundändringen är hållen.');await load(artifact.artifactId)})}>Tillämpa mottagen kundändring</button>}</div>}
 <p role="status" aria-live="polite" className="break-words">{feedback}</p></section>
}
