-- Read-only catalog evidence from the genuine disposable replay. No user rows,
-- credentials, grants, ownership changes, or inferred authority are included.
SELECT jsonb_build_object(
 'currentUser',current_user,'sessionUser',session_user,'serverVersion',current_setting('server_version'),
 'roles',(SELECT jsonb_agg(jsonb_build_object('name',rolname,'super',rolsuper,'inherit',rolinherit,'login',rolcanlogin,'bypassRls',rolbypassrls) ORDER BY rolname) FROM pg_roles WHERE rolname IN('postgres','supabase_admin','supabase_auth_admin','supabase_storage_admin','gridex_ediel_retention_owner','anon','authenticated','service_role')),
 'memberships',(SELECT jsonb_agg(jsonb_build_object('role',r.rolname,'member',m.rolname,'grantor',g.rolname,'admin',a.admin_option,'inherit',a.inherit_option,'set',a.set_option) ORDER BY r.rolname,m.rolname) FROM pg_auth_members a JOIN pg_roles r ON r.oid=a.roleid JOIN pg_roles m ON m.oid=a.member JOIN pg_roles g ON g.oid=a.grantor WHERE r.rolname IN('postgres','supabase_admin','supabase_auth_admin','supabase_storage_admin','gridex_ediel_retention_owner') OR m.rolname='postgres'),
 'schemas',(SELECT jsonb_agg(jsonb_build_object('name',n.nspname,'owner',pg_get_userbyid(n.nspowner),'acl',n.nspacl,'currentCreate',has_schema_privilege(current_user,n.oid,'CREATE'),'currentUsage',has_schema_privilege(current_user,n.oid,'USAGE')) ORDER BY n.nspname) FROM pg_namespace n WHERE n.nspname IN('public','auth','storage','gridex_ediel_retention')),
 'relations',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl,'currentSelect',has_table_privilege(current_user,c.oid,'SELECT'),'currentUpdate',has_table_privilege(current_user,c.oid,'UPDATE')) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE (n.nspname,c.relname) IN(('auth','users'),('storage','objects'),('public','companies'))),
 'authUid',(SELECT jsonb_agg(jsonb_build_object('identity',p.oid::regprocedure::text,'owner',pg_get_userbyid(p.proowner),'acl',p.proacl,'currentExecute',has_function_privilege(current_user,p.oid,'EXECUTE'))) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='auth' AND p.proname='uid')
) AS ediel_retention_replay_role_diagnostic;
