// Generated by scripts/generate-staff-openapi.cjs. Do not edit.
// Contract version: 2026-10-03.1; Source SHA-256: cf524f691b2ebd37ef8dfcc4b898c55fc74a99c930a59089235adbfda2752d71.
import type { PublicApiRouteContract } from '@/lib/api/publicRouteRegistry'
export const STAFF_API_ROUTE_DEFINITIONS: Array<Omit<PublicApiRouteContract, 'operationId' | 'responseSchema' | 'scopeMode' | 'cachePolicy' | 'publicIdPolicy'>> = [
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Authenticate an eligible staff member.",
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions/refresh",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Rotate this API client’s staff session credentials.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions/logout",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Revoke the staff API session.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions/mfa/challenge",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Create a challenge for an actor-owned TOTP factor.",
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions/mfa/verify",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Complete the actor-owned TOTP challenge.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions/password",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Change a staff password through the restricted session.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions/recovery",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Request staff recovery without disclosing account existence.",
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/sessions/recovery/verify",
    "scopes": [
      "staff_sessions.write"
    ],
    "description": "Verify a recovery token and obtain a restricted session.",
    "rateLimitClass": "write"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/me",
    "scopes": [
      "staff_context.read"
    ],
    "description": "Read fresh staff permissions and effective capabilities.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/customers",
    "scopes": [
      "staff_customers.read"
    ],
    "description": "Search the API-key organization’s customers.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/customers/[customerReference]",
    "scopes": [
      "staff_customers.read"
    ],
    "description": "Retrieve an explicitly projected customer profile.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/customers/[customerReference]/contacts",
    "scopes": [
      "staff_customers.read"
    ],
    "description": "List the customer’s contacts.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/customers/[customerReference]/addresses",
    "scopes": [
      "staff_customers.read"
    ],
    "description": "List the customer’s addresses.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/customers/[customerReference]/facilities",
    "scopes": [
      "staff_customers.read"
    ],
    "description": "List the customer’s facilities.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/support/cases",
    "scopes": [
      "staff_support.read"
    ],
    "description": "List and search support cases in this organization.",
    "rateLimitClass": "read"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/support/cases",
    "scopes": [
      "staff_support.write"
    ],
    "description": "Create a support case without stopping operational processes.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/support/cases/[caseReference]",
    "scopes": [
      "staff_support.read"
    ],
    "description": "Retrieve a staff-visible support case.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/support/cases/[caseReference]/entries",
    "scopes": [
      "staff_support.read"
    ],
    "description": "List safe staff conversation and case entries.",
    "rateLimitClass": "read"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/support/cases/[caseReference]/replies",
    "scopes": [
      "staff_support.write"
    ],
    "description": "Publish a staff reply or phone summary for the customer.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/support/cases/[caseReference]/internal-notes",
    "scopes": [
      "staff_support.write"
    ],
    "description": "Record an internal note that is never customer-visible.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/support/cases/[caseReference]/status",
    "scopes": [
      "staff_support.write"
    ],
    "description": "Change case status using the current case version.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/support/cases/[caseReference]/assignment",
    "scopes": [
      "staff_support.write"
    ],
    "description": "Assign or unassign an eligible tenant staff member.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/support/assignees",
    "scopes": [
      "staff_support.read"
    ],
    "description": "List currently eligible case assignees.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/support/cases/[caseReference]/attachments",
    "scopes": [
      "staff_support.read"
    ],
    "description": "List staff-visible attachment outcomes.",
    "rateLimitClass": "read"
  },
  {
    "method": "POST",
    "path": "/api/v1/staff/support/cases/[caseReference]/attachments",
    "scopes": [
      "staff_support.write"
    ],
    "description": "Upload one attachment and return its persisted scan outcome.",
    "idempotencyRequired": true,
    "rateLimitClass": "write"
  },
  {
    "method": "GET",
    "path": "/api/v1/staff/support/cases/[caseReference]/attachments/[attachmentReference]",
    "scopes": [
      "staff_support.read"
    ],
    "description": "Download released bytes after checking the stored SHA-256.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/openapi/staff-support-v1.json",
    "scopes": [],
    "description": "Retrieve the current staff OpenAPI specification.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/openapi/2026-10-03.1/staff-support-v1.json",
    "scopes": [],
    "description": "Retrieve the immutable staff OpenAPI specification.",
    "rateLimitClass": "read"
  },
  {
    "method": "GET",
    "path": "/api/v1/openapi/staff-release-manifest.json",
    "scopes": [],
    "description": "Retrieve protocol metadata; this does not confer staff permissions.",
    "rateLimitClass": "read"
  }
]
