import {invoiceeMandatory} from '@/lib/ediel/prodat/prodatInvoicee'
import type {ProdatEngineInvoiceeContext} from '@/lib/ediel/prodat/types'
import {renderProdat} from '@/lib/ediel/prodat/engine'
import {prodatMessageTypeToken} from '@/lib/ediel/prodat/registry'
import {EdifactEnvelopeCodec} from '@/lib/ediel/core/edifactEnvelopeCodec'
import {deriveEdielAckDefaults} from '@/lib/ediel/references'
import {requestedChangeRegisterFacts,requestedChangeDeathSelection,type RequestedChangeBasis} from '@/lib/ediel/production/requestedChangeSource'
import {createProdatRegisterEvidence} from '@/lib/ediel/prodat/prodatRegisterEvidence'
import type {ProdatEngineInput} from '@/lib/ediel/prodat/types'
import type {EdielMessageIntent} from '@/lib/ediel/intent/types'
import type {CreateEdielMessageInput} from '@/lib/ediel/types'
import type {resolveCanonicalOutboundContext} from '@/lib/ediel/core/kernel'
export function requestedChangeRenderInput(input:{basis:RequestedChangeBasis;senderEdielId:string;receiverEdielId:string;applicationReference:string;interchangeReference:string;transactionReference:string;messageVersion:string;generatedAt?:Date}):ProdatEngineInput{
 const b=input.basis,u=b.customerIdentity;if(b.eventKind!==({E:'death',F:'quarter_contract',G:'method_contract'} as const)[b.variant])throw Error('requested_change_variant_event_mismatch')
 const required=b.variant==='E'?invoiceeMandatory(b.invoiceeProfile,'Z09','E'):false
 if(required===null)throw Error('requested_change_invoicee_scope_unqualified')
 const iv=b.invoiceeProfile.invoicee
 if(required&&[...iv.address.lines,iv.address.city,iv.address.postalCode,iv.address.country].some(v=>typeof v!=='string'))throw Error('requested_change_invoicee_components_unqualified')
 const invoicee:ProdatEngineInvoiceeContext|null=required?{id:iv.identity.id,idCodeListQualifier:iv.identity.qualifier,idAgency:iv.identity.agency,name:iv.nameLines.join(' '),nameLines:iv.nameLines,addressLines:iv.address.lines.map(value=>{if(typeof value!=='string')throw Error('requested_change_invoicee_components_unqualified');return value}),city:iv.address.city as string,postalCode:iv.address.postalCode as string,country:iv.address.country as string}:null
 return {code:'Z09',variant:b.variant,mode:b.environment,generatedAt:input.generatedAt,actor:{senderEdielId:input.senderEdielId,receiverEdielId:input.receiverEdielId},route:{applicationReference:input.applicationReference},version:{selectedVersion:input.messageVersion,messageTypeToken:prodatMessageTypeToken(input.messageVersion)},context:{code:'Z09',bgmReference:input.interchangeReference,transactionReference:input.transactionReference,senderEdielId:input.senderEdielId,receiverEdielId:input.receiverEdielId,legalSenderId:b.legalSenderId,legalReceiverId:b.legalReceiverId,meterPointId:b.pointId,meterPointIdAgency:b.identityAgency,gridAreaId:b.gridArea,reasonForTransaction:({E:'E34',F:'E64',G:'E32'} as const)[b.variant],startDate:b.effectiveAt,balanceResponsibleId:b.brpEdielId,meteringMethod:b.variant==='E'?null:b.variant==='F'?'Z04':'Z03',businessContext:b.variant==='E'?'death':null,invoicee,customerId:b.variant==='E'?u.id:null,customerIdCodeListQualifier:b.variant==='E'?u.qualifier:null,customerIdAgency:u.agency,customerName:b.variant==='E'?u.name:'',customerAddressLines:b.variant==='E'?u.addressLines:[],customerCity:b.variant==='E'?u.city:null,customerPostalCode:b.variant==='E'?u.postalCode:null,customerCountry:b.variant==='E'?u.country:null,dependentConditionFacts:{...requestedChangeRegisterFacts(b),deathStatus:requestedChangeDeathSelection(b,input.transactionReference)}}}
}
export function buildRequestedChangeDraft(input:{basis:RequestedChangeBasis;intent:EdielMessageIntent;actorUserId:string;outboundRequestId:string;routeContext:Awaited<ReturnType<typeof resolveCanonicalOutboundContext>>;messageVersion:string}):CreateEdielMessageInput{
 const b=input.basis,i=input.intent,r=input.routeContext
 if(r.companyId!==b.companyId||r.environment!==b.environment||r.actor.tenantIdentity?.legalActorId!==b.legalActorId||r.actor.legalActorEdielId!==b.legalSenderId||r.receiverEdielId!==b.legalReceiverId||!r.actor.marketRoles.includes('electricity_supplier')||i.applicationReference!=='23-DDQ-PRODAT'||!i.transactionReference)throw Error('requested_change_canonical_legal_route_mismatch')
 const request=requestedChangeRenderInput({basis:b,senderEdielId:r.senderEdielId,receiverEdielId:r.receiverEdielId,applicationReference:i.applicationReference,interchangeReference:i.interchangeReference,transactionReference:i.transactionReference,messageVersion:input.messageVersion}),rendered=renderProdat(request),ack=deriveEdielAckDefaults({family:'PRODAT',code:'Z09'})
 const raw=EdifactEnvelopeCodec.encode({sender:r.senderEdielId,receiver:r.receiverEdielId,senderSubAddress:r.senderSubAddress,receiverSubAddress:r.receiverMessageSubAddress??r.receiverSubAddress,interchangeReference:i.interchangeReference,applicationReference:i.applicationReference,environment:b.environment,acknowledgementRequest:ack.requiresContrl,messages:[{messageReference:i.messageReference,messageTypeToken:prodatMessageTypeToken(input.messageVersion),businessSegments:rendered.segments}]})
 return {companyId:b.companyId,actorUserId:input.actorUserId,intentId:i.id,sourceOperationId:b.eventId,routeProfileId:i.routeProfileId,direction:'outbound',messageStandard:'edifact',messageFamily:'PRODAT',messageCode:'Z09',messageVersion:input.messageVersion,processType:'customer_masterdata',environment:b.environment,testFlag:b.environment==='test'?1:0,status:'draft',transportType:'smtp',mailbox:r.mailbox,senderEdielId:r.senderEdielId,senderName:r.senderName,senderSubAddress:r.senderSubAddress,receiverEdielId:r.receiverEdielId,receiverName:r.receiverName,receiverSubAddress:r.receiverMessageSubAddress??r.receiverSubAddress,receiverEmail:r.receiverEmail,communicationRouteId:r.route.id,outboundRequestId:input.outboundRequestId,customerId:b.customerId,meteringPointId:b.meteringPointId,externalReference:i.interchangeReference,interchangeReference:i.interchangeReference,transactionReference:i.transactionReference,applicationReference:i.applicationReference,rawPayload:raw,parsedPayload:{draftType:'requested_change',requestedChangeEventId:b.eventId,actorRole:'supplier',reasonForTransaction:request.context.reasonForTransaction,prodatEngine:{...rendered.diagnostics,registerEvidence:createProdatRegisterEvidence({code:'Z09',rawSegments:rendered.segments,facts:requestedChangeRegisterFacts(b)})}},subject:`PRODAT Z09 ${i.interchangeReference}`,mimeType:'application/edifact',...ack,syntaxCheckStatus:'not_checked',functionalCheckStatus:'not_checked'}
}
