import {renderProdat} from '@/lib/ediel/prodat/engine'
import {prodatMessageTypeToken} from '@/lib/ediel/prodat/registry'
import {resolveCanonicalOutboundVersion} from '@/lib/ediel/core/versionRegistry'
import {EdifactEnvelopeCodec} from '@/lib/ediel/core/edifactEnvelopeCodec'
import {deriveEdielAckDefaults} from '@/lib/ediel/references'
import {prepareCustomerMasterdataSource} from '@/lib/ediel/production/customerMasterdataSource'
import {createCustomerMasterdataAddressFacts} from '@/lib/ediel/prodat/customerMasterdataAuthority'
import {rememberCustomerMasterdataDraft} from '@/lib/ediel/prodat/customerMasterdataDraft'
import {assertSupplyRescissionRoute,type SupplyRescissionBasis} from '@/lib/ediel/production/supplyRescissionOperation'
import {readContractInvoicee} from '@/lib/ediel/production/contractInvoicee'
import type {EdielMessageIntent} from '@/lib/ediel/intent/types'
import type {resolveCanonicalOutboundContext} from '@/lib/ediel/core/kernel'
import type {CreateEdielMessageInput} from '@/lib/ediel/types'

export async function buildSupplyRescissionDraft(input:{actorUserId:string;basis:SupplyRescissionBasis;intent:EdielMessageIntent;routeContext:Awaited<ReturnType<typeof resolveCanonicalOutboundContext>>;outboundRequestId:string}){
 const{basis:b,intent:i,routeContext:route}=input;assertSupplyRescissionRoute(b,route)
 if(i.operationId!==b.mandateId||i.companyId!==b.companyId||i.environment!==b.environment||i.transactionReference!==b.lineItemReference||i.messageCode!=='Z08')throw Error('supply_rescission_render_intent_mismatch')
 const version=await resolveCanonicalOutboundVersion({family:'PRODAT',code:'Z08',standard:'edifact',environment:b.environment,routeDefaultMessageVersion:route.defaultMessageVersion});if(!version)throw Error('supply_rescission_canonical_version_required')
 const customer=await prepareCustomerMasterdataSource({companyId:b.companyId,customerId:b.customerId,actorUserId:input.actorUserId,environment:b.environment})
 if(JSON.stringify(customer.customerIdentity)!==JSON.stringify(b.customerIdentity))throw Error('supply_rescission_actual_customer_changed')
 const address=customer.endUserMasterdata
 const invoicee=await readContractInvoicee({companyId:b.companyId,customerId:b.customerId,contractId:b.contractId,meteringPointId:b.externalPoint,identityAgency:b.identityAgency,
  endUser:{identity:customer.customerIdentity,nameParts:address.nameParts,streetParts:address.streetParts,postalCode:address.postalCode,city:address.city,country:address.country}})
 const rendered=renderProdat({code:'Z08',variant:'H',mode:b.environment,actor:{senderEdielId:route.senderEdielId,receiverEdielId:route.receiverEdielId},route:{applicationReference:i.applicationReference,senderSubAddress:route.senderSubAddress,receiverSubAddress:route.receiverMessageSubAddress??route.receiverSubAddress},version:{selectedVersion:version,messageTypeToken:prodatMessageTypeToken(version)},context:{code:'Z08',bgmReference:b.documentReference,transactionReference:b.lineItemReference,senderEdielId:route.senderEdielId,receiverEdielId:route.receiverEdielId,legalSenderId:b.legalSenderId,legalReceiverId:b.legalReceiverId,meterPointId:b.externalPoint,meterPointIdAgency:b.identityAgency,gridAreaId:b.gridArea,reasonForTransaction:'Z25',contractEndDate:b.effectiveAt,balanceResponsibleId:b.balanceResponsibleId,customerId:customer.customerIdentity.id,customerIdCodeListQualifier:customer.customerIdentity.qualifier,customerIdAgency:customer.customerIdentity.agency,customerName:address.nameParts[0],customerNameLines:address.nameParts,customerAddress:address.streetParts[0],customerAddressLines:address.streetParts,customerPostalCode:address.postalCode,customerCity:address.city,customerCountry:address.country,...(invoicee.invoicee?{invoicee:invoicee.invoicee}:{}),dependentConditionFacts:{market:'electricity',invoiceeObjects:[invoicee.fact],endUserAddressObjects:createCustomerMasterdataAddressFacts({projection:customer,meteringPointId:b.externalPoint,identityAgency:b.identityAgency})}}})
 const ack=deriveEdielAckDefaults({family:'PRODAT',code:'Z08'}),raw=EdifactEnvelopeCodec.encode({sender:route.senderEdielId,receiver:route.receiverEdielId,senderSubAddress:route.senderSubAddress,receiverSubAddress:route.receiverMessageSubAddress??route.receiverSubAddress,interchangeReference:i.interchangeReference,applicationReference:i.applicationReference,environment:b.environment,acknowledgementRequest:ack.requiresContrl,messages:[{messageReference:i.messageReference,messageTypeToken:prodatMessageTypeToken(version),businessSegments:rendered.segments}]})
 const draft:CreateEdielMessageInput={actorUserId:input.actorUserId,companyId:b.companyId,intentId:i.id,sourceOperationId:b.mandateId,routeProfileId:i.routeProfileId,direction:'outbound',messageStandard:'edifact',messageFamily:'PRODAT',messageCode:'Z08',messageVersion:version,processType:'delivery_contract',environment:b.environment,testFlag:b.environment==='test'?1:0,status:'draft',transportType:'smtp',mailbox:route.mailbox,senderEdielId:route.senderEdielId,senderName:route.senderName,senderSubAddress:route.senderSubAddress,receiverEdielId:route.receiverEdielId,receiverName:route.receiverName,receiverSubAddress:route.receiverMessageSubAddress??route.receiverSubAddress,receiverEmail:route.receiverEmail,communicationRouteId:route.route.id,outboundRequestId:input.outboundRequestId,customerId:b.customerId,siteId:b.siteId,meteringPointId:b.pointId,externalReference:i.interchangeReference,interchangeReference:i.interchangeReference,transactionReference:b.lineItemReference,applicationReference:i.applicationReference,rawPayload:raw,parsedPayload:{draftType:'supply_rescission',transactionSubtype:'H',supplyRescissionMandateId:b.mandateId,customerMasterdataSourceContextId:customer.sourceContextId,prodatEngine:rendered.diagnostics},subject:`PRODAT Z08 ${b.documentReference}`,mimeType:'application/edifact',...ack,syntaxCheckStatus:'not_checked',functionalCheckStatus:'not_checked'}
 return{draft:rememberCustomerMasterdataDraft(draft,customer)}
}
