'use client'
import { useActionState } from 'react'
import { customerRecordRetentionAction, type RetentionActionState } from './actions'
export type RetentionChoice={retentionClass:string;label:string;targets:Array<{targetId:string;recordedAt:string|null;tombstoned:boolean}>}
const initial:RetentionActionState={status:'idle',message:''}
function Outcome({state}:{state:RetentionActionState}){return state.message?<div role="status" className="mt-3 rounded-lg border p-3 text-sm"><p>{state.message}</p>{state.decisionId?<p className="mt-1 break-all">Beslutsreferens: {state.decisionId}</p>:null}{state.documentBase64?<a className="mt-2 inline-block underline" download="retention-beslutsunderlag.bin" href={`data:application/octet-stream;base64,${state.documentBase64}`}>Hämta arkiverat beslutsunderlag</a>:null}</div>:null}
export default function CustomerRecordRetentionWorkspace({choices,canSubmit,canReview,canPurge}:{choices:RetentionChoice[];canSubmit:boolean;canReview:boolean;canPurge:boolean}){
 const [submitted,submit,pendingSubmit]=useActionState(customerRecordRetentionAction,initial),[reviewed,review,pendingReview]=useActionState(customerRecordRetentionAction,initial),[purged,purge,pendingPurge]=useActionState(customerRecordRetentionAction,initial)
 return <div className="grid gap-6">
  <section className="rounded-xl border p-4"><h2 className="text-lg font-semibold">Arkivera klassens beslut</h2><p className="mt-2 text-sm">Välj en exakt källa. Bifoga det behöriga juridiska beslutet och dess signerade utfärdarkvitto. Saknat eller ogiltigt kvitto håller ingreppet spärrat.</p>
   {choices.map(choice=><form action={submit} key={choice.retentionClass} className="mt-5 grid gap-3 border-t pt-4"><input type="hidden" name="action" value="submit"/><input type="hidden" name="retention_class" value={choice.retentionClass}/><h3 className="font-semibold">{choice.label}</h3><label>Exakt källpost<select name="target_id" required className="block w-full rounded border p-2" disabled={!canSubmit}><option value="">Välj källa</option>{choice.targets.filter(t=>!t.tombstoned).map(t=><option key={t.targetId} value={t.targetId}>{t.recordedAt??'Registreringstid saknas'} · {t.targetId}</option>)}</select></label><label>Juridiskt beslutsunderlag (högst 750 kB)<input type="file" name="document" required className="block w-full" disabled={!canSubmit}/></label><label>Signerat utfärdarkvitto<textarea name="issuer_receipt" rows={4} maxLength={32768} className="block w-full rounded border p-2" disabled={!canSubmit}/></label><button disabled={!canSubmit||pendingSubmit} className="rounded bg-slate-950 px-4 py-2 text-white disabled:opacity-50">Arkivera beslut</button></form>)}<Outcome state={submitted}/>
  </section>
  <section className="rounded-xl border p-4"><h2 className="text-lg font-semibold">Separat granskning</h2><p className="mt-2 text-sm">En annan behörig person läser originalbeslutet och granskar exakt källa, rättslig grund, tidsgräns och det bevarade journaländamålet.</p>
   <form action={review} className="mt-3 grid gap-3"><input type="hidden" name="action" value="read"/><label>Beslutsreferens för läsning<input name="decision_id" required className="block w-full rounded border p-2" disabled={!canReview}/></label><button disabled={!canReview||pendingReview} className="rounded bg-slate-950 px-4 py-2 text-white disabled:opacity-50">Läs arkiverat originalbeslut</button></form>
   <form action={review} className="mt-5 grid gap-3 border-t pt-4"><input type="hidden" name="action" value="review"/><label>Beslutsreferens för granskning<input name="decision_id" required className="block w-full rounded border p-2" disabled={!canReview}/></label><label>Utfall<select name="outcome" className="block w-full rounded border p-2" disabled={!canReview}><option value="hold">Spärra</option><option value="approve">Godkänn underlaget</option><option value="reject">Avvisa</option></select></label><label>Granskningsmotivering<textarea name="reason" required maxLength={4000} className="block w-full rounded border p-2" disabled={!canReview}/></label><button disabled={!canReview||pendingReview} className="rounded bg-slate-950 px-4 py-2 text-white disabled:opacity-50">Registrera separat granskning</button></form>
   <form action={review} className="mt-5 grid gap-3 border-t pt-4"><input type="hidden" name="action" value="revoke"/><label>Beslutsreferens för återkallelse<input name="decision_id" required className="block w-full rounded border p-2" disabled={!canReview}/></label><label>Återkallelsemotivering<textarea name="reason" required maxLength={4000} className="block w-full rounded border p-2" disabled={!canReview}/></label><button disabled={!canReview||pendingReview} className="rounded bg-slate-950 px-4 py-2 text-white disabled:opacity-50">Återkalla beslutets behörighet</button></form><Outcome state={reviewed}/></section>
  <section className="rounded-xl border p-4"><h2 className="text-lg font-semibold">Genomför klassens ingrepp</h2><p className="mt-2 text-sm">Bolagets kund måste vara operativt avvecklad utan aktiv leverans. Åtkomst återkallas före persondatagallring. Avtalsfil kräver faktisk lagringsradering och verifierad otillgänglighet.</p><form action={purge} className="mt-3 grid gap-3"><input type="hidden" name="action" value="purge"/><label>Beslutsreferens<input name="decision_id" required className="block w-full rounded border p-2" disabled={!canPurge}/></label><button disabled={!canPurge||pendingPurge} className="rounded bg-slate-950 px-4 py-2 text-white disabled:opacity-50">Pröva och genomför ingrepp</button></form><Outcome state={purged}/></section>
 </div>
}
