'use client'
import {useEffect,useState,type FormEvent} from 'react'
export type ProfileChoice={rulePackId:string;label:string}
type Agreement={id:string;environment:string;capability_code:string;source_reference:string|null}
type Artifact={artifactId:string;status:string;sourceHash:string;scopeHash:string;sourceReference:string;sourceVersion:string;byteLength:number;missing:string[];scope:{gridArea:string;validFrom:string;validTo:string;kind:string;sourceVersion:string}}
const control='mt-1 w-full rounded border border-gray-400 bg-white p-2 text-black disabled:bg-gray-100',button='rounded bg-blue-700 px-4 py-2 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-50'
async function body(response:Response){const value=await response.json();if(!response.ok&&value.status!=='held')throw Error(value.error??'Åtgärden kunde inte genomföras.');return value}
async function encoded(file:File){if(!file.size||file.size>8*1024*1024)throw Error('Välj ett original på högst 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let value='';for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(value)}
function missing(m:string[]){return m.some(code=>/issuer|representation/.test(code))?'Ett autentiskt intyg och utfärdarens aktuella rättsliga mandat saknas.':m.some(code=>/separate.*review/.test(code))?'En annan behörig granskare måste pröva originalet.':m.length?'Original, anvisning, nätområde, parter eller aktuellt mandat behöver kompletteras.':''}
export default function BilateralProdatWorkspace({choices,agreements,gridAreas,initialArtifactId,canArchive,canReview}:{choices:ProfileChoice[];agreements:Agreement[];gridAreas:string[];initialArtifactId:string;canArchive:boolean;canReview:boolean}){
 const [artifactId,setArtifactId]=useState(initialArtifactId),[artifact,setArtifact]=useState<Artifact|null>(null),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false)
 async function load(id:string){const value=await body(await fetch(`/api/ediel/bilateral-prodat-sources/${encodeURIComponent(id)}`,{cache:'no-store'}));setArtifact(value);setArtifactId(id)}
 useEffect(()=>{let current=true;if(initialArtifactId)fetch(`/api/ediel/bilateral-prodat-sources/${encodeURIComponent(initialArtifactId)}`,{cache:'no-store'}).then(body).then(value=>{if(current)setArtifact(value)}).catch(error=>{if(current)setFeedback(error.message)});return()=>{current=false}},[initialArtifactId])
 async function act(work:()=>Promise<void>){setBusy(true);setFeedback('');try{await work()}catch(error){setFeedback(error instanceof Error?error.message:'Åtgärden kunde inte genomföras.')}finally{setBusy(false)}}
 async function archive(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{
  const choice=choices.find(c=>c.rulePackId===form.get('pack')),agreement=agreements.find(a=>a.id===form.get('agreement'));if(!choice||!agreement)throw Error('Välj den valda anvisningen och bolagets dokumenterade överenskommelse.')
  const kind=agreement.capability_code.slice('PRODAT:BILATERAL:'.length),gridAreaCode=String(form.get('gridArea'));if(!gridAreas.includes(gridAreaCode))throw Error('Välj bolagets faktiska nätområde.')
  const file=form.get('source') as File;if(!(file instanceof File))throw Error('Välj originalunderlaget.');const mimeType=file.type||(/\.pdf$/i.test(file.name)?'application/pdf':/\.json$/i.test(file.name)?'application/json':'text/plain')
  if(!['application/pdf','application/json','text/plain'].includes(mimeType))throw Error('Underlaget måste vara PDF, text eller JSON.')
  const issuerFile=form.get('issuer') as File;let issuerReceipt:unknown;if(issuerFile instanceof File&&issuerFile.size){if(issuerFile.size>65536)throw Error('Utfärdarintyget är för stort.');issuerReceipt=JSON.parse(await issuerFile.text())}
  const result=await body(await fetch('/api/ediel/bilateral-prodat-sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({environment:agreement.environment,kind,rulePackId:choice.rulePackId,gridAreaCode,bilateralAgreementId:agreement.id,validFrom:new Date(String(form.get('validFrom'))).toISOString(),validTo:new Date(String(form.get('validTo'))).toISOString(),source:{bytesBase64:await encoded(file),mimeType,reference:String(form.get('reference')),version:String(form.get('version'))},...(issuerReceipt?{issuerReceipt}: {})})}))
  if(result.status==='held'){setFeedback(missing(result.missing??[]));return}await load(result.artifactId);window.history.replaceState(null,'',`?artifactId=${encodeURIComponent(result.artifactId)}`);setFeedback('Originalet är arkiverat och inväntar en separat granskare.')
 })}
 async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{if(!artifact)throw Error('Öppna ett underlag först.');const result=await body(await fetch(`/api/ediel/bilateral-prodat-sources/${artifact.artifactId}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceHash:artifact.sourceHash,scopeHash:artifact.scopeHash,decision:String(form.get('decision')),reason:String(form.get('reason'))})}));await load(artifact.artifactId);setFeedback(result.status==='authorized'?'Profilen är källkvalificerad med aktuellt mandat. Varje faktisk affärshändelse prövas separat.':result.status==='rejected'?'Underlaget har avslagits.':missing(result.missing??[]))})}
 return <div className="space-y-8" aria-busy={busy}><p role="status" aria-live="polite">{feedback}</p>
  {canArchive&&<section aria-labelledby="archive-title"><h2 id="archive-title" className="text-xl font-semibold">Arkivera bilateralt profilunderlag</h2><p>Originalet måste ange förfarandet, parterna, nätområdet, giltighetstiden och den valda anvisningen.</p><form onSubmit={archive} className="mt-3 space-y-4">
   <label className="block">Vald anvisning<select name="pack" required className={control}><option value="">Välj anvisning</option>{choices.map(c=><option key={c.rulePackId} value={c.rulePackId}>{c.label}</option>)}</select></label>
   <label className="block">Dokumenterad överenskommelse<select name="agreement" required className={control}><option value="">Välj bolagets överenskommelse</option>{agreements.map(a=><option key={a.id} value={a.id}>{a.capability_code.endsWith('normal_start_h')?'Bilateralt H-startförfarande':a.capability_code.endsWith('own_end_h')?'Bilateralt H-slutförfarande':'Bilateralt LK-förfarande'} · {a.environment==='test'?'Test':'Produktion'} · {a.source_reference}</option>)}</select></label>
   <label className="block">Nätområde<select name="gridArea" required className={control}><option value="">Välj eget nätområde</option>{gridAreas.map(area=><option key={area} value={area}>{area}</option>)}</select></label>
   <label className="block">Gäller från<input type="datetime-local" name="validFrom" required className={control}/></label><label className="block">Gäller till<input type="datetime-local" name="validTo" required className={control}/></label>
   <label className="block">Originalunderlag<input type="file" name="source" required accept="application/pdf,text/plain,application/json,.pdf,.txt,.json" className={control}/><span>Högst 8 MB.</span></label>
   <label className="block">Underlagets beteckning enligt överenskommelsen<input name="reference" required maxLength={2000} className={control}/></label><label className="block">Version<input name="version" required maxLength={200} className={control}/></label>
   <label className="block">Utfärdarens signerade intyg<input type="file" name="issuer" accept="application/json,.json" className={control}/><span>Saknat eller obehörigt intyg medför att profilen hålls för komplettering.</span></label>
   <button className={button} disabled={busy||!choices.length||!agreements.length}>Arkivera original</button>
  </form></section>}
  <section aria-labelledby="review-title"><h2 id="review-title" className="text-xl font-semibold">Öppna och granska original</h2><form onSubmit={event=>{event.preventDefault();void act(()=>load(artifactId))}} className="mt-3 space-y-3"><label className="block">Underlagsreferens<input required value={artifactId} onChange={event=>{setArtifactId(event.target.value);setArtifact(null)}} className={control}/></label><button className={button} disabled={busy}>Öppna underlag</button></form>
   {artifact&&<div className="mt-4 space-y-3"><dl><dt>Status</dt><dd>{artifact.status==='authorized'?'Källkvalificerad profil':artifact.status==='held'?'Behöver kompletteras':artifact.status==='rejected'?'Avslaget':'Arkiverat, väntar på granskning'}</dd><dt>Nätområde</dt><dd>{artifact.scope.gridArea}</dd><dt>Giltighet</dt><dd>{artifact.scope.validFrom} – {artifact.scope.validTo}</dd><dt>Vald anvisning</dt><dd>{artifact.scope.sourceVersion}</dd><dt>Original</dt><dd>{artifact.sourceReference} · {artifact.sourceVersion} · {artifact.byteLength} byte</dd><dt>Kontrollsumma för originalet</dt><dd className="break-all font-mono text-sm">{artifact.sourceHash}</dd></dl><p>{missing(artifact.missing)}</p><a className="inline-block text-blue-700 underline" href={`/api/ediel/bilateral-prodat-sources/${artifact.artifactId}/source`}>Ladda ned arkiverat original</a><p><a className="text-blue-700 underline" href={`?artifactId=${artifact.artifactId}`}>Länk för annan granskare</a></p>
    {canReview&&<form onSubmit={review} className="space-y-3"><p>Kontrollera original, utfärdarintyg, förfarande, anvisning, parter och nätområde. Uppladdaren får inte godkänna sitt eget original.</p><label className="block">Beslut<select name="decision" className={control}><option value="hold">Begär komplettering</option><option value="approve">Godkänn styrkt bilateral profil</option><option value="reject">Avslå</option></select></label><label className="block">Motivering<textarea name="reason" required maxLength={4000} className={control}/></label><button className={button} disabled={busy}>Registrera granskning</button></form>}
   </div>}
  </section>
 </div>
}
