import {createHash} from 'node:crypto'
import {supabaseService} from '@/lib/supabase/service'
import {REQUESTED_CHANGE_SOURCE_MAX_BYTES,type RequestedChangeReviewCommand,requestedChangeReviewPayload} from './requestedChangeIntake'

/** Selectors and original document bytes only. Customer/party changes, legal
 * counterparties and receipt authority are derived from protected native rows. */
export type BilateralCustomerSourceSubmission={sourceMessageId:string;agreementId:string;supplyPeriodId:string;contractId:string;source:{bytesBase64:string;mimeType:'application/pdf';reference:string;version:string};issuerReceipt?:{keyId:string;representationId:string;payloadBase64:string;signatureHex:string}}
export type ArchivedBilateralCustomerSource={status:'archived';artifactId:string;sourceHash:string;claimsHash:string;missing:string[]}
export type BilateralCustomerSourceArtifact={artifactId:string;sourceMessageId:string;agreementId:string;supplyPeriodId:string;contractId:string;effectiveAt:string;sourceReference:string;sourceVersion:string;sourceHash:string;claimsHash:string;mimeType:'application/pdf';byteLength:number;status:'archived'|'held'|'rejected'|'authorized';missing:string[]}
export type BilateralCustomerSourceReviewResult={status:'authorized';artifactId:string;sourceMessageId:string}|{status:'held'|'rejected';artifactId:string;missing:string[]}
type Scope={companyId:string;actorUserId:string;artifactId:string}
type Rpc=(name:string,params:Record<string,unknown>)=>PromiseLike<{data:unknown;error:unknown}>
const rpc=()=>supabaseService.rpc.bind(supabaseService) as unknown as Rpc
const record=(v:unknown):Record<string,unknown>|null=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:null
function requireResult(data:unknown,statuses:string[]){const r=record(data);if(!r||!statuses.includes(String(r.status))||typeof r.artifactId!=='string')throw Error('bilateral_customer_source_result_invalid');return r}
export async function archiveBilateralCustomerSource(input:BilateralCustomerSourceSubmission&{companyId:string;actorUserId:string}):Promise<ArchivedBilateralCustomerSource>{
 const bytes=Buffer.from(input.source.bytesBase64,'base64')
 if(!bytes.length||bytes.length>REQUESTED_CHANGE_SOURCE_MAX_BYTES||bytes.toString('base64')!==input.source.bytesBase64||!bytes.subarray(0,5).equals(Buffer.from('%PDF-')))throw Error('bilateral_customer_source_bytes_invalid')
 const{companyId,actorUserId,...submission}=input
 const{data,error}=await rpc()('ediel_archive_bilateral_customer_source_v1',{p_company_id:companyId,p_actor_user_id:actorUserId,p_submission:submission});if(error)throw error
 const r=requireResult(data,['archived']);if(!/^[a-f0-9]{64}$/.test(String(r.sourceHash))||!/^[a-f0-9]{64}$/.test(String(r.claimsHash))||!Array.isArray(r.missing))throw Error('bilateral_customer_source_archive_result_invalid');return r as unknown as ArchivedBilateralCustomerSource
}
async function read(input:Scope,includeBytes:boolean){const{data,error}=await rpc()('ediel_read_bilateral_customer_source_v1',{p_company_id:input.companyId,p_actor_user_id:input.actorUserId,p_artifact_id:input.artifactId,p_include_bytes:includeBytes});if(error)throw error;const r=requireResult(data,['archived','held','rejected','authorized']);if(r.artifactId!==input.artifactId)throw Error('bilateral_customer_source_scope_invalid');return r}
export async function readBilateralCustomerSourceArtifact(input:Scope):Promise<BilateralCustomerSourceArtifact>{const r=await read(input,false);if('bytesBase64'in r||typeof r.sourceMessageId!=='string'||typeof r.sourceHash!=='string'||typeof r.claimsHash!=='string'||typeof r.byteLength!=='number'||!Array.isArray(r.missing))throw Error('bilateral_customer_source_metadata_invalid');return r as unknown as BilateralCustomerSourceArtifact}
export async function readBilateralCustomerSourceBytes(input:Scope):Promise<{mimeType:'application/pdf';bytes:Uint8Array;sourceHash:string}>{const r=await read(input,true);if(typeof r.bytesBase64!=='string'||r.mimeType!=='application/pdf'||typeof r.sourceHash!=='string')throw Error('bilateral_customer_source_bytes_invalid');const bytes=Buffer.from(r.bytesBase64,'base64');if(!bytes.length||bytes.length!==r.byteLength||bytes.length>REQUESTED_CHANGE_SOURCE_MAX_BYTES||createHash('sha256').update(bytes).digest('hex')!==r.sourceHash)throw Error('bilateral_customer_source_bytes_invalid');return{mimeType:'application/pdf',bytes,sourceHash:r.sourceHash}}
export async function reviewBilateralCustomerSourceArtifact(input:Scope&RequestedChangeReviewCommand):Promise<BilateralCustomerSourceReviewResult>{const{companyId,actorUserId,artifactId,...review}=input;const{data,error}=await rpc()('ediel_review_bilateral_customer_source_v1',{p_company_id:companyId,p_actor_user_id:actorUserId,p_artifact_id:artifactId,p_review:requestedChangeReviewPayload(review)});if(error)throw error;const r=requireResult(data,['authorized','held','rejected']);if(r.artifactId!==artifactId||r.status==='authorized'&&typeof r.sourceMessageId!=='string'||r.status!=='authorized'&&!Array.isArray(r.missing))throw Error('bilateral_customer_source_review_result_invalid');return r as unknown as BilateralCustomerSourceReviewResult}
