import {createHash} from 'node:crypto'
import {supabaseService} from '@/lib/supabase/service'
import type {RequestedChangeReviewCommand} from './requestedChangeIntake'
export const REQUESTED_CUSTOMER_CHANGE_MAX_SOURCE_BYTES=8*1024*1024
export const REQUESTED_CUSTOMER_CHANGE_MAX_RAW_BYTES=1024*1024
export type RequestedCustomerChangeSubmission={environment:'test'|'production';agreementId:string;supplyPeriodId:string;contractId:string;rawPayload:string;source:{bytesBase64:string;mimeType:'application/pdf';reference:string;version:string};issuerReceipt?:{keyId:string;representationId:string;payloadBase64:string;signatureHex:string}}
export type RequestedCustomerChangeArchive={status:'archived';artifactId:string;sourceHash:string;claimsHash:string;missing:string[]}
export type RequestedCustomerChangeArtifact={artifactId:string;agreementId:string;supplyPeriodId:string;contractId:string;eventId:string|null;sourceReference:string;sourceVersion:string;sourceHash:string;claimsHash:string;mimeType:'application/pdf';byteLength:number;status:'archived'|'held'|'rejected'|'authorized';missing:string[]}
export type RequestedCustomerChangeReviewResult={status:'authorized';artifactId:string;eventId:string}|{status:'held'|'rejected';artifactId:string;missing:string[]}
export type RequestedCustomerChangeScope={companyId:string;actorUserId:string;artifactId:string}
type Rpc=(name:string,params:Record<string,unknown>)=>PromiseLike<{data:unknown;error:unknown}>
const rpc=()=>supabaseService.rpc.bind(supabaseService) as unknown as Rpc
function result(data:unknown,statuses:string[],artifactId?:string):Record<string,unknown>{if(!data||typeof data!=='object'||Array.isArray(data))throw Error('requested_customer_change_result_invalid');const r=data as Record<string,unknown>;if(!statuses.includes(String(r.status))||typeof r.artifactId!=='string'||artifactId&&r.artifactId!==artifactId)throw Error('requested_customer_change_scope_invalid');return r}
export async function archiveRequestedCustomerChangeSource(input:RequestedCustomerChangeSubmission&{companyId:string;actorUserId:string}):Promise<RequestedCustomerChangeArchive>{
 if(typeof input.rawPayload!=='string'||!input.rawPayload.length||Buffer.byteLength(input.rawPayload,'utf8')>REQUESTED_CUSTOMER_CHANGE_MAX_RAW_BYTES)throw Error('requested_customer_change_raw_invalid')
 const bytes=Buffer.from(input.source.bytesBase64,'base64');if(!bytes.length||bytes.length>REQUESTED_CUSTOMER_CHANGE_MAX_SOURCE_BYTES||bytes.toString('base64')!==input.source.bytesBase64||!bytes.subarray(0,5).equals(Buffer.from('%PDF-')))throw Error('requested_customer_change_bytes_invalid')
 const{companyId,actorUserId,...submission}=input,{data,error}=await rpc()('ediel_archive_requested_customer_change_v1',{p_company_id:companyId,p_actor_user_id:actorUserId,p_submission:submission});if(error)throw error
 const r=result(data,['archived']);if(!/^[a-f0-9]{64}$/.test(String(r.sourceHash))||!/^[a-f0-9]{64}$/.test(String(r.claimsHash))||!Array.isArray(r.missing))throw Error('requested_customer_change_archive_invalid');return r as unknown as RequestedCustomerChangeArchive
}
async function read(input:RequestedCustomerChangeScope,includeBytes:boolean){const{data,error}=await rpc()('ediel_read_requested_customer_change_v1',{p_company_id:input.companyId,p_actor_user_id:input.actorUserId,p_artifact_id:input.artifactId,p_include_bytes:includeBytes});if(error)throw error;return result(data,['archived','held','rejected','authorized'],input.artifactId)}
export async function readRequestedCustomerChangeSourceArtifact(input:RequestedCustomerChangeScope):Promise<RequestedCustomerChangeArtifact>{const r=await read(input,false);if('bytesBase64'in r||'rawPayload'in r||'claims'in r||typeof r.sourceHash!=='string'||typeof r.claimsHash!=='string'||typeof r.byteLength!=='number'||!Array.isArray(r.missing))throw Error('requested_customer_change_metadata_invalid');return r as unknown as RequestedCustomerChangeArtifact}
export async function readRequestedCustomerChangeSourceBytes(input:RequestedCustomerChangeScope){const r=await read(input,true);if(typeof r.bytesBase64!=='string'||typeof r.sourceHash!=='string'||r.mimeType!=='application/pdf')throw Error('requested_customer_change_bytes_invalid');const bytes=Buffer.from(r.bytesBase64,'base64');if(!bytes.length||bytes.length>REQUESTED_CUSTOMER_CHANGE_MAX_SOURCE_BYTES||bytes.length!==r.byteLength||bytes.toString('base64')!==r.bytesBase64||createHash('sha256').update(bytes).digest('hex')!==r.sourceHash)throw Error('requested_customer_change_bytes_invalid');return {bytes:new Uint8Array(bytes),mimeType:'application/pdf' as const,sourceHash:r.sourceHash}}
export async function reviewRequestedCustomerChangeSourceArtifact(input:RequestedCustomerChangeScope&RequestedChangeReviewCommand):Promise<RequestedCustomerChangeReviewResult>{const{companyId,actorUserId,artifactId,...review}=input,{data,error}=await rpc()('ediel_review_requested_customer_change_v1',{p_company_id:companyId,p_actor_user_id:actorUserId,p_artifact_id:artifactId,p_review:review});if(error)throw error;const r=result(data,['authorized','held','rejected'],artifactId);if(r.status==='authorized'&&typeof r.eventId!=='string'||r.status!=='authorized'&&!Array.isArray(r.missing))throw Error('requested_customer_change_review_invalid');return r as unknown as RequestedCustomerChangeReviewResult}
export async function readRequestedCustomerChangeQueueSource(input:RequestedCustomerChangeScope):Promise<{status:'authorized';artifactId:string;eventId:string}|{status:'held';artifactId:string;missing:string[]}>{const{data,error}=await rpc()('ediel_requested_customer_change_queue_basis_v1',{p_company_id:input.companyId,p_actor_user_id:input.actorUserId,p_artifact_id:input.artifactId});if(error)throw error;const r=result(data,['authorized','held'],input.artifactId);if(r.status==='authorized'&&typeof r.eventId!=='string'||r.status==='held'&&!Array.isArray(r.missing))throw Error('requested_customer_change_queue_source_invalid');return r as unknown as {status:'authorized';artifactId:string;eventId:string}|{status:'held';artifactId:string;missing:string[]}}
