import {it,expect,vi,beforeEach} from 'vitest'
vi.mock('@/lib/customer-contracts/documents',()=>({}))
type FixtureCommand={power_of_attorney:{legal_text_version_id:string|null;status:string};legal:{acceptance_snapshot:{legal_versions:unknown[]}}}
type FixtureQuery={select:()=>FixtureQuery;eq:()=>FixtureQuery;single:()=>Promise<{data:{id:string;customer_number:string};error:null}>}
const m=vi.hoisted(()=>({command:null as FixtureCommand|null}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:async(name:string,args:{p_command:FixtureCommand})=>{expect(name).toBe('canonical_onboard_customer_graph');m.command=args.p_command;return{data:{ok:true,code:'customer_onboarding_committed',operation_id:'operation',customer_id:'customer',customer_number:'CUS-0001',created_new_customer:true,power_of_attorney_id:'poa',site_id:null,metering_point_id:null,contract_id:null},error:null}},from:()=>{const b:FixtureQuery={select:()=>b,eq:()=>b,single:async()=>({data:{id:'customer',customer_number:'CUS-0001'},error:null})};return b}}}))
import {onboardCanonicalWebsiteCustomerGraph} from '@/lib/website/customerApplicationOnboarding'
import {normalizeStructuredPoa,validateStructuredPoaForExternalSendability} from '@/lib/website/customerApplicationSchemas'
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', doc='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', different='dddddddd-dddd-4ddd-8ddd-dddddddddddd'
function input(version:string|null=doc):Parameters<typeof onboardCanonicalWebsiteCustomerGraph>[0]{return{client:{id,company_id:id,scopes:[]},body:{customer:{customer_type:'private',first_name:'Synthetic',last_name:'Signer',personal_number:'199001011234'},consents:{power_of_attorney:true}},rawBody:{},externalCustomerId:'synthetic-ref',applicationRowId:id,applicationNumber:'APP-0001',publicOffer:{id,canonical_offer_reference:'offer-synthetic',price_plan_id:id,price_plan_version_id:id,contract_type:'variable_monthly',energy_direction:'consumption',legal_bundle_version_id:id},offerReference:'offer-synthetic',websiteQuote:null,readiness:{status:'ready',priceArea:'SE3',requestedStartDate:'2026-11-01',missingFields:[],blockingReasons:[]},legalVersions:[{id:doc,type:'power_of_attorney',module_key:'power_of_attorney',version:'v1',status:'published'}],structuredPoa:{accepted:true,scope:['supplier_switch'],signerName:'Synthetic Signer',signerIdentityNumber:'199001011234',method:'website_acceptance',textVersionId:version},agreementAcceptedAt:'2026-10-07T00:00:00Z',idempotencyKey:'synthetic-poa-key'} as unknown as Parameters<typeof onboardCanonicalWebsiteCustomerGraph>[0]}
beforeEach(()=>{m.command=null})
it('actual Website builder plus native RPC wrapper writes exact canonical document ID into legacy FK column',async()=>{await onboardCanonicalWebsiteCustomerGraph(input());expect(m.command!.power_of_attorney.legal_text_version_id).toBe(doc);expect(m.command!.power_of_attorney).not.toHaveProperty('legal_bundle_version_document_id');expect(m.command!.power_of_attorney.status).toBe('signed')})
it('actual Website builder accepts caller POA version differing from accepted legal document without validation',async()=>{await onboardCanonicalWebsiteCustomerGraph(input(different));expect(m.command!.power_of_attorney.legal_text_version_id).toBe(different);expect(m.command!.legal.acceptance_snapshot.legal_versions).toEqual(expect.arrayContaining([expect.objectContaining({id:doc})]))})
it('initial normalization and structured validation also accepts different UUID as sendable',()=>{const poa=normalizeStructuredPoa({powerOfAttorney:{accepted:true,scope:['supplier_switch'],signerName:'Synthetic Signer',signerIdentityNumber:'199001011234',method:'website_acceptance',textVersionId:different}} as Parameters<typeof normalizeStructuredPoa>[0]);expect(validateStructuredPoaForExternalSendability(poa)).toBe(null);expect(poa?.textVersionId).toBe(different)})
