// Explicit disposable external registry-issuer competence boundary. Actual
// company/actor/original/archive/independent-review producers remain unmocked.
import {createHash,createHmac,randomUUID} from 'node:crypto'
import {createBilateralSourceOperator} from './ediel-bilateral-customer-native-fixture'
import {nativeSql as sql,literal} from './ediel-normal-switch-native-fixture'
import type {createRequestedChangeSupplyFixture} from './ediel-requested-change-native-fixture'
import type {NetworkRegistrySourceSubmission} from '@/lib/ediel/production/networkRegistrySource'
export async function attachNetworkRegistrySourceFixture(f:Awaited<ReturnType<typeof createRequestedChangeSupplyFixture>>){
 const keys=['communication.read','communication.write','communication.send','customers.read','customers.write','contracts.read','contracts.write','ediel.network_registry.review'],uploader=await createBilateralSourceOperator(f.companyId,keys),reviewer=await createBilateralSourceOperator(f.companyId,keys),networkActorId=sql<string>(`SELECT to_jsonb(actor_id) FROM public.platform_actor_identifiers WHERE identifier_type='EdielId' AND identifier_value=${literal(f.receiver)} AND is_verified`),keyId=randomUUID(),representationId=randomUUID(),secret=Buffer.alloc(32,47),competence=createHash('sha256').update('SYNTHETIC NETWORK REGISTRY ISSUER COMPETENCE ONLY').digest('hex')
 sql(`INSERT INTO gridex_network_registry_sources.issuer_keys(id,company_id,environment,network_actor_id,registry_version,legal_authority_reference,legal_authority_hash,receipt_signing_key,valid_from,valid_to) VALUES(${literal(keyId)},${literal(f.companyId)},'test',${literal(networkActorId)},'SYNTHETIC NETWORK ISSUER REGISTRY VERSION1','SYNTHETIC NETWORK ISSUER COMPETENCE ONLY',${literal(competence)},decode('${secret.toString('hex')}','hex'),'2020-01-01','2099-01-01');INSERT INTO gridex_network_registry_sources.representations(id,company_id,environment,issuer_key_id,network_actor_id,legal_authority_reference,legal_authority_hash,valid_from,valid_to) VALUES(${literal(representationId)},${literal(f.companyId)},'test',${literal(keyId)},${literal(networkActorId)},'SYNTHETIC NETWORK LEGAL REPRESENTATION ONLY',${literal(competence)},'2020-01-01','2099-01-01')`)
 const clause={locator:'page1 synthetic dated network registry',quote:'The synthetic competent registry issuer confirms this exact network identity and dated registry version.'},policy={environment:'test' as const,networkActorId,validFrom:new Date(Math.floor((Date.now()-3600000)/60000)*60000).toISOString(),validUntil:new Date(Math.floor((Date.now()+3600000)/60000)*60000).toISOString()}
 function submission(reference:string,bytes:Buffer,version='1',withReceipt=true):NetworkRegistrySourceSubmission{const base={...policy,source:{bytesBase64:bytes.toString('base64'),mimeType:'application/pdf' as const,reference,version}},claims=sql<Record<string,unknown>>(`SELECT gridex_network_registry_sources.claims_v1(${literal(f.companyId)},${literal(base)}::jsonb)`),payload=Buffer.from(JSON.stringify({format:'ediel_network_registry_receipt_v1',receiptId:randomUUID(),claims,sourceHash:createHash('sha256').update(bytes).digest('hex'),sourceReference:reference,sourceVersion:version,registryVersion:'SYNTHETIC NETWORK ISSUER REGISTRY VERSION1',clause,issuedAt:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(Date.now()+7200000).toISOString()}));return {...base,...(withReceipt?{issuerReceipt:{keyId,representationId,payloadBase64:payload.toString('base64'),signatureHex:createHmac('sha256',secret).update(payload).digest('hex')}}:{})}}
 const pdf=(label:string)=>Buffer.from(`%PDF-1.7\nSYNTHETIC ${label}\n${clause.quote}\n%%EOF`)
 return {uploader,reviewer,networkActorId,keyId,representationId,clause,policy,submission,pdf}
}
