// Disposable native producer fixture. All issuer trust configuration is synthetic.
import {createHash,createHmac,randomUUID} from 'node:crypto'
import {expect} from 'vitest'
import {seedNormalSwitchNativeFixture,type NormalSwitchStageNativeFixture,nativeSql as sql,literal} from './ediel-normal-switch-native-fixture'
import {readBilateralProdatGroundScope,type BilateralProdatSubmission} from '@/lib/ediel/production/bilateralProdatProfileIntake'
export async function createBilateralProdatGroundNativeFixture(sourceFixture?:NormalSwitchStageNativeFixture){
 const f=sourceFixture??await seedNormalSwitchNativeFixture({requestedStartDate:'2026-10-15'}),reviewer=randomUUID(),agreement=randomUUID(),keyId=randomUUID(),representationId=randomUUID(),key=Buffer.from('SYNTHETIC bilateral issuer verifier mechanism fixture only')
 sql(`INSERT INTO auth.users(id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,is_sso_user,is_anonymous) VALUES(${literal(reviewer)},'authenticated','authenticated',${literal(`${reviewer}@example.invalid`)},now(),'{}','{}',now(),now(),false,false);
 INSERT INTO public.user_profiles(id,email,full_name,user_status) VALUES(${literal(reviewer)},${literal(`${reviewer}@example.invalid`)},'Synthetic separate bilateral reviewer','active') ON CONFLICT(id) DO UPDATE SET user_status='active';
 INSERT INTO public.company_memberships(company_id,user_id,membership_role,status,accepted_at,metadata,role,is_active,joined_at,role_key) VALUES(${literal(f.companyId)},${literal(reviewer)},'company_admin','active',now(),'{}','company_admin',true,now(),'company_admin');
 INSERT INTO public.user_permissions(user_id,company_id,permission_id,permission_key,effect,is_active,status) SELECT own.actor,${literal(f.companyId)},p.id,p.key,'allow',true,'active' FROM (VALUES(${literal(reviewer)}::uuid)) own(actor) CROSS JOIN public.permissions p WHERE p.key IN('communication.read','communication.write','contracts.read','metering.read','metering.write');
 INSERT INTO public.user_permissions(user_id,company_id,permission_id,permission_key,effect,is_active,status) SELECT ${literal(reviewer)},${literal(f.companyId)},id,key,'allow',true,'active' FROM public.permissions WHERE key='ediel.bilateral_profile.review';`)
 const dso=sql<string>(`SELECT to_jsonb(actor_id) FROM public.platform_actor_identifiers WHERE identifier_type='EdielId' AND identifier_value=${literal(f.receiver)} AND is_verified`)
 sql(`INSERT INTO public.tenant_bilateral_agreements(id,company_id,environment,counterparty_actor_id,capability_code,terms,is_enabled,valid_from,valid_to,source_reference) VALUES(${literal(agreement)},${literal(f.companyId)},'test',${literal(dso)},'PRODAT:BILATERAL:normal_start_h','{"synthetic_fixture_only":true}',true,'2000-01-01','2100-01-01','SYNTHETIC NATIVE LEGAL ORIGINAL');`)
 const rulePackId=sql<string>(`SELECT to_jsonb(pack.id) FROM public.ediel_rule_packs pack WHERE pack.family='PRODAT' AND pack.guide_version='26.A' AND pack.guide_revision='3' AND pack.status IN('active','transition') AND (SELECT count(*) FROM public.ediel_message_profiles p WHERE p.rule_pack_id=pack.id AND p.message_code IN('Z03','Z04') AND p.transaction_subtype='H' AND p.is_enabled)=2`);expect(rulePackId).toMatch(/^[a-f0-9-]{36}$/)
 const selector={environment:'test' as const,kind:'normal_start_h' as const,rulePackId,gridAreaCode:f.gridAreaCode,bilateralAgreementId:agreement,validFrom:'2000-01-02T00:00:00Z',validTo:'2099-01-01T00:00:00Z'},owner={companyId:f.companyId,actorUserId:f.actorUserId}
 const scoped=await readBilateralProdatGroundScope({...owner,...selector});expect(scoped.status,JSON.stringify(scoped)).toBe('scoped')
 const bytes=Buffer.from('%PDF-1.7\nSYNTHETIC test legal original; no real decision\n%%EOF'),sourceHash=createHash('sha256').update(bytes).digest('hex'),submission:BilateralProdatSubmission={...selector,source:{bytesBase64:bytes.toString('base64'),mimeType:'application/pdf',reference:'SYNTHETIC NATIVE LEGAL ORIGINAL',version:'1'}}
 sql(`INSERT INTO gridex_bilateral_prodat.issuer_keys(id,company_id,environment,issuer_code,legal_issuer_reference,legal_authority_source_hash,receipt_signing_key,valid_from,valid_to) VALUES(${literal(keyId)},${literal(f.companyId)},'test','SYNTHETIC','DECLARED VERIFIER BOUNDARY; NOT LEGAL ACCEPTANCE',${literal('a'.repeat(64))},decode(${literal(key.toString('hex'))},'hex'),'2000-01-01','2100-01-01');
 INSERT INTO gridex_bilateral_prodat.issuer_representations(id,company_id,environment,issuer_key_id,legal_actor_id,dso_actor_id,grid_area_code,permitted_kind,bilateral_agreement_id,legal_representation_reference,legal_authority_source_hash,valid_from,valid_to) VALUES(${literal(representationId)},${literal(f.companyId)},'test',${literal(keyId)},${literal(f.actorUserId)},${literal(dso)},${literal(f.gridAreaCode)},'normal_start_h',${literal(agreement)},'SYNTHETIC NON LEGAL REPRESENTATION',${literal('b'.repeat(64))},'2000-01-01','2100-01-01');`)
 const signed=(version='1')=>{const payload=Buffer.from(JSON.stringify({format:'ediel_bilateral_prodat_ground_receipt_v1',issuerCode:'SYNTHETIC',receiptId:randomUUID(),companyId:f.companyId,environment:'test',scope:scoped.scope,sourceHash,sourceReference:submission.source.reference,sourceVersion:version,legalDecisionReference:'SYNTHETIC DECLARED MECHANISM ONLY',issuedAt:new Date(Date.now()-1000).toISOString(),expiresAt:'2100-01-01T00:00:00Z'}));return {...submission,source:{...submission.source,version},issuerReceipt:{keyId,representationId,payloadBase64:payload.toString('base64'),signatureHex:createHmac('sha256',key).update(payload).digest('hex')}}}
 return {...f,...owner,reviewer,agreement,representationId,scoped,bytes,sourceHash,submission,signed}
}