// Actual installed financial producer; only synthetic legal competence and
// public internal pricing inputs cross the declared external fixture boundary.
import {createHash,createHmac,randomUUID} from 'node:crypto'
import {expect} from 'vitest'
import {seedNormalSwitchNativeFixture,nativeSql as sql,literal} from './ediel-normal-switch-native-fixture'
import {createCustomerRecordRetentionNativeUser as user} from './ediel-customer-record-retention-native-fixture'
export async function seedFinanceCopyRetentionNativeFixture(password?:string){
 const f=await seedNormalSwitchNativeFixture({deferOriginal:true})
 const common=['ediel.retention.read','ediel.retention.settlement_copy_evidence'],writer=await user(f.companyId,[...common,'ediel.retention.submit','ediel.retention.review','ediel.retention.purge'],password),reviewer=await user(f.companyId,[...common,'ediel.retention.review'],password),readonly=await user(f.companyId,common,password),grantIssuer=await user(f.companyId,[])
 const portfolio=randomUUID(),plan=randomUUID(),version=randomUUID()
 sql(`INSERT INTO public.portfolios(id,company_id,code,name,created_by) VALUES(${literal(portfolio)},${literal(f.companyId)},${literal('SYN-'+randomUUID())},'SYNTHETIC internal finance input',${literal(writer.id)});INSERT INTO public.price_plans(id,company_id,name,plan_code,pricing_model,created_by) VALUES(${literal(plan)},${literal(f.companyId)},'SYNTHETIC native finance input',${literal('SYN-'+randomUUID())},'portfolio',${literal(writer.id)});INSERT INTO public.price_plan_versions(id,company_id,price_plan_id,version_number,version_label,snapshot_json,content_sha256,created_by) VALUES(${literal(version)},${literal(f.companyId)},${literal(plan)},1,'SYNTHETIC',${literal({portfolio_method:{portfolio_id:portfolio}})}::jsonb,encode(sha256(convert_to((${literal({portfolio_method:{portfolio_id:portfolio}})}::jsonb)::text,'UTF8')),'hex'),${literal(writer.id)});INSERT INTO public.admin_users(user_id,role,is_active) VALUES(${literal(grantIssuer.id)},'platform_superadmin',true)`)
 for(const key of ['create','calculate','review','approve','lock'])expect(sql(`SET ROLE service_role;SELECT to_jsonb(public.gridex_grant_portfolio_settlement_permission(${literal(grantIssuer.id)},${literal(writer.id)},${literal('portfolio_settlement.'+key)},${literal(f.companyId)},${literal(portfolio)},NULL,'SYNTHETIC local delegated native grant boundary'))`)).toMatch(/^[a-f0-9-]{36}$/)
 sql(`DELETE FROM public.admin_users WHERE user_id=${literal(grantIssuer.id)}`)
 expect(sql(`SELECT to_jsonb(EXISTS(SELECT FROM public.admin_users WHERE user_id=${literal(writer.id)} AND is_active))`)).toBe(false)
 const target=sql<string>(`SET ROLE service_role;SELECT to_jsonb(public.gridex_save_portfolio_settlement_draft(${literal(writer.id)},${literal(f.companyId)},${literal(portfolio)},'SE3','2020-01-01',${literal(version)},1000,0,0,0,1000,NULL,1,'manual',${literal('finance-'+randomUUID())}))`)
 for(const action of ['calculate','review','approve','lock'])expect(sql<{status:string}>(`SET ROLE service_role;SELECT public.gridex_transition_portfolio_settlement(${literal(writer.id)},${literal(target)},${literal(action)},'SYNTHETIC real financial owner mechanism')`).status).toBe(({calculate:'calculated',review:'reviewed',approve:'final',lock:'locked'})[action])
 expect(sql(`SELECT to_jsonb(calculation_snapshot_sha256=encode(sha256(convert_to(calculation_snapshot::text,'UTF8')),'hex')) FROM public.portfolio_monthly_settlements WHERE id=${literal(target)}`)).toBe(true)
 const audit=sql<string>(`SELECT to_jsonb(id::text) FROM public.portfolio_settlement_audit_log WHERE company_id=${literal(f.companyId)} AND settlement_id=${literal(target)} AND action='settlement.locked' ORDER BY id DESC LIMIT 1`)
 const issuer=randomUUID(),key=Buffer.from('SYNTHETIC finance competence only '+randomUUID()),legal=Buffer.from('SYNTHETIC competence boundary: no actual legal approval')
 sql(`INSERT INTO gridex_ediel_retention.issuers(id,company_id,legal_reference,legal_evidence,legal_hash,signing_key,valid_from,valid_to) VALUES(${literal(issuer)},${literal(f.companyId)},'SYNTHETIC finance competence only',decode(${literal(legal.toString('hex'))},'hex'),${literal(createHash('sha256').update(legal).digest('hex'))},decode(${literal(key.toString('hex'))},'hex'),now()-interval '1 day',now()+interval '1 day');UPDATE public.customers SET status='archived' WHERE company_id=${literal(f.companyId)};UPDATE public.companies SET status='archived' WHERE id=${literal(f.companyId)}`)
 const policy=(basis:Record<string,unknown>,document:Buffer,extra:Record<string,unknown>={})=>{const payload=Buffer.from(JSON.stringify({format:'ediel_finance_copy_retention_policy_v1',...basis,operation:'redact_finance_copy_body',companyId:f.companyId,documentHash:createHash('sha256').update(document).digest('hex'),issuerLegalReference:'SYNTHETIC finance competence only',legalBasisReference:'SYNTHETIC exact finance class deadline only',journalPurposeReference:'SYNTHETIC separately finite original hash identity purpose',accessRevocationRequired:true,issuedAt:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),retainUntil:new Date(Date.now()-1000).toISOString(),journalRetainUntil:new Date(Date.now()+3600000).toISOString(),...extra}));return {issuerId:issuer,payloadBase64:payload.toString('base64'),signatureHex:createHmac('sha256',key).update(payload).digest('hex')}}
 return {...f,writer,reviewer,readonly,portfolio,version,target,audit,policy}
}
