'use client'
import Link from 'next/link'
import { useActionState, useState } from 'react'
import { prodatRecoveryAction, type RecoveryActionState } from './actions'
import type {RecoveryRecord} from '@/lib/ediel/recovery/operatorWorkspace'

type Choice={id:string;environment:string;label:string}
type Props={originals:Choice[];acks:Choice[];corrections:(Choice&{status:string})[];attempts:{id:string;messageId:string;label:string}[];record:RecoveryRecord|null;operationId:string;initialMessageId:string;initialOriginalId:string;canPrepare:boolean;canQueue:boolean}
const inputClass='mt-1 block w-full min-w-0 rounded border p-2'
const buttonClass='rounded bg-slate-950 px-4 py-2 text-white disabled:opacity-50'
const initial:RecoveryActionState={status:'idle',message:''}
const ackLabel=(status:string)=>({ack_status_held:'Spärrad',ack_status_unproven:'Ej styrkt',ack_originals_qualified:'Kvalificerade ACK-original',ack_source_rejected:'Hela källan avvisad',ack_source_accepted:'Hela källan godkänd',ack_completed_with_rejections:'Slutligt ACK med avvisningar',ack_partially_received:'Delvis mottaget',positive:'Positivt, kvalificerat original',negative:'Negativt, kvalificerat original',pending:'Väntar på kvalificerat ACK',not_required:'Krävs inte enligt kvalificerat underlag','—':'Ej styrkt'}[status]??'Ej styrkt')

export default function RecoveryWorkspace({originals,acks,corrections,attempts,record:initialRecord,operationId,initialMessageId,initialOriginalId,canPrepare,canQueue}:Props) {
  const seed:RecoveryActionState=initialRecord?{status:'read',message:'Det valda beständiga meddelandet är återläst.',record:initialRecord}:initial
  const [state,action,pending]=useActionState(prodatRecoveryAction,seed)
  const [originalId,setOriginal]=useState(initialOriginalId),[raw,setRaw]=useState(''),[readId,setReadId]=useState(initialMessageId)
  const original=originals.find(m=>m.id===originalId), record=state.record
  const selectedCorrection=corrections.find(m=>m.id===(record?.messageId??readId))
  const queueId=record?.originalMessageId?record.messageId:selectedCorrection?.id
  const queueable=record?.originalMessageId?['draft','queued'].includes(record.status):!!selectedCorrection&&['draft','queued'].includes(selectedCorrection.status)
  return <div className="min-w-0 space-y-6">
    <section className="rounded-xl border p-4"><h2 className="text-lg font-semibold">1. Läs original eller sparad rättelse</h2><form action={action} className="mt-3 space-y-3"><input type="hidden" name="action" value="read"/><label className="block">Beständigt meddelande<select required name="messageId" className={inputClass} value={readId} onChange={e=>setReadId(e.target.value)}><option value="">Välj meddelande</option>{originals.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><button disabled={pending||!readId} className={buttonClass}>Återläs status och originalinnehåll</button></form>
    <form action={action} className="mt-4 space-y-3"><input type="hidden" name="action" value="read"/><label className="block">Sparad rättelse<select required name="messageId" className={inputClass} defaultValue={initialMessageId}><option value="">Välj rättelse</option>{corrections.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><button disabled={pending} className={buttonClass}>Återläs rättelse</button></form>
    {record&&<div className="mt-4 min-w-0 space-y-2"><p className="break-words">Miljö: {record.environment==='test'?'Test':'Produktion'} · Status: {record.status}</p><p className="break-words">ACK-underlag: {ackLabel(record.ack.state)} · CONTRL: {ackLabel(record.ack.contrl)} · APERAK: {ackLabel(record.ack.aperak)}</p><p className="break-all">Meddelande: {record.messageId}<br/>Operation: {record.operationId??'saknas'}<br/>Original: {record.originalMessageId??'samma meddelande'}<br/>Payloadhash: {record.payloadHash??'saknas'}</p><Link className="underline" href={`/admin/ediel/prodat-recovery?messageId=${record.messageId}`}>Öppna samma beständiga meddelande efter omladdning</Link>
    <p>Gemensam källprövning vid återläsning: {record.sourceCurrent==='qualified'?'kvalificerad':record.sourceCurrent==='held'?'spärrad':'inget befintligt rättelsekvitto'}.</p>
    {record.contentCurrent?<><label className="block">Återläst innehåll<textarea readOnly className={`${inputClass} h-48 font-mono text-xs`} value={record.rawPayload??''}/></label><button type="button" className="rounded border px-3 py-2" onClick={()=>{setOriginal(record.messageId);setRaw(record.rawPayload??'')}}>Använd återläst innehåll som rättelseunderlag</button></>:<p role="alert">Originalbytes är inte tillgängliga med verifierad hash. Underlaget får inte behandlas som ett aktuellt original.</p>}</div>}
    </section>
    <section className="rounded-xl border p-4"><h2 className="text-lg font-semibold">2. Förbered eget rättelseutkast</h2><p className="mt-2 text-sm">Det faktiska ACK:et avgör rättelsens scope. Kund, anläggning, period och andra affärsfält måste behållas enligt källans kriterier. Nya tekniska meddelandeidentiteter krävs. Om fält 226 saknas och ACK:et styrker det, tilldelar servern en ny egen LI-referens.</p><form action={action} className="mt-3 space-y-3"><input type="hidden" name="action" value="prepare"/><input type="hidden" name="operationId" value={operationId}/><label className="block">Original<select name="originalMessageId" required className={inputClass} value={originalId} onChange={e=>setOriginal(e.target.value)} disabled={!canPrepare}><option value="">Välj original</option>{originals.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><p>Miljön hämtas från valt original: {original?.environment==='test'?'Test':original?.environment==='production'?'Produktion':'välj original'}.</p><label className="block">Faktiskt mottaget ACK<select name="sourceAckMessageId" required className={inputClass} key={originalId} disabled={!canPrepare}><option value="">Välj ACK</option>{acks.filter(m=>m.environment===original?.environment).map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><label className="block">Rättat EDIFACT-innehåll<textarea name="correctedRawPayload" required className={`${inputClass} h-64 font-mono text-xs`} maxLength={262144} value={raw} onChange={e=>setRaw(e.target.value)} disabled={!canPrepare}/></label><button disabled={pending||!canPrepare||!originalId} className={buttonClass}>Pröva källa och spara utkast</button></form>{!canPrepare&&<p className="mt-2 text-sm">Du behöver aktuell skrivbehörighet för att förbereda en rättelse.</p>}<p className="mt-3"><Link className="underline" href={`/admin/ediel/prodat-recovery${originalId?`?originalMessageId=${originalId}`:''}`}>Starta en ny separat rättelseoperation</Link></p></section>
    <section className="rounded-xl border p-4"><h2 className="text-lg font-semibold">3. Köa sparad rättelse</h2><p className="mt-2 text-sm">Källan, mandatet och avsändarens aktuella behörighet prövas igen. Miljö och operationsbindning hämtas från det beständiga utkastet.</p><form action={action} className="mt-3"><input type="hidden" name="action" value="queue"/><input type="hidden" name="messageId" value={queueId??''}/><button disabled={pending||!canQueue||!queueId||!queueable} className={buttonClass}>Pröva och köa vald rättelse</button></form>{!canQueue&&<p className="mt-2 text-sm">Du behöver aktuell sändbehörighet för att köa ett utkast.</p>}</section>
    <section className="rounded-xl border p-4"><h2 className="text-lg font-semibold">Styrkt transportåterförsök</h2><p className="mt-2 text-sm">Återförsöket behåller originalets identitet och innehåll. Servern kräver faktisk negativ leveransbevisning och kontroll av replay innan en ny leveransavsikt köas.</p><form action={action} className="mt-3 space-y-3"><input type="hidden" name="action" value="retry"/><input type="hidden" name="operationId" value={operationId}/><input type="hidden" name="originalMessageId" value={originalId}/><label className="block">Transportförsök för valt original<select name="previousAttemptId" required className={inputClass} key={originalId} disabled={!canPrepare||!canQueue}><option value="">Välj transportförsök</option>{attempts.filter(a=>a.messageId===originalId).map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><button disabled={pending||!canPrepare||!canQueue||!originalId} className={buttonClass}>Pröva bevis och köa återförsök</button></form></section>
    {state.message&&<p role={state.status==='unavailable'||state.status==='held'?'alert':'status'} className="min-w-0 break-words rounded border p-3">{state.message}</p>}
  </div>
}
