'use client'
import {useEffect,useState,type FormEvent} from 'react'
import type {SignedBrpArtifact} from '@/lib/ediel/production/signedBrpDeclarationIntake'
const api='/api/ediel/signed-brp-declarations',field='mt-1 block w-full rounded border border-slate-400 p-2',button='rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50',maximum=10*1024*1024
async function json(response:Response){const result=await response.json();if(!response.ok)throw Error(result.error??result.missing?.join(', ')??'Underlaget kunde inte behandlas.');return result}
async function original(file:File|null){
 if(!file||file.size<1||file.size>maximum)throw Error('Välj ett original på högst 10 MiB.')
 const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let n=0;n<bytes.length;n+=0x8000)binary+=String.fromCharCode(...bytes.subarray(n,n+0x8000))
 return{base64:btoa(binary),hash:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(v=>v.toString(16).padStart(2,'0')).join('')}
}
export default function SignedBrpWorkspace({contracts,initialArtifactId,canArchive,canReview}:{contracts:Array<{id:string;label:string}>;initialArtifactId:string;canArchive:boolean;canReview:boolean}){
 const[contract,setContract]=useState(contracts[0]?.id??''),[environment,setEnvironment]=useState('test'),[ground,setGround]=useState(''),[agency,setAgency]=useState('89'),[agreement,setAgreement]=useState<File|null>(null),[source,setSource]=useState<File|null>(null),[reference,setReference]=useState(''),[version,setVersion]=useState(''),[receipt,setReceipt]=useState('')
 const[artifactId,setArtifactId]=useState(initialArtifactId),[artifact,setArtifact]=useState<SignedBrpArtifact|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[scopeHash,setScopeHash]=useState(''),[decision,setDecision]=useState('hold'),[reason,setReason]=useState(''),[locator,setLocator]=useState(''),[quote,setQuote]=useState(''),[previous,setPrevious]=useState(''),[revocationReason,setRevocationReason]=useState('')
 async function act(work:()=>Promise<void>){setBusy(true);try{await work()}catch(error){setFeedback(error instanceof Error?error.message:'Underlaget kunde inte behandlas.')}finally{setBusy(false)}}
 async function load(id:string){const result=await json(await fetch(`${api}/${encodeURIComponent(id)}`,{cache:'no-store'}));setArtifact(result);setArtifactId(result.artifactId);history.replaceState(null,'',`?artifactId=${encodeURIComponent(result.artifactId)}`)}
 useEffect(()=>{if(!initialArtifactId)return;let current=true;void fetch(`${api}/${encodeURIComponent(initialArtifactId)}`,{cache:'no-store'}).then(json).then(result=>{if(current){setArtifact(result);setArtifactId(result.artifactId)}}).catch(error=>{if(current)setFeedback(error instanceof Error?error.message:'Underlaget kunde inte läsas.')});return()=>{current=false}},[initialArtifactId])
 async function archive(event:FormEvent){event.preventDefault();await act(async()=>{const[a,s]=await Promise.all([original(agreement),original(source)]),issuerReceipt=receipt.trim()?JSON.parse(receipt):undefined,result=await json(await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({environment,contractId:contract,registryGroundId:ground,identityAgency:agency,agreementBase64:a.base64,sourceBase64:s.base64,sourceReference:reference,sourceVersion:version,...(issuerReceipt?{issuerReceipt}:{})})}));await load(result.artifactId);setFeedback(result.issuerQualified?'Originalen är arkiverade och inväntar separat granskning.':'Originalen är arkiverade. Utfärdarens aktuella mandat återstår att styrka.')})}
 async function review(event:FormEvent){event.preventDefault();if(!artifact)return;await act(async()=>{const result=await json(await fetch(`${api}/${artifact.artifactId}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agreementHash:artifact.agreementHash,sourceHash:artifact.sourceHash,claimsHash:artifact.claimsHash,decision,reason,...(locator&&quote?{clause:{locator,quote}}:{}),...(previous?{previousDeclarationId:previous}:{})})}));await load(artifact.artifactId);setFeedback(result.status==='authorized'?'BRP-underlaget är godkänt. Aktuell behörighet och källauktoritet prövas även när uppgiften används.':`Underlaget är ${result.status==='held'?'hållet':'avvisat'}: ${result.missing?.join(', ')??''}`)})}
 return <section className="space-y-6">
 {canArchive&&<form onSubmit={archive} className="space-y-4 rounded border border-slate-300 p-4"><h2 className="text-lg font-semibold">Arkivera original</h2><label className="block">Undertecknat avtal<select aria-label="Undertecknat avtal" className={field} value={contract} onChange={e=>setContract(e.target.value)} required>{contracts.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="block">Miljö<select aria-label="Miljö" className={field} value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="test">Test</option><option value="production">Produktion</option></select></label><label className="block">Nätregistrets underlags-ID<input aria-label="Nätregistrets underlags-ID" className={field} value={ground} onChange={e=>setGround(e.target.value)} required/></label><label className="block">Identitetsbyrå<select aria-label="Identitetsbyrå" className={field} value={agency} onChange={e=>setAgency(e.target.value)}><option value="89">89</option><option value="9">9</option></select></label><label className="block">Undertecknat PDF-original, högst 10 MiB<input aria-label="Undertecknat PDF-original, högst 10 MiB" className={field} type="file" accept="application/pdf,.pdf" onChange={e=>{setAgreement(e.target.files?.[0]??null);setScopeHash('')}} required/></label><label className="block">BRP-källoriginal, högst 10 MiB<input aria-label="BRP-källoriginal, högst 10 MiB" className={field} type="file" onChange={e=>setSource(e.target.files?.[0]??null)} required/></label><label className="block">Källreferens<input aria-label="Källreferens" className={field} value={reference} onChange={e=>setReference(e.target.value)} maxLength={2000} required/></label><label className="block">Källversion<input aria-label="Källversion" className={field} value={version} onChange={e=>setVersion(e.target.value)} maxLength={200} required/></label><button type="button" className={button} disabled={busy} onClick={()=>void act(async()=>{const a=await original(agreement),result=await json(await fetch(`${api}/scope`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({environment,contractId:contract,registryGroundId:ground,identityAgency:agency,agreementHash:a.hash})}));setScopeHash(result.claimsHash);setFeedback('Avtalets och nätregistrets aktuella avgränsning är läst.')})}>Kontrollera avtal och nätregister</button>{scopeHash&&<p className="break-all">Underlagets SHA-256 för utfärdarkvitto: {scopeHash}</p>}<label className="block">Utfärdarkvitto (JSON)<textarea aria-label="Utfärdarkvitto (JSON)" className={field} value={receipt} onChange={e=>setReceipt(e.target.value)} rows={4} maxLength={100000}/></label><button className={button} disabled={busy} type="submit">Arkivera original</button></form>}
 <form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void act(()=>load(artifactId))}}><label className="min-w-0 grow">Arkiverat underlags-ID<input aria-label="Arkiverat underlags-ID" className={field} value={artifactId} onChange={e=>setArtifactId(e.target.value)} required/></label><button className={button} disabled={busy} type="submit">Läs underlag</button></form>
 {artifact&&<div className="space-y-4 rounded border border-slate-300 p-4"><h2 className="text-lg font-semibold">Arkiverat underlag</h2><dl className="space-y-2 break-all"><div><dt>Status</dt><dd>{artifact.status}</dd></div><div><dt>Källreferens och version</dt><dd>{artifact.sourceReference} · {artifact.sourceVersion}</dd></div><div><dt>Avtalsoriginalets SHA-256</dt><dd>{artifact.agreementHash}</dd></div><div><dt>Källoriginalets SHA-256</dt><dd>{artifact.sourceHash}</dd></div><div><dt>Granskningsinnehållets SHA-256</dt><dd>{artifact.claimsHash}</dd></div><div><dt>Återstående underlag</dt><dd>{artifact.missing.join(', ')||'Inga rapporterade luckor.'}</dd></div></dl>{artifact.bytesAvailable&&<p><a className="underline" href={`${api}/${artifact.artifactId}/original?kind=agreement`}>Ladda ned avtalsoriginal</a> · <a className="underline" href={`${api}/${artifact.artifactId}/original?kind=source`}>Ladda ned källoriginal</a></p>}
 {canReview&&<form onSubmit={review} className="space-y-3"><h3 className="font-semibold">Separat granskning</h3><label className="block">Beslut<select aria-label="Beslut" className={field} value={decision} onChange={e=>setDecision(e.target.value)}><option value="hold">Håll för komplettering</option><option value="approve">Godkänn underlaget</option><option value="reject">Avvisa underlaget</option></select></label><label className="block">Skäl<textarea aria-label="Skäl" className={field} value={reason} onChange={e=>setReason(e.target.value)} maxLength={4000} required/></label><label className="block">Klausulens plats i avtalsoriginalet<input aria-label="Klausulens plats i avtalsoriginalet" className={field} value={locator} onChange={e=>setLocator(e.target.value)} maxLength={1000} required={decision==='approve'}/></label><label className="block">Ordagrant BRP-klausulcitat<textarea aria-label="Ordagrant BRP-klausulcitat" className={field} value={quote} onChange={e=>setQuote(e.target.value)} maxLength={10000} required={decision==='approve'}/></label><label className="block">Tidigare BRP-underlags-ID vid rättning<input aria-label="Tidigare BRP-underlags-ID vid rättning" className={field} value={previous} onChange={e=>setPrevious(e.target.value)}/></label><button className={button} disabled={busy} type="submit">Spara granskning</button></form>}
 {canArchive&&<div><label className="block">Skäl för återkallelse<textarea aria-label="Skäl för återkallelse" className={field} value={revocationReason} onChange={e=>setRevocationReason(e.target.value)} maxLength={4000}/></label><button type="button" className={button} disabled={busy||!revocationReason.trim()} onClick={()=>void act(async()=>{await json(await fetch(`${api}/${artifact.artifactId}/revoke`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:revocationReason})}));await load(artifact.artifactId);setFeedback('Källauktoriteten är återkallad. Originalen och granskningen finns kvar.')})}>Återkalla underlaget med angivet skäl</button></div>}</div>}
 <p role="status" aria-live="polite" className="break-words">{feedback}</p></section>
}
