import {createSupabaseServerClient} from '@/lib/supabase/server'
import {z} from 'zod'
const uuid=z.string().uuid(),hash=z.string().regex(/^[a-f0-9]{64}$/)
const result=z.union([z.object({status:z.literal('submitted'),decisionId:uuid,sourceHash:hash,documentHash:hash,retentionClass:z.literal('customer_canonical_personal_fields'),issuerQualified:z.boolean()}),z.object({status:z.enum(['held','approved','rejected']),decisionId:uuid.optional(),reviewId:uuid.optional(),missing:z.array(z.string()).optional()}),z.object({status:z.literal('pseudonymised'),customerId:uuid,sourceHash:hash,pseudonymisedAt:z.string().datetime({offset:true}),replay:z.boolean()})])
async function call(name:string,companyId:string,args:Record<string,unknown>){uuid.parse(companyId);const client=await createSupabaseServerClient(),auth=await client.auth.getUser();if(auth.error||!auth.data.user)throw Error('customer_retention_authenticated_actor_required');const{data,error}=await client.rpc(name,{p_company_id:companyId,p_actor_user_id:auth.data.user.id,...args});if(error)throw error;return data}
export async function submitCustomerRetention(input:{companyId:string;customerId:string;document:Buffer;issuerReceipt:Record<string,unknown>|null}){uuid.parse(input.customerId);if(!Buffer.isBuffer(input.document)||input.document.length<1||input.document.length>1048576)throw Error('customer_retention_document_limit');return result.parse(await call('ediel_submit_customer_retention_v1',input.companyId,{p_customer_id:input.customerId,p_document_base64:input.document.toString('base64'),p_issuer_receipt:input.issuerReceipt}))}
export async function reviewCustomerRetention(input:{companyId:string;decisionId:string;outcome:'approve'|'hold'|'reject';reason:string}){uuid.parse(input.decisionId);z.enum(['approve','hold','reject']).parse(input.outcome);z.string().min(1).max(4000).parse(input.reason);return result.parse(await call('ediel_review_customer_retention_v1',input.companyId,{p_decision_id:input.decisionId,p_outcome:input.outcome,p_reason:input.reason}))}
export async function revokeCustomerRetention(input:{companyId:string;decisionId:string;reason:string}){uuid.parse(input.decisionId);z.string().min(1).max(4000).parse(input.reason);await call('ediel_revoke_customer_retention_v1',input.companyId,{p_decision_id:input.decisionId,p_reason:input.reason})}
export async function pseudonymiseCustomerRetention(input:{companyId:string;decisionId:string}){uuid.parse(input.decisionId);return result.parse(await call('ediel_pseudonymise_customer_retention_v1',input.companyId,{p_decision_id:input.decisionId}))}
