export const FINANCE_COPY_CATALOG = [
 { retentionClass: 'billing_underlay_source_body', label: 'Kvalificerad mätkällkopia för faktureringsunderlag', sourceTable: 'gridex_billing_source.underlay_bindings', bodyColumns: ["source_basis"], permission: 'ediel.retention.billing_source_evidence', idKind: 'uuid' },
 { retentionClass: 'billing_underlay_payload_body', label: 'Underlagets beräknings- och priskopia', sourceTable: 'public.billing_underlays', bodyColumns: ["payload", "pricing_snapshot"], permission: 'ediel.retention.billing_source_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_calculation_body', label: 'Fakturans beräknings- och metadatakopia', sourceTable: 'public.customer_invoices', bodyColumns: ["raw_payload", "metadata", "calculation_snapshot", "portfolio_settlement_snapshot"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_line_body', label: 'Fakturaradens personliga fritext', sourceTable: 'public.customer_invoice_lines', bodyColumns: ["description", "metadata"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_export_item_body', label: 'Fakturautförselns begäran och svar', sourceTable: 'public.invoice_export_items', bodyColumns: ["request_payload", "response_payload", "error_payload", "status_payload", "metadata"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_export_run_body', label: 'Utfall och beredskapskopia för fakturakörning', sourceTable: 'public.invoice_export_runs', bodyColumns: ["readiness_snapshot", "metadata"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_provider_event_body', label: 'Leverantörens fakturahändelse', sourceTable: 'public.invoice_provider_events', bodyColumns: ["payload"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_purchase_event_body', label: 'Leverantörens köpkopia', sourceTable: 'public.invoice_purchase_events', bodyColumns: ["payload"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_document_provider_body', label: 'Leverantörens dokumentmetadata', sourceTable: 'public.invoice_documents', bodyColumns: ["provider_payload"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_dead_letter_body', label: 'Fakturans felkö och fritext', sourceTable: 'public.invoice_dead_letters', bodyColumns: ["payload", "error_message"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'invoice_export_attempt_body', label: 'Svarstext från ett fakturaförsök', sourceTable: 'public.invoice_export_attempts', bodyColumns: ["response_excerpt"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'billing_export_item_body', label: 'Fakturaförberedelsens adress- och adapterkopior', sourceTable: 'public.billing_export_run_items', bodyColumns: ["payload", "invoice_address_snapshot", "site_address_snapshot", "payload_snapshot", "adapter_payload_snapshot"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'partner_export_body', label: 'Partnerutförselns begäran och svarshistorik', sourceTable: 'public.partner_exports', bodyColumns: ["payload", "response_payload", "partner_response_log"], permission: 'ediel.retention.invoice_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'settlement_calculation_body', label: 'Avräkningens beräkningskopia', sourceTable: 'public.portfolio_monthly_settlements', bodyColumns: ["calculation_snapshot"], permission: 'ediel.retention.settlement_copy_evidence', idKind: 'uuid' },
 { retentionClass: 'settlement_audit_body', label: 'Avräkningens historiska journalbody', sourceTable: 'public.portfolio_settlement_audit_log', bodyColumns: ["old_values", "new_values", "reason"], permission: 'ediel.retention.settlement_copy_evidence', idKind: 'integer' },
 { retentionClass: 'settlement_invoice_binding_body', label: 'Avräkningens sparade fakturabindning', sourceTable: 'public.portfolio_settlement_invoice_bindings', bodyColumns: ["settlement_snapshot"], permission: 'ediel.retention.settlement_copy_evidence', idKind: 'uuid' },
] as const
export const FINANCE_COPY_CLASSES = FINANCE_COPY_CATALOG.map(row=>row.retentionClass) as [typeof FINANCE_COPY_CATALOG[number]['retentionClass'], ...typeof FINANCE_COPY_CATALOG[number]['retentionClass'][]]
export type FinanceCopyClass = typeof FINANCE_COPY_CATALOG[number]['retentionClass']
