'use client'
import {useEffect,useState,type FormEvent} from 'react'
import Link from 'next/link'
export type RescissionChoice={periodId:string;rulePackId:string;environment:'test'|'production';label:string}
type Artifact={artifactId:string;status:'archived'|'held'|'rejected'|'authorized';mandateId?:string;sourceHash:string;scopeHash:string;sourceReference:string;sourceVersion:string;byteLength:number|null;missing:string[];scope:{effectiveAt:string;externalPoint:string;environment:string}}
const control='mt-1 w-full rounded border border-gray-400 bg-white p-2 text-black disabled:bg-gray-100'
const button='rounded bg-blue-700 px-4 py-2 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-50'
async function originalBase64(file:File){if(!file.size||file.size>8*1024*1024)throw Error('Välj ett originalunderlag på högst 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let value='';for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(value)}
async function responseBody(response:Response){const result=await response.json();if(!response.ok&&result.status!=='held')throw Error(result.error??'Åtgärden kunde inte genomföras.');return result}
function missingText(missing:string[]){if(missing.some(m=>/cutoff/.test(m)))return 'Tidsgränsen för den begärda hävningsdagen har passerat.';if(missing.some(m=>/issuer|legal.*prerequisites/.test(m)))return 'Ett autentiskt rättsligt intyg från behörig utfärdare och styrkta rättsliga förutsättningar saknas.';if(missing.some(m=>/separate.*review/.test(m)))return 'En annan behörig granskare måste granska originalet.';if(missing.length)return 'Underlaget behöver kompletteras. Kontrollera originalet, egen leverans, avtal, källprofil och aktuella behörigheter.';return ''}
export default function SupplyRescissionWorkspace({choices,initialArtifactId,canArchive,canReview,canQueue}:{choices:RescissionChoice[];initialArtifactId:string;canArchive:boolean;canReview:boolean;canQueue:boolean}){
 const [artifactId,setArtifactId]=useState(initialArtifactId),[artifact,setArtifact]=useState<Artifact|null>(null),[selected,setSelected]=useState(choices[0]?`${choices[0].periodId}:${choices[0].rulePackId}`:''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('')
 const choice=choices.find(c=>`${c.periodId}:${c.rulePackId}`===selected)
 async function load(id:string){const result=await responseBody(await fetch(`/api/ediel/supply-rescission-sources/${encodeURIComponent(id)}`,{cache:'no-store'}));setArtifact(result);setArtifactId(id);return result as Artifact}
 useEffect(()=>{let current=true;if(initialArtifactId)fetch(`/api/ediel/supply-rescission-sources/${encodeURIComponent(initialArtifactId)}`,{cache:'no-store'}).then(responseBody).then(result=>{if(current)setArtifact(result)}).catch(error=>{if(current)setFeedback(error.message)});return()=>{current=false}},[initialArtifactId])
 async function act(work:()=>Promise<void>){setBusy(true);setFeedback('');try{await work()}catch(error){setFeedback(error instanceof Error?error.message:'Åtgärden kunde inte genomföras.')}finally{setBusy(false)}}
 function selector(form:FormData){if(!choice)throw Error('Välj en egen leveransperiod.');const value=String(form.get('effectiveAt'));if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw Error('Ange hävningstid i svensk standardtid, UTC+01.');return{environment:choice.environment,supplyPeriodId:choice.periodId,rulePackId:choice.rulePackId,effectiveAt:new Date(`${value}:00+01:00`).toISOString()}}
 async function archive(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{
  const input=selector(form),scope=await responseBody(await fetch('/api/ediel/supply-rescission-sources/scope',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}));if(scope.status==='held'){setFeedback(missingText(scope.missing??[]));return}
  const file=form.get('source');if(!(file instanceof File))throw Error('Välj originalunderlaget.');const mimeType=file.type||(/\.pdf$/i.test(file.name)?'application/pdf':'text/plain');if(!['application/pdf','text/plain'].includes(mimeType))throw Error('Underlaget måste vara PDF eller text.');
  const receiptFile=form.get('issuerReceipt');let issuerReceipt:unknown;if(receiptFile instanceof File&&receiptFile.size){if(receiptFile.size>128*1024)throw Error('Utfärdarintyget är för stort.');issuerReceipt=JSON.parse(await receiptFile.text())}
  const result=await responseBody(await fetch('/api/ediel/supply-rescission-sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,source:{bytesBase64:await originalBase64(file),mimeType,reference:String(form.get('reference')),version:String(form.get('version'))},...(issuerReceipt?{issuerReceipt}:{})})}));if(result.status==='held'){setFeedback(missingText(result.missing??[]));return}
  await load(result.artifactId);window.history.replaceState(null,'',`?artifactId=${encodeURIComponent(result.artifactId)}`);setFeedback('Originalunderlaget är arkiverat och väntar på oberoende granskning.')
 })}
 async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{if(!artifact)throw Error('Öppna ett underlag först.');const quote=String(form.get('quote')),locator=String(form.get('locator'));const result=await responseBody(await fetch(`/api/ediel/supply-rescission-sources/${artifact.artifactId}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceHash:artifact.sourceHash,scopeHash:artifact.scopeHash,decision:String(form.get('decision')),reason:String(form.get('reason')),...(quote?{sourceClauseQuote:quote}:{}),...(locator?{sourceClauseLocator:locator}:{})})}));await load(artifact.artifactId);setFeedback(result.status==='authorized'?'Underlaget är godkänt med aktuellt rättsligt mandat.':result.status==='rejected'?'Underlaget har avslagits.':missingText(result.missing??[]))})}
 return <div className="space-y-8" aria-busy={busy}><p role="status" aria-live="polite" className="break-words">{feedback}</p>
  {canArchive&&<section aria-labelledby="archive-title"><h2 id="archive-title" className="text-xl font-semibold">Arkivera rättsligt original</h2><form onSubmit={archive} className="mt-3 space-y-4">
   <label className="block">Egen anläggning och leveransperiod<select aria-label="Egen anläggning och leveransperiod" required value={selected} onChange={e=>setSelected(e.target.value)} className={control}><option value="">Välj leveransperiod</option>{choices.map(c=><option key={`${c.periodId}:${c.rulePackId}`} value={`${c.periodId}:${c.rulePackId}`}>{c.label}</option>)}</select></label>
   <label className="block">Begärd hävningstid, svensk standardtid (UTC+01)<input aria-label="Begärd hävningstid, svensk standardtid (UTC+01)" type="datetime-local" name="effectiveAt" required step={60} className={control}/></label>
   <label className="block">Rättsligt originalunderlag<input aria-label="Rättsligt originalunderlag" type="file" name="source" required accept="application/pdf,text/plain,.pdf,.txt" className={control}/><span>Högst 8 MB.</span></label>
   <label className="block">Originalets beteckning<input aria-label="Originalets beteckning" name="reference" required maxLength={2000} className={control}/></label><label className="block">Version<input aria-label="Version" name="version" required maxLength={200} className={control}/></label>
   <label className="block">Utfärdarens intyg, om tillgängligt<input aria-label="Utfärdarens intyg, om tillgängligt" type="file" name="issuerReceipt" accept="application/json,.json" className={control}/><span>Originalet kan arkiveras utan intyg. Ett autentiskt intyg krävs för godkännande.</span></label>
   <button className={button} disabled={busy||!choice}>Arkivera underlag</button>
  </form></section>}
  <section aria-labelledby="review-title"><h2 id="review-title" className="text-xl font-semibold">Öppna och granska underlag</h2><form className="mt-3 flex flex-col gap-3 sm:flex-row" onSubmit={event=>{event.preventDefault();void act(()=>load(artifactId).then(()=>undefined))}}><label className="grow">Underlagsreferens<input aria-label="Underlagsreferens" value={artifactId} onChange={e=>{setArtifactId(e.target.value);setArtifact(null)}} required className={control}/></label><button className={button} disabled={busy}>Öppna underlag</button></form>
   {artifact&&<div className="mt-4 space-y-4"><dl className="grid gap-2 break-words"><dt>Status</dt><dd>{artifact.status==='authorized'?'Godkänt':artifact.status==='rejected'?'Avslaget':artifact.status==='held'?'Behöver kompletteras':'Arkiverat, väntar på granskning'}</dd><dt>Original</dt><dd>{artifact.sourceReference} · version {artifact.sourceVersion} · {artifact.byteLength??'ej tillgängligt'} byte</dd><dt>Anläggning</dt><dd>{artifact.scope.externalPoint}</dd><dt>Begärd hävningstid</dt><dd>{artifact.scope.effectiveAt}</dd></dl><p>{missingText(artifact.missing)}</p>
    <a href={`/api/ediel/supply-rescission-sources/${artifact.artifactId}/source`} className="inline-block text-blue-700 underline">Ladda ned arkiverat original</a><p><Link href={`?artifactId=${artifact.artifactId}`} className="text-blue-700 underline">Länk till underlaget för annan granskare</Link></p>
    {canReview&&<form onSubmit={review} className="space-y-3"><p>Granska originalets rättsliga stöd och den egna leveransen. Uppladdaren får inte godkänna sitt eget underlag.</p><label className="block">Beslut<select aria-label="Beslut" name="decision" className={control}><option value="hold">Begär komplettering</option><option value="approve">Godkänn styrkt underlag</option><option value="reject">Avslå</option></select></label><label className="block">Motivering<textarea aria-label="Motivering" name="reason" required maxLength={2000} className={control}/></label><label className="block">Var finns det rättsliga stödet?<input aria-label="Var finns det rättsliga stödet?" name="locator" maxLength={2000} className={control}/></label><label className="block">Ordagrant utdrag ur originalet<textarea aria-label="Ordagrant utdrag ur originalet" name="quote" maxLength={2000} className={control}/></label><button className={button} disabled={busy}>Registrera granskning</button></form>}
    {canQueue&&artifact.status==='authorized'&&artifact.mandateId&&<button className={button} disabled={busy} onClick={()=>void act(async()=>{const result=await responseBody(await fetch(`/api/ediel/supply-rescission-sources/${artifact.artifactId}/queue`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}));setFeedback(result.status==='held'?missingText(result.missing??[]):result.status==='queued'?'H-begäran är köad och väntar på transport. Leveransen är ännu inte avslutad.':'H-begäran finns redan.');await load(artifact.artifactId)})}>Köa H-begäran</button>}
   </div>}
  </section>
 </div>
}
