'use client'
import {useState,type FormEvent} from 'react'
import type {RequestedCustomerChangeArtifact} from '@/lib/ediel/production/requestedCustomerChangeSource'
type Choice={id:string;label:string}
type Props={periods:(Choice&{contractId:string})[];agreements:Choice[];initialArtifactId:string;canArchive:boolean;canReview:boolean;canQueue:boolean}
const reasonLabels:Record<string,string>={authentic_current_outgoing_customer_mandate:'Utfärdarens aktuella bilaterala mandat och signerade kvitto saknas.',current_owned_supply_source_required:'Den egna leveransens aktuella källversion behöver styrkas.',separate_requested_customer_change_review_required:'En annan behörig granskare behöver granska originalet.',current_outgoing_customer_mandate_unavailable:'Mandatet eller granskarens aktuella behörighet kan inte längre styrkas.',actual_original_pdf_verbatim_outgoing_customer_clause:'Den granskade avtalstexten måste finnas ordagrant i originalet.',explicit_requested_customer_change_hold:'Granskaren har lagt underlaget på vänt.',explicit_requested_customer_change_rejection:'Granskaren har avvisat underlaget.'}
const humanReasons=(missing:unknown)=>Array.isArray(missing)?missing.map(r=>reasonLabels[String(r)]??'Aktuell källa eller behörighet behöver verifieras.').join(' '):''
async function pdfBase64(file:File){if(file.size>8*1024*1024)throw Error('Originalet får vara högst 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let at=0;at<bytes.length;at+=8192)binary+=String.fromCharCode(...bytes.subarray(at,at+8192));return btoa(binary)}
export default function RequestedCustomerChangeWorkspace(props:Props){
 const[artifactId,setArtifactId]=useState(props.initialArtifactId),[artifact,setArtifact]=useState<RequestedCustomerChangeArtifact|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
 async function perform(work:()=>Promise<void>){setBusy(true);setNotice('');setError('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Åtgärden kunde inte genomföras.')}finally{setBusy(false)}}
 async function json(path:string,body?:unknown){const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await response.json();if(!response.ok&&response.status!==409)throw Error(typeof data.error==='string'?data.error:'Underlaget kunde inte behandlas.');return data}
 async function load(id=artifactId){const data=await json(`/api/ediel/requested-customer-change-sources/${encodeURIComponent(id)}`);setArtifact(data);setArtifactId(data.artifactId);setNotice(humanReasons(data.missing)||'Underlaget har aktuell källauktoritet.')}
 function archive(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void perform(async()=>{const pdf=form.get('original'),wire=form.get('candidate'),receipt=form.get('receipt');if(!(pdf instanceof File)||!pdf.size||!(wire instanceof File)||!wire.size)throw Error('Välj originalavtal och den överenskomna begäran.');if(wire.size>1024*1024)throw Error('Begäran får vara högst 1 MB.');const period=props.periods.find(p=>p.id===form.get('period'));if(!period)throw Error('Välj en egen leverans.');let issuerReceipt:unknown;if(receipt instanceof File&&receipt.size){if(receipt.size>96*1024)throw Error('Utfärdarkvittot är för stort.');issuerReceipt=JSON.parse(await receipt.text())}const data=await json('/api/ediel/requested-customer-change-sources',{supplyPeriodId:period.id,contractId:period.contractId,agreementId:form.get('agreement'),rawPayload:await wire.text(),source:{bytesBase64:await pdfBase64(pdf),mimeType:'application/pdf',reference:form.get('reference'),version:form.get('version')},...(issuerReceipt?{issuerReceipt}:{})});setArtifactId(data.artifactId);await load(data.artifactId)})}
 function review(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void perform(async()=>{if(!artifact)throw Error('Öppna det arkiverade originalet först.');const quote=String(form.get('quote')??''),locator=String(form.get('locator')??'');const data=await json(`/api/ediel/requested-customer-change-sources/${artifact.artifactId}/review`,{sourceHash:artifact.sourceHash,claimsHash:artifact.claimsHash,decision:form.get('decision'),reason:form.get('reason'),...(quote||locator?{clause:{quote,locator}}:{})});await load(artifact.artifactId);if(data.status==='authorized')setNotice('Separat granskning godkänd med aktuell källauktoritet. Begäran kan köläggas.');else setNotice(humanReasons(data.missing))})}
 const field='w-full rounded border p-2',button='rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50'
 return <div role="region" aria-label="Begärd kundändring" className="min-w-0 space-y-8">
  {error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <section aria-labelledby="archive-title"><h2 id="archive-title" className="text-lg font-semibold">1. Arkivera överenskommelsen</h2><form onSubmit={archive} className="mt-3 grid gap-3">
   <label>Bilateralt mandat<select className={field} name="agreement" required disabled={!props.canArchive||busy}><option value="">Välj mandat</option>{props.agreements.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label>
   <label>Egen leverans och avtal<select className={field} name="period" required disabled={!props.canArchive||busy}><option value="">Välj leverans</option>{props.periods.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>
   <label>Originalavtal (PDF, högst 8 MB)<input className={field} type="file" name="original" accept="application/pdf" required disabled={!props.canArchive||busy}/></label>
   <label>Överenskommen begäran (Ediel-original, högst 1 MB)<input className={field} type="file" name="candidate" accept=".edi,.edifact,.txt" required disabled={!props.canArchive||busy}/></label>
   <label>Utfärdarens signerade kvitto, om tillgängligt<input className={field} type="file" name="receipt" accept="application/json,.json" disabled={!props.canArchive||busy}/></label>
   <label>Källreferens<input className={field} name="reference" required maxLength={2000} disabled={!props.canArchive||busy}/></label><label>Originalets version<input className={field} name="version" required maxLength={200} disabled={!props.canArchive||busy}/></label>
   <button className={button} disabled={!props.canArchive||busy}>Arkivera original</button>
  </form></section>
  <section aria-labelledby="open-title"><h2 id="open-title" className="text-lg font-semibold">2. Öppna arkiverat underlag</h2><form className="mt-3 flex flex-col gap-2 sm:flex-row" onSubmit={e=>{e.preventDefault();void perform(()=>load())}}><label className="flex-1">Underlags-ID<input aria-label="Underlags-ID" className={field} value={artifactId} onChange={e=>{setArtifactId(e.target.value);setArtifact(null)}} required disabled={busy}/></label><button className={button} disabled={busy}>Öppna underlag</button></form>
   {artifact&&<div className="mt-3 space-y-2 break-words"><p>{artifact.sourceReference} · version {artifact.sourceVersion} · {artifact.status==='authorized'?'Aktuellt mandat':artifact.status==='rejected'?'Avvisat':'Inväntar granskning eller källauktoritet'}</p><a className="underline" href={`/api/ediel/requested-customer-change-sources/${artifact.artifactId}/source`}>Hämta originalet för granskning</a><details><summary>Originalets kontrollsumma</summary><p className="font-mono text-sm">{artifact.sourceHash}</p></details><p>{humanReasons(artifact.missing)}</p></div>}
  </section>
  {artifact&&<section aria-labelledby="review-title"><h2 id="review-title" className="text-lg font-semibold">3. Separat granskning</h2><p>Den som arkiverade originalet får inte godkänna det. Behörig utfärdare, exakt kund och leverans samt ordagrann avtalstext måste styrkas.</p><form onSubmit={review} className="mt-3 grid gap-3"><label>Granskningsval<select className={field} name="decision" disabled={!props.canReview||busy}><option value="hold">Lägg på vänt</option><option value="approve">Godkänn aktuell överenskommelse</option><option value="reject">Avvisa</option></select></label><label>Motivering<textarea className={field} name="reason" required maxLength={4000} disabled={!props.canReview||busy}/></label><label>Var finns avtalstexten?<input className={field} name="locator" maxLength={1000} disabled={!props.canReview||busy}/></label><label>Ordagrann avtalstext<textarea className={field} name="quote" maxLength={10000} disabled={!props.canReview||busy}/></label><button className={button} disabled={!props.canReview||busy}>Spara separat granskning</button></form></section>}
  {artifact&&<section aria-labelledby="queue-title"><h2 id="queue-title" className="text-lg font-semibold">4. Kölägg begärd kundändring</h2><p>Köläggning verifierar aktuell källauktoritet, bolagets aktör, kanal och hela begäran igen.</p><button className={`${button} mt-3`} disabled={!props.canQueue||busy||artifact.status!=='authorized'} onClick={()=>void perform(async()=>{const data=await json(`/api/ediel/requested-customer-change-sources/${artifact.artifactId}/queue`,{});await load(artifact.artifactId);setNotice(data.status==='queued'?'Begäran är kölagd.':data.status==='existing'?'Den tidigare begäran finns redan.':humanReasons(data.missing)||'Begäran ligger på vänt.')})}>Kölägg kundändring</button></section>}
 </div>
}
