// Generated by the Gridex OPS quality playbook on 2026-08-10.
// These tests exercise production modules and public contract artifacts.
import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import customerPortalOpenApi from '@/docs/openapi/customer-portal-v1.json'
import { PUBLIC_API_ROUTES } from '@/lib/api/publicRouteRegistry'
import { customerPortalJson } from '@/lib/customer-portal/externalApi'
import { assertPublicResponsePayload } from '@/lib/api/publicPayloadSafety'
import {
  buildPortalDatabasePage,
  decodePortalCursor,
} from '@/lib/customer-portal/keysetPagination'
import {
  pagePublicItems,
  publicPortalBundleRows,
  publicPortalCustomer,
  publicPortalInvoice,
  publicPortalSite,
} from '@/lib/customer-portal/publicDto'
import type { PublicPage } from '@/lib/customer-portal/publicDto'
import { buildOpenApiReleaseManifest } from '@/lib/integrations/openApiReleaseManifest'
import { isPublicReference, publicReference } from '@/lib/integrations/publicReferences'
import { integrationWriteRequestHash } from '@/lib/integrations/writeIdempotency'
import { buildPublicWebhookPayload } from '@/lib/integrations/webhooks'
import {
  evaluatePlatformSchemaReadiness,
  isVerifiedSchemaFingerprint,
} from '@/lib/platform/schemaReadiness'
import {
  assertTenantContextCompany,
  createTenantContext,
} from '@/lib/tenant/context'

const tenantA = '0f140c8b-1111-4222-8333-f088008e2d6f'
const tenantB = '9b2e2434-1111-4222-8333-4289e20c6a50'
const internalId = '5ef6d6c4-1111-4222-8333-30f160647e4f'

function allKeys(value: unknown): string[] {
  if (Array.isArray(value)) return value.flatMap(allKeys)
  if (!value || typeof value !== 'object') return []
  return Object.entries(value as Record<string, unknown>).flatMap(
    ([key, child]) => [key, ...allKeys(child)],
  )
}

function operationIds(document: typeof customerPortalOpenApi): string[] {
  return Object.values(document.paths).flatMap((pathItem) =>
    Object.values(pathItem)
      .filter((operation): operation is { operationId: string } =>
        Boolean(operation && typeof operation === 'object' && 'operationId' in operation),
      )
      .map((operation) => operation.operationId),
  )
}

describe('Spec requirements', () => {
  it('[REQ-001] maps customer, site and invoice without database ownership keys', () => {
    const values = [
      publicPortalCustomer(
        { id: internalId, company_id: tenantA, full_name: 'Ada' },
        { external_customer_id: 'customer-public', customer_number: '1001' },
      ),
      publicPortalSite(tenantA, {
        id: internalId,
        company_id: tenantA,
        customer_id: internalId,
        site_name: 'Home',
      }),
      publicPortalInvoice(tenantA, {
        id: internalId,
        company_id: tenantA,
        customer_id: internalId,
        invoice_number: 'INV-1',
      }),
    ]
    const forbidden = new Set(['id', 'company_id', 'customer_id', 'site_id'])
    for (const value of values) {
      expect(allKeys(value).filter((key) => forbidden.has(key))).toEqual([])
      expect(JSON.stringify(value)).not.toContain(tenantA)
      expect(JSON.stringify(value)).not.toContain(internalId)
    }
  })

  it('[REQ-002] traverses 1,001 equal-timestamp rows with a stable keyset exactly once', () => {
    const orderValue = '2026-08-10T00:00:00.000Z'
    const source = Array.from({ length: 1001 }, (_, index) => ({
      id: `00000000-0000-4000-8000-${String(1000 - index).padStart(12, '0')}`,
      created_at: orderValue,
      index,
    }))
    const seen: number[] = []
    let cursor: string | null = null
    do {
      const tuple = decodePortalCursor({
        cursor,
        companyId: tenantA,
        customerId: internalId,
        resource: 'contracts',
      })
      const remaining = tuple
        ? source.filter((row) => row.created_at < tuple.orderValue ||
          (row.created_at === tuple.orderValue && row.id < tuple.id))
        : source
      const page = buildPortalDatabasePage(remaining.slice(0, 101), {
        limit: 100,
        companyId: tenantA,
        customerId: internalId,
        resource: 'contracts',
        orderColumn: 'created_at',
      })
      seen.push(...page.items.map((item) => item.index))
      cursor = page.page.next_cursor
    } while (cursor)
    expect(seen).toHaveLength(1001)
    expect(new Set(seen).size).toBe(1001)
    expect(seen[0]).toBe(0)
    expect(seen[100]).toBe(100)
    expect(seen[1000]).toBe(1000)
  })

  it('[REQ-003] produces a stable tenant-bound canonical invoice reference', () => {
    const first = publicPortalInvoice(tenantA, { id: internalId })
    const again = publicPortalInvoice(tenantA, { id: internalId })
    const otherTenant = publicPortalInvoice(tenantB, { id: internalId })
    expect(first.invoice_reference).toBe(again.invoice_reference)
    expect(first.invoice_reference).not.toBe(otherTenant.invoice_reference)
    expect(isPublicReference(first.invoice_reference)).toBe(true)
  })

  it('[REQ-004] fails schema readiness closed without verified evidence', () => {
    expect(isVerifiedSchemaFingerprint(null)).toBe(false)
    expect(
      evaluatePlatformSchemaReadiness({
        is_ready: true,
        schema_fingerprint: 'invalid',
        blocking_issues: [],
      }).ready,
    ).toBe(false)
    expect(
      evaluatePlatformSchemaReadiness({
        is_ready: true,
        schema_fingerprint: 'a'.repeat(64),
        blocking_issues: ['RPC_MISSING'],
      }).ready,
    ).toBe(false)
  })

  it('[REQ-005] hashes equivalent JSON objects identically and changed intent differently', () => {
    const first = integrationWriteRequestHash({
      customer_reference: 'customer-1',
      values: [1, 2],
    })
    const reordered = integrationWriteRequestHash({
      values: [1, 2],
      customer_reference: 'customer-1',
    })
    const changed = integrationWriteRequestHash({
      values: [2, 1],
      customer_reference: 'customer-1',
    })
    expect(first).toBe(reordered)
    expect(first).not.toBe(changed)
  })

  it('[REQ-006] rejects malformed and duplicate OpenAPI operationIds', () => {
    const ids = operationIds(customerPortalOpenApi)
    expect(ids.every((id) => /^[A-Za-z][A-Za-z0-9]*$/.test(id))).toBe(true)
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('[REQ-006] gives every registry operation canonical metadata', () => {
    for (const route of PUBLIC_API_ROUTES as Array<Record<string, unknown>>) {
      expect(route.operationId).toMatch(/^[A-Za-z][A-Za-z0-9]*$/)
      expect(route.responseSchema).toBeTruthy()
      expect(route.scopeMode).toMatch(/^(all|any)$/)
      expect(route.cachePolicy).toBeTruthy()
      expect(route.publicIdPolicy).toBeTruthy()
    }
  })

  it('[REQ-007] requires bootstrap client references not derived from a UUID', () => {
    const source = readFileSync('lib/integrations/tenantContext.ts', 'utf8')
    expect(PUBLIC_API_ROUTES.some((route) => route.path === '/api/v1/integration/context')).toBe(true)
    expect(source).not.toContain("client.id.replaceAll('-', '')")
  })

  it('[REQ-008] tenant context rejects a mismatched company before domain work', () => {
    const context = createTenantContext({
      companyId: tenantA,
      actorType: 'integration',
      actorId: 'client-a',
      scopes: ['customer_invoices.read'],
      sourceChannel: 'partner_api',
      correlationId: 'correlation-a',
    })
    expect(() => assertTenantContextCompany(context, tenantB)).toThrow()
  })

  it('[REQ-009] forbids select-star in scoped hot public-contract reads', () => {
    const source = readFileSync('lib/website/publicContracts.ts', 'utf8')
    expect(PUBLIC_API_ROUTES.some((route) => route.path === '/api/v1/public-contracts')).toBe(true)
    expect(source).not.toMatch(/\.select\(\s*['"]\*['"]\s*\)/)
  })

  it('[REQ-010] strips internal identifiers from current webhook projection', () => {
    const payload = buildPublicWebhookPayload(
      {
        id: internalId,
        company_id: tenantA,
        event_type: 'contract.application_received',
        aggregate_type: 'customer_contract',
        aggregate_id: internalId,
        subject_customer_id: internalId,
        actor_user_id: internalId,
        source: 'application',
        event_version: 1,
        idempotency_key: null,
        payload: { application_number: 'APP-1', company_id: tenantA },
        occurred_at: '2026-08-10T00:00:00.000Z',
        created_at: '2026-08-10T00:00:00.000Z',
      },
      'tenant_public_a',
    )
    expect(JSON.stringify(payload)).not.toContain(tenantA)
    expect(JSON.stringify(payload)).not.toContain(internalId)
  })

  it('[REQ-011] contains the official connected-dev migration tail in source', () => {
    const required = [
      '20260809180628_gridex_ops_external_api_performance_foundation.sql',
      '20260809181141_backfill_legacy_ediel_test_run_tenant.sql',
      '20260809181153_validate_pending_public_constraints.sql',
      '20260809181803_portal_event_keyset_read_model.sql',
      '20260809182215_authenticate_integration_request_v1.sql',
      '20260809182318_authenticate_integration_request_route_cost.sql',
      '20260809182554_resolve_portal_customer_identity_v1.sql',
      '20260809183210_public_contract_feed_fingerprint_v1.sql',
      '20260809191057_authenticate_integration_request_route_cost.sql',
      '20260809191135_portal_event_keyset_read_model.sql',
    ]
    expect(required.every((name) => existsSync(`supabase/migrations/${name}`))).toBe(true)
  })

  it('[REQ-012] refuses to invent a build commit without deployment provenance', () => {
    const previousVercel = process.env.VERCEL_GIT_COMMIT_SHA
    const previousGit = process.env.GIT_COMMIT_SHA
    delete process.env.VERCEL_GIT_COMMIT_SHA
    delete process.env.GIT_COMMIT_SHA
    try {
      expect(buildOpenApiReleaseManifest().build_commit).toBe('unknown')
    } finally {
      if (previousVercel) process.env.VERCEL_GIT_COMMIT_SHA = previousVercel
      if (previousGit) process.env.GIT_COMMIT_SHA = previousGit
    }
  })
})

describe('Fitness scenarios', () => {
  it('[QUALITY Scenario 1] reaches the first, 101st and 1,001st record', () => {
    const values = Array.from({ length: 1001 }, (_, index) => `row-${index + 1}`)
    const pages: string[] = []
    let cursor: string | null = null
    do {
      const page: PublicPage<string> = pagePublicItems(values, { limit: 73, cursor })
      pages.push(...page.items)
      cursor = page.page.next_cursor
    } while (cursor)
    expect([pages[0], pages[100], pages[1000]]).toEqual(['row-1', 'row-101', 'row-1001'])
  })

  it('[QUALITY Scenario 2] keeps an old invoice public reference independent of array position', () => {
    const rows = Array.from({ length: 1001 }, (_, index) => ({ id: `internal-${index}` }))
    const oldest = publicPortalInvoice(tenantA, rows[1000]).invoice_reference
    expect(oldest).toBe(publicReference('invoice', tenantA, 'internal-1000'))
  })

  it('[QUALITY Scenario 3] contradictory readiness evidence cannot be ready', () => {
    expect(
      evaluatePlatformSchemaReadiness({
        is_ready: true,
        schema_fingerprint: 'a'.repeat(64),
        blocking_issues: ['MIGRATION_MISSING'],
      }),
    ).toMatchObject({ ready: false, blockingIssuesVerified: false })
  })

  it('[QUALITY Scenario 4] final success serializer rejects a nested internal key', () => {
    expect(() => customerPortalJson({ data: { nested: { company_id: tenantA } } })).toThrow()
    expect(() => assertPublicResponsePayload({
      data: [{ id: internalId, offer_reference: 'public-offer' }],
    })).toThrow()
  })

  it('[QUALITY Scenario 5] canonical hashing distinguishes an altered body', () => {
    expect(integrationWriteRequestHash({ a: 1, b: null }))
      .not.toBe(integrationWriteRequestHash({ a: 2, b: null }))
  })

  it('[QUALITY Scenario 6] public references hide the internal UUID and bind the tenant', () => {
    const a = publicReference('api_client', tenantA, internalId)
    const b = publicReference('api_client', tenantB, internalId)
    expect(a).not.toContain(internalId.replaceAll('-', ''))
    expect(a).not.toBe(b)
  })

  it('[QUALITY Scenario 7] release compatibility uses one classification', () => {
    const manifest = buildOpenApiReleaseManifest()
    expect(manifest.specifications.website.compatibility).toBe(manifest.compatibility_classification)
    expect(manifest.specifications.customer_portal.compatibility).toBe(manifest.compatibility_classification)
  })

  it('[QUALITY Scenario 8] webhook public references differ when tenant reference differs', () => {
    const event = {
      id: internalId, company_id: tenantA, event_type: 'contract.application_received',
      aggregate_type: 'customer_contract', aggregate_id: internalId,
      subject_customer_id: internalId, actor_user_id: null, source: 'application',
      event_version: 1, idempotency_key: null, payload: { application_number: 'APP-1' },
      occurred_at: '2026-08-10T00:00:00.000Z', created_at: '2026-08-10T00:00:00.000Z',
    }
    const a = buildPublicWebhookPayload(event, 'tenant_public_a')
    const b = buildPublicWebhookPayload(event, 'tenant_public_b')
    expect(a.event_id).not.toBe(b.event_id)
  })

  it('[QUALITY Scenario 9] migration source contains the live atomic auth function', () => {
    expect(existsSync('supabase/migrations/20260809182215_authenticate_integration_request_v1.sql')).toBe(true)
  })

  it('[QUALITY Scenario 10] missing release provenance is explicitly unknown', () => {
    const manifest = buildOpenApiReleaseManifest()
    expect(typeof manifest.build_commit).toBe('string')
    expect(manifest.build_commit.length).toBeGreaterThan(0)
  })
})

describe('Boundaries and edge cases', () => {
  it('[REQ-001 boundary] returns null instead of a misleading reference for absent identity', () => {
    expect(publicReference('invoice', tenantA, null)).toBeNull()
    expect(publicReference('invoice', '', internalId)).toBeNull()
  })

  it('[REQ-001 boundary] maps every bundle variant through a public mapper', () => {
    const bundle = publicPortalBundleRows(tenantA, {
      contracts: [{ id: 'c' }], sites: [{ id: 's' }], meteringPoints: [{ id: 'mp' }],
      invoices: [{ id: 'i' }], meteringValues: [{ id: 'mv' }], documents: [{ id: 'd' }],
      legalAcceptances: [{ id: 'l' }], powersOfAttorney: [{ id: 'p' }],
      notifications: [{ id: 'n' }], events: [{ id: 'e' }], applications: [{ id: 'a' }],
    })
    expect(Object.values(bundle).every((items) => items.length === 1)).toBe(true)
    expect(allKeys(bundle)).not.toContain('company_id')
  })

  it('[REQ-002 boundary] clamps page sizes to one through one hundred', () => {
    expect(pagePublicItems([1, 2], { limit: -5 }).page.limit).toBe(1)
    expect(pagePublicItems(Array.from({ length: 200 }), { limit: 1000 }).page.limit).toBe(100)
  })

  it('[REQ-002 boundary] rejects a tampered or cross-tenant cursor', () => {
    const page = buildPortalDatabasePage([
      { id: internalId, created_at: '2026-08-10T00:00:00.000Z' },
      { id: '4d68aac2-1111-4222-8333-30f160647e4f', created_at: '2026-08-09T00:00:00.000Z' },
    ], {
      limit: 1,
      companyId: tenantA,
      customerId: internalId,
      resource: 'contracts',
      orderColumn: 'created_at',
    })
    expect(page.page.next_cursor).toBeTruthy()
    const cursor = page.page.next_cursor!
    expect(() => decodePortalCursor({
      cursor: `${cursor.slice(0, -1)}A`,
      companyId: tenantA,
      customerId: internalId,
      resource: 'contracts',
    })).toThrow()
    expect(() => decodePortalCursor({
      cursor,
      companyId: tenantB,
      customerId: internalId,
      resource: 'contracts',
    })).toThrow()
  })

  it('[REQ-004 boundary] preserves the canonical error envelope and request ID', async () => {
    const response = customerPortalJson(
      { error: { code: 'quota_exceeded', message: 'Quota', retryable: true }, request_id: 'request-1' },
      { status: 429 },
    )
    expect(response.status).toBe(429)
    expect(response.headers.get('x-request-id')).toBe('request-1')
    expect(await response.json()).toMatchObject({
      request_id: 'request-1',
      error: { code: 'quota_exceeded', retryable: true },
    })
  })

  it('[REQ-005 boundary] canonical hashing distinguishes array order but not object order', () => {
    expect(integrationWriteRequestHash({ a: [1, 2], b: { x: 1, y: 2 } }))
      .not.toBe(integrationWriteRequestHash({ a: [2, 1], b: { y: 2, x: 1 } }))
    expect(integrationWriteRequestHash({ b: { y: 2, x: 1 }, a: [1, 2] }))
      .toBe(integrationWriteRequestHash({ a: [1, 2], b: { x: 1, y: 2 } }))
  })

  it('[REQ-008 boundary] normalizes duplicate tenant scopes and freezes context', () => {
    const context = createTenantContext({
      companyId: tenantA, actorType: 'integration', actorId: 'client-a',
      scopes: ['b', 'a', 'b'], sourceChannel: 'partner_api', correlationId: 'c',
    })
    expect(context.scopes).toEqual(['a', 'b'])
    expect(Object.isFrozen(context)).toBe(true)
  })

  it('[REQ-006 boundary] immutable OpenAPI routes remain in the registry', () => {
    const manifest = buildOpenApiReleaseManifest()
    const websitePath = new URL(manifest.specifications.website.immutable_url).pathname
    const portalPath = new URL(manifest.specifications.customer_portal.immutable_url).pathname
    expect(PUBLIC_API_ROUTES.some((route) => route.path === websitePath)).toBe(true)
    expect(PUBLIC_API_ROUTES.some((route) => route.path === portalPath)).toBe(true)
  })
})
