// Generated by the Gridex OPS quality playbook on 2026-08-10.
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import customerPortalOpenApi from '@/docs/openapi/customer-portal-v1.json'
import { PUBLIC_API_ROUTES } from '@/lib/api/publicRouteRegistry'
import { customerPortalJson } from '@/lib/customer-portal/externalApi'

function source(path: string): string {
  return readFileSync(path, 'utf8')
}

describe('Gridex remediation confirmed regressions', () => {
  it('BUG-001: regression_bug_001_reaches_row_1001', () => {
    const data = source('lib/customer-portal/apiData.ts')
    for (const fn of ['listPortalContractsPage', 'listPortalSitesPage', 'listPortalInvoicesPage', 'listPortalDocumentsPage', 'listPortalEventsPage']) {
      const body = data.slice(data.indexOf(`export async function ${fn}`), data.indexOf('\nexport async function', data.indexOf(`export async function ${fn}`) + 1))
      expect(body).toMatch(/portalTablePage|p_limit:\s*limit\s*\+\s*1/)
    }
  })

  it('BUG-002: regression_bug_002_invoice_detail_uses_direct_lookup', () => {
    const route = source('app/api/v1/customer/invoices/[id]/route.ts')
    expect(route).toContain('getPortalInvoiceByReference')
    expect(route).not.toContain('listPortalInvoices')
    expect(route).not.toContain('.find(')
  })

  it('BUG-003: regression_bug_003_schema_failure_is_503', () => {
    const data = source('lib/customer-portal/apiData.ts')
    const fallback = data.slice(data.indexOf('async function listWithSchemaFallback'), data.indexOf('\nexport async function', data.indexOf('async function listWithSchemaFallback')))
    expect(fallback).toContain('PlatformSchemaNotReadyError')
    expect(fallback).not.toMatch(/return\s*\[\]\s*$/m)
  })

  it('BUG-004: regression_bug_004_api_client_reference_is_opaque', () => {
    const context = source('lib/integrations/tenantContext.ts')
    expect(context).not.toContain("client.id.replaceAll('-', '')")
    expect(context).toMatch(/public_reference|publicReference\('api_client'/)
  })

  it('BUG-005: regression_bug_005_completion_failure_blocks_success', () => {
    const idempotency = source('lib/integrations/writeIdempotency.ts')
    const completion = idempotency.slice(
      idempotency.indexOf('completeIntegrationWriteIdempotency'),
      idempotency.indexOf('export async function failIntegrationWriteIdempotency'),
    )
    expect(completion).not.toContain('best effort')
    expect(completion).not.toContain('console.error')
    expect(completion).toMatch(/throw|rpc\(/)
  })

  it('BUG-006: regression_bug_006_registry_openapi_metadata_parity', () => {
    for (const route of PUBLIC_API_ROUTES as Array<Record<string, unknown>>) {
      expect(route.operationId).toMatch(/^[A-Za-z][A-Za-z0-9]*$/)
      expect(route.responseSchema).toBeTruthy()
      expect(route.scopeMode).toMatch(/^(all|any)$/)
      expect(route.cachePolicy).toBeTruthy()
      expect(route.publicIdPolicy).toBeTruthy()
    }
    const ids = Object.values(customerPortalOpenApi.paths).flatMap((item) =>
      Object.values(item).map((operation) => (operation as { operationId?: string }).operationId).filter(Boolean),
    ) as string[]
    expect(ids.every((id) => /^[A-Za-z][A-Za-z0-9]*$/.test(id))).toBe(true)
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('BUG-007: regression_bug_007_parity_follows_split_runtime', () => {
    expect(() => execFileSync('node', ['scripts/check-openapi-runtime-parity.cjs'], { stdio: 'pipe' })).not.toThrow()
    const test = source('__tests__/api-canonical-release.test.ts')
    expect(test).toContain('customerApplicationProcess.ts')
  })

  it('BUG-008: regression_bug_008_live_migration_tail_is_present', () => {
    const files = [
      '20260809180628_gridex_ops_external_api_performance_foundation.sql',
      '20260809181141_backfill_legacy_ediel_test_run_tenant.sql',
      '20260809181153_validate_pending_public_constraints.sql',
      '20260809181803_portal_event_keyset_read_model.sql',
      '20260809182215_authenticate_integration_request_v1.sql',
      '20260809182318_authenticate_integration_request_route_cost.sql',
      '20260809182554_resolve_portal_customer_identity_v1.sql',
      '20260809183210_public_contract_feed_fingerprint_v1.sql',
      '20260809191057_authenticate_integration_request_route_cost.sql',
      '20260809191135_portal_event_keyset_read_model.sql',
    ]
    expect(files.every((file) => existsSync(`supabase/migrations/${file}`))).toBe(true)
  })

  it('BUG-009: regression_bug_009_webhooks_fail_closed_per_tenant', () => {
    const webhooks = source('lib/integrations/webhooks.ts')
    expect(webhooks).toContain('WEBHOOK_EVENT_REGISTRY')
    expect(webhooks).not.toContain('WEBHOOK_SIGNING_SECRET_FALLBACK')
    expect(webhooks).not.toContain('sanitizeWebhookData')
  })

  it('BUG-010: regression_bug_010_auth_uses_route_cost_rpc', () => {
    const auth = source('lib/integrations/apiAuth.ts')
    expect(auth).toContain("rpc('authenticate_integration_request_v1'")
    expect(auth).toMatch(/rateLimitClass|routeCost/)
    expect(auth).not.toContain("rpc('check_and_increment_integration_api_rate_limit'")
  })

  it('BUG-011: regression_bug_011_serializer_rejects_internal_fields', () => {
    expect(() => customerPortalJson({ data: { nested: { company_id: 'tenant-internal' } } })).toThrow(/forbidden|public/i)
  })

  it('BUG-012: regression_bug_012_public_contracts_use_projection_and_early_fingerprint', () => {
    const reads = source('lib/website/publicContracts.ts')
    expect(reads).not.toMatch(/\.select\(\s*['"]\*['"]\s*\)/)
    const route = source('app/api/v1/website/public-contracts/route.ts')
    const fingerprintIndex = route.indexOf("rpc('public_contract_feed_fingerprint_v1'")
    const contractLoadIndex = route.indexOf('loadPublicContracts({ client: auth.client')
    const parallelLoadIndex = route.indexOf('await Promise.all([')
    expect(fingerprintIndex).toBeGreaterThanOrEqual(0)
    expect(contractLoadIndex).toBeGreaterThanOrEqual(0)
    expect(parallelLoadIndex).toBeGreaterThan(fingerprintIndex)
    expect(fingerprintIndex).toBeLessThan(contractLoadIndex)
    expect(route).toContain('currentTenantReference = tenant.tenant_reference')
    expect(route.indexOf('loadExternalTenantContext(auth.client).then')).toBeGreaterThanOrEqual(0)
    expect(route.indexOf('loadExternalTenantContext(auth.client).then')).toBeLessThan(parallelLoadIndex)
  })

  it('BUG-013: regression_bug_013_identity_uses_canonical_rpc', () => {
    const resolver = source('lib/customer-portal/customerResolver.ts')
    expect(resolver).toContain("rpc('resolve_portal_customer_identity_v1'")
    expect(resolver).not.toMatch(/\.limit\(1\)/)
  })

  it('BUG-014: regression_bug_014_new_tenant_uses_granular_scopes_and_smoke', () => {
    const profile = source('lib/integrations/apiClientProfiles.ts')
    const tenantProfile = profile.slice(profile.indexOf('tenant_website:'), profile.indexOf('customer_portal:'))
    expect(tenantProfile).not.toContain("'customer_portal.read'")
    expect(tenantProfile).not.toContain("'customer_portal.write'")
    const provisioning = source('lib/integrations/tenantWebsiteProvisioning.ts')
    expect(provisioning).toContain('runTenantIntegrationSmokeTest')
  })
})
