"use client"
import {useState} from 'react'
import {decisionEvidenceClasses,decisionEvidencePermission,type DecisionEvidenceClass} from '@/lib/ediel/retention/decisionEvidenceClasses'
import type {decisionOriginalSchema,decisionPolicySchema} from '@/lib/ediel/retention/decisionEvidenceRetention'
import type {z} from 'zod'

type Original=z.infer<typeof decisionOriginalSchema>;type Policy=z.infer<typeof decisionPolicySchema>
const labels:Record<DecisionEvidenceClass,string>={artifact_retention_decision_original_bytes:'Källartefaktens gallringsbeslut',blob_retention_decision_original_bytes:'Meddelande- eller MIME-beslut',record_retention_decision_original_bytes:'Kund- eller kontraktsbeslut',process_retention_decision_original_bytes:'Processjournalens gallringsbeslut',decision_evidence_policy_original_bytes:'Beslutsoriginalets rättsliga underlag',finance_retention_decision_original_bytes:'Finanskopians gallringsbeslut'}
const api='/api/ediel/decision-evidence-retention'
async function request<T>(url:string,body?:unknown):Promise<T>{
 const response=await fetch(url,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'})
 const data=await response.json();if(!response.ok)throw Error(typeof data.error==='string'?data.error:'Begäran kunde inte genomföras.');return data as T
}
async function base64(file:File){if(file.size<1||file.size>1048576)throw Error('Underlaget får vara högst 1 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let value='';for(const byte of bytes)value+=String.fromCharCode(byte);return btoa(value)}
export default function DecisionEvidenceWorkspace({companyId,userId,permissions}:{companyId:string;userId:string;permissions:string[]}){
 const classes=decisionEvidenceClasses.filter(k=>permissions.includes(decisionEvidencePermission[k]))
 const [retentionClass,setClass]=useState<DecisionEvidenceClass>(classes[0]??'blob_retention_decision_original_bytes'),[targetId,setTarget]=useState(''),[original,setOriginal]=useState<Original|null>(null),[document,setDocument]=useState<File|null>(null),[receipt,setReceipt]=useState<File|null>(null),[policyId,setPolicyId]=useState(''),[policy,setPolicy]=useState<Policy|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const currentClass=policy?.retentionClass??retentionClass,hasClass=permissions.includes(decisionEvidencePermission[currentClass]),canSubmit=permissions.includes('ediel.retention.submit')&&permissions.includes(decisionEvidencePermission[retentionClass]),canReview=permissions.includes('ediel.retention.review')&&hasClass,canPurge=permissions.includes('ediel.retention.purge')&&hasClass
 async function perform(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action()}catch(error){setMessage(error instanceof Error?error.message:'Begäran kunde inte genomföras.')}finally{setBusy(false)}}
 async function refresh(id:string){setPolicy(await request<Policy>(`${api}/${encodeURIComponent(id)}`))}
 if(classes.length===0)return <p>Aktuell behörighet till en beslutsoriginalklass saknas.</p>
 return <div className="space-y-6" data-testid="decision-evidence-workspace"><p className="break-all text-sm">Bolag: {companyId}</p>
 <section className="space-y-3 rounded border p-4"><h2 className="text-lg font-semibold">Läs originalets metadata</h2><label className="block">Originalklass<select className="block w-full rounded border p-2" value={retentionClass} onChange={e=>{setClass(e.target.value as DecisionEvidenceClass);setOriginal(null)}}>{classes.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>
 <label className="block">Originalets ID<input className="block w-full rounded border p-2" value={targetId} onChange={e=>{setTarget(e.target.value);setOriginal(null)}}/></label><button className="rounded border px-3 py-2" disabled={busy||!targetId} onClick={()=>perform(async()=>setOriginal(await request<Original>(`${api}/original/${retentionClass}/${encodeURIComponent(targetId)}`)))}>Läs originalmetadata</button>
 {original&&<dl className="space-y-1 break-all"><dt>Originalhash</dt><dd data-testid="decision-source-hash">{original.documentHash}</dd><dt>Metadatahash</dt><dd>{original.targetMetadataHash}</dd><dt>Originalinnehåll</dt><dd>{original.bytesAvailable?'Bevarat':'Rensat – endast hash och metadata återstår'}</dd><dt>Antal byte</dt><dd>{original.documentByteLength}</dd>{original.purgedAt&&<><dt>Rensat vid</dt><dd>{original.purgedAt}</dd></>}</dl>}
 {original?.bytesAvailable&&permissions.includes('ediel.retention.review')&&<a className="inline-block underline" href={`${api}/original/${retentionClass}/${encodeURIComponent(targetId)}/document`}>Hämta original för granskning</a>}</section>
 {canSubmit&&<section className="space-y-3 rounded border p-4"><h2 className="text-lg font-semibold">Arkivera ett eget underlag</h2><label className="block">Rättsligt underlag<input className="block" type="file" onChange={e=>setDocument(e.target.files?.[0]??null)}/></label><label className="block">Utfärdarens signerade kvitto<input className="block" type="file" accept="application/json,.json" onChange={e=>setReceipt(e.target.files?.[0]??null)}/></label><p className="text-sm">Underlag utan kvalificerat utfärdarkvitto bevaras för granskning och ger ingen rensningsrätt.</p><button className="rounded border px-3 py-2" disabled={busy||!document||!targetId||original?.bytesAvailable===false} onClick={()=>perform(async()=>{let issuerReceipt:Record<string,unknown>|null=null;if(receipt){if(receipt.size>32768)throw Error('Utfärdarkvittot är för stort.');issuerReceipt=JSON.parse(await receipt.text())}const result=await request<{policyId:string}>(api,{retentionClass,targetId,documentBase64:await base64(document!),issuerReceipt});setPolicyId(result.policyId);await refresh(result.policyId);setMessage('Underlaget är arkiverat. Separat granskning krävs.')} )}>Arkivera underlag</button></section>}
 <section className="space-y-3 rounded border p-4"><h2 className="text-lg font-semibold">Granska och följ underlaget</h2><label className="block">Underlagets ID<input className="block w-full rounded border p-2" value={policyId} onChange={e=>{setPolicyId(e.target.value);setPolicy(null)}}/></label><button className="rounded border px-3 py-2" disabled={busy||!policyId} onClick={()=>perform(()=>refresh(policyId))}>Läs underlag</button>
 {policy&&<><dl className="space-y-1 break-all"><dt>Originalklass</dt><dd>{labels[policy.retentionClass]}</dd><dt>Källans ID</dt><dd>{policy.targetId}</dd><dt>Källans hash</dt><dd>{policy.sourceHash}</dd><dt>Underlagets hash</dt><dd>{policy.documentHash}</dd><dt>Underlagets original</dt><dd>{policy.bytesAvailable?'Bevarat':'Rensat – historiska metadata kvarstår'}</dd><dt>Utfärdarkvitto</dt><dd>{policy.issuerQualified?'Aktuellt kvalificerat':'Saknas eller håller inte aktuella krav'}</dd><dt>Separat granskning</dt><dd>{policy.currentQualified?'Aktuellt kvalificerad':'Rensning hålls tills aktuella krav är uppfyllda'}</dd></dl>
 {canReview&&policy.bytesAvailable&&<a className="inline-block underline" href={`${api}/${policy.policyId}/document`}>Hämta underlag för granskning</a>}
 {policy.reviews.length>0&&<ul className="space-y-1">{policy.reviews.map(r=><li className="break-all" key={r.reviewId}>{r.createdAt}: {r.outcome} – {r.reason}</li>)}</ul>}
 {canReview&&<><label className="block">Granskarens motivering<textarea className="block w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="flex flex-wrap gap-2">{(['approve','hold','reject'] as const).map((outcome,i)=><button key={outcome} className="rounded border px-3 py-2" disabled={busy||!reason||outcome==='approve'&&policy.submittedBy===userId||!policy.bytesAvailable||policy.revoked} onClick={()=>perform(async()=>{const result=await request<{status:string}>(`${api}/${policy.policyId}/review`,{outcome,reason});await refresh(policy.policyId);setMessage(result.status==='approved'?'Granskningen är registrerad.':'Underlaget ger för närvarande ingen rensningsrätt.')} )}>{['Godkänn efter separat granskning','Håll för komplettering','Avvisa underlag'][i]}</button>)}<button className="rounded border px-3 py-2" disabled={busy||!reason||policy.revoked} onClick={()=>perform(async()=>{await request(`${api}/${policy.policyId}/revoke`,{reason});await refresh(policy.policyId);setMessage('Underlaget är återkallat.')} )}>Återkalla underlag</button></div></>}
 {policy.purge&&<p data-testid="decision-purge-completed">Originalet är rensat: {policy.purge.purgedAt}. Hash och metadata finns kvar.</p>}
 {canPurge&&<button className="rounded border px-3 py-2" disabled={busy||!policy.currentQualified&&!policy.purge} onClick={()=>perform(async()=>{const result=await request<{status:string}>(`${api}/${policy.policyId}/purge`,{});await refresh(policy.policyId);setMessage(result.status==='purged'?'Originalet är rensat och dess fortsatta beslutsrätt är återkallad.':'Rensning hålls. Kontrollera aktuellt underlag, separat granskning och tidpunkt.')} )}>Verkställ beslutad rensning</button>}</>}
 </section><p role="status" aria-live="polite" className="break-words">{message}</p></div>
}
