import { afterAll, beforeAll, expect, it, vi } from 'vitest'
vi.mock('server-only', () => ({}))
// Next request storage is absent in this native worker. Only the empty cookie
// container is supplied; membership, permission and graph checks stay real.
vi.mock('next/headers', () => ({ cookies: async () => ({ get: () => undefined }) }))
import { checkSupplierSwitchReadiness, persistSwitchReadinessSnapshot } from '@/lib/customer-operations/switchReadiness'
import { processInboundResponse } from '@/lib/customer-operations/automation.part-2'
import { processJob, processSupplierSwitch } from '@/lib/customer-operations/automation.part-3'
import { updateJob, type JobRow } from '@/lib/customer-operations/automation.part-1'
import { proofSql as sql, quote } from './customer-read-proof-native'
import { createPositiveSiteFixture, createHeldPositiveSiteRoutes, signPositiveSiteAgreement, preparePositiveZ01AndCaptureZ02, type PositiveSiteFixture } from './customer-site-positive-continuation-20261001.fixture'

const API = 'http://127.0.0.1:54321'
const actualFetch = globalThis.fetch
const companies: string[] = []
let forbiddenFetches = 0
beforeAll(() => {
  globalThis.fetch = ((input: string | URL | Request, init?: RequestInit) => {
    const url = new URL(input instanceof Request ? input.url : String(input))
    if (url.origin !== API) { forbiddenFetches++; throw new Error('site_positive_external_delivery_forbidden') }
    return actualFetch(input, init)
  }) as typeof fetch
})
afterAll(() => {
  globalThis.fetch = actualFetch
  // Cancel only this disposable fixture's remaining queues before any later
  // CI worker runs. No sender/activation consumer is invoked by this proof.
  if (companies.length) sql(`UPDATE public.customer_operation_jobs SET status='cancelled',locked_at=NULL,locked_by=NULL,lock_token=NULL
      WHERE company_id IN (${companies.map(quote).join(',')}) AND status IN('queued','running','waiting_response');
    UPDATE public.tenant_email_outbox SET status='cancelled' WHERE company_id IN (${companies.map(quote).join(',')}) AND status='queued';
    UPDATE public.ediel_outbox SET status='blocked' WHERE company_id IN (${companies.map(quote).join(',')}) AND status='queued';
    SELECT to_jsonb(true);`)
})
function effects(f: PositiveSiteFixture) {
  return sql<Record<string, unknown>>(`SELECT jsonb_build_object(
    'switches',(SELECT coalesce(jsonb_agg(to_jsonb(s) ORDER BY id),'[]') FROM public.supplier_switch_requests s WHERE company_id=${quote(f.company)}),
    'notifications',(SELECT coalesce(jsonb_agg(to_jsonb(j) ORDER BY id),'[]') FROM public.customer_operation_jobs j WHERE company_id=${quote(f.company)} AND job_type='dispatch_lifecycle_notification'),
    'email',(SELECT coalesce(jsonb_agg(to_jsonb(e) ORDER BY id),'[]') FROM public.tenant_email_outbox e WHERE company_id=${quote(f.company)}),
    'outbound',(SELECT coalesce(jsonb_agg(to_jsonb(e) ORDER BY id),'[]') FROM public.ediel_outbox e JOIN public.ediel_messages m ON m.id=e.ediel_message_id WHERE e.company_id=${quote(f.company)} AND m.message_code='Z03'),
    'sentEmail',(SELECT count(*) FROM public.communication_logs WHERE company_id=${quote(f.company)} AND (status IN('sent','delivered') OR provider_message_id IS NOT NULL)),
    'sentEdiel',(SELECT count(*) FROM public.ediel_messages WHERE company_id=${quote(f.company)} AND direction='outbound' AND message_code='Z03' AND message_sent_at IS NOT NULL),
    'activeSupply',(SELECT count(*) FROM public.customer_supply_periods WHERE company_id=${quote(f.company)} AND status='active'));`)
}

it('actual exact Z02, signed legal/PDF/POA and approved held routes continue to one durable switch and unsent notification', async () => {
  const f = createPositiveSiteFixture(companies)
  createHeldPositiveSiteRoutes(f)
  await signPositiveSiteAgreement(f)
  const job = await preparePositiveZ01AndCaptureZ02(f)
  // All four proof fields are generated by actual enabled database gates.
  // The fixture never inserts or overrides a claimed success result.
  expect(job).toMatchObject({ status: 'queued', result: { z02_correlation_status: 'exact', z02_payload_validation_status: 'valid',
    z02_snapshot_freshness_status: 'valid', z02_atomic_core_applied: true, z02_atomic_core: { ok: true, meteringPointRecordId: f.point } } })
  const ready = await checkSupplierSwitchReadiness({ companyId: f.company, customerId: f.customer, siteId: f.site, contractId: f.contract })
  expect(ready.blockers).toEqual([]); expect(ready.ready).toBe(true)
  expect(ready.readinessSnapshot).toMatchObject({ contract_id: f.contract, legal_acceptance_count: expect.any(Number),
    authorization_scope: { covered: true }, contract: { agreement_signed: true, signed_pdf_archived: true, valid_power_of_attorney: true, switch_ready: true },
    grid_owner_verification: { can_start_supplier_switch: true }, route_readiness: { ready: true } })
  expect(Number(ready.readinessSnapshot.legal_acceptance_count)).toBeGreaterThan(0)
  console.log('SITE_POSITIVE_PREREQUISITES_NATIVE_PASS actual_z02_gates=true actual_signature_rpc=true exact_legal_set=true actual_storage_pdf_hash=true site_poa_scope=true approved_local_held_route=true')
  const applied = await processInboundResponse(job)
  expect(applied).toMatchObject({ status: 'completed', result: { reason: 'z02_atomic_core_finalized', metering_point_id: f.point } })
  await updateJob(job, { status: applied.status, result: applied.result })
  const switchJobId = String(applied.result?.supplier_switch_job_id)
  const switchJob = sql<JobRow>(`SELECT to_jsonb(j) FROM public.customer_operation_jobs j WHERE company_id=${quote(f.company)} AND id=${quote(switchJobId)};`)
  expect(switchJob).toMatchObject({ customer_id: f.customer, customer_site_id: f.site, metering_point_id: f.point, operation_id: f.operation })
  const prepared = await processSupplierSwitch(switchJob)
  expect(prepared).toMatchObject({ status: 'completed' })
  await updateJob(switchJob, { status: prepared.status, result: prepared.result })
  const requestId = String(prepared.result?.supplier_switch_request_id)
  const durable = sql<Record<string, unknown>>(`SELECT to_jsonb(s) FROM public.supplier_switch_requests s WHERE id=${quote(requestId)} AND company_id=${quote(f.company)};`)
  expect(durable).toMatchObject({ customer_id: f.customer, site_id: f.site, metering_point_id: f.point, customer_contract_id: f.contract, contract_id: f.contract,
    power_of_attorney_id: expect.any(String), authorization_document_id: expect.any(String) })
  await persistSwitchReadinessSnapshot({ companyId: f.company, switchRequestId: requestId, snapshot: ready.readinessSnapshot })
  expect(sql(`SELECT to_jsonb(readiness_snapshot) FROM public.supplier_switch_requests WHERE id=${quote(requestId)};`)).toMatchObject({ ready: true, contract_id: f.contract })
  const intent = sql<JobRow>(`SELECT to_jsonb(j) FROM public.customer_operation_jobs j WHERE company_id=${quote(f.company)} AND job_type='dispatch_lifecycle_notification'
    AND payload->>'event_type'='supplier_switch.requested';`)
  expect(intent).toMatchObject({ status: 'queued', customer_site_id: f.site, metering_point_id: f.point })
  const notified = await processJob(intent)
  expect(notified).toMatchObject({ status: 'completed', result: { queued: true, eventKey: 'switch.started' } })
  await updateJob(intent, { status: notified.status, result: notified.result })
  const before = effects(f)
  expect(before.switches).toHaveLength(1); expect(before.notifications).toHaveLength(1); expect(before.email).toHaveLength(1); expect(before.outbound).toHaveLength(1)
  expect(before.email).toEqual([expect.objectContaining({ status: 'queued', attempts: 0, provider_message_id: null })])
  expect(before.outbound).toEqual([expect.objectContaining({ status: 'queued', attempts: 0 })])
  expect(before).toMatchObject({ sentEmail: 0, sentEdiel: 0, activeSupply: 0 })
  // Actual lifecycle consumer repeats against its permanent email key. The
  // completed notification intent and already queued outboxes stay unchanged.
  await expect(processJob(intent)).resolves.toMatchObject({ status: 'completed', result: { queued: true } })
  expect(effects(f)).toEqual(before); expect(forbiddenFetches).toBe(0)
  console.log('SITE_POSITIVE_CONTINUATION_NATIVE_PASS actual_inbound_consumer=true exact_contract_bound=true actual_z03_preparation=true durable_switch=1 actual_notification_consumer=true unsent_email=1 unsent_ediel=1 retry_effects_unchanged=true provider_dispatch=0 supply_activation=0')
})
