import {beforeEach,expect,it} from 'vitest'
import {spawn} from 'node:child_process'
import {randomUUID} from 'node:crypto'
import {sendEdielMessageViaSmtp} from '@/lib/ediel/transport'
import {reportFreshEdielBusinessIncident,readFreshEdielBusinessIncident} from '@/lib/ediel/incidents/freshBusinessIncident'
import {seedNativeEscoFixture,qualifyNativeEscoFixture,resetNativeEscoFixture,nativeEscoSql as sql,nativeEscoLiteral as lit,nativeEscoExternal as external,NATIVE_ESCO_DB as DB} from './fixtures/ediel-service-evidence-native'
beforeEach(resetNativeEscoFixture)
async function original(){const f=await seedNativeEscoFixture();await qualifyNativeEscoFixture(f);const positive=await f.utilts('accepted','NATIVE-LATE-ISSUE');await positive.persist();const ack=await positive.ack();await positive.finalize(ack);return {f,positive,ack,command:{commandId:randomUUID(),sourceMessageId:positive.source.id,ackMessageId:ack.id,scopeReference:'NATIVE-LATE-ISSUE',finding:{code:'late_internal_business_error' as const,summary:'Synthetic new operator business check; this report is not a new protocol rejection.'}}}}
const counts=(c:string)=>sql<Record<string,number>>(`SELECT jsonb_build_object('incidents',(SELECT count(*) FROM gridex_ediel_business_incidents.incidents WHERE company_id=${lit(c)}),'plans',(SELECT count(*) FROM gridex_ediel_business_incidents.plans WHERE company_id=${lit(c)}),'events',(SELECT count(*) FROM gridex_ediel_business_incidents.events WHERE company_id=${lit(c)}))`)
it('fresh reported incident requires actual accepted original ACK and positive own scope; retry attempts no writes or ACK/history/outbox effects',async()=>{
 const {f,positive,ack,command}=await original(),input={companyId:f.ids.company,actorUserId:f.ids.actor,command},initial=f.effects()
 await expect(reportFreshEdielBusinessIncident(input)).rejects.toMatchObject({message:expect.stringContaining('ediel_business_incident_actual_accepted_ack_required')});expect(counts(f.ids.company)).toEqual({incidents:0,plans:0,events:0});expect(f.effects()).toEqual(initial)
 await sendEdielMessageViaSmtp(ack,{actorUserId:f.ids.actor,smtpMimeMode:'nodemailer-attachment'});const stable=f.effects()
 const found=await reportFreshEdielBusinessIncident(input);expect(found).toMatchObject({status:'reported',findingValidated:false,ackHistoryChanged:false,contactStatus:'held',correctionStatus:'held',trafficAuthorized:false});expect(counts(f.ids.company)).toEqual({incidents:1,plans:2,events:1});expect(f.effects()).toEqual(stable)
 const trigger='no_incident_replay_'+f.ids.company.replaceAll('-','')
 sql(`CREATE FUNCTION gridex_ediel_business_incidents.${trigger}() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.company_id=${lit(f.ids.company)}::uuid THEN RAISE EXCEPTION 'attempted_incident_replay_effect';END IF;RETURN NEW;END$$;`)
 for(const table of ['incidents','plans','events'])sql(`CREATE TRIGGER ${trigger} BEFORE INSERT ON gridex_ediel_business_incidents.${table} FOR EACH ROW EXECUTE FUNCTION gridex_ediel_business_incidents.${trigger}()`)
 try{const replays=await Promise.all([reportFreshEdielBusinessIncident(input),reportFreshEdielBusinessIncident(input),readFreshEdielBusinessIncident({...input,incidentId:found.incidentId})]);for(const r of replays)expect(r).toEqual(found);expect(counts(f.ids.company)).toEqual({incidents:1,plans:2,events:1});expect(f.effects()).toEqual(stable)}finally{for(const table of ['incidents','plans','events'])sql(`DROP TRIGGER ${trigger} ON gridex_ediel_business_incidents.${table}`)}
 await expect(reportFreshEdielBusinessIncident({...input,command:{...command,scopeReference:'FOREIGN-IDE'}})).rejects.toMatchObject({message:expect.stringContaining('actual_positive_scope_required')});expect(f.effects()).toEqual(stable)
 expect((await positive.ack()).id).toBe(ack.id);expect(f.effects()).toEqual(stable);expect(external.send).toHaveBeenCalledTimes(2)
})
it('last incident audit failure rolls back incident and both held plans without touching the accepted original',async()=>{
 const {f,ack,command}=await original();await sendEdielMessageViaSmtp(ack,{actorUserId:f.ids.actor,smtpMimeMode:'nodemailer-attachment'});const stable=f.effects(),trigger='fail_incident_'+f.ids.company.replaceAll('-','')
 sql(`CREATE FUNCTION gridex_ediel_business_incidents.${trigger}() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.company_id=${lit(f.ids.company)}::uuid THEN RAISE EXCEPTION 'native_last_incident_audit_failure';END IF;RETURN NEW;END$$;CREATE TRIGGER ${trigger} BEFORE INSERT ON gridex_ediel_business_incidents.events FOR EACH ROW EXECUTE FUNCTION gridex_ediel_business_incidents.${trigger}()`)
 try{await expect(reportFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:f.ids.actor,command})).rejects.toMatchObject({message:expect.stringContaining('native_last_incident_audit_failure')});expect(counts(f.ids.company)).toEqual({incidents:0,plans:0,events:0});expect(f.effects()).toEqual(stable)}finally{sql(`DROP TRIGGER ${trigger} ON gridex_ediel_business_incidents.events`)}
})
it.each(['company','global'] as const)('real pending %s DENY serializes before fresh incident qualification and yields zero effects',async scope=>{
 const {f,ack,command}=await original();await sendEdielMessageViaSmtp(ack,{actorUserId:f.ids.actor,smtpMimeMode:'nodemailer-attachment'});const stable=f.effects()
 const blocker=spawn('psql',[DB,'-XAtq','-v','ON_ERROR_STOP=1'],{stdio:['pipe','pipe','pipe']})
 const ready=new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('native_incident_deny_timeout')),10000);blocker.stdout.on('data',chunk=>{if(String(chunk).includes('incident-deny-locked')){clearTimeout(timeout);resolve()}});blocker.on('error',reject)})
 blocker.stdin.write(`BEGIN;LOCK TABLE public.user_permission_overrides IN SHARE ROW EXCLUSIVE MODE;INSERT INTO public.user_permission_overrides(user_id,company_id,permission_key,effect,is_active,valid_from,valid_to) VALUES(${lit(f.ids.actor)},${scope==='company'?lit(f.ids.company):'NULL'},'communication.write','deny',true,now()-interval '1 minute',NULL);SELECT 'incident-deny-locked';\n`)
 await ready;const pending=reportFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:f.ids.actor,command}).then(value=>({value,error:null}),error=>({value:null,error}))
 try{let observed=false;for(let n=0;n<100;n++){observed=sql<boolean>(`SELECT to_jsonb(EXISTS(SELECT FROM pg_stat_activity a JOIN pg_locks l ON l.pid=a.pid WHERE a.wait_event_type='Lock' AND a.query LIKE '%ediel_report_fresh_business_incident_v1%' AND l.relation='public.user_permission_overrides'::regclass AND l.mode='ShareLock' AND NOT l.granted AND a.pid<>pg_backend_pid()))`);if(observed)break;await new Promise(resolve=>setTimeout(resolve,25))}expect(observed,'actual HTTP incident creation awaits current DENY fence before source').toBe(true)}finally{blocker.stdin.end('COMMIT;\n')}
 const result=await pending;expect(result.value).toBeNull();expect(result.error).toMatchObject({message:expect.stringContaining('ediel_business_incident_actor_forbidden')});expect(counts(f.ids.company)).toEqual({incidents:0,plans:0,events:0});expect(f.effects()).toEqual(stable);expect(external.send).toHaveBeenCalledTimes(2)
})
