import {expect,it} from 'vitest'
import {randomUUID} from 'node:crypto'
import {createDecisionOriginalNativeFixture,decisionNativeSql as sql,hash,literal,signSyntheticDecisionOriginalPolicy} from './helpers/ediel-decision-original-native-fixture'

it('actual installed six-class custody has private table ACL, preserved native guards and explicit unassigned current keys',()=>{
 expect(sql(`SELECT jsonb_build_object('classes',(SELECT count(*)>=6 FROM gridex_ediel_retention.decision_evidence_catalog),'app_table_read',has_table_privilege('authenticated','gridex_ediel_retention.decision_evidence_policies','SELECT'),'service_purge',has_function_privilege('service_role','public.ediel_purge_decision_evidence_retention_v1(uuid,uuid,uuid)','EXECUTE'),'role_assigned',(SELECT count(*) FROM public.role_permissions rp JOIN public.permissions p ON p.id=rp.permission_id OR rp.permission_id IS NULL AND p.key=rp.permission_key WHERE p.key IN(SELECT permission_key FROM gridex_ediel_retention.decision_evidence_catalog)))`)).toEqual({classes:true,app_table_read:false,service_purge:false,role_assigned:0})
},30000)
it('actual GoTrue/JWT archive and separate review erase only bound old decision bytes, retaining original source and immutable history',async()=>{
 const f=await createDecisionOriginalNativeFixture(randomUUID()+'Aa1!'),document=Buffer.from('SYNTHETIC native decision-original policy; no real legal competence'),parameters={p_company_id:f.companyId,p_policy_id:''},submission={p_company_id:f.companyId,p_actor_user_id:f.actor.id,p_retention_class:f.basis.retentionClass,p_target_id:f.targetId,p_document_base64:document.toString('base64'),p_issuer_receipt:signSyntheticDecisionOriginalPolicy(f.companyId,f.issuerId,f.basis,document)}
 const pending=await f.actor.client.rpc('ediel_submit_decision_evidence_retention_v1',submission);expect(pending.error).toBeNull();expect(pending.data.issuerQualified).toBe(true);parameters.p_policy_id=pending.data.policyId
 expect((await f.actor.client.rpc('ediel_review_decision_evidence_retention_v1',{...parameters,p_actor_user_id:f.actor.id,p_outcome:'approve',p_reason:'SYNTHETIC self review denied'})).error).not.toBeNull()
 expect((await f.actor.client.rpc('ediel_review_decision_evidence_retention_v1',{...parameters,p_actor_user_id:f.reviewer.id,p_outcome:'approve',p_reason:'SYNTHETIC actor spoof denied'})).error).not.toBeNull()
 const reviewed=await f.reviewer.client.rpc('ediel_review_decision_evidence_retention_v1',{...parameters,p_actor_user_id:f.reviewer.id,p_outcome:'approve',p_reason:'SYNTHETIC current separate native review'});expect(reviewed.error).toBeNull();expect(reviewed.data.status).toBe('approved')
 const readOriginal={p_company_id:f.companyId,p_actor_user_id:f.readonly.id,p_retention_class:f.basis.retentionClass,p_target_id:f.targetId,p_include_document:false}
 expect((await f.readonly.client.rpc('ediel_read_retention_decision_original_v1',readOriginal)).data).toMatchObject({bytesAvailable:true,documentBase64:null,documentHash:f.sourceHash})
 expect((await f.readonly.client.rpc('ediel_read_retention_decision_original_v1',{...readOriginal,p_include_document:true})).error).not.toBeNull()
 expect((await f.foreign.client.rpc('ediel_read_retention_decision_original_v1',{...readOriginal,p_actor_user_id:f.foreign.id})).error).not.toBeNull()
 sql(`INSERT INTO public.user_permission_overrides(user_id,company_id,permission_key,effect,is_active) VALUES(${literal(f.reviewer.id)},${literal(f.companyId)},'ediel.retention.review','deny',true)`)
 expect((await f.actor.client.rpc('ediel_purge_decision_evidence_retention_v1',{...parameters,p_actor_user_id:f.actor.id})).error).not.toBeNull()
 expect(sql(`SELECT to_jsonb(document_bytes IS NOT NULL) FROM gridex_ediel_retention.blob_decisions WHERE id=${literal(f.targetId)}`)).toBe(true)
 sql(`DELETE FROM public.user_permission_overrides WHERE user_id=${literal(f.reviewer.id)} AND company_id=${literal(f.companyId)} AND permission_key='ediel.retention.review'`)
 const complete=await f.actor.client.rpc('ediel_purge_decision_evidence_retention_v1',{...parameters,p_actor_user_id:f.actor.id});expect(complete.error).toBeNull();expect(complete.data).toMatchObject({status:'purged',targetId:f.targetId,sourceHash:f.sourceHash,bytesAvailable:false,replay:false})
 expect((await f.actor.client.rpc('ediel_purge_decision_evidence_retention_v1',{...parameters,p_actor_user_id:f.actor.id})).data.replay).toBe(true)
 const after=await f.readonly.client.rpc('ediel_read_retention_decision_original_v1',readOriginal);expect(after.error).toBeNull();expect(after.data).toMatchObject({bytesAvailable:false,documentBase64:null,documentHash:f.sourceHash,documentByteLength:f.sourceDocument.length,authority:'none'});expect(after.data.purgedAt).toBeTruthy()
 expect(sql(`SELECT jsonb_build_object('bytes',d.document_bytes,'receipt',gridex_ediel_retention.blob_receipt_v1(d),'revoked',(SELECT count(*) FROM gridex_ediel_retention.blob_revocations WHERE decision_id=d.id),'raw',(SELECT raw_payload IS NOT NULL FROM public.ediel_messages WHERE id=${literal(f.sourceMessageId)}),'audit',(SELECT count(*) FROM public.audit_logs WHERE entity_id=d.id::text AND action='ediel.retention.decision_original_bytes_removed')) FROM gridex_ediel_retention.blob_decisions d WHERE id=${literal(f.targetId)}`)).toEqual({bytes:null,receipt:null,revoked:1,raw:true,audit:1})
 const readPolicy=await f.readonly.client.rpc('ediel_read_decision_evidence_policy_v1',{...parameters,p_actor_user_id:f.readonly.id,p_include_document:false});expect(readPolicy.error).toBeNull();expect(readPolicy.data).toMatchObject({documentHash:hash(document),currentQualified:false,bytesAvailable:true,authority:'none'})
 console.log(JSON.stringify({kind:'decision_original_native',mechanismOnly:true,source:'actual raw capture and protected unapproved original archive; no market source/accepted owner seeded',legalAuthority:'synthetic competence; not real issuer/deadline',classesExecuted:['blob_retention_decision_original_bytes'],allSixNativeAccepted:false}))
},90000)
