import {randomUUID} from 'node:crypto'
import {expect,it,vi} from 'vitest'
vi.mock('server-only',()=>({}))
vi.mock('@/lib/customer-notifications/notificationOrchestrator',()=>({enqueueCustomerLifecycleNotification:async()=>null}))
vi.mock('@/lib/website/customerApplicationWorkflowBridge',()=>({transitionCorrelatedCustomerApplicationWorkflow:async()=>null}))
import {seedNormalSwitchNativeFixture,nativeSql as sql,literal} from './helpers/ediel-normal-switch-native-fixture'
import {createCustomerRecordRetentionNativeUser as user} from './helpers/ediel-customer-record-retention-native-fixture'
const classes=['masterdata_declaration_agreement_original_bytes','masterdata_declaration_source_original_bytes','masterdata_preparation_agreement_original_bytes','masterdata_preparation_source_original_bytes','metering_contract_request_agreement_original_bytes','metering_contract_request_source_original_bytes','metering_method_event_agreement_original_bytes','metering_method_event_source_original_bytes'] as const
it('installed eight actual-original adapters have explicit native class/source ownership and closed private copy authority',()=>{
 const result=sql<{classes:string[];views:number;volatile:string;privateRows:number;privateExecute:number}>(`SELECT jsonb_build_object('classes',(SELECT jsonb_agg(retention_class ORDER BY retention_class) FROM gridex_ediel_retention.contract_copy_catalog),'views',(SELECT count(*) FROM gridex_ediel_retention.contract_copy_catalog c JOIN pg_class p ON p.relname=c.view_name AND p.relnamespace='gridex_ediel_retention'::regnamespace WHERE p.relkind='v' AND p.relowner='gridex_ediel_retention_owner'::regrole),'volatile',(SELECT provolatile FROM pg_proc WHERE oid='gridex_ediel_retention.contract_copy_source_current_v1(uuid,text,text,uuid)'::regprocedure),'privateRows',(SELECT count(*) FROM unnest(ARRAY['anon','authenticated','service_role']) role WHERE has_table_privilege(role,'gridex_ediel_retention.contract_copy_revocations','SELECT')),'privateExecute',(SELECT count(*) FROM unnest(ARRAY['anon','authenticated','service_role']) role WHERE has_function_privilege(role,'gridex_ediel_retention.contract_copy_source_current_v1(uuid,text,text,uuid)','EXECUTE')))`)
 expect(result).toEqual({classes:[...classes].sort(),views:8,volatile:'v',privateRows:0,privateExecute:0})
},30000)
it('genuine signed-publication/PDF archive and actual GoTrue class readers never invent legacy source approvals or copy decisions for absent targets',async()=>{
 const f=await seedNormalSwitchNativeFixture({deferOriginal:true}),password=randomUUID()+'Aa1!',reader=await user(f.companyId,['ediel.retention.read','ediel.retention.record_decision_evidence'],password),target=randomUUID()
 const before=sql(`SELECT jsonb_build_object('declarations',(SELECT count(*) FROM gridex_customer_masterdata.signed_declarations WHERE company_id=${literal(f.companyId)}),'methodDeclarations',(SELECT count(*) FROM gridex_metering_method_changes.contract_request_declarations WHERE company_id=${literal(f.companyId)}),'events',(SELECT count(*) FROM gridex_metering_method_changes.events WHERE company_id=${literal(f.companyId)}),'copies',(SELECT count(*) FROM gridex_ediel_retention.contract_copy_revocations WHERE company_id=${literal(f.companyId)}),'policies',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_policies WHERE company_id=${literal(f.companyId)}),'marketOriginals',(SELECT count(*) FROM gridex_received_sources.switch_originals WHERE company_id=${literal(f.companyId)}))`)
 expect(before).toEqual({declarations:0,methodDeclarations:0,events:0,copies:0,policies:0,marketOriginals:0})
 for(const retentionClass of classes){const r=await reader.client.rpc('ediel_read_retention_decision_original_v1',{p_company_id:f.companyId,p_actor_user_id:reader.id,p_retention_class:retentionClass,p_target_id:target,p_include_document:false});expect(r.error?.message).toContain('decision_evidence_original_scope_required');expect(r.data).toBeNull()}
 const changed=await reader.client.rpc('ediel_read_retention_decision_original_v1',{p_company_id:randomUUID(),p_actor_user_id:reader.id,p_retention_class:classes[0],p_target_id:target,p_include_document:true});expect(changed.error).not.toBeNull();expect(changed.data).toBeNull()
 expect(sql(`SELECT jsonb_build_object('declarations',(SELECT count(*) FROM gridex_customer_masterdata.signed_declarations WHERE company_id=${literal(f.companyId)}),'methodDeclarations',(SELECT count(*) FROM gridex_metering_method_changes.contract_request_declarations WHERE company_id=${literal(f.companyId)}),'events',(SELECT count(*) FROM gridex_metering_method_changes.events WHERE company_id=${literal(f.companyId)}),'copies',(SELECT count(*) FROM gridex_ediel_retention.contract_copy_revocations WHERE company_id=${literal(f.companyId)}),'policies',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_policies WHERE company_id=${literal(f.companyId)}),'marketOriginals',(SELECT count(*) FROM gridex_received_sources.switch_originals WHERE company_id=${literal(f.companyId)}))`)).toEqual(before)
 // Positive source archive/review and each physical-copy purge are separate
 // follow-up producer scenarios; none is inferred from these negative reads.
},240000)
