import {futureNativeSupplyDate} from './helpers/ediel-normal-switch-native-fixture'
import {createHash,randomUUID} from 'node:crypto'
import {afterEach,expect,it,vi} from 'vitest'
const effects=vi.hoisted(()=>({smtp:vi.fn()}))
vi.mock('server-only',()=>({}))
vi.mock('nodemailer',()=>({default:{createTransport:()=>({sendMail:effects.smtp})}}))
vi.mock('@/lib/customer-notifications/notificationOrchestrator',()=>({enqueueCustomerLifecycleNotification:async()=>null}))
vi.mock('@/lib/website/customerApplicationWorkflowBridge',()=>({transitionCorrelatedCustomerApplicationWorkflow:async()=>null}))
import {supabaseService} from '@/lib/supabase/service'
import {createBilateralCustomerSourceFixture} from './helpers/ediel-bilateral-customer-native-fixture'
import {attachAiPurposeSourceFixture} from './helpers/ediel-ai-purpose-native-fixture'
import {attachNetworkRegistrySourceFixture} from './helpers/ediel-network-registry-native-fixture'
import {nativeSql as sql,literal} from './helpers/ediel-normal-switch-native-fixture'
import {archiveAiPurposeSource,reviewAiPurposeSource} from '@/lib/ediel/production/aiPurposeSource'
import {archiveNetworkRegistrySource,reviewNetworkRegistrySource,revokeNetworkRegistrySource,readNetworkRegistrySourceBytes} from '@/lib/ediel/production/networkRegistrySource'
import {archiveBilateralCustomerSource,reviewBilateralCustomerSourceArtifact} from '@/lib/ediel/production/bilateralCustomerSource'
import {approveSafeMasterdataChanges} from '@/lib/ediel/safeApplyReview'
import {prepareAndQueueAiList} from '@/lib/ediel/flows/aiListFlow'
import {sendEdielMessageViaSmtp} from '@/lib/ediel/transport'
import {getEdielMessageById} from '@/lib/ediel/db'
import {parseAiBiTechnicalFile} from '@/lib/ediel/aiListFormat'
afterEach(()=>{vi.unstubAllEnvs();effects.smtp.mockReset()})
it('genuine customer and legal/network original producers supply dated AI intent/CSV/storage/queue/immutable transport; revoked fresh source and BI export stop',async()=>{
 for(const[k,v]of Object.entries({EDIEL_SHARED_MAILBOX_ADDRESS:'synthetic@example.invalid',EDIEL_APP_DKIM_ENABLED:'false',EMAIL_PROVIDER:'resend',EDIEL_SMTP_FROM:'synthetic@example.invalid',EDIEL_SMTP_USER:'synthetic@example.invalid',EDIEL_SMTP_PASS:'synthetic-only',EDIEL_EMAIL_PROVIDER:'strato'}))vi.stubEnv(k,v)
 const f=await createBilateralCustomerSourceFixture(email=>effects.smtp.mockResolvedValue({accepted:[email],rejected:[],messageId:randomUUID(),response:'250 synthetic accepted'})),purpose=await attachAiPurposeSourceFixture(f),network=await attachNetworkRegistrySourceFixture(f)
 const customer=await archiveBilateralCustomerSource({...f.submission('SYNTHETIC actual dated customer',f.pdf('full chain actual customer')),companyId:f.companyId,actorUserId:f.uploader.id});expect((await reviewBilateralCustomerSourceArtifact({...customer,companyId:f.companyId,actorUserId:f.reviewer.id,decision:'approve',reason:'Synthetic actual dated customer review',clause:f.clause})).status).toBe('authorized');expect(await approveSafeMasterdataChanges({actorUserId:f.reviewer.id,edielMessageId:f.sourceMessageId})).toMatchObject({status:'applied'})
 const legal=await archiveAiPurposeSource({...purpose.submission('SYNTHETIC full native AI purpose',purpose.pdf('actual purpose')),companyId:f.companyId,actorUserId:purpose.uploader.id});expect((await reviewAiPurposeSource({...legal,companyId:f.companyId,actorUserId:purpose.reviewer.id,decision:'approve',reason:'Synthetic independent actual original legal review',clause:purpose.clause})).status).toBe('authorized')
 const route=randomUUID(),profile=randomUUID();sql(`INSERT INTO public.communication_routes(id,company_id,route_name,route_scope,grid_owner_id,environment_type,is_active,target_email) VALUES(${literal(route)},${literal(f.companyId)},'Disposable full native AI','meter_values',${literal(f.gridId)},'bilateral_test',true,'recipient@example.invalid');INSERT INTO public.ediel_route_profiles(id,company_id,communication_route_id,route_name,environment,message_standard,sender_ediel_id,receiver_ediel_id,application_reference,is_enabled,transport_security_mode,smtp_to,receiver_email,message_family,business_code) VALUES(${literal(profile)},${literal(f.companyId)},${literal(route)},'Disposable full native AI','test','ai_list',${literal(f.sender)},${literal(f.receiver)},'',true,'unencrypted','recipient@example.invalid','recipient@example.invalid','AI_LIST','AI')`)
 const request={actorUserId:purpose.uploader.id,companyId:f.companyId,listType:'AI' as const,customerId:f.customerId,siteId:f.siteId,meteringPointId:f.pointId,receiverEdielId:f.receiver,fromDate:futureNativeSupplyDate(),toDate:futureNativeSupplyDate(21),communicationRouteId:route,environment:'test' as const}
 await expect(prepareAndQueueAiList(request)).rejects.toThrow(/network_registry/)
 const missing=await archiveNetworkRegistrySource({...network.submission('SYNTHETIC missing network issuer',network.pdf('held'), 'pending',false),companyId:f.companyId,actorUserId:network.uploader.id});expect((await reviewNetworkRegistrySource({...missing,companyId:f.companyId,actorUserId:network.reviewer.id,decision:'approve',reason:'Synthetic missing network evidence',clause:network.clause})).status).toBe('held')
 const source=await archiveNetworkRegistrySource({...network.submission('SYNTHETIC full native network registry',network.pdf('actual registry')),companyId:f.companyId,actorUserId:network.uploader.id});await expect(reviewNetworkRegistrySource({...source,companyId:f.companyId,actorUserId:network.uploader.id,decision:'approve',reason:'Synthetic self review forbidden',clause:network.clause})).rejects.toBeTruthy();expect((await reviewNetworkRegistrySource({...source,companyId:f.companyId,actorUserId:network.reviewer.id,decision:'approve',reason:'Synthetic actual independent registry original review',clause:network.clause})).status).toBe('authorized');expect(Buffer.from((await readNetworkRegistrySourceBytes({companyId:f.companyId,actorUserId:network.uploader.id,artifactId:source.artifactId})).bytes)).toEqual(network.pdf('actual registry'))
 const queued=await prepareAndQueueAiList(request);expect(queued.status).toBe('queued');expect(queued.company_id).toBe(f.companyId);expect(queued.intent_id).toBeTruthy();expect(queued.message_standard).toBe('ai_list');const technical=parseAiBiTechnicalFile(queued.raw_payload!,'AI');expect(technical.rows).toHaveLength(2);expect(queued.raw_payload).toContain('SYNTHETIC DATED CUSTOMER')
 const ownership=sql<Record<string,unknown>>(`SELECT jsonb_build_object('origins',(SELECT count(*) FROM gridex_ai_processing.outbound_origins WHERE intent_id=${literal(queued.intent_id)}),'bindings',(SELECT count(*) FROM gridex_ai_processing.outbound_origin_bindings WHERE intent_id=${literal(queued.intent_id)}),'hash',(SELECT encode(sha256(convert_to(raw_payload,'UTF8')),'hex') FROM gridex_ai_processing.outbound_origins WHERE intent_id=${literal(queued.intent_id)}),'decision',(SELECT processing_decision_id FROM gridex_ai_processing.outbound_origins WHERE intent_id=${literal(queued.intent_id)}))`);expect(ownership).toMatchObject({origins:1,bindings:1,hash:createHash('sha256').update(queued.raw_payload!,'utf8').digest('hex')})
 effects.smtp.mockResolvedValue({accepted:['recipient@example.invalid'],rejected:[],messageId:randomUUID(),response:'250 synthetic accepted'});const count=effects.smtp.mock.calls.length;await sendEdielMessageViaSmtp(queued,{actorUserId:purpose.uploader.id,smtpMimeMode:'nodemailer-attachment'});expect(effects.smtp.mock.calls.length).toBe(count+1)
 await expect(prepareAndQueueAiList({...request,listType:'BI'})).rejects.toThrow();expect(sql(`SELECT to_jsonb(count(*)) FROM public.ediel_messages WHERE company_id=${literal(f.companyId)} AND direction='outbound' AND message_code='BI'`)).toBe(0)
 expect((await revokeNetworkRegistrySource({...source,companyId:f.companyId,actorUserId:network.reviewer.id,reason:'Synthetic withdrawal of actual network source'})).status).toBe('held');await expect(prepareAndQueueAiList(request)).rejects.toThrow(/network_registry/)
 // Immutable original disclosure is a separate current READ phase. It uses
 // its actual native binding despite withdrawn current registry authority and
 // produces no new intent, original, queue action or provider invocation.
 const immutableCounts=()=>sql(`SELECT jsonb_build_object('messages',(SELECT count(*) FROM public.ediel_messages WHERE company_id=${literal(f.companyId)}),'intents',(SELECT count(*) FROM public.ediel_message_intents WHERE company_id=${literal(f.companyId)}),'origins',(SELECT count(*) FROM gridex_ai_processing.outbound_origins WHERE company_id=${literal(f.companyId)}),'bindings',(SELECT count(*) FROM gridex_ai_processing.outbound_origin_bindings WHERE company_id=${literal(f.companyId)}))`)
 const readCounts=immutableCounts(),readProviderCalls=effects.smtp.mock.calls.length
 const readOrigin=()=>supabaseService.rpc('gridex_ai_outbound_origin_status_v1',{p_company_id:f.companyId,p_actor_user_id:f.reader.id,p_intent_id:queued.intent_id!})
 const readResult=await readOrigin();expect(readResult.error).toBeNull();expect(readResult.data).toMatchObject({status:'bound',messageId:queued.id,payloadHash:createHash('sha256').update(queued.raw_payload!,'utf8').digest('hex')})
 expect(immutableCounts()).toEqual(readCounts);expect(effects.smtp.mock.calls.length).toBe(readProviderCalls)
 sql(`UPDATE auth.users SET banned_until=clock_timestamp()+interval '1 hour' WHERE id=${literal(f.reader.id)}`)
 try{expect((await readOrigin()).error?.message).toContain('ediel_tenant_actor_forbidden');expect(immutableCounts()).toEqual(readCounts)}finally{sql(`UPDATE auth.users SET banned_until=NULL WHERE id=${literal(f.reader.id)}`)}
 const sent=await getEdielMessageById(queued.id);expect(sent).not.toBeNull();const acceptedCount=effects.smtp.mock.calls.length;await sendEdielMessageViaSmtp(sent!,{actorUserId:purpose.uploader.id,smtpMimeMode:'nodemailer-attachment'});expect(effects.smtp.mock.calls.length).toBe(acceptedCount)
 expect((await supabaseService.from('ediel_messages').select('raw_payload').eq('id',queued.id).single()).data?.raw_payload).toBe(queued.raw_payload)
},120000)
