import {createClient,type SupabaseClient} from '@supabase/supabase-js'
import {createHash,createHmac,randomUUID} from 'node:crypto'
import {afterEach,expect,it,vi} from 'vitest'
const io=vi.hoisted(()=>({smtp:vi.fn(),client:null as SupabaseClient|null}))
vi.mock('nodemailer',()=>({default:{createTransport:()=>({sendMail:io.smtp})}}))
vi.mock('@/lib/supabase/server',()=>({createSupabaseServerClient:async()=>{if(!io.client)throw Error('native_session_required');return io.client}}))
vi.mock('@/lib/customer-notifications/notificationOrchestrator',()=>({enqueueCustomerLifecycleNotification:async()=>null}))
vi.mock('@/lib/website/customerApplicationWorkflowBridge',()=>({transitionCorrelatedCustomerApplicationWorkflow:async()=>null}))
import {supabaseService} from '@/lib/supabase/service'
import {purgeBlobRetention} from '@/lib/ediel/retention/blobLifecycleRetention'
import {seedNormalSwitchNativeFixture,nativeSql as sql,literal} from './helpers/ediel-normal-switch-native-fixture'
import {createRequestedChangeSupplyFixture} from './helpers/ediel-requested-change-native-fixture'
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex')
afterEach(()=>{vi.unstubAllEnvs();io.smtp.mockReset();io.client=null})
async function user(company:string,permissions:string[]){
 const email=randomUUID()+'@example.invalid',password=randomUUID()+'Aa1!',created=await supabaseService.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull();const id=created.data.user!.id
 sql(`INSERT INTO public.company_memberships(company_id,user_id,membership_role,status,accepted_at,metadata,role,is_active,joined_at,role_key) VALUES(${literal(company)},${literal(id)},'member','active',now(),'{}','member',true,now(),'member');UPDATE public.user_profiles SET user_status='active' WHERE id=${literal(id)};INSERT INTO public.user_permissions(user_id,company_id,permission_id,permission_key) SELECT ${literal(id)},${literal(company)},id,key FROM public.permissions WHERE key=ANY(ARRAY[${permissions.map(literal).join(',')}])`)
 const client=createClient('http://127.0.0.1:54321',process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false}});expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();return {id,client}
}
/** Actual local contract/POA publication→native Z03 source/prepare/enter/finish
 * creates the immutable transport archive. Only SMTP observation and legal
 * issuer competence are synthetic; neither proves external delivery/authority.
 * Storage upload/download/remove use actual local HTTP and the real user JWT. */
it('actual native MIME retention revokes fresh byte authority before authenticated HTTP Storage purge and preserves journal continuity',async()=>{
 for(const[k,v]of Object.entries({EDIEL_SHARED_MAILBOX_ADDRESS:'synthetic@example.invalid',EDIEL_APP_DKIM_ENABLED:'false',EMAIL_PROVIDER:'resend',EDIEL_SMTP_FROM:'synthetic@example.invalid',EDIEL_SMTP_USER:'synthetic@example.invalid',EDIEL_SMTP_PASS:'synthetic-only',EDIEL_EMAIL_PROVIDER:'strato'}))vi.stubEnv(k,v)
 const f=await seedNormalSwitchNativeFixture({provider:email=>io.smtp.mockResolvedValue({accepted:[email],rejected:[],messageId:randomUUID(),response:'250 synthetic accepted'})})
 const target=sql<{id:string;path:string;sha:string;length:number}>(`SELECT jsonb_build_object('id',p.id,'path',p.metadata->>'archive_path','sha',p.metadata->>'archived_mime_sha256','length',(p.metadata->>'archived_mime_bytes')::int) FROM public.ediel_message_payloads p JOIN gridex_ediel_transport.attempts a ON a.company_id=p.company_id AND a.message_id=p.ediel_message_id AND a.binding->>'mimePayloadSnapshotId'=p.id::text WHERE p.company_id=${literal(f.companyId)} AND p.ediel_message_id=${literal(f.originalZ03.id)} AND a.entered_at IS NOT NULL ORDER BY p.created_at DESC LIMIT 1`)
 expect(target.id).toBeTruthy();const bucket=supabaseService.storage.from('ediel-files'),before=await bucket.download(target.path);expect(before.error).toBeNull();const originalBytes=Buffer.from(await before.data!.arrayBuffer());expect(hash(originalBytes)).toBe(target.sha);expect(originalBytes.length).toBe(target.length)
 const submitter=await user(f.companyId,['communication.read','communication.write','ediel.retention.submit','ediel.retention.purge','ediel.retention.mime_bytes']),reviewer=await user(f.companyId,['ediel.retention.review','ediel.retention.mime_bytes']),otherCompany=randomUUID()
 const document=Buffer.from('SYNTHETIC exact MIME class deadline; no actual legal issuer'),legal=Buffer.from('SYNTHETIC competence only'),key=Buffer.from('SYNTHETIC ONLY MIME retention HMAC key 01234567890123456789'),issuer=randomUUID()
 sql(`INSERT INTO public.companies(id,name,status) VALUES(${literal(otherCompany)},'Synthetic unrelated native tenant','active');INSERT INTO gridex_ediel_retention.issuers(id,company_id,legal_reference,legal_evidence,legal_hash,signing_key,valid_from,valid_to) VALUES(${literal(issuer)},${literal(f.companyId)},'SYNTHETIC COMPETENCE ONLY',decode('${legal.toString('hex')}','hex'),${literal(hash(legal))},decode('${key.toString('hex')}','hex'),'2020-01-01','2099-01-01')`)
 const basis=sql<{targetHash:string;sourceHash:string;messageId:string}>(`SELECT gridex_ediel_retention.blob_basis_v1(${literal(f.companyId)},'transport_raw_mime_bytes',${literal(target.id)})`),payload=Buffer.from(JSON.stringify({format:'ediel_blob_retention_policy_v1',retentionClass:'transport_raw_mime_bytes',companyId:f.companyId,targetId:target.id,messageId:basis.messageId,sourceHash:basis.sourceHash,targetHash:basis.targetHash,documentHash:hash(document),issuerLegalReference:'SYNTHETIC COMPETENCE ONLY',legalBasisReference:'SYNTHETIC separate byte-class policy',issuedAt:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),retainUntil:new Date(Date.now()-1000).toISOString()})),receipt={issuerId:issuer,payloadBase64:payload.toString('base64'),signatureHex:createHmac('sha256',key).update(payload).digest('hex')}
 const submitted=await submitter.client.rpc('ediel_submit_blob_retention_v1',{p_company_id:f.companyId,p_actor_user_id:submitter.id,p_retention_class:'transport_raw_mime_bytes',p_target_id:target.id,p_document_base64:document.toString('base64'),p_issuer_receipt:receipt});expect(submitted.error).toBeNull();expect(submitted.data.issuerQualified).toBe(true);const decisionId=submitted.data.decisionId
 const reviewed=await reviewer.client.rpc('ediel_review_blob_retention_v1',{p_company_id:f.companyId,p_actor_user_id:reviewer.id,p_decision_id:decisionId,p_outcome:'approve',p_reason:'SYNTHETIC separate current review'});expect(reviewed.error).toBeNull();expect(reviewed.data.status).toBe('approved')
 io.client=submitter.client;await expect(purgeBlobRetention({companyId:otherCompany,decisionId})).rejects.toBeTruthy()
 const parameters={p_company_id:f.companyId,p_actor_user_id:submitter.id,p_decision_id:decisionId},pending=await submitter.client.rpc('ediel_begin_blob_purge_v1',parameters);expect(pending.error).toBeNull();expect(pending.data.status).toBe('storage_purge_pending')
 expect((await supabaseService.rpc('ediel_require_source_bytes_available_v1',{p_company_id:f.companyId,p_source_message_id:f.originalZ03.id})).error).not.toBeNull()
 expect((await bucket.download(target.path)).error).toBeNull() // tombstone precedes physical action
 sql(`INSERT INTO public.user_permission_overrides(user_id,company_id,permission_key,effect,is_active) VALUES(${literal(reviewer.id)},${literal(f.companyId)},'ediel.retention.review','deny',true)`)
 const denied=await submitter.client.storage.from('ediel-files').remove([target.path]);expect(denied.error).not.toBeNull();expect((await bucket.download(target.path)).error).toBeNull()
 expect((await submitter.client.rpc('ediel_finish_blob_storage_purge_v1',parameters)).error).not.toBeNull()
 sql(`DELETE FROM public.user_permission_overrides WHERE user_id=${literal(reviewer.id)} AND company_id=${literal(f.companyId)} AND permission_key='ediel.retention.review'`)
 const removed=await purgeBlobRetention({companyId:f.companyId,decisionId});expect(removed).toMatchObject({status:'purged',targetId:target.id,sourceHash:target.sha,byteLength:target.length,replay:false});expect(await purgeBlobRetention({companyId:f.companyId,decisionId})).toMatchObject({status:'purged',replay:true})
 const after=await bucket.download(target.path);expect(after.data).toBeNull();expect(String(after.error?.statusCode)).toBe('404')
 expect((await bucket.upload(target.path,originalBytes,{contentType:'message/rfc822'})).error).not.toBeNull()
 expect(sql(`SELECT jsonb_build_object('hash',source_hash,'original',(SELECT raw_payload IS NOT NULL FROM public.ediel_messages WHERE id=${literal(f.originalZ03.id)}),'receipt',(SELECT count(*) FROM gridex_ediel_transport.attempts WHERE company_id=${literal(f.companyId)} AND message_id=${literal(f.originalZ03.id)} AND classification='accepted'),'events',(SELECT count(*) FROM gridex_ediel_retention.blob_events WHERE target_id=${literal(target.id)}),'audit',(SELECT count(*) FROM public.audit_logs WHERE entity_id=${literal(target.id)} AND action='ediel.retention.mime_bytes_removed')) FROM gridex_ediel_retention.blob_tombstones WHERE target_id=${literal(target.id)}`)).toEqual({hash:target.sha,original:true,receipt:1,events:2,audit:1})
},60000)
/** A real canonical/full Z04 owner qualifies before erasure. Its exact native
 * assessment arguments are read unchanged; caller JSON does not create them.
 * Legal policy/issuer is synthetic mechanism evidence, not actual authority. */
it('native received-original erasure retains supply continuity and stops the exact v3 and mixed consumers from minting further facts',async()=>{
 for(const[k,v]of Object.entries({EDIEL_SHARED_MAILBOX_ADDRESS:'synthetic@example.invalid',EDIEL_APP_DKIM_ENABLED:'false',EMAIL_PROVIDER:'resend',EDIEL_SMTP_FROM:'synthetic@example.invalid',EDIEL_SMTP_USER:'synthetic@example.invalid',EDIEL_SMTP_PASS:'synthetic-only',EDIEL_EMAIL_PROVIDER:'strato'}))vi.stubEnv(k,v)
 const f=await createRequestedChangeSupplyFixture(email=>io.smtp.mockResolvedValue({accepted:[email],rejected:[],messageId:randomUUID(),response:'250 synthetic accepted'})),submitter=await user(f.companyId,['communication.write','ediel.retention.submit','ediel.retention.purge','ediel.retention.original_bytes']),reviewer=await user(f.companyId,['ediel.retention.review','ediel.retention.original_bytes'])
 const canonical=sql<{hash:string;facts:string;ignored:string|null;object:string}>(`SELECT jsonb_build_object('hash',a.source_payload_hash,'facts',a.facts_text,'ignored',i.fields_text,'object',o.facts_text) FROM gridex_received_sources.validation_assessments a JOIN gridex_received_sources.prodat_object_validation_facets o ON o.assessment_id=a.id LEFT JOIN gridex_received_sources.prodat_ignored_field_facets i ON i.canonical_assessment_id=a.id WHERE a.source_message_id=${literal(f.source)} AND NOT EXISTS(SELECT FROM gridex_received_sources.validation_assessments child WHERE child.previous_assessment_id=a.id)`)
 expect(canonical.object).toBeTruthy()
 const argumentsV3={p_company_id:f.companyId,p_environment:'test',p_source_message_id:f.source,p_source_payload_hash:canonical.hash,p_facts_text:canonical.facts,p_ignored_fields_text:canonical.ignored,p_object_facts_text:canonical.object},beforeCapture=await supabaseService.rpc('gridex_record_prodat_source_validation_v3',argumentsV3);expect(beforeCapture.error).toBeNull();expect(beforeCapture.data.version).toBe(3)
 const document=Buffer.from('SYNTHETIC exact received-original class deadline'),legal=Buffer.from('SYNTHETIC source-retention competence only'),key=Buffer.from('SYNTHETIC ONLY original HMAC key 01234567890123456789'),issuer=randomUUID(),basis=sql<{sourceHash:string;targetHash:string;messageId:string}>(`SELECT gridex_ediel_retention.blob_basis_v1(${literal(f.companyId)},'received_ediel_message_content',${literal(f.source)})`)
 sql(`INSERT INTO gridex_ediel_retention.issuers(id,company_id,legal_reference,legal_evidence,legal_hash,signing_key,valid_from,valid_to) VALUES(${literal(issuer)},${literal(f.companyId)},'SYNTHETIC ORIGINAL COMPETENCE ONLY',decode('${legal.toString('hex')}','hex'),${literal(hash(legal))},decode('${key.toString('hex')}','hex'),'2020-01-01','2099-01-01')`)
 const payload=Buffer.from(JSON.stringify({format:'ediel_blob_retention_policy_v1',retentionClass:'received_ediel_message_content',companyId:f.companyId,targetId:f.source,messageId:basis.messageId,sourceHash:basis.sourceHash,targetHash:basis.targetHash,documentHash:hash(document),issuerLegalReference:'SYNTHETIC ORIGINAL COMPETENCE ONLY',legalBasisReference:'SYNTHETIC separate original content policy',issuedAt:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),retainUntil:new Date(Date.now()-1000).toISOString()})),receipt={issuerId:issuer,payloadBase64:payload.toString('base64'),signatureHex:createHmac('sha256',key).update(payload).digest('hex')}
 const decision=await submitter.client.rpc('ediel_submit_blob_retention_v1',{p_company_id:f.companyId,p_actor_user_id:submitter.id,p_retention_class:'received_ediel_message_content',p_target_id:f.source,p_document_base64:document.toString('base64'),p_issuer_receipt:receipt});expect(decision.error).toBeNull();expect(decision.data.issuerQualified).toBe(true)
 const review=await reviewer.client.rpc('ediel_review_blob_retention_v1',{p_company_id:f.companyId,p_actor_user_id:reviewer.id,p_decision_id:decision.data.decisionId,p_outcome:'approve',p_reason:'SYNTHETIC separate original review'});expect(review.error).toBeNull();expect(review.data.status).toBe('approved')
 io.client=submitter.client;expect(await purgeBlobRetention({companyId:f.companyId,decisionId:decision.data.decisionId})).toMatchObject({status:'purged',targetId:f.source,sourceHash:canonical.hash,replay:false})
 expect(sql(`SELECT jsonb_build_object('raw',raw_payload,'hash',payload_hash,'bytes',retention_byte_length,'purged',retention_purged_at IS NOT NULL) FROM gridex_received_sources.sources WHERE source_message_id=${literal(f.source)}`)).toMatchObject({raw:null,hash:canonical.hash,purged:true})
 expect(sql(`SELECT jsonb_build_object('raw',raw_payload,'parsed',parsed_payload,'validation',validation_report,'metadata',metadata) FROM public.ediel_messages WHERE id=${literal(f.source)}`)).toEqual({raw:null,parsed:{},validation:{},metadata:{}})
 const counts=()=>sql(`SELECT jsonb_build_object('canonical',(SELECT count(*) FROM gridex_received_sources.validation_assessments WHERE source_message_id=${literal(f.source)}),'full',(SELECT count(*) FROM gridex_received_sources.prodat_object_validation_facets WHERE source_message_id=${literal(f.source)}),'mixed',(SELECT count(*) FROM gridex_received_sources.prodat_mixed_object_receipts WHERE source_message_id=${literal(f.source)}),'outbox',(SELECT count(*) FROM gridex_received_sources.prodat_mixed_reply_outbox WHERE source_message_id=${literal(f.source)}),'supply',(SELECT count(*) FROM public.customer_supply_periods WHERE id=${literal(f.period)}),'transition',(SELECT count(*) FROM gridex_received_sources.supply_source_transitions WHERE source_message_id=${literal(f.source)}),'ack',(SELECT count(*) FROM public.ediel_messages WHERE related_message_id=${literal(f.source)}),'audit',(SELECT count(*) FROM public.audit_logs WHERE company_id=${literal(f.companyId)}))`),frozen=counts()
 expect((await supabaseService.rpc('gridex_record_prodat_source_validation_v3',argumentsV3)).error).not.toBeNull()
 const reply=await supabaseService.rpc('ediel_read_prodat_mixed_reply_v1',{p_company_id:f.companyId,p_source_message_id:f.source,p_actor_user_id:f.actorUserId});expect(reply.error).not.toBeNull();expect(reply.data).toBeNull();expect(counts()).toEqual(frozen)
},60000)
