import {beforeEach,describe,expect,it} from 'vitest'
import {spawn} from 'node:child_process'
import {randomUUID} from 'node:crypto'
import {readFileSync,writeFileSync} from 'node:fs'
import {supabaseService} from '@/lib/supabase/service'
import {sendEdielMessageViaSmtp} from '@/lib/ediel/transport'
import {reportFreshEdielBusinessIncident,readFreshEdielBusinessIncident,readFreshEdielBusinessIncidentAccess} from '@/lib/ediel/incidents/freshBusinessIncident'
import {seedNativeEscoFixture,qualifyNativeEscoFixture,resetNativeEscoFixture,nativeEscoSql as sql,nativeEscoLiteral as lit,nativeEscoExternal as external,NATIVE_ESCO_DB as DB} from './fixtures/ediel-service-evidence-native'
const verifyAfterBrowser=process.env.GRIDEX_EDIEL_INCIDENT_VERIFY_AFTER_BROWSER==='1'
describe.skipIf(verifyAfterBrowser)('genuine incident producer and browser fixture',()=>{
beforeEach(resetNativeEscoFixture)
async function original(){const f=await seedNativeEscoFixture();await qualifyNativeEscoFixture(f);const positive=await f.utilts('accepted','NATIVE-LATE-ISSUE');await positive.persist();const ack=await positive.ack();await positive.finalize(ack);return {f,positive,ack,command:{commandId:randomUUID(),sourceMessageId:positive.source.id,ackMessageId:ack.id,scopeReference:'NATIVE-LATE-ISSUE',finding:{code:'late_internal_business_error' as const,summary:'Synthetic new operator business check; this report is not a new protocol rejection.'}}}}
const counts=(c:string)=>sql<Record<string,number>>(`SELECT jsonb_build_object('incidents',(SELECT count(*) FROM gridex_ediel_business_incidents.incidents WHERE company_id=${lit(c)}),'plans',(SELECT count(*) FROM gridex_ediel_business_incidents.plans WHERE company_id=${lit(c)}),'events',(SELECT count(*) FROM gridex_ediel_business_incidents.events WHERE company_id=${lit(c)}))`)
it('fresh reported incident requires actual accepted original ACK and positive own scope; retry attempts no writes or ACK/history/outbox effects',async()=>{
 const {f,positive,ack,command}=await original(),input={companyId:f.ids.company,actorUserId:f.ids.actor,command},initial=f.effects()
 await expect(reportFreshEdielBusinessIncident(input)).rejects.toMatchObject({message:expect.stringContaining('ediel_business_incident_actual_accepted_ack_required')});expect(counts(f.ids.company)).toEqual({incidents:0,plans:0,events:0});expect(f.effects()).toEqual(initial)
 await sendEdielMessageViaSmtp(ack,{actorUserId:f.ids.actor,smtpMimeMode:'nodemailer-attachment'});const stable=f.effects()
 const found=await reportFreshEdielBusinessIncident(input);expect(found).toMatchObject({status:'reported',findingValidated:false,ackHistoryChanged:false,contactStatus:'held',correctionStatus:'held',trafficAuthorized:false});expect(counts(f.ids.company)).toEqual({incidents:1,plans:2,events:1});expect(f.effects()).toEqual(stable)
 const trigger='no_incident_replay_'+f.ids.company.replaceAll('-','')
 sql(`CREATE FUNCTION gridex_ediel_business_incidents.${trigger}() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.company_id=${lit(f.ids.company)}::uuid THEN RAISE EXCEPTION 'attempted_incident_replay_effect';END IF;RETURN NEW;END$$;`)
 for(const table of ['incidents','plans','events'])sql(`CREATE TRIGGER ${trigger} BEFORE INSERT ON gridex_ediel_business_incidents.${table} FOR EACH ROW EXECUTE FUNCTION gridex_ediel_business_incidents.${trigger}()`)
 try{const replays=await Promise.all([reportFreshEdielBusinessIncident(input),reportFreshEdielBusinessIncident(input),readFreshEdielBusinessIncident({...input,incidentId:found.incidentId})]);for(const r of replays)expect(r).toEqual(found);expect(counts(f.ids.company)).toEqual({incidents:1,plans:2,events:1});expect(f.effects()).toEqual(stable)}finally{for(const table of ['incidents','plans','events'])sql(`DROP TRIGGER ${trigger} ON gridex_ediel_business_incidents.${table}`)}
 await expect(reportFreshEdielBusinessIncident({...input,command:{...command,scopeReference:'FOREIGN-IDE'}})).rejects.toMatchObject({message:expect.stringContaining('actual_positive_scope_required')});expect(f.effects()).toEqual(stable)
 expect((await positive.ack()).id).toBe(ack.id);expect(f.effects()).toEqual(stable);expect(external.send).toHaveBeenCalledTimes(2)
})
it('last incident audit failure rolls back incident and both held plans without touching the accepted original',async()=>{
 const {f,ack,command}=await original();await sendEdielMessageViaSmtp(ack,{actorUserId:f.ids.actor,smtpMimeMode:'nodemailer-attachment'});const stable=f.effects(),trigger='fail_incident_'+f.ids.company.replaceAll('-','')
 sql(`CREATE FUNCTION gridex_ediel_business_incidents.${trigger}() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.company_id=${lit(f.ids.company)}::uuid THEN RAISE EXCEPTION 'native_last_incident_audit_failure';END IF;RETURN NEW;END$$;CREATE TRIGGER ${trigger} BEFORE INSERT ON gridex_ediel_business_incidents.events FOR EACH ROW EXECUTE FUNCTION gridex_ediel_business_incidents.${trigger}()`)
 try{await expect(reportFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:f.ids.actor,command})).rejects.toMatchObject({message:expect.stringContaining('native_last_incident_audit_failure')});expect(counts(f.ids.company)).toEqual({incidents:0,plans:0,events:0});expect(f.effects()).toEqual(stable)}finally{sql(`DROP TRIGGER ${trigger} ON gridex_ediel_business_incidents.events`)}
})
it.each(['company','global'] as const)('real pending %s DENY serializes before fresh incident qualification and yields zero effects',async scope=>{
 const {f,ack,command}=await original();await sendEdielMessageViaSmtp(ack,{actorUserId:f.ids.actor,smtpMimeMode:'nodemailer-attachment'});const stable=f.effects()
 const blocker=spawn('psql',[DB,'-XAtq','-v','ON_ERROR_STOP=1'],{stdio:['pipe','pipe','pipe']})
 const ready=new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('native_incident_deny_timeout')),10000);blocker.stdout.on('data',chunk=>{if(String(chunk).includes('incident-deny-locked')){clearTimeout(timeout);resolve()}});blocker.on('error',reject)})
 blocker.stdin.write(`BEGIN;LOCK TABLE public.user_permission_overrides IN SHARE ROW EXCLUSIVE MODE;INSERT INTO public.user_permission_overrides(user_id,company_id,permission_key,effect,is_active,valid_from,valid_to) VALUES(${lit(f.ids.actor)},${scope==='company'?lit(f.ids.company):'NULL'},'communication.write','deny',true,now()-interval '1 minute',NULL);SELECT 'incident-deny-locked';\n`)
 await ready;const pending=reportFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:f.ids.actor,command}).then(value=>({value,error:null}),error=>({value:null,error}))
 try{let observed=false;for(let n=0;n<100;n++){observed=sql<boolean>(`SELECT to_jsonb(EXISTS(SELECT FROM pg_stat_activity a JOIN pg_locks l ON l.pid=a.pid WHERE a.wait_event_type='Lock' AND a.query LIKE '%ediel_report_fresh_business_incident_v1%' AND l.relation='public.user_permission_overrides'::regclass AND l.mode='ShareLock' AND NOT l.granted AND a.pid<>pg_backend_pid()))`);if(observed)break;await new Promise(resolve=>setTimeout(resolve,25))}expect(observed,'actual HTTP incident creation awaits current DENY fence before source').toBe(true)}finally{blocker.stdin.end('COMMIT;\n')}
 const result=await pending;expect(result.value).toBeNull();expect(result.error).toMatchObject({message:expect.stringContaining('ediel_business_incident_actor_forbidden')});expect(counts(f.ids.company)).toEqual({incidents:0,plans:0,events:0});expect(f.effects()).toEqual(stable);expect(external.send).toHaveBeenCalledTimes(2)
})

async function incidentOperator(company:string,keys:string[]){
 const email=`incident-${randomUUID()}@example.invalid`,password=process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD??'Disposable-Incident-Only-2026!'
 const result=await supabaseService.auth.admin.createUser({email,password,email_confirm:true});expect(result.error).toBeNull();const id=result.data.user!.id
 sql(`INSERT INTO public.user_profiles(id,email,full_name,user_status) VALUES(${lit(id)},${lit(email)},'Disposable incident operator','active') ON CONFLICT(id) DO UPDATE SET user_status='active';INSERT INTO public.company_memberships(company_id,user_id,membership_role,status,accepted_at,role,is_active,joined_at,role_key) VALUES(${lit(company)},${lit(id)},'member','active',now(),'member',true,now(),'member');INSERT INTO public.user_permissions(user_id,company_id,permission_id,permission_key) SELECT ${lit(id)},${lit(company)},id,key FROM public.permissions WHERE key=ANY(ARRAY[${keys.map(lit).join(',')}]);`)
 return {id,email}
}
it('actual own-company read-only incident inspection requalifies current originals without send authority and never changes any row',async()=>{
 const {f,ack,command}=await original();await sendEdielMessageViaSmtp(ack,{actorUserId:f.ids.actor,smtpMimeMode:'nodemailer-attachment'})
 const writer=await incidentOperator(f.ids.company,['communication.read','communication.write','communication.send']),reader=await incidentOperator(f.ids.company,['communication.read']),foreign=await seedNativeEscoFixture(),outsider=await incidentOperator(foreign.ids.company,['communication.read','communication.write','communication.send'])
 const found=await reportFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:writer.id,command}),stable=f.effects(),stableCount=counts(f.ids.company)
 expect(await readFreshEdielBusinessIncidentAccess({companyId:f.ids.company,actorUserId:reader.id})).toEqual({companyId:f.ids.company,canRead:true,canReport:false})
 expect(await readFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:reader.id,incidentId:found.incidentId})).toEqual(found)
 await expect(reportFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:reader.id,command:{...command,commandId:randomUUID()}})).rejects.toMatchObject({message:expect.stringContaining('actor_forbidden')})
 await expect(readFreshEdielBusinessIncident({companyId:foreign.ids.company,actorUserId:outsider.id,incidentId:found.incidentId})).rejects.toMatchObject({message:expect.stringContaining('unavailable')})
 await expect(readFreshEdielBusinessIncidentAccess({companyId:f.ids.company,actorUserId:outsider.id})).rejects.toMatchObject({message:expect.stringContaining('reader_forbidden')})
 const deny=randomUUID();sql(`INSERT INTO public.user_permission_overrides(id,user_id,company_id,permission_key,effect,is_active) VALUES(${lit(deny)},${lit(reader.id)},${lit(f.ids.company)},'communication.read','deny',true)`)
 await expect(readFreshEdielBusinessIncident({companyId:f.ids.company,actorUserId:reader.id,incidentId:found.incidentId})).rejects.toMatchObject({message:expect.stringContaining('reader_forbidden')})
 sql(`UPDATE public.user_permission_overrides SET is_active=false WHERE id=${lit(deny)}`);expect(f.effects()).toEqual(stable);expect(counts(f.ids.company)).toEqual(stableCount)
 const path=process.env.GRIDEX_EDIEL_INCIDENT_FIXTURE_PATH
 if(path)writeFileSync(path,JSON.stringify({companyId:f.ids.company,writerId:writer.id,readerId:reader.id,outsiderId:outsider.id,outsiderCompanyId:foreign.ids.company,writerEmail:writer.email,readerEmail:reader.email,outsiderEmail:outsider.email,nativeIncidentId:found.incidentId,baselineEffects:stable,originalHashes:sql(`SELECT jsonb_object_agg(id::text,encode(sha256(convert_to(raw_payload,'UTF8')),'hex')) FROM public.ediel_messages WHERE company_id=${lit(f.ids.company)} AND id IN(${lit(command.sourceMessageId)},${lit(command.ackMessageId)})`),sourceMessageId:command.sourceMessageId,ackMessageId:command.ackMessageId,scopeReference:command.scopeReference,nativeFinding:command.finding.summary}),{mode:0o600})
})

})
it.runIf(verifyAfterBrowser)('post-browser genuine native receipt retains exactly two incidents, immutable accepted ACK, held plans and zero market/outbox mutations',async()=>{
 const path=process.env.GRIDEX_EDIEL_INCIDENT_FIXTURE_PATH;if(!path)throw Error('native_incident_browser_fixture_required')
 const f=JSON.parse(readFileSync(path,'utf8')) as {companyId:string;writerId:string;readerId:string;outsiderId:string;outsiderCompanyId:string;nativeIncidentId:string;browserIncidentId:string;browserCommandId:string;sourceMessageId:string;ackMessageId:string;scopeReference:string;browserFinding:string;baselineEffects:Record<string,number>;originalHashes:Record<string,string>}
 expect(f.browserIncidentId).toBeTruthy();expect(f.browserCommandId).toBeTruthy();expect(counts(f.companyId)).toEqual({incidents:2,plans:4,events:2})
 const effects=()=>sql<Record<string,number>>(`SELECT jsonb_build_object('messages',(SELECT count(*) FROM public.ediel_messages WHERE company_id=${lit(f.companyId)}),'businessReferences',(SELECT count(*) FROM public.ediel_business_references WHERE company_id=${lit(f.companyId)}),'creationReceipts',(SELECT count(*) FROM gridex_ediel_ack_replay.creation_receipts WHERE company_id=${lit(f.companyId)}),'consumptions',(SELECT count(*) FROM gridex_ediel_outbound_owner.consumptions WHERE company_id=${lit(f.companyId)}),'namespace',(SELECT count(*) FROM gridex_ediel_wire_namespace.coverage WHERE company_id=${lit(f.companyId)}),'outbox',(SELECT count(*) FROM public.ediel_outbox WHERE company_id=${lit(f.companyId)}),'intents',(SELECT count(*) FROM public.ediel_message_intents WHERE company_id=${lit(f.companyId)}),'series',(SELECT count(*) FROM public.meter_reading_series WHERE company_id=${lit(f.companyId)}),'values',(SELECT count(*) FROM public.meter_reading_values WHERE company_id=${lit(f.companyId)}),'contracts',(SELECT count(*) FROM gridex_utilts_binding.contracts WHERE company_id=${lit(f.companyId)}),'bindings',(SELECT count(*) FROM gridex_utilts_binding.receipts WHERE company_id=${lit(f.companyId)}),'reservations',(SELECT count(*) FROM public.ediel_ack_transaction_results WHERE company_id=${lit(f.companyId)}),'acks',(SELECT count(*) FROM public.ediel_messages WHERE company_id=${lit(f.companyId)} AND direction='outbound' AND related_message_id IS NOT NULL),'witnesses',(SELECT count(*) FROM gridex_ediel_outbound_owner.witnesses WHERE company_id=${lit(f.companyId)}),'scopeReceipts',(SELECT count(*) FROM gridex_ediel_ack_replay.positive_service_scope_receipts WHERE company_id=${lit(f.companyId)}),'events',(SELECT count(*) FROM public.ediel_message_events WHERE company_id=${lit(f.companyId)}),'attempts',(SELECT count(*) FROM gridex_ediel_transport.attempts WHERE company_id=${lit(f.companyId)}))`)
 expect(effects()).toEqual(f.baselineEffects);expect(sql(`SELECT jsonb_object_agg(id::text,encode(sha256(convert_to(raw_payload,'UTF8')),'hex')) FROM public.ediel_messages WHERE company_id=${lit(f.companyId)} AND id IN(${lit(f.sourceMessageId)},${lit(f.ackMessageId)})`)).toEqual(f.originalHashes)
 const actual=sql<{held:number;source:string;ack:string}>(`SELECT jsonb_build_object('held',(SELECT count(*) FROM gridex_ediel_business_incidents.plans WHERE company_id=${lit(f.companyId)} AND status='held' AND authority_required='source_supported_independent_review_and_new_operation_required'),'source',(SELECT source_hash FROM gridex_ediel_business_incidents.incidents WHERE id=${lit(f.browserIncidentId)} AND company_id=${lit(f.companyId)}),'ack',(SELECT ack_hash FROM gridex_ediel_business_incidents.incidents WHERE id=${lit(f.browserIncidentId)} AND company_id=${lit(f.companyId)}))`);expect(actual).toEqual({held:4,source:f.originalHashes[f.sourceMessageId],ack:f.originalHashes[f.ackMessageId]})
 const command={commandId:f.browserCommandId,sourceMessageId:f.sourceMessageId,ackMessageId:f.ackMessageId,scopeReference:f.scopeReference,finding:{code:'late_internal_business_error' as const,summary:f.browserFinding}}
 const trigger='post_browser_noeffect_'+f.companyId.replaceAll('-','');sql(`CREATE FUNCTION gridex_ediel_business_incidents.${trigger}() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.company_id=${lit(f.companyId)}::uuid THEN RAISE EXCEPTION 'attempted_postbrowser_incident_effect';END IF;RETURN NEW;END$$`);for(const table of ['incidents','plans','events'])sql(`CREATE TRIGGER ${trigger} BEFORE INSERT ON gridex_ediel_business_incidents.${table} FOR EACH ROW EXECUTE FUNCTION gridex_ediel_business_incidents.${trigger}()`);
 const replay=await reportFreshEdielBusinessIncident({companyId:f.companyId,actorUserId:f.writerId,command});expect(replay.incidentId).toBe(f.browserIncidentId);expect(await readFreshEdielBusinessIncident({companyId:f.companyId,actorUserId:f.readerId,incidentId:f.browserIncidentId})).toEqual(replay)
 await expect(readFreshEdielBusinessIncident({companyId:f.outsiderCompanyId,actorUserId:f.outsiderId,incidentId:f.browserIncidentId})).rejects.toMatchObject({message:expect.stringContaining('unavailable')});expect(counts(f.outsiderCompanyId)).toEqual({incidents:0,plans:0,events:0});expect(effects()).toEqual(f.baselineEffects)
 const role=sql<string>(`SELECT to_jsonb(actor_id) FROM public.tenant_actor_roles WHERE company_id=${lit(f.companyId)} AND environment='test' AND role_code='energy_service_company' AND valid_from<=now() AND (valid_to IS NULL OR now()<valid_to)`)
 sql(`UPDATE public.tenant_actor_roles SET valid_to=clock_timestamp() WHERE company_id=${lit(f.companyId)} AND actor_id=${lit(role)} AND role_code='energy_service_company' AND valid_from<=now() AND (valid_to IS NULL OR now()<valid_to)`)
 await expect(readFreshEdielBusinessIncident({companyId:f.companyId,actorUserId:f.readerId,incidentId:f.browserIncidentId})).rejects.toBeDefined();expect(counts(f.companyId)).toEqual({incidents:2,plans:4,events:2});expect(effects()).toEqual(f.baselineEffects);for(const table of ['incidents','plans','events'])sql(`DROP TRIGGER ${trigger} ON gridex_ediel_business_incidents.${table}`)
})
