import {readFileSync} from 'node:fs'
import {expect,it} from 'vitest'
import {createDecisionOriginalNativeFixture,decisionNativeSql as sql,hash,literal,signSyntheticDecisionOriginalPolicy} from './helpers/ediel-decision-original-native-fixture'
import {writeBrowserFixture} from './helpers/browserFixture'

type Fixture={companyId:string;foreignCompanyId:string;sourceMessageId:string;targetId:string;sourceHash:string;sourceDocumentBase64:string;issuerId:string;actorId:string;actorEmail:string;reviewerId:string;reviewerEmail:string;readonlyEmail:string;foreignEmail:string;basis:{retentionClass:string;targetId:string;sourceHash:string;targetMetadataHash:string};documentBase64:string;documentHash:string;issuerReceipt:Record<string,unknown>;revokedDocumentBase64:string;revokedIssuerReceipt:Record<string,unknown>;policyId?:string;revokedPolicyId?:string;subsequentPolicyId?:string}
it('actual local archive owner prepares archived-only decision-original UI data and independently checks byte/tombstone/current authority after browser',async()=>{
 const path=process.env.GRIDEX_DECISION_RETENTION_FIXTURE_PATH,password=process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD
 if(!path||!password||process.env.NEXT_PUBLIC_SUPABASE_URL!=='http://127.0.0.1:54321')throw Error('decision_original_owned_browser_fixture_required')
 if(process.env.GRIDEX_DECISION_RETENTION_VERIFY_AFTER_BROWSER==='1'){
  const f=JSON.parse(readFileSync(path,'utf8')) as Fixture;expect(f.policyId).toBeTruthy();expect(f.revokedPolicyId).toBeTruthy();expect(f.subsequentPolicyId).toBeTruthy()
  expect(sql(`SELECT jsonb_build_object('original',d.document_bytes IS NULL AND d.document_hash=${literal(f.sourceHash)},'originalRevoked',(SELECT count(*) FROM gridex_ediel_retention.blob_revocations WHERE decision_id=d.id),'tombstone',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_tombstones WHERE company_id=d.company_id AND target_id=d.id AND policy_id=${literal(f.policyId!)}),'policyBytes',(SELECT document_bytes IS NULL AND document_hash=${literal(f.documentHash)} FROM gridex_ediel_retention.decision_evidence_policies WHERE id=${literal(f.policyId!)}),'policyRevoked',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_revocations WHERE policy_id=${literal(f.policyId!)}),'declaredRevocation',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_revocations WHERE policy_id=${literal(f.revokedPolicyId!)}),'review',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_reviews WHERE policy_id=${literal(f.policyId!)} AND actor_user_id=${literal(f.reviewerId)} AND outcome='approved'),'sourceRaw',(SELECT raw_payload IS NOT NULL FROM public.ediel_messages WHERE id=${literal(f.sourceMessageId)}),'audit',(SELECT count(*) FROM public.audit_logs WHERE company_id=d.company_id AND action='ediel.retention.decision_original_bytes_removed'),'foreign',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_policies WHERE company_id=${literal(f.foreignCompanyId)})) FROM gridex_ediel_retention.blob_decisions d WHERE id=${literal(f.targetId)}`)).toEqual({original:true,originalRevoked:1,tombstone:1,policyBytes:true,policyRevoked:1,declaredRevocation:1,review:1,sourceRaw:true,audit:2,foreign:0})
  expect(sql(`SELECT gridex_ediel_retention.decision_evidence_receipt_v1(d) FROM gridex_ediel_retention.decision_evidence_policies d WHERE id=${literal(f.policyId!)}`)).toBeNull()
  console.log(JSON.stringify({kind:'decision_original_browser_post',classes:['blob_retention_decision_original_bytes','decision_evidence_policy_original_bytes'],physicalBytesNullVerified:true,retainedHashVerified:true,noMarketSourceAcceptanceClaim:true,actualLegalIssuer:false,allSixNativeAccepted:false}));return
 }
 const f=await createDecisionOriginalNativeFixture(password),document=Buffer.from('SYNTHETIC browser separate decision-original source policy'),revoked=Buffer.from('SYNTHETIC browser withdrawn decision-original policy')
 for(const actor of [f.actor,f.reviewer,f.readonly,f.foreign]){const list=await actor.client.rpc('ediel_current_retention_companies_v1',{});expect(list.error).toBeNull();expect(list.data.map((v:{companyId:string})=>v.companyId)).toEqual([actor===f.foreign?f.foreignCompanyId:f.companyId])}
 writeBrowserFixture(path,{companyId:f.companyId,foreignCompanyId:f.foreignCompanyId,sourceMessageId:f.sourceMessageId,targetId:f.targetId,sourceHash:f.sourceHash,sourceDocumentBase64:f.sourceDocument.toString('base64'),issuerId:f.issuerId,actorId:f.actor.id,actorEmail:f.actor.email,reviewerId:f.reviewer.id,reviewerEmail:f.reviewer.email,readonlyEmail:f.readonly.email,foreignEmail:f.foreign.email,basis:f.basis,documentBase64:document.toString('base64'),documentHash:hash(document),issuerReceipt:signSyntheticDecisionOriginalPolicy(f.companyId,f.issuerId,f.basis,document),revokedDocumentBase64:revoked.toString('base64'),revokedIssuerReceipt:signSyntheticDecisionOriginalPolicy(f.companyId,f.issuerId,f.basis,revoked)} satisfies Fixture,{mode:0o600})
},90000)
