import {expect,it} from 'vitest'
import {randomUUID} from 'node:crypto'
import {createDecisionOriginalNativeFixture,decisionNativeSql as sql,decisionUser,literal} from './helpers/ediel-decision-original-native-fixture'

const classes=['brp_declaration_agreement_original_bytes','brp_declaration_source_original_bytes','certification_workbook_original_bytes','certification_classification_original_bytes','certification_revocation_original_bytes'] as const

it('installed BRP and certification original-copy classes retain native private custody and exact current-source consumers',()=>{
 const result=sql<{classes:string[];keys:string[];privateExecute:number;privateRead:number;helperVolatility:string;brpBytesGate:boolean;certificationBytesGate:boolean}>(`SELECT jsonb_build_object('classes',(SELECT jsonb_agg(retention_class ORDER BY retention_class) FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=ANY(ARRAY[${classes.map(literal).join(',')}])), 'keys',(SELECT jsonb_agg(DISTINCT permission_key) FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=ANY(ARRAY[${classes.map(literal).join(',')}])), 'privateExecute',(SELECT count(*) FROM unnest(ARRAY['anon','authenticated','service_role']) role WHERE has_function_privilege(role,'gridex_ediel_retention.protected_copy_transition_v1(text,jsonb,jsonb)','EXECUTE')), 'privateRead',(SELECT count(*) FROM unnest(ARRAY['anon','authenticated','service_role']) role WHERE has_table_privilege(role,'gridex_ediel_retention.protected_copy_revocations','SELECT') OR has_table_privilege(role,'gridex_ediel_retention.brp_declaration_agreement_originals','SELECT')), 'helperVolatility',(SELECT provolatile FROM pg_proc WHERE oid='gridex_ediel_retention.protected_copy_current_v1(uuid,uuid)'::regprocedure), 'brpBytesGate',(SELECT position('d.agreement_original IS NULL OR d.source_original IS NULL' IN prosrc)>0 AND position('protected_copy_current_v1(c,d.id)' IN prosrc)>0 FROM pg_proc WHERE oid='gridex_brp_sources.require_source_v1(uuid,uuid,uuid,text,text,uuid,uuid,uuid,timestamptz,uuid)'::regprocedure), 'certificationBytesGate',(SELECT position('d.workbook_original IS NULL OR d.classification_original IS NULL' IN prosrc)>0 AND position('protected_copy_current_v1(d.company_id,d.id)' IN prosrc)>0 FROM pg_proc WHERE oid='gridex_customer_life_events.certification_basis_v1(jsonb,text)'::regprocedure))`)
 expect(result).toEqual({classes:[...classes].sort(),keys:['ediel.retention.record_decision_evidence'],privateExecute:0,privateRead:0,helperVolatility:'v',brpBytesGate:true,certificationBytesGate:true})
},30000)

it('actual GoTrue own and foreign reads of absent BRP/certification copies create no declaration, approval, erasure or business effect',async()=>{
 const password=randomUUID()+'Aa1!',f=await createDecisionOriginalNativeFixture(password),own=await decisionUser(f.companyId,['ediel.retention.read','ediel.retention.record_decision_evidence'],password),foreign=await decisionUser(f.foreignCompanyId,['ediel.retention.read','ediel.retention.record_decision_evidence'],password),target=randomUUID()
 const snapshot=()=>sql(`SELECT jsonb_build_object('brpDeclarations',(SELECT count(*) FROM gridex_brp_sources.contract_declarations WHERE company_id=${literal(f.companyId)}), 'certificationClassifications',(SELECT count(*) FROM gridex_customer_life_events.certification_classifications WHERE company_id=${literal(f.companyId)}), 'copyRevocations',(SELECT count(*) FROM gridex_ediel_retention.protected_copy_revocations WHERE company_id=${literal(f.companyId)}), 'tombstones',(SELECT count(*) FROM gridex_ediel_retention.decision_evidence_tombstones WHERE company_id=${literal(f.companyId)}), 'sourceRetained',(SELECT raw_payload IS NOT NULL FROM public.ediel_messages WHERE id=${literal(f.sourceMessageId)}), 'attempts',(SELECT count(*) FROM gridex_ediel_transport.attempts WHERE company_id=${literal(f.companyId)}))`)
 const before=snapshot()
 for(const retentionClass of classes){
  const parameters={p_company_id:f.companyId,p_actor_user_id:own.id,p_retention_class:retentionClass,p_target_id:target,p_include_document:true}
  const missing=await own.client.rpc('ediel_read_retention_decision_original_v1',parameters);expect(missing.data).toBeNull();expect(missing.error?.message).toContain('decision_evidence_original_scope_required')
  const wrong=await foreign.client.rpc('ediel_read_retention_decision_original_v1',{...parameters,p_actor_user_id:foreign.id});expect(wrong.data).toBeNull();expect(wrong.error).not.toBeNull()
 }
 expect(snapshot()).toEqual(before)
 console.log(JSON.stringify({kind:'brp_certification_copy_native',classesExecuted:classes,proof:'installed actual private ACL and current-source gates; actual GoTrue missing/foreign scoped reads without effects',realBrpDeclarationOrWorkbookAuthority:false,positiveFiveClassErasureNativeAccepted:false}))
},90000)
