import {createClient} from '@supabase/supabase-js'
import {createHash,createHmac,randomUUID} from 'node:crypto'
import {expect,it} from 'vitest'
import {supabaseService} from '@/lib/supabase/service'
import {nativeSql as sql,literal} from './helpers/ediel-normal-switch-native-fixture'
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex')
async function user(company:string,permissions:string[]){
 const email=randomUUID()+'@example.invalid',password=randomUUID()+'Aa1!',created=await supabaseService.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull();const id=created.data.user!.id
 sql(`INSERT INTO public.company_memberships(company_id,user_id,membership_role,status,accepted_at,metadata,role,is_active,joined_at,role_key) VALUES(${literal(company)},${literal(id)},'member','active',now(),'{}','member',true,now(),'member');UPDATE public.user_profiles SET user_status='active' WHERE id=${literal(id)};INSERT INTO public.user_permissions(user_id,company_id,permission_id,permission_key) SELECT ${literal(id)},${literal(company)},id,key FROM public.permissions WHERE key=ANY(ARRAY[${permissions.map(literal).join(',')}])`)
 const client=createClient('http://127.0.0.1:54321',process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false}});expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();return{id,client}
}
/** Actual installed schema, JWT/RPC and private legal mechanics. The customer,
 * operative archived status, competence and legal policy are synthetic facts;
 * this does not prove an actual customer closure or lawful retention period. */
it('actual native customer class preserves current-source holds then revokes portal access and pseudonymises only its own fields',async()=>{
 const company=randomUUID(),customer=randomUUID(),otherCompany=randomUUID(),otherCustomer=randomUUID(),portal=randomUUID()
 sql(`INSERT INTO public.companies(id,name,status) VALUES(${literal(company)},'Synthetic retention native','active'),(${literal(otherCompany)},'Synthetic other retention','active');INSERT INTO public.customers(id,company_id,status,first_name,last_name,full_name,email,personal_number,phone) VALUES(${literal(customer)},${literal(company)},'active','SYNTHETIC','PERSON','SYNTHETIC PERSON','synthetic@example.invalid','199001011234','0101234567'),(${literal(otherCustomer)},${literal(otherCompany)},'archived','OTHER','PERSON','OTHER PERSON','other@example.invalid','198001011234','0101111111');INSERT INTO public.customer_portal_accounts(id,company_id,customer_id,status,is_active,email) VALUES(${literal(portal)},${literal(company)},${literal(customer)},'active',true,'synthetic@example.invalid')`)
 const submitter=await user(company,['customers.write','ediel.retention.submit','ediel.retention.purge']),reviewer=await user(company,['ediel.retention.review']),document=Buffer.from('SYNTHETIC native class decision, no actual legal issuer'),issuer=randomUUID(),legal=Buffer.from('SYNTHETIC competence only'),key=Buffer.from('SYNTHETIC ONLY customer HMAC key 01234567890123456789')
 const submit=(doc:Buffer,token:unknown=null)=>submitter.client.rpc('ediel_submit_customer_retention_v1',{p_company_id:company,p_actor_user_id:submitter.id,p_customer_id:customer,p_document_base64:doc.toString('base64'),p_issuer_receipt:token})
 const held=await submit(Buffer.from('SYNTHETIC no issuer'));expect(held.error).toBeNull();expect(held.data.issuerQualified).toBe(false)
 sql(`UPDATE public.customers SET status='archived' WHERE id=${literal(customer)};INSERT INTO gridex_ediel_retention.issuers(id,company_id,legal_reference,legal_evidence,legal_hash,signing_key,valid_from,valid_to) VALUES(${literal(issuer)},${literal(company)},'SYNTHETIC COMPETENCE ONLY',decode('${legal.toString('hex')}','hex'),${literal(hash(legal))},decode('${key.toString('hex')}','hex'),'2020-01-01','2099-01-01')`)
 const sourceHash=sql<string>(`SELECT to_jsonb(encode(sha256(convert_to(gridex_ediel_retention.customer_personal_fields_v1(c)::text,'UTF8')),'hex')) FROM public.customers c WHERE id=${literal(customer)} AND company_id=${literal(company)}`),payload=Buffer.from(JSON.stringify({format:'ediel_customer_retention_policy_v1',retentionClass:'customer_canonical_personal_fields',companyId:company,customerId:customer,sourceHash,documentHash:hash(document),issuerLegalReference:'SYNTHETIC COMPETENCE ONLY',legalBasisReference:'SYNTHETIC class deadline',issuedAt:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString(),retainUntil:new Date(Date.now()-1000).toISOString()})),token={issuerId:issuer,payloadBase64:payload.toString('base64'),signatureHex:createHmac('sha256',key).update(payload).digest('hex')}
 const decision=await submit(document,token);expect(decision.error).toBeNull();expect(decision.data.issuerQualified).toBe(true);const id=decision.data.decisionId
 const reviewed=await reviewer.client.rpc('ediel_review_customer_retention_v1',{p_company_id:company,p_actor_user_id:reviewer.id,p_decision_id:id,p_outcome:'approve',p_reason:'SYNTHETIC separate review'});expect(reviewed.error).toBeNull();expect(reviewed.data.status).toBe('approved')
 const params={p_company_id:company,p_actor_user_id:submitter.id,p_decision_id:id},purge=()=>submitter.client.rpc('ediel_pseudonymise_customer_retention_v1',params)
 sql(`UPDATE public.customers SET email='changed@example.invalid' WHERE id=${literal(customer)}`);expect((await purge()).data).toMatchObject({status:'held',missing:['exact_native_customer_personal_fields_changed']});sql(`UPDATE public.customers SET email='synthetic@example.invalid' WHERE id=${literal(customer)}`)
 expect((await submitter.client.rpc('ediel_pseudonymise_customer_retention_v1',{...params,p_company_id:otherCompany})).error).not.toBeNull()
 const result=await purge();expect(result.error).toBeNull();expect(result.data).toMatchObject({status:'pseudonymised',customerId:customer,sourceHash,replay:false});expect((await purge()).data.replay).toBe(true)
 expect(sql(`SELECT jsonb_build_object('status',status,'name',full_name,'email',email,'identity',personal_number,'anonymised',anonymized_at IS NOT NULL) FROM public.customers WHERE id=${literal(customer)}`)).toEqual({status:'archived',name:'Pseudonymiserad kund',email:null,identity:null,anonymised:true})
 expect(sql(`SELECT to_jsonb(status='revoked' AND NOT is_active) FROM public.customer_portal_accounts WHERE id=${literal(portal)}`)).toBe(true);expect(sql(`SELECT to_jsonb(email) FROM public.customers WHERE id=${literal(otherCustomer)}`)).toBe('other@example.invalid')
 expect(sql(`SELECT to_jsonb(count(*)) FROM public.audit_logs WHERE entity_id=${literal(customer)} AND action='ediel.retention.customer_pseudonymised'`)).toBe(1)
 expect(sql(`SELECT to_jsonb(source_hash) FROM gridex_ediel_retention.customer_tombstones WHERE customer_id=${literal(customer)}`)).toBe(sourceHash)
},30000)
