'use client'
import {useEffect,useState,type FormEvent} from 'react'
import Link from 'next/link'
import type {AiPurposeSourceArtifact} from '@/lib/ediel/production/aiPurposeSource'
const control='mt-1 w-full rounded border border-gray-400 bg-white p-2 text-black disabled:bg-gray-100',button='rounded bg-blue-700 px-4 py-2 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-50'
async function documentBase64(file:File){if(!file.size||file.size>8*1024*1024)throw Error('Välj ett PDF-original på högst 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let value='';for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(value)}
async function body(response:Response){const result=await response.json();if(!response.ok&&result.status!=='held')throw Error(result.error??'Åtgärden kunde inte genomföras.');return result}
function statusText(state:AiPurposeSourceArtifact['status']){return state==='authorized'?'Styrkt ändamålsunderlag':state==='rejected'?'Avslaget':state==='held'?'Behöver kompletteras':'Arkiverat, väntar på granskning'}
function missingText(missing:string[]){if(!missing.length)return '';if(missing.some(m=>/issuer|representation/.test(m)))return 'Ett autentiskt intyg om utfärdarens kompetens och företrädarens aktuella rätt saknas.';if(missing.some(m=>/clause/.test(m)))return 'Den exakta juridiska klausulen i det signerade originalet måste styrkas.';return 'Underlaget saknar aktuell källauktoritet eller behörighet. Kontrollera original, giltighet och separat granskning.'}
export default function AiPurposeWorkspace({environments,initialArtifactId,canArchive,canReview}:{environments:('test'|'production')[];initialArtifactId:string;canArchive:boolean;canReview:boolean}){
 const [artifactId,setArtifactId]=useState(initialArtifactId),[artifact,setArtifact]=useState<AiPurposeSourceArtifact|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[purpose,setPurpose]=useState('ediel_list_export'),[listType,setListType]=useState('AI')
 async function load(id:string){const result=await body(await fetch(`/api/ediel/ai-purpose-sources/${encodeURIComponent(id)}`,{cache:'no-store'}));setArtifact(result);setArtifactId(id)}
 useEffect(()=>{let current=true;if(initialArtifactId)fetch(`/api/ediel/ai-purpose-sources/${encodeURIComponent(initialArtifactId)}`,{cache:'no-store'}).then(body).then(result=>{if(current)setArtifact(result)}).catch(error=>{if(current)setFeedback(error.message)});return()=>{current=false}},[initialArtifactId])
 async function act(work:()=>Promise<void>){setBusy(true);setFeedback('');try{await work()}catch(error){setFeedback(error instanceof Error?error.message:'Åtgärden kunde inte genomföras.')}finally{setBusy(false)}}
 async function archive(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{const file=form.get('source');if(!(file instanceof File))throw Error('Välj PDF-originalet.');const receiptFile=form.get('issuerReceipt');let issuerReceipt:unknown;if(receiptFile instanceof File&&receiptFile.size){if(receiptFile.size>65536)throw Error('Utfärdarintyget är för stort.');issuerReceipt=JSON.parse(await receiptFile.text())}
  const result=await body(await fetch('/api/ediel/ai-purpose-sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({environment:String(form.get('environment')),listType,purpose,gdprBasis:String(form.get('gdprBasis')),retentionDays:Number(form.get('retentionDays')),retentionUntil:String(form.get('retentionUntil')),validFrom:new Date(String(form.get('validFrom'))).toISOString(),validUntil:new Date(String(form.get('validUntil'))).toISOString(),source:{bytesBase64:await documentBase64(file),mimeType:'application/pdf',reference:String(form.get('reference')),version:String(form.get('version'))},...(issuerReceipt?{issuerReceipt}:{})})}));await load(result.artifactId);window.history.replaceState(null,'',`?artifactId=${encodeURIComponent(result.artifactId)}`);setFeedback('Originalet är arkiverat. En separat granskare måste pröva det före behandling.')})}
 async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{if(!artifact)throw Error('Öppna ett underlag först.');const quote=String(form.get('quote')),result=await body(await fetch(`/api/ediel/ai-purpose-sources/${artifact.artifactId}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceHash:artifact.sourceHash,claimsHash:artifact.claimsHash,decision:String(form.get('decision')),reason:String(form.get('reason')),...(quote?{clause:{locator:String(form.get('locator')),quote}}:{})})}));await load(artifact.artifactId);setFeedback(result.status==='authorized'?'Ändamålsunderlaget är styrkt med aktuell källauktoritet.':result.status==='rejected'?'Underlaget har avslagits.':missingText(result.missing??[]))})}
 return <div className="space-y-8" aria-busy={busy}><p role="status" aria-live="polite" className="break-words">{feedback}</p>
 {canArchive&&<section aria-labelledby="archive-title"><h2 id="archive-title" className="text-xl font-semibold">Arkivera juridiskt original</h2><form onSubmit={archive} className="mt-3 space-y-4">
 <label className="block">Miljö<select aria-label="Miljö" name="environment" required className={control}>{environments.map(e=><option key={e} value={e}>{e==='test'?'Test':'Produktion'}</option>)}</select></label>
 <label className="block">Ändamål<select aria-label="Ändamål" name="purpose" value={purpose} onChange={e=>{setPurpose(e.target.value);if(e.target.value==='ediel_list_export')setListType('AI')}} className={control}><option value="ediel_list_export">Generera och överföra egen AI-lista</option><option value="ediel_list_reconciliation">Stämma av mottagen AI/BI-lista</option></select></label>
 <label className="block">Listtyp<select aria-label="Listtyp" name="listType" value={listType} onChange={e=>setListType(e.target.value)} className={control}><option value="AI">AI</option>{purpose==='ediel_list_reconciliation'&&<option value="BI">BI</option>}</select></label>
 <p>BI får endast behandlas för avstämning av mottagen lista.</p>
 <label className="block">Juridisk grund enligt originalet<textarea aria-label="Juridisk grund enligt originalet" name="gdprBasis" required maxLength={2000} className={control}/></label>
 <div className="grid gap-4 sm:grid-cols-2"><label>Giltig från<input aria-label="Giltig från" name="validFrom" type="datetime-local" required className={control}/></label><label>Giltig till<input aria-label="Giltig till" name="validUntil" type="datetime-local" required className={control}/></label><label>Gallringsfrist i dagar<input aria-label="Gallringsfrist i dagar" name="retentionDays" type="number" min="1" max="99999999" required className={control}/></label><label>Sista lagringsdag<input aria-label="Sista lagringsdag" name="retentionUntil" type="date" required className={control}/></label></div>
 <label className="block">PDF-original<input aria-label="PDF-original" name="source" type="file" accept="application/pdf,.pdf" required className={control}/></label><p>Högst 8 MB. Villkoren måste stämma med den autentiskt signerade klausulen.</p>
 <label className="block">Originalets beteckning<input aria-label="Originalets beteckning" name="reference" required maxLength={2000} className={control}/></label><label className="block">Version<input aria-label="Version" name="version" required maxLength={200} className={control}/></label><label className="block">Utfärdarintyg, om tillgängligt<input aria-label="Utfärdarintyg, om tillgängligt" name="issuerReceipt" type="file" accept="application/json,.json" className={control}/></label>
 <button className={button} disabled={busy||!environments.length}>Arkivera ändamålsunderlag</button></form></section>}
 <section aria-labelledby="review-title"><h2 id="review-title" className="text-xl font-semibold">Öppna och granska original</h2><form className="mt-3 flex flex-col gap-3 sm:flex-row" onSubmit={event=>{event.preventDefault();void act(()=>load(artifactId))}}><label className="grow">Underlagsreferens<input aria-label="Underlagsreferens" value={artifactId} onChange={e=>{setArtifactId(e.target.value);setArtifact(null)}} required className={control}/></label><button className={button} disabled={busy}>Öppna underlag</button></form>
 {artifact&&<div className="mt-4 space-y-4"><dl className="grid gap-2 break-words"><dt>Status</dt><dd>{statusText(artifact.status)}</dd><dt>Original</dt><dd>{artifact.sourceReference} · version {artifact.sourceVersion} · {artifact.byteLength} byte</dd><dt>Miljö och ändamål</dt><dd>{artifact.environment==='test'?'Test':'Produktion'} · {artifact.listType} · {artifact.purpose==='ediel_list_export'?'Generera egen lista':'Avstämning av mottagen lista'}</dd><dt>Juridisk grund</dt><dd>{artifact.gdprBasis}</dd><dt>Giltighet</dt><dd>{artifact.validFrom} — {artifact.validUntil}</dd><dt>Gallring</dt><dd>{artifact.retentionDays} dagar; senast {artifact.retentionUntil}</dd><dt>Kontrollsumma för originalet</dt><dd className="break-all font-mono text-sm">{artifact.sourceHash}</dd></dl><p>{missingText(artifact.missing)}</p><a href={`/api/ediel/ai-purpose-sources/${artifact.artifactId}/source`} className="inline-block text-blue-700 underline">Ladda ned juridiskt original</a><p><Link href={`?artifactId=${artifact.artifactId}`} className="text-blue-700 underline">Länk till originalet för annan granskare</Link></p>
 {canReview&&<form onSubmit={review} className="space-y-3"><p>Kontrollera behörig utfärdare, representation, ändamål, juridisk grund och gallringsvillkor mot originalet. Uppladdaren får inte godkänna sitt eget underlag.</p><label className="block">Beslut<select aria-label="Beslut" name="decision" className={control}><option value="hold">Begär komplettering</option><option value="approve">Godkänn styrkt underlag</option><option value="reject">Avslå</option></select></label><label className="block">Motivering<textarea aria-label="Motivering" name="reason" required maxLength={4000} className={control}/></label><label className="block">Var finns den juridiska klausulen?<input aria-label="Var finns den juridiska klausulen?" name="locator" maxLength={1000} className={control}/></label><label className="block">Ordagrant utdrag om ändamål och gallring<textarea aria-label="Ordagrant utdrag om ändamål och gallring" name="quote" maxLength={10000} className={control}/></label><button className={button} disabled={busy}>Registrera ändamålsgranskning</button></form>}
 {artifact.status==='authorized'&&artifact.listType==='AI'&&artifact.purpose==='ediel_list_export'&&<p><Link href="/admin/ediel/ai-list" className="text-blue-700 underline">Öppna AI-listor</Link>. Underlagets miljö, giltighet och behörighet kontrolleras på nytt före varje behandling.</p>}</div>}
 </section></div>
}
