'use client'
import {useEffect,useState,type FormEvent} from 'react'
import Link from 'next/link'
import type {NetworkRegistrySourceArtifact} from '@/lib/ediel/production/networkRegistrySource'
const control='mt-1 w-full rounded border border-gray-400 bg-white p-2 text-black disabled:bg-gray-100',button='rounded bg-blue-700 px-4 py-2 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-50'
async function documentBase64(file:File){if(!file.size||file.size>8*1024*1024)throw Error('Välj ett PDF-original på högst 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let value='';for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(value)}
async function body(response:Response){const result=await response.json();if(!response.ok&&result.status!=='held')throw Error(result.error??'Åtgärden kunde inte genomföras.');return result}
function statusText(state:NetworkRegistrySourceArtifact['status']){return state==='authorized'?'Styrkt nätregisterunderlag':state==='rejected'?'Avslaget':state==='held'?'Behöver kompletteras':'Arkiverat, väntar på granskning'}
function missingText(missing:string[]){if(!missing.length)return '';if(missing.some(m=>/issuer|representation/.test(m)))return 'Ett autentiskt intyg om utfärdarens kompetens och företrädarens aktuella rätt saknas.';if(missing.some(m=>/clause/.test(m)))return 'Den exakta nätregisterklausulen i det signerade originalet måste styrkas.';return 'Underlaget saknar aktuell källauktoritet eller behörighet. Kontrollera original, giltighet och separat granskning.'}
export default function NetworkRegistryWorkspace({environments,choices,initialArtifactId,canArchive,canReview}:{environments:('test'|'production')[];choices:{id:string;label:string}[];initialArtifactId:string;canArchive:boolean;canReview:boolean}){
 const [artifactId,setArtifactId]=useState(initialArtifactId),[artifact,setArtifact]=useState<NetworkRegistrySourceArtifact|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('')
 async function load(id:string){const result=await body(await fetch(`/api/ediel/network-registry-sources/${encodeURIComponent(id)}`,{cache:'no-store'}));setArtifact(result);setArtifactId(id)}
 useEffect(()=>{let current=true;if(initialArtifactId)fetch(`/api/ediel/network-registry-sources/${encodeURIComponent(initialArtifactId)}`,{cache:'no-store'}).then(body).then(result=>{if(current)setArtifact(result)}).catch(error=>{if(current)setFeedback(error.message)});return()=>{current=false}},[initialArtifactId])
 async function act(work:()=>Promise<void>){setBusy(true);setFeedback('');try{await work()}catch(error){setFeedback(error instanceof Error?error.message:'Åtgärden kunde inte genomföras.')}finally{setBusy(false)}}
 async function archive(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{const file=form.get('source');if(!(file instanceof File))throw Error('Välj PDF-originalet.');const receiptFile=form.get('issuerReceipt');let issuerReceipt:unknown;if(receiptFile instanceof File&&receiptFile.size){if(receiptFile.size>65536)throw Error('Utfärdarintyget är för stort.');issuerReceipt=JSON.parse(await receiptFile.text())}
  const result=await body(await fetch('/api/ediel/network-registry-sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({environment:String(form.get('environment')),networkActorId:String(form.get('networkActorId')),validFrom:new Date(String(form.get('validFrom'))).toISOString(),validUntil:new Date(String(form.get('validUntil'))).toISOString(),source:{bytesBase64:await documentBase64(file),mimeType:'application/pdf',reference:String(form.get('reference')),version:String(form.get('version'))},...(issuerReceipt?{issuerReceipt}:{})})}));await load(result.artifactId);window.history.replaceState(null,'',`?artifactId=${encodeURIComponent(result.artifactId)}`);setFeedback('Originalet är arkiverat. En separat granskare måste pröva det före behandling.')})}
 async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{if(!artifact)throw Error('Öppna ett underlag först.');const quote=String(form.get('quote')),result=await body(await fetch(`/api/ediel/network-registry-sources/${artifact.artifactId}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceHash:artifact.sourceHash,claimsHash:artifact.claimsHash,decision:String(form.get('decision')),reason:String(form.get('reason')),...(quote?{clause:{locator:String(form.get('locator')),quote}}:{})})}));await load(artifact.artifactId);setFeedback(result.status==='authorized'?'Nätregisterunderlaget är styrkt med aktuell källauktoritet.':result.status==='rejected'?'Underlaget har avslagits.':missingText(result.missing??[]))})}
 return <div className="space-y-8" aria-busy={busy}><p role="status" aria-live="polite" className="break-words">{feedback}</p>
 {canArchive&&<section aria-labelledby="archive-title"><h2 id="archive-title" className="text-xl font-semibold">Arkivera nätregisteroriginal</h2><form onSubmit={archive} className="mt-3 space-y-4">
 <label className="block">Miljö<select aria-label="Miljö" name="environment" required className={control}>{environments.map(e=><option key={e} value={e}>{e==='test'?'Test':'Produktion'}</option>)}</select></label>
 <label className="block">Nätföretag<select aria-label="Nätföretag" name="networkActorId" required className={control}>{choices.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>
 <div className="grid gap-4 sm:grid-cols-2"><label>Registerversion giltig från<input name="validFrom" type="datetime-local" required className={control}/></label><label>Registerversion giltig till<input name="validUntil" type="datetime-local" required className={control}/></label></div>
 <label className="block">PDF-original<input aria-label="PDF-original" name="source" type="file" accept="application/pdf,.pdf" required className={control}/></label><p>Högst 8 MB. Villkoren måste stämma med den autentiskt signerade registerklausulen.</p>
 <label className="block">Originalets beteckning<input aria-label="Originalets beteckning" name="reference" required maxLength={2000} className={control}/></label><label className="block">Version<input aria-label="Version" name="version" required maxLength={200} className={control}/></label><label className="block">Utfärdarintyg, om tillgängligt<input aria-label="Utfärdarintyg, om tillgängligt" name="issuerReceipt" type="file" accept="application/json,.json" className={control}/></label>
 <button className={button} disabled={busy||!environments.length||!choices.length}>Arkivera nätregisterunderlag</button></form></section>}
 <section aria-labelledby="review-title"><h2 id="review-title" className="text-xl font-semibold">Öppna och granska original</h2><form className="mt-3 flex flex-col gap-3 sm:flex-row" onSubmit={event=>{event.preventDefault();void act(()=>load(artifactId))}}><label className="grow">Underlagsreferens<input aria-label="Underlagsreferens" value={artifactId} onChange={e=>{setArtifactId(e.target.value);setArtifact(null)}} required className={control}/></label><button className={button} disabled={busy}>Öppna underlag</button></form>
 {artifact&&<div className="mt-4 space-y-4"><dl className="grid gap-2 break-words"><dt>Status</dt><dd>{statusText(artifact.status)}</dd><dt>Original</dt><dd>{artifact.sourceReference} · version {artifact.sourceVersion} · {artifact.byteLength} byte</dd><dt>Miljö och nätföretag</dt><dd>{artifact.environment==='test'?'Test':'Produktion'} · {artifact.networkName} · {artifact.networkEdielId}</dd><dt>Giltighet</dt><dd>{artifact.validFrom} — {artifact.validUntil}</dd><dt>Kontrollsumma för originalet</dt><dd className="break-all font-mono text-sm">{artifact.sourceHash}</dd></dl><p>{missingText(artifact.missing)}</p><a href={`/api/ediel/network-registry-sources/${artifact.artifactId}/source`} className="inline-block text-blue-700 underline">Ladda ned nätregisteroriginal</a><p><Link href={`?artifactId=${artifact.artifactId}`} className="text-blue-700 underline">Länk till originalet för annan granskare</Link></p>
 {canReview&&<form onSubmit={review} className="space-y-3"><p>Kontrollera behörig utfärdare, representation, nätföretagets identitet och registerversion mot originalet. Uppladdaren får inte godkänna sitt eget underlag.</p><label className="block">Beslut<select aria-label="Beslut" name="decision" className={control}><option value="hold">Begär komplettering</option><option value="approve">Godkänn styrkt underlag</option><option value="reject">Avslå</option></select></label><label className="block">Motivering<textarea aria-label="Motivering" name="reason" required maxLength={4000} className={control}/></label><label className="block">Var finns nätregisterklausulen?<input aria-label="Var finns nätregisterklausulen?" name="locator" maxLength={1000} className={control}/></label><label className="block">Ordagrant utdrag om nätföretag och registerversion<textarea aria-label="Ordagrant utdrag om nätföretag och registerversion" name="quote" maxLength={10000} className={control}/></label><button className={button} disabled={busy}>Registrera nätregistergranskning</button></form>}
 {canReview&&artifact.status==='authorized'&&<form className="space-y-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(async()=>{await body(await fetch(`/api/ediel/network-registry-sources/${artifact.artifactId}/revoke`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceHash:artifact.sourceHash,claimsHash:artifact.claimsHash,reason:String(form.get('withdrawalReason'))})}));await load(artifact.artifactId);setFeedback('Registerunderlaget är återkallat. Det får inte ge stöd för nya behandlingar.')})}}><label className="block">Motivering till återkallelse<textarea aria-label="Motivering till återkallelse" name="withdrawalReason" required maxLength={4000} className={control}/></label><button className={button} disabled={busy}>Återkalla nätregisterunderlag</button></form>}</div>}
 </section></div>
}
