'use client'
import {useEffect,useState,type FormEvent} from 'react'
import Link from 'next/link'
import type {RequestedChangeArtifact,RequestedChangeSourceSubmission} from '@/lib/ediel/production/requestedChangeIntake'
export type SourceChoice={periodId:string;contractId:string;point:string;label:string;customer:{id:string;qualifier:''|'SE1'|'SE2';name:string;street:string;city:string;postalCode:string;country:string}}
const control='mt-1 w-full rounded border border-gray-400 bg-white p-2 text-black disabled:bg-gray-100'
const button='rounded bg-blue-700 px-4 py-2 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-50'
const maxBytes=8*1024*1024
async function base64(file:File){if(!file.size||file.size>maxBytes)throw Error('Välj ett originalunderlag på högst 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let value='';for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(value)}
async function responseBody(response:Response){const result=await response.json();if(!response.ok&&result.status!=='held')throw Error(result.error??'Åtgärden kunde inte genomföras.');return result}
function missingText(missing:string[]){if(missing.some(m=>/issuer|representation/.test(m)))return 'Ett autentiskt intyg från en behörig utfärdare och aktuell rätt att företräda kunden saknas.';if(missing.some(m=>/signed_contract|metering_clause/.test(m)))return 'Eget signerat originalavtal och en uttrycklig avtalsklausul för mätningen måste styrkas.';if(missing.some(m=>/separate.*review/.test(m)))return 'En annan behörig granskare måste granska originalunderlaget.';if(missing.length)return 'Underlaget saknar aktuell källauktoritet eller behörighet. Kontrollera original, kund, anläggning och granskning.';return ''}
export default function RequestedChangeWorkspace({choices,initialArtifactId,canArchive,canReview,canQueue}:{choices:SourceChoice[];initialArtifactId:string;canArchive:boolean;canReview:boolean;canQueue:boolean}){
 const [artifactId,setArtifactId]=useState(initialArtifactId),[artifact,setArtifact]=useState<RequestedChangeArtifact|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[selected,setSelected]=useState(choices[0]?.periodId??''),[kind,setKind]=useState<RequestedChangeSourceSubmission['kind']>('death')
 const choice=choices.find(c=>c.periodId===selected)
 async function load(id:string){const result=await responseBody(await fetch(`/api/ediel/requested-change-sources/${encodeURIComponent(id)}`,{cache:'no-store'}));setArtifact(result);setArtifactId(id);return result as RequestedChangeArtifact}
 useEffect(()=>{let current=true;if(initialArtifactId)fetch(`/api/ediel/requested-change-sources/${encodeURIComponent(initialArtifactId)}`,{cache:'no-store'}).then(responseBody).then(result=>{if(current)setArtifact(result)}).catch(error=>{if(current)setFeedback(error.message)});return()=>{current=false}},[initialArtifactId])
 async function act(work:()=>Promise<void>){setBusy(true);setFeedback('');try{await work()}catch(error){setFeedback(error instanceof Error?error.message:'Åtgärden kunde inte genomföras.')}finally{setBusy(false)}}
 async function archive(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{
  if(!choice)throw Error('Välj en egen leveransperiod med avtal och anläggning.');const file=form.get('source') as File;if(!(file instanceof File))throw Error('Välj originalunderlaget.');
  const mimeType=file.type||(/\.pdf$/i.test(file.name)?'application/pdf':/\.json$/i.test(file.name)?'application/json':'text/plain');if(!['application/pdf','application/json','text/plain'].includes(mimeType))throw Error('Underlaget måste vara PDF, text eller JSON.');
  const qualifier=String(form.get('customerQualifier')) as ''|'SE1'|'SE2',identity={id:String(form.get('customerId')),qualifier,agency:qualifier?'260' as const:'89' as const}
  const reference=String(form.get('reference')),street=String(form.get('street')),city=String(form.get('city')),postalCode=String(form.get('postalCode')),country=String(form.get('country')).toUpperCase(),name=String(form.get('customerName'))
  const address={lines:[street,'',''] as [string,string,string],city,postalCode,country,representation:{convention:'originalunderlag',reference,mode:1 as const}}
  const invoiceeIdentity={id:String(form.get('invoiceeId')),qualifier:String(form.get('invoiceeQualifier')) as ''|'SE1'|'SE2',agency:form.get('invoiceeQualifier')?'260' as const:'89' as const}
  const invoiceeAddress={...address,lines:[String(form.get('invoiceeStreet')),'',''] as [string,string,string],city:String(form.get('invoiceeCity')),postalCode:String(form.get('invoiceePostalCode')),country:String(form.get('invoiceeCountry')).toUpperCase()}
  const receiptFile=form.get('issuerReceipt') as File;let issuerReceipt:unknown;if(receiptFile instanceof File&&receiptFile.size){if(receiptFile.size>65536)throw Error('Utfärdarintyget är för stort.');issuerReceipt=JSON.parse(await receiptFile.text())}
  const result=await responseBody(await fetch('/api/ediel/requested-change-sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({supplyPeriodId:choice.periodId,contractId:choice.contractId,kind,effectiveAt:new Date(String(form.get('effectiveAt'))).toISOString(),source:{bytesBase64:await base64(file),mimeType,reference,version:String(form.get('version'))},
   customerIdentity:{...identity,name,addressLines:[street],city,postalCode,country},invoiceeProfile:{meteringPointId:choice.point,identityAgency:'9',endUser:{identity,address},invoicee:{identity:invoiceeIdentity,nameLines:[String(form.get('invoiceeName'))],address:invoiceeAddress,availability:'available'},event:{state:'none',reference}},...(issuerReceipt?{issuerReceipt}: {})})}));await load(result.artifactId);window.history.replaceState(null,'',`?artifactId=${encodeURIComponent(result.artifactId)}`);setFeedback('Originalunderlaget är arkiverat. Det är ännu inte godkänt för en ändringsbegäran.');
 })}
 async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{if(!artifact)throw Error('Öppna ett underlag först.');const decision=String(form.get('decision')),clause=String(form.get('quote'));const result=await responseBody(await fetch(`/api/ediel/requested-change-sources/${artifact.artifactId}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceHash:artifact.sourceHash,claimsHash:artifact.claimsHash,decision,reason:String(form.get('reason')),...(clause?{clause:{locator:String(form.get('locator')),quote:clause}}:{})})}));await load(artifact.artifactId);setFeedback(result.status==='authorized'?'Underlaget är godkänt med aktuell källauktoritet.':result.status==='rejected'?'Underlaget har avslagits.':missingText(result.missing??[]))})}
 return <div className="space-y-8" aria-busy={busy}>
  <p role="status" aria-live="polite" className="break-words">{feedback}</p>
  {canArchive&&<section aria-labelledby="archive-title"><h2 id="archive-title" className="text-xl font-semibold">Arkivera originalunderlag</h2><form onSubmit={archive} className="mt-3 space-y-4">
   <label className="block">Kund, anläggning och leveransperiod<select required value={selected} onChange={e=>setSelected(e.target.value)} className={control}><option value="">Välj leveransperiod</option>{choices.map(c=><option key={c.periodId} value={c.periodId}>{c.label}</option>)}</select></label>
   <label className="block">Orsak<select name="kind" value={kind} onChange={e=>setKind(e.target.value as typeof kind)} className={control}><option value="death">Dödsfall</option><option value="quarter_contract">Avtal om kvartsmätning</option><option value="method_contract">Avtal om annan mätmetod</option></select></label>
   <label className="block">Gäller från<input type="datetime-local" name="effectiveAt" required className={control}/></label>
   <label className="block">Originalunderlag<input type="file" name="source" required accept="application/pdf,text/plain,application/json,.pdf,.txt,.json" className={control}/></label><p>Högst 8 MB. För avtal krävs bolagets eget verifierade signerade PDF-original.</p>
   <label className="block">Underlagets beteckning<input name="reference" required maxLength={2000} className={control}/></label><label className="block">Version<input name="version" required maxLength={200} className={control}/></label>
   {kind==='death'&&<label className="block">Intyg från utfärdaren, om tillgängligt<input type="file" name="issuerReceipt" accept="application/json,.json" className={control}/><span>Avsaknad av autentiskt intyg gör att underlaget hålls för komplettering.</span></label>}
   <fieldset key={choice?.periodId} className="grid gap-3 border p-3 sm:grid-cols-2"><legend className="px-1 font-semibold">Kund och fakturamottagare enligt originalunderlaget</legend>
    <label>Kundidentitet<input name="customerId" required defaultValue={choice?.customer.id} maxLength={35} className={control}/></label><label>Typ av kundidentitet<select name="customerQualifier" defaultValue={choice?.customer.qualifier} className={control}><option value="SE1">Personnummer</option><option value="SE2">Organisationsnummer</option><option value="">Avtalad kundidentitet</option></select></label>
    <label>Kundnamn<input name="customerName" required defaultValue={choice?.customer.name} maxLength={35} className={control}/></label><label>Kundens adress<input name="street" required defaultValue={choice?.customer.street} maxLength={35} className={control}/></label><label>Ort<input name="city" required defaultValue={choice?.customer.city} maxLength={35} className={control}/></label><label>Postnummer<input name="postalCode" required defaultValue={choice?.customer.postalCode} maxLength={9} className={control}/></label><label>Landkod<input name="country" required defaultValue={choice?.customer.country??'SE'} maxLength={3} className={control}/></label>
    <label>Fakturamottagarens identitet<input name="invoiceeId" required defaultValue={choice?.customer.id} maxLength={35} className={control}/></label><label>Typ av mottagaridentitet<select name="invoiceeQualifier" defaultValue={choice?.customer.qualifier} className={control}><option value="SE1">Personnummer</option><option value="SE2">Organisationsnummer</option><option value="">Avtalad kundidentitet</option></select></label><label>Mottagarens namn<input name="invoiceeName" required defaultValue={choice?.customer.name} maxLength={35} className={control}/></label><label>Mottagarens adress<input name="invoiceeStreet" required defaultValue={choice?.customer.street} maxLength={35} className={control}/></label><label>Mottagarens ort<input name="invoiceeCity" required defaultValue={choice?.customer.city} maxLength={35} className={control}/></label><label>Mottagarens postnummer<input name="invoiceePostalCode" required defaultValue={choice?.customer.postalCode} maxLength={9} className={control}/></label><label>Mottagarens landkod<input name="invoiceeCountry" required defaultValue={choice?.customer.country??'SE'} maxLength={3} className={control}/></label>
   </fieldset><button className={button} disabled={busy||!choice}>Arkivera underlag</button>
  </form></section>}
  <section aria-labelledby="review-title"><h2 id="review-title" className="text-xl font-semibold">Öppna och granska underlag</h2><form className="mt-3 flex flex-col gap-3 sm:flex-row" onSubmit={event=>{event.preventDefault();void act(()=>load(artifactId).then(()=>undefined))}}><label className="grow">Underlagsreferens<input value={artifactId} onChange={e=>{setArtifactId(e.target.value);setArtifact(null)}} required className={control}/></label><button className={button} disabled={busy}>Öppna underlag</button></form>
   {artifact&&<div className="mt-4 space-y-4"><dl className="grid gap-2 break-words"><dt>Status</dt><dd>{artifact.status==='authorized'?'Godkänt':artifact.status==='rejected'?'Avslaget':artifact.status==='held'?'Behöver kompletteras':'Arkiverat, väntar på granskning'}</dd><dt>Original</dt><dd>{artifact.sourceReference} · version {artifact.sourceVersion} · {artifact.byteLength} byte</dd><dt>Kontrollsumma för originalet</dt><dd className="break-all font-mono text-sm">{artifact.sourceHash}</dd><dt>Kund</dt><dd>{artifact.customerIdentity.name}</dd><dt>Gäller från</dt><dd>{artifact.effectiveAt}</dd></dl><p>{missingText(artifact.missing)}</p>
    <a href={`/api/ediel/requested-change-sources/${artifact.artifactId}/source`} className="inline-block text-blue-700 underline">Ladda ned arkiverat original</a><p><Link href={`?artifactId=${artifact.artifactId}`} className="text-blue-700 underline">Länk till detta underlag för annan granskare</Link></p>
    {canReview&&<form onSubmit={review} className="space-y-3"><p>Kontrollera originalet, kundens identitet och anläggning. Uppladdaren får inte godkänna sitt eget underlag.</p><label className="block">Beslut<select name="decision" className={control}><option value="hold">Begär komplettering</option><option value="approve">Godkänn styrkt underlag</option><option value="reject">Avslå</option></select></label><label className="block">Motivering<textarea name="reason" required maxLength={4000} className={control}/></label>{artifact.kind!=='death'&&<><label className="block">Var finns avtalsklausulen?<input name="locator" maxLength={1000} className={control}/></label><label className="block">Ordagrant utdrag om avtalad mätning<textarea name="quote" maxLength={10000} className={control}/></label></>}<button className={button} disabled={busy}>Registrera granskning</button></form>}
    {canQueue&&artifact.status==='authorized'&&artifact.eventId&&<button className={button} disabled={busy} onClick={()=>void act(async()=>{const result=await responseBody(await fetch('/api/ediel/requested-changes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:artifact.eventId})}));setFeedback(result.status==='held'?missingText(result.missing??[]):result.status==='queued'?'Ändringsbegäran är köad. Den har ännu inte skickats.':'Ändringsbegäran finns redan.');await load(artifact.artifactId)})}>Köa ändringsbegäran</button>}
   </div>}
  </section>
 </div>
}
