-- Requested non-death Z09E has a distinct authenticated outgoing mandate.
-- It cannot promote a received Z06 artifact, bankruptcy or death declaration.
BEGIN;
CREATE SCHEMA gridex_requested_customer_changes;
REVOKE ALL ON SCHEMA gridex_requested_customer_changes FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE gridex_requested_customer_changes.artifacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL CHECK(environment IN('test','production')),agreement_id uuid NOT NULL REFERENCES public.tenant_bilateral_agreements(id),supply_period_id uuid NOT NULL REFERENCES public.customer_supply_periods(id),contract_id uuid NOT NULL REFERENCES public.customer_contracts(id),raw_payload text NOT NULL CHECK(octet_length(raw_payload) BETWEEN 1 AND 1048576),claims jsonb NOT NULL,claims_hash text NOT NULL,source_bytes bytea NOT NULL CHECK(octet_length(source_bytes) BETWEEN 1 AND 8388608),source_hash text NOT NULL CHECK(source_hash=encode(sha256(source_bytes),'hex')),source_reference text NOT NULL,source_version text NOT NULL,issuer_receipt jsonb,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(company_id,environment,source_hash,claims_hash));
CREATE TABLE gridex_requested_customer_changes.reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),artifact_id uuid NOT NULL REFERENCES gridex_requested_customer_changes.artifacts(id),company_id uuid NOT NULL,reviewer_user_id uuid NOT NULL REFERENCES auth.users(id),decision text NOT NULL CHECK(decision IN('approved','held','rejected')),reason text NOT NULL,clause jsonb,missing jsonb NOT NULL DEFAULT '[]',reviewed_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_requested_customer_changes.origins(artifact_id uuid PRIMARY KEY REFERENCES gridex_requested_customer_changes.artifacts(id),review_id uuid NOT NULL UNIQUE REFERENCES gridex_requested_customer_changes.reviews(id),event_id uuid NOT NULL UNIQUE REFERENCES gridex_customer_life_events.events(id),company_id uuid NOT NULL,recorded_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_requested_customer_changes.issuer_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,environment text NOT NULL,counterparty_actor_id uuid NOT NULL,legal_authority_reference text NOT NULL CHECK(length(legal_authority_reference)>0),legal_authority_hash text NOT NULL CHECK(legal_authority_hash~'^[a-f0-9]{64}$'),receipt_signing_key bytea NOT NULL CHECK(octet_length(receipt_signing_key)>=32),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(valid_to>valid_from));
CREATE TABLE gridex_requested_customer_changes.representations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,environment text NOT NULL,issuer_key_id uuid NOT NULL REFERENCES gridex_requested_customer_changes.issuer_keys(id),legal_actor_id uuid NOT NULL,agreement_id uuid NOT NULL REFERENCES public.tenant_bilateral_agreements(id),purpose text NOT NULL CHECK(purpose='prodat_z09e_requested_customer_change'),legal_authority_reference text NOT NULL CHECK(length(legal_authority_reference)>0),legal_authority_hash text NOT NULL CHECK(legal_authority_hash~'^[a-f0-9]{64}$'),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(valid_to>valid_from));
CREATE TABLE gridex_requested_customer_changes.revocations(target_kind text NOT NULL CHECK(target_kind IN('key','representation','artifact')),target_id uuid NOT NULL,source_reference text NOT NULL CHECK(length(source_reference)>0),source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),revoked_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(target_kind,target_id));
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['artifacts','reviews','origins','issuer_keys','representations','revocations'] LOOP
 EXECUTE format('ALTER TABLE gridex_requested_customer_changes.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_requested_customer_changes.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_requested_customer_changes.%I FROM PUBLIC,anon,authenticated,service_role',t);
 EXECUTE format('CREATE TRIGGER immutable_%I BEFORE UPDATE OR DELETE ON gridex_requested_customer_changes.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t,t);EXECUTE format('CREATE TRIGGER no_truncate_%I BEFORE TRUNCATE ON gridex_requested_customer_changes.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t,t);
 END LOOP;END$$;

-- Keep the actual installed current-company actor/permission semantics. The
-- outgoing namespace uses wall clocks after waits; the older shared ports and
-- their OIDs/ACLs remain unchanged. No platform-admin or caller approval port.
DO $actor_ports$DECLARE port text;definition text;BEGIN
 FOREACH port IN ARRAY ARRAY['scoped_permission_v1','actor_v1'] LOOP
  SELECT pg_get_functiondef(p.oid) INTO STRICT definition FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_requested_changes' AND p.proname=port;
  definition:=replace(definition,'gridex_requested_changes.','gridex_requested_customer_changes.');
  definition:=replace(replace(definition,'now()','clock_timestamp()'),'current_date','(clock_timestamp()::date)');
  EXECUTE definition;
 END LOOP;
END$actor_ports$;

CREATE FUNCTION gridex_requested_customer_changes.source_claims_v1(c uuid,env text,agreement uuid,supply_id uuid,contract_id uuid,raw text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE wire jsonb;own jsonb;tokens jsonb;first_lin int;end_lin int;customer_tokens jsonb;sp public.customer_supply_periods%rowtype;cc public.customer_contracts%rowtype;mp public.metering_points%rowtype;ba public.tenant_bilateral_agreements%rowtype;supply jsonb;at_time timestamptz;legal_actor uuid;sender text;scope jsonb;qualified bool;
BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 IF(env IN('test','production')) IS NOT TRUE OR raw IS NULL OR octet_length(raw) NOT BETWEEN 1 AND 1048576 THEN RAISE EXCEPTION 'requested_customer_change_raw_required';END IF;
 wire:=gridex_customer_life_events.wire_v1(raw);tokens:=gridex_received_sources.closure_wire_tokens_v2(raw);
 IF wire IS NULL OR wire->>'code' IS DISTINCT FROM 'Z09' OR jsonb_array_length(wire->'objects')<>1 THEN RAISE EXCEPTION 'requested_customer_change_whole_owned_z09e_required';END IF;own:=wire->'objects'->0;
 IF own->>'reason' IS DISTINCT FROM 'E34' OR own ? 'customerStatus' OR own->>'projectionHeld'='true' THEN RAISE EXCEPTION 'requested_customer_change_non_death_e34_required';END IF;
 at_time:=(own->>'effectiveAt')::timestamptz;
 IF at_time IS NULL OR NOT isfinite(at_time) THEN RAISE EXCEPTION 'requested_customer_change_physical_216_dtm157_required';END IF;
 SELECT min((t->>'index')::int) INTO first_lin FROM jsonb_array_elements(tokens)t WHERE t->>'tag'='LIN';
 SELECT min((t->>'index')::int) INTO end_lin FROM jsonb_array_elements(tokens)t WHERE (t->>'index')::int>first_lin AND t->>'tag' IN('LIN','UNH','UNT','UNZ');
 SELECT jsonb_agg(jsonb_build_object('tag',t->>'tag','elements',t->'elements') ORDER BY (t->>'index')::int) INTO customer_tokens FROM jsonb_array_elements(tokens)t WHERE (t->>'index')::int>first_lin AND (end_lin IS NULL OR(t->>'index')::int<end_lin) AND (t->>'tag'='NAD' AND t#>>'{elements,1,0}' IN('UD','IV') OR t->>'tag'='DTM' AND t#>>'{elements,1,0}'='329');
 IF (SELECT count(*) FROM jsonb_array_elements(customer_tokens)t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD')<>1 OR (SELECT count(*) FROM jsonb_array_elements(customer_tokens)t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV')>1 THEN RAISE EXCEPTION 'requested_customer_change_own_exact_customer_tokens_required';END IF;
 SELECT * INTO sp FROM public.customer_supply_periods WHERE id=supply_id AND company_id=c;
 -- Qualified supply owner locks the immutable source union before own resources.
 supply:=gridex_received_sources.supply_period_source_at_v1(c,sp.id,at_time);qualified:=supply->>'qualified'='true';
 SELECT * INTO cc FROM public.customer_contracts WHERE id=contract_id AND company_id=c FOR SHARE;
 SELECT * INTO mp FROM public.metering_points WHERE id=sp.metering_point_id AND company_id=c FOR SHARE;
 IF sp.id IS NULL OR cc.id IS NULL OR mp.id IS NULL OR cc.customer_id IS DISTINCT FROM sp.customer_id OR cc.metering_point_id IS DISTINCT FROM mp.id OR mp.customer_id IS DISTINCT FROM sp.customer_id OR (cc.status IN('signed','active')) IS NOT TRUE OR cc.signed_at IS NULL OR nullif(cc.signed_version,'') IS NULL OR coalesce(sp.customer_contract_id,sp.contract_id) IS DISTINCT FROM cc.id OR mp.ediel_metering_point_id IS DISTINCT FROM own->>'point' OR mp.grid_owner_ediel_id IS DISTINCT FROM wire->>'legalReceiver' OR mp.grid_area_code IS DISTINCT FROM own->>'gridArea' OR mp.product_direction IS DISTINCT FROM 'consumption' THEN RAISE EXCEPTION 'requested_customer_change_actual_owned_contract_point_required';END IF;
 PERFORM id FROM public.customer_sites WHERE id=coalesce(mp.customer_site_id,mp.site_id) AND company_id=c AND customer_id=sp.customer_id FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'requested_customer_change_owned_site_required';END IF;
 IF qualified AND (supply->>'companyId' IS DISTINCT FROM c::text OR supply->>'customerId' IS DISTINCT FROM sp.customer_id::text OR supply->>'siteId' IS DISTINCT FROM coalesce(mp.customer_site_id,mp.site_id)::text OR supply->>'meteringPointId' IS DISTINCT FROM mp.id::text OR supply->>'dsoEdielId' IS DISTINCT FROM wire->>'legalReceiver' OR NOT EXISTS(SELECT FROM jsonb_array_elements(supply->'sourceObjects')o WHERE o->>'point'=own->>'point' AND o->>'identityAgency'=own->>'identityAgency' AND o->>'gridArea'=own->>'gridArea')) THEN RAISE EXCEPTION 'requested_customer_change_same_owned_supply_required';END IF;
 SELECT * INTO sp FROM public.customer_supply_periods WHERE id=supply_id AND company_id=c FOR SHARE;
 SELECT min(identifier_value),min(actor_id::text)::uuid INTO sender,legal_actor FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=env AND identifier_type='EdielId' AND valid_from<=clock_timestamp() AND(valid_to IS NULL OR valid_to>clock_timestamp());
 IF sender IS DISTINCT FROM wire->>'legalSender' OR (SELECT count(DISTINCT(actor_id,identifier_value)) FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=env AND identifier_type='EdielId' AND valid_from<=clock_timestamp() AND(valid_to IS NULL OR valid_to>clock_timestamp()))<>1 OR qualified AND supply->>'legalActorId' IS DISTINCT FROM legal_actor::text OR NOT EXISTS(SELECT FROM public.tenant_actor_roles WHERE company_id=c AND environment=env AND actor_id=legal_actor AND role_code='electricity_supplier' AND valid_from<=clock_timestamp() AND(valid_to IS NULL OR valid_to>clock_timestamp())) OR NOT EXISTS(SELECT FROM public.tenant_ediel_profiles WHERE company_id=c AND environment=env AND market='electricity' AND is_enabled AND valid_from<=clock_timestamp() AND(valid_to IS NULL OR valid_to>clock_timestamp())) THEN RAISE EXCEPTION 'requested_customer_change_current_own_legal_supplier_required';END IF;
 SELECT * INTO ba FROM public.tenant_bilateral_agreements WHERE id=agreement AND company_id=c AND environment=env FOR SHARE;
 PERFORM id FROM public.platform_actor_identifiers WHERE actor_id=ba.counterparty_actor_id ORDER BY id FOR SHARE;PERFORM id FROM public.platform_actor_roles WHERE actor_id=ba.counterparty_actor_id ORDER BY id FOR SHARE;
 IF ba.id IS NULL OR ba.capability_code IS DISTINCT FROM 'prodat_z09e_requested_customer_change' OR ba.is_enabled IS NOT TRUE OR ba.valid_from IS NULL OR ba.valid_from>clock_timestamp() OR ba.valid_to<=clock_timestamp() OR nullif(ba.source_reference,'') IS NULL OR NOT EXISTS(SELECT FROM public.platform_actor_identifiers WHERE actor_id=ba.counterparty_actor_id AND identifier_type='EdielId' AND identifier_value=wire->>'legalReceiver' AND is_verified AND(valid_from IS NULL OR valid_from<=(clock_timestamp()::date)) AND(valid_to IS NULL OR (clock_timestamp()::date)<=valid_to)) OR NOT EXISTS(SELECT FROM public.platform_actor_roles WHERE actor_id=ba.counterparty_actor_id AND actor_role='grid_owner' AND is_active) THEN RAISE EXCEPTION 'requested_customer_change_exact_current_dso_mandate_required';END IF;
 scope:=jsonb_build_array(jsonb_build_object('periodId',sp.id,'customerId',sp.customer_id,'siteId',coalesce(mp.customer_site_id,mp.site_id),'meteringPointId',mp.id,'pointId',own->>'point','identityAgency',own->>'identityAgency','gridArea',own->>'gridArea','sourceMessageId',supply->>'sourceMessageId','sourcePayloadHash',supply->>'payloadHash','marketStateVersion',supply->>'marketStateVersion','effectiveAt',own->>'effectiveAt','lineItemReference',own->>'li'));
 RETURN jsonb_build_object('purpose','prodat_z09e_requested_customer_change','companyId',c,'environment',env,'agreementId',ba.id,'agreementHash',encode(sha256(convert_to((to_jsonb(ba)-ARRAY['updated_at','created_at'])::text,'UTF8')),'hex'),'agreementReference',ba.source_reference,'agreementTermsHash',encode(sha256(convert_to(ba.terms::text,'UTF8')),'hex'),'counterpartyActorId',ba.counterparty_actor_id,'contractId',cc.id,'contractHash',gridex_received_sources.production_contract_hash_v1(cc),'customerId',sp.customer_id,'supplyPeriodId',sp.id,'supplyQualified',coalesce(qualified,false),'scope',scope,'legalActorId',legal_actor,'legalSender',sender,'legalReceiver',wire->>'legalReceiver','effectiveAt',own->>'effectiveAt','payloadHash',encode(sha256(convert_to(raw,'UTF8')),'hex'),'customerTokens',customer_tokens);
END$$;

CREATE FUNCTION gridex_requested_customer_changes.receipt_current_v1(a gridex_requested_customer_changes.artifacts) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE k gridex_requested_customer_changes.issuer_keys%rowtype;g gridex_requested_customer_changes.representations%rowtype;r jsonb:=a.issuer_receipt;p jsonb;raw bytea;issued timestamptz;expires timestamptz;
BEGIN
 IF a.claims->>'supplyQualified' IS DISTINCT FROM 'true' OR r IS NULL OR jsonb_typeof(r)<>'object' OR coalesce(r->>'signatureHex','')!~'^[a-f0-9]{64}$' OR length(coalesce(r->>'payloadBase64','')) NOT BETWEEN 1 AND 65536 THEN RETURN NULL;END IF;
 SELECT * INTO k FROM gridex_requested_customer_changes.issuer_keys WHERE id=(r->>'keyId')::uuid AND company_id=a.company_id AND environment=a.environment AND counterparty_actor_id=(a.claims->>'counterpartyActorId')::uuid FOR SHARE;
 SELECT * INTO g FROM gridex_requested_customer_changes.representations WHERE id=(r->>'representationId')::uuid AND company_id=a.company_id AND environment=a.environment AND issuer_key_id=k.id AND legal_actor_id=(a.claims->>'legalActorId')::uuid AND agreement_id=a.agreement_id AND purpose='prodat_z09e_requested_customer_change' FOR SHARE;
 IF k.id IS NULL OR g.id IS NULL OR clock_timestamp()<k.valid_from OR clock_timestamp()>=k.valid_to OR clock_timestamp()<g.valid_from OR clock_timestamp()>=g.valid_to OR EXISTS(SELECT FROM gridex_requested_customer_changes.revocations WHERE target_kind='key' AND target_id=k.id OR target_kind='representation' AND target_id=g.id OR target_kind='artifact' AND target_id=a.id) THEN RETURN NULL;END IF;
 raw:=decode(r->>'payloadBase64','base64');IF replace(encode(raw,'base64'),E'\n','') IS DISTINCT FROM r->>'payloadBase64' OR sha256(gridex_requested_changes.receipt_hmac_sha256_v1(raw,k.receipt_signing_key)) IS DISTINCT FROM sha256(decode(r->>'signatureHex','hex')) THEN RETURN NULL;END IF;
 p:=convert_from(raw,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;
 IF issued IS NULL OR expires IS NULL OR NOT isfinite(issued) OR NOT isfinite(expires) OR expires<=issued THEN RETURN NULL;END IF;
 IF p->>'format' IS DISTINCT FROM 'ediel_requested_customer_change_receipt_v1' OR p->>'purpose' IS DISTINCT FROM 'prodat_z09e_requested_customer_change' OR nullif(p->>'receiptId','') IS NULL OR p->'claims' IS DISTINCT FROM a.claims OR p->>'sourceHash' IS DISTINCT FROM a.source_hash OR p->>'sourceReference' IS DISTINCT FROM a.source_reference OR p->>'sourceVersion' IS DISTINCT FROM a.source_version OR jsonb_typeof(p->'authorizedFields') IS DISTINCT FROM 'array' OR (p->'authorizedFields' @> '["227","228","231","232","316"]'::jsonb) IS NOT TRUE OR EXISTS(SELECT FROM jsonb_array_elements_text(p->'authorizedFields')f WHERE f NOT IN('227','228','229','231','232','249','250','251','252','253','316','317','318')) OR EXISTS(SELECT FROM jsonb_array_elements(a.claims->'customerTokens')t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD' AND t#>'{elements,5}' IS NOT NULL AND (p->'authorizedFields' @> '["229"]'::jsonb) IS NOT TRUE) OR EXISTS(SELECT FROM jsonb_array_elements(a.claims->'customerTokens')t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV') AND (p->'authorizedFields' @> '["250","251","252","253","317","318"]'::jsonb) IS NOT TRUE OR EXISTS(SELECT FROM jsonb_array_elements(a.claims->'customerTokens')t WHERE t->>'tag'='DTM') AND (p->'authorizedFields' @> '["249"]'::jsonb) IS NOT TRUE OR NOT isfinite(issued) OR NOT isfinite(expires) OR issued>a.created_at OR issued>clock_timestamp() OR expires<=clock_timestamp() OR issued<greatest(k.valid_from,g.valid_from) OR expires>least(k.valid_to,g.valid_to) THEN RETURN NULL;END IF;
 RETURN p;
EXCEPTION WHEN data_exception THEN RETURN NULL;
END$$;
CREATE FUNCTION gridex_requested_customer_changes.current_v1(artifact uuid,c uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_requested_customer_changes.artifacts%rowtype;o gridex_requested_customer_changes.origins%rowtype;r gridex_requested_customer_changes.reviews%rowtype;receipt jsonb;actual jsonb;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();SELECT * INTO a FROM gridex_requested_customer_changes.artifacts WHERE id=artifact AND company_id=c;
 IF a.id IS NULL THEN RETURN NULL;END IF;
 actual:=gridex_requested_customer_changes.source_claims_v1(c,a.environment,a.agreement_id,a.supply_period_id,a.contract_id,a.raw_payload);
 SELECT * INTO a FROM gridex_requested_customer_changes.artifacts WHERE id=artifact AND company_id=c FOR SHARE;
 SELECT * INTO o FROM gridex_requested_customer_changes.origins WHERE artifact_id=a.id AND company_id=c FOR SHARE;SELECT * INTO r FROM gridex_requested_customer_changes.reviews WHERE id=o.review_id AND artifact_id=a.id AND company_id=c FOR SHARE;
 IF o.artifact_id IS NULL OR r.decision IS DISTINCT FROM 'approved' OR r.reviewer_user_id=a.submitted_by OR gridex_requested_customer_changes.actor_v1(c,r.reviewer_user_id,'review','method_contract') IS NOT TRUE OR actual IS DISTINCT FROM a.claims OR a.claims_hash IS DISTINCT FROM encode(sha256(convert_to(a.claims::text,'UTF8')),'hex') OR a.source_hash IS DISTINCT FROM encode(sha256(a.source_bytes),'hex') OR a.created_at>r.reviewed_at OR r.reviewed_at>o.recorded_at OR o.recorded_at>clock_timestamp() THEN RETURN NULL;END IF;
 receipt:=gridex_requested_customer_changes.receipt_current_v1(a);IF receipt IS NULL OR receipt->'clause' IS DISTINCT FROM r.clause OR position(convert_to(r.clause->>'quote','UTF8') IN a.source_bytes)=0 THEN RETURN NULL;END IF;
 -- All source/issuer/artifact locks are now held. Re-evaluate wall-clock legal
 -- scope and reviewer permissions after any wait before returning authority.
 actual:=gridex_requested_customer_changes.source_claims_v1(c,a.environment,a.agreement_id,a.supply_period_id,a.contract_id,a.raw_payload);
 IF actual IS DISTINCT FROM a.claims OR gridex_requested_customer_changes.actor_v1(c,r.reviewer_user_id,'review','method_contract') IS NOT TRUE THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('status','authorized','artifactId',a.id,'eventId',o.event_id);
EXCEPTION WHEN raise_exception OR data_exception THEN RETURN NULL;END$$;

CREATE FUNCTION public.ediel_archive_requested_customer_change_v1(p_company_id uuid,p_actor_user_id uuid,p_submission jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_requested_customer_changes.artifacts%rowtype;captured_claims jsonb;bytes bytea;hash text;ch text;missing jsonb:='[]';BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'requested_customer_change_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'archive','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_archive_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_submission) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission)k WHERE k NOT IN('environment','agreementId','supplyPeriodId','contractId','rawPayload','source','issuerReceipt')) OR jsonb_typeof(p_submission->'source') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission->'source')k WHERE k NOT IN('bytesBase64','mimeType','reference','version')) OR length(coalesce(p_submission#>>'{source,bytesBase64}','')) NOT BETWEEN 1 AND 11184812 OR p_submission#>>'{source,mimeType}' IS DISTINCT FROM 'application/pdf' OR nullif(p_submission#>>'{source,reference}','') IS NULL OR length(p_submission#>>'{source,reference}')>2000 OR nullif(p_submission#>>'{source,version}','') IS NULL OR length(p_submission#>>'{source,version}')>200 THEN RAISE EXCEPTION 'requested_customer_change_archive_shape_required';END IF;
 bytes:=decode(p_submission#>>'{source,bytesBase64}','base64');IF octet_length(bytes) NOT BETWEEN 1 AND 8388608 OR replace(encode(bytes,'base64'),E'\n','') IS DISTINCT FROM p_submission#>>'{source,bytesBase64}' OR substring(bytes,1,5)<>decode('255044462d','hex') THEN RAISE EXCEPTION 'requested_customer_change_original_pdf_required';END IF;
 captured_claims:=gridex_requested_customer_changes.source_claims_v1(p_company_id,p_submission->>'environment',(p_submission->>'agreementId')::uuid,(p_submission->>'supplyPeriodId')::uuid,(p_submission->>'contractId')::uuid,p_submission->>'rawPayload');hash:=encode(sha256(bytes),'hex');ch:=encode(sha256(convert_to(captured_claims::text,'UTF8')),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended('requested_customer_change_archive:'||p_company_id::text||hash||ch,0));
 SELECT * INTO a FROM gridex_requested_customer_changes.artifacts WHERE company_id=p_company_id AND environment=captured_claims->>'environment' AND source_hash=hash AND claims_hash=ch FOR SHARE;
 IF FOUND THEN IF a.raw_payload IS DISTINCT FROM p_submission->>'rawPayload' OR a.source_reference IS DISTINCT FROM p_submission#>>'{source,reference}' OR a.source_version IS DISTINCT FROM p_submission#>>'{source,version}' OR a.issuer_receipt IS DISTINCT FROM p_submission->'issuerReceipt' THEN RAISE EXCEPTION 'requested_customer_change_original_conflict';END IF;
 ELSE
  IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'archive','method_contract') IS NOT TRUE OR captured_claims IS DISTINCT FROM gridex_requested_customer_changes.source_claims_v1(p_company_id,captured_claims->>'environment',(p_submission->>'agreementId')::uuid,(p_submission->>'supplyPeriodId')::uuid,(p_submission->>'contractId')::uuid,p_submission->>'rawPayload') THEN RAISE EXCEPTION 'requested_customer_change_post_wait_archive_actor_or_source_forbidden' USING ERRCODE='42501';END IF;
  INSERT INTO gridex_requested_customer_changes.artifacts(company_id,environment,agreement_id,supply_period_id,contract_id,raw_payload,claims,claims_hash,source_bytes,source_hash,source_reference,source_version,issuer_receipt,submitted_by)VALUES(p_company_id,captured_claims->>'environment',(p_submission->>'agreementId')::uuid,(p_submission->>'supplyPeriodId')::uuid,(p_submission->>'contractId')::uuid,p_submission->>'rawPayload',captured_claims,ch,bytes,hash,p_submission#>>'{source,reference}',p_submission#>>'{source,version}',p_submission->'issuerReceipt',p_actor_user_id) RETURNING * INTO a;END IF;
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'archive','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_post_wait_archive_actor_forbidden' USING ERRCODE='42501';END IF;
 IF a.claims->>'supplyQualified' IS DISTINCT FROM 'true' THEN missing:='["current_owned_supply_source_required"]';ELSIF gridex_requested_customer_changes.receipt_current_v1(a) IS NULL THEN missing:='["authentic_current_outgoing_customer_mandate"]';END IF;
 RETURN jsonb_build_object('status','archived','artifactId',a.id,'sourceHash',a.source_hash,'claimsHash',a.claims_hash,'missing',missing);END$$;
CREATE FUNCTION public.ediel_read_requested_customer_change_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_include_bytes boolean DEFAULT false)RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_requested_customer_changes.artifacts%rowtype;r gridex_requested_customer_changes.reviews%rowtype;o gridex_requested_customer_changes.origins%rowtype;current_source jsonb;status text;missing jsonb;result jsonb;BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'requested_customer_change_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'read','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_read_actor_forbidden' USING ERRCODE='42501';END IF;
 current_source:=gridex_requested_customer_changes.current_v1(p_artifact_id,p_company_id);
 SELECT * INTO STRICT a FROM gridex_requested_customer_changes.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR SHARE;SELECT * INTO r FROM gridex_requested_customer_changes.reviews WHERE artifact_id=a.id ORDER BY reviewed_at DESC,id DESC LIMIT 1 FOR SHARE;SELECT * INTO o FROM gridex_requested_customer_changes.origins WHERE artifact_id=a.id;
 IF current_source IS NOT NULL THEN status:='authorized';missing:='[]';ELSIF r.decision='rejected' THEN status:='rejected';missing:=r.missing;ELSIF r.id IS NOT NULL THEN status:='held';missing:=CASE WHEN r.decision='approved' THEN '["current_outgoing_customer_mandate_unavailable"]'::jsonb ELSE r.missing END;ELSE status:='archived';missing:='["separate_requested_customer_change_review_required"]';END IF;
 IF o.artifact_id IS NULL AND status='archived' THEN
  IF a.claims->>'supplyQualified' IS DISTINCT FROM 'true' THEN missing:=missing||'["current_owned_supply_source_required"]'::jsonb;
  ELSIF gridex_requested_customer_changes.receipt_current_v1(a) IS NULL THEN missing:=missing||'["authentic_current_outgoing_customer_mandate"]'::jsonb;END IF;
 END IF;
 result:=jsonb_build_object('artifactId',a.id,'agreementId',a.agreement_id,'supplyPeriodId',a.supply_period_id,'contractId',a.contract_id,'eventId',o.event_id,'sourceReference',a.source_reference,'sourceVersion',a.source_version,'sourceHash',a.source_hash,'claimsHash',a.claims_hash,'mimeType','application/pdf','byteLength',octet_length(a.source_bytes),'status',status,'missing',missing);
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'read','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_post_wait_reader_forbidden' USING ERRCODE='42501';END IF;
 IF p_include_bytes THEN result:=result||jsonb_build_object('bytesBase64',replace(encode(a.source_bytes,'base64'),E'\n',''));END IF;RETURN result;END$$;
CREATE FUNCTION public.ediel_review_requested_customer_change_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_review jsonb)RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_requested_customer_changes.artifacts%rowtype;r gridex_requested_customer_changes.reviews%rowtype;o gridex_requested_customer_changes.origins%rowtype;actual jsonb;receipt jsonb;decision text;missing jsonb:='[]';event uuid;fields text[];current_source jsonb;BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'requested_customer_change_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'review','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_review_actor_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO STRICT a FROM gridex_requested_customer_changes.artifacts WHERE id=p_artifact_id AND company_id=p_company_id;
 actual:=gridex_requested_customer_changes.source_claims_v1(a.company_id,a.environment,a.agreement_id,a.supply_period_id,a.contract_id,a.raw_payload);
 SELECT * INTO STRICT a FROM gridex_requested_customer_changes.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR UPDATE;decision:=p_review->>'decision';
 IF jsonb_typeof(p_review) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review)k WHERE k NOT IN('sourceHash','claimsHash','decision','reason','clause')) OR(decision IN('approve','hold','reject')) IS NOT TRUE OR p_review->>'sourceHash' IS DISTINCT FROM a.source_hash OR p_review->>'claimsHash' IS DISTINCT FROM a.claims_hash OR nullif(p_review->>'reason','') IS NULL OR length(p_review->>'reason')>4000 THEN RAISE EXCEPTION 'requested_customer_change_actual_archive_review_required';END IF;
 IF decision='approve' AND a.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'requested_customer_change_separate_reviewer_required';END IF;
 SELECT * INTO o FROM gridex_requested_customer_changes.origins WHERE artifact_id=a.id FOR SHARE;
 IF FOUND THEN IF decision<>'approve' THEN RAISE EXCEPTION 'requested_customer_change_current_origin_requires_revocation';END IF;current_source:=gridex_requested_customer_changes.current_v1(a.id,p_company_id);RETURN coalesce(current_source,jsonb_build_object('status','held','artifactId',a.id,'missing',ARRAY['current_outgoing_customer_mandate_unavailable']));END IF;
 IF decision='hold' THEN missing:='["explicit_requested_customer_change_hold"]';ELSIF decision='reject' THEN missing:='["explicit_requested_customer_change_rejection"]';ELSE
  receipt:=gridex_requested_customer_changes.receipt_current_v1(a);
  IF actual IS DISTINCT FROM a.claims OR a.claims->>'supplyQualified' IS DISTINCT FROM 'true' THEN missing:='["current_owned_supply_source_required"]';ELSIF receipt IS NULL THEN missing:='["authentic_current_outgoing_customer_mandate"]';
  ELSIF jsonb_typeof(p_review->'clause') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review->'clause')k WHERE k NOT IN('locator','quote')) OR nullif(p_review#>>'{clause,locator}','') IS NULL OR length(p_review#>>'{clause,locator}')>1000 OR nullif(p_review#>>'{clause,quote}','') IS NULL OR length(p_review#>>'{clause,quote}')>10000 OR receipt->'clause' IS DISTINCT FROM p_review->'clause' OR position(convert_to(p_review#>>'{clause,quote}','UTF8') IN a.source_bytes)=0 THEN missing:='["actual_original_pdf_verbatim_outgoing_customer_clause"]';END IF;
 END IF;
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'review','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_post_wait_reviewer_forbidden' USING ERRCODE='42501';END IF;
 IF missing='[]'::jsonb AND (gridex_requested_customer_changes.source_claims_v1(a.company_id,a.environment,a.agreement_id,a.supply_period_id,a.contract_id,a.raw_payload) IS DISTINCT FROM a.claims OR gridex_requested_customer_changes.receipt_current_v1(a) IS NULL) THEN missing:='["current_outgoing_customer_mandate_unavailable"]';END IF;
 INSERT INTO gridex_requested_customer_changes.reviews(artifact_id,company_id,reviewer_user_id,decision,reason,clause,missing)VALUES(a.id,p_company_id,p_actor_user_id,CASE WHEN missing='[]'::jsonb THEN 'approved' WHEN decision='reject' THEN 'rejected' ELSE 'held' END,p_review->>'reason',p_review->'clause',missing)RETURNING * INTO r;
 IF missing<>'[]'::jsonb THEN RETURN jsonb_build_object('status',CASE WHEN decision='reject' THEN 'rejected' ELSE 'held' END,'artifactId',a.id,'missing',missing);END IF;
 SELECT array_agg(f ORDER BY f) INTO fields FROM jsonb_array_elements_text(receipt->'authorizedFields')f WHERE f IN('227','228','229','231','232','316');event:=gen_random_uuid();
 INSERT INTO gridex_customer_life_events.events(id,company_id,environment,customer_id,classification,legal_actor_id,legal_sender_id,legal_receiver_id,source_reference,source_version,source_sha256,legal_decision_reference,bilateral_agreement_id,bilateral_capability_code,bilateral_source_reference,bilateral_terms_sha256,approved_raw_payload,approved_payload_hash,approved_scope,allowed_customer_fields,information_known_at,approved_by,approved_at)
 VALUES(event,a.company_id,a.environment,(a.claims->>'customerId')::uuid,'other_masterdata',(a.claims->>'legalActorId')::uuid,a.claims->>'legalSender',a.claims->>'legalReceiver',a.source_reference,a.source_version,a.source_hash,r.id::text,a.agreement_id,'prodat_z09e_requested_customer_change',a.claims->>'agreementReference',a.claims->>'agreementTermsHash',a.raw_payload,a.claims->>'payloadHash',a.claims->'scope',fields,a.created_at,p_actor_user_id,clock_timestamp());
 INSERT INTO gridex_requested_customer_changes.origins(artifact_id,review_id,event_id,company_id)VALUES(a.id,r.id,event,a.company_id);
 RETURN jsonb_build_object('status','authorized','artifactId',a.id,'eventId',event);END$$;
CREATE FUNCTION public.ediel_requested_customer_change_queue_basis_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid)RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE result jsonb;BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'requested_customer_change_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'archive','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_queue_actor_forbidden' USING ERRCODE='42501';END IF;
 result:=gridex_requested_customer_changes.current_v1(p_artifact_id,p_company_id);
 IF gridex_requested_customer_changes.actor_v1(p_company_id,p_actor_user_id,'archive','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_post_wait_queue_actor_forbidden' USING ERRCODE='42501';END IF;
 RETURN coalesce(result,jsonb_build_object('status','held','artifactId',p_artifact_id,'missing',ARRAY['current_outgoing_customer_mandate_unavailable']));END$$;

CREATE FUNCTION gridex_requested_customer_changes.revoke_lock_v1()RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 IF NEW.target_kind='key' THEN PERFORM id FROM gridex_requested_customer_changes.issuer_keys WHERE id=NEW.target_id FOR UPDATE;
 ELSIF NEW.target_kind='representation' THEN PERFORM id FROM gridex_requested_customer_changes.representations WHERE id=NEW.target_id FOR UPDATE;
 ELSE PERFORM id FROM gridex_requested_customer_changes.artifacts WHERE id=NEW.target_id FOR UPDATE;END IF;
 IF NOT FOUND THEN RAISE EXCEPTION 'requested_customer_change_revocation_target_required';END IF;RETURN NEW;END$$;
CREATE TRIGGER requested_customer_change_revoke_lock BEFORE INSERT ON gridex_requested_customer_changes.revocations FOR EACH ROW EXECUTE FUNCTION gridex_requested_customer_changes.revoke_lock_v1();
-- Current source requalification is before any old event lock. Native immutable
-- accepted provider replay in the existing transport journal remains earlier.
DO $observer$DECLARE definition text;before_oid oid;before_acl aclitem[];before_owner oid;before_config text[];before_vol "char";before_security bool;BEGIN
 SELECT oid,proacl,proowner,proconfig,provolatile,prosecdef,pg_get_functiondef(oid)INTO before_oid,before_acl,before_owner,before_config,before_vol,before_security,definition FROM pg_proc WHERE oid='gridex_customer_life_events.source_v1(uuid,uuid,uuid,text)'::regprocedure;
 IF before_oid IS NULL OR position('BEGIN' IN definition)=0 THEN RAISE EXCEPTION 'requested_customer_change_current_source_owner_required';END IF;
 definition:=regexp_replace(definition,'BEGIN',$prefix$BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 IF EXISTS(SELECT FROM gridex_requested_customer_changes.origins WHERE company_id=c AND event_id=event) THEN
  IF gridex_requested_customer_changes.actor_v1(c,actor,CASE WHEN phase='read' THEN 'read' ELSE 'archive' END,'method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'requested_customer_change_current_execution_actor_forbidden' USING ERRCODE='42501';END IF;
  IF gridex_requested_customer_changes.current_v1((SELECT artifact_id FROM gridex_requested_customer_changes.origins WHERE company_id=c AND event_id=event),c) IS NULL THEN RETURN jsonb_build_object('status','held','missing',ARRAY['current_outgoing_customer_mandate_unavailable']);END IF;
 END IF;
$prefix$);EXECUTE definition;
 IF(SELECT oid<>before_oid OR proacl IS DISTINCT FROM before_acl OR proowner<>before_owner OR proconfig IS DISTINCT FROM before_config OR provolatile<>before_vol OR prosecdef<>before_security FROM pg_proc WHERE oid='gridex_customer_life_events.source_v1(uuid,uuid,uuid,text)'::regprocedure)THEN RAISE EXCEPTION 'requested_customer_change_source_owner_identity_changed';END IF;
END$observer$;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA gridex_requested_customer_changes FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.ediel_archive_requested_customer_change_v1(uuid,uuid,jsonb),public.ediel_read_requested_customer_change_v1(uuid,uuid,uuid,boolean),public.ediel_review_requested_customer_change_v1(uuid,uuid,uuid,jsonb),public.ediel_requested_customer_change_queue_basis_v1(uuid,uuid,uuid)FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_archive_requested_customer_change_v1(uuid,uuid,jsonb),public.ediel_read_requested_customer_change_v1(uuid,uuid,uuid,boolean),public.ediel_review_requested_customer_change_v1(uuid,uuid,uuid,jsonb),public.ediel_requested_customer_change_queue_basis_v1(uuid,uuid,uuid)TO service_role;
COMMIT;
