-- Composed-history bridge. 20261001004331 (merged later, earlier timestamp)
-- renamed the plans row alias plan->planned in the final period projection and
-- transition insert of apply_supply_before_legal_context_v1. 20261001043234
-- derives other_supply_scope_effect_v1 from that body with exact needles of the
-- earlier alias and failed on authentic clean replay. Applied bytes stay
-- untouched: this maps only those two statements to the form 043234 consumes;
-- 20261001043235 restores the exact 004331 statements in the original function.
BEGIN;
DO $bridge$DECLARE f record;body text;BEGIN
 SELECT p.oid,to_jsonb(p)-'prosrc' metadata,p.prosrc,pg_get_functiondef(p.oid) definition INTO STRICT f FROM pg_proc p WHERE oid='gridex_received_sources.apply_supply_before_legal_context_v1(uuid,uuid,uuid)'::regprocedure;
 IF (length(f.prosrc)-length(replace(f.prosrc,$t$ SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.id),'[]'::jsonb) INTO after_states FROM public.customer_supply_periods p WHERE p.company_id=m.company_id AND p.id IN (SELECT (planned->>'periodId')::uuid FROM jsonb_array_elements(plans) planned);$t$,'')))/length($t$ SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.id),'[]'::jsonb) INTO after_states FROM public.customer_supply_periods p WHERE p.company_id=m.company_id AND p.id IN (SELECT (planned->>'periodId')::uuid FROM jsonb_array_elements(plans) planned);$t$)<>1 OR (length(f.prosrc)-length(replace(f.prosrc,$t$ INSERT INTO gridex_received_sources.supply_source_transitions(source_message_id,company_id,payload_hash,source_code,source_objects,previous_states,resulting_states,qualified_switch_ids,actor_user_id) VALUES(m.id,m.company_id,encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex'),wire->>'code',wire->'objects',before_states,after_states,ARRAY(SELECT (planned->>'switchId')::uuid FROM jsonb_array_elements(plans) planned WHERE planned->>'kind'='cancel_start'),p_actor_user_id);$t$,'')))/length($t$ INSERT INTO gridex_received_sources.supply_source_transitions(source_message_id,company_id,payload_hash,source_code,source_objects,previous_states,resulting_states,qualified_switch_ids,actor_user_id) VALUES(m.id,m.company_id,encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex'),wire->>'code',wire->'objects',before_states,after_states,ARRAY(SELECT (planned->>'switchId')::uuid FROM jsonb_array_elements(plans) planned WHERE planned->>'kind'='cancel_start'),p_actor_user_id);$t$)<>1 THEN RAISE EXCEPTION 'supply_before_legal_context_alias_bridge_predecessor_required';END IF;
 body:=replace(replace(f.prosrc,$t$ SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.id),'[]'::jsonb) INTO after_states FROM public.customer_supply_periods p WHERE p.company_id=m.company_id AND p.id IN (SELECT (planned->>'periodId')::uuid FROM jsonb_array_elements(plans) planned);$t$,$t$ SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.id),'[]'::jsonb) INTO after_states FROM public.customer_supply_periods p WHERE p.company_id=m.company_id AND p.id IN (SELECT (plan->>'periodId')::uuid FROM jsonb_array_elements(plans) plan);$t$),$t$ INSERT INTO gridex_received_sources.supply_source_transitions(source_message_id,company_id,payload_hash,source_code,source_objects,previous_states,resulting_states,qualified_switch_ids,actor_user_id) VALUES(m.id,m.company_id,encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex'),wire->>'code',wire->'objects',before_states,after_states,ARRAY(SELECT (planned->>'switchId')::uuid FROM jsonb_array_elements(plans) planned WHERE planned->>'kind'='cancel_start'),p_actor_user_id);$t$,$t$ INSERT INTO gridex_received_sources.supply_source_transitions(source_message_id,company_id,payload_hash,source_code,source_objects,previous_states,resulting_states,qualified_switch_ids,actor_user_id) VALUES(m.id,m.company_id,encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex'),wire->>'code',wire->'objects',before_states,after_states,ARRAY(SELECT (plan->>'switchId')::uuid FROM jsonb_array_elements(plans) plan WHERE plan->>'kind'='cancel_start'),p_actor_user_id);$t$);
 EXECUTE replace(f.definition,f.prosrc,body);
 IF(SELECT to_jsonb(p)-'prosrc' FROM pg_proc p WHERE oid=f.oid) IS DISTINCT FROM f.metadata THEN RAISE EXCEPTION 'supply_before_legal_context_alias_bridge_metadata_changed';END IF;
END$bridge$;
COMMIT;
