-- Each class has its own native target-fact hash and signed legal decision.
-- Actual Storage deletion is qualified in its deletion transaction, not inferred
-- from deleting metadata with SQL. No period/issuer/default grant is seeded.
BEGIN;
CREATE TABLE gridex_ediel_retention.blob_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),retention_class text NOT NULL CHECK(retention_class IN('received_ediel_message_content','transport_raw_mime_bytes')),target_id uuid NOT NULL,message_id uuid NOT NULL,source_hash text NOT NULL,target_hash text NOT NULL,document_bytes bytea NOT NULL CHECK(octet_length(document_bytes) BETWEEN 1 AND 1048576),document_hash text NOT NULL CHECK(document_hash=encode(sha256(document_bytes),'hex')),issuer_receipt jsonb,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(company_id,retention_class,target_id,target_hash,document_hash));
CREATE TABLE gridex_ediel_retention.blob_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),decision_id uuid NOT NULL REFERENCES gridex_ediel_retention.blob_decisions(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),outcome text NOT NULL CHECK(outcome IN('approved','held','rejected')),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.blob_revocations(decision_id uuid PRIMARY KEY REFERENCES gridex_ediel_retention.blob_decisions(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.blob_tombstones(retention_class text NOT NULL,target_id uuid NOT NULL,company_id uuid NOT NULL,message_id uuid NOT NULL,decision_id uuid NOT NULL REFERENCES gridex_ediel_retention.blob_decisions(id),review_id uuid NOT NULL REFERENCES gridex_ediel_retention.blob_reviews(id),source_hash text NOT NULL,target_hash text NOT NULL,public_content_hash text,byte_length bigint NOT NULL,storage_path text,actor_user_id uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(retention_class,target_id));
CREATE TABLE gridex_ediel_retention.blob_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),retention_class text NOT NULL,target_id uuid NOT NULL,kind text NOT NULL CHECK(kind IN('storage_delete_authorized','physical_bytes_removed')),actor_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(retention_class,target_id) REFERENCES gridex_ediel_retention.blob_tombstones(retention_class,target_id),UNIQUE(retention_class,target_id,kind));
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['blob_decisions','blob_reviews','blob_revocations','blob_tombstones','blob_events'] LOOP EXECUTE format('ALTER TABLE gridex_ediel_retention.%I OWNER TO gridex_ediel_retention_owner',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_ediel_retention.%I FROM PUBLIC,anon,authenticated,service_role',t);EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t||'_immutable',t);EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON gridex_ediel_retention.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t||'_no_truncate',t);END LOOP;END$$;
CREATE FUNCTION gridex_ediel_retention.public_content_v1(m public.ediel_messages) RETURNS jsonb LANGUAGE sql IMMUTABLE SET search_path=pg_catalog AS $$ SELECT jsonb_build_object('raw',m.raw_payload,'parsed',m.parsed_payload,'validation',m.validation_report,'metadata',m.metadata) $$;
CREATE FUNCTION gridex_ediel_retention.blob_revocation_lock_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN PERFORM id FROM gridex_ediel_retention.blob_decisions WHERE id=NEW.decision_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'blob_retention_revocation_target_required';END IF;RETURN NEW;END$$;
CREATE TRIGGER blob_retention_revocation_lock BEFORE INSERT ON gridex_ediel_retention.blob_revocations FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.blob_revocation_lock_v1();
CREATE FUNCTION gridex_ediel_retention.blob_basis_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE m public.ediel_messages%rowtype;s gridex_received_sources.sources%rowtype;p public.ediel_message_payloads%rowtype;facts jsonb;rawhash text;bytes bigint;path text;payloads jsonb;
BEGIN
 IF k='received_ediel_message_content' THEN
  SELECT * INTO STRICT m FROM public.ediel_messages WHERE id=target AND company_id=c FOR SHARE;SELECT * INTO STRICT s FROM gridex_received_sources.sources WHERE source_message_id=m.id AND company_id=c FOR SHARE;
  IF m.direction IS DISTINCT FROM 'inbound' OR s.raw_payload IS NULL OR m.raw_payload IS DISTINCT FROM s.raw_payload OR s.payload_hash IS DISTINCT FROM encode(sha256(convert_to(s.raw_payload,'UTF8')),'hex') THEN RAISE EXCEPTION 'retention_actual_received_original_required';END IF;
  PERFORM id FROM public.ediel_message_payloads WHERE company_id=c AND ediel_message_id=m.id ORDER BY id FOR SHARE;
  SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'raw',raw_payload,'encrypted',encrypted_payload,'hash',raw_payload_hash,'kind',payload_kind) ORDER BY id),'[]') INTO payloads FROM public.ediel_message_payloads WHERE company_id=c AND ediel_message_id=m.id;
  rawhash:=s.payload_hash;bytes:=octet_length(convert_to(s.raw_payload,'UTF8'));facts:=jsonb_build_object('source',to_jsonb(s),'publicContent',gridex_ediel_retention.public_content_v1(m),'payloadCopies',payloads);
 ELSIF k='transport_raw_mime_bytes' THEN
  SELECT * INTO STRICT p FROM public.ediel_message_payloads WHERE id=target AND company_id=c FOR SHARE;SELECT * INTO STRICT m FROM public.ediel_messages WHERE id=p.ediel_message_id AND company_id=c FOR SHARE;
  rawhash:=p.metadata->>'archived_mime_sha256';bytes:=(p.metadata->>'archived_mime_bytes')::bigint;path:='transport/'||c::text||'/'||m.id::text||'/'||rawhash||'.eml';
  IF m.direction IS DISTINCT FROM 'outbound' OR p.payload_kind NOT IN('raw_mime','smime_enveloped') OR p.metadata->>'archive_verified' IS DISTINCT FROM 'true' OR rawhash!~'^[a-f0-9]{64}$' OR bytes NOT BETWEEN 1 AND 33554432 OR p.encrypted_payload_ref IS DISTINCT FROM 'storage://ediel-files/'||path
  OR NOT (EXISTS(SELECT FROM gridex_ediel_transport.attempts a WHERE a.company_id=c AND a.message_id=m.id AND a.entered_at IS NOT NULL AND a.binding->>'mimeSha256'=rawhash AND a.binding->>'mimeArchiveRef'=p.encrypted_payload_ref AND a.binding->>'mimeLength'=bytes::text AND a.binding->>'rfcMessageId'=p.metadata->>'archived_rfc_message_id')
   OR EXISTS(SELECT FROM gridex_outbound_dispatch.attempts a JOIN gridex_outbound_dispatch.events e ON e.attempt_id=a.id AND e.kind='provider_call_entered' WHERE a.company_id=c AND a.message_id=m.id AND a.binding->>'mimeSha256'=rawhash AND a.binding->>'mimeArchiveRef'=p.encrypted_payload_ref AND a.binding->>'mimeLength'=bytes::text AND a.binding->>'rfcMessageId'=p.metadata->>'archived_rfc_message_id')) THEN RAISE EXCEPTION 'retention_private_entered_mime_original_required';END IF;
  facts:=jsonb_build_object('snapshot',to_jsonb(p),'message',m.id,'company',c,'environment',m.environment);
 ELSE RAISE EXCEPTION 'retention_class_not_implemented';END IF;
 RETURN jsonb_build_object('companyId',c,'retentionClass',k,'targetId',target,'messageId',m.id,'sourceHash',rawhash,'targetHash',encode(sha256(convert_to(facts::text,'UTF8')),'hex'),'publicContentHash',encode(sha256(convert_to(gridex_ediel_retention.public_content_v1(m)::text,'UTF8')),'hex'),'byteLength',bytes,'storagePath',path);
END$$;
CREATE FUNCTION gridex_ediel_retention.blob_receipt_v1(d gridex_ediel_retention.blob_decisions) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE k gridex_ediel_retention.issuers%rowtype;p jsonb;b bytea;issued timestamptz;expires timestamptz;deadline timestamptz;
BEGIN
 IF jsonb_typeof(d.issuer_receipt) IS DISTINCT FROM 'object' OR coalesce(d.issuer_receipt->>'signatureHex','')!~'^[a-f0-9]{64}$' OR length(coalesce(d.issuer_receipt->>'payloadBase64','')) NOT BETWEEN 1 AND 32768 THEN RETURN NULL;END IF;
 SELECT * INTO k FROM gridex_ediel_retention.issuers WHERE id=(d.issuer_receipt->>'issuerId')::uuid AND company_id=d.company_id FOR SHARE;
 IF k.id IS NULL OR now()<k.valid_from OR now()>=k.valid_to OR EXISTS(SELECT FROM gridex_ediel_retention.issuer_revocations WHERE issuer_id=k.id) OR EXISTS(SELECT FROM gridex_ediel_retention.blob_revocations WHERE decision_id=d.id) THEN RETURN NULL;END IF;
 b:=decode(d.issuer_receipt->>'payloadBase64','base64');IF encode(gridex_requested_changes.receipt_hmac_sha256_v1(b,k.signing_key),'hex') IS DISTINCT FROM d.issuer_receipt->>'signatureHex' THEN RETURN NULL;END IF;
 p:=convert_from(b,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;deadline:=(p->>'retainUntil')::timestamptz;
 IF p->>'format' IS DISTINCT FROM 'ediel_blob_retention_policy_v1' OR p->>'retentionClass' IS DISTINCT FROM d.retention_class OR p->>'companyId' IS DISTINCT FROM d.company_id::text OR p->>'targetId' IS DISTINCT FROM d.target_id::text OR p->>'messageId' IS DISTINCT FROM d.message_id::text OR p->>'sourceHash' IS DISTINCT FROM d.source_hash OR p->>'targetHash' IS DISTINCT FROM d.target_hash OR p->>'documentHash' IS DISTINCT FROM d.document_hash OR p->>'issuerLegalReference' IS DISTINCT FROM k.legal_reference OR nullif(p->>'legalBasisReference','') IS NULL OR isfinite(issued) IS DISTINCT FROM true OR isfinite(expires) IS DISTINCT FROM true OR isfinite(deadline) IS DISTINCT FROM true OR issued>now() OR expires<=now() OR issued<k.valid_from OR expires>k.valid_to THEN RETURN NULL;END IF;RETURN p;
EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN NULL;
END$$;
CREATE FUNCTION gridex_ediel_retention.blob_current_v1(d gridex_ediel_retention.blob_decisions) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE r gridex_ediel_retention.blob_reviews%rowtype;claims jsonb;BEGIN
 SELECT * INTO r FROM gridex_ediel_retention.blob_reviews WHERE decision_id=d.id ORDER BY created_at DESC,id DESC LIMIT 1 FOR SHARE;
 PERFORM id FROM auth.users WHERE id=r.actor_user_id FOR SHARE;PERFORM id FROM public.user_profiles WHERE id=r.actor_user_id FOR SHARE;PERFORM user_id FROM public.company_memberships WHERE company_id=d.company_id AND user_id=r.actor_user_id FOR SHARE;
 IF r.outcome IS DISTINCT FROM 'approved' OR NOT EXISTS(SELECT FROM auth.users WHERE id=r.actor_user_id AND deleted_at IS NULL AND (banned_until IS NULL OR banned_until<=now())) OR NOT EXISTS(SELECT FROM public.user_profiles WHERE id=r.actor_user_id AND user_status='active') OR NOT EXISTS(SELECT FROM public.company_memberships WHERE company_id=d.company_id AND user_id=r.actor_user_id AND status='active' AND is_active AND accepted_at IS NOT NULL) OR gridex_ediel_retention.permission_v1(d.company_id,r.actor_user_id,'ediel.retention.review') IS NOT TRUE THEN RETURN NULL;END IF;
 claims:=gridex_ediel_retention.blob_receipt_v1(d);IF claims IS NULL OR (claims->>'retainUntil')::timestamptz>now() THEN RETURN NULL;END IF;RETURN r.id;
END$$;
CREATE FUNCTION public.ediel_submit_blob_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid,p_document_base64 text,p_issuer_receipt jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE basis jsonb;d gridex_ediel_retention.blob_decisions%rowtype;b bytea;h text;BEGIN
 PERFORM gridex_ediel_retention.actor_v1(p_company_id,p_actor_user_id,'ediel.retention.submit');IF gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'communication.write') IS NOT TRUE THEN RAISE EXCEPTION 'blob_retention_scoped_communication_required' USING ERRCODE='42501';END IF;
 basis:=gridex_ediel_retention.blob_basis_v1(p_company_id,p_retention_class,p_target_id);IF length(p_document_base64)>1398104 THEN RAISE EXCEPTION 'blob_retention_document_limit';END IF;b:=decode(p_document_base64,'base64');IF octet_length(b) NOT BETWEEN 1 AND 1048576 THEN RAISE EXCEPTION 'blob_retention_document_required';END IF;h:=encode(sha256(b),'hex');
 INSERT INTO gridex_ediel_retention.blob_decisions(company_id,retention_class,target_id,message_id,source_hash,target_hash,document_bytes,document_hash,issuer_receipt,submitted_by) VALUES(p_company_id,p_retention_class,p_target_id,(basis->>'messageId')::uuid,basis->>'sourceHash',basis->>'targetHash',b,h,p_issuer_receipt,p_actor_user_id) ON CONFLICT(company_id,retention_class,target_id,target_hash,document_hash) DO NOTHING;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.blob_decisions WHERE company_id=p_company_id AND retention_class=p_retention_class AND target_id=p_target_id AND target_hash=basis->>'targetHash' AND document_hash=h FOR SHARE;IF d.issuer_receipt IS DISTINCT FROM p_issuer_receipt THEN RAISE EXCEPTION 'blob_retention_original_receipt_conflict';END IF;
 INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'blob_retention_decision',d.id,'ediel.retention.blob_submitted',basis-'storagePath');RETURN jsonb_build_object('status','submitted','decisionId',d.id,'sourceHash',d.source_hash,'targetHash',d.target_hash,'messageId',d.message_id,'documentHash',h,'issuerQualified',gridex_ediel_retention.blob_receipt_v1(d) IS NOT NULL);
END$$;
CREATE FUNCTION public.ediel_review_blob_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid,p_outcome text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE d gridex_ediel_retention.blob_decisions%rowtype;outcome text;r uuid;BEGIN
 PERFORM gridex_ediel_retention.actor_v1(p_company_id,p_actor_user_id,'ediel.retention.review');SELECT * INTO STRICT d FROM gridex_ediel_retention.blob_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;IF p_outcome NOT IN('approve','hold','reject') OR nullif(p_reason,'') IS NULL OR length(p_reason)>4000 THEN RAISE EXCEPTION 'blob_retention_review_shape_required';END IF;IF p_outcome='approve' AND d.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'blob_retention_separate_reviewer_required';END IF;
 outcome:=CASE WHEN p_outcome='reject' THEN 'rejected' WHEN p_outcome='approve' AND gridex_ediel_retention.blob_receipt_v1(d) IS NOT NULL THEN 'approved' ELSE 'held' END;
 INSERT INTO gridex_ediel_retention.blob_reviews(decision_id,actor_user_id,outcome,reason) VALUES(d.id,p_actor_user_id,outcome,p_reason) RETURNING id INTO r;INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'blob_retention_decision',d.id,'ediel.retention.blob_reviewed',jsonb_build_object('reviewId',r,'outcome',outcome));RETURN jsonb_build_object('status',outcome,'decisionId',d.id,'reviewId',r);
END$$;
CREATE FUNCTION public.ediel_revoke_blob_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid,p_reason text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM gridex_ediel_retention.actor_v1(p_company_id,p_actor_user_id,'ediel.retention.review');PERFORM id FROM gridex_ediel_retention.blob_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;IF NOT FOUND OR nullif(p_reason,'') IS NULL THEN RAISE EXCEPTION 'blob_retention_revoke_scope_required';END IF;INSERT INTO gridex_ediel_retention.blob_revocations(decision_id,actor_user_id,reason) VALUES(p_decision_id,p_actor_user_id,p_reason) ON CONFLICT DO NOTHING;INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'blob_retention_decision',p_decision_id,'ediel.retention.blob_revoked',jsonb_build_object('reason',p_reason));END$$;
ALTER TABLE gridex_received_sources.sources ADD COLUMN retention_byte_length bigint,ADD COLUMN retention_purged_at timestamptz;
DROP TRIGGER no_evidence_update_delete ON gridex_received_sources.sources;
UPDATE gridex_received_sources.sources SET retention_byte_length=octet_length(convert_to(raw_payload,'UTF8'));
ALTER TABLE gridex_received_sources.sources DROP CONSTRAINT received_source_hash_check;
ALTER TABLE gridex_received_sources.sources ADD CONSTRAINT received_source_hash_check CHECK((raw_payload IS NULL AND payload_hash IS NULL AND retention_purged_at IS NULL) OR (raw_payload IS NOT NULL AND payload_hash=encode(sha256(convert_to(raw_payload,'UTF8')),'hex') AND retention_purged_at IS NULL) OR(raw_payload IS NULL AND payload_hash~'^[a-f0-9]{64}$' AND retention_byte_length>0 AND retention_purged_at IS NOT NULL));
CREATE FUNCTION gridex_ediel_retention.source_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 IF TG_OP<>'UPDATE' OR old.raw_payload IS NULL OR new.raw_payload IS NOT NULL OR new.retention_purged_at IS NULL OR (to_jsonb(new)-ARRAY['raw_payload','retention_purged_at']) IS DISTINCT FROM (to_jsonb(old)-ARRAY['raw_payload','retention_purged_at']) OR NOT EXISTS(SELECT FROM gridex_ediel_retention.blob_tombstones t WHERE t.retention_class='received_ediel_message_content' AND t.target_id=old.source_message_id AND t.company_id=old.company_id AND t.source_hash=old.payload_hash AND t.byte_length=octet_length(convert_to(old.raw_payload,'UTF8')) AND t.created_at=new.retention_purged_at) THEN RAISE EXCEPTION 'received_original_immutable_without_native_retention';END IF;RETURN new;END$$;
CREATE FUNCTION gridex_ediel_retention.source_insert_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN IF new.retention_purged_at IS NOT NULL THEN RAISE EXCEPTION 'received_original_new_tombstone_forbidden';END IF;new.retention_byte_length:=octet_length(convert_to(new.raw_payload,'UTF8'));RETURN new;END$$;
CREATE TRIGGER retention_source_insert BEFORE INSERT ON gridex_received_sources.sources FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.source_insert_v1();
CREATE TRIGGER no_evidence_update_delete BEFORE UPDATE OR DELETE ON gridex_received_sources.sources FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.source_guard_v1();
CREATE FUNCTION public.ediel_is_qualified_retention_transition_v1(oldrow public.ediel_messages,newrow public.ediel_messages) RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT oldrow.raw_payload IS NOT NULL AND newrow.raw_payload IS NULL AND newrow.parsed_payload='{}'::jsonb AND newrow.validation_report='{}'::jsonb AND coalesce(newrow.metadata,'{}')='{}'::jsonb
 AND (to_jsonb(oldrow)-ARRAY['raw_payload','parsed_payload','validation_report','metadata','updated_at']) IS NOT DISTINCT FROM (to_jsonb(newrow)-ARRAY['raw_payload','parsed_payload','validation_report','metadata','updated_at'])
 AND EXISTS(SELECT FROM gridex_ediel_retention.blob_tombstones t WHERE t.retention_class='received_ediel_message_content' AND t.target_id=oldrow.id AND t.company_id=oldrow.company_id AND t.source_hash=encode(sha256(convert_to(oldrow.raw_payload,'UTF8')),'hex') AND t.public_content_hash=encode(sha256(convert_to(gridex_ediel_retention.public_content_v1(oldrow)::text,'UTF8')),'hex'))
$$;
-- Preserve each actual installed trigger owner/ACL and complete original body.
-- The only early return is the exact native-qualified erase transition above;
-- ordinary mutation/capture/namespace/owner guards continue unchanged.
DO $$DECLARE f record;body text;definition text;BEGIN FOR f IN SELECT DISTINCT p.oid,p.oid::regprocedure signature,p.prosrc,l.lanname FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid JOIN pg_language l ON l.oid=p.prolang WHERE t.tgrelid='public.ediel_messages'::regclass AND NOT t.tgisinternal AND (t.tgtype::int&16)=16 AND p.prosrc~*'(raw_payload|parsed_payload|receivedProdatContext|receivedAckContext|receivedUtiltsContext)' LOOP
 IF EXISTS(SELECT FROM pg_trigger t WHERE t.tgfoid=f.oid AND t.tgrelid<>'public.ediel_messages'::regclass AND NOT t.tgisinternal) THEN RAISE EXCEPTION 'retention_shared_trigger_requires_explicit_review:%',f.signature;END IF;
 IF f.lanname<>'plpgsql' OR f.prosrc!~*'\mBEGIN\M' THEN RAISE EXCEPTION 'retention_trigger_body_requires_explicit_review:%',f.signature;END IF;
 body:=regexp_replace(f.prosrc,'\mBEGIN\M','BEGIN IF TG_OP=''UPDATE'' AND OLD.raw_payload IS NOT NULL AND NEW.raw_payload IS NULL AND public.ediel_is_qualified_retention_transition_v1(OLD,NEW) THEN RETURN NEW;END IF;','i');definition:=pg_get_functiondef(f.oid);IF position(f.prosrc IN definition)=0 THEN RAISE EXCEPTION 'retention_trigger_definition_binding_failed';END IF;EXECUTE replace(definition,f.prosrc,body);
END LOOP;END$$;
CREATE FUNCTION gridex_ediel_retention.payload_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 IF EXISTS(SELECT FROM gridex_ediel_retention.blob_tombstones t WHERE t.retention_class='received_ediel_message_content' AND t.company_id=new.company_id AND t.message_id=new.ediel_message_id) AND (new.raw_payload IS NOT NULL OR new.encrypted_payload IS NOT NULL) THEN RAISE EXCEPTION 'ediel_payload_original_retention_tombstoned';END IF;RETURN new;
END$$;
CREATE TRIGGER retention_payload_guard BEFORE INSERT OR UPDATE ON public.ediel_message_payloads FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.payload_guard_v1();
CREATE FUNCTION public.ediel_require_source_bytes_available_v1(p_company_id uuid,p_source_message_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 IF EXISTS(SELECT FROM gridex_ediel_retention.blob_tombstones WHERE company_id=p_company_id AND message_id=p_source_message_id) THEN RAISE EXCEPTION 'ediel_original_bytes_retention_tombstoned';END IF;END$$;
CREATE FUNCTION public.ediel_begin_blob_purge_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE d gridex_ediel_retention.blob_decisions%rowtype;t gridex_ediel_retention.blob_tombstones%rowtype;basis jsonb;r uuid;at timestamptz:=clock_timestamp();BEGIN
 PERFORM gridex_ediel_retention.actor_v1(p_company_id,p_actor_user_id,'ediel.retention.purge');IF gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'communication.write') IS NOT TRUE THEN RAISE EXCEPTION 'blob_retention_scoped_communication_required' USING ERRCODE='42501';END IF;
 LOCK TABLE public.ediel_message_payloads IN SHARE ROW EXCLUSIVE MODE;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.blob_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;PERFORM id FROM public.ediel_messages WHERE id=d.message_id AND company_id=p_company_id FOR UPDATE;
 SELECT * INTO t FROM gridex_ediel_retention.blob_tombstones WHERE retention_class=d.retention_class AND target_id=d.target_id;
 IF FOUND THEN IF t.decision_id IS DISTINCT FROM d.id THEN RAISE EXCEPTION 'blob_retention_tombstone_conflict';END IF;RETURN jsonb_build_object('status',CASE WHEN t.retention_class='received_ediel_message_content' OR EXISTS(SELECT FROM gridex_ediel_retention.blob_events e WHERE e.retention_class=t.retention_class AND e.target_id=t.target_id AND e.kind='physical_bytes_removed') THEN 'purged' ELSE 'storage_purge_pending' END,'targetId',t.target_id,'sourceHash',t.source_hash,'byteLength',t.byte_length,'storagePath',t.storage_path,'replay',true);END IF;
 r:=gridex_ediel_retention.blob_current_v1(d);IF r IS NULL THEN RETURN jsonb_build_object('status','held','missing',ARRAY['current_blob_class_legal_review_deadline']);END IF;
 basis:=gridex_ediel_retention.blob_basis_v1(p_company_id,d.retention_class,d.target_id);IF basis->>'targetHash' IS DISTINCT FROM d.target_hash OR basis->>'sourceHash' IS DISTINCT FROM d.source_hash THEN RETURN jsonb_build_object('status','held','missing',ARRAY['exact_native_blob_target_changed']);END IF;
 INSERT INTO gridex_ediel_retention.blob_tombstones(retention_class,target_id,company_id,message_id,decision_id,review_id,source_hash,target_hash,public_content_hash,byte_length,storage_path,actor_user_id,created_at) VALUES(d.retention_class,d.target_id,d.company_id,d.message_id,d.id,r,d.source_hash,d.target_hash,basis->>'publicContentHash',(basis->>'byteLength')::bigint,basis->>'storagePath',p_actor_user_id,at);
 IF d.retention_class='received_ediel_message_content' THEN
  UPDATE gridex_received_sources.sources SET raw_payload=NULL,retention_purged_at=at WHERE source_message_id=d.target_id AND company_id=p_company_id;
  UPDATE public.ediel_message_payloads SET raw_payload=NULL,encrypted_payload=NULL WHERE company_id=p_company_id AND ediel_message_id=d.message_id;
  UPDATE public.ediel_messages SET raw_payload=NULL,parsed_payload='{}',validation_report='{}',metadata='{}' WHERE id=d.message_id AND company_id=p_company_id;
 END IF;
 INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'ediel_message',d.message_id,'ediel.retention.blob_tombstoned',jsonb_build_object('decisionId',d.id,'targetId',d.target_id,'sourceHash',d.source_hash,'retentionClass',d.retention_class,'purgedAt',at));RETURN jsonb_build_object('status',CASE WHEN d.retention_class='received_ediel_message_content' THEN 'purged' ELSE 'storage_purge_pending' END,'targetId',d.target_id,'sourceHash',d.source_hash,'byteLength',(basis->>'byteLength')::bigint,'storagePath',basis->>'storagePath','replay',false);
END$$;
CREATE FUNCTION gridex_ediel_retention.storage_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE t gridex_ediel_retention.blob_tombstones%rowtype;d gridex_ediel_retention.blob_decisions%rowtype;basis jsonb;r uuid;actor uuid:=auth.uid();BEGIN
 IF TG_OP<>'DELETE' AND new.bucket_id='ediel-files' AND EXISTS(SELECT FROM gridex_ediel_retention.blob_tombstones WHERE retention_class='transport_raw_mime_bytes' AND storage_path=new.name) THEN RAISE EXCEPTION 'ediel_storage_retention_object_tombstoned';END IF;
 IF (CASE WHEN TG_OP='INSERT' THEN new.bucket_id ELSE old.bucket_id END) IS DISTINCT FROM 'ediel-files' THEN IF TG_OP='DELETE' THEN RETURN old;ELSE RETURN new;END IF;END IF;
 SELECT * INTO t FROM gridex_ediel_retention.blob_tombstones WHERE retention_class='transport_raw_mime_bytes' AND storage_path=(CASE WHEN TG_OP='INSERT' THEN new.name ELSE old.name END);
 IF NOT FOUND THEN IF TG_OP='UPDATE' AND old.name LIKE 'transport/%' AND EXISTS(SELECT FROM public.ediel_message_payloads p WHERE p.encrypted_payload_ref='storage://ediel-files/'||old.name AND p.metadata->>'archive_verified'='true') THEN RAISE EXCEPTION 'ediel_storage_archived_object_immutable';END IF;IF TG_OP='DELETE' AND old.name LIKE 'transport/%' THEN RAISE EXCEPTION 'ediel_storage_native_class_purge_required';END IF;IF TG_OP='DELETE' THEN RETURN old;ELSE RETURN new;END IF;END IF;
 IF TG_OP<>'DELETE' THEN RAISE EXCEPTION 'ediel_storage_retention_object_tombstoned';END IF;
 PERFORM gridex_ediel_retention.actor_v1(t.company_id,actor,'ediel.retention.purge');IF gridex_ediel_retention.permission_v1(t.company_id,actor,'communication.write') IS NOT TRUE THEN RAISE EXCEPTION 'blob_retention_scoped_communication_required';END IF;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.blob_decisions WHERE id=t.decision_id FOR UPDATE;r:=gridex_ediel_retention.blob_current_v1(d);basis:=gridex_ediel_retention.blob_basis_v1(t.company_id,t.retention_class,t.target_id);
 IF r IS NULL OR basis->>'targetHash' IS DISTINCT FROM t.target_hash OR basis->>'storagePath' IS DISTINCT FROM old.name THEN RAISE EXCEPTION 'ediel_storage_current_legal_purge_required';END IF;
 INSERT INTO gridex_ediel_retention.blob_events(retention_class,target_id,kind,actor_user_id) VALUES(t.retention_class,t.target_id,'storage_delete_authorized',actor) ON CONFLICT DO NOTHING;RETURN old;
END$$;
CREATE TRIGGER ediel_retention_storage_guard BEFORE INSERT OR UPDATE OR DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.storage_guard_v1();
-- Restrictive predicate: actual Storage owner/deletion still checks current
-- native JWT+grants/legal decision with row/table locks in the DELETE trigger.
CREATE FUNCTION public.ediel_storage_retention_target_v1(p_path text) RETURNS SETOF boolean LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT true FROM gridex_ediel_retention.blob_tombstones t WHERE t.retention_class='transport_raw_mime_bytes' AND t.storage_path=p_path AND gridex_ediel_retention.permission_v1(t.company_id,auth.uid(),'ediel.retention.purge') IS TRUE AND EXISTS(SELECT FROM public.company_memberships m WHERE m.company_id=t.company_id AND m.user_id=auth.uid() AND m.status='active' AND m.is_active AND m.accepted_at IS NOT NULL)
$$;
CREATE POLICY ediel_qualified_retention_storage_delete ON storage.objects FOR DELETE TO authenticated USING(bucket_id='ediel-files' AND EXISTS(SELECT FROM public.ediel_storage_retention_target_v1(name)));
CREATE FUNCTION public.ediel_finish_blob_storage_purge_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE d gridex_ediel_retention.blob_decisions%rowtype;t gridex_ediel_retention.blob_tombstones%rowtype;BEGIN
 PERFORM gridex_ediel_retention.actor_v1(p_company_id,p_actor_user_id,'ediel.retention.purge');SELECT * INTO STRICT d FROM gridex_ediel_retention.blob_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;SELECT * INTO STRICT t FROM gridex_ediel_retention.blob_tombstones WHERE retention_class=d.retention_class AND target_id=d.target_id;
 IF t.retention_class IS DISTINCT FROM 'transport_raw_mime_bytes' OR NOT EXISTS(SELECT FROM gridex_ediel_retention.blob_events WHERE retention_class=t.retention_class AND target_id=t.target_id AND kind='storage_delete_authorized') OR EXISTS(SELECT FROM storage.objects WHERE bucket_id='ediel-files' AND name=t.storage_path) THEN RAISE EXCEPTION 'ediel_storage_actual_delete_receipt_required';END IF;
 IF EXISTS(SELECT FROM gridex_ediel_retention.blob_events WHERE retention_class=t.retention_class AND target_id=t.target_id AND kind='physical_bytes_removed') THEN RETURN jsonb_build_object('status','purged','targetId',t.target_id,'sourceHash',t.source_hash,'byteLength',t.byte_length,'replay',true);END IF;
 INSERT INTO gridex_ediel_retention.blob_events(retention_class,target_id,kind,actor_user_id) VALUES(t.retention_class,t.target_id,'physical_bytes_removed',p_actor_user_id) ON CONFLICT DO NOTHING;
 INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'ediel_message_payload',t.target_id,'ediel.retention.mime_bytes_removed',jsonb_build_object('decisionId',d.id,'sourceHash',t.source_hash,'byteLength',t.byte_length,'physicalReceipt','authenticated_storage_delete_object_absence'));RETURN jsonb_build_object('status','purged','targetId',t.target_id,'sourceHash',t.source_hash,'byteLength',t.byte_length,'replay',false);
END$$;
-- Wrappers run the genuine predecessor first: accepted immutable replay stays
-- receipt-first; a fresh prepare/enter true result is rolled back if tombstoned.
ALTER FUNCTION gridex_ediel_transport.mutate_v1(jsonb) RENAME TO mutate_before_blob_retention_v1;
CREATE FUNCTION gridex_ediel_transport.mutate_v1(p_input jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;BEGIN r:=gridex_ediel_transport.mutate_before_blob_retention_v1(p_input);IF p_input->>'action' IN('prepare','enter') AND r->>'proceed'='true' THEN PERFORM public.ediel_require_source_bytes_available_v1((p_input->>'companyId')::uuid,(p_input->>'messageId')::uuid);END IF;RETURN r;END$$;
ALTER FUNCTION gridex_outbound_dispatch.mutate_v1(jsonb) RENAME TO mutate_before_blob_retention_v1;
CREATE FUNCTION gridex_outbound_dispatch.mutate_v1(p_input jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;BEGIN r:=gridex_outbound_dispatch.mutate_before_blob_retention_v1(p_input);IF p_input->>'action' IN('prepare','enter') AND r->>'proceed'='true' THEN PERFORM public.ediel_require_source_bytes_available_v1((p_input->>'companyId')::uuid,(p_input->>'messageId')::uuid);END IF;RETURN r;END$$;
REVOKE ALL ON FUNCTION gridex_ediel_transport.mutate_v1(jsonb),gridex_outbound_dispatch.mutate_v1(jsonb),gridex_ediel_transport.mutate_before_blob_retention_v1(jsonb),gridex_outbound_dispatch.mutate_before_blob_retention_v1(jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION gridex_ediel_transport.mutate_v1(jsonb),gridex_outbound_dispatch.mutate_v1(jsonb) TO service_role;
GRANT USAGE ON SCHEMA storage,gridex_ediel_transport,gridex_outbound_dispatch TO gridex_ediel_retention_owner;
GRANT SELECT,UPDATE ON public.ediel_messages,public.ediel_message_payloads,gridex_received_sources.sources,gridex_ediel_transport.attempts,gridex_outbound_dispatch.attempts,gridex_outbound_dispatch.events,storage.objects TO gridex_ediel_retention_owner;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure identity FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_ediel_retention' AND p.proname IN('public_content_v1','blob_basis_v1','blob_receipt_v1','blob_current_v1','blob_revocation_lock_v1','source_guard_v1','source_insert_v1','storage_guard_v1','payload_guard_v1') OR n.nspname='public' AND p.proname IN('ediel_submit_blob_retention_v1','ediel_review_blob_retention_v1','ediel_revoke_blob_retention_v1','ediel_is_qualified_retention_transition_v1','ediel_require_source_bytes_available_v1','ediel_begin_blob_purge_v1','ediel_finish_blob_storage_purge_v1','ediel_storage_retention_target_v1') LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO gridex_ediel_retention_owner',f.identity);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.identity);END LOOP;END$$;
GRANT EXECUTE ON FUNCTION public.ediel_submit_blob_retention_v1(uuid,uuid,text,uuid,text,jsonb),public.ediel_review_blob_retention_v1(uuid,uuid,uuid,text,text),public.ediel_revoke_blob_retention_v1(uuid,uuid,uuid,text),public.ediel_begin_blob_purge_v1(uuid,uuid,uuid),public.ediel_finish_blob_storage_purge_v1(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_is_qualified_retention_transition_v1(public.ediel_messages,public.ediel_messages) TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.ediel_require_source_bytes_available_v1(uuid,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ediel_storage_retention_target_v1(text) TO authenticated;
COMMIT;
