-- Generated by pinned Supabase CLI 2.101.0 on 2026-10-10.
-- Qualify the private assigned-negative owner; preserve ordinary domain-effect authority.
-- External proposed forward only; ROOT owns fresh CLI migration construction.
-- Existing published migrations and authentic capture outputs remain immutable.
BEGIN;
DO $h6_domain_birth_forward$
DECLARE target_oid oid;before_definition text;after_definition text;old_body text;new_body text;before_metadata jsonb;
BEGIN
 target_oid:='gridex_received_sources.require_domain_response_at_birth_v1()'::regprocedure;
 SELECT prosrc,to_jsonb(p)-'prosrc' INTO old_body,before_metadata FROM pg_proc p WHERE p.oid=target_oid;
 IF encode(sha256(convert_to(old_body,'UTF8')),'hex') IS DISTINCT FROM '7c5eb47550b028fe325e503df04821897e1983c6aefef1ac962d830a3a92e544' THEN
  RAISE EXCEPTION 'h6_domain_birth_unknown_preimage:require_domain_response_at_birth_v1';
 END IF;
 new_body:=$h6_domain_birth_body$
DECLARE s public.ediel_messages%rowtype;initial jsonb;actual jsonb;final_facet jsonb;positive_indices integer[];w gridex_ediel_outbound_owner.witnesses%rowtype;
 existing gridex_ediel_ack_guide.prodat_structural_response_bindings%rowtype;facet_text text;facet_hash text;
 common_witness gridex_ediel_common_header.negative_witnesses%rowtype;
BEGIN
 IF NEW.direction IS DISTINCT FROM 'outbound' OR NEW.message_family IS DISTINCT FROM 'APERAK' OR NEW.raw_payload IS NULL
  OR(TG_OP='UPDATE' AND OLD.raw_payload IS NOT NULL) THEN RETURN NEW;END IF;
 SELECT * INTO s FROM public.ediel_messages WHERE id=NEW.related_message_id AND company_id=NEW.company_id AND environment=NEW.environment
  AND direction='inbound' AND message_family='PRODAT' FOR SHARE;
 IF s.id IS NULL OR(s.message_code NOT IN('Z04','Z05','Z14','Z15') AND NOT(s.message_code='Z06' AND EXISTS(SELECT FROM gridex_requested_changes.confirmed_customer_versions v WHERE v.source_message_id=s.id AND v.company_id=s.company_id AND v.environment=s.environment AND v.event_id IS NOT NULL AND v.bilateral_artifact_id IS NULL))) THEN RETURN NEW;END IF;
 PERFORM src.source_message_id FROM gridex_received_sources.sources src WHERE src.source_message_id=s.id AND src.company_id=s.company_id AND src.environment=s.environment FOR UPDATE;
 -- Assigned negative-only originals use their own frozen common-header owner,
 -- not a domain-effect witness. Qualify its full private source/route/ACK proof
 -- before birth; existing AFTER consumption still seals this exact ACK once.
 IF NEW.execution_context_snapshot->>'prodatCommonHeaderNegativeWitnessId' IS NOT NULL
  AND gridex_ediel_header_negative_birth.is_bound_v1(s,false) IS TRUE THEN
  common_witness:=gridex_ediel_common_header.witness_v1(NEW);
  IF common_witness.actor_user_id IS DISTINCT FROM NEW.created_by
   OR (common_witness.evidence-'syntaxAssessmentId') IS DISTINCT FROM gridex_ediel_header_negative_birth.evidence_v1(s)
   OR NEW.ack_outcome IS DISTINCT FROM 'negative'
   OR NEW.execution_context_snapshot->>'outboundOwnerWitnessId' IS NOT NULL THEN
   RAISE EXCEPTION 'prodat_domain_response_frozen_owner_required';
  END IF;
  RETURN NEW;
 END IF;
 SELECT * INTO w FROM gridex_ediel_outbound_owner.witnesses WHERE id=(NEW.execution_context_snapshot->>'outboundOwnerWitnessId')::uuid FOR SHARE;
 IF w.id IS NULL OR w.company_id IS DISTINCT FROM NEW.company_id OR w.environment IS DISTINCT FROM NEW.environment OR w.related_message_id IS DISTINCT FROM s.id
  OR w.payload_sha256 IS DISTINCT FROM encode(sha256(convert_to(NEW.raw_payload,'UTF8')),'hex') THEN RAISE EXCEPTION 'prodat_domain_response_frozen_owner_required';END IF;
 SELECT * INTO existing FROM gridex_ediel_ack_guide.prodat_structural_response_bindings WHERE witness_id=w.id;
 IF existing.witness_id IS NOT NULL THEN
  IF existing.source_message_id IS DISTINCT FROM s.id OR existing.company_id IS DISTINCT FROM NEW.company_id OR existing.environment IS DISTINCT FROM NEW.environment
   OR existing.ack_hash IS DISTINCT FROM w.payload_sha256 OR existing.facet_hash IS DISTINCT FROM encode(sha256(convert_to(existing.facet_text,'UTF8')),'hex')
   OR existing.facet_text::jsonb->>'sourcePayloadHash' IS DISTINCT FROM encode(sha256(convert_to(s.raw_payload,'UTF8')),'hex') THEN RAISE EXCEPTION 'prodat_domain_response_frozen_owner_changed';END IF;
  -- The actual prepare already froze committed effects. Do not reselect a
  -- newer canonical leaf or independent role when consuming that same seal.
  RETURN NEW;
 END IF;
 initial:=gridex_received_sources.require_prodat_responses_v1(NEW.company_id,s.id);
 actual:=gridex_ediel_ack_guide.prodat_wire_responses_v1(NEW.raw_payload,initial->'objects');
 SELECT array_agg(DISTINCT(x->>'lineIndex')::integer ORDER BY(x->>'lineIndex')::integer) INTO positive_indices FROM jsonb_array_elements(actual)x WHERE x->>'ercCode'='100';
 IF positive_indices IS NULL THEN RETURN NEW;END IF;
 final_facet:=gridex_received_sources.prodat_structural_response_v1(NEW.company_id,s.id,positive_indices);
 IF final_facet IS NULL THEN RAISE EXCEPTION 'prodat_domain_response_own_effect_required';END IF;
 facet_text:=final_facet::text;facet_hash:=encode(sha256(convert_to(facet_text,'UTF8')),'hex');
 INSERT INTO gridex_ediel_ack_guide.prodat_structural_response_bindings VALUES(w.id,s.id,NEW.company_id,NEW.environment,w.payload_sha256,facet_text,facet_hash);
 RETURN NEW;
END $h6_domain_birth_body$;
 before_definition:=pg_get_functiondef(target_oid);
 IF (length(before_definition)-length(replace(before_definition,old_body,'')))/length(old_body)<>1 THEN
  RAISE EXCEPTION 'h6_domain_birth_unique_body_required:require_domain_response_at_birth_v1';
 END IF;
 after_definition:=replace(before_definition,old_body,new_body);
 IF replace(after_definition,new_body,old_body) IS DISTINCT FROM before_definition THEN
  RAISE EXCEPTION 'h6_domain_birth_full_definition_inverse_required:require_domain_response_at_birth_v1';
 END IF;
 EXECUTE after_definition;
 IF (SELECT encode(sha256(convert_to(prosrc,'UTF8')),'hex') FROM pg_proc WHERE oid=target_oid) IS DISTINCT FROM 'e0892dd2280c68e9968eef2d9f2b867b802331932a5fbf9714934a765977d825'
  OR (SELECT to_jsonb(p)-'prosrc' FROM pg_proc p WHERE p.oid=target_oid) IS DISTINCT FROM before_metadata THEN
  RAISE EXCEPTION 'h6_domain_birth_postimage_or_metadata_changed:require_domain_response_at_birth_v1';
 END IF;
END
$h6_domain_birth_forward$;
COMMIT;
