-- P26.A r3 pp15–16,47,114–116: a customer facet belongs to the
-- first physical register of one point+agency group. Same-object later LIN
-- does not create another customer, and cannot supply missing first UD/IV/LI.
-- Every original still requires the genuine sole accepted canonical assessment
-- and exact raw SHA/legal/supply/contract/issuer/reviewer source. Distinct objects
-- remain held until an atomic whole-source multi-object facet owner exists.
BEGIN;
CREATE OR REPLACE FUNCTION public.ediel_apply_customer_before_bilateral_v1(p_company_id uuid,p_source_message_id uuid,p_actor_user_id uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE m public.ediel_messages%rowtype;src gridex_received_sources.sources%rowtype;
 canonical gridex_received_sources.validation_assessments%rowtype;prior gridex_requested_changes.confirmed_customer_versions%rowtype;
 candidate gridex_requested_changes.events%rowtype;e gridex_requested_changes.events%rowtype;point public.metering_points%rowtype;
 tokens jsonb;own_tokens jsonb;ud jsonb;dtm jsonb;lin jsonb;physical_at timestamptz;party jsonb;b jsonb;result jsonb;
 n integer;qualified_count integer:=0;first_lin integer;end_lin integer;
BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'archive','death') IS NOT TRUE THEN RAISE EXCEPTION 'customer_source_actor_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO m FROM public.ediel_messages WHERE id=p_source_message_id AND company_id=p_company_id FOR UPDATE;
 IF NOT FOUND OR m.direction IS DISTINCT FROM 'inbound' OR m.message_standard IS DISTINCT FROM 'edifact' OR m.message_family IS DISTINCT FROM 'PRODAT' OR m.message_code IS DISTINCT FROM 'Z06' THEN RAISE EXCEPTION 'customer_source_original_required';END IF;
 PERFORM gridex_ediel_inbound_context.require_v1(p_company_id,m.id);
 PERFORM gridex_ediel_source_rules.require_v1(p_company_id,m.id);
 SELECT * INTO src FROM gridex_received_sources.sources WHERE source_message_id=m.id AND company_id=p_company_id AND environment=m.environment FOR UPDATE;
 IF src.source_message_id IS NULL OR src.raw_payload IS DISTINCT FROM m.raw_payload OR src.payload_hash IS DISTINCT FROM encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex') OR src.source_received_at IS NULL OR src.source_received_at IS DISTINCT FROM m.message_received_at THEN RAISE EXCEPTION 'customer_source_immutable_original_required';END IF;
 SELECT count(*) INTO n FROM gridex_received_sources.validation_assessments a WHERE a.source_message_id=m.id AND a.company_id=p_company_id AND a.environment=m.environment AND a.source_payload_hash=src.payload_hash AND NOT EXISTS(SELECT FROM gridex_received_sources.validation_assessments child WHERE child.previous_assessment_id=a.id);
 IF n<>1 THEN RETURN jsonb_build_object('applied',false,'reason','customer_source_canonical_ambiguous');END IF;
 SELECT * INTO canonical FROM gridex_received_sources.validation_assessments a WHERE a.source_message_id=m.id AND a.company_id=p_company_id AND a.environment=m.environment AND a.source_payload_hash=src.payload_hash AND NOT EXISTS(SELECT FROM gridex_received_sources.validation_assessments child WHERE child.previous_assessment_id=a.id) FOR SHARE;
 IF canonical.facts_text::jsonb->>'syntaxDecision' IS DISTINCT FROM 'accepted' OR canonical.facts_text::jsonb->>'applicationDecision' IS DISTINCT FROM 'accepted' OR canonical.facts_text::jsonb->>'functionalDecision' IS DISTINCT FROM 'accepted' THEN RETURN jsonb_build_object('applied',false,'reason','customer_source_canonical_not_accepted');END IF;
 tokens:=gridex_received_sources.closure_wire_tokens_v2(src.raw_payload);
 IF tokens IS NULL OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='BGM' AND t#>>'{elements,1,0}'='Z06' AND coalesce(t#>>'{elements,3,0}','9')='9')<>1 OR (SELECT count(DISTINCT jsonb_build_array(t#>>'{elements,3,0}',t#>>'{elements,3,3}')) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN')<>1 THEN RAISE EXCEPTION 'customer_source_whole_original_required';END IF;
 SELECT t INTO lin FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN' ORDER BY (t->>'index')::integer LIMIT 1;first_lin:=(lin->>'index')::integer;
 SELECT min((t->>'index')::integer) INTO end_lin FROM jsonb_array_elements(tokens) t WHERE (t->>'index')::integer>first_lin AND t->>'tag' IN('UNT','UNZ','UNH','LIN');
 SELECT jsonb_agg(t ORDER BY (t->>'index')::integer) INTO own_tokens FROM jsonb_array_elements(tokens) t WHERE (t->>'index')::integer>first_lin AND (end_lin IS NULL OR (t->>'index')::integer<end_lin);
 -- Exact CCI parent and first own CAV; an unrelated code anywhere in a raw
 -- message cannot create death authority. Other E34 processes retain a hold.
 IF (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='E34' AND (SELECT p#>>'{elements,2,0}' FROM jsonb_array_elements(own_tokens) p WHERE p->>'tag'='CCI' AND (p->>'index')::integer<(t->>'index')::integer ORDER BY (p->>'index')::integer DESC LIMIT 1)='Z13')<>1 THEN RAISE EXCEPTION 'customer_source_z06e_required';END IF;
 IF (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='Z41' AND (SELECT p#>>'{elements,2,0}' FROM jsonb_array_elements(own_tokens) p WHERE p->>'tag'='CCI' AND (p->>'index')::integer<(t->>'index')::integer ORDER BY (p->>'index')::integer DESC LIMIT 1)='Z17')<>1 THEN RETURN jsonb_build_object('applied',false,'reason','customer_source_separate_bilateral_non_death_ground_required');END IF;
 IF (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD')<>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='157' AND t#>>'{elements,1,2}'='203')<>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='RFF' AND t#>>'{elements,1,0}'='LI' AND nullif(t#>>'{elements,1,1}','') IS NOT NULL)<>1 THEN RAISE EXCEPTION 'customer_source_own_customer_clock_reference_required';END IF;
 SELECT t INTO ud FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD';
 SELECT t INTO dtm FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='157';
 physical_at:=gridex_received_sources.permission_time_v1(dtm#>>'{elements,1,1}');
 IF physical_at IS NULL OR nullif(gridex_ai_processing.party_text_v1(ud,4,2),'') IS NULL THEN RAISE EXCEPTION 'customer_source_party_or_clock_invalid';END IF;
 FOR candidate IN SELECT * FROM gridex_requested_changes.events x WHERE x.company_id=p_company_id AND x.environment=m.environment AND x.variant='E' AND x.event_kind='death' AND x.point_id=lin#>>'{elements,3,0}' AND x.identity_agency=lin#>>'{elements,3,3}' AND x.effective_at=physical_at AND x.customer_identity->>'id'=ud#>>'{elements,2,0}' ORDER BY x.id FOR SHARE LOOP
  b:=gridex_requested_changes.context_v1(p_company_id,candidate.id,p_actor_user_id,'communication.write');
  IF b->>'status'='authorized' AND ud#>'{elements,2}'=jsonb_build_array(candidate.customer_identity->>'id',candidate.customer_identity->>'qualifier',candidate.customer_identity->>'agency')
   AND m.sender_ediel_id=candidate.legal_receiver_id AND m.receiver_ediel_id=candidate.legal_sender_id
   AND (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND (t->>'index')::integer<first_lin AND t#>>'{elements,1,0}'='FR' AND t#>'{elements,2}'=jsonb_build_array(candidate.legal_receiver_id,'160','SVK'))=1
   AND (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND (t->>'index')::integer<first_lin AND t#>>'{elements,1,0}'='DO' AND t#>'{elements,2}'=jsonb_build_array(candidate.legal_sender_id,'160','SVK'))=1 THEN qualified_count:=qualified_count+1;e:=candidate;END IF;
 END LOOP;
 IF qualified_count<>1 THEN RETURN jsonb_build_object('applied',false,'reason',CASE WHEN qualified_count>1 THEN 'customer_source_life_event_ambiguous' ELSE 'customer_source_qualified_life_event_missing' END);END IF;
 SELECT * INTO point FROM public.metering_points WHERE id=e.metering_point_id AND company_id=p_company_id AND customer_id=e.customer_id FOR SHARE;
 IF point.id IS NULL OR coalesce(point.customer_site_id,point.site_id) IS NULL THEN RAISE EXCEPTION 'customer_source_owned_site_required';END IF;
 PERFORM s.id FROM public.customer_sites s WHERE s.id=coalesce(point.customer_site_id,point.site_id) AND s.company_id=p_company_id AND s.customer_id=e.customer_id FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'customer_source_owned_site_required';END IF;
 party:=jsonb_build_object('id',ud#>>'{elements,2,0}','qualifier',ud#>>'{elements,2,1}','agency',ud#>>'{elements,2,2}','name',gridex_ai_processing.party_text_v1(ud,4,2),'nameLines',ud#>'{elements,4}','addressLines',ud#>'{elements,5}','city',ud#>>'{elements,6,0}','postalCode',ud#>>'{elements,8,0}','country',ud#>>'{elements,9,0}','deathStatus','Z41');
 SELECT * INTO prior FROM gridex_requested_changes.confirmed_customer_versions WHERE source_message_id=m.id FOR SHARE;
 IF FOUND THEN IF prior.payload_hash IS DISTINCT FROM src.payload_hash OR prior.event_id IS DISTINCT FROM e.id OR prior.canonical_assessment_id IS DISTINCT FROM canonical.id OR prior.party IS DISTINCT FROM party THEN RAISE EXCEPTION 'customer_source_replay_conflict';END IF;RETURN prior.result;END IF;
 result:=jsonb_build_object('applied',true,'sourceMessageId',m.id,'appliedCount',1,'owner','confirmed-customer-source-v1','payloadHash',src.payload_hash,'eventId',e.id,'objects',jsonb_build_array(jsonb_build_object('meteringPointId',point.id,'siteId',coalesce(point.customer_site_id,point.site_id),'effectiveAt',physical_at,'sourceReceivedAt',src.source_received_at)));
 INSERT INTO gridex_requested_changes.confirmed_customer_versions(source_message_id,event_id,company_id,environment,payload_hash,customer_id,metering_point_id,effective_at,received_at,party,actor_user_id,canonical_assessment_id,supply_period_id,site_id,object_id,identity_agency,legal_sender,legal_receiver,result)
 VALUES(m.id,e.id,p_company_id,m.environment,src.payload_hash,e.customer_id,e.metering_point_id,physical_at,src.source_received_at,party,p_actor_user_id,canonical.id,e.supply_period_id,coalesce(point.customer_site_id,point.site_id),e.point_id,e.identity_agency,e.legal_receiver_id,e.legal_sender_id,result);
 INSERT INTO public.ediel_message_events(company_id,ediel_message_id,message_id,event_type,event_status,message,payload,event_payload,created_by)
 VALUES(p_company_id,m.id,m.id,'manual_note','success','Källbunden kundversion granskad.',jsonb_build_object('safeApply',true,'safeApplyDecision','applied','appliedCount',1,'customerVersionSourceId',m.id,'appliedAutomatically',false),jsonb_build_object('safeApply',true,'safeApplyDecision','applied','appliedCount',1,'customerVersionSourceId',m.id,'appliedAutomatically',false),p_actor_user_id);
 RETURN result;
END$$;
CREATE OR REPLACE FUNCTION gridex_bilateral_customer_sources.source_claims_v1(c uuid,source_id uuid,agreement uuid,supply_id uuid,contract_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE m public.ediel_messages%rowtype;s gridex_received_sources.sources%rowtype;a gridex_received_sources.validation_assessments%rowtype;ba public.tenant_bilateral_agreements%rowtype;sp public.customer_supply_periods%rowtype;cc public.customer_contracts%rowtype;mp public.metering_points%rowtype;
 tokens jsonb;own_tokens jsonb;lin jsonb;ud jsonb;iv jsonb;dtm jsonb;supply jsonb;at timestamptz;first_lin int;last_lin int;n int;sender text;legal_actor uuid;counterparty uuid;customer_tokens jsonb;party jsonb;
BEGIN
 SELECT * INTO m FROM public.ediel_messages WHERE id=source_id AND company_id=c FOR SHARE;
 IF NOT FOUND OR m.direction IS DISTINCT FROM 'inbound' OR m.message_standard IS DISTINCT FROM 'edifact' OR m.message_family IS DISTINCT FROM 'PRODAT' OR m.message_code IS DISTINCT FROM 'Z06' THEN RAISE EXCEPTION 'bilateral_customer_source_original_required';END IF;
 PERFORM gridex_ediel_inbound_context.require_v1(c,m.id);PERFORM gridex_ediel_source_rules.require_v1(c,m.id);
 SELECT * INTO s FROM gridex_received_sources.sources WHERE source_message_id=m.id AND company_id=c AND environment=m.environment FOR SHARE;
 IF NOT FOUND OR s.raw_payload IS DISTINCT FROM m.raw_payload OR s.payload_hash IS DISTINCT FROM encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex') OR s.source_received_at IS NULL OR s.source_received_at IS DISTINCT FROM m.message_received_at THEN RAISE EXCEPTION 'bilateral_customer_source_immutable_received_original_required';END IF;
 SELECT count(*) INTO n FROM gridex_received_sources.validation_assessments x WHERE x.source_message_id=m.id AND x.company_id=c AND x.environment=m.environment AND x.source_payload_hash=s.payload_hash AND NOT EXISTS(SELECT FROM gridex_received_sources.validation_assessments child WHERE child.previous_assessment_id=x.id);
 IF n<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_unique_canonical_required';END IF;
 SELECT * INTO a FROM gridex_received_sources.validation_assessments x WHERE x.source_message_id=m.id AND x.company_id=c AND x.environment=m.environment AND x.source_payload_hash=s.payload_hash AND NOT EXISTS(SELECT FROM gridex_received_sources.validation_assessments child WHERE child.previous_assessment_id=x.id) FOR SHARE;
 IF a.facts_text::jsonb->>'syntaxDecision' IS DISTINCT FROM 'accepted' OR a.facts_text::jsonb->>'applicationDecision' IS DISTINCT FROM 'accepted' OR a.facts_text::jsonb->>'functionalDecision' IS DISTINCT FROM 'accepted' THEN RAISE EXCEPTION 'bilateral_customer_source_canonical_accepted_required';END IF;
 tokens:=gridex_received_sources.closure_wire_tokens_v2(s.raw_payload);
 IF (SELECT count(DISTINCT jsonb_build_array(t#>>'{elements,3,0}',t#>>'{elements,3,3}')) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN')<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='BGM' AND t#>>'{elements,1,0}'='Z06' AND coalesce(t#>>'{elements,3,0}','9')='9')<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_whole_original_required';END IF;
 SELECT t INTO lin FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN' ORDER BY (t->>'index')::integer LIMIT 1;first_lin:=(lin->>'index')::int;
 SELECT min((t->>'index')::int) INTO last_lin FROM jsonb_array_elements(tokens) t WHERE (t->>'index')::int>first_lin AND t->>'tag' IN('UNT','UNZ','UNH','LIN');
 SELECT jsonb_agg(t ORDER BY (t->>'index')::int) INTO own_tokens FROM jsonb_array_elements(tokens) t WHERE (t->>'index')::int>first_lin AND (last_lin IS NULL OR (t->>'index')::int<last_lin);
 IF (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='E34' AND (SELECT p#>>'{elements,2,0}' FROM jsonb_array_elements(own_tokens) p WHERE p->>'tag'='CCI' AND (p->>'index')::int<(t->>'index')::int ORDER BY (p->>'index')::int DESC LIMIT 1)='Z13')<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_z06e_required';END IF;
 IF EXISTS(SELECT FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='Z41') THEN RAISE EXCEPTION 'bilateral_customer_source_cannot_mint_death_fact';END IF;
 IF (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD')<>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV')>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='157' AND t#>>'{elements,1,2}'='203')<>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='RFF' AND t#>>'{elements,1,0}'='LI' AND nullif(t#>>'{elements,1,1}','') IS NOT NULL)<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_own_parties_clock_reference_required';END IF;
 SELECT t INTO ud FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD';SELECT t INTO iv FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV';SELECT t INTO dtm FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='157';at:=gridex_received_sources.permission_time_v1(dtm#>>'{elements,1,1}');
 IF at IS NULL OR nullif(ud#>>'{elements,2,0}','') IS NULL OR nullif(gridex_ai_processing.party_text_v1(ud,4,2),'') IS NULL THEN RAISE EXCEPTION 'bilateral_customer_source_actual_party_minute_required';END IF;
 SELECT * INTO sp FROM public.customer_supply_periods WHERE id=supply_id AND company_id=c FOR SHARE;SELECT * INTO cc FROM public.customer_contracts WHERE id=contract_id AND company_id=c FOR SHARE;SELECT * INTO mp FROM public.metering_points WHERE id=sp.metering_point_id AND company_id=c FOR SHARE;
 supply:=gridex_received_sources.supply_period_source_basis_v1(c,sp.id,at,at+interval '1 minute');legal_actor:=(supply->>'legalActorId')::uuid;
 IF sp.id IS NULL OR cc.id IS NULL OR mp.id IS NULL OR cc.customer_id IS DISTINCT FROM sp.customer_id OR cc.metering_point_id IS DISTINCT FROM mp.id OR mp.customer_id IS DISTINCT FROM sp.customer_id OR (cc.status IN('signed','active')) IS NOT TRUE OR cc.signed_at IS NULL OR nullif(cc.signed_version,'') IS NULL OR supply->>'qualified' IS DISTINCT FROM 'true' OR supply->>'customerId' IS DISTINCT FROM sp.customer_id::text OR supply->>'meteringPointId' IS DISTINCT FROM mp.id::text OR mp.ediel_metering_point_id IS DISTINCT FROM lin#>>'{elements,3,0}' OR (lin#>>'{elements,3,3}' IN('9','89')) IS NOT TRUE OR supply->>'dsoEdielId' IS DISTINCT FROM m.sender_ediel_id OR mp.grid_owner_ediel_id IS DISTINCT FROM m.sender_ediel_id OR mp.product_direction IS DISTINCT FROM 'consumption' THEN RAISE EXCEPTION 'bilateral_customer_source_current_owned_supply_contract_point_required';END IF;
 PERFORM cs.id FROM public.customer_sites cs WHERE cs.id=coalesce(mp.customer_site_id,mp.site_id) AND cs.company_id=c AND cs.customer_id=sp.customer_id FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'bilateral_customer_source_current_owned_site_required';END IF;
 PERFORM t.id FROM public.tenant_actor_identifiers t WHERE t.company_id=c AND t.environment=m.environment ORDER BY t.id FOR SHARE;PERFORM t.id FROM public.tenant_actor_roles t WHERE t.company_id=c AND t.environment=m.environment ORDER BY t.id FOR SHARE;PERFORM t.id FROM public.tenant_ediel_profiles t WHERE t.company_id=c AND t.environment=m.environment ORDER BY t.id FOR SHARE;
 SELECT min(identifier_value) INTO sender FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=m.environment AND actor_id=legal_actor AND identifier_type='EdielId' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now());
 IF sender IS DISTINCT FROM m.receiver_ediel_id OR (SELECT count(DISTINCT(actor_id,identifier_value)) FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=m.environment AND identifier_type='EdielId' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now()))<>1 OR NOT EXISTS(SELECT FROM public.tenant_actor_roles WHERE company_id=c AND environment=m.environment AND actor_id=legal_actor AND role_code='electricity_supplier' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now())) OR NOT EXISTS(SELECT FROM public.tenant_ediel_profiles WHERE company_id=c AND environment=m.environment AND market='electricity' AND is_enabled AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now())) OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND (t->>'index')::int<first_lin AND t#>>'{elements,1,0}'='FR' AND t#>'{elements,2}'=jsonb_build_array(m.sender_ediel_id,'160','SVK'))<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND (t->>'index')::int<first_lin AND t#>>'{elements,1,0}'='DO' AND t#>'{elements,2}'=jsonb_build_array(sender,'160','SVK'))<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_exact_current_legal_supplier_required';END IF;
 SELECT * INTO ba FROM public.tenant_bilateral_agreements WHERE id=agreement AND company_id=c AND environment=m.environment FOR SHARE;
 PERFORM i.id FROM public.platform_actor_identifiers i WHERE i.actor_id=ba.counterparty_actor_id ORDER BY i.id FOR SHARE;PERFORM r.id FROM public.platform_actor_roles r WHERE r.actor_id=ba.counterparty_actor_id ORDER BY r.id FOR SHARE;
 IF ba.id IS NULL OR ba.capability_code IS DISTINCT FROM 'prodat_z06e_customer_change' OR ba.is_enabled IS NOT TRUE OR ba.valid_from>now() OR ba.valid_to<=now() OR nullif(ba.source_reference,'') IS NULL OR (SELECT count(DISTINCT i.identifier_value) FROM public.platform_actor_identifiers i WHERE i.actor_id=ba.counterparty_actor_id AND lower(i.identifier_type) IN('edielid','ediel_id') AND i.is_verified AND (i.valid_from IS NULL OR i.valid_from<=current_date) AND (i.valid_to IS NULL OR i.valid_to>=current_date))<>1 OR NOT EXISTS(SELECT FROM public.platform_actor_identifiers i WHERE i.actor_id=ba.counterparty_actor_id AND lower(i.identifier_type) IN('edielid','ediel_id') AND i.is_verified AND i.identifier_value=m.sender_ediel_id AND (i.valid_from IS NULL OR i.valid_from<=current_date) AND (i.valid_to IS NULL OR i.valid_to>=current_date)) OR NOT EXISTS(SELECT FROM public.platform_actor_roles r WHERE r.actor_id=ba.counterparty_actor_id AND r.actor_role='grid_owner' AND r.is_active) THEN RAISE EXCEPTION 'bilateral_customer_source_current_exact_dso_agreement_required';END IF;
 SELECT jsonb_agg(jsonb_build_object('tag',t->>'tag','elements',t->'elements') ORDER BY (t->>'index')::int) INTO customer_tokens FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag' IN('NAD','DTM') AND (t->>'tag'='NAD' AND t#>>'{elements,1,0}' IN('UD','IV') OR t->>'tag'='DTM' AND t#>>'{elements,1,0}'='329');
 party:=jsonb_build_object('id',ud#>>'{elements,2,0}','qualifier',ud#>>'{elements,2,1}','agency',ud#>>'{elements,2,2}','name',gridex_ai_processing.party_text_v1(ud,4,2),'nameLines',ud#>'{elements,4}','addressLines',ud#>'{elements,5}','city',ud#>>'{elements,6,0}','postalCode',ud#>>'{elements,8,0}','country',ud#>>'{elements,9,0}','invoicee',CASE WHEN iv IS NULL THEN NULL ELSE iv->'elements' END,'birthDate',(SELECT t#>>'{elements,1,1}' FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='329' LIMIT 1));
 RETURN jsonb_build_object('sourceMessageId',m.id,'payloadHash',s.payload_hash,'canonicalAssessmentId',a.id,'companyId',c,'environment',m.environment,'agreementId',ba.id,'agreementHash',encode(sha256(convert_to((to_jsonb(ba)-ARRAY['updated_at','created_at'])::text,'UTF8')),'hex'),'counterpartyActorId',ba.counterparty_actor_id,'supplyPeriodId',sp.id,'supplySourceMessageId',supply->>'sourceMessageId','supplyStateVersion',supply->'marketStateVersion','contractId',cc.id,'contractHash',gridex_received_sources.production_contract_hash_v1(cc),'customerId',sp.customer_id,'meteringPointId',mp.id,'siteId',coalesce(mp.customer_site_id,mp.site_id),'objectId',lin#>>'{elements,3,0}','identityAgency',lin#>>'{elements,3,3}','legalActorId',legal_actor,'legalSender',m.sender_ediel_id,'legalReceiver',m.receiver_ediel_id,'effectiveAt',at,'sourceReceivedAt',s.source_received_at,'party',party,'customerTokens',customer_tokens);
END$$;
REVOKE ALL ON FUNCTION public.ediel_apply_customer_before_bilateral_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION gridex_bilateral_customer_sources.source_claims_v1(uuid,uuid,uuid,uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
COMMIT;
