-- Five separate original-byte purposes. No actor grant, issuer registration,
-- approval, legal period or cascade is created by this migration.
BEGIN;
DO $$BEGIN PERFORM 'gridex_brp_sources.contract_declarations'::regclass;PERFORM 'gridex_customer_life_events.certification_classifications'::regclass;PERFORM 'gridex_customer_life_events.certification_classification_revocations'::regclass;END$$;
GRANT USAGE ON SCHEMA gridex_brp_sources TO gridex_ediel_retention_owner;
GRANT SELECT,UPDATE ON gridex_brp_sources.contract_declarations,gridex_brp_sources.contract_revocations,gridex_customer_life_events.certification_classifications,gridex_customer_life_events.certification_classification_revocations,public.customer_contracts TO gridex_ediel_retention_owner;
ALTER TABLE gridex_brp_sources.contract_declarations ALTER COLUMN agreement_original DROP NOT NULL,ALTER COLUMN source_original DROP NOT NULL;
ALTER TABLE gridex_customer_life_events.certification_classifications ALTER COLUMN workbook_original DROP NOT NULL,ALTER COLUMN classification_original DROP NOT NULL;
ALTER TABLE gridex_customer_life_events.certification_classification_revocations ALTER COLUMN source_original DROP NOT NULL;
CREATE TABLE gridex_ediel_retention.protected_copy_specs(retention_class text PRIMARY KEY REFERENCES gridex_ediel_retention.decision_evidence_catalog(retention_class),view_name text UNIQUE NOT NULL,source_schema text NOT NULL,source_table text NOT NULL,body_field text NOT NULL,hash_field text NOT NULL);
CREATE TABLE gridex_ediel_retention.protected_copy_revocations(retention_class text NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_catalog(retention_class),target_id uuid NOT NULL,company_id uuid NOT NULL,policy_id uuid NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_policies(id),review_id uuid NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_reviews(id),source_hash text NOT NULL,actor_user_id uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(retention_class,target_id));
CREATE VIEW gridex_ediel_retention.brp_declaration_agreement_originals WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.agreement_original document_bytes,q.agreement_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_brp_sources.contract_declarations q;
ALTER VIEW gridex_ediel_retention.brp_declaration_agreement_originals OWNER TO gridex_ediel_retention_owner;
REVOKE ALL ON gridex_ediel_retention.brp_declaration_agreement_originals FROM PUBLIC,anon,authenticated,service_role;
INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('brp_declaration_agreement_original_bytes','brp_declaration_agreement_originals','ediel.retention.record_decision_evidence','protected_copy_revocations','target_id','protected_copy_current_v1');
INSERT INTO gridex_ediel_retention.protected_copy_specs VALUES('brp_declaration_agreement_original_bytes','brp_declaration_agreement_originals','gridex_brp_sources','contract_declarations','agreement_original','agreement_sha256');
CREATE VIEW gridex_ediel_retention.brp_declaration_source_originals WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.source_original document_bytes,q.source_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_brp_sources.contract_declarations q;
ALTER VIEW gridex_ediel_retention.brp_declaration_source_originals OWNER TO gridex_ediel_retention_owner;
REVOKE ALL ON gridex_ediel_retention.brp_declaration_source_originals FROM PUBLIC,anon,authenticated,service_role;
INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('brp_declaration_source_original_bytes','brp_declaration_source_originals','ediel.retention.record_decision_evidence','protected_copy_revocations','target_id','protected_copy_current_v1');
INSERT INTO gridex_ediel_retention.protected_copy_specs VALUES('brp_declaration_source_original_bytes','brp_declaration_source_originals','gridex_brp_sources','contract_declarations','source_original','source_sha256');
CREATE VIEW gridex_ediel_retention.certification_workbook_originals WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.workbook_original document_bytes,q.workbook_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['workbook_original','classification_original'] source_metadata FROM gridex_customer_life_events.certification_classifications q;
ALTER VIEW gridex_ediel_retention.certification_workbook_originals OWNER TO gridex_ediel_retention_owner;
REVOKE ALL ON gridex_ediel_retention.certification_workbook_originals FROM PUBLIC,anon,authenticated,service_role;
INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('certification_workbook_original_bytes','certification_workbook_originals','ediel.retention.record_decision_evidence','protected_copy_revocations','target_id','protected_copy_current_v1');
INSERT INTO gridex_ediel_retention.protected_copy_specs VALUES('certification_workbook_original_bytes','certification_workbook_originals','gridex_customer_life_events','certification_classifications','workbook_original','workbook_sha256');
CREATE VIEW gridex_ediel_retention.certification_classification_originals WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.classification_original document_bytes,q.classification_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['workbook_original','classification_original'] source_metadata FROM gridex_customer_life_events.certification_classifications q;
ALTER VIEW gridex_ediel_retention.certification_classification_originals OWNER TO gridex_ediel_retention_owner;
REVOKE ALL ON gridex_ediel_retention.certification_classification_originals FROM PUBLIC,anon,authenticated,service_role;
INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('certification_classification_original_bytes','certification_classification_originals','ediel.retention.record_decision_evidence','protected_copy_revocations','target_id','protected_copy_current_v1');
INSERT INTO gridex_ediel_retention.protected_copy_specs VALUES('certification_classification_original_bytes','certification_classification_originals','gridex_customer_life_events','certification_classifications','classification_original','classification_sha256');
CREATE VIEW gridex_ediel_retention.certification_revocation_originals WITH(security_barrier=true) AS SELECT q.id,q.company_id,r.source_original document_bytes,r.source_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,jsonb_build_object('classification',to_jsonb(q)-ARRAY['workbook_original','classification_original'],'revocation',to_jsonb(r)-'source_original') source_metadata FROM gridex_customer_life_events.certification_classification_revocations r JOIN gridex_customer_life_events.certification_classifications q ON q.id=r.declaration_id;
ALTER VIEW gridex_ediel_retention.certification_revocation_originals OWNER TO gridex_ediel_retention_owner;
REVOKE ALL ON gridex_ediel_retention.certification_revocation_originals FROM PUBLIC,anon,authenticated,service_role;
INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('certification_revocation_original_bytes','certification_revocation_originals','ediel.retention.record_decision_evidence','protected_copy_revocations','target_id','protected_copy_current_v1');
INSERT INTO gridex_ediel_retention.protected_copy_specs VALUES('certification_revocation_original_bytes','certification_revocation_originals','gridex_customer_life_events','certification_classification_revocations','source_original','source_sha256');
DO $$DECLARE tab text;BEGIN FOREACH tab IN ARRAY ARRAY['protected_copy_specs','protected_copy_revocations'] LOOP EXECUTE format('ALTER TABLE gridex_ediel_retention.%I OWNER TO gridex_ediel_retention_owner',tab);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ENABLE ROW LEVEL SECURITY',tab);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I FORCE ROW LEVEL SECURITY',tab);EXECUTE format('REVOKE ALL ON gridex_ediel_retention.%I FROM PUBLIC,anon,authenticated,service_role',tab);EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',tab);EXECUTE format('CREATE TRIGGER no_truncate BEFORE TRUNCATE ON gridex_ediel_retention.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',tab);END LOOP;END$$;
CREATE FUNCTION gridex_ediel_retention.protected_copy_row_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec gridex_ediel_retention.protected_copy_specs%rowtype;ct uuid;r jsonb;b bytea;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();SELECT * INTO STRICT spec FROM gridex_ediel_retention.protected_copy_specs WHERE retention_class=k;
 IF spec.source_schema='gridex_brp_sources' THEN
  SELECT contract_id INTO ct FROM gridex_brp_sources.contract_declarations WHERE id=target AND company_id=c;
  PERFORM id FROM public.customer_contracts WHERE id=ct AND company_id=c FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'decision_evidence_original_scope_required';END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('contract-brp:'||c::text||':'||ct::text,0));PERFORM id FROM gridex_brp_sources.contract_declarations WHERE id=target AND company_id=c FOR UPDATE;
 ELSE
  PERFORM id FROM gridex_customer_life_events.certification_classifications WHERE id=target AND company_id=c FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'decision_evidence_original_scope_required';END IF;
  IF spec.source_table='certification_classification_revocations' THEN PERFORM declaration_id FROM gridex_customer_life_events.certification_classification_revocations WHERE declaration_id=target FOR UPDATE;END IF;
 END IF;
 EXECUTE format('SELECT to_jsonb(v),v.document_bytes FROM gridex_ediel_retention.%I v WHERE id=$1 AND company_id=$2',spec.view_name) INTO r,b USING target,c;
 IF r IS NULL THEN RAISE EXCEPTION 'decision_evidence_original_scope_required';END IF;
 SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=k AND target_id=target AND company_id=c;
 IF b IS NOT NULL AND encode(sha256(b),'hex') IS DISTINCT FROM r->>'document_hash' OR b IS NULL AND(t.target_id IS NULL OR t.source_hash IS DISTINCT FROM r->>'document_hash') THEN RAISE EXCEPTION 'decision_evidence_original_custody_mismatch';END IF;
 RETURN r||jsonb_build_object('document_byte_length',CASE WHEN b IS NULL THEN t.byte_length ELSE NULL END,'document_purged_at',t.created_at);
END$$;
CREATE FUNCTION gridex_ediel_retention.protected_copy_basis_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;b bytea;BEGIN r:=gridex_ediel_retention.protected_copy_row_v1(c,k,target);b:=decode(substr(r->>'document_bytes',3),'hex');IF b IS NULL OR octet_length(b) NOT BETWEEN 1 AND 10485760 THEN RAISE EXCEPTION 'decision_evidence_actual_original_bytes_required';END IF;RETURN jsonb_build_object('retentionClass',k,'targetId',target,'sourceHash',r->>'document_hash','targetMetadataHash',encode(sha256(convert_to((r-ARRAY['document_bytes','document_byte_length','document_purged_at'])::text,'UTF8')),'hex'),'byteLength',octet_length(b));END$$;
CREATE FUNCTION gridex_ediel_retention.protected_copy_transition_v1(k text,o jsonb,n jsonb) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec gridex_ediel_retention.protected_copy_specs%rowtype;target uuid:=coalesce(o->>'id',o->>'declaration_id')::uuid;c uuid;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;d gridex_ediel_retention.decision_evidence_policies%rowtype;r gridex_ediel_retention.decision_evidence_reviews%rowtype;basis jsonb;p jsonb;h text;b bytea;permission text;at timestamptz;BEGIN
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.protected_copy_specs WHERE retention_class=k;
 IF o->>spec.body_field IS NULL OR n->>spec.body_field IS NOT NULL OR(o-spec.body_field) IS DISTINCT FROM(n-spec.body_field) THEN RETURN false;END IF;
 IF spec.source_table='certification_classification_revocations' THEN SELECT company_id INTO c FROM gridex_customer_life_events.certification_classifications WHERE id=target;ELSE c:=(o->>'company_id')::uuid;END IF;
 basis:=gridex_ediel_retention.protected_copy_basis_v1(c,k,target);b:=decode(substr(o->>spec.body_field,3),'hex');h:=encode(sha256(b),'hex');
 SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=k AND target_id=target AND company_id=c;
 IF t.target_id IS NULL OR t.source_hash IS DISTINCT FROM h OR t.byte_length IS DISTINCT FROM octet_length(b) OR t.target_metadata_hash IS DISTINCT FROM basis->>'targetMetadataHash' OR NOT EXISTS(SELECT FROM gridex_ediel_retention.protected_copy_revocations WHERE retention_class=k AND target_id=target AND company_id=c AND policy_id=t.policy_id AND review_id=t.review_id AND source_hash=h AND actor_user_id=t.actor_user_id) THEN RETURN false;END IF;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.decision_evidence_policies WHERE id=t.policy_id FOR UPDATE;SELECT * INTO r FROM gridex_ediel_retention.decision_evidence_reviews WHERE policy_id=d.id ORDER BY created_at DESC,id DESC LIMIT 1 FOR SHARE;
 IF r.id IS DISTINCT FROM t.review_id OR r.outcome IS DISTINCT FROM 'approved' OR r.actor_user_id=d.submitted_by OR d.company_id IS DISTINCT FROM c OR d.retention_class IS DISTINCT FROM k OR d.target_id IS DISTINCT FROM target OR d.source_hash IS DISTINCT FROM h OR d.target_metadata_hash IS DISTINCT FROM t.target_metadata_hash THEN RETURN false;END IF;
 p:=gridex_ediel_retention.decision_evidence_receipt_v1(d);IF p IS NULL THEN RETURN false;END IF;PERFORM gridex_ediel_retention.decision_evidence_actor_v1(c,t.actor_user_id,k,'ediel.retention.purge');PERFORM gridex_ediel_retention.decision_evidence_lock_reviewer_v1(c,r.actor_user_id,k);p:=gridex_ediel_retention.decision_evidence_receipt_v1(d);IF p IS NULL THEN RETURN false;END IF;
 SELECT permission_key INTO STRICT permission FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=k;
 IF gridex_ediel_retention.permission_v1(c,t.actor_user_id,'ediel.retention.purge') IS NOT TRUE OR gridex_ediel_retention.permission_v1(c,t.actor_user_id,permission) IS NOT TRUE OR gridex_ediel_retention.permission_v1(c,r.actor_user_id,'ediel.retention.review') IS NOT TRUE OR gridex_ediel_retention.permission_v1(c,r.actor_user_id,permission) IS NOT TRUE THEN RETURN false;END IF;
 at:=clock_timestamp();RETURN(p->>'retainUntil')::timestamptz<=at AND(p->>'issuedAt')::timestamptz<=at AND(p->>'expiresAt')::timestamptz>at AND(p->>'journalRetainUntil')::timestamptz>at;
END$$;
CREATE FUNCTION gridex_ediel_retention.protected_copy_view_update_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec gridex_ediel_retention.protected_copy_specs%rowtype;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;key text;BEGIN
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.protected_copy_specs WHERE view_name=TG_TABLE_NAME;SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=spec.retention_class AND target_id=OLD.id AND company_id=OLD.company_id;
 IF t.target_id IS NULL OR OLD.document_bytes IS NULL OR NEW.document_bytes IS NOT NULL OR(to_jsonb(OLD)-ARRAY['document_bytes','document_byte_length','document_purged_at']) IS DISTINCT FROM(to_jsonb(NEW)-ARRAY['document_bytes','document_byte_length','document_purged_at']) OR NEW.document_byte_length IS DISTINCT FROM t.byte_length OR NEW.document_purged_at IS DISTINCT FROM t.created_at THEN RAISE EXCEPTION 'protected_copy_physical_transition_required';END IF;
 key:=CASE spec.source_table WHEN 'certification_classification_revocations' THEN 'declaration_id' ELSE 'id' END;EXECUTE format('UPDATE %I.%I SET %I=NULL WHERE %I=$1',spec.source_schema,spec.source_table,spec.body_field,key) USING OLD.id;RETURN NEW;
END$$;
CREATE FUNCTION gridex_ediel_retention.protected_copy_insert_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec record;row jsonb:=to_jsonb(NEW);c uuid;ct uuid;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 IF TG_TABLE_SCHEMA='gridex_brp_sources' THEN
  IF TG_TABLE_NAME='contract_declarations' THEN c:=NEW.company_id;ct:=NEW.contract_id;ELSE SELECT company_id,contract_id INTO c,ct FROM gridex_brp_sources.contract_declarations WHERE id=NEW.declaration_id;END IF;
  PERFORM id FROM public.customer_contracts WHERE id=ct AND company_id=c FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'protected_copy_actual_contract_scope_required';END IF;
 END IF;
 FOR spec IN SELECT * FROM gridex_ediel_retention.protected_copy_specs WHERE source_schema=TG_TABLE_SCHEMA AND source_table=TG_TABLE_NAME LOOP
  IF row->>spec.body_field IS NULL OR encode(sha256(decode(substr(row->>spec.body_field,3),'hex')),'hex') IS DISTINCT FROM row->>spec.hash_field THEN RAISE EXCEPTION 'protected_copy_new_actual_bytes_required';END IF;
 END LOOP;RETURN NEW;
END$$;
DO $$DECLARE tab record;f record;body text;definition text;name text;spec record;prefix text;BEGIN
 FOR tab IN SELECT DISTINCT source_schema,source_table FROM gridex_ediel_retention.protected_copy_specs LOOP
  SELECT t.oid,t.tgname,t.tgenabled,p.prosrc INTO STRICT f FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid WHERE t.tgrelid=format('%I.%I',tab.source_schema,tab.source_table)::regclass AND t.tgname IN('brp_source_no_mutation','certification_classification_immutable') AND NOT t.tgisinternal;
  IF f.prosrc!~*'RAISE\s+EXCEPTION' OR f.tgenabled NOT IN('O','A') THEN RAISE EXCEPTION 'protected_copy_original_guard_review_required';END IF;
  prefix:='BEGIN IF TG_OP=''UPDATE'' AND (';FOR spec IN SELECT retention_class FROM gridex_ediel_retention.protected_copy_specs WHERE source_schema=tab.source_schema AND source_table=tab.source_table ORDER BY retention_class LOOP prefix:=prefix||format('gridex_ediel_retention.protected_copy_transition_v1(%L,to_jsonb(OLD),to_jsonb(NEW)) IS TRUE OR ',spec.retention_class);END LOOP;prefix:=left(prefix,length(prefix)-4)||') THEN RETURN NEW;END IF;';body:=regexp_replace(f.prosrc,'\mBEGIN\M',prefix,'i');name:=tab.source_table||'_retention_original_guard_v1';
  EXECUTE format('CREATE FUNCTION gridex_ediel_retention.%I() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS %L',name,body);EXECUTE format('ALTER FUNCTION gridex_ediel_retention.%I() OWNER TO gridex_ediel_retention_owner',name);EXECUTE format('REVOKE ALL ON FUNCTION gridex_ediel_retention.%I() FROM PUBLIC,anon,authenticated,service_role',name);
  definition:=pg_get_triggerdef(f.oid);EXECUTE format('DROP TRIGGER %I ON %I.%I',f.tgname,tab.source_schema,tab.source_table);EXECUTE regexp_replace(definition,'EXECUTE (FUNCTION|PROCEDURE) .*$',format('EXECUTE FUNCTION gridex_ediel_retention.%I()',name));IF f.tgenabled='A' THEN EXECUTE format('ALTER TABLE %I.%I ENABLE ALWAYS TRIGGER %I',tab.source_schema,tab.source_table,f.tgname);END IF;
  EXECUTE format('CREATE TRIGGER brp_00_retention_source_lock BEFORE INSERT ON %I.%I FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.protected_copy_insert_v1()',tab.source_schema,tab.source_table);
 END LOOP;
 CREATE TRIGGER brp_00_retention_source_lock BEFORE INSERT ON gridex_brp_sources.contract_revocations FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.protected_copy_insert_v1();
 FOR spec IN SELECT * FROM gridex_ediel_retention.protected_copy_specs LOOP EXECUTE format('CREATE TRIGGER protected_copy_view_update INSTEAD OF UPDATE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.protected_copy_view_update_v1()',spec.view_name);END LOOP;
END$$;
-- Current consumer predicates apply to the selected original. A retired older
-- declaration never blankets an independent later source or dated candidate.
CREATE FUNCTION gridex_ediel_retention.protected_copy_current_v1(c uuid,target uuid) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 RETURN NOT EXISTS(SELECT FROM gridex_ediel_retention.protected_copy_revocations WHERE company_id=c AND target_id=target);
END$$;
DO $$DECLARE f record;body text;needle text;signature text;BEGIN
 FOR signature IN SELECT unnest(ARRAY['gridex_ediel_retention.decision_evidence_basis_v1(uuid,text,uuid)','public.ediel_read_retention_decision_original_v1(uuid,uuid,text,uuid,boolean)','public.ediel_purge_decision_evidence_retention_v1(uuid,uuid,uuid)','gridex_brp_sources.require_source_v1(uuid,uuid,uuid,text,text,uuid,uuid,uuid,timestamptz,uuid)','gridex_customer_life_events.certification_basis_v1(jsonb,text)']) LOOP
  SELECT p.oid,to_jsonb(p)-'prosrc' metadata,p.prosrc,pg_get_functiondef(p.oid) definition INTO STRICT f FROM pg_proc p WHERE p.oid=signature::regprocedure;body:=f.prosrc;
  IF signature LIKE '%decision_evidence_basis_v1%' THEN
   needle:='SELECT source_table INTO STRICT tab';IF position(needle IN body)=0 THEN RAISE EXCEPTION 'protected_copy_basis_port_review_required';END IF;
   body:=replace(body,needle,'IF EXISTS(SELECT FROM gridex_ediel_retention.protected_copy_specs WHERE retention_class=k) THEN RETURN gridex_ediel_retention.protected_copy_basis_v1(c,k,target);END IF; '||needle);
  ELSIF signature LIKE '%ediel_read_retention_decision_original_v1%' THEN
   needle:='SELECT source_table INTO STRICT tab';IF position(needle IN body)=0 OR body!~'decision_evidence_read_actor_v1' THEN RAISE EXCEPTION 'protected_copy_read_port_review_required';END IF;
   body:=replace(body,needle,'IF EXISTS(SELECT FROM gridex_ediel_retention.protected_copy_specs WHERE retention_class=p_retention_class) THEN r:=gridex_ediel_retention.protected_copy_row_v1(p_company_id,p_retention_class,p_target_id);b:=decode(substr(r->>''document_bytes'',3),''hex'');SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=p_retention_class AND target_id=p_target_id AND company_id=p_company_id;RETURN jsonb_build_object(''companyId'',p_company_id,''retentionClass'',p_retention_class,''targetId'',p_target_id,''documentHash'',r->>''document_hash'',''targetMetadataHash'',encode(sha256(convert_to((r-ARRAY[''document_bytes'',''document_byte_length'',''document_purged_at''])::text,''UTF8'')),''hex''),''documentByteLength'',coalesce(octet_length(b),t.byte_length),''bytesAvailable'',b IS NOT NULL,''documentBase64'',CASE WHEN p_include_document AND b IS NOT NULL THEN replace(encode(b,''base64''),E''
'','''') ELSE NULL END,''purgedAt'',t.created_at,''authority'',''none'');END IF; '||needle);
  ELSIF signature LIKE '%ediel_purge_decision_evidence_retention_v1%' THEN
   needle:='EXECUTE format(''INSERT INTO gridex_ediel_retention.%I(%I,actor_user_id,reason) VALUES($1,$2,$3) ON CONFLICT DO NOTHING'',spec.revocation_table,spec.revocation_id_column) USING d.target_id,p_actor_user_id,left(''Qualified decision-original policy: ''||(p->>''legalBasisReference''),4000);';
   IF position(needle IN body)=0 OR body!~'replay'',true' THEN RAISE EXCEPTION 'protected_copy_purge_port_review_required';END IF;
   body:=replace(body,needle,'IF EXISTS(SELECT FROM gridex_ediel_retention.protected_copy_specs WHERE retention_class=d.retention_class) THEN INSERT INTO gridex_ediel_retention.protected_copy_revocations(retention_class,target_id,company_id,policy_id,review_id,source_hash,actor_user_id) VALUES(d.retention_class,d.target_id,d.company_id,d.id,r.id,d.source_hash,p_actor_user_id);ELSE '||needle||' END IF;');
  ELSIF signature LIKE '%require_source_v1%' THEN
   needle:='SELECT * INTO d FROM gridex_brp_sources.contract_declarations x';IF position(needle IN body)=0 OR body!~'signed_contract_brp_declaration' THEN RAISE EXCEPTION 'protected_copy_brp_actual_selected_source_review_required';END IF;
   needle:=substr(body,position(needle IN body));needle:=left(needle,position('FOR SHARE;' IN needle)+9);
   body:=replace(body,needle,needle||' IF d.agreement_original IS NULL OR d.source_original IS NULL OR encode(sha256(d.agreement_original),''hex'') IS DISTINCT FROM d.agreement_sha256 OR encode(sha256(d.source_original),''hex'') IS DISTINCT FROM d.source_sha256 OR gridex_ediel_retention.protected_copy_current_v1(c,d.id) IS NOT TRUE THEN RETURN jsonb_build_object(''status'',''held'',''missing'',ARRAY[''actual_retained_brp_declaration_originals'']);END IF;');
   body:=regexp_replace(body,'\mBEGIN\M','BEGIN PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();','i');
  ELSE
   needle:='IF EXISTS(SELECT FROM gridex_customer_life_events.certification_classification_revocations r WHERE r.declaration_id=d.id)';IF position(needle IN body)=0 OR body!~'independently_classified_fixture' THEN RAISE EXCEPTION 'protected_copy_certification_actual_selected_source_review_required';END IF;
   body:=replace(body,needle,'IF d.workbook_original IS NULL OR d.classification_original IS NULL OR encode(sha256(d.workbook_original),''hex'') IS DISTINCT FROM d.workbook_sha256 OR encode(sha256(d.classification_original),''hex'') IS DISTINCT FROM d.classification_sha256 OR gridex_ediel_retention.protected_copy_current_v1(d.company_id,d.id) IS NOT TRUE THEN RETURN jsonb_build_object(''status'',''held'',''missing'',ARRAY[''actual_retained_certification_classification_originals'']);END IF; '||needle);
   body:=regexp_replace(body,'\mBEGIN\M','BEGIN PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();','i');
  END IF;
  EXECUTE replace(f.definition,f.prosrc,body);IF NOT EXISTS(SELECT FROM pg_proc p WHERE p.oid=f.oid AND(to_jsonb(p)-'prosrc')=f.metadata) THEN RAISE EXCEPTION 'protected_copy_function_identity_changed';END IF;
 END LOOP;
END$$;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_ediel_retention' AND p.proname LIKE 'protected_copy_%' LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO gridex_ediel_retention_owner',f.signature);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.signature);END LOOP;END$$;
COMMIT;
