-- Bounded signed-BRP custody port composed with the current source consumer.
-- Reviewed predecessor WIP93100 is not reapplied or published as history.
-- Independent signed-agreement BRP purpose. Retention issuer competence,
-- technical routing, an uploaded PDF or a caller approval flag cannot mint it.
BEGIN;
CREATE SCHEMA gridex_brp_declaration_intake;
REVOKE ALL ON SCHEMA gridex_brp_declaration_intake FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE gridex_brp_declaration_intake.artifacts(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL CHECK(environment IN('test','production')),contract_id uuid NOT NULL REFERENCES public.customer_contracts(id),
 claims jsonb NOT NULL,claims_hash text NOT NULL CHECK(claims_hash~'^[a-f0-9]{64}$'),agreement_original bytea NOT NULL CHECK(octet_length(agreement_original) BETWEEN 1 AND 10485760),agreement_sha256 text NOT NULL CHECK(agreement_sha256=encode(sha256(agreement_original),'hex')),
 source_original bytea NOT NULL CHECK(octet_length(source_original) BETWEEN 1 AND 10485760),source_sha256 text NOT NULL CHECK(source_sha256=encode(sha256(source_original),'hex')),source_reference text NOT NULL CHECK(length(btrim(source_reference)) BETWEEN 1 AND 2000),source_version text NOT NULL CHECK(length(btrim(source_version)) BETWEEN 1 AND 200),issuer_receipt jsonb,
 submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(company_id,environment,contract_id,claims_hash,agreement_sha256,source_sha256,source_reference,source_version));
CREATE TABLE gridex_brp_declaration_intake.reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),artifact_id uuid NOT NULL REFERENCES gridex_brp_declaration_intake.artifacts(id),company_id uuid NOT NULL,reviewer_user_id uuid NOT NULL REFERENCES auth.users(id),decision text NOT NULL CHECK(decision IN('approved','held','rejected')),reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 4000),missing jsonb NOT NULL,clause jsonb,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_brp_declaration_intake.origins(declaration_id uuid PRIMARY KEY REFERENCES gridex_brp_sources.contract_declarations(id),artifact_id uuid UNIQUE NOT NULL REFERENCES gridex_brp_declaration_intake.artifacts(id),review_id uuid UNIQUE NOT NULL REFERENCES gridex_brp_declaration_intake.reviews(id),company_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_brp_declaration_intake.artifact_revocations(artifact_id uuid PRIMARY KEY REFERENCES gridex_brp_declaration_intake.artifacts(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 4000),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
-- A protected source-authority register is deliberately unseeded. These keys
-- have no shared retention/death/bilateral/temporary-transport competence.
CREATE TABLE gridex_brp_declaration_intake.issuer_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL CHECK(environment IN('test','production')),issuer_code text NOT NULL,legal_source_reference text NOT NULL CHECK(btrim(legal_source_reference)<>''),legal_source_sha256 text NOT NULL CHECK(legal_source_sha256~'^[a-f0-9]{64}$'),signing_key bytea NOT NULL CHECK(octet_length(signing_key)>=32),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(isfinite(valid_from) AND isfinite(valid_to) AND valid_to>valid_from));
CREATE TABLE gridex_brp_declaration_intake.issuer_representations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,environment text NOT NULL,issuer_key_id uuid NOT NULL REFERENCES gridex_brp_declaration_intake.issuer_keys(id),legal_actor_id uuid NOT NULL,purpose text NOT NULL CHECK(purpose='signed_contract_brp_declaration'),legal_source_reference text NOT NULL CHECK(btrim(legal_source_reference)<>''),legal_source_sha256 text NOT NULL CHECK(legal_source_sha256~'^[a-f0-9]{64}$'),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(isfinite(valid_from) AND isfinite(valid_to) AND valid_to>valid_from));
CREATE TABLE gridex_brp_declaration_intake.issuer_revocations(target_kind text NOT NULL CHECK(target_kind IN('key','representation')),target_id uuid NOT NULL,legal_source_reference text NOT NULL CHECK(btrim(legal_source_reference)<>''),legal_source_sha256 text NOT NULL CHECK(legal_source_sha256~'^[a-f0-9]{64}$'),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(target_kind,target_id));
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['artifacts','reviews','origins','artifact_revocations','issuer_keys','issuer_representations','issuer_revocations'] LOOP
 EXECUTE format('ALTER TABLE gridex_brp_declaration_intake.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_brp_declaration_intake.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_brp_declaration_intake.%I FROM PUBLIC,anon,authenticated,service_role',t);
 EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON gridex_brp_declaration_intake.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);EXECUTE format('CREATE TRIGGER no_truncate BEFORE TRUNCATE ON gridex_brp_declaration_intake.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);
END LOOP;END$$;
CREATE FUNCTION gridex_brp_declaration_intake.actor_v1(c uuid,actor uuid,mode text,require_session boolean DEFAULT true) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE wanted text;at timestamptz;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 IF (mode IN('archive','read','review','revoke')) IS NOT TRUE OR require_session AND public.ediel_retention_session_actor_v1() IS DISTINCT FROM actor OR public.ediel_retention_lock_auth_actor_v1(actor) IS NOT TRUE THEN RETURN false;END IF;
 PERFORM id FROM public.companies WHERE id=c FOR SHARE;PERFORM user_id FROM public.company_memberships WHERE company_id=c AND user_id=actor FOR SHARE;
 IF NOT EXISTS(SELECT FROM public.companies WHERE id=c AND status='active') OR NOT EXISTS(SELECT FROM public.company_memberships WHERE company_id=c AND user_id=actor AND status='active' AND is_active AND accepted_at IS NOT NULL) THEN RETURN false;END IF;
 PERFORM id FROM public.user_permission_overrides WHERE user_id=actor AND(company_id IS NULL OR company_id=c) ORDER BY id FOR SHARE;
 FOREACH wanted IN ARRAY CASE WHEN mode='read' THEN ARRAY['communication.read','customers.read','contracts.read'] WHEN mode='review' THEN ARRAY['communication.write','customers.write','contracts.write','ediel.source.review'] ELSE ARRAY['communication.write','customers.write','contracts.write'] END LOOP
  IF gridex_requested_changes.scoped_permission_v1(c,actor,wanted) IS NOT TRUE THEN RETURN false;END IF;
  at:=clock_timestamp();IF EXISTS(SELECT FROM public.user_permission_overrides WHERE user_id=actor AND(company_id IS NULL OR company_id=c) AND permission_key=wanted AND is_active AND effect='deny' AND(valid_from IS NULL OR valid_from<=at) AND(valid_to IS NULL OR at<valid_to)) THEN RETURN false;END IF;
 END LOOP;RETURN true;
END$$;
CREATE FUNCTION gridex_brp_declaration_intake.scope_v1(c uuid,env text,ct uuid,ground uuid,agreement_hash text,agency text) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE contract public.customer_contracts%rowtype;point public.metering_points%rowtype;site public.customer_sites%rowtype;document public.customer_contract_documents%rowtype;g gridex_brp_changes.registry_grounds%rowtype;sender text;header jsonb;registry jsonb;signature text;n integer;at timestamptz;
BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 SELECT * INTO contract FROM public.customer_contracts WHERE id=ct AND company_id=c FOR SHARE;
 SELECT * INTO point FROM public.metering_points WHERE id=contract.metering_point_id AND company_id=c FOR SHARE;
 SELECT * INTO site FROM public.customer_sites WHERE id=coalesce(contract.customer_site_id,contract.site_id) AND company_id=c FOR SHARE;
 SELECT * INTO document FROM public.customer_contract_documents WHERE company_id=c AND customer_contract_id=ct AND document_type='signed_contract_pdf' AND document_sha256=agreement_hash AND verified_at IS NOT NULL ORDER BY id LIMIT 1 FOR SHARE;
 signature:=encode(sha256(convert_to(contract.signature_snapshot::text,'UTF8')),'hex');
 IF (env IN('test','production')) IS NOT TRUE OR (agency IN('9','89')) IS NOT TRUE OR contract.id IS NULL OR point.id IS NULL OR site.id IS NULL OR document.id IS NULL OR contract.customer_id IS DISTINCT FROM point.customer_id OR site.customer_id IS DISTINCT FROM contract.customer_id OR coalesce(point.customer_site_id,point.site_id) IS DISTINCT FROM site.id OR contract.site_id IS NOT NULL AND contract.site_id IS DISTINCT FROM site.id OR contract.customer_site_id IS NOT NULL AND contract.customer_site_id IS DISTINCT FROM site.id OR point.site_id IS NOT NULL AND point.site_id IS DISTINCT FROM site.id OR point.customer_site_id IS NOT NULL AND point.customer_site_id IS DISTINCT FROM site.id
 OR (contract.status IN('signed','active')) IS NOT TRUE OR contract.signed_at IS NULL OR nullif(contract.signed_version,'') IS NULL OR contract.signed_version IS DISTINCT FROM contract.contract_version OR contract.document_sha256 IS DISTINCT FROM agreement_hash OR signature IS DISTINCT FROM contract.signature_snapshot_sha256 OR contract.signature_snapshot->>'company_id' IS DISTINCT FROM c::text OR contract.signature_snapshot->>'customer_id' IS DISTINCT FROM contract.customer_id::text OR contract.signature_snapshot->>'contract_id' IS DISTINCT FROM ct::text THEN RETURN NULL;END IF;
 PERFORM id FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=env ORDER BY id FOR SHARE;
 at:=clock_timestamp();SELECT count(DISTINCT actor_id),min(identifier_value) INTO n,sender FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=env AND identifier_type='EdielId' AND valid_from<=at AND(valid_to IS NULL OR at<valid_to);
 IF n<>1 OR nullif(sender,'') IS NULL OR(SELECT count(DISTINCT identifier_value) FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=env AND identifier_type='EdielId' AND valid_from<=at AND(valid_to IS NULL OR at<valid_to))<>1 THEN RETURN NULL;END IF;
 SELECT * INTO g FROM gridex_brp_changes.registry_grounds WHERE id=ground AND company_id=c AND environment=env AND dso_ediel_id=point.grid_owner_ediel_id AND grid_area_code=point.grid_area_code FOR SHARE;IF g.id IS NULL THEN RETURN NULL;END IF;
 registry:=gridex_brp_sources.registry_basis_v1(c,env,point.grid_owner_ediel_id,point.grid_area_code,g.brp_ediel_id,at,g.id);IF registry IS NULL THEN RETURN NULL;END IF;
 BEGIN header:=gridex_ai_processing.header_company_basis_v1(c,env,sender,point.grid_owner_ediel_id);EXCEPTION WHEN raise_exception THEN RETURN NULL;END;
 IF header->>'legalActorId' IS NULL OR header->>'legalSupplier' IS DISTINCT FROM sender THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('purpose','signed_contract_brp_declaration','companyId',c,'environment',env,'contractId',ct,'contractRevision',contract.signed_version,'protectedContractHash',gridex_received_sources.production_contract_hash_v1(contract),'customerId',contract.customer_id,'siteId',site.id,'meteringPointId',point.id,'pointId',coalesce(nullif(point.ediel_metering_point_id,''),nullif(point.meter_point_id,'')),'identityAgency',agency,'legalActorId',header->>'legalActorId','legalSenderId',sender,'legalReceiverId',point.grid_owner_ediel_id,'gridAreaCode',point.grid_area_code,'registryGroundId',g.id,'brpEdielId',g.brp_ediel_id,'agreementHash',agreement_hash,'contractDocumentId',document.id,'contractDocumentHash',encode(sha256(convert_to(to_jsonb(document)::text,'UTF8')),'hex'),'signatureHash',signature,'registryBasis',registry);
END$$;
CREATE FUNCTION gridex_brp_declaration_intake.receipt_current_v1(a gridex_brp_declaration_intake.artifacts) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE k gridex_brp_declaration_intake.issuer_keys%rowtype;g gridex_brp_declaration_intake.issuer_representations%rowtype;raw bytea;p jsonb;r jsonb:=a.issuer_receipt;issued timestamptz;expires timestamptz;at timestamptz;BEGIN
 IF a.agreement_original IS NULL OR a.source_original IS NULL OR encode(sha256(a.agreement_original),'hex') IS DISTINCT FROM a.agreement_sha256 OR encode(sha256(a.source_original),'hex') IS DISTINCT FROM a.source_sha256 OR encode(sha256(convert_to(a.claims::text,'UTF8')),'hex') IS DISTINCT FROM a.claims_hash OR r IS NULL THEN RETURN false;END IF;
 SELECT * INTO k FROM gridex_brp_declaration_intake.issuer_keys WHERE id=(r->>'keyId')::uuid AND company_id=a.company_id AND environment=a.environment FOR SHARE;
 SELECT * INTO g FROM gridex_brp_declaration_intake.issuer_representations WHERE id=(r->>'representationId')::uuid AND issuer_key_id=k.id AND company_id=a.company_id AND environment=a.environment AND legal_actor_id=(a.claims->>'legalActorId')::uuid AND purpose='signed_contract_brp_declaration' FOR SHARE;
 at:=clock_timestamp();IF k.id IS NULL OR g.id IS NULL OR at<k.valid_from OR at>=k.valid_to OR at<g.valid_from OR at>=g.valid_to OR EXISTS(SELECT FROM gridex_brp_declaration_intake.issuer_revocations WHERE target_kind='key' AND target_id=k.id OR target_kind='representation' AND target_id=g.id) THEN RETURN false;END IF;
 raw:=decode(r->>'payloadBase64','base64');IF octet_length(raw) NOT BETWEEN 1 AND 65536 OR sha256(gridex_requested_changes.receipt_hmac_sha256_v1(raw,k.signing_key)) IS DISTINCT FROM sha256(decode(r->>'signatureHex','hex')) THEN RETURN false;END IF;
 p:=convert_from(raw,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;at:=clock_timestamp();
 RETURN(p->>'format'='ediel_signed_brp_declaration_receipt_v1' AND p->>'purpose'='signed_contract_brp_declaration' AND p->>'companyId'=a.company_id::text AND p->>'environment'=a.environment AND p->>'issuerCode'=k.issuer_code AND nullif(p->>'receiptId','') IS NOT NULL AND p->>'issuerLegalReference'=k.legal_source_reference AND p->>'representationLegalReference'=g.legal_source_reference AND p->>'claimsHash'=a.claims_hash AND p->>'agreementHash'=a.agreement_sha256 AND p->>'sourceHash'=a.source_sha256 AND p->>'sourceReference'=a.source_reference AND p->>'sourceVersion'=a.source_version AND issued IS NOT NULL AND expires IS NOT NULL AND isfinite(issued) AND isfinite(expires) AND at>=greatest(k.valid_from,g.valid_from) AND at<least(k.valid_to,g.valid_to) AND issued<=at AND expires>at AND issued>=greatest(k.valid_from,g.valid_from) AND expires<=least(k.valid_to,g.valid_to)) IS TRUE;
EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR invalid_datetime_format OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN false;
END$$;
CREATE FUNCTION gridex_brp_declaration_intake.revocation_lock_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE ct uuid;c uuid;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 IF TG_TABLE_NAME='issuer_revocations' THEN IF NEW.target_kind='key' THEN PERFORM id FROM gridex_brp_declaration_intake.issuer_keys WHERE id=NEW.target_id FOR UPDATE;ELSE PERFORM id FROM gridex_brp_declaration_intake.issuer_representations WHERE id=NEW.target_id FOR UPDATE;END IF;
 ELSE SELECT contract_id,company_id INTO ct,c FROM gridex_brp_declaration_intake.artifacts WHERE id=NEW.artifact_id;PERFORM id FROM public.customer_contracts WHERE id=ct AND company_id=c FOR SHARE;PERFORM pg_advisory_xact_lock(hashtextextended('contract-brp:'||c::text||':'||ct::text,0));PERFORM id FROM gridex_brp_sources.contract_declarations WHERE id IN(SELECT declaration_id FROM gridex_brp_declaration_intake.origins WHERE artifact_id=NEW.artifact_id) FOR UPDATE;PERFORM id FROM gridex_brp_declaration_intake.artifacts WHERE id=NEW.artifact_id FOR UPDATE;END IF;
 IF NOT FOUND THEN RAISE EXCEPTION 'signed_brp_revocation_target_required';END IF;RETURN NEW;
END$$;
CREATE TRIGGER source_revocation_lock BEFORE INSERT ON gridex_brp_declaration_intake.artifact_revocations FOR EACH ROW EXECUTE FUNCTION gridex_brp_declaration_intake.revocation_lock_v1();
CREATE TRIGGER issuer_revocation_lock BEFORE INSERT ON gridex_brp_declaration_intake.issuer_revocations FOR EACH ROW EXECUTE FUNCTION gridex_brp_declaration_intake.revocation_lock_v1();
CREATE FUNCTION public.ediel_signed_brp_declaration_scope_v1(p_company_id uuid,p_actor_user_id uuid,p_selector jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE claims jsonb;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'read') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_scope_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_selector) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_selector) k WHERE k NOT IN('environment','contractId','registryGroundId','identityAgency','agreementHash')) OR (p_selector->>'agreementHash'~'^[a-f0-9]{64}$') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_scope_shape_required';END IF;
 claims:=gridex_brp_declaration_intake.scope_v1(p_company_id,p_selector->>'environment',(p_selector->>'contractId')::uuid,(p_selector->>'registryGroundId')::uuid,p_selector->>'agreementHash',p_selector->>'identityAgency');
 IF claims IS NULL THEN RETURN jsonb_build_object('status','held','missing',ARRAY['actual_current_signed_contract_document_registry_scope'],'authority','none');END IF;
 RETURN jsonb_build_object('status','scope_available','claims',claims,'claimsHash',encode(sha256(convert_to(claims::text,'UTF8')),'hex'),'authority','none');
END$$;
CREATE FUNCTION public.ediel_archive_signed_brp_declaration_v1(p_company_id uuid,p_actor_user_id uuid,p_submission jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE claims jsonb;ah text;sh text;ch text;agreement bytea;source bytea;a gridex_brp_declaration_intake.artifacts%rowtype;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'archive') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_archive_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_submission) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission) k WHERE k NOT IN('environment','contractId','registryGroundId','identityAgency','agreementBase64','sourceBase64','sourceReference','sourceVersion','issuerReceipt')) THEN RAISE EXCEPTION 'signed_brp_archive_shape_required';END IF;
 agreement:=decode(p_submission->>'agreementBase64','base64');source:=decode(p_submission->>'sourceBase64','base64');IF octet_length(agreement) NOT BETWEEN 1 AND 10485760 OR octet_length(source) NOT BETWEEN 1 AND 10485760 OR substr(agreement,1,5)<>convert_to('%PDF-','UTF8') THEN RAISE EXCEPTION 'signed_brp_actual_pdf_and_source_required';END IF;
 ah:=encode(sha256(agreement),'hex');sh:=encode(sha256(source),'hex');claims:=gridex_brp_declaration_intake.scope_v1(p_company_id,p_submission->>'environment',(p_submission->>'contractId')::uuid,(p_submission->>'registryGroundId')::uuid,ah,p_submission->>'identityAgency');IF claims IS NULL THEN RAISE EXCEPTION 'signed_brp_actual_current_contract_document_registry_scope_required';END IF;ch:=encode(sha256(convert_to(claims::text,'UTF8')),'hex');
 SELECT * INTO a FROM gridex_brp_declaration_intake.artifacts WHERE company_id=p_company_id AND environment=p_submission->>'environment' AND contract_id=(p_submission->>'contractId')::uuid AND claims_hash=ch AND agreement_sha256=ah AND source_sha256=sh AND source_reference=p_submission->>'sourceReference' AND source_version=p_submission->>'sourceVersion' FOR SHARE;
 IF FOUND THEN IF a.issuer_receipt IS DISTINCT FROM p_submission->'issuerReceipt' THEN RAISE EXCEPTION 'signed_brp_archive_immutable_receipt_conflict';END IF;ELSE
  IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'archive') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_archive_actor_revoked' USING ERRCODE='42501';END IF;
  INSERT INTO gridex_brp_declaration_intake.artifacts(company_id,environment,contract_id,claims,claims_hash,agreement_original,agreement_sha256,source_original,source_sha256,source_reference,source_version,issuer_receipt,submitted_by) VALUES(p_company_id,p_submission->>'environment',(p_submission->>'contractId')::uuid,claims,ch,agreement,ah,source,sh,p_submission->>'sourceReference',p_submission->>'sourceVersion',p_submission->'issuerReceipt',p_actor_user_id) RETURNING * INTO a;
 END IF;RETURN jsonb_build_object('status','archived','artifactId',a.id,'agreementHash',ah,'sourceHash',sh,'claimsHash',ch,'issuerQualified',gridex_brp_declaration_intake.receipt_current_v1(a),'authority','none');
END$$;
CREATE FUNCTION gridex_brp_declaration_intake.origin_current_v1(c uuid,declaration uuid) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_brp_sources.contract_declarations%rowtype;a gridex_brp_declaration_intake.artifacts%rowtype;o gridex_brp_declaration_intake.origins%rowtype;r gridex_brp_declaration_intake.reviews%rowtype;claims jsonb;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();SELECT contract_id INTO d.contract_id FROM gridex_brp_sources.contract_declarations WHERE id=declaration AND company_id=c;PERFORM id FROM public.customer_contracts WHERE id=d.contract_id AND company_id=c FOR SHARE;PERFORM pg_advisory_xact_lock_shared(hashtextextended('contract-brp:'||c::text||':'||d.contract_id::text,0));
 SELECT * INTO d FROM gridex_brp_sources.contract_declarations WHERE id=declaration AND company_id=c FOR SHARE;SELECT * INTO o FROM gridex_brp_declaration_intake.origins WHERE declaration_id=declaration AND company_id=c;SELECT * INTO a FROM gridex_brp_declaration_intake.artifacts WHERE id=o.artifact_id AND company_id=c FOR SHARE;SELECT * INTO r FROM gridex_brp_declaration_intake.reviews WHERE id=o.review_id AND company_id=c FOR SHARE;
 IF a.id IS NULL OR gridex_ediel_retention.protected_copy_current_v1(c,a.id) IS NOT TRUE OR d.id IS NULL OR r.decision IS DISTINCT FROM 'approved' OR r.reviewer_user_id=a.submitted_by OR r.artifact_id IS DISTINCT FROM a.id OR EXISTS(SELECT FROM gridex_brp_declaration_intake.artifact_revocations WHERE artifact_id=a.id) OR a.agreement_original IS NULL OR a.source_original IS NULL OR d.agreement_original IS DISTINCT FROM a.agreement_original OR d.source_original IS DISTINCT FROM a.source_original OR d.source_reference IS DISTINCT FROM a.source_reference OR d.source_version IS DISTINCT FROM a.source_version OR encode(sha256(convert_to(a.claims::text,'UTF8')),'hex') IS DISTINCT FROM a.claims_hash THEN RETURN false;END IF;
 claims:=gridex_brp_declaration_intake.scope_v1(c,a.environment,a.contract_id,(a.claims->>'registryGroundId')::uuid,a.agreement_sha256,a.claims->>'identityAgency');
 RETURN claims=a.claims AND gridex_brp_declaration_intake.receipt_current_v1(a) IS TRUE AND gridex_brp_declaration_intake.actor_v1(c,r.reviewer_user_id,'review',false) IS TRUE AND gridex_brp_declaration_intake.receipt_current_v1(a) IS TRUE;
END$$;
CREATE FUNCTION public.ediel_read_signed_brp_declaration_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_include_bytes boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE a gridex_brp_declaration_intake.artifacts%rowtype;r gridex_brp_declaration_intake.reviews%rowtype;declaration uuid;result jsonb;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'read') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_read_actor_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO STRICT a FROM gridex_brp_declaration_intake.artifacts WHERE id=p_artifact_id AND company_id=p_company_id;
 PERFORM id FROM public.customer_contracts WHERE id=a.contract_id AND company_id=p_company_id FOR SHARE;PERFORM pg_advisory_xact_lock_shared(hashtextextended('contract-brp:'||p_company_id::text||':'||a.contract_id::text,0));SELECT declaration_id INTO declaration FROM gridex_brp_declaration_intake.origins WHERE artifact_id=a.id;PERFORM id FROM gridex_brp_sources.contract_declarations WHERE id=declaration FOR SHARE;SELECT * INTO STRICT a FROM gridex_brp_declaration_intake.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR SHARE;
 SELECT * INTO r FROM gridex_brp_declaration_intake.reviews WHERE artifact_id=a.id ORDER BY created_at DESC,id DESC LIMIT 1;
 result:=jsonb_build_object('artifactId',a.id,'companyId',a.company_id,'environment',a.environment,'contractId',a.contract_id,'claims',a.claims,'claimsHash',a.claims_hash,'agreementHash',a.agreement_sha256,'sourceHash',a.source_sha256,'sourceReference',a.source_reference,'sourceVersion',a.source_version,'agreementByteLength',octet_length(a.agreement_original),'sourceByteLength',octet_length(a.source_original),'bytesAvailable',a.agreement_original IS NOT NULL AND a.source_original IS NOT NULL,'issuerQualified',gridex_brp_declaration_intake.receipt_current_v1(a),'status',CASE WHEN declaration IS NOT NULL AND gridex_brp_declaration_intake.origin_current_v1(p_company_id,declaration) IS TRUE THEN 'authorized' WHEN r.decision='rejected' THEN 'rejected' ELSE 'held' END,'declarationId',declaration,'missing',coalesce(r.missing,'["separate_current_source_review"]'::jsonb),'authority','none');
 IF p_include_bytes THEN IF a.agreement_original IS NULL OR a.source_original IS NULL THEN RAISE EXCEPTION 'signed_brp_archived_original_retention_tombstone';END IF;result:=result||jsonb_build_object('agreementBase64',replace(encode(a.agreement_original,'base64'),E'\n',''),'sourceBase64',replace(encode(a.source_original,'base64'),E'\n',''));END IF;
 IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'read') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_read_actor_revoked' USING ERRCODE='42501';END IF;RETURN result;
END$$;
CREATE FUNCTION public.ediel_review_signed_brp_declaration_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_review jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE a gridex_brp_declaration_intake.artifacts%rowtype;r gridex_brp_declaration_intake.reviews%rowtype;o gridex_brp_declaration_intake.origins%rowtype;d gridex_brp_sources.contract_declarations%rowtype;claims jsonb;missing jsonb:='[]';decision text;ct uuid;prior uuid;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'review') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_review_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_review) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review) k WHERE k NOT IN('agreementHash','sourceHash','claimsHash','decision','reason','clause','previousDeclarationId')) OR (p_review->>'decision' IN('approve','hold','reject')) IS NOT TRUE OR (length(btrim(p_review->>'reason')) BETWEEN 1 AND 4000) IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_review_shape_required';END IF;
 SELECT contract_id INTO STRICT ct FROM gridex_brp_declaration_intake.artifacts WHERE id=p_artifact_id AND company_id=p_company_id;PERFORM id FROM public.customer_contracts WHERE id=ct AND company_id=p_company_id FOR SHARE;PERFORM pg_advisory_xact_lock(hashtextextended('contract-brp:'||p_company_id::text||':'||ct::text,0));SELECT * INTO o FROM gridex_brp_declaration_intake.origins WHERE artifact_id=p_artifact_id;prior:=nullif(p_review->>'previousDeclarationId','')::uuid;PERFORM id FROM gridex_brp_sources.contract_declarations WHERE id IN(o.declaration_id,prior) FOR SHARE;SELECT * INTO STRICT a FROM gridex_brp_declaration_intake.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR UPDATE;
 IF a.submitted_by=p_actor_user_id OR a.agreement_sha256 IS DISTINCT FROM p_review->>'agreementHash' OR a.source_sha256 IS DISTINCT FROM p_review->>'sourceHash' OR a.claims_hash IS DISTINCT FROM p_review->>'claimsHash' THEN RAISE EXCEPTION 'signed_brp_separate_exact_original_review_required';END IF;
 IF o.declaration_id IS NOT NULL THEN IF gridex_brp_declaration_intake.origin_current_v1(p_company_id,o.declaration_id) IS TRUE THEN RETURN jsonb_build_object('status','authorized','artifactId',a.id,'declarationId',o.declaration_id,'replay',true);END IF;RETURN jsonb_build_object('status','held','artifactId',a.id,'missing',ARRAY['existing_brp_source_current_authority']);END IF;
 claims:=gridex_brp_declaration_intake.scope_v1(p_company_id,a.environment,a.contract_id,(a.claims->>'registryGroundId')::uuid,a.agreement_sha256,a.claims->>'identityAgency');
 IF claims IS DISTINCT FROM a.claims OR a.agreement_original IS NULL OR a.source_original IS NULL OR encode(sha256(convert_to(a.claims::text,'UTF8')),'hex') IS DISTINCT FROM a.claims_hash THEN missing:=missing||'"same_current_signed_contract_document_registry_scope"'::jsonb;END IF;
 IF gridex_brp_declaration_intake.receipt_current_v1(a) IS NOT TRUE THEN missing:=missing||'"authentic_current_brp_purpose_issuer_representation_receipt"'::jsonb;END IF;
 IF EXISTS(SELECT FROM gridex_brp_declaration_intake.artifact_revocations WHERE artifact_id=a.id) THEN missing:=missing||'"archived_source_revoked"'::jsonb;END IF;
 IF p_review->>'decision'='hold' THEN missing:=missing||'"explicit_source_review_hold"'::jsonb;END IF;
 IF jsonb_typeof(p_review->'clause') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review->'clause') k WHERE k NOT IN('locator','quote')) OR (length(btrim(p_review#>>'{clause,locator}')) BETWEEN 1 AND 1000) IS NOT TRUE OR (length(btrim(p_review#>>'{clause,quote}')) BETWEEN 1 AND 10000) IS NOT TRUE THEN missing:=missing||'"verbatim_signed_agreement_brp_clause_review"'::jsonb;END IF;
 IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'review') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_review_actor_revoked' USING ERRCODE='42501';END IF;
 decision:=CASE WHEN p_review->>'decision'='reject' THEN 'rejected' WHEN jsonb_array_length(missing)>0 THEN 'held' ELSE 'approved' END;
 INSERT INTO gridex_brp_declaration_intake.reviews(artifact_id,company_id,reviewer_user_id,decision,reason,missing,clause) VALUES(a.id,p_company_id,p_actor_user_id,decision,p_review->>'reason',missing,p_review->'clause') RETURNING * INTO r;
 IF decision<>'approved' THEN RETURN jsonb_build_object('status',CASE decision WHEN 'rejected' THEN 'rejected' ELSE 'held' END,'artifactId',a.id,'missing',missing);END IF;
 IF gridex_brp_declaration_intake.receipt_current_v1(a) IS NOT TRUE OR gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'review') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_current_source_authority_expired' USING ERRCODE='42501';END IF;
 INSERT INTO gridex_brp_sources.contract_declarations(previous_declaration_id,company_id,environment,contract_id,contract_revision,protected_contract_hash,customer_id,site_id,metering_point_id,legal_actor_id,legal_sender_id,legal_receiver_id,point_id,identity_agency,grid_area_code,registry_ground_id,brp_ediel_id,agreement_original,agreement_sha256,source_reference,source_version,source_original,source_sha256,approved_by,approved_at)
 VALUES(prior,a.company_id,a.environment,a.contract_id,a.claims->>'contractRevision',a.claims->>'protectedContractHash',(a.claims->>'customerId')::uuid,(a.claims->>'siteId')::uuid,(a.claims->>'meteringPointId')::uuid,(a.claims->>'legalActorId')::uuid,a.claims->>'legalSenderId',a.claims->>'legalReceiverId',a.claims->>'pointId',a.claims->>'identityAgency',a.claims->>'gridAreaCode',(a.claims->>'registryGroundId')::uuid,a.claims->>'brpEdielId',a.agreement_original,a.agreement_sha256,a.source_reference,a.source_version,a.source_original,a.source_sha256,p_actor_user_id,clock_timestamp()) RETURNING * INTO d;
 INSERT INTO gridex_brp_declaration_intake.origins(declaration_id,artifact_id,review_id,company_id) VALUES(d.id,a.id,r.id,a.company_id);RETURN jsonb_build_object('status','authorized','artifactId',a.id,'declarationId',d.id,'replay',false);
END$$;
CREATE FUNCTION public.ediel_revoke_signed_brp_declaration_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_reason text) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE a gridex_brp_declaration_intake.artifacts%rowtype;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();IF gridex_brp_declaration_intake.actor_v1(p_company_id,p_actor_user_id,'revoke') IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_revoke_actor_forbidden' USING ERRCODE='42501';END IF;IF (length(btrim(p_reason)) BETWEEN 1 AND 4000) IS NOT TRUE THEN RAISE EXCEPTION 'signed_brp_revoke_reason_required';END IF;
 SELECT * INTO STRICT a FROM gridex_brp_declaration_intake.artifacts WHERE id=p_artifact_id AND company_id=p_company_id;
 INSERT INTO gridex_brp_declaration_intake.artifact_revocations(artifact_id,actor_user_id,reason) VALUES(a.id,p_actor_user_id,p_reason) ON CONFLICT DO NOTHING;RETURN jsonb_build_object('status','held','artifactId',a.id,'missing',ARRAY['archived_source_revoked']);
END$$;
-- Only this producer's immutable origin extends legacy fresh authority. No
-- old declaration is retroactively approved, and dated received-source sources
-- keep their existing independent branch and protected accepted replay.
DO $$DECLARE f record;body text;needle text;BEGIN
 SELECT p.oid,to_jsonb(p)-'prosrc' metadata,p.prosrc,pg_get_functiondef(p.oid) definition INTO STRICT f FROM pg_proc p WHERE p.oid='gridex_brp_sources.require_source_v1(uuid,uuid,uuid,text,text,uuid,uuid,uuid,timestamptz,uuid)'::regprocedure;
 needle:='SELECT * INTO mp FROM public.metering_points WHERE id=point';IF position(needle IN f.prosrc)=0 OR f.prosrc!~'protected_copy_current_v1' THEN RAISE EXCEPTION 'signed_brp_actual_fresh_consumer_port_review_required';END IF;
 body:=replace(f.prosrc,needle,'IF gridex_brp_declaration_intake.origin_current_v1(c,d.id) IS NOT TRUE THEN RETURN jsonb_build_object(''status'',''held'',''missing'',ARRAY[''current_authenticated_signed_brp_source_origin'']);END IF; '||needle);EXECUTE replace(f.definition,f.prosrc,body);
 IF NOT EXISTS(SELECT FROM pg_proc p WHERE p.oid=f.oid AND(to_jsonb(p)-'prosrc')=f.metadata) THEN RAISE EXCEPTION 'signed_brp_actual_consumer_identity_changed';END IF;
END$$;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_brp_declaration_intake' LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.signature);END LOOP;END$$;
REVOKE ALL ON FUNCTION public.ediel_signed_brp_declaration_scope_v1(uuid,uuid,jsonb),public.ediel_archive_signed_brp_declaration_v1(uuid,uuid,jsonb),public.ediel_read_signed_brp_declaration_v1(uuid,uuid,uuid,boolean),public.ediel_review_signed_brp_declaration_v1(uuid,uuid,uuid,jsonb),public.ediel_revoke_signed_brp_declaration_v1(uuid,uuid,uuid,text) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.ediel_signed_brp_declaration_scope_v1(uuid,uuid,jsonb),public.ediel_archive_signed_brp_declaration_v1(uuid,uuid,jsonb),public.ediel_read_signed_brp_declaration_v1(uuid,uuid,uuid,boolean),public.ediel_review_signed_brp_declaration_v1(uuid,uuid,uuid,jsonb),public.ediel_revoke_signed_brp_declaration_v1(uuid,uuid,uuid,text) TO authenticated;
COMMIT;
