-- Each actual finance copy has its own exact native class and source period.
-- Amounts, identity, original producer hashes and immutable history survive.
-- No default legal duration, invoice deletion, provider traffic or cascade.
BEGIN;
GRANT CREATE ON SCHEMA public TO gridex_ediel_retention_owner;
CREATE TABLE gridex_ediel_retention.finance_class_catalog(retention_class text PRIMARY KEY,source_schema text NOT NULL,source_table text NOT NULL,id_column text NOT NULL,body_columns text[] NOT NULL,permission_key text NOT NULL,source_kind text NOT NULL,operation text NOT NULL,UNIQUE(source_schema,source_table));
INSERT INTO gridex_ediel_retention.finance_class_catalog VALUES
 ('billing_underlay_source_body','gridex_billing_source','underlay_bindings','underlay_id',ARRAY['source_basis'],'ediel.retention.billing_source_evidence','underlay','redact_finance_copy_body'),
 ('billing_underlay_payload_body','public','billing_underlays','id',ARRAY['payload','pricing_snapshot'],'ediel.retention.billing_source_evidence','underlay','redact_finance_copy_body'),
 ('invoice_calculation_body','public','customer_invoices','id',ARRAY['raw_payload','metadata','calculation_snapshot','portfolio_settlement_snapshot'],'ediel.retention.invoice_copy_evidence','invoice','redact_finance_copy_body'),
 ('invoice_line_body','public','customer_invoice_lines','id',ARRAY['description','metadata'],'ediel.retention.invoice_copy_evidence','invoice_line','redact_finance_copy_body'),
 ('invoice_export_item_body','public','invoice_export_items','id',ARRAY['request_payload','response_payload','error_payload','status_payload','metadata'],'ediel.retention.invoice_copy_evidence','item','redact_finance_copy_body'),
 ('invoice_export_run_body','public','invoice_export_runs','id',ARRAY['readiness_snapshot','metadata'],'ediel.retention.invoice_copy_evidence','run','redact_finance_copy_body'),
 ('invoice_provider_event_body','public','invoice_provider_events','id',ARRAY['payload'],'ediel.retention.invoice_copy_evidence','provider_event','redact_finance_copy_body'),
 ('invoice_purchase_event_body','public','invoice_purchase_events','id',ARRAY['payload'],'ediel.retention.invoice_copy_evidence','item_child','redact_finance_copy_body'),
 ('invoice_document_provider_body','public','invoice_documents','id',ARRAY['provider_payload'],'ediel.retention.invoice_copy_evidence','item_child','redact_finance_copy_body'),
 ('invoice_dead_letter_body','public','invoice_dead_letters','id',ARRAY['payload','error_message'],'ediel.retention.invoice_copy_evidence','item_child','redact_finance_copy_body'),
 ('invoice_export_attempt_body','public','invoice_export_attempts','id',ARRAY['response_excerpt'],'ediel.retention.invoice_copy_evidence','item_child','redact_finance_copy_body'),
 ('billing_export_item_body','public','billing_export_run_items','id',ARRAY['payload','invoice_address_snapshot','site_address_snapshot','payload_snapshot','adapter_payload_snapshot'],'ediel.retention.invoice_copy_evidence','underlay_child','redact_finance_copy_body'),
 ('partner_export_body','public','partner_exports','id',ARRAY['payload','response_payload','partner_response_log'],'ediel.retention.invoice_copy_evidence','underlay_child','redact_finance_copy_body'),
 ('settlement_calculation_body','public','portfolio_monthly_settlements','id',ARRAY['calculation_snapshot'],'ediel.retention.settlement_copy_evidence','settlement','redact_finance_copy_body'),
 ('settlement_audit_body','public','portfolio_settlement_audit_log','id',ARRAY['old_values','new_values','reason'],'ediel.retention.settlement_copy_evidence','settlement_child','redact_finance_copy_body'),
 ('settlement_invoice_binding_body','public','portfolio_settlement_invoice_bindings','id',ARRAY['settlement_snapshot'],'ediel.retention.settlement_copy_evidence','settlement_child','redact_finance_copy_body');
CREATE TABLE gridex_ediel_retention.finance_decisions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),
 retention_class text NOT NULL REFERENCES gridex_ediel_retention.finance_class_catalog(retention_class),target_id text NOT NULL,
 source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),target_hash text NOT NULL CHECK(target_hash~'^[a-f0-9]{64}$'),scope_hash text NOT NULL CHECK(scope_hash~'^[a-f0-9]{64}$'),
 document_bytes bytea NOT NULL CHECK(octet_length(document_bytes) BETWEEN 1 AND 1048576),document_hash text NOT NULL CHECK(document_hash=encode(sha256(document_bytes),'hex')),
 issuer_receipt jsonb,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(company_id,retention_class,target_id,target_hash,scope_hash,document_hash));
CREATE TABLE gridex_ediel_retention.finance_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),decision_id uuid NOT NULL REFERENCES gridex_ediel_retention.finance_decisions(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),outcome text NOT NULL CHECK(outcome IN('approved','held','rejected')),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.finance_revocations(decision_id uuid PRIMARY KEY REFERENCES gridex_ediel_retention.finance_decisions(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.finance_tombstones(retention_class text NOT NULL REFERENCES gridex_ediel_retention.finance_class_catalog(retention_class),target_id text NOT NULL,company_id uuid NOT NULL,decision_id uuid NOT NULL REFERENCES gridex_ediel_retention.finance_decisions(id),review_id uuid NOT NULL REFERENCES gridex_ediel_retention.finance_reviews(id),source_hash text NOT NULL,target_hash text NOT NULL,scope_hash text NOT NULL,byte_length bigint NOT NULL CHECK(byte_length>0),actor_user_id uuid NOT NULL REFERENCES auth.users(id),journal_retain_until timestamptz NOT NULL,journal_purpose_reference text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(retention_class,target_id));
CREATE TABLE gridex_ediel_retention.finance_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),retention_class text NOT NULL,target_id text NOT NULL,actor_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(retention_class,target_id) REFERENCES gridex_ediel_retention.finance_tombstones(retention_class,target_id),UNIQUE(retention_class,target_id));
DO $$DECLARE t text;spec record;column_name text;BEGIN
 FOREACH t IN ARRAY ARRAY['finance_class_catalog','finance_decisions','finance_reviews','finance_revocations','finance_tombstones','finance_events'] LOOP
 EXECUTE format('ALTER TABLE gridex_ediel_retention.%I OWNER TO gridex_ediel_retention_owner',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_ediel_retention.%I FROM PUBLIC,anon,authenticated,service_role',t);EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);EXECUTE format('CREATE TRIGGER no_truncate BEFORE TRUNCATE ON gridex_ediel_retention.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);END LOOP;
 FOR spec IN SELECT * FROM gridex_ediel_retention.finance_class_catalog LOOP
  IF to_regclass(format('%I.%I',spec.source_schema,spec.source_table)) IS NULL THEN RAISE EXCEPTION 'finance_retention_actual_table_required: %',spec.source_table;END IF;
  FOREACH column_name IN ARRAY spec.body_columns LOOP IF NOT EXISTS(SELECT FROM pg_attribute WHERE attrelid=format('%I.%I',spec.source_schema,spec.source_table)::regclass AND attname=column_name AND NOT attisdropped AND atttypid IN('jsonb'::regtype,'text'::regtype)) THEN RAISE EXCEPTION 'finance_retention_actual_body_column_required: %.%',spec.source_table,column_name;END IF;END LOOP;
  EXECUTE format('GRANT USAGE ON SCHEMA %I TO gridex_ediel_retention_owner',spec.source_schema);EXECUTE format('GRANT SELECT,UPDATE ON %I.%I TO gridex_ediel_retention_owner',spec.source_schema,spec.source_table);
 END LOOP;END$$;
GRANT SELECT,UPDATE ON public.customer_contracts,public.ediel_messages TO gridex_ediel_retention_owner;
CREATE FUNCTION gridex_ediel_retention.finance_actor_v1(c uuid,actor uuid,k text,op text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE key text;BEGIN
 SELECT permission_key INTO STRICT key FROM gridex_ediel_retention.finance_class_catalog WHERE retention_class=k;
 IF op='ediel.retention.read' THEN PERFORM gridex_ediel_retention.record_read_actor_v1(c,actor);ELSE PERFORM gridex_ediel_retention.actor_v1(c,actor,op);END IF;
 IF gridex_ediel_retention.permission_v1(c,actor,key) IS NOT TRUE THEN RAISE EXCEPTION 'finance_retention_current_exact_class_required' USING ERRCODE='42501';END IF;END$$;
CREATE FUNCTION gridex_ediel_retention.finance_basis_v1(c uuid,k text,target text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE spec gridex_ediel_retention.finance_class_catalog%rowtype;r jsonb;body jsonb;underlay jsonb;invoice jsonb;item jsonb;settlement jsonb;ref uuid;customer uuid;start_at timestamptz;end_at timestamptz;scope jsonb;included_ids uuid[];closed boolean;source_bound boolean:=false;original_sha text;node record;scope_company uuid;scope_customer uuid;included_ref uuid;finance_graph jsonb;BEGIN
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.finance_class_catalog WHERE retention_class=k;
 IF target!~'^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' AND NOT(spec.source_table='portfolio_settlement_audit_log' AND target~'^[1-9][0-9]{0,18}$') THEN RAISE EXCEPTION 'finance_retention_actual_selector_required';END IF;
 IF EXISTS(SELECT FROM gridex_ediel_retention.finance_tombstones WHERE retention_class=k AND target_id=target AND company_id=c) THEN RAISE EXCEPTION 'finance_copy_retention_tombstoned';END IF;
 EXECUTE format('SELECT to_jsonb(x) FROM %I.%I x WHERE %I::text=$1 AND company_id=$2 FOR SHARE',spec.source_schema,spec.source_table,spec.id_column) INTO r USING target,c;
 IF r IS NULL THEN RAISE EXCEPTION 'finance_retention_actual_source_required';END IF;
 SELECT jsonb_object_agg(col,r->col) INTO body FROM unnest(spec.body_columns)col;
 IF octet_length(body::text) NOT BETWEEN 1 AND 20971520 OR body@>'{"retentionUnavailable":true}' THEN RAISE EXCEPTION 'finance_retention_actual_body_required';END IF;
 -- All period selectors come from real native relationships, never policy JSON.
 IF spec.source_kind='invoice' THEN invoice:=r;
 ELSIF spec.source_kind='invoice_line' THEN SELECT to_jsonb(x) INTO invoice FROM public.customer_invoices x WHERE id=(r->>'invoice_id')::uuid AND company_id=c FOR SHARE;
 ELSIF spec.source_kind='item' THEN item:=r;
 ELSIF spec.source_kind IN('item_child','provider_event') THEN ref:=coalesce(r->>'invoice_export_item_id',r->>'matched_invoice_export_item_id')::uuid;SELECT to_jsonb(x) INTO item FROM public.invoice_export_items x WHERE id=ref AND company_id=c FOR SHARE;
 ELSIF spec.source_kind='settlement' THEN settlement:=r;
 ELSIF spec.source_kind='settlement_child' THEN ref:=coalesce(r->>'settlement_id',r->>'portfolio_monthly_settlement_id')::uuid;SELECT to_jsonb(x) INTO settlement FROM public.portfolio_monthly_settlements x WHERE id=ref AND company_id=c FOR SHARE;END IF;
 IF spec.source_kind IN('underlay','underlay_child') THEN ref:=CASE WHEN spec.source_kind='underlay' THEN (r->>spec.id_column)::uuid ELSE (r->>'billing_underlay_id')::uuid END;
 ELSE ref:=coalesce(invoice->>'billing_underlay_id',item->>'billing_underlay_id',r->>'billing_underlay_id')::uuid;END IF;
 IF ref IS NOT NULL THEN SELECT to_jsonb(x) INTO underlay FROM public.billing_underlays x WHERE id=ref AND company_id=c FOR SHARE;END IF;
 IF underlay IS NOT NULL THEN
  customer:=(underlay->>'customer_id')::uuid;start_at:=(underlay->>'billing_period_start')::timestamptz;end_at:=(underlay->>'billing_period_end')::timestamptz;
  SELECT source_basis_hash INTO original_sha FROM gridex_billing_source.underlay_bindings WHERE underlay_id=ref AND company_id=c AND (source_basis_hash=encode(sha256(convert_to(source_basis::text,'UTF8')),'hex') OR EXISTS(SELECT FROM gridex_ediel_retention.finance_tombstones t WHERE t.retention_class='billing_underlay_source_body' AND t.target_id=ref::text AND t.company_id=c));source_bound:=original_sha IS NOT NULL;
 ELSIF settlement IS NOT NULL THEN start_at:=(settlement->>'delivery_month')::date::timestamptz;end_at:=start_at+interval '1 month';original_sha:=settlement->>'calculation_snapshot_sha256';source_bound:=settlement->>'status'='locked' AND (original_sha=encode(sha256(convert_to((settlement->'calculation_snapshot')::text,'UTF8')),'hex') OR EXISTS(SELECT FROM gridex_ediel_retention.finance_tombstones t WHERE t.retention_class='settlement_calculation_body' AND t.target_id=settlement->>'id' AND t.company_id=c));
 ELSIF spec.source_kind='run' AND r->>'billing_month'~'^\d{4}-\d{2}$' THEN
  start_at:=(r->>'billing_month'||'-01')::date::timestamptz;end_at:=start_at+interval '1 month';
  SELECT count(*)>0 AND bool_and(b.underlay_id IS NOT NULL AND (b.source_basis_hash=encode(sha256(convert_to(b.source_basis::text,'UTF8')),'hex') OR EXISTS(SELECT FROM gridex_ediel_retention.finance_tombstones t WHERE t.company_id=c AND t.retention_class='billing_underlay_source_body' AND t.target_id=b.underlay_id::text))),encode(sha256(convert_to(coalesce(jsonb_agg(jsonb_build_object('itemId',i.id,'underlayId',i.billing_underlay_id,'sourceHash',b.source_basis_hash) ORDER BY i.id),'[]')::text,'UTF8')),'hex') INTO source_bound,original_sha FROM public.invoice_export_items i LEFT JOIN gridex_billing_source.underlay_bindings b ON b.underlay_id=i.billing_underlay_id AND b.company_id=c WHERE i.company_id=c AND i.export_run_id=(r->>'id')::uuid;
 END IF;
 IF start_at IS NULL OR end_at IS NULL OR NOT isfinite(start_at) OR NOT isfinite(end_at) OR end_at<=start_at THEN RAISE EXCEPTION 'finance_retention_native_exact_period_required';END IF;
 LOCK TABLE public.customers,public.customer_supply_periods,public.customer_invoices,public.invoice_export_items,public.invoice_export_attempts IN SHARE ROW EXCLUSIVE MODE;
 IF customer IS NULL THEN SELECT coalesce(array_agg(id ORDER BY id),ARRAY[]::uuid[]) INTO included_ids FROM public.customers WHERE company_id=c;ELSE included_ids:=ARRAY[customer];END IF;
 -- Decode actual stored native copy references. A known foreign included
 -- customer/contract/message cannot be hidden by the row's customer selector.
 FOR node IN SELECT * FROM gridex_ediel_retention.process_nodes_v1(body) LOOP
  IF node.key IN('companyId','company_id') AND jsonb_typeof(node.value)='string' AND (node.value#>>'{}') IS DISTINCT FROM c::text THEN RAISE EXCEPTION 'finance_retention_foreign_included_scope';END IF;
  IF node.key IN('customerId','customer_id','contractId','contract_id','customer_contract_id','sourceMessageId','source_message_id','messageId','originalMessageId') AND jsonb_typeof(node.value)='string' THEN
   BEGIN included_ref:=(node.value#>>'{}')::uuid;EXCEPTION WHEN invalid_text_representation THEN CONTINUE;END;
   scope_company:=NULL;scope_customer:=NULL;
   IF node.key IN('customerId','customer_id') THEN SELECT company_id,id INTO scope_company,scope_customer FROM public.customers WHERE id=included_ref;
   ELSIF node.key IN('contractId','contract_id','customer_contract_id') THEN SELECT company_id,customer_id INTO scope_company,scope_customer FROM public.customer_contracts WHERE id=included_ref;
   ELSE SELECT company_id,customer_id INTO scope_company,scope_customer FROM public.ediel_messages WHERE id=included_ref;END IF;
   IF scope_company IS NOT NULL AND scope_company IS DISTINCT FROM c THEN RAISE EXCEPTION 'finance_retention_foreign_included_scope';END IF;
  END IF;
 END LOOP;
 -- Free text and provider/aggregate copies are not an exhaustive caller list.
 -- Qualify the conservative real company population and its open finance graph.
 SELECT coalesce(array_agg(id ORDER BY id),ARRAY[]::uuid[]) INTO included_ids FROM public.customers WHERE company_id=c;
 IF cardinality(included_ids)>10000 THEN RAISE EXCEPTION 'finance_retention_included_scope_bound';END IF;
 IF EXISTS(SELECT FROM public.customers WHERE id=ANY(included_ids) AND company_id IS DISTINCT FROM c) THEN RAISE EXCEPTION 'finance_retention_foreign_included_scope';END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('customerId',x.id,'status',x.status,'supplies',(SELECT coalesce(jsonb_agg(to_jsonb(s) ORDER BY s.id),'[]') FROM public.customer_supply_periods s WHERE s.company_id=c AND s.customer_id=x.id),'invoices',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',i.id,'status',i.status) ORDER BY i.id),'[]') FROM public.customer_invoices i WHERE i.company_id=c AND i.customer_id=x.id)) ORDER BY x.id),'[]'),coalesce(bool_and(x.status='archived'),true) INTO scope,closed FROM public.customers x WHERE x.company_id=c AND id=ANY(included_ids);
 closed:=closed AND source_bound AND end_at<=clock_timestamp()
 AND NOT EXISTS(SELECT FROM public.customer_supply_periods s WHERE s.company_id=c AND s.customer_id=ANY(included_ids) AND s.status NOT IN('cancelled','rejected','terminated','ended','closed','inactive') AND (coalesce(s.actual_end_date,s.end_date) IS NULL OR coalesce(s.actual_end_date,s.end_date)>=current_date))
 AND NOT EXISTS(SELECT FROM public.customer_invoices i WHERE i.company_id=c AND i.customer_id=ANY(included_ids) AND i.status NOT IN('paid','cancelled','void','credited'))
 AND NOT EXISTS(SELECT FROM public.invoice_export_items i WHERE i.company_id=c AND i.customer_id=ANY(included_ids) AND i.status IN('pending','failed','retrying'))
 AND NOT EXISTS(SELECT FROM public.invoice_export_attempts a JOIN public.invoice_export_items i ON i.id=a.invoice_export_item_id WHERE i.company_id=c AND i.customer_id=ANY(included_ids) AND a.finished_at IS NULL);
 SELECT coalesce(jsonb_agg(jsonb_build_object('itemId',i.id,'customerId',i.customer_id,'underlayId',i.billing_underlay_id,'runId',i.export_run_id,'status',i.status,'sourceHash',b.source_basis_hash,'attempts',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',a.id,'finishedAt',a.finished_at) ORDER BY a.id),'[]') FROM public.invoice_export_attempts a WHERE a.company_id=c AND a.invoice_export_item_id=i.id)) ORDER BY i.id),'[]') INTO finance_graph FROM public.invoice_export_items i LEFT JOIN gridex_billing_source.underlay_bindings b ON b.underlay_id=i.billing_underlay_id AND b.company_id=c WHERE i.company_id=c;
 RETURN jsonb_build_object('retentionClass',k,'targetId',target,'sourceTable',spec.source_schema||'.'||spec.source_table,'bodyColumns',spec.body_columns,'sourceHash',encode(sha256(convert_to(body::text,'UTF8')),'hex'),'targetHash',encode(sha256(convert_to(r::text,'UTF8')),'hex'),'scopeHash',encode(sha256(convert_to(jsonb_build_object('companyId',c,'customers',scope,'financialGraph',finance_graph,'periodStart',start_at,'periodEnd',end_at,'sourceBound',source_bound,'originalProducerHash',original_sha)::text,'UTF8')),'hex'),'periodStart',start_at,'periodEnd',end_at,'originalProducerHash',original_sha,'byteLength',octet_length(body::text),'includedCustomers',included_ids,'allIncludedScopesClosed',closed,'sourceBound',source_bound,'complete',false,'authority','none');END$$;
CREATE FUNCTION gridex_ediel_retention.finance_receipt_v1(d gridex_ediel_retention.finance_decisions) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE issuer gridex_ediel_retention.issuers%rowtype;p jsonb;bytes bytea;issued timestamptz;expires timestamptz;deadline timestamptz;journal_end timestamptz;operation text;BEGIN
 IF jsonb_typeof(d.issuer_receipt) IS DISTINCT FROM 'object' OR coalesce(d.issuer_receipt->>'signatureHex','')!~'^[a-f0-9]{64}$' OR length(coalesce(d.issuer_receipt->>'payloadBase64','')) NOT BETWEEN 1 AND 32768 THEN RETURN NULL;END IF;
 SELECT * INTO issuer FROM gridex_ediel_retention.issuers WHERE id=(d.issuer_receipt->>'issuerId')::uuid AND company_id=d.company_id FOR SHARE;
 IF issuer.id IS NULL OR now()<issuer.valid_from OR now()>=issuer.valid_to OR EXISTS(SELECT FROM gridex_ediel_retention.issuer_revocations WHERE issuer_id=issuer.id) OR EXISTS(SELECT FROM gridex_ediel_retention.finance_revocations WHERE decision_id=d.id) THEN RETURN NULL;END IF;
 bytes:=decode(d.issuer_receipt->>'payloadBase64','base64');IF encode(gridex_requested_changes.receipt_hmac_sha256_v1(bytes,issuer.signing_key),'hex') IS DISTINCT FROM d.issuer_receipt->>'signatureHex' THEN RETURN NULL;END IF;
 p:=convert_from(bytes,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;deadline:=(p->>'retainUntil')::timestamptz;journal_end:=(p->>'journalRetainUntil')::timestamptz;
 SELECT x.operation INTO STRICT operation FROM gridex_ediel_retention.finance_class_catalog x WHERE retention_class=d.retention_class;
 IF p->>'format' IS DISTINCT FROM 'ediel_finance_copy_retention_policy_v1' OR p->>'retentionClass' IS DISTINCT FROM d.retention_class OR p->>'targetId' IS DISTINCT FROM d.target_id OR p->>'companyId' IS DISTINCT FROM d.company_id::text
 OR p->>'sourceTable' IS DISTINCT FROM (SELECT source_schema||'.'||source_table FROM gridex_ediel_retention.finance_class_catalog WHERE retention_class=d.retention_class)
 OR p->>'sourceHash' IS DISTINCT FROM d.source_hash OR p->>'targetHash' IS DISTINCT FROM d.target_hash OR p->>'scopeHash' IS DISTINCT FROM d.scope_hash OR p->>'documentHash' IS DISTINCT FROM d.document_hash OR p->>'operation' IS DISTINCT FROM operation
 OR p->>'issuerLegalReference' IS DISTINCT FROM issuer.legal_reference OR nullif(p->>'legalBasisReference','') IS NULL OR nullif(p->>'journalPurposeReference','') IS NULL OR p->>'accessRevocationRequired' IS DISTINCT FROM 'true'
 OR isfinite(issued) IS DISTINCT FROM true OR isfinite(expires) IS DISTINCT FROM true OR isfinite(deadline) IS DISTINCT FROM true OR isfinite(journal_end) IS DISTINCT FROM true OR journal_end<=now() OR issued>now() OR expires<=now() OR issued<issuer.valid_from OR expires>issuer.valid_to THEN RETURN NULL;END IF;RETURN p;
EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN NULL;END$$;
CREATE FUNCTION public.ediel_finance_copy_retention_basis_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN PERFORM gridex_ediel_retention.finance_actor_v1(p_company_id,p_actor_user_id,p_retention_class,CASE WHEN gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'ediel.retention.read') THEN 'ediel.retention.read' ELSE 'ediel.retention.review' END);RETURN gridex_ediel_retention.finance_basis_v1(p_company_id,p_retention_class,p_target_id);END$$;
CREATE FUNCTION public.ediel_submit_finance_copy_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id text,p_document_base64 text,p_issuer_receipt jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE basis jsonb;bytes bytea;d gridex_ediel_retention.finance_decisions%rowtype;BEGIN
 PERFORM gridex_ediel_retention.finance_actor_v1(p_company_id,p_actor_user_id,p_retention_class,'ediel.retention.submit');basis:=gridex_ediel_retention.finance_basis_v1(p_company_id,p_retention_class,p_target_id);
 IF length(p_document_base64)>1398104 THEN RAISE EXCEPTION 'finance_retention_document_limit';END IF;bytes:=decode(p_document_base64,'base64');IF octet_length(bytes) NOT BETWEEN 1 AND 1048576 THEN RAISE EXCEPTION 'finance_retention_document_required';END IF;
 INSERT INTO gridex_ediel_retention.finance_decisions(company_id,retention_class,target_id,source_hash,target_hash,scope_hash,document_bytes,document_hash,issuer_receipt,submitted_by) VALUES(p_company_id,p_retention_class,p_target_id,basis->>'sourceHash',basis->>'targetHash',basis->>'scopeHash',bytes,encode(sha256(bytes),'hex'),p_issuer_receipt,p_actor_user_id) ON CONFLICT DO NOTHING;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.finance_decisions WHERE company_id=p_company_id AND retention_class=p_retention_class AND target_id=p_target_id AND target_hash=basis->>'targetHash' AND scope_hash=basis->>'scopeHash' AND document_hash=encode(sha256(bytes),'hex') FOR SHARE;
 IF d.issuer_receipt IS DISTINCT FROM p_issuer_receipt THEN RAISE EXCEPTION 'finance_retention_original_receipt_conflict';END IF;
 INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'finance_copy_retention',d.id,'ediel.retention.finance_submitted',jsonb_build_object('retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'scopeHash',d.scope_hash));
 RETURN jsonb_build_object('status','submitted','decisionId',d.id,'retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'targetHash',d.target_hash,'scopeHash',d.scope_hash,'documentHash',d.document_hash,'issuerQualified',gridex_ediel_retention.finance_receipt_v1(d) IS NOT NULL);END$$;
CREATE FUNCTION public.ediel_read_finance_copy_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.finance_decisions%rowtype;p jsonb;BEGIN
 SELECT * INTO STRICT d FROM gridex_ediel_retention.finance_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR SHARE;PERFORM gridex_ediel_retention.finance_actor_v1(p_company_id,p_actor_user_id,d.retention_class,CASE WHEN gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'ediel.retention.read') THEN 'ediel.retention.read' ELSE 'ediel.retention.review' END);p:=gridex_ediel_retention.finance_receipt_v1(d);
 RETURN jsonb_build_object('decisionId',d.id,'retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'targetHash',d.target_hash,'scopeHash',d.scope_hash,'documentHash',d.document_hash,'documentBase64',encode(d.document_bytes,'base64'),'submittedBy',d.submitted_by,'issuerQualified',p IS NOT NULL,'retainUntil',p->>'retainUntil','journalRetainUntil',p->>'journalRetainUntil','journalPurposeReference',p->>'journalPurposeReference');END$$;
CREATE FUNCTION public.ediel_review_finance_copy_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid,p_outcome text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.finance_decisions%rowtype;basis jsonb;outcome text;r uuid;BEGIN
 SELECT * INTO STRICT d FROM gridex_ediel_retention.finance_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;PERFORM gridex_ediel_retention.finance_actor_v1(p_company_id,p_actor_user_id,d.retention_class,'ediel.retention.review');
 IF p_outcome NOT IN('approve','hold','reject') OR nullif(btrim(p_reason),'') IS NULL OR length(p_reason)>4000 THEN RAISE EXCEPTION 'finance_retention_review_shape_required';END IF;IF p_outcome='approve' AND d.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'finance_retention_separate_reviewer_required';END IF;
 basis:=gridex_ediel_retention.finance_basis_v1(p_company_id,d.retention_class,d.target_id);outcome:=CASE WHEN p_outcome='reject' THEN 'rejected' WHEN p_outcome='approve' AND gridex_ediel_retention.finance_receipt_v1(d) IS NOT NULL AND basis->>'sourceHash'=d.source_hash AND basis->>'targetHash'=d.target_hash AND basis->>'scopeHash'=d.scope_hash AND basis->>'allIncludedScopesClosed'='true' AND (gridex_ediel_retention.finance_receipt_v1(d))->>'periodStart'=basis->>'periodStart' AND (gridex_ediel_retention.finance_receipt_v1(d))->>'periodEnd'=basis->>'periodEnd' THEN 'approved' ELSE 'held' END;
 INSERT INTO gridex_ediel_retention.finance_reviews(decision_id,actor_user_id,outcome,reason) VALUES(d.id,p_actor_user_id,outcome,p_reason) RETURNING id INTO r;INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'finance_copy_retention',d.id,'ediel.retention.finance_reviewed',jsonb_build_object('reviewId',r,'outcome',outcome));RETURN jsonb_build_object('status',outcome,'decisionId',d.id,'reviewId',r);END$$;
CREATE FUNCTION public.ediel_revoke_finance_copy_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid,p_reason text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.finance_decisions%rowtype;BEGIN SELECT * INTO STRICT d FROM gridex_ediel_retention.finance_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;PERFORM gridex_ediel_retention.finance_actor_v1(p_company_id,p_actor_user_id,d.retention_class,'ediel.retention.review');IF nullif(btrim(p_reason),'') IS NULL OR length(p_reason)>4000 THEN RAISE EXCEPTION 'finance_retention_revoke_scope_required';END IF;INSERT INTO gridex_ediel_retention.finance_revocations(decision_id,actor_user_id,reason) VALUES(p_decision_id,p_actor_user_id,p_reason) ON CONFLICT DO NOTHING;END$$;
CREATE FUNCTION gridex_ediel_retention.finance_revocation_lock_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN PERFORM id FROM gridex_ediel_retention.finance_decisions WHERE id=NEW.decision_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'finance_retention_revocation_target_required';END IF;RETURN NEW;END$$;
CREATE TRIGGER finance_retention_revocation_lock BEFORE INSERT ON gridex_ediel_retention.finance_revocations FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.finance_revocation_lock_v1();
CREATE FUNCTION gridex_ediel_retention.finance_redacted_v1(k text,oldrow jsonb,hash text) RETURNS jsonb LANGUAGE plpgsql SET search_path=pg_catalog AS $$DECLARE spec gridex_ediel_retention.finance_class_catalog%rowtype;col text;type oid;marker jsonb:=jsonb_build_object('retentionUnavailable',true,'sourceHash',hash,'complete',false,'authority','none');result jsonb:=oldrow;BEGIN SELECT * INTO STRICT spec FROM gridex_ediel_retention.finance_class_catalog WHERE retention_class=k;FOREACH col IN ARRAY spec.body_columns LOOP SELECT atttypid INTO STRICT type FROM pg_attribute WHERE attrelid=format('%I.%I',spec.source_schema,spec.source_table)::regclass AND attname=col;result:=jsonb_set(result,ARRAY[col],CASE WHEN type='jsonb'::regtype THEN marker ELSE to_jsonb(marker::text) END);END LOOP;RETURN result;END$$;
CREATE FUNCTION public.ediel_is_qualified_finance_retention_transition_v1(p_schema text,p_table text,p_old jsonb,p_new jsonb) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec gridex_ediel_retention.finance_class_catalog%rowtype;t gridex_ediel_retention.finance_tombstones%rowtype;BEGIN SELECT * INTO spec FROM gridex_ediel_retention.finance_class_catalog WHERE source_schema=p_schema AND source_table=p_table;IF NOT FOUND THEN RETURN false;END IF;SELECT * INTO t FROM gridex_ediel_retention.finance_tombstones WHERE retention_class=spec.retention_class AND target_id=p_old->>spec.id_column;RETURN t.target_id IS NOT NULL AND t.company_id::text=p_old->>'company_id' AND t.target_hash=encode(sha256(convert_to(p_old::text,'UTF8')),'hex') AND p_new=gridex_ediel_retention.finance_redacted_v1(spec.retention_class,p_old,t.source_hash);END$$;
CREATE FUNCTION gridex_ediel_retention.finance_target_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec gridex_ediel_retention.finance_class_catalog%rowtype;r jsonb;BEGIN SELECT * INTO STRICT spec FROM gridex_ediel_retention.finance_class_catalog WHERE source_schema=TG_TABLE_SCHEMA AND source_table=TG_TABLE_NAME;r:=CASE WHEN TG_OP='INSERT' THEN to_jsonb(NEW) ELSE to_jsonb(OLD) END;IF EXISTS(SELECT FROM gridex_ediel_retention.finance_tombstones WHERE retention_class=spec.retention_class AND target_id=r->>spec.id_column) AND NOT(TG_OP='UPDATE' AND public.ediel_is_qualified_finance_retention_transition_v1(TG_TABLE_SCHEMA,TG_TABLE_NAME,to_jsonb(OLD),to_jsonb(NEW))) THEN RAISE EXCEPTION 'finance_copy_retention_tombstoned';END IF;RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;END$$;
-- Clone only actual immutable guard bindings, not their owners or ACLs. The
-- bounded exception permits the one native authorized OLD/NEW body transition.
DO $$DECLARE spec record;f record;name text;body text;definition text;setting text;BEGIN FOR spec IN SELECT * FROM gridex_ediel_retention.finance_class_catalog LOOP
 FOR f IN SELECT t.oid trigger_oid,t.tgname,p.prosrc,p.proowner,p.proconfig,p.prosecdef FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid WHERE t.tgrelid=format('%I.%I',spec.source_schema,spec.source_table)::regclass AND NOT t.tgisinternal AND (t.tgtype & 2)=2 AND (t.tgtype & 16)=16 AND (p.prosrc~*'immutable|append.only|protected|already.*sent|locked.*settlement|new[.]updated_at|new[.]updated_by') LOOP
 IF f.prosrc!~*'\mBEGIN\M' THEN RAISE EXCEPTION 'finance_retention_guard_source_review_required';END IF;name:='finance_guard_'||f.trigger_oid;body:=regexp_replace(f.prosrc,'\mBEGIN\M','BEGIN IF TG_OP=''UPDATE'' AND public.ediel_is_qualified_finance_retention_transition_v1(TG_TABLE_SCHEMA,TG_TABLE_NAME,to_jsonb(OLD),to_jsonb(NEW)) THEN RETURN NEW;END IF;','i');EXECUTE format('CREATE FUNCTION gridex_ediel_retention.%I() RETURNS trigger LANGUAGE plpgsql SECURITY %s SET search_path=pg_catalog AS %L',name,CASE WHEN f.prosecdef THEN 'DEFINER' ELSE 'INVOKER' END,body);FOREACH setting IN ARRAY coalesce(f.proconfig,ARRAY[]::text[]) LOOP EXECUTE format('ALTER FUNCTION gridex_ediel_retention.%I() SET %I TO %L',name,split_part(setting,'=',1),substring(setting from position('=' in setting)+1));END LOOP;EXECUTE format('ALTER FUNCTION gridex_ediel_retention.%I() OWNER TO %I',name,(SELECT rolname FROM pg_roles WHERE oid=f.proowner));EXECUTE format('REVOKE ALL ON FUNCTION gridex_ediel_retention.%I() FROM PUBLIC,anon,authenticated,service_role',name);EXECUTE format('GRANT EXECUTE ON FUNCTION public.ediel_is_qualified_finance_retention_transition_v1(text,text,jsonb,jsonb) TO %I',(SELECT rolname FROM pg_roles WHERE oid=f.proowner));definition:=pg_get_triggerdef(f.trigger_oid);EXECUTE format('DROP TRIGGER %I ON %I.%I',f.tgname,spec.source_schema,spec.source_table);EXECUTE regexp_replace(definition,'EXECUTE (FUNCTION|PROCEDURE) .*$',format('EXECUTE FUNCTION gridex_ediel_retention.%I()',name));END LOOP;
 EXECUTE format('CREATE TRIGGER zz_finance_retention_target BEFORE INSERT OR UPDATE OR DELETE ON %I.%I FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.finance_target_guard_v1()',spec.source_schema,spec.source_table);END LOOP;END$$;
-- The existing native financial audit owner must not re-copy the old body
-- solely because this exact class was lawfully redacted. The class event and
-- signed finite journal purpose above retain its qualified operation receipt.
DO $$DECLARE body text;definition text;BEGIN
 IF to_regprocedure('public.gridex_audit_portfolio_settlement_write()') IS NOT NULL THEN
  SELECT prosrc INTO STRICT body FROM pg_proc WHERE oid='public.gridex_audit_portfolio_settlement_write()'::regprocedure;definition:=pg_get_functiondef('public.gridex_audit_portfolio_settlement_write()'::regprocedure);
  IF body!~*'\mBEGIN\M' THEN RAISE EXCEPTION 'finance_retention_actual_audit_owner_review_required';END IF;
  body:=regexp_replace(body,'\mBEGIN\M','BEGIN IF TG_OP=''UPDATE'' AND public.ediel_is_qualified_finance_retention_transition_v1(TG_TABLE_SCHEMA,TG_TABLE_NAME,to_jsonb(OLD),to_jsonb(NEW)) THEN RETURN NEW;END IF;','i');EXECUTE replace(definition,(SELECT prosrc FROM pg_proc WHERE oid='public.gridex_audit_portfolio_settlement_write()'::regprocedure),body);
 END IF;END$$;
CREATE FUNCTION public.ediel_purge_finance_copy_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.finance_decisions%rowtype;t gridex_ediel_retention.finance_tombstones%rowtype;r gridex_ediel_retention.finance_reviews%rowtype;spec gridex_ediel_retention.finance_class_catalog%rowtype;p jsonb;basis jsonb;oldrow jsonb;redacted jsonb;cols text;BEGIN
 SELECT * INTO STRICT d FROM gridex_ediel_retention.finance_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;PERFORM gridex_ediel_retention.finance_actor_v1(p_company_id,p_actor_user_id,d.retention_class,'ediel.retention.purge');SELECT * INTO t FROM gridex_ediel_retention.finance_tombstones WHERE retention_class=d.retention_class AND target_id=d.target_id;IF FOUND THEN IF t.decision_id IS DISTINCT FROM d.id OR t.company_id IS DISTINCT FROM p_company_id THEN RAISE EXCEPTION 'finance_retention_replay_conflict';END IF;RETURN jsonb_build_object('status','redacted','retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'byteLength',t.byte_length,'replay',true);END IF;
 SELECT * INTO r FROM gridex_ediel_retention.finance_reviews WHERE decision_id=d.id ORDER BY created_at DESC,id DESC LIMIT 1;SELECT * INTO STRICT spec FROM gridex_ediel_retention.finance_class_catalog WHERE retention_class=d.retention_class;
 IF r.outcome IS DISTINCT FROM 'approved' OR r.actor_user_id=d.submitted_by OR public.ediel_retention_lock_auth_actor_v1(r.actor_user_id) IS NOT TRUE OR gridex_ediel_retention.permission_v1(p_company_id,r.actor_user_id,spec.permission_key) IS NOT TRUE OR gridex_ediel_retention.permission_v1(p_company_id,r.actor_user_id,'ediel.retention.review') IS NOT TRUE THEN RETURN jsonb_build_object('status','held','missing',ARRAY['current_separate_exact_class_review']);END IF;
 p:=gridex_ediel_retention.finance_receipt_v1(d);IF p IS NULL OR (p->>'retainUntil')::timestamptz>clock_timestamp() THEN RETURN jsonb_build_object('status','held','missing',ARRAY['current_exact_class_legal_deadline']);END IF;
 basis:=gridex_ediel_retention.finance_basis_v1(p_company_id,d.retention_class,d.target_id);IF basis->>'sourceHash' IS DISTINCT FROM d.source_hash OR basis->>'targetHash' IS DISTINCT FROM d.target_hash OR basis->>'scopeHash' IS DISTINCT FROM d.scope_hash OR basis->>'allIncludedScopesClosed' IS DISTINCT FROM 'true' OR p->>'periodStart' IS DISTINCT FROM basis->>'periodStart' OR p->>'periodEnd' IS DISTINCT FROM basis->>'periodEnd' THEN RETURN jsonb_build_object('status','held','missing',ARRAY['unchanged_source_native_period_all_scopes_closed']);END IF;
 LOCK TABLE public.customer_portal_accounts,public.customer_portal_claims IN SHARE ROW EXCLUSIVE MODE;UPDATE public.customer_portal_accounts SET status='revoked',is_active=false,updated_at=clock_timestamp() WHERE company_id=p_company_id AND customer_id IN(SELECT value::uuid FROM jsonb_array_elements_text(basis->'includedCustomers'));UPDATE public.customer_portal_claims SET status='revoked',updated_at=clock_timestamp() WHERE company_id=p_company_id AND customer_id IN(SELECT value::uuid FROM jsonb_array_elements_text(basis->'includedCustomers'));
 INSERT INTO gridex_ediel_retention.finance_tombstones(retention_class,target_id,company_id,decision_id,review_id,source_hash,target_hash,scope_hash,byte_length,actor_user_id,journal_retain_until,journal_purpose_reference) VALUES(d.retention_class,d.target_id,p_company_id,d.id,r.id,d.source_hash,d.target_hash,d.scope_hash,(basis->>'byteLength')::bigint,p_actor_user_id,(p->>'journalRetainUntil')::timestamptz,p->>'journalPurposeReference');
 EXECUTE format('SELECT to_jsonb(x) FROM %I.%I x WHERE %I::text=$1 AND company_id=$2 FOR UPDATE',spec.source_schema,spec.source_table,spec.id_column) INTO oldrow USING d.target_id,p_company_id;redacted:=gridex_ediel_retention.finance_redacted_v1(d.retention_class,oldrow,d.source_hash);SELECT string_agg(format('%I',v),',') INTO cols FROM unnest(spec.body_columns)v;EXECUTE format('UPDATE %I.%I SET (%s)=(SELECT %s FROM jsonb_populate_record(NULL::%I.%I,$1)) WHERE %I::text=$2 AND company_id=$3',spec.source_schema,spec.source_table,cols,cols,spec.source_schema,spec.source_table,spec.id_column) USING redacted,d.target_id,p_company_id;
 INSERT INTO gridex_ediel_retention.finance_events(retention_class,target_id,actor_user_id) VALUES(d.retention_class,d.target_id,p_actor_user_id);INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'finance_copy_retention',d.id,'ediel.retention.finance_redacted',jsonb_build_object('retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'scopeHash',d.scope_hash,'journalRetainUntil',p->>'journalRetainUntil','journalPurposeReference',p->>'journalPurposeReference','complete',false,'authority','none'));RETURN jsonb_build_object('status','redacted','retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'byteLength',(basis->>'byteLength')::bigint,'replay',false);END$$;
CREATE FUNCTION public.ediel_require_finance_copy_available_v1(p_company_id uuid,p_retention_class text,p_target_id text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF EXISTS(SELECT FROM gridex_ediel_retention.finance_tombstones WHERE company_id=p_company_id AND retention_class=p_retention_class AND target_id=p_target_id) THEN RAISE EXCEPTION 'finance_copy_retention_tombstoned' USING ERRCODE='23514';END IF;END$$;
CREATE FUNCTION public.ediel_require_invoice_source_copies_available_v1(p_company_id uuid,p_underlay_id uuid,p_invoice_id uuid DEFAULT NULL,p_export_item_id uuid DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE source uuid;BEGIN
 IF p_underlay_id IS NOT NULL THEN PERFORM public.ediel_require_finance_copy_available_v1(p_company_id,'billing_underlay_source_body',p_underlay_id::text);PERFORM public.ediel_require_finance_copy_available_v1(p_company_id,'billing_underlay_payload_body',p_underlay_id::text);SELECT portfolio_monthly_settlement_id INTO source FROM public.billing_underlays WHERE company_id=p_company_id AND id=p_underlay_id;IF source IS NOT NULL THEN PERFORM public.ediel_require_finance_copy_available_v1(p_company_id,'settlement_calculation_body',source::text);END IF;END IF;
 IF p_invoice_id IS NOT NULL THEN PERFORM public.ediel_require_finance_copy_available_v1(p_company_id,'invoice_calculation_body',p_invoice_id::text);END IF;IF p_export_item_id IS NOT NULL THEN PERFORM public.ediel_require_finance_copy_available_v1(p_company_id,'invoice_export_item_body',p_export_item_id::text);END IF;END$$;
DO $$DECLARE body text;definition text;needle text:='SELECT * INTO prior FROM gridex_billing_source.underlay_bindings';BEGIN
 SELECT prosrc INTO STRICT body FROM pg_proc WHERE oid='public.gridex_store_billing_underlay(uuid,jsonb,jsonb,uuid)'::regprocedure;definition:=pg_get_functiondef('public.gridex_store_billing_underlay(uuid,jsonb,jsonb,uuid)'::regprocedure);
 IF position(needle in body)=0 THEN RAISE EXCEPTION 'finance_retention_actual_billing_owner_review_required';END IF;
 body:=overlay(body placing 'PERFORM public.ediel_require_invoice_source_copies_available_v1(p_company_id,(p_underlay->>''id'')::uuid);'||chr(10) from position(needle in body) for 0);EXECUTE replace(definition,(SELECT prosrc FROM pg_proc WHERE oid='public.gridex_store_billing_underlay(uuid,jsonb,jsonb,uuid)'::regprocedure),body);
 SELECT prosrc INTO STRICT body FROM pg_proc WHERE oid='gridex_billing_source.require_underlay_v1(uuid,uuid)'::regprocedure;definition:=pg_get_functiondef('gridex_billing_source.require_underlay_v1(uuid,uuid)'::regprocedure);body:=regexp_replace(body,'\mBEGIN\M','BEGIN PERFORM public.ediel_require_invoice_source_copies_available_v1(p_company,p_underlay);','i');EXECUTE replace(definition,(SELECT prosrc FROM pg_proc WHERE oid='gridex_billing_source.require_underlay_v1(uuid,uuid)'::regprocedure),body);
END$$;
CREATE FUNCTION gridex_ediel_retention.finance_fresh_consumption_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb:=to_jsonb(NEW);source uuid;BEGIN
 IF TG_OP='UPDATE' AND public.ediel_is_qualified_finance_retention_transition_v1(TG_TABLE_SCHEMA,TG_TABLE_NAME,to_jsonb(OLD),r) IS TRUE THEN RETURN NEW;END IF;
 IF TG_TABLE_NAME='portfolio_monthly_settlements' THEN source:=(r->>'supersedes_settlement_id')::uuid;IF source IS NOT NULL THEN PERFORM public.ediel_require_finance_copy_available_v1(NEW.company_id,'settlement_calculation_body',source::text);END IF;
 ELSE source:=(r->>'billing_underlay_id')::uuid;IF source IS NOT NULL THEN PERFORM public.ediel_require_invoice_source_copies_available_v1(NEW.company_id,source);END IF;END IF;RETURN NEW;END$$;
-- Late native writes recheck the actual prospective consumed source; an
-- independent new underlay/settlement is unaffected by older customer history.
CREATE TRIGGER zz_finance_actual_source_consumption BEFORE INSERT OR UPDATE ON public.customer_invoices FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.finance_fresh_consumption_guard_v1();
CREATE TRIGGER zz_finance_actual_source_consumption BEFORE INSERT OR UPDATE ON public.invoice_export_items FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.finance_fresh_consumption_guard_v1();
CREATE TRIGGER zz_finance_actual_source_consumption BEFORE INSERT OR UPDATE ON public.billing_export_run_items FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.finance_fresh_consumption_guard_v1();
CREATE TRIGGER zz_finance_actual_source_consumption BEFORE INSERT OR UPDATE ON public.partner_exports FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.finance_fresh_consumption_guard_v1();
CREATE TRIGGER zz_finance_actual_source_consumption BEFORE INSERT ON public.portfolio_monthly_settlements FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.finance_fresh_consumption_guard_v1();
-- A negative availability predicate never creates source or business authority.
-- Existing owner replay returns before the native fresh-consumption checks.
DO $$DECLARE signature text;definition text;body text;needle text;match text;extra text;BEGIN
 FOREACH signature IN ARRAY ARRAY['public.gridex_bind_locked_portfolio_settlement_to_underlay(uuid,uuid,uuid,uuid,text)','public.gridex_attach_portfolio_settlement_to_invoice(uuid,uuid,uuid,uuid,text)'] LOOP
 definition:=pg_get_functiondef(signature::regprocedure);SELECT prosrc INTO STRICT body FROM pg_proc WHERE oid=signature::regprocedure;
 SELECT substring(body from '(?i)select\s+\*\s+into\s+v_underlay') INTO match;IF match IS NULL THEN RAISE EXCEPTION 'finance_retention_fresh_consumer_source_review_required: %',signature;END IF;
 extra:='perform public.ediel_require_invoice_source_copies_available_v1(p_company_id,p_billing_underlay_id);';
 IF signature LIKE '%gridex_bind_locked%' THEN extra:=extra||'perform public.ediel_require_finance_copy_available_v1(p_company_id,''settlement_calculation_body'',p_portfolio_monthly_settlement_id::text);';
 ELSE extra:=extra||'perform public.ediel_require_finance_copy_available_v1(p_company_id,''settlement_invoice_binding_body'',v_binding.id::text);perform public.ediel_require_invoice_source_copies_available_v1(p_company_id,p_billing_underlay_id,p_customer_invoice_id);';END IF;
 body:=overlay(body placing extra||chr(10) from position(match in body) for 0);EXECUTE replace(definition,(SELECT prosrc FROM pg_proc WHERE oid=signature::regprocedure),body);END LOOP;END$$;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_ediel_retention' AND p.proname LIKE 'finance_%' AND p.proname NOT LIKE 'finance_guard_%' OR n.nspname='public' AND p.proname IN('ediel_finance_copy_retention_basis_v1','ediel_submit_finance_copy_retention_v1','ediel_read_finance_copy_retention_v1','ediel_review_finance_copy_retention_v1','ediel_revoke_finance_copy_retention_v1','ediel_purge_finance_copy_retention_v1','ediel_is_qualified_finance_retention_transition_v1','ediel_require_finance_copy_available_v1','ediel_require_invoice_source_copies_available_v1') LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO gridex_ediel_retention_owner',f.signature);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.signature);END LOOP;END$$;
GRANT EXECUTE ON FUNCTION public.ediel_finance_copy_retention_basis_v1(uuid,uuid,text,text),public.ediel_submit_finance_copy_retention_v1(uuid,uuid,text,text,text,jsonb),public.ediel_read_finance_copy_retention_v1(uuid,uuid,uuid),public.ediel_review_finance_copy_retention_v1(uuid,uuid,uuid,text,text),public.ediel_revoke_finance_copy_retention_v1(uuid,uuid,uuid,text),public.ediel_purge_finance_copy_retention_v1(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_require_finance_copy_available_v1(uuid,text,text),public.ediel_require_invoice_source_copies_available_v1(uuid,uuid,uuid,uuid) TO service_role;
-- Original source owners need only the exact negative predicate, never the
-- private decisions or permission to issue policy or retention truth.
DO $$DECLARE o text;signature text;BEGIN FOREACH signature IN ARRAY ARRAY['public.gridex_bind_locked_portfolio_settlement_to_underlay(uuid,uuid,uuid,uuid,text)','public.gridex_attach_portfolio_settlement_to_invoice(uuid,uuid,uuid,uuid,text)','public.gridex_store_billing_underlay(uuid,jsonb,jsonb,uuid)','gridex_billing_source.require_underlay_v1(uuid,uuid)','public.gridex_audit_portfolio_settlement_write()'] LOOP IF to_regprocedure(signature) IS NULL THEN CONTINUE;END IF;SELECT rolname INTO o FROM pg_roles WHERE oid=(SELECT proowner FROM pg_proc WHERE oid=signature::regprocedure);EXECUTE format('GRANT EXECUTE ON FUNCTION public.ediel_require_invoice_source_copies_available_v1(uuid,uuid,uuid,uuid),public.ediel_require_finance_copy_available_v1(uuid,text,text),public.ediel_is_qualified_finance_retention_transition_v1(text,text,jsonb,jsonb) TO %I',o);END LOOP;END$$;
REVOKE CREATE ON SCHEMA public FROM gridex_ediel_retention_owner;
COMMIT;
