-- P09/SC030/AT-Z09E/F/G: source-owned requests, never a customer switch.
-- Genuine approvals are unseeded and inaccessible to every application role.
BEGIN;
CREATE SCHEMA gridex_requested_changes;
REVOKE ALL ON SCHEMA gridex_requested_changes FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE gridex_requested_changes.events(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL CHECK(environment IN('test','production')),
 supply_period_id uuid NOT NULL REFERENCES public.customer_supply_periods(id),supply_source_message_id uuid NOT NULL REFERENCES public.ediel_messages(id),supply_state_version bigint NOT NULL,
 contract_id uuid NOT NULL REFERENCES public.customer_contracts(id),protected_contract_hash text NOT NULL CHECK(protected_contract_hash~'^[a-f0-9]{64}$'),
 customer_id uuid NOT NULL REFERENCES public.customers(id),metering_point_id uuid NOT NULL REFERENCES public.metering_points(id),customer_snapshot_hash text NOT NULL CHECK(customer_snapshot_hash~'^[a-f0-9]{64}$'),
 legal_actor_id uuid NOT NULL,legal_sender_id text NOT NULL,legal_receiver_id text NOT NULL,point_id text NOT NULL,identity_agency text NOT NULL CHECK(identity_agency IN('9','89')),grid_area_code text NOT NULL,brp_ediel_id text NOT NULL,
 variant text NOT NULL CHECK(variant IN('E','F','G')),event_kind text NOT NULL CHECK(event_kind IN('death','quarter_contract','method_contract')),
 effective_at timestamptz NOT NULL CHECK(isfinite(effective_at) AND extract(second FROM effective_at)=0),customer_identity jsonb NOT NULL,invoicee_profile jsonb NOT NULL,
 source_reference text NOT NULL CHECK(length(source_reference)>0),source_sha256 text NOT NULL CHECK(source_sha256~'^[a-f0-9]{64}$'),source_version text NOT NULL CHECK(length(source_version)>0),
 approved_by uuid NOT NULL REFERENCES auth.users(id),approved_at timestamptz NOT NULL,
 CHECK(event_kind=CASE variant WHEN 'E' THEN 'death' WHEN 'F' THEN 'quarter_contract' ELSE 'method_contract' END),UNIQUE(company_id,environment,source_reference,source_version));
CREATE TABLE gridex_requested_changes.revocations(event_id uuid PRIMARY KEY REFERENCES gridex_requested_changes.events(id),source_reference text NOT NULL CHECK(length(source_reference)>0),source_sha256 text NOT NULL CHECK(source_sha256~'^[a-f0-9]{64}$'),actor_user_id uuid NOT NULL REFERENCES auth.users(id),revoked_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE gridex_requested_changes.origins(event_id uuid PRIMARY KEY REFERENCES gridex_requested_changes.events(id),company_id uuid NOT NULL REFERENCES public.companies(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),intent_id uuid UNIQUE NOT NULL REFERENCES public.ediel_message_intents(id),outbound_request_id uuid UNIQUE NOT NULL REFERENCES public.outbound_requests(id),basis jsonb NOT NULL,intent_binding jsonb NOT NULL,request_binding jsonb NOT NULL,message_id uuid UNIQUE REFERENCES public.ediel_messages(id),payload_hash text,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),CHECK((message_id IS NULL)=(payload_hash IS NULL)));
CREATE TABLE gridex_requested_changes.confirmed_customer_versions(source_message_id uuid PRIMARY KEY REFERENCES public.ediel_messages(id),event_id uuid NOT NULL REFERENCES gridex_requested_changes.events(id),company_id uuid NOT NULL,environment text NOT NULL,payload_hash text NOT NULL,customer_id uuid NOT NULL,metering_point_id uuid NOT NULL,effective_at timestamptz NOT NULL,received_at timestamptz NOT NULL,party jsonb NOT NULL,actor_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
DO $$DECLARE t text;BEGIN FOR t IN SELECT unnest(ARRAY['events','revocations','origins','confirmed_customer_versions']) LOOP
 EXECUTE format('ALTER TABLE gridex_requested_changes.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_requested_changes.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_requested_changes.%I FROM PUBLIC,anon,authenticated,service_role',t);
 IF t<>'origins' THEN EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON gridex_requested_changes.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_immutable',t);END IF;
 EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON gridex_requested_changes.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_no_truncate',t);
 END LOOP;END$$;
CREATE FUNCTION gridex_requested_changes.revoke_lock_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN PERFORM id FROM gridex_requested_changes.events WHERE id=NEW.event_id FOR UPDATE;RETURN NEW;END$$;
CREATE TRIGGER requested_change_revoke_lock BEFORE INSERT ON gridex_requested_changes.revocations FOR EACH ROW EXECUTE FUNCTION gridex_requested_changes.revoke_lock_v1();
CREATE FUNCTION gridex_requested_changes.context_v1(c uuid,event uuid,actor uuid,permission text DEFAULT 'communication.write') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE e gridex_requested_changes.events%rowtype;contract public.customer_contracts%rowtype;customer public.customers%rowtype;supply jsonb;initial public.ediel_messages%rowtype;tokens jsonb;party jsonb;mp public.metering_points%rowtype;
BEGIN
 PERFORM u.id FROM public.user_profiles u WHERE u.id=actor FOR SHARE;PERFORM cm.user_id FROM public.company_memberships cm WHERE cm.company_id=c AND cm.user_id=actor FOR SHARE;
 IF permission NOT IN('communication.write','communication.send') OR actor IS NULL OR NOT EXISTS(SELECT FROM public.user_profiles WHERE id=actor AND user_status='active') OR NOT EXISTS(SELECT FROM public.company_memberships WHERE company_id=c AND user_id=actor AND status='active' AND is_active AND accepted_at IS NOT NULL) OR public.gridex_actor_has_company_permission(actor,c,permission) IS NOT TRUE THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_execution_actor_unqualified']);END IF;
 SELECT * INTO e FROM gridex_requested_changes.events WHERE id=event AND company_id=c FOR SHARE;
 IF NOT FOUND OR e.approved_at>now() OR EXISTS(SELECT FROM gridex_requested_changes.revocations WHERE event_id=e.id) THEN RETURN jsonb_build_object('status','held','missing',ARRAY['authentic_customer_death_or_signed_metering_change_event']);END IF;
 supply:=gridex_received_sources.supply_period_source_basis_v1(c,e.supply_period_id,e.effective_at,e.effective_at+interval '1 minute');
 IF supply->>'qualified' IS DISTINCT FROM 'true' OR supply->>'sourceMessageId' IS DISTINCT FROM e.supply_source_message_id::text OR (supply->>'marketStateVersion')::bigint IS DISTINCT FROM e.supply_state_version OR supply->>'customerId' IS DISTINCT FROM e.customer_id::text OR supply->>'meteringPointId' IS DISTINCT FROM e.metering_point_id::text OR supply->>'legalActorId' IS DISTINCT FROM e.legal_actor_id::text OR supply->>'dsoEdielId' IS DISTINCT FROM e.legal_receiver_id
 OR (SELECT count(*) FROM jsonb_array_elements(supply->'sourceObjects') own WHERE own->>'point'=e.point_id AND own->>'identityAgency'=e.identity_agency)<>1 THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_current_approved_physical_supply']);END IF;
 SELECT * INTO initial FROM public.ediel_messages WHERE company_id=c AND id=(supply->>'initialSourceMessageId')::uuid FOR SHARE;
 tokens:=gridex_received_sources.closure_wire_tokens_v2(initial.raw_payload);
 IF initial.environment IS DISTINCT FROM e.environment OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='Z02' AND t#>>'{elements,2,0}'=e.brp_ediel_id AND t#>>'{elements,2,1}'='160' AND t#>>'{elements,2,2}'='SVK')<>1 THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_owned_original_brp_identity']);END IF;
 SELECT * INTO contract FROM public.customer_contracts WHERE id=e.contract_id AND company_id=c FOR SHARE;SELECT * INTO customer FROM public.customers WHERE id=e.customer_id AND company_id=c FOR SHARE;SELECT * INTO mp FROM public.metering_points WHERE id=e.metering_point_id AND company_id=c FOR SHARE;
 IF contract.id IS NULL OR customer.id IS NULL OR mp.id IS NULL OR contract.customer_id IS DISTINCT FROM e.customer_id OR contract.metering_point_id IS DISTINCT FROM e.metering_point_id OR (contract.status IN('signed','active')) IS NOT TRUE OR contract.signed_at IS NULL OR nullif(contract.signed_version,'') IS NULL OR gridex_received_sources.production_contract_hash_v1(contract) IS DISTINCT FROM e.protected_contract_hash OR encode(sha256(convert_to((to_jsonb(customer)-'updated_at')::text,'UTF8')),'hex') IS DISTINCT FROM e.customer_snapshot_hash OR mp.customer_id IS DISTINCT FROM e.customer_id OR mp.product_direction IS DISTINCT FROM 'consumption' OR mp.ediel_metering_point_id IS DISTINCT FROM e.point_id OR mp.grid_owner_ediel_id IS DISTINCT FROM e.legal_receiver_id OR mp.grid_area_code IS DISTINCT FROM e.grid_area_code THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_exact_owned_contract_customer_point']);END IF;
 PERFORM p.id FROM public.tenant_ediel_profiles p WHERE company_id=c AND environment=e.environment ORDER BY id FOR SHARE;PERFORM p.id FROM public.tenant_actor_identifiers p WHERE company_id=c AND environment=e.environment ORDER BY id FOR SHARE;PERFORM p.id FROM public.tenant_actor_roles p WHERE company_id=c AND environment=e.environment ORDER BY id FOR SHARE;
 IF NOT EXISTS(SELECT FROM public.tenant_ediel_profiles WHERE company_id=c AND environment=e.environment AND market='electricity' AND is_enabled AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now())) OR NOT EXISTS(SELECT FROM public.tenant_actor_roles WHERE company_id=c AND environment=e.environment AND actor_id=e.legal_actor_id AND role_code='electricity_supplier' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now())) OR (SELECT count(DISTINCT(actor_id,identifier_value)) FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=e.environment AND identifier_type='EdielId' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now()))<>1 OR NOT EXISTS(SELECT FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=e.environment AND actor_id=e.legal_actor_id AND identifier_type='EdielId' AND identifier_value=e.legal_sender_id AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now())) THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_current_legal_supplier']);END IF;
 party:=e.customer_identity;
 IF jsonb_typeof(party) IS DISTINCT FROM 'object' OR nullif(party->>'id','') IS NULL OR nullif(party->>'name','') IS NULL OR (party->>'qualifier' IN('','1','SE1','SE2')) IS NOT TRUE OR party->>'agency' IS DISTINCT FROM (CASE WHEN party->>'qualifier'='' THEN '89' ELSE '260' END) OR jsonb_typeof(party->'addressLines') IS DISTINCT FROM 'array'
 OR e.invoicee_profile->>'meteringPointId' IS DISTINCT FROM e.point_id OR e.invoicee_profile->>'identityAgency' IS DISTINCT FROM e.identity_agency OR e.invoicee_profile#>>'{source,companyId}' IS DISTINCT FROM c::text OR e.invoicee_profile#>'{endUser,identity}' IS DISTINCT FROM jsonb_build_object('id',party->>'id','qualifier',party->>'qualifier','agency',party->>'agency') THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_explicit_customer_invoicee_source']);END IF;
 RETURN jsonb_build_object('status','authorized','companyId',c,'environment',e.environment,'eventId',e.id,'variant',e.variant,'eventKind',e.event_kind,'supplyPeriodId',e.supply_period_id,'supplySourceMessageId',e.supply_source_message_id,'supplyStateVersion',e.supply_state_version,'customerId',e.customer_id,'meteringPointId',e.metering_point_id,'legalActorId',e.legal_actor_id,'legalSenderId',e.legal_sender_id,'legalReceiverId',e.legal_receiver_id,'pointId',e.point_id,'identityAgency',e.identity_agency,'gridArea',e.grid_area_code,'brpEdielId',e.brp_ediel_id,'effectiveAt',e.effective_at,'sourceReference',e.source_reference,'sourceVersion',e.source_version,'sourceDigest',e.source_sha256,'customerIdentity',party,'invoiceeProfile',e.invoicee_profile);
END$$;
CREATE FUNCTION public.ediel_requested_change_source_v1(p_company_id uuid,p_event_id uuid,p_actor_user_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$SELECT gridex_requested_changes.context_v1(p_company_id,p_event_id,p_actor_user_id)$$;
CREATE FUNCTION public.ediel_originate_requested_change_v1(p_company_id uuid,p_event_id uuid,p_actor_user_id uuid,p_route jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE e gridex_requested_changes.events%rowtype;b jsonb;o gridex_requested_changes.origins%rowtype;i public.ediel_message_intents%rowtype;r public.outbound_requests%rowtype;route public.ediel_route_profiles%rowtype;ref text;
BEGIN
 SELECT * INTO e FROM gridex_requested_changes.events WHERE id=p_event_id AND company_id=p_company_id FOR UPDATE;b:=gridex_requested_changes.context_v1(p_company_id,p_event_id,p_actor_user_id);IF b->>'status' IS DISTINCT FROM 'authorized' THEN RETURN b;END IF;
 SELECT * INTO o FROM gridex_requested_changes.origins WHERE event_id=e.id FOR UPDATE;
 IF FOUND THEN RETURN jsonb_build_object('status','originated','intentId',o.intent_id,'outboundRequestId',o.outbound_request_id,'messageId',o.message_id);END IF;
 SELECT * INTO route FROM public.ediel_route_profiles WHERE id=(p_route->>'routeProfileId')::uuid AND company_id=p_company_id AND environment=e.environment FOR SHARE;
 PERFORM id FROM public.communication_routes WHERE id=(p_route->>'communicationRouteId')::uuid AND company_id=p_company_id AND is_active FOR SHARE;
 IF NOT FOUND OR route.id IS NULL OR NOT route.is_enabled OR NOT route.is_active OR route.sender_ediel_id IS DISTINCT FROM p_route->>'senderEdielId' OR route.receiver_ediel_id IS DISTINCT FROM p_route->>'receiverEdielId' OR nullif(route.sender_sub_address,'') IS DISTINCT FROM nullif(p_route->>'senderSubaddress','') OR nullif(route.receiver_sub_address,'') IS DISTINCT FROM nullif(p_route->>'receiverSubaddress','') OR p_route->>'applicationReference' IS DISTINCT FROM '23-DDQ-PRODAT' THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_exact_owned_current_route']);END IF;
 ref:=replace(gen_random_uuid()::text,'-','');ref:=upper(substring(ref,1,20));
 INSERT INTO public.ediel_message_intents(company_id,environment,market,message_family,message_code,business_process,direction,sender_ediel_id,sender_subaddress,receiver_ediel_id,receiver_subaddress,application_reference,route_profile_id,communication_route_id,customer_id,operation_id,metering_point_id,facility_id,grid_area_code,interchange_reference,message_reference,transaction_reference,payload,idempotency_key,created_by,updated_by)
 VALUES(p_company_id,e.environment,'electricity','PRODAT','Z09','customer_masterdata','outbound',route.sender_ediel_id,nullif(route.sender_sub_address,''),route.receiver_ediel_id,nullif(route.receiver_sub_address,''),'23-DDQ-PRODAT',route.id,(p_route->>'communicationRouteId')::uuid,e.customer_id,e.id,e.point_id,e.point_id,e.grid_area_code,ref,'1',ref,jsonb_build_object('actorRole','supplier','requestedChangeEventId',e.id,'variant',e.variant),'requested-change:'||e.id::text,p_actor_user_id,p_actor_user_id) RETURNING * INTO i;
 INSERT INTO public.outbound_requests(company_id,customer_id,metering_point_id,communication_route_id,request_type,source_type,source_id,environment,status,channel_type,payload,created_by,updated_by,operation_id)
 VALUES(p_company_id,e.customer_id,e.metering_point_id,i.communication_route_id,'customer_masterdata','manual',i.id,e.environment,'prepared','smtp',jsonb_build_object('requestedChangeEventId',e.id,'intentId',i.id),p_actor_user_id,p_actor_user_id,e.id) RETURNING * INTO r;
 INSERT INTO gridex_requested_changes.origins(event_id,company_id,actor_user_id,intent_id,outbound_request_id,basis,intent_binding,request_binding) VALUES(e.id,p_company_id,p_actor_user_id,i.id,r.id,b,to_jsonb(i)-ARRAY['validation_result','blocking_reasons','validation_status','render_status','outbox_status','updated_by','updated_at','ediel_message_id','outbound_request_id'],to_jsonb(r)-ARRAY['status','payload','response_payload','attempts_count','queued_at','prepared_at','sent_at','acknowledged_at','failed_at','failure_reason','updated_at','updated_by']);
 RETURN jsonb_build_object('status','originated','intentId',i.id,'outboundRequestId',r.id,'messageId',null);
END$$;
CREATE FUNCTION gridex_requested_changes.origin_guard_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN
 IF TG_OP<>'UPDATE' OR (to_jsonb(NEW)-ARRAY['message_id','payload_hash']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['message_id','payload_hash']) OR OLD.message_id IS NOT NULL OR NEW.message_id IS NULL OR NEW.payload_hash IS NULL THEN RAISE EXCEPTION 'requested_change_origin_immutable';END IF;RETURN NEW;END$$;
CREATE TRIGGER requested_change_origin_immutable BEFORE UPDATE OR DELETE ON gridex_requested_changes.origins FOR EACH ROW EXECUTE FUNCTION gridex_requested_changes.origin_guard_v1();
CREATE FUNCTION gridex_requested_changes.party_matches_v1(t jsonb,identity jsonb,names jsonb,lines jsonb,city text,postal text,country text) RETURNS boolean LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$
DECLARE wire_lines jsonb:=lines;
BEGIN
 IF coalesce(lines->>0,'')='' AND EXISTS(SELECT FROM jsonb_array_elements_text(lines) WITH ORDINALITY x(v,n) WHERE n>1 AND v<>'') THEN wire_lines:=jsonb_set(lines,'{0}','"."');END IF;
 RETURN t#>'{elements,2}'=jsonb_build_array(identity->>'id',identity->>'qualifier',identity->>'agency') AND t#>'{elements,4}'=names AND t#>'{elements,5}'=wire_lines AND t#>>'{elements,6,0}' IS NOT DISTINCT FROM city AND t#>>'{elements,8,0}' IS NOT DISTINCT FROM postal AND t#>>'{elements,9,0}' IS NOT DISTINCT FROM country;
END$$;
CREATE FUNCTION gridex_requested_changes.require_message_v1(m public.ediel_messages,actor uuid,permission text DEFAULT 'communication.write') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE o gridex_requested_changes.origins%rowtype;e gridex_requested_changes.events%rowtype;b jsonb;i public.ediel_message_intents%rowtype;r public.outbound_requests%rowtype;tokens jsonb;own jsonb;reason text;iv jsonb;ud jsonb;point jsonb;need_iv boolean;
BEGIN
 SELECT * INTO o FROM gridex_requested_changes.origins WHERE intent_id=m.intent_id AND company_id=m.company_id FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'requested_change_original_origin_required';END IF;
 SELECT * INTO e FROM gridex_requested_changes.events WHERE id=o.event_id FOR SHARE;b:=gridex_requested_changes.context_v1(m.company_id,e.id,actor,permission);IF b->>'status' IS DISTINCT FROM 'authorized' OR b IS DISTINCT FROM o.basis THEN RAISE EXCEPTION 'requested_change_original_current_source_required';END IF;
 SELECT * INTO i FROM public.ediel_message_intents WHERE id=o.intent_id AND company_id=m.company_id FOR SHARE;SELECT * INTO r FROM public.outbound_requests WHERE id=o.outbound_request_id AND company_id=m.company_id FOR SHARE;
 IF i.id IS NULL OR r.id IS NULL OR (to_jsonb(i)-ARRAY['validation_result','blocking_reasons','validation_status','render_status','outbox_status','updated_by','updated_at','ediel_message_id','outbound_request_id']) IS DISTINCT FROM o.intent_binding OR (to_jsonb(r)-ARRAY['status','payload','response_payload','attempts_count','queued_at','prepared_at','sent_at','acknowledged_at','failed_at','failure_reason','updated_at','updated_by']) IS DISTINCT FROM o.request_binding OR m.environment IS DISTINCT FROM e.environment OR m.direction IS DISTINCT FROM 'outbound' OR m.message_standard IS DISTINCT FROM 'edifact' OR m.message_family IS DISTINCT FROM 'PRODAT' OR m.message_code IS DISTINCT FROM 'Z09' OR m.source_operation_id::text IS DISTINCT FROM e.id::text OR m.outbound_request_id IS DISTINCT FROM o.outbound_request_id OR m.customer_id IS DISTINCT FROM e.customer_id OR m.metering_point_id IS DISTINCT FROM e.metering_point_id OR m.application_reference IS DISTINCT FROM i.application_reference OR m.sender_ediel_id IS DISTINCT FROM i.sender_ediel_id OR m.receiver_ediel_id IS DISTINCT FROM i.receiver_ediel_id OR nullif(m.sender_sub_address,'') IS DISTINCT FROM nullif(i.sender_subaddress,'') OR nullif(m.receiver_sub_address,'') IS DISTINCT FROM nullif(i.receiver_subaddress,'') OR m.route_profile_id IS DISTINCT FROM i.route_profile_id OR m.communication_route_id IS DISTINCT FROM i.communication_route_id THEN RAISE EXCEPTION 'requested_change_message_scope_changed';END IF;
 tokens:=gridex_received_sources.closure_wire_tokens_v2(m.raw_payload);reason:=CASE e.variant WHEN 'E' THEN 'E34' WHEN 'F' THEN 'E64' ELSE 'E32' END;
 IF (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='UNH' AND t#>>'{elements,2,0}'='PRODAT')<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='BGM' AND t#>>'{elements,1,0}'='Z09' AND t#>>'{elements,2,0}'=i.interchange_reference)<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN' AND t#>>'{elements,3,0}'=e.point_id AND t#>>'{elements,3,3}'=e.identity_agency)<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN')<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='RFF' AND t#>>'{elements,1,0}'='LI' AND t#>>'{elements,1,1}'=i.transaction_reference)<>1 THEN RAISE EXCEPTION 'requested_change_physical_original_scope_changed';END IF;
 IF (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='FR' AND t#>>'{elements,2,0}'=e.legal_sender_id AND t#>>'{elements,2,1}'='160' AND t#>>'{elements,2,2}'='SVK')<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='DO' AND t#>>'{elements,2,0}'=e.legal_receiver_id AND t#>>'{elements,2,1}'='160' AND t#>>'{elements,2,2}'='SVK')<>1 THEN RAISE EXCEPTION 'requested_change_legal_parties_changed';END IF;
 IF (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='157' AND t#>>'{elements,1,1}'=to_char(e.effective_at AT TIME ZONE 'Etc/GMT-1','YYYYMMDDHH24MI') AND t#>>'{elements,1,2}'='203')<>1 OR EXISTS(SELECT FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}' IN('92','93')) OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'=reason)<>1 THEN RAISE EXCEPTION 'requested_change_reason_or_effective_boundary_changed';END IF;
 IF e.variant='E' THEN
  SELECT t INTO ud FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD';
  IF (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD')<>1 OR gridex_requested_changes.party_matches_v1(ud,e.customer_identity,jsonb_build_array(e.customer_identity->>'name'),e.customer_identity->'addressLines',e.customer_identity->>'city',e.customer_identity->>'postalCode',e.customer_identity->>'country') IS NOT TRUE OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='Z41')<>1 THEN RAISE EXCEPTION 'requested_change_death_customer_changed';END IF;
  IF e.invoicee_profile#>>'{invoicee,availability}' IS DISTINCT FROM 'available' OR e.invoicee_profile#>'{endUser,address,representation}' IS NULL OR e.invoicee_profile#>>'{endUser,address,representation,convention}' IS DISTINCT FROM e.invoicee_profile#>>'{invoicee,address,representation,convention}' OR e.invoicee_profile#>'{endUser,address,representation,mode}' IS DISTINCT FROM e.invoicee_profile#>'{invoicee,address,representation,mode}' OR EXISTS(SELECT FROM jsonb_array_elements(e.invoicee_profile#>'{endUser,address,lines}') v WHERE jsonb_typeof(v)<>'string') OR EXISTS(SELECT FROM jsonb_array_elements(e.invoicee_profile#>'{invoicee,address,lines}') v WHERE jsonb_typeof(v)<>'string') THEN RAISE EXCEPTION 'requested_change_invoicee_comparison_unqualified';END IF;
  need_iv:=e.invoicee_profile#>'{endUser,identity}' IS DISTINCT FROM e.invoicee_profile#>'{invoicee,identity}' OR ((e.invoicee_profile#>'{endUser,address}')-'representation') IS DISTINCT FROM ((e.invoicee_profile#>'{invoicee,address}')-'representation');
  SELECT t INTO iv FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV';
  IF need_iv THEN
   IF (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV')<>1 OR gridex_requested_changes.party_matches_v1(iv,e.invoicee_profile#>'{invoicee,identity}',e.invoicee_profile#>'{invoicee,nameLines}',e.invoicee_profile#>'{invoicee,address,lines}',e.invoicee_profile#>>'{invoicee,address,city}',e.invoicee_profile#>>'{invoicee,address,postalCode}',e.invoicee_profile#>>'{invoicee,address,country}') IS NOT TRUE THEN RAISE EXCEPTION 'requested_change_invoicee_changed';END IF;
  ELSIF iv IS NOT NULL THEN RAISE EXCEPTION 'requested_change_invoicee_forbidden';END IF;
 ELSE
  IF EXISTS(SELECT FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}' IN('UD','IV')) OR EXISTS(SELECT FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='Z41') OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'=(CASE e.variant WHEN 'F' THEN 'Z04' ELSE 'Z03' END))<>1 THEN RAISE EXCEPTION 'requested_change_metering_method_or_customer_scope_changed';END IF;
 END IF;
 IF o.message_id IS NOT NULL AND (o.message_id IS DISTINCT FROM m.id OR o.payload_hash IS DISTINCT FROM encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex')) THEN RAISE EXCEPTION 'requested_change_bound_original_changed';END IF;
 RETURN b;
END$$;
CREATE FUNCTION gridex_requested_changes.bind_message_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE o gridex_requested_changes.origins%rowtype;BEGIN
 SELECT * INTO o FROM gridex_requested_changes.origins WHERE intent_id=NEW.intent_id AND company_id=NEW.company_id FOR UPDATE;IF NOT FOUND THEN RETURN NEW;END IF;
 PERFORM gridex_requested_changes.require_message_v1(NEW,o.actor_user_id);
 IF o.message_id IS NOT NULL THEN RAISE EXCEPTION 'requested_change_message_already_bound' USING ERRCODE='23505';END IF;
 UPDATE gridex_requested_changes.origins SET message_id=NEW.id,payload_hash=encode(sha256(convert_to(NEW.raw_payload,'UTF8')),'hex') WHERE event_id=o.event_id;RETURN NEW;END$$;
CREATE TRIGGER bind_requested_change_original AFTER INSERT ON public.ediel_messages FOR EACH ROW EXECUTE FUNCTION gridex_requested_changes.bind_message_v1();
CREATE FUNCTION public.ediel_require_requested_change_source_current_v1(p_company_id uuid,p_message_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE m public.ediel_messages%rowtype;o gridex_requested_changes.origins%rowtype;tokens jsonb;q jsonb;
BEGIN SELECT * INTO STRICT m FROM public.ediel_messages WHERE id=p_message_id AND company_id=p_company_id FOR SHARE;IF m.direction IS DISTINCT FROM 'outbound' THEN RETURN;END IF;
 tokens:=gridex_received_sources.closure_wire_tokens_v2(m.raw_payload);
 IF NOT EXISTS(SELECT FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='BGM' AND t#>>'{elements,1,0}'='Z09') OR NOT EXISTS(SELECT FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}' IN('E34','E64','E32')) THEN RETURN;END IF;
 SELECT * INTO o FROM gridex_requested_changes.origins WHERE message_id=m.id AND company_id=p_company_id FOR SHARE;
 IF NOT FOUND THEN
  IF m.environment='test' AND m.message_standard='edifact' AND m.message_family='PRODAT' AND m.message_code='Z09' THEN
   -- The established fixture owner checks actual registered original/run/step/
   -- role and sole-consumed message. No live business approval is created.
   q:=gridex_negative_fixtures.require_positive_message_v1(p_company_id,p_message_id,'Z09');
   IF q->>'kind'='source_qualified_positive_fixture' AND q->>'version'='1' AND q->>'companyId'=p_company_id::text AND q->>'roleCode'='supplier' AND q->>'suite'='PRODAT' AND q->>'expectedOutcome'='positive' AND q->'expectedDiagnosticCodes'='[]'::jsonb AND q->'authorizesBusinessEffect'='false'::jsonb THEN RETURN;END IF;
  END IF;
  RAISE EXCEPTION 'requested_change_original_origin_required';
 END IF;PERFORM gridex_requested_changes.require_message_v1(m,o.actor_user_id);
END$$;
CREATE FUNCTION public.ediel_requested_change_message_basis_v1(p_company_id uuid,p_message_id uuid,p_actor_user_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE m public.ediel_messages%rowtype;o gridex_requested_changes.origins%rowtype;b jsonb;BEGIN
 SELECT * INTO o FROM gridex_requested_changes.origins WHERE company_id=p_company_id AND message_id=p_message_id FOR SHARE;IF NOT FOUND THEN RETURN NULL;END IF;
 SELECT * INTO STRICT m FROM public.ediel_messages WHERE id=p_message_id AND company_id=p_company_id FOR SHARE;b:=gridex_requested_changes.require_message_v1(m,p_actor_user_id,'communication.send');
 RETURN jsonb_build_object('basis',b,'messageId',m.id,'intentId',o.intent_id,'payloadHash',o.payload_hash);END$$;
ALTER FUNCTION gridex_ediel_transport.mutate_v1(jsonb) RENAME TO mutate_before_requested_change_v1;
CREATE FUNCTION gridex_ediel_transport.mutate_v1(i jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;BEGIN
 r:=gridex_ediel_transport.mutate_before_requested_change_v1(i);
 IF (i->>'action' IN('prepare','enter')) IS TRUE AND r->>'proceed'='true' THEN PERFORM public.ediel_require_requested_change_source_current_v1((i->>'companyId')::uuid,(i->>'messageId')::uuid);END IF;RETURN r;END$$;
ALTER FUNCTION gridex_outbound_dispatch.mutate_v1(jsonb) RENAME TO mutate_before_requested_change_v1;
CREATE FUNCTION gridex_outbound_dispatch.mutate_v1(i jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;BEGIN
 r:=gridex_outbound_dispatch.mutate_before_requested_change_v1(i);
 IF (i->>'action' IN('prepare','enter')) IS TRUE AND r->>'scoped'='true' AND r->>'proceed'='true' THEN PERFORM public.ediel_require_requested_change_source_current_v1((i->>'companyId')::uuid,(i->>'messageId')::uuid);END IF;RETURN r;END$$;
REVOKE ALL ON FUNCTION gridex_ediel_transport.mutate_before_requested_change_v1(jsonb),gridex_outbound_dispatch.mutate_before_requested_change_v1(jsonb),gridex_ediel_transport.mutate_v1(jsonb),gridex_outbound_dispatch.mutate_v1(jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION gridex_ediel_transport.mutate_v1(jsonb),gridex_outbound_dispatch.mutate_v1(jsonb) TO service_role;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA gridex_requested_changes FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.ediel_requested_change_source_v1(uuid,uuid,uuid),public.ediel_originate_requested_change_v1(uuid,uuid,uuid,jsonb),public.ediel_require_requested_change_source_current_v1(uuid,uuid),public.ediel_requested_change_message_basis_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_requested_change_source_v1(uuid,uuid,uuid),public.ediel_originate_requested_change_v1(uuid,uuid,uuid,jsonb),public.ediel_require_requested_change_source_current_v1(uuid,uuid),public.ediel_requested_change_message_basis_v1(uuid,uuid,uuid) TO service_role;
COMMIT;
