-- Separate original-byte policies for retention decisions themselves. Actual
-- deadlines/purposes are signed source facts, never a default or a cascade.
-- Existing completed tombstones/metadata remain historical witnesses only.
BEGIN;
DO $$BEGIN
 IF NOT EXISTS(SELECT FROM pg_namespace WHERE nspname='gridex_ediel_retention' AND nspowner='gridex_ediel_retention_owner'::regrole)
 OR EXISTS(SELECT FROM pg_roles WHERE rolname='gridex_ediel_retention_owner' AND rolcanlogin) THEN RAISE EXCEPTION 'decision_evidence_private_owner_required';END IF;
 PERFORM 'gridex_ediel_retention.process_decisions'::regclass;
 PERFORM 'public.ediel_retention_lock_auth_actor_v1(uuid)'::regprocedure;
END$$;
GRANT CREATE ON SCHEMA public TO gridex_ediel_retention_owner;
CREATE TABLE gridex_ediel_retention.decision_evidence_catalog(retention_class text PRIMARY KEY,source_table text NOT NULL UNIQUE,permission_key text NOT NULL UNIQUE,revocation_table text NOT NULL,revocation_id_column text NOT NULL,receipt_function text NOT NULL);
INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES
 ('artifact_retention_decision_original_bytes','decisions','ediel.retention.artifact_decision_evidence','revocations','decision_id','receipt_v1'),
 ('blob_retention_decision_original_bytes','blob_decisions','ediel.retention.blob_decision_evidence','blob_revocations','decision_id','blob_receipt_v1'),
 ('record_retention_decision_original_bytes','record_decisions','ediel.retention.record_decision_evidence','record_revocations','decision_id','record_receipt_v1'),
 ('process_retention_decision_original_bytes','process_decisions','ediel.retention.process_decision_evidence','process_revocations','decision_id','process_receipt_v1'),
 ('decision_evidence_policy_original_bytes','decision_evidence_policies','ediel.retention.decision_policy_evidence','decision_evidence_revocations','policy_id','decision_evidence_receipt_v1');
CREATE TABLE gridex_ediel_retention.decision_evidence_policies(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),retention_class text NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_catalog(retention_class),target_id uuid NOT NULL,
 source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),target_metadata_hash text NOT NULL CHECK(target_metadata_hash~'^[a-f0-9]{64}$'),
 document_bytes bytea CHECK(octet_length(document_bytes) BETWEEN 1 AND 1048576),document_hash text NOT NULL CHECK(document_hash~'^[a-f0-9]{64}$'),document_byte_length bigint,document_purged_at timestamptz,
 issuer_receipt jsonb,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),CHECK(target_id<>id),
 UNIQUE(company_id,retention_class,target_id,source_hash,document_hash),CHECK(document_bytes IS NOT NULL AND document_purged_at IS NULL OR document_bytes IS NULL AND document_purged_at IS NOT NULL AND document_byte_length>0));
CREATE TABLE gridex_ediel_retention.decision_evidence_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),policy_id uuid NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_policies(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),outcome text NOT NULL CHECK(outcome IN('approved','held','rejected')),reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 4000),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.decision_evidence_revocations(policy_id uuid PRIMARY KEY REFERENCES gridex_ediel_retention.decision_evidence_policies(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 4000),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.decision_evidence_tombstones(retention_class text NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_catalog(retention_class),target_id uuid NOT NULL,company_id uuid NOT NULL,policy_id uuid NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_policies(id),review_id uuid NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_reviews(id),source_hash text NOT NULL,target_metadata_hash text NOT NULL,byte_length bigint NOT NULL CHECK(byte_length>0),actor_user_id uuid NOT NULL REFERENCES auth.users(id),journal_retain_until timestamptz NOT NULL,journal_purpose_reference text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(retention_class,target_id));
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['decision_evidence_catalog','decision_evidence_policies','decision_evidence_reviews','decision_evidence_revocations','decision_evidence_tombstones'] LOOP
 EXECUTE format('ALTER TABLE gridex_ediel_retention.%I OWNER TO gridex_ediel_retention_owner',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_ediel_retention.%I FROM PUBLIC,anon,authenticated,service_role',t);
 EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);EXECUTE format('CREATE TRIGGER no_truncate BEFORE TRUNCATE ON gridex_ediel_retention.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);
 END LOOP;END$$;
INSERT INTO public.permissions(key,name,category,description,is_active)
 SELECT permission_key,'Retention decision original: '||retention_class,'ediel','Explicit own original-byte class; no role/default assignment, issuer or deadline',true FROM gridex_ediel_retention.decision_evidence_catalog ON CONFLICT(key) DO NOTHING;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_actor_v1(c uuid,actor uuid,k text,operation text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE permission text;BEGIN
 IF operation='ediel.retention.read' THEN PERFORM gridex_ediel_retention.record_read_actor_v1(c,actor);ELSE PERFORM gridex_ediel_retention.actor_v1(c,actor,operation);END IF;
 SELECT permission_key INTO STRICT permission FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=k;
 IF gridex_ediel_retention.permission_v1(c,actor,permission) IS NOT TRUE THEN RAISE EXCEPTION 'decision_evidence_current_class_grant_required' USING ERRCODE='42501';END IF;
END$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_read_actor_v1(c uuid,actor uuid,k text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE operation text;BEGIN
 IF gridex_ediel_retention.record_permission_v1(c,actor,'__read_scope__') IS TRUE THEN operation:='ediel.retention.read';
 ELSIF gridex_ediel_retention.permission_v1(c,actor,'ediel.retention.review') IS TRUE THEN operation:='ediel.retention.review';
 ELSIF gridex_ediel_retention.permission_v1(c,actor,'ediel.retention.submit') IS TRUE THEN operation:='ediel.retention.submit';ELSE operation:='ediel.retention.purge';END IF;
 PERFORM gridex_ediel_retention.decision_evidence_actor_v1(c,actor,k,operation);
END$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_basis_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE tab text;r jsonb;bytes bytea;BEGIN
 SELECT source_table INTO STRICT tab FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=k;
 EXECUTE format('SELECT to_jsonb(d),d.document_bytes FROM gridex_ediel_retention.%I d WHERE id=$1 AND company_id=$2 FOR UPDATE',tab) INTO r,bytes USING target,c;
 IF r IS NULL THEN RAISE EXCEPTION 'decision_evidence_original_scope_required';END IF;
 IF bytes IS NULL OR octet_length(bytes) NOT BETWEEN 1 AND 1048576 OR encode(sha256(bytes),'hex') IS DISTINCT FROM r->>'document_hash' THEN RAISE EXCEPTION 'decision_evidence_actual_original_bytes_required';END IF;
 RETURN jsonb_build_object('retentionClass',k,'targetId',target,'sourceHash',r->>'document_hash','targetMetadataHash',encode(sha256(convert_to((r-ARRAY['document_bytes','document_byte_length','document_purged_at'])::text,'UTF8')),'hex'),'byteLength',octet_length(bytes));
END$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_receipt_v1(d gridex_ediel_retention.decision_evidence_policies) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE issuer gridex_ediel_retention.issuers%rowtype;p jsonb;bytes bytea;issued timestamptz;expires timestamptz;deadline timestamptz;journal_end timestamptz;BEGIN
 IF d.document_bytes IS NULL OR encode(sha256(d.document_bytes),'hex') IS DISTINCT FROM d.document_hash OR jsonb_typeof(d.issuer_receipt) IS DISTINCT FROM 'object' OR coalesce(d.issuer_receipt->>'signatureHex','')!~'^[a-f0-9]{64}$' OR length(coalesce(d.issuer_receipt->>'payloadBase64','')) NOT BETWEEN 1 AND 32768 THEN RETURN NULL;END IF;
 SELECT * INTO issuer FROM gridex_ediel_retention.issuers WHERE id=(d.issuer_receipt->>'issuerId')::uuid AND company_id=d.company_id FOR SHARE;
 IF issuer.id IS NULL OR encode(sha256(issuer.legal_evidence),'hex') IS DISTINCT FROM issuer.legal_hash OR now()<issuer.valid_from OR now()>=issuer.valid_to OR EXISTS(SELECT FROM gridex_ediel_retention.issuer_revocations WHERE issuer_id=issuer.id) OR EXISTS(SELECT FROM gridex_ediel_retention.decision_evidence_revocations WHERE policy_id=d.id) THEN RETURN NULL;END IF;
 bytes:=decode(d.issuer_receipt->>'payloadBase64','base64');IF encode(gridex_requested_changes.receipt_hmac_sha256_v1(bytes,issuer.signing_key),'hex') IS DISTINCT FROM d.issuer_receipt->>'signatureHex' THEN RETURN NULL;END IF;
 p:=convert_from(bytes,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;deadline:=(p->>'retainUntil')::timestamptz;journal_end:=(p->>'journalRetainUntil')::timestamptz;
 IF p->>'format' IS DISTINCT FROM 'ediel_retention_decision_original_policy_v1' OR p->>'operation' IS DISTINCT FROM 'erase_retention_decision_original_bytes' OR p->>'retentionClass' IS DISTINCT FROM d.retention_class OR p->>'companyId' IS DISTINCT FROM d.company_id::text OR p->>'targetId' IS DISTINCT FROM d.target_id::text OR p->>'sourceHash' IS DISTINCT FROM d.source_hash OR p->>'targetMetadataHash' IS DISTINCT FROM d.target_metadata_hash OR p->>'documentHash' IS DISTINCT FROM d.document_hash OR p->>'issuerLegalReference' IS DISTINCT FROM issuer.legal_reference OR nullif(btrim(p->>'legalBasisReference'),'') IS NULL OR nullif(btrim(p->>'journalPurposeReference'),'') IS NULL OR isfinite(issued) IS DISTINCT FROM true OR isfinite(expires) IS DISTINCT FROM true OR isfinite(deadline) IS DISTINCT FROM true OR isfinite(journal_end) IS DISTINCT FROM true OR issued>now() OR expires<=now() OR issued<issuer.valid_from OR expires>issuer.valid_to OR journal_end<=now() OR journal_end<deadline THEN RETURN NULL;END IF;
 RETURN p;
EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN NULL;
END$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_lock_reviewer_v1(c uuid,actor uuid,k text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE permission text;BEGIN
 IF public.ediel_retention_lock_auth_actor_v1(actor) IS NOT TRUE THEN RAISE EXCEPTION 'decision_evidence_current_reviewer_required' USING ERRCODE='42501';END IF;
 PERFORM id FROM public.user_profiles WHERE id=actor FOR SHARE;PERFORM user_id FROM public.company_memberships WHERE company_id=c AND user_id=actor FOR SHARE;
 SELECT permission_key INTO STRICT permission FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=k;
 IF NOT EXISTS(SELECT FROM public.user_profiles WHERE id=actor AND user_status='active' AND disabled_at IS NULL) OR NOT EXISTS(SELECT FROM public.company_memberships WHERE company_id=c AND user_id=actor AND status='active' AND is_active AND accepted_at IS NOT NULL) OR gridex_ediel_retention.permission_v1(c,actor,'ediel.retention.review') IS NOT TRUE OR gridex_ediel_retention.permission_v1(c,actor,permission) IS NOT TRUE THEN RAISE EXCEPTION 'decision_evidence_current_reviewer_required' USING ERRCODE='42501';END IF;
END$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_revocation_lock_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN
 PERFORM id FROM gridex_ediel_retention.decision_evidence_policies WHERE id=NEW.policy_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'decision_evidence_revocation_original_required';END IF;RETURN NEW;
END$$;
CREATE TRIGGER decision_evidence_revocation_lock BEFORE INSERT ON gridex_ediel_retention.decision_evidence_revocations FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.decision_evidence_revocation_lock_v1();
-- Serialize this private workflow before either the policy or its original is
-- locked, including idempotent intake versus purge. No auth result is cached.
CREATE FUNCTION gridex_ediel_retention.decision_evidence_lock_v1(c uuid) RETURNS void LANGUAGE sql SET search_path=pg_catalog AS $$SELECT pg_advisory_xact_lock(hashtextextended('gridex:retention:decision-original:'||c::text,0))$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_policy_current_v1(d gridex_ediel_retention.decision_evidence_policies) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r gridex_ediel_retention.decision_evidence_reviews%rowtype;b jsonb;BEGIN
 IF gridex_ediel_retention.decision_evidence_receipt_v1(d) IS NULL OR EXISTS(SELECT FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=d.retention_class AND target_id=d.target_id) THEN RETURN false;END IF;
 SELECT * INTO r FROM gridex_ediel_retention.decision_evidence_reviews WHERE policy_id=d.id ORDER BY created_at DESC,id DESC LIMIT 1 FOR SHARE;
 IF r.outcome IS DISTINCT FROM 'approved' OR r.actor_user_id=d.submitted_by THEN RETURN false;END IF;
 PERFORM gridex_ediel_retention.decision_evidence_lock_reviewer_v1(d.company_id,r.actor_user_id,d.retention_class);b:=gridex_ediel_retention.decision_evidence_basis_v1(d.company_id,d.retention_class,d.target_id);RETURN b->>'sourceHash'=d.source_hash AND b->>'targetMetadataHash'=d.target_metadata_hash;
EXCEPTION WHEN insufficient_privilege THEN RETURN false;WHEN raise_exception THEN IF SQLERRM IN('decision_evidence_actual_original_bytes_required','decision_evidence_original_scope_required') THEN RETURN false;END IF;RAISE;
END$$;
CREATE FUNCTION public.ediel_submit_decision_evidence_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid,p_document_base64 text,p_issuer_receipt jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE basis jsonb;bytes bytea;h text;d gridex_ediel_retention.decision_evidence_policies%rowtype;BEGIN
 PERFORM gridex_ediel_retention.decision_evidence_lock_v1(p_company_id);
 PERFORM gridex_ediel_retention.decision_evidence_actor_v1(p_company_id,p_actor_user_id,p_retention_class,'ediel.retention.submit');basis:=gridex_ediel_retention.decision_evidence_basis_v1(p_company_id,p_retention_class,p_target_id);
 IF length(p_document_base64)>1398104 THEN RAISE EXCEPTION 'decision_evidence_document_limit';END IF;bytes:=decode(p_document_base64,'base64');IF octet_length(bytes) NOT BETWEEN 1 AND 1048576 THEN RAISE EXCEPTION 'decision_evidence_document_required';END IF;h:=encode(sha256(bytes),'hex');
 INSERT INTO gridex_ediel_retention.decision_evidence_policies(company_id,retention_class,target_id,source_hash,target_metadata_hash,document_bytes,document_hash,issuer_receipt,submitted_by) VALUES(p_company_id,p_retention_class,p_target_id,basis->>'sourceHash',basis->>'targetMetadataHash',bytes,h,p_issuer_receipt,p_actor_user_id) ON CONFLICT(company_id,retention_class,target_id,source_hash,document_hash) DO NOTHING;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.decision_evidence_policies WHERE company_id=p_company_id AND retention_class=p_retention_class AND target_id=p_target_id AND source_hash=basis->>'sourceHash' AND document_hash=h FOR UPDATE;
 IF d.issuer_receipt IS DISTINCT FROM p_issuer_receipt OR d.target_metadata_hash IS DISTINCT FROM basis->>'targetMetadataHash' OR d.document_bytes IS DISTINCT FROM bytes THEN RAISE EXCEPTION 'decision_evidence_original_policy_conflict';END IF;
 INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'retention_decision_original',d.id,'ediel.retention.decision_original_submitted',jsonb_build_object('retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'documentHash',d.document_hash));
 RETURN jsonb_build_object('status','submitted','policyId',d.id,'retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'documentHash',d.document_hash,'issuerQualified',gridex_ediel_retention.decision_evidence_receipt_v1(d) IS NOT NULL);
END$$;
CREATE FUNCTION public.ediel_review_decision_evidence_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_policy_id uuid,p_outcome text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.decision_evidence_policies%rowtype;p jsonb;basis jsonb;r uuid;outcome text;BEGIN
 PERFORM gridex_ediel_retention.decision_evidence_lock_v1(p_company_id);
 SELECT * INTO STRICT d FROM gridex_ediel_retention.decision_evidence_policies WHERE id=p_policy_id AND company_id=p_company_id FOR UPDATE;PERFORM gridex_ediel_retention.decision_evidence_actor_v1(p_company_id,p_actor_user_id,d.retention_class,'ediel.retention.review');
 IF p_outcome NOT IN('approve','hold','reject') OR nullif(btrim(p_reason),'') IS NULL OR length(p_reason)>4000 THEN RAISE EXCEPTION 'decision_evidence_review_shape_required';END IF;
 IF p_outcome='approve' AND d.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'decision_evidence_separate_reviewer_required';END IF;
 p:=gridex_ediel_retention.decision_evidence_receipt_v1(d);basis:=gridex_ediel_retention.decision_evidence_basis_v1(p_company_id,d.retention_class,d.target_id);
 outcome:=CASE WHEN p_outcome='reject' THEN 'rejected' WHEN p_outcome='approve' AND p IS NOT NULL AND basis->>'sourceHash'=d.source_hash AND basis->>'targetMetadataHash'=d.target_metadata_hash THEN 'approved' ELSE 'held' END;
 INSERT INTO gridex_ediel_retention.decision_evidence_reviews(policy_id,actor_user_id,outcome,reason) VALUES(d.id,p_actor_user_id,outcome,p_reason) RETURNING id INTO r;
 INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'retention_decision_original',d.id,'ediel.retention.decision_original_reviewed',jsonb_build_object('reviewId',r,'outcome',outcome));RETURN jsonb_build_object('status',outcome,'policyId',d.id,'reviewId',r);
END$$;
CREATE FUNCTION public.ediel_revoke_decision_evidence_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_policy_id uuid,p_reason text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.decision_evidence_policies%rowtype;BEGIN
 PERFORM gridex_ediel_retention.decision_evidence_lock_v1(p_company_id);
 SELECT * INTO STRICT d FROM gridex_ediel_retention.decision_evidence_policies WHERE id=p_policy_id AND company_id=p_company_id FOR UPDATE;PERFORM gridex_ediel_retention.decision_evidence_actor_v1(p_company_id,p_actor_user_id,d.retention_class,'ediel.retention.review');IF nullif(btrim(p_reason),'') IS NULL OR length(p_reason)>4000 THEN RAISE EXCEPTION 'decision_evidence_revoke_reason_required';END IF;
 INSERT INTO gridex_ediel_retention.decision_evidence_revocations(policy_id,actor_user_id,reason) VALUES(d.id,p_actor_user_id,p_reason) ON CONFLICT DO NOTHING;
END$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_transition_v1(tab text,o jsonb,n jsonb) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE k text;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;BEGIN
 SELECT retention_class INTO k FROM gridex_ediel_retention.decision_evidence_catalog WHERE source_table=tab;SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=k AND target_id=(o->>'id')::uuid AND company_id=(o->>'company_id')::uuid;
 RETURN t.target_id IS NOT NULL AND o->>'document_bytes' IS NOT NULL AND n->>'document_bytes' IS NULL AND (n->>'document_purged_at')::timestamptz=t.created_at AND (n->>'document_byte_length')::bigint=t.byte_length AND o->>'document_hash'=t.source_hash AND encode(sha256(convert_to((o-ARRAY['document_bytes','document_byte_length','document_purged_at'])::text,'UTF8')),'hex')=t.target_metadata_hash AND (o-ARRAY['document_bytes','document_byte_length','document_purged_at'])=(n-ARRAY['document_bytes','document_byte_length','document_purged_at']);
END$$;
CREATE FUNCTION gridex_ediel_retention.decision_evidence_original_insert_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN
 IF NEW.document_bytes IS NULL OR NEW.document_purged_at IS NOT NULL OR octet_length(NEW.document_bytes) NOT BETWEEN 1 AND 1048576 OR encode(sha256(NEW.document_bytes),'hex') IS DISTINCT FROM NEW.document_hash OR NEW.document_byte_length IS NOT NULL AND NEW.document_byte_length<>octet_length(NEW.document_bytes) THEN RAISE EXCEPTION 'decision_original_new_actual_bytes_required';END IF;RETURN NEW;
END$$;
-- Add nullable byte custody metadata only; no historical original UPDATE is
-- performed. The old immutable trigger body still rejects every other change.
DO $$DECLARE spec record;f record;body text;definition text;name text;before_oid oid;before_owner oid;before_acl aclitem[];before_config text[];BEGIN
 FOR spec IN SELECT * FROM gridex_ediel_retention.decision_evidence_catalog LOOP
  IF spec.source_table<>'decision_evidence_policies' THEN
   EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ADD COLUMN document_byte_length bigint,ADD COLUMN document_purged_at timestamptz,ALTER COLUMN document_bytes DROP NOT NULL',spec.source_table);
   EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ADD CONSTRAINT decision_original_byte_custody CHECK(document_bytes IS NOT NULL AND document_purged_at IS NULL OR document_bytes IS NULL AND document_purged_at IS NOT NULL AND document_byte_length>0)',spec.source_table);
   SELECT p.oid,p.proowner,p.proacl,p.proconfig,p.prosrc,pg_get_functiondef(p.oid) definition INTO STRICT f FROM pg_proc p WHERE p.oid=format('gridex_ediel_retention.%I(gridex_ediel_retention.%I)',spec.receipt_function,spec.source_table)::regprocedure;
   IF f.prosrc!~*'\mBEGIN\M' OR f.prosrc!~'d\.issuer_receipt' THEN RAISE EXCEPTION 'decision_original_receipt_source_review_required';END IF;
   body:=regexp_replace(f.prosrc,'\mBEGIN\M','BEGIN IF d.document_bytes IS NULL OR encode(sha256(d.document_bytes),''hex'') IS DISTINCT FROM d.document_hash THEN RETURN NULL;END IF;','i');
   before_oid:=f.oid;before_owner:=f.proowner;before_acl:=f.proacl;before_config:=f.proconfig;EXECUTE replace(f.definition,f.prosrc,body);
   IF NOT EXISTS(SELECT FROM pg_proc p WHERE p.oid=before_oid AND p.proowner=before_owner AND p.proacl IS NOT DISTINCT FROM before_acl AND p.proconfig IS NOT DISTINCT FROM before_config) THEN RAISE EXCEPTION 'decision_original_receipt_identity_changed';END IF;
  END IF;
  EXECUTE format('CREATE TRIGGER decision_original_insert BEFORE INSERT ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.decision_evidence_original_insert_v1()',spec.source_table);
  SELECT t.oid trigger_oid,t.tgname,t.tgenabled,p.prosrc,p.proowner,p.proconfig,p.prosecdef INTO STRICT f FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid WHERE t.tgrelid=format('gridex_ediel_retention.%I',spec.source_table)::regclass AND t.tgname IN('immutable',spec.source_table||'_immutable') AND NOT t.tgisinternal;
  IF f.prosrc!~*'\mBEGIN\M' OR f.prosrc!~*'RAISE\s+EXCEPTION' OR f.tgenabled NOT IN('O','A') THEN RAISE EXCEPTION 'decision_original_guard_source_review_required';END IF;
  name:=spec.source_table||'_original_guard_v1';body:=regexp_replace(f.prosrc,'\mBEGIN\M','BEGIN IF TG_OP=''UPDATE'' AND gridex_ediel_retention.decision_evidence_transition_v1(TG_TABLE_NAME,to_jsonb(OLD),to_jsonb(NEW)) IS TRUE THEN RETURN NEW;END IF;','i');
  EXECUTE format('CREATE FUNCTION gridex_ediel_retention.%I() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS %L',name,body);EXECUTE format('ALTER FUNCTION gridex_ediel_retention.%I() OWNER TO gridex_ediel_retention_owner',name);EXECUTE format('REVOKE ALL ON FUNCTION gridex_ediel_retention.%I() FROM PUBLIC,anon,authenticated,service_role',name);
  definition:=pg_get_triggerdef(f.trigger_oid);EXECUTE format('DROP TRIGGER %I ON gridex_ediel_retention.%I',f.tgname,spec.source_table);EXECUTE regexp_replace(definition,'EXECUTE (FUNCTION|PROCEDURE) .*$',format('EXECUTE FUNCTION gridex_ediel_retention.%I()',name));IF f.tgenabled='A' THEN EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ENABLE ALWAYS TRIGGER %I',spec.source_table,f.tgname);END IF;
 END LOOP;
END$$;
CREATE FUNCTION public.ediel_purge_decision_evidence_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_policy_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.decision_evidence_policies%rowtype;r gridex_ediel_retention.decision_evidence_reviews%rowtype;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;spec gridex_ediel_retention.decision_evidence_catalog%rowtype;p jsonb;basis jsonb;at timestamptz:=clock_timestamp();BEGIN
 PERFORM gridex_ediel_retention.decision_evidence_lock_v1(p_company_id);
 SELECT * INTO STRICT d FROM gridex_ediel_retention.decision_evidence_policies WHERE id=p_policy_id AND company_id=p_company_id FOR UPDATE;PERFORM gridex_ediel_retention.decision_evidence_actor_v1(p_company_id,p_actor_user_id,d.retention_class,'ediel.retention.purge');
 SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=d.retention_class AND target_id=d.target_id;
 IF FOUND THEN IF t.policy_id IS DISTINCT FROM d.id OR t.company_id IS DISTINCT FROM p_company_id THEN RAISE EXCEPTION 'decision_original_purge_replay_conflict';END IF;RETURN jsonb_build_object('status','purged','retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',t.source_hash,'byteLength',t.byte_length,'bytesAvailable',false,'authority','none','replay',true);END IF;
 SELECT * INTO r FROM gridex_ediel_retention.decision_evidence_reviews WHERE policy_id=d.id ORDER BY created_at DESC,id DESC LIMIT 1 FOR SHARE;
 IF r.outcome IS DISTINCT FROM 'approved' OR r.actor_user_id=d.submitted_by THEN RETURN jsonb_build_object('status','held','policyId',d.id,'missing',ARRAY['separate_current_original_class_review']);END IF;
 PERFORM gridex_ediel_retention.decision_evidence_lock_reviewer_v1(p_company_id,r.actor_user_id,d.retention_class);p:=gridex_ediel_retention.decision_evidence_receipt_v1(d);
 IF p IS NULL OR (p->>'retainUntil')::timestamptz>at THEN RETURN jsonb_build_object('status','held','policyId',d.id,'missing',ARRAY['current_exact_original_deadline']);END IF;
 basis:=gridex_ediel_retention.decision_evidence_basis_v1(p_company_id,d.retention_class,d.target_id);IF basis->>'sourceHash' IS DISTINCT FROM d.source_hash OR basis->>'targetMetadataHash' IS DISTINCT FROM d.target_metadata_hash THEN RETURN jsonb_build_object('status','held','policyId',d.id,'missing',ARRAY['unchanged_original_source_metadata']);END IF;
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=d.retention_class;
 -- Invalidate the consumed original policy before physical byte removal. Its
 -- already completed receipts remain available as immutable historical facts.
 EXECUTE format('INSERT INTO gridex_ediel_retention.%I(%I,actor_user_id,reason) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',spec.revocation_table,spec.revocation_id_column) USING d.target_id,p_actor_user_id,left('Qualified decision-original policy: '||(p->>'legalBasisReference'),4000);
 INSERT INTO gridex_ediel_retention.decision_evidence_tombstones(retention_class,target_id,company_id,policy_id,review_id,source_hash,target_metadata_hash,byte_length,actor_user_id,journal_retain_until,journal_purpose_reference,created_at) VALUES(d.retention_class,d.target_id,p_company_id,d.id,r.id,d.source_hash,d.target_metadata_hash,(basis->>'byteLength')::bigint,p_actor_user_id,(p->>'journalRetainUntil')::timestamptz,p->>'journalPurposeReference',at);
 EXECUTE format('UPDATE gridex_ediel_retention.%I SET document_bytes=NULL,document_byte_length=$1,document_purged_at=$2 WHERE id=$3 AND company_id=$4',spec.source_table) USING (basis->>'byteLength')::bigint,at,d.target_id,p_company_id;
 INSERT INTO public.audit_logs(actor_user_id,company_id,entity_type,entity_id,action,metadata) VALUES(p_actor_user_id,p_company_id,'retention_decision_original',d.target_id,'ediel.retention.decision_original_bytes_removed',jsonb_build_object('policyId',d.id,'reviewId',r.id,'retentionClass',d.retention_class,'sourceHash',d.source_hash,'byteLength',(basis->>'byteLength')::bigint,'journalRetainUntil',p->>'journalRetainUntil','journalPurposeReference',p->>'journalPurposeReference','freshAuthorityRevoked',true));
 RETURN jsonb_build_object('status','purged','retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'byteLength',(basis->>'byteLength')::bigint,'bytesAvailable',false,'authority','none','replay',false);
END$$;
CREATE FUNCTION public.ediel_read_retention_decision_original_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid,p_include_document boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE tab text;r jsonb;b bytea;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;BEGIN
 PERFORM gridex_ediel_retention.decision_evidence_lock_v1(p_company_id);
 PERFORM gridex_ediel_retention.decision_evidence_read_actor_v1(p_company_id,p_actor_user_id,p_retention_class);IF p_include_document THEN PERFORM gridex_ediel_retention.decision_evidence_actor_v1(p_company_id,p_actor_user_id,p_retention_class,'ediel.retention.review');END IF;
 SELECT source_table INTO STRICT tab FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=p_retention_class;EXECUTE format('SELECT to_jsonb(d),d.document_bytes FROM gridex_ediel_retention.%I d WHERE id=$1 AND company_id=$2 FOR SHARE',tab) INTO r,b USING p_target_id,p_company_id;IF r IS NULL THEN RAISE EXCEPTION 'decision_evidence_original_scope_required';END IF;
 SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=p_retention_class AND target_id=p_target_id AND company_id=p_company_id;
 IF b IS NULL AND (t.target_id IS NULL OR r->>'document_hash' IS DISTINCT FROM t.source_hash) OR b IS NOT NULL AND encode(sha256(b),'hex') IS DISTINCT FROM r->>'document_hash' THEN RAISE EXCEPTION 'decision_evidence_original_custody_mismatch';END IF;
 RETURN jsonb_build_object('companyId',p_company_id,'retentionClass',p_retention_class,'targetId',p_target_id,'documentHash',r->>'document_hash','documentByteLength',coalesce(octet_length(b),t.byte_length),'bytesAvailable',b IS NOT NULL,'documentBase64',CASE WHEN p_include_document AND b IS NOT NULL THEN replace(encode(b,'base64'),E'\n','') ELSE NULL END,'purgedAt',t.created_at,'authority','none');
END$$;
CREATE FUNCTION public.ediel_read_decision_evidence_policy_v1(p_company_id uuid,p_actor_user_id uuid,p_policy_id uuid,p_include_document boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.decision_evidence_policies%rowtype;p jsonb;r jsonb;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;bytes_length bigint;BEGIN
 PERFORM gridex_ediel_retention.decision_evidence_lock_v1(p_company_id);
 SELECT * INTO STRICT d FROM gridex_ediel_retention.decision_evidence_policies WHERE id=p_policy_id AND company_id=p_company_id FOR SHARE;PERFORM gridex_ediel_retention.decision_evidence_read_actor_v1(p_company_id,p_actor_user_id,d.retention_class);IF p_include_document THEN PERFORM gridex_ediel_retention.decision_evidence_actor_v1(p_company_id,p_actor_user_id,d.retention_class,'ediel.retention.review');END IF;
 IF d.document_bytes IS NOT NULL AND encode(sha256(d.document_bytes),'hex') IS DISTINCT FROM d.document_hash THEN RAISE EXCEPTION 'decision_evidence_policy_original_hash_required';END IF;
 p:=gridex_ediel_retention.decision_evidence_receipt_v1(d);SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=d.retention_class AND target_id=d.target_id AND company_id=p_company_id;
 SELECT coalesce(jsonb_agg(jsonb_build_object('reviewId',id,'actorUserId',actor_user_id,'outcome',outcome,'reason',reason,'createdAt',created_at) ORDER BY created_at,id),'[]') INTO r FROM gridex_ediel_retention.decision_evidence_reviews WHERE policy_id=d.id;
 bytes_length:=coalesce(octet_length(d.document_bytes),d.document_byte_length);
 RETURN jsonb_build_object('companyId',d.company_id,'policyId',d.id,'retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'targetMetadataHash',d.target_metadata_hash,'documentHash',d.document_hash,'documentByteLength',bytes_length,'bytesAvailable',d.document_bytes IS NOT NULL,'documentBase64',CASE WHEN p_include_document AND d.document_bytes IS NOT NULL THEN replace(encode(d.document_bytes,'base64'),E'\n','') ELSE NULL END,'submittedBy',d.submitted_by,'createdAt',d.created_at,'issuerQualified',p IS NOT NULL,'currentQualified',gridex_ediel_retention.decision_evidence_policy_current_v1(d),'revoked',EXISTS(SELECT FROM gridex_ediel_retention.decision_evidence_revocations WHERE policy_id=d.id),'reviews',r,'purge',CASE WHEN t.target_id IS NULL THEN NULL ELSE jsonb_build_object('purgedAt',t.created_at,'sourceHash',t.source_hash,'byteLength',t.byte_length) END,'authority','none');
END$$;
-- Extend only the exact standalone session class whitelist. Its current auth
-- bridge, own membership, DENY and operation+class gate remain the same body.
DO $$DECLARE f record;body text;needle text:='''ediel.retention.legal_history'']';extra text:='''ediel.retention.legal_history'',''ediel.retention.artifact_decision_evidence'',''ediel.retention.blob_decision_evidence'',''ediel.retention.record_decision_evidence'',''ediel.retention.process_decision_evidence'',''ediel.retention.decision_policy_evidence'',''ediel.retention.billing_source_evidence'',''ediel.retention.invoice_copy_evidence'',''ediel.retention.settlement_copy_evidence'']';BEGIN
 SELECT p.oid,p.proowner,p.proacl,p.proconfig,p.prosrc,pg_get_functiondef(p.oid) definition INTO STRICT f FROM pg_proc p WHERE p.oid='gridex_ediel_retention.permission_v1(uuid,uuid,text)'::regprocedure;
 IF f.prosrc!~'retention_keys constant text\[\]' OR f.prosrc!~'ediel_retention_lock_auth_actor_v1' OR f.prosrc!~'company_id=c' OR f.prosrc!~'effect=''deny''' OR position('''ediel.retention.mime_bytes'']' in f.prosrc)=0 THEN RAISE EXCEPTION 'decision_evidence_permission_source_review_required';END IF;
 body:=replace(f.prosrc,'''ediel.retention.mime_bytes'']','''ediel.retention.mime_bytes'',''ediel.retention.artifact_decision_evidence'',''ediel.retention.blob_decision_evidence'',''ediel.retention.record_decision_evidence'',''ediel.retention.process_decision_evidence'',''ediel.retention.decision_policy_evidence'',''ediel.retention.billing_source_evidence'',''ediel.retention.invoice_copy_evidence'',''ediel.retention.settlement_copy_evidence'']');EXECUTE replace(f.definition,f.prosrc,body);
 IF NOT EXISTS(SELECT FROM pg_proc p WHERE p.oid=f.oid AND p.proowner=f.proowner AND p.proacl IS NOT DISTINCT FROM f.proacl AND p.proconfig IS NOT DISTINCT FROM f.proconfig) THEN RAISE EXCEPTION 'decision_evidence_permission_identity_changed';END IF;
 SELECT p.oid,p.proowner,p.proacl,p.proconfig,p.prosrc,pg_get_functiondef(p.oid) definition INTO STRICT f FROM pg_proc p WHERE p.oid='public.ediel_current_retention_session_v1(uuid,uuid)'::regprocedure;
 IF position(needle in f.prosrc)=0 OR f.prosrc!~'retention_current_explicit_session_required' OR f.prosrc!~'ediel_retention_session_actor_v1' OR f.prosrc!~'record_permission_v1' THEN RAISE EXCEPTION 'decision_evidence_session_source_review_required';END IF;
 body:=replace(f.prosrc,needle,extra);EXECUTE replace(f.definition,f.prosrc,body);
 IF NOT EXISTS(SELECT FROM pg_proc p WHERE p.oid=f.oid AND p.proowner=f.proowner AND p.proacl IS NOT DISTINCT FROM f.proacl AND p.proconfig IS NOT DISTINCT FROM f.proconfig) THEN RAISE EXCEPTION 'decision_evidence_session_identity_changed';END IF;
 -- Company-list delegates to this exact session for each actual own membership.
 SELECT p.prosrc INTO STRICT body FROM pg_proc p WHERE p.oid='public.ediel_current_retention_companies_v1()'::regprocedure;IF body!~'public.ediel_current_retention_session_v1\(company.id,actor\)' OR body!~'ediel_retention_session_actor_v1' THEN RAISE EXCEPTION 'decision_evidence_company_list_source_review_required';END IF;
END$$;
DO $$DECLARE f record;BEGIN
 FOR f IN SELECT p.oid::regprocedure signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_ediel_retention' AND p.proname LIKE 'decision_evidence_%' OR n.nspname='public' AND p.proname IN('ediel_submit_decision_evidence_retention_v1','ediel_review_decision_evidence_retention_v1','ediel_revoke_decision_evidence_retention_v1','ediel_purge_decision_evidence_retention_v1','ediel_read_retention_decision_original_v1','ediel_read_decision_evidence_policy_v1') LOOP
  EXECUTE format('ALTER FUNCTION %s OWNER TO gridex_ediel_retention_owner',f.signature);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.signature);
 END LOOP;
END$$;
GRANT EXECUTE ON FUNCTION public.ediel_submit_decision_evidence_retention_v1(uuid,uuid,text,uuid,text,jsonb),public.ediel_review_decision_evidence_retention_v1(uuid,uuid,uuid,text,text),public.ediel_revoke_decision_evidence_retention_v1(uuid,uuid,uuid,text),public.ediel_purge_decision_evidence_retention_v1(uuid,uuid,uuid),public.ediel_read_retention_decision_original_v1(uuid,uuid,text,uuid,boolean),public.ediel_read_decision_evidence_policy_v1(uuid,uuid,uuid,boolean) TO authenticated;
REVOKE CREATE ON SCHEMA public FROM gridex_ediel_retention_owner;
COMMIT;
