-- Non-death incoming Z06E has an independent bilateral source owner. Actual
-- local inbound attribution is not remote signature authentication. Unseeded
-- counterparty keys/mandates below are NEVER granted to application roles.
BEGIN;
-- Explicit current company DENY wins over every direct/role allow. Existing
-- permission/catalog/role/member locks remain held through the transaction.
CREATE OR REPLACE FUNCTION gridex_requested_changes.scoped_permission_v1(c uuid,actor uuid,wanted text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 PERFORM p.id FROM public.permissions p WHERE p.key=wanted ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.user_permissions p WHERE p.user_id=actor AND p.company_id=c ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.user_roles p WHERE p.user_id=actor AND p.company_id=c ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.roles p WHERE EXISTS(SELECT FROM public.user_roles u WHERE u.user_id=actor AND u.company_id=c AND u.role_id=p.id) ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.role_permissions p WHERE EXISTS(SELECT FROM public.user_roles u WHERE u.user_id=actor AND u.company_id=c AND u.role_id=p.role_id) ORDER BY p.id FOR SHARE;
 RETURN NOT EXISTS(SELECT FROM public.user_permission_overrides d WHERE d.user_id=actor AND (d.company_id IS NULL OR d.company_id=c) AND d.is_active AND d.effect='deny' AND d.permission_key=wanted AND (d.valid_from IS NULL OR d.valid_from<=now()) AND (d.valid_to IS NULL OR now()<d.valid_to))
 AND NOT EXISTS(SELECT FROM public.user_permissions u JOIN public.permissions p ON p.id=u.permission_id OR u.permission_id IS NULL AND p.key=u.permission_key WHERE u.user_id=actor AND (u.company_id IS NULL OR u.company_id=c) AND u.is_active AND u.status='active' AND u.effect='deny' AND p.is_active AND p.key=wanted)
 AND NOT EXISTS(SELECT FROM public.user_roles u JOIN public.roles r ON r.id=u.role_id JOIN public.role_permissions rp ON rp.role_id=r.id JOIN public.permissions p ON p.id=rp.permission_id OR rp.permission_id IS NULL AND p.key=rp.permission_key WHERE u.user_id=actor AND u.company_id=c AND u.is_active AND u.status='active' AND r.is_active AND rp.effect='deny' AND p.is_active AND p.key=wanted)
 AND (EXISTS(SELECT FROM public.user_permissions u JOIN public.permissions p ON p.id=u.permission_id OR u.permission_id IS NULL AND p.key=u.permission_key WHERE u.user_id=actor AND u.company_id=c AND u.is_active AND u.status='active' AND u.effect='allow' AND p.is_active AND p.key=wanted)
 OR EXISTS(SELECT FROM public.user_roles u JOIN public.roles r ON r.id=u.role_id JOIN public.role_permissions rp ON rp.role_id=r.id JOIN public.permissions p ON p.id=rp.permission_id OR rp.permission_id IS NULL AND p.key=rp.permission_key WHERE u.user_id=actor AND u.company_id=c AND u.is_active AND u.status='active' AND r.is_active AND rp.effect='allow' AND p.is_active AND p.key=wanted));
END$$;
CREATE OR REPLACE FUNCTION gridex_requested_changes.actor_v1(c uuid,actor uuid,mode text,kind text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 PERFORM id FROM auth.users WHERE id=actor FOR SHARE;PERFORM id FROM public.user_profiles WHERE id=actor FOR SHARE;PERFORM user_id FROM public.company_memberships WHERE company_id=c AND user_id=actor FOR SHARE;
 RETURN actor IS NOT NULL AND mode IN('archive','read','review') AND EXISTS(SELECT FROM public.user_profiles WHERE id=actor AND user_status='active') AND EXISTS(SELECT FROM public.company_memberships WHERE company_id=c AND user_id=actor AND status='active' AND is_active AND accepted_at IS NOT NULL)
 AND EXISTS(SELECT FROM auth.users WHERE id=actor AND deleted_at IS NULL AND (banned_until IS NULL OR banned_until<=now()))
 AND gridex_requested_changes.scoped_permission_v1(c,actor,CASE mode WHEN 'read' THEN 'communication.read' ELSE 'communication.write' END) IS TRUE
 AND gridex_requested_changes.scoped_permission_v1(c,actor,CASE mode WHEN 'read' THEN 'customers.read' ELSE 'customers.write' END) IS TRUE
 AND (kind='death' OR gridex_requested_changes.scoped_permission_v1(c,actor,CASE mode WHEN 'read' THEN 'contracts.read' ELSE 'contracts.write' END) IS TRUE)
 AND (mode<>'review' OR gridex_requested_changes.scoped_permission_v1(c,actor,'ediel.source.review') IS TRUE);
END$$;
CREATE SCHEMA gridex_bilateral_customer_sources;
REVOKE ALL ON SCHEMA gridex_bilateral_customer_sources FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE gridex_bilateral_customer_sources.artifacts(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL,
 source_message_id uuid NOT NULL REFERENCES public.ediel_messages(id),agreement_id uuid NOT NULL REFERENCES public.tenant_bilateral_agreements(id),supply_period_id uuid NOT NULL REFERENCES public.customer_supply_periods(id),contract_id uuid NOT NULL REFERENCES public.customer_contracts(id),
 claims jsonb NOT NULL,claims_hash text NOT NULL CHECK(claims_hash~'^[a-f0-9]{64}$'),source_bytes bytea NOT NULL CHECK(octet_length(source_bytes) BETWEEN 1 AND 8388608),source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),source_reference text NOT NULL,source_version text NOT NULL,issuer_receipt jsonb,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(company_id,environment,source_hash,claims_hash));
CREATE TABLE gridex_bilateral_customer_sources.reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),artifact_id uuid NOT NULL REFERENCES gridex_bilateral_customer_sources.artifacts(id),company_id uuid NOT NULL,reviewer_user_id uuid NOT NULL REFERENCES auth.users(id),decision text NOT NULL CHECK(decision IN('approved','held','rejected')),reason text NOT NULL,clause jsonb,missing jsonb NOT NULL DEFAULT '[]',reviewed_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_bilateral_customer_sources.origins(artifact_id uuid PRIMARY KEY REFERENCES gridex_bilateral_customer_sources.artifacts(id),review_id uuid NOT NULL UNIQUE REFERENCES gridex_bilateral_customer_sources.reviews(id),company_id uuid NOT NULL,source_message_id uuid NOT NULL UNIQUE REFERENCES public.ediel_messages(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_bilateral_customer_sources.issuer_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,environment text NOT NULL,counterparty_actor_id uuid NOT NULL,legal_authority_reference text NOT NULL CHECK(length(legal_authority_reference)>0),legal_authority_hash text NOT NULL CHECK(legal_authority_hash~'^[a-f0-9]{64}$'),receipt_signing_key bytea NOT NULL CHECK(octet_length(receipt_signing_key)>=32),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(valid_to>valid_from));
CREATE TABLE gridex_bilateral_customer_sources.representations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,environment text NOT NULL,issuer_key_id uuid NOT NULL REFERENCES gridex_bilateral_customer_sources.issuer_keys(id),legal_actor_id uuid NOT NULL,agreement_id uuid NOT NULL REFERENCES public.tenant_bilateral_agreements(id),purpose text NOT NULL CHECK(purpose='prodat_z06e_customer_change'),legal_authority_reference text NOT NULL CHECK(length(legal_authority_reference)>0),legal_authority_hash text NOT NULL CHECK(legal_authority_hash~'^[a-f0-9]{64}$'),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(valid_to>valid_from));
CREATE TABLE gridex_bilateral_customer_sources.revocations(target_kind text NOT NULL CHECK(target_kind IN('key','representation','artifact')),target_id uuid NOT NULL,source_reference text NOT NULL CHECK(length(source_reference)>0),source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),revoked_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(target_kind,target_id));
DO $$DECLARE t text;BEGIN FOR t IN SELECT unnest(ARRAY['artifacts','reviews','origins','issuer_keys','representations','revocations']) LOOP
 EXECUTE format('ALTER TABLE gridex_bilateral_customer_sources.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_bilateral_customer_sources.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_bilateral_customer_sources.%I FROM PUBLIC,anon,authenticated,service_role',t);
 EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON gridex_bilateral_customer_sources.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_immutable',t);EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON gridex_bilateral_customer_sources.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_no_truncate',t);
 END LOOP;END$$;
CREATE FUNCTION gridex_bilateral_customer_sources.revoke_lock_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN
 IF NEW.target_kind='key' THEN PERFORM id FROM gridex_bilateral_customer_sources.issuer_keys WHERE id=NEW.target_id FOR UPDATE;
 ELSIF NEW.target_kind='representation' THEN PERFORM id FROM gridex_bilateral_customer_sources.representations WHERE id=NEW.target_id FOR UPDATE;
 ELSE PERFORM id FROM gridex_bilateral_customer_sources.artifacts WHERE id=NEW.target_id FOR UPDATE;END IF;
 IF NOT FOUND THEN RAISE EXCEPTION 'bilateral_customer_source_revocation_target_required';END IF;RETURN NEW;END$$;
CREATE TRIGGER bilateral_customer_source_revoke_lock BEFORE INSERT ON gridex_bilateral_customer_sources.revocations FOR EACH ROW EXECUTE FUNCTION gridex_bilateral_customer_sources.revoke_lock_v1();
-- All native facts are reconstructed, including original full customer and
-- invoicee tokens. No source selector/parsed proposal is a business approval.
CREATE FUNCTION gridex_bilateral_customer_sources.source_claims_v1(c uuid,source_id uuid,agreement uuid,supply_id uuid,contract_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE m public.ediel_messages%rowtype;s gridex_received_sources.sources%rowtype;a gridex_received_sources.validation_assessments%rowtype;ba public.tenant_bilateral_agreements%rowtype;sp public.customer_supply_periods%rowtype;cc public.customer_contracts%rowtype;mp public.metering_points%rowtype;
 tokens jsonb;own_tokens jsonb;lin jsonb;ud jsonb;iv jsonb;dtm jsonb;supply jsonb;at timestamptz;first_lin int;last_lin int;n int;sender text;legal_actor uuid;counterparty uuid;customer_tokens jsonb;party jsonb;
BEGIN
 SELECT * INTO m FROM public.ediel_messages WHERE id=source_id AND company_id=c FOR SHARE;
 IF NOT FOUND OR m.direction IS DISTINCT FROM 'inbound' OR m.message_standard IS DISTINCT FROM 'edifact' OR m.message_family IS DISTINCT FROM 'PRODAT' OR m.message_code IS DISTINCT FROM 'Z06' THEN RAISE EXCEPTION 'bilateral_customer_source_original_required';END IF;
 PERFORM gridex_ediel_inbound_context.require_v1(c,m.id);PERFORM gridex_ediel_source_rules.require_v1(c,m.id);
 SELECT * INTO s FROM gridex_received_sources.sources WHERE source_message_id=m.id AND company_id=c AND environment=m.environment FOR SHARE;
 IF NOT FOUND OR s.raw_payload IS DISTINCT FROM m.raw_payload OR s.payload_hash IS DISTINCT FROM encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex') OR s.source_received_at IS NULL OR s.source_received_at IS DISTINCT FROM m.message_received_at THEN RAISE EXCEPTION 'bilateral_customer_source_immutable_received_original_required';END IF;
 SELECT count(*) INTO n FROM gridex_received_sources.validation_assessments x WHERE x.source_message_id=m.id AND x.company_id=c AND x.environment=m.environment AND x.source_payload_hash=s.payload_hash AND NOT EXISTS(SELECT FROM gridex_received_sources.validation_assessments child WHERE child.previous_assessment_id=x.id);
 IF n<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_unique_canonical_required';END IF;
 SELECT * INTO a FROM gridex_received_sources.validation_assessments x WHERE x.source_message_id=m.id AND x.company_id=c AND x.environment=m.environment AND x.source_payload_hash=s.payload_hash AND NOT EXISTS(SELECT FROM gridex_received_sources.validation_assessments child WHERE child.previous_assessment_id=x.id) FOR SHARE;
 IF a.facts_text::jsonb->>'syntaxDecision' IS DISTINCT FROM 'accepted' OR a.facts_text::jsonb->>'applicationDecision' IS DISTINCT FROM 'accepted' OR a.facts_text::jsonb->>'functionalDecision' IS DISTINCT FROM 'accepted' THEN RAISE EXCEPTION 'bilateral_customer_source_canonical_accepted_required';END IF;
 tokens:=gridex_received_sources.closure_wire_tokens_v2(s.raw_payload);
 IF (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN')<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='BGM' AND t#>>'{elements,1,0}'='Z06' AND coalesce(t#>>'{elements,3,0}','9')='9')<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_whole_original_required';END IF;
 SELECT t INTO lin FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='LIN';first_lin:=(lin->>'index')::int;
 SELECT min((t->>'index')::int) INTO last_lin FROM jsonb_array_elements(tokens) t WHERE (t->>'index')::int>first_lin AND t->>'tag' IN('UNT','UNZ','UNH','LIN');
 SELECT jsonb_agg(t ORDER BY (t->>'index')::int) INTO own_tokens FROM jsonb_array_elements(tokens) t WHERE (t->>'index')::int>first_lin AND (last_lin IS NULL OR (t->>'index')::int<last_lin);
 IF (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='E34' AND (SELECT p#>>'{elements,2,0}' FROM jsonb_array_elements(own_tokens) p WHERE p->>'tag'='CCI' AND (p->>'index')::int<(t->>'index')::int ORDER BY (p->>'index')::int DESC LIMIT 1)='Z13')<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_z06e_required';END IF;
 IF EXISTS(SELECT FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='CAV' AND t#>>'{elements,1,0}'='Z41') THEN RAISE EXCEPTION 'bilateral_customer_source_cannot_mint_death_fact';END IF;
 IF (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD')<>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV')>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='157' AND t#>>'{elements,1,2}'='203')<>1 OR (SELECT count(*) FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='RFF' AND t#>>'{elements,1,0}'='LI' AND nullif(t#>>'{elements,1,1}','') IS NOT NULL)<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_own_parties_clock_reference_required';END IF;
 SELECT t INTO ud FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD';SELECT t INTO iv FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='IV';SELECT t INTO dtm FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='157';at:=gridex_received_sources.permission_time_v1(dtm#>>'{elements,1,1}');
 IF at IS NULL OR nullif(ud#>>'{elements,2,0}','') IS NULL OR nullif(gridex_ai_processing.party_text_v1(ud,4,2),'') IS NULL THEN RAISE EXCEPTION 'bilateral_customer_source_actual_party_minute_required';END IF;
 SELECT * INTO sp FROM public.customer_supply_periods WHERE id=supply_id AND company_id=c FOR SHARE;SELECT * INTO cc FROM public.customer_contracts WHERE id=contract_id AND company_id=c FOR SHARE;SELECT * INTO mp FROM public.metering_points WHERE id=sp.metering_point_id AND company_id=c FOR SHARE;
 supply:=gridex_received_sources.supply_period_source_basis_v1(c,sp.id,at,at+interval '1 minute');legal_actor:=(supply->>'legalActorId')::uuid;
 IF sp.id IS NULL OR cc.id IS NULL OR mp.id IS NULL OR cc.customer_id IS DISTINCT FROM sp.customer_id OR cc.metering_point_id IS DISTINCT FROM mp.id OR mp.customer_id IS DISTINCT FROM sp.customer_id OR (cc.status IN('signed','active')) IS NOT TRUE OR cc.signed_at IS NULL OR nullif(cc.signed_version,'') IS NULL OR supply->>'qualified' IS DISTINCT FROM 'true' OR supply->>'customerId' IS DISTINCT FROM sp.customer_id::text OR supply->>'meteringPointId' IS DISTINCT FROM mp.id::text OR mp.ediel_metering_point_id IS DISTINCT FROM lin#>>'{elements,3,0}' OR (lin#>>'{elements,3,3}' IN('9','89')) IS NOT TRUE OR supply->>'dsoEdielId' IS DISTINCT FROM m.sender_ediel_id OR mp.grid_owner_ediel_id IS DISTINCT FROM m.sender_ediel_id OR mp.product_direction IS DISTINCT FROM 'consumption' THEN RAISE EXCEPTION 'bilateral_customer_source_current_owned_supply_contract_point_required';END IF;
 PERFORM cs.id FROM public.customer_sites cs WHERE cs.id=coalesce(mp.customer_site_id,mp.site_id) AND cs.company_id=c AND cs.customer_id=sp.customer_id FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'bilateral_customer_source_current_owned_site_required';END IF;
 PERFORM t.id FROM public.tenant_actor_identifiers t WHERE t.company_id=c AND t.environment=m.environment ORDER BY t.id FOR SHARE;PERFORM t.id FROM public.tenant_actor_roles t WHERE t.company_id=c AND t.environment=m.environment ORDER BY t.id FOR SHARE;PERFORM t.id FROM public.tenant_ediel_profiles t WHERE t.company_id=c AND t.environment=m.environment ORDER BY t.id FOR SHARE;
 SELECT min(identifier_value) INTO sender FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=m.environment AND actor_id=legal_actor AND identifier_type='EdielId' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now());
 IF sender IS DISTINCT FROM m.receiver_ediel_id OR (SELECT count(DISTINCT(actor_id,identifier_value)) FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=m.environment AND identifier_type='EdielId' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now()))<>1 OR NOT EXISTS(SELECT FROM public.tenant_actor_roles WHERE company_id=c AND environment=m.environment AND actor_id=legal_actor AND role_code='electricity_supplier' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now())) OR NOT EXISTS(SELECT FROM public.tenant_ediel_profiles WHERE company_id=c AND environment=m.environment AND market='electricity' AND is_enabled AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now())) OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND (t->>'index')::int<first_lin AND t#>>'{elements,1,0}'='FR' AND t#>'{elements,2}'=jsonb_build_array(m.sender_ediel_id,'160','SVK'))<>1 OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND (t->>'index')::int<first_lin AND t#>>'{elements,1,0}'='DO' AND t#>'{elements,2}'=jsonb_build_array(sender,'160','SVK'))<>1 THEN RAISE EXCEPTION 'bilateral_customer_source_exact_current_legal_supplier_required';END IF;
 SELECT * INTO ba FROM public.tenant_bilateral_agreements WHERE id=agreement AND company_id=c AND environment=m.environment FOR SHARE;
 PERFORM i.id FROM public.platform_actor_identifiers i WHERE i.actor_id=ba.counterparty_actor_id ORDER BY i.id FOR SHARE;PERFORM r.id FROM public.platform_actor_roles r WHERE r.actor_id=ba.counterparty_actor_id ORDER BY r.id FOR SHARE;
 IF ba.id IS NULL OR ba.capability_code IS DISTINCT FROM 'prodat_z06e_customer_change' OR ba.is_enabled IS NOT TRUE OR ba.valid_from>now() OR ba.valid_to<=now() OR nullif(ba.source_reference,'') IS NULL OR (SELECT count(DISTINCT i.identifier_value) FROM public.platform_actor_identifiers i WHERE i.actor_id=ba.counterparty_actor_id AND lower(i.identifier_type) IN('edielid','ediel_id') AND i.is_verified AND (i.valid_from IS NULL OR i.valid_from<=current_date) AND (i.valid_to IS NULL OR i.valid_to>=current_date))<>1 OR NOT EXISTS(SELECT FROM public.platform_actor_identifiers i WHERE i.actor_id=ba.counterparty_actor_id AND lower(i.identifier_type) IN('edielid','ediel_id') AND i.is_verified AND i.identifier_value=m.sender_ediel_id AND (i.valid_from IS NULL OR i.valid_from<=current_date) AND (i.valid_to IS NULL OR i.valid_to>=current_date)) OR NOT EXISTS(SELECT FROM public.platform_actor_roles r WHERE r.actor_id=ba.counterparty_actor_id AND r.actor_role='grid_owner' AND r.is_active) THEN RAISE EXCEPTION 'bilateral_customer_source_current_exact_dso_agreement_required';END IF;
 SELECT jsonb_agg(jsonb_build_object('tag',t->>'tag','elements',t->'elements') ORDER BY (t->>'index')::int) INTO customer_tokens FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag' IN('NAD','DTM') AND (t->>'tag'='NAD' AND t#>>'{elements,1,0}' IN('UD','IV') OR t->>'tag'='DTM' AND t#>>'{elements,1,0}'='329');
 party:=jsonb_build_object('id',ud#>>'{elements,2,0}','qualifier',ud#>>'{elements,2,1}','agency',ud#>>'{elements,2,2}','name',gridex_ai_processing.party_text_v1(ud,4,2),'nameLines',ud#>'{elements,4}','addressLines',ud#>'{elements,5}','city',ud#>>'{elements,6,0}','postalCode',ud#>>'{elements,8,0}','country',ud#>>'{elements,9,0}','invoicee',CASE WHEN iv IS NULL THEN NULL ELSE iv->'elements' END,'birthDate',(SELECT t#>>'{elements,1,1}' FROM jsonb_array_elements(own_tokens) t WHERE t->>'tag'='DTM' AND t#>>'{elements,1,0}'='329' LIMIT 1));
 RETURN jsonb_build_object('sourceMessageId',m.id,'payloadHash',s.payload_hash,'canonicalAssessmentId',a.id,'companyId',c,'environment',m.environment,'agreementId',ba.id,'agreementHash',encode(sha256(convert_to((to_jsonb(ba)-ARRAY['updated_at','created_at'])::text,'UTF8')),'hex'),'counterpartyActorId',ba.counterparty_actor_id,'supplyPeriodId',sp.id,'supplySourceMessageId',supply->>'sourceMessageId','supplyStateVersion',supply->'marketStateVersion','contractId',cc.id,'contractHash',gridex_received_sources.production_contract_hash_v1(cc),'customerId',sp.customer_id,'meteringPointId',mp.id,'siteId',coalesce(mp.customer_site_id,mp.site_id),'objectId',lin#>>'{elements,3,0}','identityAgency',lin#>>'{elements,3,3}','legalActorId',legal_actor,'legalSender',m.sender_ediel_id,'legalReceiver',m.receiver_ediel_id,'effectiveAt',at,'sourceReceivedAt',s.source_received_at,'party',party,'customerTokens',customer_tokens);
END$$;
CREATE FUNCTION gridex_bilateral_customer_sources.receipt_current_v1(a gridex_bilateral_customer_sources.artifacts) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE r jsonb:=a.issuer_receipt;k gridex_bilateral_customer_sources.issuer_keys%rowtype;g gridex_bilateral_customer_sources.representations%rowtype;raw bytea;p jsonb;issued timestamptz;expires timestamptz;
BEGIN
 IF r IS NULL OR jsonb_typeof(r)<>'object' OR coalesce(r->>'signatureHex','')!~'^[a-f0-9]{64}$' OR length(coalesce(r->>'payloadBase64','')) NOT BETWEEN 1 AND 65536 THEN RETURN NULL;END IF;
 SELECT * INTO k FROM gridex_bilateral_customer_sources.issuer_keys WHERE id=(r->>'keyId')::uuid AND company_id=a.company_id AND environment=a.environment AND counterparty_actor_id=(a.claims->>'counterpartyActorId')::uuid FOR SHARE;
 SELECT * INTO g FROM gridex_bilateral_customer_sources.representations WHERE id=(r->>'representationId')::uuid AND company_id=a.company_id AND environment=a.environment AND issuer_key_id=k.id AND legal_actor_id=(a.claims->>'legalActorId')::uuid AND agreement_id=a.agreement_id AND purpose='prodat_z06e_customer_change' FOR SHARE;
 IF k.id IS NULL OR g.id IS NULL OR now()<k.valid_from OR now()>=k.valid_to OR now()<g.valid_from OR now()>=g.valid_to OR EXISTS(SELECT FROM gridex_bilateral_customer_sources.revocations WHERE target_kind='key' AND target_id=k.id OR target_kind='representation' AND target_id=g.id OR target_kind='artifact' AND target_id=a.id) THEN RETURN NULL;END IF;
 raw:=decode(r->>'payloadBase64','base64');IF sha256(gridex_requested_changes.receipt_hmac_sha256_v1(raw,k.receipt_signing_key)) IS DISTINCT FROM sha256(decode(r->>'signatureHex','hex')) THEN RETURN NULL;END IF;
 p:=convert_from(raw,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;
 IF p->>'format' IS DISTINCT FROM 'ediel_bilateral_customer_source_receipt_v1' OR nullif(p->>'receiptId','') IS NULL OR (p->>'lifeEventKind' IN('customer_change','bankruptcy')) IS NOT TRUE OR p->'claims' IS DISTINCT FROM a.claims OR p->>'sourceHash' IS DISTINCT FROM a.source_hash OR p->>'sourceReference' IS DISTINCT FROM a.source_reference OR p->>'sourceVersion' IS DISTINCT FROM a.source_version OR jsonb_typeof(p->'authorizedFields') IS DISTINCT FROM 'array' OR jsonb_array_length(p->'authorizedFields')=0 OR EXISTS(SELECT FROM jsonb_array_elements_text(p->'authorizedFields') x WHERE x NOT IN('227','228','229','231','232','249','250','251','252','253','316','317','318')) OR (p->'authorizedFields' @> '["227","228","229","231","232","316"]'::jsonb) IS NOT TRUE OR a.claims#>'{party,invoicee}' IS NOT NULL AND a.claims#>'{party,invoicee}'<>'null'::jsonb AND (p->'authorizedFields' @> '["250","251","252","253","317","318"]'::jsonb) IS NOT TRUE OR EXISTS(SELECT FROM jsonb_array_elements(a.claims->'customerTokens') t WHERE t->>'tag'='DTM') AND (p->'authorizedFields' @> '["249"]'::jsonb) IS NOT TRUE OR NOT isfinite(issued) OR NOT isfinite(expires) OR issued>now() OR expires<=now() OR issued<greatest(k.valid_from,g.valid_from) OR expires>least(k.valid_to,g.valid_to) THEN RETURN NULL;END IF;
 RETURN p;
EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR invalid_datetime_format OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN NULL;
END$$;
CREATE FUNCTION gridex_bilateral_customer_sources.current_v1(a gridex_bilateral_customer_sources.artifacts) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE actual jsonb;receipt jsonb;o gridex_bilateral_customer_sources.origins%rowtype;r gridex_bilateral_customer_sources.reviews%rowtype;
BEGIN
 SELECT * INTO o FROM gridex_bilateral_customer_sources.origins WHERE artifact_id=a.id AND company_id=a.company_id AND source_message_id=a.source_message_id FOR SHARE;SELECT * INTO r FROM gridex_bilateral_customer_sources.reviews WHERE id=o.review_id AND artifact_id=a.id AND company_id=a.company_id FOR SHARE;
 IF r.decision IS DISTINCT FROM 'approved' OR r.reviewer_user_id=a.submitted_by OR gridex_requested_changes.actor_v1(a.company_id,r.reviewer_user_id,'review','method_contract') IS NOT TRUE OR encode(sha256(a.source_bytes),'hex') IS DISTINCT FROM a.source_hash OR encode(sha256(convert_to(a.claims::text,'UTF8')),'hex') IS DISTINCT FROM a.claims_hash THEN RETURN NULL;END IF;
 actual:=gridex_bilateral_customer_sources.source_claims_v1(a.company_id,a.source_message_id,a.agreement_id,a.supply_period_id,a.contract_id);IF actual IS DISTINCT FROM a.claims THEN RETURN NULL;END IF;
 receipt:=gridex_bilateral_customer_sources.receipt_current_v1(a);IF receipt IS NULL OR receipt->'clause' IS DISTINCT FROM r.clause OR position(convert_to(r.clause->>'quote','UTF8') IN a.source_bytes)=0 THEN RETURN NULL;END IF;
 RETURN receipt;
EXCEPTION WHEN raise_exception THEN RETURN NULL;
END$$;
CREATE FUNCTION public.ediel_archive_bilateral_customer_source_v1(p_company_id uuid,p_actor_user_id uuid,p_submission jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_bilateral_customer_sources.artifacts%rowtype;actual_claims jsonb;bytes bytea;hash text;ch text;missing jsonb:='[]';
BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'bilateral_customer_source_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'archive','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'bilateral_customer_source_archive_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_submission) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission) k WHERE k NOT IN('sourceMessageId','agreementId','supplyPeriodId','contractId','source','issuerReceipt')) OR jsonb_typeof(p_submission->'source') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission->'source') k WHERE k NOT IN('bytesBase64','mimeType','reference','version')) OR length(coalesce(p_submission#>>'{source,bytesBase64}','')) NOT BETWEEN 1 AND 11184812 OR p_submission#>>'{source,mimeType}' IS DISTINCT FROM 'application/pdf' OR nullif(p_submission#>>'{source,reference}','') IS NULL OR length(p_submission#>>'{source,reference}')>2000 OR nullif(p_submission#>>'{source,version}','') IS NULL OR length(p_submission#>>'{source,version}')>200 THEN RAISE EXCEPTION 'bilateral_customer_source_archive_shape_required';END IF;
 bytes:=decode(p_submission#>>'{source,bytesBase64}','base64');IF octet_length(bytes) NOT BETWEEN 1 AND 8388608 OR replace(encode(bytes,'base64'),E'\n','') IS DISTINCT FROM p_submission#>>'{source,bytesBase64}' OR substring(bytes,1,5)<>decode('255044462d','hex') THEN RAISE EXCEPTION 'bilateral_customer_source_bytes_invalid';END IF;
 actual_claims:=gridex_bilateral_customer_sources.source_claims_v1(p_company_id,(p_submission->>'sourceMessageId')::uuid,(p_submission->>'agreementId')::uuid,(p_submission->>'supplyPeriodId')::uuid,(p_submission->>'contractId')::uuid);hash:=encode(sha256(bytes),'hex');ch:=encode(sha256(convert_to(actual_claims::text,'UTF8')),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended('bilateral_customer_source_archive:'||p_company_id::text||hash||ch,0));
 SELECT * INTO a FROM gridex_bilateral_customer_sources.artifacts WHERE company_id=p_company_id AND environment=actual_claims->>'environment' AND source_hash=hash AND claims_hash=ch FOR SHARE;
 IF FOUND THEN IF a.source_reference IS DISTINCT FROM p_submission#>>'{source,reference}' OR a.source_version IS DISTINCT FROM p_submission#>>'{source,version}' OR a.issuer_receipt IS DISTINCT FROM p_submission->'issuerReceipt' THEN RAISE EXCEPTION 'bilateral_customer_source_archive_original_conflict';END IF;
 ELSE INSERT INTO gridex_bilateral_customer_sources.artifacts(company_id,environment,source_message_id,agreement_id,supply_period_id,contract_id,claims,claims_hash,source_bytes,source_hash,source_reference,source_version,issuer_receipt,submitted_by) VALUES(p_company_id,actual_claims->>'environment',(p_submission->>'sourceMessageId')::uuid,(p_submission->>'agreementId')::uuid,(p_submission->>'supplyPeriodId')::uuid,(p_submission->>'contractId')::uuid,actual_claims,ch,bytes,hash,p_submission#>>'{source,reference}',p_submission#>>'{source,version}',p_submission->'issuerReceipt',p_actor_user_id) RETURNING * INTO a;END IF;
 IF gridex_bilateral_customer_sources.receipt_current_v1(a) IS NULL THEN missing:='["authentic_current_bilateral_dso_receipt_and_representation"]';END IF;
 RETURN jsonb_build_object('status','archived','artifactId',a.id,'sourceHash',a.source_hash,'claimsHash',a.claims_hash,'missing',missing);
END$$;
CREATE FUNCTION public.ediel_read_bilateral_customer_source_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_include_bytes boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_bilateral_customer_sources.artifacts%rowtype;r gridex_bilateral_customer_sources.reviews%rowtype;status text;missing jsonb;result jsonb;
BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'bilateral_customer_source_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'read','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'bilateral_customer_source_read_actor_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO STRICT a FROM gridex_bilateral_customer_sources.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR SHARE;SELECT * INTO r FROM gridex_bilateral_customer_sources.reviews WHERE artifact_id=a.id ORDER BY reviewed_at DESC,id DESC LIMIT 1 FOR SHARE;
 IF gridex_bilateral_customer_sources.current_v1(a) IS NOT NULL THEN status:='authorized';missing:='[]';ELSIF r.decision='rejected' THEN status:='rejected';missing:=r.missing;ELSIF r.id IS NOT NULL THEN status:='held';missing:=CASE WHEN r.decision='approved' THEN '["current_bilateral_source_authority_unavailable"]'::jsonb ELSE r.missing END;ELSE status:='archived';missing:='["separate_bilateral_source_review_required"]';END IF;
 result:=jsonb_build_object('artifactId',a.id,'sourceMessageId',a.source_message_id,'agreementId',a.agreement_id,'supplyPeriodId',a.supply_period_id,'contractId',a.contract_id,'effectiveAt',a.claims->'effectiveAt','sourceReference',a.source_reference,'sourceVersion',a.source_version,'sourceHash',a.source_hash,'claimsHash',a.claims_hash,'mimeType','application/pdf','byteLength',octet_length(a.source_bytes),'status',status,'missing',missing);
 IF p_include_bytes THEN result:=result||jsonb_build_object('bytesBase64',replace(encode(a.source_bytes,'base64'),E'\n',''));END IF;RETURN result;
END$$;
CREATE FUNCTION public.ediel_review_bilateral_customer_source_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_review jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_bilateral_customer_sources.artifacts%rowtype;o gridex_bilateral_customer_sources.origins%rowtype;receipt jsonb;actual jsonb;missing jsonb:='[]';decision text;review_id uuid;
BEGIN
 IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'bilateral_customer_source_service_required' USING ERRCODE='42501';END IF;
 IF gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'review','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'bilateral_customer_source_review_actor_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO STRICT a FROM gridex_bilateral_customer_sources.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR UPDATE;decision:=p_review->>'decision';
 IF jsonb_typeof(p_review) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review) k WHERE k NOT IN('sourceHash','claimsHash','decision','reason','clause')) OR (decision IN('approve','hold','reject')) IS NOT TRUE OR p_review->>'sourceHash' IS DISTINCT FROM a.source_hash OR p_review->>'claimsHash' IS DISTINCT FROM a.claims_hash OR nullif(p_review->>'reason','') IS NULL OR length(p_review->>'reason')>4000 THEN RAISE EXCEPTION 'bilateral_customer_source_actual_archived_review_required';END IF;
 IF decision='approve' AND a.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'bilateral_customer_source_separate_reviewer_required';END IF;
 SELECT * INTO o FROM gridex_bilateral_customer_sources.origins WHERE artifact_id=a.id FOR SHARE;IF FOUND THEN IF decision<>'approve' THEN RAISE EXCEPTION 'bilateral_customer_source_authorized_origin_requires_revocation';END IF;IF gridex_bilateral_customer_sources.current_v1(a) IS NULL THEN RETURN jsonb_build_object('status','held','artifactId',a.id,'missing',ARRAY['current_bilateral_source_authority_unavailable']);END IF;RETURN jsonb_build_object('status','authorized','artifactId',a.id,'sourceMessageId',a.source_message_id);END IF;
 IF decision='hold' THEN missing:='["explicit_bilateral_source_review_hold"]';ELSIF decision='reject' THEN missing:='["explicit_bilateral_source_review_rejection"]';
 ELSE
  actual:=gridex_bilateral_customer_sources.source_claims_v1(a.company_id,a.source_message_id,a.agreement_id,a.supply_period_id,a.contract_id);receipt:=gridex_bilateral_customer_sources.receipt_current_v1(a);
  IF actual IS DISTINCT FROM a.claims OR receipt IS NULL THEN missing:='["authentic_current_bilateral_dso_receipt_and_representation"]';
  ELSIF jsonb_typeof(p_review->'clause') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review->'clause') k WHERE k NOT IN('locator','quote')) OR nullif(p_review#>>'{clause,locator}','') IS NULL OR length(p_review#>>'{clause,locator}')>1000 OR nullif(p_review#>>'{clause,quote}','') IS NULL OR length(p_review#>>'{clause,quote}')>10000 OR receipt->'clause' IS DISTINCT FROM p_review->'clause' OR position(convert_to(p_review#>>'{clause,quote}','UTF8') IN a.source_bytes)=0 THEN missing:='["actual_signed_bilateral_pdf_and_verbatim_customer_clause"]';END IF;
 END IF;
 INSERT INTO gridex_bilateral_customer_sources.reviews(artifact_id,company_id,reviewer_user_id,decision,reason,clause,missing) VALUES(a.id,a.company_id,p_actor_user_id,CASE WHEN missing='[]'::jsonb THEN 'approved' WHEN decision='reject' THEN 'rejected' ELSE 'held' END,p_review->>'reason',p_review->'clause',missing) RETURNING id INTO review_id;
 IF missing<>'[]'::jsonb THEN RETURN jsonb_build_object('status',CASE decision WHEN 'reject' THEN 'rejected' ELSE 'held' END,'artifactId',a.id,'missing',missing);END IF;
 INSERT INTO gridex_bilateral_customer_sources.origins(artifact_id,review_id,company_id,source_message_id) VALUES(a.id,review_id,a.company_id,a.source_message_id);
 RETURN jsonb_build_object('status','authorized','artifactId',a.id,'sourceMessageId',a.source_message_id);
END$$;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA gridex_bilateral_customer_sources FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.ediel_archive_bilateral_customer_source_v1(uuid,uuid,jsonb),public.ediel_read_bilateral_customer_source_v1(uuid,uuid,uuid,boolean),public.ediel_review_bilateral_customer_source_v1(uuid,uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_archive_bilateral_customer_source_v1(uuid,uuid,jsonb),public.ediel_read_bilateral_customer_source_v1(uuid,uuid,uuid,boolean),public.ediel_review_bilateral_customer_source_v1(uuid,uuid,uuid,jsonb) TO service_role;
-- Protected versions may point to either a death event or a reviewed bilateral
-- artifact, never both. No synthetic death or outbound request is created.
ALTER TABLE gridex_requested_changes.confirmed_customer_versions ALTER COLUMN event_id DROP NOT NULL,ADD COLUMN bilateral_artifact_id uuid REFERENCES gridex_bilateral_customer_sources.artifacts(id),ADD CONSTRAINT customer_version_exactly_one_authority CHECK((event_id IS NULL)<>(bilateral_artifact_id IS NULL));
ALTER FUNCTION public.ediel_apply_reviewed_customer_source_v1(uuid,uuid,uuid) RENAME TO ediel_apply_customer_before_bilateral_v1;
REVOKE ALL ON FUNCTION public.ediel_apply_customer_before_bilateral_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_apply_reviewed_customer_source_v1(p_company_id uuid,p_source_message_id uuid,p_actor_user_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE result jsonb;a gridex_bilateral_customer_sources.artifacts%rowtype;prior gridex_requested_changes.confirmed_customer_versions%rowtype;receipt jsonb;claims jsonb;
BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();
 -- The genuine existing whole-original/canonical/death owner runs first. Only
 -- its explicit non-death hold delegates to this separate bilateral owner.
 result:=public.ediel_apply_customer_before_bilateral_v1(p_company_id,p_source_message_id,p_actor_user_id);
 IF result->>'reason' IS DISTINCT FROM 'customer_source_separate_bilateral_non_death_ground_required' THEN RETURN result;END IF;
 IF gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'archive','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'bilateral_customer_source_apply_actor_forbidden' USING ERRCODE='42501';END IF;
 SELECT x.* INTO a FROM gridex_bilateral_customer_sources.origins o JOIN gridex_bilateral_customer_sources.artifacts x ON x.id=o.artifact_id AND x.company_id=o.company_id WHERE o.company_id=p_company_id AND o.source_message_id=p_source_message_id FOR SHARE OF o,x;
 IF NOT FOUND THEN RETURN jsonb_build_object('applied',false,'reason','customer_source_reviewed_bilateral_ground_missing');END IF;
 receipt:=gridex_bilateral_customer_sources.current_v1(a);IF receipt IS NULL THEN RETURN jsonb_build_object('applied',false,'reason','customer_source_current_bilateral_authority_missing');END IF;claims:=a.claims;
 SELECT * INTO prior FROM gridex_requested_changes.confirmed_customer_versions WHERE source_message_id=p_source_message_id FOR SHARE;
 IF FOUND THEN IF prior.bilateral_artifact_id IS DISTINCT FROM a.id OR prior.event_id IS NOT NULL OR prior.payload_hash IS DISTINCT FROM claims->>'payloadHash' OR prior.party IS DISTINCT FROM claims->'party' OR prior.canonical_assessment_id::text IS DISTINCT FROM claims->>'canonicalAssessmentId' THEN RAISE EXCEPTION 'bilateral_customer_source_replay_conflict';END IF;RETURN prior.result;END IF;
 result:=jsonb_build_object('applied',true,'sourceMessageId',p_source_message_id,'appliedCount',1,'owner','confirmed-customer-source-v1','payloadHash',claims->>'payloadHash','eventId',null,'authority',jsonb_build_object('kind','bilateral','artifactId',a.id),'objects',jsonb_build_array(jsonb_build_object('meteringPointId',claims->>'meteringPointId','siteId',claims->>'siteId','effectiveAt',claims->'effectiveAt','sourceReceivedAt',claims->'sourceReceivedAt')));
 INSERT INTO gridex_requested_changes.confirmed_customer_versions(source_message_id,event_id,bilateral_artifact_id,company_id,environment,payload_hash,customer_id,metering_point_id,effective_at,received_at,party,actor_user_id,canonical_assessment_id,supply_period_id,site_id,object_id,identity_agency,legal_sender,legal_receiver,result)
 VALUES(p_source_message_id,null,a.id,p_company_id,a.environment,claims->>'payloadHash',(claims->>'customerId')::uuid,(claims->>'meteringPointId')::uuid,(claims->>'effectiveAt')::timestamptz,(claims->>'sourceReceivedAt')::timestamptz,claims->'party',p_actor_user_id,(claims->>'canonicalAssessmentId')::uuid,a.supply_period_id,(claims->>'siteId')::uuid,claims->>'objectId',claims->>'identityAgency',claims->>'legalSender',claims->>'legalReceiver',result);
 INSERT INTO public.ediel_message_events(company_id,ediel_message_id,message_id,event_type,event_status,message,payload,event_payload,created_by) VALUES(p_company_id,p_source_message_id,p_source_message_id,'manual_note','success','Bilateralt källbunden kundversion granskad.',jsonb_build_object('safeApply',true,'safeApplyDecision','applied','appliedCount',1,'customerVersionSourceId',p_source_message_id,'bilateralArtifactId',a.id,'appliedAutomatically',false),jsonb_build_object('safeApply',true,'safeApplyDecision','applied','appliedCount',1,'customerVersionSourceId',p_source_message_id,'bilateralArtifactId',a.id,'appliedAutomatically',false),p_actor_user_id);
 RETURN result;
END$$;
REVOKE ALL ON FUNCTION public.ediel_apply_reviewed_customer_source_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_apply_reviewed_customer_source_v1(uuid,uuid,uuid) TO service_role;
ALTER FUNCTION gridex_requested_changes.customer_facet_basis_v1(jsonb,timestamptz,uuid,text,uuid,uuid,text,text,text) RENAME TO customer_facet_before_bilateral_v1;
CREATE FUNCTION gridex_requested_changes.customer_facet_basis_v1(body jsonb,cutoff timestamptz,c uuid,env text,customer uuid,site uuid,source_id text,p_object_id text,agency text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE v gridex_requested_changes.confirmed_customer_versions%rowtype;a gridex_bilateral_customer_sources.artifacts%rowtype;snap gridex_received_sources.object_selection_snapshots%rowtype;w gridex_requested_changes.customer_version_availability%rowtype;src jsonb;receipt jsonb;n int;
BEGIN
 SELECT * INTO v FROM gridex_requested_changes.confirmed_customer_versions WHERE source_message_id::text=source_id AND company_id=c AND environment=env AND customer_id=customer AND site_id=site AND object_id=p_object_id AND identity_agency=agency AND canonical_assessment_id IS NOT NULL FOR SHARE;
 IF v.bilateral_artifact_id IS NULL THEN RETURN gridex_requested_changes.customer_facet_before_bilateral_v1(body,cutoff,c,env,customer,site,source_id,p_object_id,agency);END IF;
 SELECT count(*) INTO n FROM gridex_received_sources.object_selection_snapshots s WHERE s.company_id=c AND s.environment=env AND s.cutoff_at=cutoff AND s.readset_text::jsonb=body AND s.readset_hash=encode(sha256(convert_to(s.readset_text,'UTF8')),'hex');IF n<>1 THEN RETURN NULL;END IF;
 SELECT * INTO snap FROM gridex_received_sources.object_selection_snapshots s WHERE s.company_id=c AND s.environment=env AND s.cutoff_at=cutoff AND s.readset_text::jsonb=body FOR SHARE;
 IF NOT pg_visible_in_snapshot(v.created_xid,snap.visibility_snapshot::pg_snapshot) THEN RETURN NULL;END IF;
 SELECT * INTO w FROM gridex_requested_changes.customer_version_availability WHERE source_message_id=v.source_message_id AND company_id=c AND environment=env AND payload_hash=v.payload_hash AND observed_at<=cutoff FOR SHARE;IF NOT FOUND THEN RETURN NULL;END IF;
 SELECT count(*),jsonb_agg(x)->0 INTO n,src FROM jsonb_array_elements(body->'sources') x WHERE x->>'sourceMessageId'=source_id AND x->>'payloadHash'=v.payload_hash;
 IF n<>1 OR src->>'rawPayload' IS NULL OR encode(sha256(convert_to(src->>'rawPayload','UTF8')),'hex') IS DISTINCT FROM v.payload_hash THEN RETURN NULL;END IF;
 SELECT * INTO a FROM gridex_bilateral_customer_sources.artifacts WHERE id=v.bilateral_artifact_id AND company_id=c AND environment=env AND source_message_id=v.source_message_id FOR SHARE;receipt:=gridex_bilateral_customer_sources.current_v1(a);
 IF receipt IS NULL OR a.claims->>'payloadHash' IS DISTINCT FROM v.payload_hash OR a.claims->>'customerId' IS DISTINCT FROM customer::text OR a.claims->>'siteId' IS DISTINCT FROM site::text OR a.claims->>'meteringPointId' IS DISTINCT FROM v.metering_point_id::text OR a.claims->>'supplyPeriodId' IS DISTINCT FROM v.supply_period_id::text OR a.claims->>'objectId' IS DISTINCT FROM p_object_id OR a.claims->>'identityAgency' IS DISTINCT FROM agency OR (a.claims->>'effectiveAt')::timestamptz IS DISTINCT FROM v.effective_at OR (a.claims->>'sourceReceivedAt')::timestamptz IS DISTINCT FROM v.received_at OR a.claims->>'legalSender' IS DISTINCT FROM v.legal_sender OR a.claims->>'legalReceiver' IS DISTINCT FROM v.legal_receiver OR a.claims->'party' IS DISTINCT FROM v.party OR a.claims->>'canonicalAssessmentId' IS DISTINCT FROM v.canonical_assessment_id::text THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('sourceMessageId',v.source_message_id,'payloadHash',v.payload_hash,'companyId',c,'environment',env,'customerId',customer,'siteId',site,'meteringPointId',v.metering_point_id,'supplyPeriodId',v.supply_period_id,'objectId',v.object_id,'identityAgency',v.identity_agency,'legalSender',v.legal_sender,'legalReceiver',v.legal_receiver,'effectiveAt',v.effective_at,'marketMinute',to_char(v.effective_at AT TIME ZONE 'Etc/GMT-1','YYYYMMDDHH24MI'),'availableAt',w.observed_at,'party',v.party,'authorityKind','bilateral','identityChangeAuthorized',receipt->'authorizedFields' @> '["227"]'::jsonb);
END$$;
REVOKE ALL ON FUNCTION gridex_requested_changes.customer_facet_before_bilateral_v1(jsonb,timestamptz,uuid,text,uuid,uuid,text,text,text),gridex_requested_changes.customer_facet_basis_v1(jsonb,timestamptz,uuid,text,uuid,uuid,text,text,text) FROM PUBLIC,anon,authenticated,service_role;
-- Same complete row fence; only a natively authenticated bilateral 227
-- mandate permits a dated identity correction. All cells/source epochs still
-- revalidate against the same original immutable snapshot and current owner.
CREATE OR REPLACE FUNCTION gridex_ai_processing.require_original_row_sources_v1(body jsonb,cutoff timestamptz,i public.ediel_message_intents,raw text,claims text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE refs jsonb;ref jsonb;clean_ref jsonb;last_ref jsonb;merged_refs jsonb:='[]';records text[];h text[];cols text[];last_cols text[];normalized text;merged text;
 state jsonb;base jsonb;ud jsonb;s jsonb;facet jsonb;latest jsonb;next_customer text;start_day text;end_day text;expected_start text;expected_end text;period_from text;period_to text;state_minute text;
 epoch jsonb;period public.customer_supply_periods%rowtype;row integer;customer_count integer;all_facets jsonb;n integer;
BEGIN
 IF claims IS NULL OR octet_length(claims)>262144 THEN RAISE EXCEPTION 'ai_list_original_row_sources_required';END IF;refs:=claims::jsonb;
 normalized:=replace(raw,E'\r\n',E'\n');IF left(normalized,1)=chr(65279) THEN normalized:=substring(normalized FROM 2);END IF;IF right(normalized,1)=E'\n' THEN normalized:=left(normalized,length(normalized)-1);END IF;
 records:=string_to_array(normalized,E'\n');h:=string_to_array(records[1],';');merged:=records[1];
 customer_count:=0;
 FOR row IN 2..cardinality(records) LOOP
  cols:=string_to_array(records[row],';');
  FOR s IN SELECT value FROM jsonb_array_elements(body->'sources') LOOP
   facet:=gridex_requested_changes.customer_facet_basis_v1(body,cutoff,i.company_id,i.environment,i.customer_id,i.customer_site_id,s->>'sourceMessageId',cols[2],cols[3]);
   IF facet IS NOT NULL AND facet->>'marketMinute'<h[9]||'0000' THEN customer_count:=1;EXIT;END IF;
  END LOOP;
  IF customer_count=1 THEN EXIT;END IF;
 END LOOP;
 IF customer_count=0 AND NOT EXISTS(SELECT FROM jsonb_array_elements(refs) x WHERE x ? 'customerSourceMessageId') THEN RETURN gridex_ai_processing.require_original_rows_before_customer_v1(body,cutoff,i,raw,claims);END IF;
 IF jsonb_typeof(refs)<>'array' OR jsonb_array_length(refs)<>cardinality(records)-1 OR jsonb_array_length(refs)>1000 THEN RAISE EXCEPTION 'ai_list_original_row_sources_required';END IF;
 FOR row IN 2..cardinality(records) LOOP
  ref:=refs->(row-2);cols:=string_to_array(records[row],';');clean_ref:=ref-'customerSourceMessageId';
  IF jsonb_typeof(ref)<>'object' OR (SELECT count(*) FROM jsonb_object_keys(clean_ref))<>4 OR NOT(clean_ref ?& ARRAY['sourceMessageId','baselineSourceMessageId','addressSourceMessageId','supplyPeriodId']) OR cardinality(cols)<>22 OR ref ? 'customerSourceMessageId' AND nullif(ref->>'customerSourceMessageId','') IS NULL THEN RAISE EXCEPTION 'ai_list_customer_row_scope_invalid';END IF;
  SELECT * INTO period FROM public.customer_supply_periods p WHERE p.id=(ref->>'supplyPeriodId')::uuid AND p.company_id=i.company_id AND p.customer_id=i.customer_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'ai_list_original_row_supply_scope_invalid';END IF;
  state:=gridex_ai_processing.source_row_basis_v1(body,cutoff,ref->>'sourceMessageId',i,cols[2],cols[3]);base:=gridex_ai_processing.source_row_basis_v1(body,cutoff,ref->>'baselineSourceMessageId',i,cols[2],cols[3]);
  IF state IS NULL OR base IS NULL THEN RAISE EXCEPTION 'ai_list_original_row_source_mismatch';END IF;
  SELECT t INTO ud FROM jsonb_array_elements(base->'ownTokens') t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='UD' ORDER BY (t->>'index')::integer LIMIT 1;
  period_from:=to_char(coalesce(period.actual_start_date,period.start_date),'YYYYMMDD');period_to:=to_char(coalesce(period.actual_end_date,period.end_date),'YYYYMMDD');
  epoch:=gridex_ai_processing.row_epoch_matches_v1(body,cutoff,i,cols[2],cols[3],period.id::text,ref->>'sourceMessageId',ref->>'addressSourceMessageId',period_from,h[8],least(h[9],coalesce(period_to,h[9])));
  state_minute:=epoch->>'stateMinute';start_day:=coalesce(nullif(cols[20],''),h[8]);end_day:=coalesce(nullif(cols[21],''),h[9]);
  IF start_day>=end_day THEN RAISE EXCEPTION 'ai_list_customer_row_interval_invalid';END IF;
  all_facets:='[]';
  FOR s IN SELECT value FROM jsonb_array_elements(body->'sources') LOOP
   facet:=gridex_requested_changes.customer_facet_basis_v1(body,cutoff,i.company_id,i.environment,i.customer_id,i.customer_site_id,s->>'sourceMessageId',cols[2],cols[3]);
   IF facet IS NOT NULL AND facet->>'supplyPeriodId'=period.id::text AND facet->>'legalSender'=i.receiver_ediel_id AND facet->>'legalReceiver'=i.sender_ediel_id AND facet->>'marketMinute'>=period_from||'0000' AND facet->>'marketMinute'<least(h[9],coalesce(period_to,h[9]))||'0000' THEN
    IF right(facet->>'marketMinute',4)<>'0000' THEN RAISE EXCEPTION 'ai_list_date_only_customer_boundary_unrepresentable';END IF;
    all_facets:=all_facets||jsonb_build_array(facet);
   END IF;
  END LOOP;
  IF EXISTS(SELECT FROM jsonb_array_elements(all_facets) x GROUP BY x->>'marketMinute' HAVING count(*)>1) THEN RAISE EXCEPTION 'ai_list_customer_epoch_ambiguous';END IF;
  SELECT x INTO latest FROM jsonb_array_elements(all_facets) x WHERE x->>'marketMinute'<=start_day||'0000' ORDER BY x->>'marketMinute' DESC LIMIT 1;
  IF ref->>'customerSourceMessageId' IS DISTINCT FROM latest->>'sourceMessageId' THEN RAISE EXCEPTION 'ai_list_customer_epoch_source_mismatch';END IF;
  IF latest IS NULL THEN
   IF cols[18] IS DISTINCT FROM ud#>>'{elements,2,0}' OR cols[19] IS DISTINCT FROM gridex_ai_processing.party_text_v1(ud,4,2) THEN RAISE EXCEPTION 'ai_list_customer_baseline_cell_mismatch';END IF;
  ELSE
   IF latest#>>'{party,id}' IS DISTINCT FROM ud#>>'{elements,2,0}' AND NOT(coalesce(latest->>'authorityKind'='bilateral' AND latest->>'identityChangeAuthorized'='true',false)) OR cols[18] IS DISTINCT FROM latest#>>'{party,id}' OR cols[19] IS DISTINCT FROM latest#>>'{party,name}' THEN RAISE EXCEPTION 'ai_list_customer_version_cell_mismatch';END IF;
  END IF;
  expected_start:=greatest(h[8],period_from,left(state_minute,8),coalesce(left(latest->>'marketMinute',8),period_from));
  SELECT min(x->>'marketMinute') INTO next_customer FROM jsonb_array_elements(all_facets) x WHERE x->>'marketMinute'>start_day||'0000';
  expected_end:=least(h[9],coalesce(period_to,h[9]),coalesce(left(epoch->>'nextMinute',8),h[9]),coalesce(left(next_customer,8),h[9]));
  IF start_day IS DISTINCT FROM expected_start OR end_day IS DISTINCT FROM expected_end THEN RAISE EXCEPTION 'ai_list_customer_epoch_omitted_or_forged';END IF;
  -- Customer fields and dates were separately checked above. All other cells
  -- must remain identical when recombining one unchanged structural epoch.
  cols[18]:=ud#>>'{elements,2,0}';cols[19]:=gridex_ai_processing.party_text_v1(ud,4,2);
  IF last_ref=clean_ref THEN
   IF last_cols[21] IS DISTINCT FROM cols[20] OR last_cols[1:19] IS DISTINCT FROM cols[1:19] OR last_cols[22] IS DISTINCT FROM cols[22] THEN RAISE EXCEPTION 'ai_list_customer_split_structural_cells_changed';END IF;
   last_cols[21]:=cols[21];
  ELSE
   IF last_ref IS NOT NULL THEN merged:=merged||E'\n'||array_to_string(last_cols,';');merged_refs:=merged_refs||jsonb_build_array(last_ref);END IF;
   last_ref:=clean_ref;last_cols:=cols;
  END IF;
 END LOOP;
 IF last_ref IS NOT NULL THEN merged:=merged||E'\n'||array_to_string(last_cols,';');merged_refs:=merged_refs||jsonb_build_array(last_ref);END IF;
 PERFORM gridex_ai_processing.require_original_rows_before_customer_v1(body,cutoff,i,merged,merged_refs::text);
 RETURN refs;
END$$;
-- Public source entry ports acquire the same central phantom fence BEFORE
-- predecessor source/intent/archive row locks; no second lock order is invented.
ALTER FUNCTION public.ediel_requested_change_source_v1(uuid,uuid,uuid) RENAME TO ediel_requested_change_source_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_requested_change_source_before_scope_fence_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_requested_change_source_v1(p_company_id uuid,p_event_id uuid,p_actor_user_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();RETURN public.ediel_requested_change_source_before_scope_fence_v1(p_company_id,p_event_id,p_actor_user_id);END$$;
REVOKE ALL ON FUNCTION public.ediel_requested_change_source_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_requested_change_source_v1(uuid,uuid,uuid) TO service_role;
ALTER FUNCTION public.ediel_originate_requested_change_v1(uuid,uuid,uuid,jsonb) RENAME TO ediel_originate_requested_change_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_originate_requested_change_before_scope_fence_v1(uuid,uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_originate_requested_change_v1(p_company_id uuid,p_event_id uuid,p_actor_user_id uuid,p_route jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();RETURN public.ediel_originate_requested_change_before_scope_fence_v1(p_company_id,p_event_id,p_actor_user_id,p_route);END$$;
REVOKE ALL ON FUNCTION public.ediel_originate_requested_change_v1(uuid,uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_originate_requested_change_v1(uuid,uuid,uuid,jsonb) TO service_role;
ALTER FUNCTION public.ediel_require_requested_change_source_current_v1(uuid,uuid) RENAME TO ediel_require_requested_change_source_current_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_require_requested_change_source_current_before_scope_fence_v1(uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_require_requested_change_source_current_v1(p_company_id uuid,p_message_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();PERFORM public.ediel_require_requested_change_source_current_before_scope_fence_v1(p_company_id,p_message_id);RETURN;END$$;
REVOKE ALL ON FUNCTION public.ediel_require_requested_change_source_current_v1(uuid,uuid) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_require_requested_change_source_current_v1(uuid,uuid) TO service_role;
ALTER FUNCTION public.ediel_requested_change_message_basis_v1(uuid,uuid,uuid) RENAME TO ediel_requested_change_message_basis_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_requested_change_message_basis_before_scope_fence_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_requested_change_message_basis_v1(p_company_id uuid,p_message_id uuid,p_actor_user_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();RETURN public.ediel_requested_change_message_basis_before_scope_fence_v1(p_company_id,p_message_id,p_actor_user_id);END$$;
REVOKE ALL ON FUNCTION public.ediel_requested_change_message_basis_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_requested_change_message_basis_v1(uuid,uuid,uuid) TO service_role;
ALTER FUNCTION public.ediel_archive_requested_change_source_v1(uuid,uuid,jsonb) RENAME TO ediel_archive_requested_change_source_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_archive_requested_change_source_before_scope_fence_v1(uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_archive_requested_change_source_v1(p_company_id uuid,p_actor_user_id uuid,p_submission jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();RETURN public.ediel_archive_requested_change_source_before_scope_fence_v1(p_company_id,p_actor_user_id,p_submission);END$$;
REVOKE ALL ON FUNCTION public.ediel_archive_requested_change_source_v1(uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_archive_requested_change_source_v1(uuid,uuid,jsonb) TO service_role;
ALTER FUNCTION public.ediel_read_requested_change_artifact_v1(uuid,uuid,uuid,boolean) RENAME TO ediel_read_requested_change_artifact_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_read_requested_change_artifact_before_scope_fence_v1(uuid,uuid,uuid,boolean) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_read_requested_change_artifact_v1(p_company_id uuid,p_artifact_id uuid,p_actor_user_id uuid,p_include_bytes boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();RETURN public.ediel_read_requested_change_artifact_before_scope_fence_v1(p_company_id,p_artifact_id,p_actor_user_id,p_include_bytes);END$$;
REVOKE ALL ON FUNCTION public.ediel_read_requested_change_artifact_v1(uuid,uuid,uuid,boolean) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_read_requested_change_artifact_v1(uuid,uuid,uuid,boolean) TO service_role;
ALTER FUNCTION public.ediel_review_requested_change_artifact_v1(uuid,uuid,uuid,jsonb) RENAME TO ediel_review_requested_change_artifact_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_review_requested_change_artifact_before_scope_fence_v1(uuid,uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_review_requested_change_artifact_v1(p_company_id uuid,p_artifact_id uuid,p_actor_user_id uuid,p_review jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();RETURN public.ediel_review_requested_change_artifact_before_scope_fence_v1(p_company_id,p_artifact_id,p_actor_user_id,p_review);END$$;
REVOKE ALL ON FUNCTION public.ediel_review_requested_change_artifact_v1(uuid,uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_review_requested_change_artifact_v1(uuid,uuid,uuid,jsonb) TO service_role;
ALTER FUNCTION public.ediel_witness_confirmed_customer_source_v1(uuid,uuid,uuid) RENAME TO ediel_witness_confirmed_customer_source_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_witness_confirmed_customer_source_before_scope_fence_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_witness_confirmed_customer_source_v1(p_company_id uuid,p_source_message_id uuid,p_actor_user_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();RETURN public.ediel_witness_confirmed_customer_source_before_scope_fence_v1(p_company_id,p_source_message_id,p_actor_user_id);END$$;
REVOKE ALL ON FUNCTION public.ediel_witness_confirmed_customer_source_v1(uuid,uuid,uuid) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_witness_confirmed_customer_source_v1(uuid,uuid,uuid) TO service_role;
ALTER FUNCTION public.ediel_confirmed_customer_snapshot_v1(uuid,uuid,uuid,text,uuid,uuid) RENAME TO ediel_confirmed_customer_snapshot_before_scope_fence_v1;
REVOKE ALL ON FUNCTION public.ediel_confirmed_customer_snapshot_before_scope_fence_v1(uuid,uuid,uuid,text,uuid,uuid) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.ediel_confirmed_customer_snapshot_v1(p_company_id uuid,p_actor_user_id uuid,p_snapshot_id uuid,p_readset_hash text,p_customer_id uuid,p_site_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE result jsonb;BEGIN IF current_setting('role',true) IS DISTINCT FROM 'service_role' AND session_user<>'service_role' THEN RAISE EXCEPTION 'customer_source_service_required' USING ERRCODE='42501';END IF;PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();result:=public.ediel_confirmed_customer_snapshot_before_scope_fence_v1(p_company_id,p_actor_user_id,p_snapshot_id,p_readset_hash,p_customer_id,p_site_id);IF EXISTS(SELECT FROM jsonb_array_elements(result->'versions') x WHERE x->>'authorityKind'='bilateral') AND gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'read','method_contract') IS NOT TRUE THEN RAISE EXCEPTION 'bilateral_customer_history_reader_forbidden' USING ERRCODE='42501';END IF;RETURN result;END$$;
REVOKE ALL ON FUNCTION public.ediel_confirmed_customer_snapshot_v1(uuid,uuid,uuid,text,uuid,uuid) FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.ediel_confirmed_customer_snapshot_v1(uuid,uuid,uuid,text,uuid,uuid) TO service_role;
COMMIT;
