-- Eight actual original/prepared copy classes. No cascade, default permission,
-- issuer registration, legal period, source approval or recursive policy family.
-- Published source rows keep their identities, hashes and completed history.
BEGIN;
GRANT USAGE ON SCHEMA gridex_customer_masterdata,gridex_metering_method_changes,gridex_customer_life_events TO gridex_ediel_retention_owner;
GRANT SELECT,UPDATE ON gridex_customer_masterdata.signed_declarations,gridex_customer_masterdata.preparations,gridex_metering_method_changes.contract_request_declarations,gridex_metering_method_changes.events,public.customer_contracts,public.customers,public.ediel_messages TO gridex_ediel_retention_owner;
GRANT SELECT ON gridex_customer_life_events.customer_versions TO gridex_ediel_retention_owner;
CREATE TABLE gridex_ediel_retention.contract_copy_catalog(retention_class text PRIMARY KEY,source_schema text NOT NULL,source_table text NOT NULL,body_column text NOT NULL,hash_column text NOT NULL,view_name text UNIQUE NOT NULL);
INSERT INTO gridex_ediel_retention.contract_copy_catalog VALUES
 ('masterdata_declaration_agreement_original_bytes','gridex_customer_masterdata','signed_declarations','agreement_original','agreement_sha256','masterdata_declaration_agreements'),
 ('masterdata_declaration_source_original_bytes','gridex_customer_masterdata','signed_declarations','source_original','source_sha256','masterdata_declaration_sources'),
 ('masterdata_preparation_agreement_original_bytes','gridex_customer_masterdata','preparations','agreement_original','agreement_sha256','masterdata_preparation_agreements'),
 ('masterdata_preparation_source_original_bytes','gridex_customer_masterdata','preparations','source_original','source_sha256','masterdata_preparation_sources'),
 ('metering_contract_request_agreement_original_bytes','gridex_metering_method_changes','contract_request_declarations','agreement_original','agreement_sha256','metering_contract_request_agreements'),
 ('metering_contract_request_source_original_bytes','gridex_metering_method_changes','contract_request_declarations','source_original','source_sha256','metering_contract_request_sources'),
 ('metering_method_event_agreement_original_bytes','gridex_metering_method_changes','events','agreement_original','agreement_sha256','metering_method_event_agreements'),
 ('metering_method_event_source_original_bytes','gridex_metering_method_changes','events','source_original','source_sha256','metering_method_event_sources');
CREATE TABLE gridex_ediel_retention.contract_copy_revocations(retention_class text NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_catalog(retention_class),target_id uuid NOT NULL,company_id uuid NOT NULL,policy_id uuid NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_policies(id),review_id uuid NOT NULL REFERENCES gridex_ediel_retention.decision_evidence_reviews(id),source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),actor_user_id uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(retention_class,target_id));
DO $$DECLARE tab text;BEGIN FOREACH tab IN ARRAY ARRAY['contract_copy_catalog','contract_copy_revocations'] LOOP
 EXECUTE format('ALTER TABLE gridex_ediel_retention.%I OWNER TO gridex_ediel_retention_owner',tab);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ENABLE ROW LEVEL SECURITY',tab);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I FORCE ROW LEVEL SECURITY',tab);EXECUTE format('REVOKE ALL ON gridex_ediel_retention.%I FROM PUBLIC,anon,authenticated,service_role',tab);EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',tab);EXECUTE format('CREATE TRIGGER no_truncate BEFORE TRUNCATE ON gridex_ediel_retention.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',tab);
 END LOOP;END$$;
-- Only literal signed-declaration rowProof and its exact E-overlay base have
-- original bytes. Registered address/customer-history metadata is independent.
CREATE FUNCTION gridex_ediel_retention.contract_copy_prepared_proof_v1(b jsonb) RETURNS jsonb LANGUAGE sql IMMUTABLE SET search_path=pg_catalog AS $$SELECT CASE WHEN b#>>'{sourceProof,rowProof,contract_id}' IS NOT NULL AND b#>>'{sourceProof,rowProof,id}' IS NOT NULL THEN b#>'{sourceProof,rowProof}' WHEN b#>>'{sourceProof,rowProof,base,contract_id}' IS NOT NULL AND b#>>'{sourceProof,rowProof,base,id}' IS NOT NULL THEN b#>'{sourceProof,rowProof,base}' END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_prepared_metadata_v1(b jsonb) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$BEGIN
 IF b#>>'{sourceProof,rowProof,contract_id}' IS NOT NULL THEN RETURN jsonb_set(b,'{sourceProof,rowProof}',(b#>'{sourceProof,rowProof}')-ARRAY['agreement_original','source_original']);
 ELSIF b#>>'{sourceProof,rowProof,base,contract_id}' IS NOT NULL THEN RETURN jsonb_set(b,'{sourceProof,rowProof,base}',(b#>'{sourceProof,rowProof,base}')-ARRAY['agreement_original','source_original']);END IF;RETURN b;END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_prepared_redact_v1(b jsonb,field text) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog AS $$BEGIN
 IF field NOT IN('agreement_original','source_original') THEN RAISE EXCEPTION 'contract_copy_exact_body_required';END IF;
 IF b#>>'{sourceProof,rowProof,contract_id}' IS NOT NULL THEN RETURN jsonb_set(b,ARRAY['sourceProof','rowProof',field],'null');
 ELSIF b#>>'{sourceProof,rowProof,base,contract_id}' IS NOT NULL THEN RETURN jsonb_set(b,ARRAY['sourceProof','rowProof','base',field],'null');END IF;RAISE EXCEPTION 'contract_copy_exact_prepared_source_required';END$$;
CREATE VIEW gridex_ediel_retention.masterdata_declaration_agreements WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.agreement_original document_bytes,q.agreement_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_customer_masterdata.signed_declarations q;
ALTER VIEW gridex_ediel_retention.masterdata_declaration_agreements OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.masterdata_declaration_agreements FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('masterdata_declaration_agreement_original_bytes','masterdata_declaration_agreements','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
CREATE VIEW gridex_ediel_retention.masterdata_declaration_sources WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.source_original document_bytes,q.source_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_customer_masterdata.signed_declarations q;
ALTER VIEW gridex_ediel_retention.masterdata_declaration_sources OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.masterdata_declaration_sources FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('masterdata_declaration_source_original_bytes','masterdata_declaration_sources','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
CREATE VIEW gridex_ediel_retention.masterdata_preparation_agreements WITH(security_barrier=true) AS SELECT q.id,q.company_id,decode(substr(gridex_ediel_retention.contract_copy_prepared_proof_v1(q.basis)->>'agreement_original',3),'hex') document_bytes,gridex_ediel_retention.contract_copy_prepared_proof_v1(q.basis)->>'agreement_sha256' document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,(to_jsonb(q)-'basis')||jsonb_build_object('basis',gridex_ediel_retention.contract_copy_prepared_metadata_v1(q.basis)) source_metadata FROM gridex_customer_masterdata.preparations q;
ALTER VIEW gridex_ediel_retention.masterdata_preparation_agreements OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.masterdata_preparation_agreements FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('masterdata_preparation_agreement_original_bytes','masterdata_preparation_agreements','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
CREATE VIEW gridex_ediel_retention.masterdata_preparation_sources WITH(security_barrier=true) AS SELECT q.id,q.company_id,decode(substr(gridex_ediel_retention.contract_copy_prepared_proof_v1(q.basis)->>'source_original',3),'hex') document_bytes,gridex_ediel_retention.contract_copy_prepared_proof_v1(q.basis)->>'source_sha256' document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,(to_jsonb(q)-'basis')||jsonb_build_object('basis',gridex_ediel_retention.contract_copy_prepared_metadata_v1(q.basis)) source_metadata FROM gridex_customer_masterdata.preparations q;
ALTER VIEW gridex_ediel_retention.masterdata_preparation_sources OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.masterdata_preparation_sources FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('masterdata_preparation_source_original_bytes','masterdata_preparation_sources','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
CREATE VIEW gridex_ediel_retention.metering_contract_request_agreements WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.agreement_original document_bytes,q.agreement_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_metering_method_changes.contract_request_declarations q;
ALTER VIEW gridex_ediel_retention.metering_contract_request_agreements OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.metering_contract_request_agreements FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('metering_contract_request_agreement_original_bytes','metering_contract_request_agreements','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
CREATE VIEW gridex_ediel_retention.metering_contract_request_sources WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.source_original document_bytes,q.source_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_metering_method_changes.contract_request_declarations q;
ALTER VIEW gridex_ediel_retention.metering_contract_request_sources OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.metering_contract_request_sources FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('metering_contract_request_source_original_bytes','metering_contract_request_sources','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
CREATE VIEW gridex_ediel_retention.metering_method_event_agreements WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.agreement_original document_bytes,q.agreement_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_metering_method_changes.events q;
ALTER VIEW gridex_ediel_retention.metering_method_event_agreements OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.metering_method_event_agreements FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('metering_method_event_agreement_original_bytes','metering_method_event_agreements','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
CREATE VIEW gridex_ediel_retention.metering_method_event_sources WITH(security_barrier=true) AS SELECT q.id,q.company_id,q.source_original document_bytes,q.source_sha256 document_hash,NULL::bigint document_byte_length,NULL::timestamptz document_purged_at,to_jsonb(q)-ARRAY['agreement_original','source_original'] source_metadata FROM gridex_metering_method_changes.events q;
ALTER VIEW gridex_ediel_retention.metering_method_event_sources OWNER TO gridex_ediel_retention_owner;REVOKE ALL ON gridex_ediel_retention.metering_method_event_sources FROM PUBLIC,anon,authenticated,service_role;INSERT INTO gridex_ediel_retention.decision_evidence_catalog VALUES('metering_method_event_source_original_bytes','metering_method_event_sources','ediel.retention.record_decision_evidence','contract_copy_revocations','target_id','contract_copy_source_current_v1');
ALTER TABLE gridex_customer_masterdata.signed_declarations ALTER COLUMN agreement_original DROP NOT NULL,ALTER COLUMN source_original DROP NOT NULL;
ALTER TABLE gridex_metering_method_changes.contract_request_declarations ALTER COLUMN agreement_original DROP NOT NULL,ALTER COLUMN source_original DROP NOT NULL;
ALTER TABLE gridex_metering_method_changes.events ALTER COLUMN agreement_original DROP NOT NULL,ALTER COLUMN source_original DROP NOT NULL;
-- A prepared basis retains its original full-byte hash after exact qualified
-- copy erasure. New INSERTs must still match their entire original JSON.
DO $$DECLARE check_name text;count_checks int;BEGIN
 SELECT count(*),min(conname) INTO count_checks,check_name FROM pg_constraint WHERE conrelid='gridex_customer_masterdata.preparations'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%basis_hash%' AND pg_get_constraintdef(oid) LIKE '%sha256%';
 IF count_checks<>1 THEN RAISE EXCEPTION 'contract_copy_exact_preparation_hash_constraint_required';END IF;EXECUTE format('ALTER TABLE gridex_customer_masterdata.preparations DROP CONSTRAINT %I',check_name);
END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_row_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE spec record;r jsonb;meta jsonb;proof jsonb;bytes bytea;h text;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;customer uuid;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();SELECT * INTO STRICT spec FROM gridex_ediel_retention.contract_copy_catalog WHERE retention_class=k;
 EXECUTE format('SELECT to_jsonb(x) FROM %I.%I x WHERE id=$1 AND company_id=$2',spec.source_schema,spec.source_table) INTO r USING target,c;
 IF r IS NULL THEN RAISE EXCEPTION 'decision_evidence_original_scope_required';END IF;customer:=(r->>'customer_id')::uuid;
 IF spec.source_schema='gridex_customer_masterdata' THEN
  PERFORM m.id FROM public.ediel_messages m WHERE m.company_id=c AND m.id IN(SELECT v.source_message_id FROM gridex_customer_life_events.customer_versions v WHERE v.company_id=c AND v.customer_id=customer) ORDER BY m.id FOR UPDATE;
  PERFORM pg_advisory_xact_lock(hashtextextended('customer-masterdata:'||c::text||':'||customer::text,0));
  PERFORM ct.id FROM public.customer_contracts ct WHERE ct.company_id=c AND ct.id IN(SELECT d.contract_id FROM gridex_customer_masterdata.signed_declarations d WHERE d.company_id=c AND d.customer_id=customer) ORDER BY ct.id FOR SHARE;
  PERFORM id FROM public.customers WHERE id=customer AND company_id=c FOR UPDATE;
 ELSIF spec.source_table='contract_request_declarations' THEN
  PERFORM id FROM public.customer_contracts WHERE id=(r->>'contract_id')::uuid AND company_id=c FOR SHARE;
  PERFORM pg_advisory_xact_lock(hashtextextended('contract-method-request:'||c::text||':'||(r->>'contract_id'),0));
 END IF;
 EXECUTE format('SELECT to_jsonb(x) FROM %I.%I x WHERE id=$1 AND company_id=$2 FOR UPDATE',spec.source_schema,spec.source_table) INTO r USING target,c;
 IF r IS NULL THEN RAISE EXCEPTION 'decision_evidence_original_scope_required';END IF;
 IF spec.source_table='preparations' THEN proof:=gridex_ediel_retention.contract_copy_prepared_proof_v1(r->'basis');h:=proof->>spec.hash_column;bytes:=decode(substr(proof->>spec.body_column,3),'hex');meta:=(r-'basis')||jsonb_build_object('basis',gridex_ediel_retention.contract_copy_prepared_metadata_v1(r->'basis'));
 ELSE h:=r->>spec.hash_column;bytes:=decode(substr(r->>spec.body_column,3),'hex');meta:=r-ARRAY['agreement_original','source_original'];END IF;
 SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=k AND target_id=target AND company_id=c;
 IF h IS NULL OR bytes IS NOT NULL AND encode(sha256(bytes),'hex') IS DISTINCT FROM h OR bytes IS NULL AND(t.target_id IS NULL OR t.source_hash IS DISTINCT FROM h) THEN RAISE EXCEPTION 'decision_evidence_original_custody_mismatch';END IF;
 RETURN jsonb_build_object('id',target,'company_id',c,'document_bytes',CASE WHEN bytes IS NULL THEN NULL ELSE '\x'||encode(bytes,'hex') END,'document_hash',h,'document_byte_length',CASE WHEN bytes IS NULL THEN t.byte_length ELSE NULL END,'document_purged_at',t.created_at,'source_metadata',meta);
END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_basis_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;b bytea;BEGIN
 r:=gridex_ediel_retention.contract_copy_row_v1(c,k,target);b:=decode(substr(r->>'document_bytes',3),'hex');IF b IS NULL OR octet_length(b)<1 THEN RAISE EXCEPTION 'decision_evidence_actual_original_bytes_required';END IF;
 RETURN jsonb_build_object('retentionClass',k,'targetId',target,'sourceHash',r->>'document_hash','targetMetadataHash',encode(sha256(convert_to((r-ARRAY['document_bytes','document_byte_length','document_purged_at'])::text,'UTF8')),'hex'),'byteLength',octet_length(b));END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_source_current_v1(c uuid,ns text,tab text,target uuid) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r jsonb;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();IF (ns='gridex_customer_masterdata' AND tab='signed_declarations' OR ns='gridex_metering_method_changes' AND tab IN('contract_request_declarations','events')) IS NOT TRUE THEN RAISE EXCEPTION 'contract_copy_exact_source_namespace_required';END IF;
 EXECUTE format('SELECT to_jsonb(x) FROM %I.%I x WHERE id=$1 AND company_id=$2 FOR SHARE',ns,tab) INTO r USING target,c;
 RETURN r IS NOT NULL AND r->>'approved_by' IS NOT NULL AND r->>'approved_at' IS NOT NULL AND(r->>'approved_at')::timestamptz<=clock_timestamp() AND r->>'agreement_original' IS NOT NULL AND r->>'source_original' IS NOT NULL AND encode(sha256(decode(substr(r->>'agreement_original',3),'hex')),'hex')=r->>'agreement_sha256' AND encode(sha256(decode(substr(r->>'source_original',3),'hex')),'hex')=r->>'source_sha256' AND NOT EXISTS(SELECT FROM gridex_ediel_retention.contract_copy_revocations v JOIN gridex_ediel_retention.contract_copy_catalog s USING(retention_class) WHERE v.company_id=c AND v.target_id=target AND s.source_schema=ns AND s.source_table=tab);
END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_preparation_current_v1(c uuid,target uuid) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r gridex_customer_masterdata.preparations%rowtype;p jsonb;BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();SELECT * INTO r FROM gridex_customer_masterdata.preparations WHERE id=target AND company_id=c FOR SHARE;IF r.id IS NULL THEN RETURN false;END IF;p:=gridex_ediel_retention.contract_copy_prepared_proof_v1(r.basis);
 IF p IS NULL THEN RETURN NOT EXISTS(SELECT FROM gridex_ediel_retention.contract_copy_revocations WHERE company_id=c AND target_id=target AND retention_class LIKE 'masterdata_preparation_%');END IF;
 RETURN p->>'agreement_original' IS NOT NULL AND p->>'source_original' IS NOT NULL AND encode(sha256(decode(substr(p->>'agreement_original',3),'hex')),'hex')=p->>'agreement_sha256' AND encode(sha256(decode(substr(p->>'source_original',3),'hex')),'hex')=p->>'source_sha256' AND gridex_ediel_retention.contract_copy_source_current_v1(c,'gridex_customer_masterdata','signed_declarations',(p->>'id')::uuid) AND NOT EXISTS(SELECT FROM gridex_ediel_retention.contract_copy_revocations WHERE company_id=c AND target_id=target AND retention_class LIKE 'masterdata_preparation_%');END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_transition_v1(k text,o jsonb,n jsonb) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE spec record;target uuid:=(o->>'id')::uuid;c uuid:=(o->>'company_id')::uuid;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;d gridex_ediel_retention.decision_evidence_policies%rowtype;r gridex_ediel_retention.decision_evidence_reviews%rowtype;p jsonb;b jsonb;bytes bytea;at timestamptz;permission text;BEGIN
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.contract_copy_catalog WHERE retention_class=k;
 IF spec.source_table='preparations' THEN
  IF n IS DISTINCT FROM(o-'basis')||jsonb_build_object('basis',gridex_ediel_retention.contract_copy_prepared_redact_v1(o->'basis',spec.body_column)) THEN RETURN false;END IF;bytes:=decode(substr(gridex_ediel_retention.contract_copy_prepared_proof_v1(o->'basis')->>spec.body_column,3),'hex');
 ELSE IF o->>spec.body_column IS NULL OR n->>spec.body_column IS NOT NULL OR(o-spec.body_column) IS DISTINCT FROM(n-spec.body_column) THEN RETURN false;END IF;bytes:=decode(substr(o->>spec.body_column,3),'hex');END IF;
 SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=k AND target_id=target AND company_id=c;
 IF t.target_id IS NULL OR bytes IS NULL OR encode(sha256(bytes),'hex') IS DISTINCT FROM t.source_hash OR octet_length(bytes) IS DISTINCT FROM t.byte_length OR NOT EXISTS(SELECT FROM gridex_ediel_retention.contract_copy_revocations WHERE retention_class=k AND target_id=target AND company_id=c AND policy_id=t.policy_id AND review_id=t.review_id AND source_hash=t.source_hash AND actor_user_id=t.actor_user_id) THEN RETURN false;END IF;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.decision_evidence_policies WHERE id=t.policy_id FOR UPDATE;SELECT * INTO r FROM gridex_ediel_retention.decision_evidence_reviews WHERE policy_id=d.id ORDER BY created_at DESC,id DESC LIMIT 1 FOR SHARE;
 IF r.id IS DISTINCT FROM t.review_id OR r.outcome IS DISTINCT FROM 'approved' OR r.actor_user_id=d.submitted_by OR d.retention_class IS DISTINCT FROM k OR d.target_id IS DISTINCT FROM target OR d.company_id IS DISTINCT FROM c OR d.source_hash IS DISTINCT FROM t.source_hash OR d.target_metadata_hash IS DISTINCT FROM t.target_metadata_hash THEN RETURN false;END IF;
 b:=gridex_ediel_retention.contract_copy_basis_v1(c,k,target);IF b->>'sourceHash' IS DISTINCT FROM d.source_hash OR b->>'targetMetadataHash' IS DISTINCT FROM d.target_metadata_hash THEN RETURN false;END IF;
 PERFORM gridex_ediel_retention.decision_evidence_actor_v1(c,t.actor_user_id,k,'ediel.retention.purge');PERFORM gridex_ediel_retention.decision_evidence_lock_reviewer_v1(c,r.actor_user_id,k);
 p:=gridex_ediel_retention.decision_evidence_receipt_v1(d);SELECT permission_key INTO STRICT permission FROM gridex_ediel_retention.decision_evidence_catalog WHERE retention_class=k;
 IF p IS NULL OR gridex_ediel_retention.permission_v1(c,t.actor_user_id,'ediel.retention.purge') IS NOT TRUE OR gridex_ediel_retention.permission_v1(c,t.actor_user_id,permission) IS NOT TRUE OR gridex_ediel_retention.permission_v1(c,r.actor_user_id,'ediel.retention.review') IS NOT TRUE OR gridex_ediel_retention.permission_v1(c,r.actor_user_id,permission) IS NOT TRUE THEN RETURN false;END IF;
 at:=clock_timestamp();RETURN(p->>'retainUntil')::timestamptz<=at AND(p->>'issuedAt')::timestamptz<=at AND(p->>'expiresAt')::timestamptz>at AND(p->>'journalRetainUntil')::timestamptz>at;
END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_insert_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN
 IF TG_TABLE_NAME='preparations' THEN IF NEW.basis_hash IS DISTINCT FROM encode(sha256(convert_to(NEW.basis::text,'UTF8')),'hex') THEN RAISE EXCEPTION 'contract_copy_new_full_preparation_hash_required';END IF;
 ELSIF NEW.agreement_original IS NULL OR NEW.source_original IS NULL OR encode(sha256(NEW.agreement_original),'hex') IS DISTINCT FROM NEW.agreement_sha256 OR encode(sha256(NEW.source_original),'hex') IS DISTINCT FROM NEW.source_sha256 THEN RAISE EXCEPTION 'contract_copy_new_actual_original_bytes_required';END IF;RETURN NEW;END$$;
CREATE FUNCTION gridex_ediel_retention.contract_copy_view_update_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec record;t gridex_ediel_retention.decision_evidence_tombstones%rowtype;changed int;BEGIN
 SELECT s.* INTO STRICT spec FROM gridex_ediel_retention.contract_copy_catalog s WHERE view_name=TG_TABLE_NAME;SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=spec.retention_class AND target_id=OLD.id AND company_id=OLD.company_id;
 IF t.target_id IS NULL OR OLD.document_bytes IS NULL OR NEW.document_bytes IS NOT NULL OR(to_jsonb(OLD)-ARRAY['document_bytes','document_byte_length','document_purged_at']) IS DISTINCT FROM(to_jsonb(NEW)-ARRAY['document_bytes','document_byte_length','document_purged_at']) OR NEW.document_byte_length IS DISTINCT FROM t.byte_length OR NEW.document_purged_at IS DISTINCT FROM t.created_at THEN RAISE EXCEPTION 'contract_copy_exact_physical_transition_required';END IF;
 IF spec.source_table='preparations' THEN EXECUTE format('UPDATE %I.%I SET basis=gridex_ediel_retention.contract_copy_prepared_redact_v1(basis,$1) WHERE id=$2 AND company_id=$3',spec.source_schema,spec.source_table) USING spec.body_column,OLD.id,OLD.company_id;
 ELSE EXECUTE format('UPDATE %I.%I SET %I=NULL WHERE id=$1 AND company_id=$2',spec.source_schema,spec.source_table,spec.body_column) USING OLD.id,OLD.company_id;END IF;
 GET DIAGNOSTICS changed=ROW_COUNT;IF changed<>1 THEN RAISE EXCEPTION 'contract_copy_exact_native_row_required';END IF;RETURN NEW;END$$;
DO $$DECLARE row record;f record;body text;name text;def text;classes text;BEGIN
 FOR row IN SELECT DISTINCT source_schema,source_table FROM gridex_ediel_retention.contract_copy_catalog LOOP
  SELECT t.oid,t.tgname,t.tgenabled,p.prosrc INTO STRICT f FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid WHERE t.tgrelid=format('%I.%I',row.source_schema,row.source_table)::regclass AND t.tgname=CASE WHEN row.source_schema='gridex_customer_masterdata' THEN 'customer_masterdata_immutable' WHEN row.source_table='events' THEN 'method_source_immutable' ELSE 'requested_method_source_immutable' END;
  IF f.prosrc!~*'RAISE\s+EXCEPTION' OR f.tgenabled NOT IN('O','A') THEN RAISE EXCEPTION 'contract_copy_actual_immutable_guard_required';END IF;
  SELECT string_agg(format('gridex_ediel_retention.contract_copy_transition_v1(%L,to_jsonb(OLD),to_jsonb(NEW)) IS TRUE',retention_class),' OR ' ORDER BY retention_class) INTO classes FROM gridex_ediel_retention.contract_copy_catalog WHERE source_schema=row.source_schema AND source_table=row.source_table;
  name:=CASE WHEN row.source_schema='gridex_customer_masterdata' THEN 'masterdata_'||row.source_table ELSE 'method_'||row.source_table END||'_copy_guard_v1';body:=regexp_replace(f.prosrc,'\mBEGIN\M','BEGIN IF TG_OP=''UPDATE'' AND ('||classes||') THEN RETURN NEW;END IF;','i');
  EXECUTE format('CREATE FUNCTION gridex_ediel_retention.%I() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS %L',name,body);EXECUTE format('ALTER FUNCTION gridex_ediel_retention.%I() OWNER TO gridex_ediel_retention_owner',name);EXECUTE format('REVOKE ALL ON FUNCTION gridex_ediel_retention.%I() FROM PUBLIC,anon,authenticated,service_role',name);
  def:=pg_get_triggerdef(f.oid);EXECUTE format('DROP TRIGGER %I ON %I.%I',f.tgname,row.source_schema,row.source_table);EXECUTE regexp_replace(def,'EXECUTE (FUNCTION|PROCEDURE) .*$',format('EXECUTE FUNCTION gridex_ediel_retention.%I()',name));IF f.tgenabled='A' THEN EXECUTE format('ALTER TABLE %I.%I ENABLE ALWAYS TRIGGER %I',row.source_schema,row.source_table,f.tgname);END IF;
  EXECUTE format('CREATE TRIGGER contract_copy_insert BEFORE INSERT ON %I.%I FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.contract_copy_insert_v1()',row.source_schema,row.source_table);
 END LOOP;
 FOR row IN SELECT * FROM gridex_ediel_retention.contract_copy_catalog LOOP EXECUTE format('CREATE TRIGGER contract_copy_view_update INSTEAD OF UPDATE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.contract_copy_view_update_v1()',row.view_name);END LOOP;
END$$;
DO $$DECLARE f record;body text;needle text;signature text;copy_classes text:='''masterdata_declaration_agreement_original_bytes'',''masterdata_declaration_source_original_bytes'',''masterdata_preparation_agreement_original_bytes'',''masterdata_preparation_source_original_bytes'',''metering_contract_request_agreement_original_bytes'',''metering_contract_request_source_original_bytes'',''metering_method_event_agreement_original_bytes'',''metering_method_event_source_original_bytes''';BEGIN
 FOR signature IN SELECT unnest(ARRAY['gridex_ediel_retention.decision_evidence_basis_v1(uuid,text,uuid)','public.ediel_read_retention_decision_original_v1(uuid,uuid,text,uuid,boolean)','public.ediel_purge_decision_evidence_retention_v1(uuid,uuid,uuid)','gridex_customer_masterdata.basis_v1(uuid,uuid,uuid,timestamp with time zone,text,text,timestamp with time zone,jsonb)','gridex_customer_masterdata.require_current_v1(uuid,uuid,uuid,text)','gridex_customer_masterdata.bind_original_v1()','gridex_metering_method_changes.contract_request_basis_v1(uuid,uuid,uuid,text,text)','gridex_metering_method_changes.context_before_contract_request_v1(uuid,uuid,uuid,text)']) LOOP
  SELECT p.oid,p.proowner,p.proacl,p.proconfig,p.provolatile,p.prosecdef,to_jsonb(p)-'prosrc' metadata,p.prosrc,pg_get_functiondef(p.oid) definition INTO STRICT f FROM pg_proc p WHERE p.oid=signature::regprocedure;body:=f.prosrc;
  IF signature LIKE '%decision_evidence_basis_v1%' THEN needle:='SELECT source_table INTO STRICT tab';body:=replace(body,needle,'IF k IN('||copy_classes||') THEN RETURN gridex_ediel_retention.contract_copy_basis_v1(c,k,target);END IF; '||needle);
  ELSIF signature LIKE '%ediel_read_retention_decision_original_v1%' THEN needle:='SELECT source_table INTO STRICT tab';body:=replace(body,needle,'IF p_retention_class IN('||copy_classes||') THEN r:=gridex_ediel_retention.contract_copy_row_v1(p_company_id,p_retention_class,p_target_id);b:=decode(substr(r->>''document_bytes'',3),''hex'');SELECT * INTO t FROM gridex_ediel_retention.decision_evidence_tombstones WHERE retention_class=p_retention_class AND target_id=p_target_id AND company_id=p_company_id;RETURN jsonb_build_object(''companyId'',p_company_id,''retentionClass'',p_retention_class,''targetId'',p_target_id,''documentHash'',r->>''document_hash'',''targetMetadataHash'',encode(sha256(convert_to((r-ARRAY[''document_bytes'',''document_byte_length'',''document_purged_at''])::text,''UTF8'')),''hex''),''documentByteLength'',coalesce(octet_length(b),t.byte_length),''bytesAvailable'',b IS NOT NULL,''documentBase64'',CASE WHEN p_include_document AND b IS NOT NULL THEN replace(encode(b,''base64''),E''\n'','''') ELSE NULL END,''purgedAt'',t.created_at,''authority'',''none'');END IF; '||needle);
  ELSIF signature LIKE '%ediel_purge_decision_evidence_retention_v1%' THEN
   needle:='IF d.retention_class IN(';
   IF position(needle IN body)=0 OR body!~'classification_copy_revocations' THEN RAISE EXCEPTION 'contract_copy_actual_815_adapter_required';END IF;
   body:=replace(body,needle,'IF d.retention_class IN('||copy_classes||') THEN INSERT INTO gridex_ediel_retention.contract_copy_revocations(retention_class,target_id,company_id,policy_id,review_id,source_hash,actor_user_id) VALUES(d.retention_class,d.target_id,d.company_id,d.id,r.id,d.source_hash,p_actor_user_id);ELSIF d.retention_class IN(');
   needle:='INSERT INTO gridex_ediel_retention.decision_evidence_tombstones';body:=replace(body,needle,'p:=gridex_ediel_retention.decision_evidence_receipt_v1(d);at:=clock_timestamp();IF p IS NULL OR (p->>''retainUntil'')::timestamptz>at THEN RAISE EXCEPTION ''contract_copy_native_deadline_changed'';END IF; '||needle);
  ELSIF signature LIKE '%contract_request_basis_v1%' THEN
   needle:='SELECT * INTO point';body:=replace(body,needle,'IF gridex_ediel_retention.contract_copy_source_current_v1(c,''gridex_metering_method_changes'',''contract_request_declarations'',d.id) IS NOT TRUE THEN RETURN jsonb_build_object(''status'',''held'',''missing'',ARRAY[''current_unpurged_signed_method_declaration'']);END IF; '||needle);
  ELSIF signature LIKE '%context_before_contract_request_v1%' THEN
   needle:='supply:=gridex_received_sources.supply_period_source_at_v1';body:=replace(body,needle,'IF gridex_ediel_retention.contract_copy_source_current_v1(c,''gridex_metering_method_changes'',''events'',e.id) IS NOT TRUE THEN RETURN jsonb_build_object(''status'',''held'',''missing'',ARRAY[''current_unpurged_method_event_originals'']);END IF; '||needle);
  ELSIF signature LIKE '%basis_v1%' THEN
   needle:='identity:=declaration.customer_identity';body:=replace(body,needle,'IF gridex_ediel_retention.contract_copy_source_current_v1(c,''gridex_customer_masterdata'',''signed_declarations'',declaration.id) IS NOT TRUE THEN RETURN jsonb_build_object(''status'',''held'',''missing'',ARRAY[''current_unpurged_signed_masterdata_originals'']);END IF; '||needle);
  ELSE
   needle:='b:=gridex_customer_masterdata.basis_v1';body:=replace(body,needle,'IF gridex_ediel_retention.contract_copy_preparation_current_v1('||CASE WHEN signature LIKE '%bind_original%' THEN 'NEW.company_id' ELSE 'c' END||',p.id) IS NOT TRUE THEN RAISE EXCEPTION ''customer_masterdata_consumed_original_copy_tombstoned'';END IF; '||needle);
  END IF;
  IF body=f.prosrc OR position(needle IN f.prosrc)=0 THEN RAISE EXCEPTION 'contract_copy_actual_consumer_source_review_required: %',signature;END IF;
  IF signature NOT LIKE '%decision_evidence%' AND signature NOT LIKE '%ediel_read_retention%' THEN body:=regexp_replace(body,'\mBEGIN\M','BEGIN PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();','i');END IF;
  EXECUTE replace(f.definition,f.prosrc,body);EXECUTE format('GRANT EXECUTE ON FUNCTION gridex_ediel_retention.contract_copy_source_current_v1(uuid,text,text,uuid),gridex_ediel_retention.contract_copy_preparation_current_v1(uuid,uuid) TO %I',pg_get_userbyid(f.proowner));
  IF NOT EXISTS(SELECT FROM pg_proc p WHERE p.oid=f.oid AND(to_jsonb(p)-'prosrc')=f.metadata) THEN RAISE EXCEPTION 'contract_copy_actual_function_identity_changed';END IF;
 END LOOP;
END$$;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure sig FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_ediel_retention' AND p.proname LIKE 'contract_copy_%' LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO gridex_ediel_retention_owner',f.sig);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.sig);END LOOP;END$$;
COMMIT;
