-- Internal custody/review owner. No issuer/representation keys or permissions
-- are granted/seeded; archive bytes and reviewer decisions never mint an issuer.
BEGIN;
INSERT INTO public.permissions(key,name,category,description,is_active)
 SELECT 'ediel.source.review','Review own Ediel source artifacts','ediel','Separate, company-scoped review of actual archived source artifacts; does not establish issuer authority.',true
 WHERE NOT EXISTS(SELECT FROM public.permissions WHERE key='ediel.source.review');
CREATE TABLE gridex_requested_changes.artifacts(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL,
 supply_period_id uuid NOT NULL REFERENCES public.customer_supply_periods(id),contract_id uuid NOT NULL REFERENCES public.customer_contracts(id),customer_id uuid NOT NULL,metering_point_id uuid NOT NULL,legal_actor_id uuid NOT NULL,legal_sender_id text NOT NULL,legal_receiver_id text NOT NULL,point_id text NOT NULL,identity_agency text NOT NULL,grid_area_code text NOT NULL,brp_ediel_id text NOT NULL,supply_source_message_id uuid NOT NULL,supply_state_version bigint NOT NULL,
 protected_contract_hash text NOT NULL,customer_snapshot_hash text NOT NULL,kind text NOT NULL CHECK(kind IN('death','quarter_contract','method_contract')),effective_at timestamptz NOT NULL CHECK(isfinite(effective_at) AND extract(second FROM effective_at)=0),
 source_bytes bytea NOT NULL CHECK(octet_length(source_bytes) BETWEEN 1 AND 8388608),source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),mime_type text NOT NULL CHECK(mime_type IN('application/pdf','text/plain','application/json')),source_reference text NOT NULL,source_version text NOT NULL,
 claims jsonb NOT NULL,claims_hash text NOT NULL,issuer_receipt jsonb,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(company_id,environment,source_hash,claims_hash));
CREATE TABLE gridex_requested_changes.reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),artifact_id uuid NOT NULL REFERENCES gridex_requested_changes.artifacts(id),company_id uuid NOT NULL,reviewer_user_id uuid NOT NULL REFERENCES auth.users(id),decision text NOT NULL CHECK(decision IN('approved','held','rejected')),reason text NOT NULL,clause jsonb,missing jsonb NOT NULL DEFAULT '[]',reviewed_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_requested_changes.issuer_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,environment text NOT NULL,issuer_code text NOT NULL,legal_issuer_reference text NOT NULL,legal_authority_source_hash text NOT NULL CHECK(legal_authority_source_hash~'^[a-f0-9]{64}$'),receipt_signing_key bytea NOT NULL CHECK(octet_length(receipt_signing_key)>=32),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(valid_to>valid_from),UNIQUE(company_id,environment,issuer_code,valid_from));
CREATE TABLE gridex_requested_changes.issuer_representations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,environment text NOT NULL,issuer_key_id uuid NOT NULL REFERENCES gridex_requested_changes.issuer_keys(id),legal_actor_id uuid NOT NULL,permitted_kind text NOT NULL CHECK(permitted_kind='death'),legal_representation_reference text NOT NULL,legal_authority_source_hash text NOT NULL CHECK(legal_authority_source_hash~'^[a-f0-9]{64}$'),valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL CHECK(valid_to>valid_from));
CREATE TABLE gridex_requested_changes.issuer_revocations(target_kind text NOT NULL CHECK(target_kind IN('key','representation')),target_id uuid NOT NULL,source_reference text NOT NULL,source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),revoked_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(target_kind,target_id));
CREATE TABLE gridex_requested_changes.review_origins(event_id uuid PRIMARY KEY REFERENCES gridex_requested_changes.events(id),artifact_id uuid NOT NULL UNIQUE REFERENCES gridex_requested_changes.artifacts(id),review_id uuid NOT NULL UNIQUE REFERENCES gridex_requested_changes.reviews(id),company_id uuid NOT NULL,contract_document_id uuid REFERENCES public.customer_contract_documents(id),contract_document_binding jsonb,signature_hash text,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
DO $$DECLARE t text;BEGIN FOR t IN SELECT unnest(ARRAY['artifacts','reviews','issuer_keys','issuer_representations','issuer_revocations','review_origins']) LOOP
 EXECUTE format('ALTER TABLE gridex_requested_changes.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_requested_changes.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_requested_changes.%I FROM PUBLIC,anon,authenticated,service_role',t);
 EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON gridex_requested_changes.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_immutable',t);EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON gridex_requested_changes.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_no_truncate',t);
 END LOOP;END$$;
CREATE FUNCTION gridex_requested_changes.scoped_permission_v1(c uuid,actor uuid,wanted text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM p.id FROM public.permissions p WHERE p.key=wanted ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.user_permissions p WHERE p.user_id=actor AND p.company_id=c ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.user_roles p WHERE p.user_id=actor AND p.company_id=c ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.roles p WHERE EXISTS(SELECT FROM public.user_roles u WHERE u.user_id=actor AND u.company_id=c AND u.role_id=p.id) ORDER BY p.id FOR SHARE;
 PERFORM p.id FROM public.role_permissions p WHERE EXISTS(SELECT FROM public.user_roles u WHERE u.user_id=actor AND u.company_id=c AND u.role_id=p.role_id) ORDER BY p.id FOR SHARE;
 RETURN EXISTS(SELECT FROM public.user_permissions u JOIN public.permissions p ON p.id=u.permission_id OR u.permission_id IS NULL AND p.key=u.permission_key WHERE u.user_id=actor AND u.company_id=c AND u.is_active AND u.status='active' AND u.effect='allow' AND p.is_active AND p.key=wanted)
 OR EXISTS(SELECT FROM public.user_roles u JOIN public.roles r ON r.id=u.role_id JOIN public.role_permissions rp ON rp.role_id=r.id JOIN public.permissions p ON p.id=rp.permission_id OR rp.permission_id IS NULL AND p.key=rp.permission_key WHERE u.user_id=actor AND u.company_id=c AND u.is_active AND u.status='active' AND r.is_active AND rp.effect='allow' AND p.is_active AND p.key=wanted);
END$$;
CREATE FUNCTION gridex_requested_changes.actor_v1(c uuid,actor uuid,mode text,kind text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM id FROM auth.users WHERE id=actor FOR SHARE;PERFORM id FROM public.user_profiles WHERE id=actor FOR SHARE;PERFORM user_id FROM public.company_memberships WHERE company_id=c AND user_id=actor FOR SHARE;
 RETURN actor IS NOT NULL AND mode IN('archive','read','review') AND EXISTS(SELECT FROM public.user_profiles WHERE id=actor AND user_status='active') AND EXISTS(SELECT FROM public.company_memberships WHERE company_id=c AND user_id=actor AND status='active' AND is_active AND accepted_at IS NOT NULL)
 AND EXISTS(SELECT FROM auth.users WHERE id=actor AND deleted_at IS NULL AND (banned_until IS NULL OR banned_until<=now()))
 AND gridex_requested_changes.scoped_permission_v1(c,actor,CASE mode WHEN 'read' THEN 'communication.read' ELSE 'communication.write' END) IS TRUE
 AND gridex_requested_changes.scoped_permission_v1(c,actor,CASE mode WHEN 'read' THEN 'customers.read' ELSE 'customers.write' END) IS TRUE
 AND (kind='death' OR gridex_requested_changes.scoped_permission_v1(c,actor,CASE mode WHEN 'read' THEN 'contracts.read' ELSE 'contracts.write' END) IS TRUE)
 AND (mode<>'review' OR gridex_requested_changes.scoped_permission_v1(c,actor,'ediel.source.review') IS TRUE);
END$$;
CREATE FUNCTION gridex_requested_changes.issuer_revocation_lock_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN
 IF NEW.target_kind='key' THEN PERFORM id FROM gridex_requested_changes.issuer_keys WHERE id=NEW.target_id FOR UPDATE;ELSE PERFORM id FROM gridex_requested_changes.issuer_representations WHERE id=NEW.target_id FOR UPDATE;END IF;
 IF NOT FOUND THEN RAISE EXCEPTION 'requested_change_issuer_revocation_target_required';END IF;RETURN NEW;END$$;
CREATE TRIGGER requested_change_issuer_revocation_lock BEFORE INSERT ON gridex_requested_changes.issuer_revocations FOR EACH ROW EXECUTE FUNCTION gridex_requested_changes.issuer_revocation_lock_v1();
-- HMAC-SHA256 uses only core immutable SHA256/byte operations. No extension,
-- secret export, client verification flag or caller-supplied digest is needed.
CREATE FUNCTION gridex_requested_changes.receipt_hmac_sha256_v1(payload bytea,key bytea) RETURNS bytea LANGUAGE plpgsql IMMUTABLE STRICT SET search_path=pg_catalog AS $$
DECLARE block bytea;inner_pad bytea:=decode(repeat('00',64),'hex');outer_pad bytea:=decode(repeat('00',64),'hex');n int;
BEGIN block:=CASE WHEN octet_length(key)>64 THEN sha256(key) ELSE key END;block:=block||decode(repeat('00',64-octet_length(block)),'hex');
 FOR n IN 0..63 LOOP inner_pad:=set_byte(inner_pad,n,get_byte(block,n)#54);outer_pad:=set_byte(outer_pad,n,get_byte(block,n)#92);END LOOP;
 RETURN sha256(outer_pad||sha256(inner_pad||payload));END$$;
CREATE FUNCTION gridex_requested_changes.receipt_current_v1(a gridex_requested_changes.artifacts) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE k gridex_requested_changes.issuer_keys%rowtype;g gridex_requested_changes.issuer_representations%rowtype;p jsonb;raw bytea;r jsonb:=a.issuer_receipt;issued timestamptz;expires timestamptz;
BEGIN
 IF a.kind<>'death' OR r IS NULL OR jsonb_typeof(r)<>'object' OR coalesce(r->>'signatureHex','')!~'^[a-f0-9]{64}$' OR length(coalesce(r->>'payloadBase64','')) NOT BETWEEN 1 AND 32768 THEN RETURN false;END IF;
 SELECT * INTO k FROM gridex_requested_changes.issuer_keys WHERE id=(r->>'keyId')::uuid AND company_id=a.company_id AND environment=a.environment FOR SHARE;
 SELECT * INTO g FROM gridex_requested_changes.issuer_representations WHERE id=(r->>'representationId')::uuid AND issuer_key_id=k.id AND company_id=a.company_id AND environment=a.environment AND legal_actor_id=a.legal_actor_id AND permitted_kind='death' FOR SHARE;
 IF k.id IS NULL OR g.id IS NULL OR now()<k.valid_from OR now()>=k.valid_to OR now()<g.valid_from OR now()>=g.valid_to OR EXISTS(SELECT FROM gridex_requested_changes.issuer_revocations WHERE target_kind='key' AND target_id=k.id OR target_kind='representation' AND target_id=g.id) THEN RETURN false;END IF;
 raw:=decode(r->>'payloadBase64','base64');IF sha256(gridex_requested_changes.receipt_hmac_sha256_v1(raw,k.receipt_signing_key)) IS DISTINCT FROM sha256(decode(r->>'signatureHex','hex')) THEN RETURN false;END IF;
 p:=convert_from(raw,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;
 RETURN p->>'format'='ediel_requested_change_issuer_receipt_v1' AND p->>'issuerCode'=k.issuer_code AND p->>'receiptId'<>'' AND p->>'companyId'=a.company_id::text AND p->>'environment'=a.environment AND p->>'legalActorId'=a.legal_actor_id::text AND p->>'customerId'=a.customer_id::text AND p->>'meteringPointId'=a.metering_point_id::text AND p->>'kind'='death' AND (p->>'effectiveAt')::timestamptz=a.effective_at AND p->>'sourceHash'=a.source_hash AND p->>'sourceReference'=a.source_reference AND p->>'sourceVersion'=a.source_version AND p->'customerIdentity'=a.claims->'customerIdentity' AND isfinite(issued) AND isfinite(expires) AND issued<=now() AND expires>now() AND issued>=greatest(k.valid_from,g.valid_from) AND expires<=least(k.valid_to,g.valid_to);
EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR invalid_datetime_format OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN false;
END$$;
CREATE FUNCTION public.ediel_archive_requested_change_source_v1(p_company_id uuid,p_actor_user_id uuid,p_submission jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c public.customer_contracts%rowtype;u public.customers%rowtype;mp public.metering_points%rowtype;sp public.customer_supply_periods%rowtype;m public.ediel_messages%rowtype;supply jsonb;bytes bytea;hash text;claims jsonb;ch text;kind text;at timestamptz;sender text;brp text;tokens jsonb;a gridex_requested_changes.artifacts%rowtype;missing jsonb:='["separate_source_review_required"]';
BEGIN
 kind:=p_submission->>'kind';IF (kind IN('death','quarter_contract','method_contract')) IS NOT TRUE OR gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'archive',kind) IS NOT TRUE THEN RAISE EXCEPTION 'requested_change_archive_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_submission)<>'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission) k WHERE k NOT IN('supplyPeriodId','contractId','kind','effectiveAt','source','customerIdentity','invoiceeProfile','issuerReceipt')) OR jsonb_typeof(p_submission->'source') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission->'source') k WHERE k NOT IN('bytesBase64','mimeType','reference','version')) THEN RAISE EXCEPTION 'requested_change_archive_shape_required';END IF;
 IF length(coalesce(p_submission#>>'{source,bytesBase64}',''))>11184812 THEN RAISE EXCEPTION 'requested_change_source_bytes_limit';END IF;bytes:=decode(p_submission#>>'{source,bytesBase64}','base64');hash:=encode(sha256(bytes),'hex');at:=(p_submission->>'effectiveAt')::timestamptz;
 IF octet_length(bytes) NOT BETWEEN 1 AND 8388608 OR (p_submission#>>'{source,mimeType}' IN('application/pdf','text/plain','application/json')) IS NOT TRUE OR nullif(p_submission#>>'{source,reference}','') IS NULL OR length(p_submission#>>'{source,reference}')>2000 OR nullif(p_submission#>>'{source,version}','') IS NULL OR length(p_submission#>>'{source,version}')>200 OR NOT isfinite(at) OR extract(second FROM at)<>0 OR p_submission#>>'{source,mimeType}'='application/pdf' AND substring(bytes,1,5)<>decode('255044462d','hex') THEN RAISE EXCEPTION 'requested_change_source_bytes_or_minute_invalid';END IF;
 SELECT * INTO sp FROM public.customer_supply_periods WHERE id=(p_submission->>'supplyPeriodId')::uuid AND company_id=p_company_id FOR SHARE;
 SELECT * INTO c FROM public.customer_contracts WHERE id=(p_submission->>'contractId')::uuid AND company_id=p_company_id FOR SHARE;
 SELECT * INTO u FROM public.customers WHERE id=sp.customer_id AND company_id=p_company_id FOR SHARE;SELECT * INTO mp FROM public.metering_points WHERE id=sp.metering_point_id AND company_id=p_company_id FOR SHARE;
 supply:=gridex_received_sources.supply_period_source_basis_v1(p_company_id,sp.id,at,at+interval '1 minute');
 IF sp.id IS NULL OR c.id IS NULL OR u.id IS NULL OR mp.id IS NULL OR c.customer_id IS DISTINCT FROM sp.customer_id OR c.metering_point_id IS DISTINCT FROM sp.metering_point_id OR supply->>'qualified' IS DISTINCT FROM 'true' OR supply->>'customerId' IS DISTINCT FROM u.id::text OR supply->>'meteringPointId' IS DISTINCT FROM mp.id::text THEN RAISE EXCEPTION 'requested_change_archive_owned_current_supply_contract_required';END IF;
 SELECT identifier_value INTO sender FROM public.tenant_actor_identifiers WHERE company_id=p_company_id AND environment=supply->>'environment' AND actor_id=(supply->>'legalActorId')::uuid AND identifier_type='EdielId' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now()) ORDER BY id LIMIT 1 FOR SHARE;
 -- The source owner may omit environment in older approved supply snapshots;
 -- it is always taken from the actual initial received original, never input.
 SELECT * INTO m FROM public.ediel_messages WHERE company_id=p_company_id AND id=(supply->>'initialSourceMessageId')::uuid FOR SHARE;
 IF sender IS NULL THEN SELECT identifier_value INTO sender FROM public.tenant_actor_identifiers WHERE company_id=p_company_id AND environment=m.environment AND actor_id=(supply->>'legalActorId')::uuid AND identifier_type='EdielId' AND valid_from<=now() AND (valid_to IS NULL OR valid_to>now()) ORDER BY id LIMIT 1 FOR SHARE;END IF;
 tokens:=gridex_received_sources.closure_wire_tokens_v2(m.raw_payload);SELECT t#>>'{elements,2,0}' INTO brp FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='NAD' AND t#>>'{elements,1,0}'='Z02' AND t#>>'{elements,2,1}'='160' AND t#>>'{elements,2,2}'='SVK';
 IF sender IS NULL OR brp IS NULL OR (SELECT count(*) FROM jsonb_array_elements(supply->'sourceObjects') x WHERE x->>'point'=mp.ediel_metering_point_id AND x->>'identityAgency' IN('9','89'))<>1 THEN RAISE EXCEPTION 'requested_change_archive_physical_original_identity_required';END IF;
 claims:=jsonb_build_object('kind',kind,'effectiveAt',at,'customerIdentity',p_submission->'customerIdentity','invoiceeProfile',p_submission->'invoiceeProfile');ch:=encode(sha256(convert_to(claims::text,'UTF8')),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended('requested_change_archive:'||p_company_id::text||hash||ch,0));
 SELECT * INTO a FROM gridex_requested_changes.artifacts WHERE company_id=p_company_id AND environment=m.environment AND source_hash=hash AND claims_hash=ch FOR SHARE;
 IF FOUND THEN IF a.supply_period_id IS DISTINCT FROM sp.id OR a.contract_id IS DISTINCT FROM c.id OR a.source_reference IS DISTINCT FROM p_submission#>>'{source,reference}' OR a.source_version IS DISTINCT FROM p_submission#>>'{source,version}' OR a.issuer_receipt IS DISTINCT FROM p_submission->'issuerReceipt' THEN RAISE EXCEPTION 'requested_change_archive_original_conflict';END IF;
 ELSE INSERT INTO gridex_requested_changes.artifacts(company_id,environment,supply_period_id,contract_id,customer_id,metering_point_id,legal_actor_id,legal_sender_id,legal_receiver_id,point_id,identity_agency,grid_area_code,brp_ediel_id,supply_source_message_id,supply_state_version,protected_contract_hash,customer_snapshot_hash,kind,effective_at,source_bytes,source_hash,mime_type,source_reference,source_version,claims,claims_hash,issuer_receipt,submitted_by)
 VALUES(p_company_id,m.environment,sp.id,c.id,u.id,mp.id,(supply->>'legalActorId')::uuid,sender,supply->>'dsoEdielId',mp.ediel_metering_point_id,(SELECT x->>'identityAgency' FROM jsonb_array_elements(supply->'sourceObjects') x WHERE x->>'point'=mp.ediel_metering_point_id),mp.grid_area_code,brp,(supply->>'sourceMessageId')::uuid,(supply->>'marketStateVersion')::bigint,gridex_received_sources.production_contract_hash_v1(c),encode(sha256(convert_to((to_jsonb(u)-'updated_at')::text,'UTF8')),'hex'),kind,at,bytes,hash,p_submission#>>'{source,mimeType}',p_submission#>>'{source,reference}',p_submission#>>'{source,version}',claims,ch,p_submission->'issuerReceipt',p_actor_user_id) RETURNING * INTO a;END IF;
 IF kind='death' AND gridex_requested_changes.receipt_current_v1(a) IS NOT TRUE THEN missing:=missing||'"authentic_current_issuer_and_representation_receipt"'::jsonb;END IF;
 RETURN jsonb_build_object('status','archived','artifactId',a.id,'sourceHash',a.source_hash,'claimsHash',a.claims_hash,'missing',missing);
END$$;
CREATE FUNCTION public.ediel_read_requested_change_artifact_v1(p_company_id uuid,p_artifact_id uuid,p_actor_user_id uuid,p_include_bytes boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_requested_changes.artifacts%rowtype;r gridex_requested_changes.reviews%rowtype;o gridex_requested_changes.review_origins%rowtype;result jsonb;b jsonb;
BEGIN SELECT * INTO STRICT a FROM gridex_requested_changes.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR SHARE;
 IF gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'read',a.kind) IS NOT TRUE THEN RAISE EXCEPTION 'requested_change_artifact_read_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO r FROM gridex_requested_changes.reviews WHERE artifact_id=a.id ORDER BY reviewed_at DESC,id DESC LIMIT 1;SELECT * INTO o FROM gridex_requested_changes.review_origins WHERE artifact_id=a.id;
 IF o.event_id IS NOT NULL THEN SELECT reviewer_user_id INTO r.reviewer_user_id FROM gridex_requested_changes.reviews WHERE id=o.review_id;b:=gridex_requested_changes.context_v1(a.company_id,o.event_id,r.reviewer_user_id,'communication.write');END IF;
 IF a.source_bytes IS NULL THEN b:=jsonb_build_object('status','held','missing',ARRAY['requested_change_source_bytes_retention_tombstone']);END IF;
 result:=jsonb_build_object('artifactId',a.id,'kind',a.kind,'effectiveAt',a.effective_at,'sourceReference',a.source_reference,'sourceVersion',a.source_version,'sourceHash',a.source_hash,'claimsHash',a.claims_hash,'mimeType',a.mime_type,'byteLength',coalesce(octet_length(a.source_bytes),(to_jsonb(a)->>'source_byte_length')::int),'customerIdentity',a.claims->'customerIdentity','invoiceeProfile',a.claims->'invoiceeProfile','status',CASE WHEN o.event_id IS NOT NULL AND b->>'status'='authorized' THEN 'authorized' WHEN b->>'status'='held' THEN 'held' WHEN r.decision='approved' THEN 'held' WHEN r.id IS NOT NULL THEN r.decision ELSE 'archived' END,'eventId',o.event_id,'missing',coalesce(b->'missing',r.missing,'["separate_source_review_required"]'::jsonb));
 IF p_include_bytes THEN IF a.source_bytes IS NULL THEN RAISE EXCEPTION 'requested_change_artifact_bytes_retained_as_tombstone';END IF;result:=result||jsonb_build_object('bytesBase64',encode(a.source_bytes,'base64'));END IF;RETURN result;
END$$;
CREATE FUNCTION public.ediel_review_requested_change_artifact_v1(p_company_id uuid,p_artifact_id uuid,p_actor_user_id uuid,p_review jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_requested_changes.artifacts%rowtype;c public.customer_contracts%rowtype;d public.customer_contract_documents%rowtype;o gridex_requested_changes.review_origins%rowtype;e gridex_requested_changes.events%rowtype;review_id uuid;missing jsonb:='[]';b jsonb;decision text;sig text;
BEGIN SELECT * INTO STRICT a FROM gridex_requested_changes.artifacts WHERE id=p_artifact_id AND company_id=p_company_id FOR UPDATE;
 IF gridex_requested_changes.actor_v1(p_company_id,p_actor_user_id,'review',a.kind) IS NOT TRUE THEN RAISE EXCEPTION 'requested_change_review_actor_forbidden' USING ERRCODE='42501';END IF;
 IF a.source_bytes IS NULL THEN RAISE EXCEPTION 'requested_change_artifact_bytes_retained_as_tombstone';END IF;
 decision:=p_review->>'decision';IF jsonb_typeof(p_review) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review) k WHERE k NOT IN('sourceHash','claimsHash','decision','reason','clause')) OR decision NOT IN('approve','hold','reject') OR p_review->>'sourceHash' IS DISTINCT FROM a.source_hash OR p_review->>'claimsHash' IS DISTINCT FROM a.claims_hash OR nullif(p_review->>'reason','') IS NULL OR length(p_review->>'reason')>4000 THEN RAISE EXCEPTION 'requested_change_review_actual_archived_candidate_required';END IF;
 IF decision='approve' AND a.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'requested_change_separate_reviewer_required';END IF;
 SELECT * INTO o FROM gridex_requested_changes.review_origins WHERE artifact_id=a.id FOR SHARE;
 IF FOUND THEN IF decision<>'approve' THEN RAISE EXCEPTION 'requested_change_authorized_origin_requires_revocation';END IF;b:=gridex_requested_changes.context_v1(p_company_id,o.event_id,p_actor_user_id,'communication.write');IF b->>'status' IS DISTINCT FROM 'authorized' THEN RETURN jsonb_build_object('status','held','artifactId',a.id,'missing',b->'missing');END IF;RETURN jsonb_build_object('status','authorized','artifactId',a.id,'eventId',o.event_id);END IF;
 IF decision='hold' THEN missing:='["explicit_source_review_hold"]';ELSIF decision='reject' THEN missing:='["explicit_source_review_rejection"]';
 ELSIF a.kind='death' THEN IF gridex_requested_changes.receipt_current_v1(a) IS NOT TRUE THEN missing:='["authentic_current_issuer_and_representation_receipt"]';END IF;
 ELSE
  SELECT * INTO c FROM public.customer_contracts WHERE id=a.contract_id AND company_id=a.company_id FOR SHARE;
  sig:=encode(sha256(convert_to(c.signature_snapshot::text,'UTF8')),'hex');SELECT * INTO d FROM public.customer_contract_documents WHERE company_id=a.company_id AND customer_contract_id=c.id AND document_type='signed_contract_pdf' AND document_sha256=a.source_hash AND verified_at IS NOT NULL ORDER BY id LIMIT 1 FOR SHARE;
  IF c.id IS NULL OR d.id IS NULL OR a.mime_type<>'application/pdf' OR c.document_sha256 IS DISTINCT FROM a.source_hash OR c.signed_at IS NULL OR c.signed_version IS DISTINCT FROM c.contract_version OR c.signature_snapshot_sha256 IS DISTINCT FROM sig OR c.signature_snapshot->>'company_id' IS DISTINCT FROM a.company_id::text OR c.signature_snapshot->>'customer_id' IS DISTINCT FROM a.customer_id::text OR c.signature_snapshot->>'contract_id' IS DISTINCT FROM c.id::text OR jsonb_typeof(p_review->'clause') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_review->'clause') k WHERE k NOT IN('locator','quote')) OR nullif(p_review#>>'{clause,locator}','') IS NULL OR length(p_review#>>'{clause,locator}')>1000 OR nullif(p_review#>>'{clause,quote}','') IS NULL OR length(p_review#>>'{clause,quote}')>10000 THEN missing:='["actual_own_signed_contract_pdf_signature_and_verbatim_metering_clause"]';END IF;
 END IF;
 IF missing<>'[]'::jsonb THEN INSERT INTO gridex_requested_changes.reviews(artifact_id,company_id,reviewer_user_id,decision,reason,clause,missing) VALUES(a.id,a.company_id,p_actor_user_id,CASE decision WHEN 'reject' THEN 'rejected' ELSE 'held' END,p_review->>'reason',p_review->'clause',missing);RETURN jsonb_build_object('status',CASE decision WHEN 'reject' THEN 'rejected' ELSE 'held' END,'artifactId',a.id,'missing',missing);END IF;
 INSERT INTO gridex_requested_changes.events(company_id,environment,supply_period_id,supply_source_message_id,supply_state_version,contract_id,protected_contract_hash,customer_id,metering_point_id,customer_snapshot_hash,legal_actor_id,legal_sender_id,legal_receiver_id,point_id,identity_agency,grid_area_code,brp_ediel_id,variant,event_kind,effective_at,customer_identity,invoicee_profile,source_reference,source_sha256,source_version,approved_by,approved_at)
 VALUES(a.company_id,a.environment,a.supply_period_id,a.supply_source_message_id,a.supply_state_version,a.contract_id,a.protected_contract_hash,a.customer_id,a.metering_point_id,a.customer_snapshot_hash,a.legal_actor_id,a.legal_sender_id,a.legal_receiver_id,a.point_id,a.identity_agency,a.grid_area_code,a.brp_ediel_id,CASE a.kind WHEN 'death' THEN 'E' WHEN 'quarter_contract' THEN 'F' ELSE 'G' END,a.kind,a.effective_at,a.claims->'customerIdentity',a.claims->'invoiceeProfile',a.source_reference,a.source_hash,a.source_version,p_actor_user_id,now()) RETURNING * INTO e;
 b:=gridex_requested_changes.context_before_intake_v1(a.company_id,e.id,p_actor_user_id,'communication.write');IF b->>'status' IS DISTINCT FROM 'authorized' THEN RAISE EXCEPTION 'requested_change_review_current_owned_source_required';END IF;
 INSERT INTO gridex_requested_changes.reviews(artifact_id,company_id,reviewer_user_id,decision,reason,clause) VALUES(a.id,a.company_id,p_actor_user_id,'approved',p_review->>'reason',p_review->'clause') RETURNING id INTO review_id;
 INSERT INTO gridex_requested_changes.review_origins(event_id,artifact_id,review_id,company_id,contract_document_id,contract_document_binding,signature_hash) VALUES(e.id,a.id,review_id,a.company_id,d.id,CASE WHEN d.id IS NULL THEN NULL ELSE to_jsonb(d) END,sig);
 RETURN jsonb_build_object('status','authorized','artifactId',a.id,'eventId',e.id);
END$$;
ALTER FUNCTION gridex_requested_changes.context_v1(uuid,uuid,uuid,text) RENAME TO context_before_intake_v1;
CREATE FUNCTION gridex_requested_changes.context_v1(c uuid,event uuid,actor uuid,permission text DEFAULT 'communication.write') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE b jsonb;o gridex_requested_changes.review_origins%rowtype;a gridex_requested_changes.artifacts%rowtype;r gridex_requested_changes.reviews%rowtype;contract public.customer_contracts%rowtype;doc public.customer_contract_documents%rowtype;
BEGIN b:=gridex_requested_changes.context_before_intake_v1(c,event,actor,permission);IF b->>'status' IS DISTINCT FROM 'authorized' THEN RETURN b;END IF;
 SELECT * INTO o FROM gridex_requested_changes.review_origins WHERE event_id=event AND company_id=c FOR SHARE;SELECT * INTO a FROM gridex_requested_changes.artifacts WHERE id=o.artifact_id AND company_id=c FOR SHARE;SELECT * INTO r FROM gridex_requested_changes.reviews WHERE id=o.review_id AND artifact_id=a.id AND company_id=c FOR SHARE;
 IF o.event_id IS NULL OR a.id IS NULL OR r.decision IS DISTINCT FROM 'approved' OR r.reviewer_user_id=a.submitted_by OR gridex_requested_changes.actor_v1(c,r.reviewer_user_id,'review',a.kind) IS NOT TRUE OR encode(sha256(a.source_bytes),'hex') IS DISTINCT FROM a.source_hash OR encode(sha256(convert_to(a.claims::text,'UTF8')),'hex') IS DISTINCT FROM a.claims_hash THEN RETURN jsonb_build_object('status','held','missing',ARRAY['requested_change_current_immutable_archived_review_authority']);END IF;
 IF a.kind='death' THEN IF gridex_requested_changes.receipt_current_v1(a) IS NOT TRUE THEN RETURN jsonb_build_object('status','held','missing',ARRAY['authentic_current_issuer_and_representation_receipt']);END IF;
 ELSE SELECT * INTO contract FROM public.customer_contracts WHERE id=a.contract_id AND company_id=c FOR SHARE;SELECT * INTO doc FROM public.customer_contract_documents WHERE id=o.contract_document_id AND company_id=c AND customer_contract_id=contract.id FOR SHARE;
  IF doc.id IS NULL OR to_jsonb(doc) IS DISTINCT FROM o.contract_document_binding OR contract.document_sha256 IS DISTINCT FROM a.source_hash OR contract.signature_snapshot_sha256 IS DISTINCT FROM o.signature_hash OR encode(sha256(convert_to(contract.signature_snapshot::text,'UTF8')),'hex') IS DISTINCT FROM o.signature_hash THEN RETURN jsonb_build_object('status','held','missing',ARRAY['actual_current_signed_contract_document_signature']);END IF;
 END IF;RETURN b;
END$$;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA gridex_requested_changes FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.ediel_archive_requested_change_source_v1(uuid,uuid,jsonb),public.ediel_read_requested_change_artifact_v1(uuid,uuid,uuid,boolean),public.ediel_review_requested_change_artifact_v1(uuid,uuid,uuid,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_archive_requested_change_source_v1(uuid,uuid,jsonb),public.ediel_read_requested_change_artifact_v1(uuid,uuid,uuid,boolean),public.ediel_review_requested_change_artifact_v1(uuid,uuid,uuid,jsonb) TO service_role;
COMMIT;
