-- CLI forward. National Z08H is a legal rescission request, not an LK
-- agreement and not an inference from payment, bankruptcy or customer status.
BEGIN;
CREATE SCHEMA gridex_supply_rescission;
REVOKE ALL ON SCHEMA gridex_supply_rescission FROM PUBLIC,anon,authenticated,service_role;
INSERT INTO public.permissions(key,name,category,description,is_active) VALUES('ediel.supply_rescission.review','Review archived legal supply rescission source','ediel','Independent review of authenticated national Z08H legal original',true) ON CONFLICT(key) DO NOTHING;
CREATE TABLE gridex_supply_rescission.artifacts(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL,
 selector jsonb NOT NULL,scope jsonb NOT NULL,scope_hash text NOT NULL,source_bytes bytea NOT NULL,source_hash text NOT NULL,
 mime_type text NOT NULL,source_reference text NOT NULL,source_version text NOT NULL,issuer_receipt jsonb,receipt_hash text NOT NULL,
 submitted_by uuid NOT NULL REFERENCES auth.users(id),archived_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(company_id,environment,scope_hash,source_hash,receipt_hash));
CREATE TABLE gridex_supply_rescission.issuer_keys(
 id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL,issuer_code text NOT NULL,
 authority_reference text NOT NULL,authority_source_hash text NOT NULL,receipt_signing_key bytea NOT NULL,valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL);
CREATE TABLE gridex_supply_rescission.issuer_representations(
 id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL,issuer_key_id uuid NOT NULL REFERENCES gridex_supply_rescission.issuer_keys(id),
 legal_actor_id uuid NOT NULL,dso_actor_id uuid NOT NULL,grid_area_code text NOT NULL,legal_representation_reference text NOT NULL,legal_authority_source_hash text NOT NULL,
 valid_from timestamptz NOT NULL,valid_to timestamptz NOT NULL);
CREATE TABLE gridex_supply_rescission.issuer_revocations(target_kind text NOT NULL CHECK(target_kind IN('key','representation')),target_id uuid NOT NULL,source_reference text NOT NULL,source_hash text NOT NULL,revoked_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(target_kind,target_id));
CREATE TABLE gridex_supply_rescission.reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),artifact_id uuid NOT NULL REFERENCES gridex_supply_rescission.artifacts(id),reviewer_user_id uuid NOT NULL REFERENCES auth.users(id),decision text NOT NULL,reason text NOT NULL,source_clause_locator text,source_clause_quote text,missing jsonb NOT NULL,reviewed_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_supply_rescission.mandates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),environment text NOT NULL,artifact_id uuid NOT NULL UNIQUE REFERENCES gridex_supply_rescission.artifacts(id),review_id uuid NOT NULL UNIQUE REFERENCES gridex_supply_rescission.reviews(id),scope jsonb NOT NULL,source_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['artifacts','issuer_keys','issuer_representations','issuer_revocations','reviews','mandates'] LOOP
 EXECUTE format('ALTER TABLE gridex_supply_rescission.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_supply_rescission.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_supply_rescission.%I FROM PUBLIC,anon,authenticated,service_role',t);
 EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON gridex_supply_rescission.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_immutable',t);EXECUTE format('CREATE TRIGGER %I BEFORE TRUNCATE ON gridex_supply_rescission.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.permission_transition_immutable_v1()',t||'_no_truncate',t);
 END LOOP;END$$;
CREATE FUNCTION gridex_supply_rescission.lock_v1() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM gridex_ediel_ack_replay.lock_current_graph_v2();PERFORM gridex_bilateral_prodat.lock_source_receipts_v1();
 LOCK TABLE gridex_supply_rescission.artifacts,gridex_supply_rescission.issuer_keys,gridex_supply_rescission.issuer_representations,gridex_supply_rescission.issuer_revocations,gridex_supply_rescission.reviews,gridex_supply_rescission.mandates IN SHARE ROW EXCLUSIVE MODE;
END$$;
CREATE FUNCTION gridex_supply_rescission.actor_v1(c uuid,actor uuid,mode text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 PERFORM gridex_supply_rescission.lock_v1();RETURN mode IN('archive','read','review') AND gridex_bilateral_prodat.actor_v1(c,actor,CASE mode WHEN 'review' THEN 'read' ELSE mode END)
 AND(mode='read' OR public.gridex_actor_has_company_permission(actor,c,'metering.write')) AND(mode<>'review' OR public.gridex_actor_has_company_permission(actor,c,'communication.write') AND public.gridex_actor_has_company_permission(actor,c,'ediel.supply_rescission.review'));
END$$;
CREATE FUNCTION gridex_supply_rescission.calendar_cutoff_v1(effective timestamptz,observed timestamptz) RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path=pg_catalog AS $$
 SELECT effective IS NOT NULL AND observed IS NOT NULL AND isfinite(effective) AND isfinite(observed) AND ((observed AT TIME ZONE 'UTC')+interval '1 hour')::date<=((effective AT TIME ZONE 'UTC')+interval '1 hour')::date
$$;
CREATE FUNCTION gridex_supply_rescission.scope_v1(c uuid,selector jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$
DECLARE p public.customer_supply_periods%rowtype;mp public.metering_points%rowtype;customer public.customers%rowtype;contract public.customer_contracts%rowtype;site public.customer_sites%rowtype;
 basis jsonb;env text;sender text;initial public.ediel_messages%rowtype;effective timestamptz;legal uuid;dso uuid;pack public.ediel_rule_packs%rowtype;profiles jsonb;grammar jsonb;identity text;ids uuid[];BEGIN
 PERFORM gridex_supply_rescission.lock_v1();
 IF jsonb_typeof(selector) IS DISTINCT FROM 'object' OR selector-ARRAY['environment','supplyPeriodId','effectiveAt','rulePackId']<>'{}'::jsonb OR NOT(selector ?& ARRAY['environment','supplyPeriodId','effectiveAt','rulePackId']) THEN RETURN NULL;END IF;
 env:=selector->>'environment';effective:=(selector->>'effectiveAt')::timestamptz;
 IF env NOT IN('test','production') OR effective IS NULL OR NOT isfinite(effective) OR date_trunc('minute',effective) IS DISTINCT FROM effective THEN RETURN NULL;END IF;
 SELECT * INTO p FROM public.customer_supply_periods WHERE id=(selector->>'supplyPeriodId')::uuid AND company_id=c;
 IF p.id IS NULL OR p.market_start_at>=effective OR p.market_end_at IS NOT NULL OR p.source_end_message_id IS NOT NULL OR (p.status IN('active','confirmed_by_grid_owner')) IS NOT TRUE THEN RETURN NULL;END IF;
 SELECT * INTO mp FROM public.metering_points WHERE id=p.metering_point_id AND company_id=c;
 SELECT * INTO customer FROM public.customers WHERE id=p.customer_id AND company_id=c;
 SELECT * INTO site FROM public.customer_sites WHERE id=coalesce(mp.customer_site_id,mp.site_id) AND company_id=c AND customer_id=p.customer_id;
 SELECT * INTO contract FROM public.customer_contracts WHERE id=coalesce(p.contract_id,p.customer_contract_id) AND company_id=c AND customer_id=p.customer_id AND metering_point_id=mp.id;
 basis:=gridex_received_sources.supply_period_source_basis_v1(c,p.id,effective-interval '1 minute',effective);
 IF basis IS NULL OR basis->>'qualified' IS DISTINCT FROM 'true' OR nullif(basis->>'originalMessageId','') IS NULL OR coalesce(basis->>'originalPayloadHash','')!~'^[a-f0-9]{64}$' OR (SELECT environment FROM public.ediel_messages WHERE id=p.source_message_id AND company_id=c) IS DISTINCT FROM env OR mp.id IS NULL OR customer.id IS NULL OR site.id IS NULL OR contract.id IS NULL OR mp.customer_id IS DISTINCT FROM p.customer_id OR nullif(mp.ediel_metering_point_id,'') IS NULL OR nullif(mp.grid_area_code,'') IS NULL OR nullif(mp.grid_owner_ediel_id,'') IS NULL THEN RETURN NULL;END IF;
 legal:=(basis->>'legalActorId')::uuid;
 SELECT * INTO initial FROM public.ediel_messages WHERE id=p.source_message_id AND company_id=c AND environment=env;
 sender:=gridex_received_sources.normal_switch_wire_v1(initial.raw_payload)->>'receiver';
 IF nullif(sender,'') IS NULL OR (SELECT count(DISTINCT(company_id,actor_id)) FROM public.tenant_actor_identifiers WHERE environment=env AND identifier_type='EdielId' AND identifier_value=sender AND valid_from<=now() AND(valid_to IS NULL OR now()<valid_to))<>1 OR NOT EXISTS(SELECT FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=env AND actor_id=legal AND identifier_type='EdielId' AND identifier_value=sender AND valid_from<=now() AND(valid_to IS NULL OR now()<valid_to)) OR NOT EXISTS(SELECT FROM public.tenant_actor_roles WHERE company_id=c AND environment=env AND actor_id=legal AND role_code='electricity_supplier' AND valid_from<=now() AND(valid_to IS NULL OR now()<valid_to)) THEN RETURN NULL;END IF;
 SELECT array_agg(DISTINCT actor_id) INTO ids FROM public.platform_actor_identifiers WHERE identifier_value=mp.grid_owner_ediel_id AND lower(identifier_type) IN('edielid','ediel_id') AND is_verified AND(valid_from IS NULL OR valid_from<=current_date) AND(valid_to IS NULL OR current_date<=valid_to);
 IF coalesce(cardinality(ids),0)<>1 THEN RETURN NULL;END IF;dso:=ids[1];
 SELECT * INTO pack FROM public.ediel_rule_packs WHERE id=(selector->>'rulePackId')::uuid AND family='PRODAT' AND market='electricity' AND status='active' AND guide_version='26.A' AND guide_revision='3' AND valid_from<=current_date AND(valid_to IS NULL OR current_date<=valid_to);
 IF pack.id IS NULL OR NOT EXISTS(SELECT FROM public.ediel_rule_pack_sources WHERE rule_pack_id=pack.id) THEN RETURN NULL;END IF;
 SELECT jsonb_agg(to_jsonb(selected_profile) ORDER BY selected_profile.id) INTO profiles FROM public.ediel_message_profiles selected_profile WHERE selected_profile.rule_pack_id=pack.id AND selected_profile.is_enabled AND(selected_profile.message_code='Z08' AND selected_profile.transaction_subtype='H' AND selected_profile.direction IN('outbound','both') OR selected_profile.message_code='Z05' AND selected_profile.transaction_subtype='L' AND selected_profile.direction IN('inbound','both'));
 IF jsonb_array_length(profiles)<>2 OR NOT EXISTS(SELECT FROM jsonb_array_elements(profiles) profile WHERE profile->>'profile_key'='PRODAT:Z08:H:26.A:r3') OR NOT EXISTS(SELECT FROM jsonb_array_elements(profiles) profile WHERE profile->>'profile_key'='PRODAT:Z05:L:26.A:r3') THEN RETURN NULL;END IF;
 grammar:=jsonb_build_object('pack',to_jsonb(pack),'profiles',profiles,'sources',(SELECT jsonb_agg(to_jsonb(s) ORDER BY s.id) FROM public.ediel_rule_pack_sources s WHERE s.rule_pack_id=pack.id),'fields',(SELECT jsonb_agg(to_jsonb(f) ORDER BY f.id) FROM public.ediel_field_rules f WHERE f.message_profile_id IN(SELECT(profile->>'id')::uuid FROM jsonb_array_elements(profiles) profile)),'segments',(SELECT jsonb_agg(to_jsonb(s) ORDER BY s.id) FROM public.ediel_segment_rules s WHERE s.message_profile_id IN(SELECT(profile->>'id')::uuid FROM jsonb_array_elements(profiles) profile)));
 identity:=coalesce(nullif(btrim(customer.org_number),''),nullif(btrim(customer.personal_number),''));IF nullif(identity,'') IS NULL THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('purpose','national_prodat_z08h_legal_rescission','companyId',c,'environment',env,'periodId',p.id,'stateVersion',p.market_state_version,'initialSourceMessageId',p.source_message_id,'initialPayloadHash',encode(sha256(convert_to(initial.raw_payload,'UTF8')),'hex'),'originalMessageId',basis->>'originalMessageId','originalPayloadHash',basis->>'originalPayloadHash','customerId',customer.id,'siteId',site.id,'pointId',mp.id,'contractId',contract.id,'contractHash',gridex_received_sources.production_contract_hash_v1(contract),'externalPoint',mp.ediel_metering_point_id,'identityAgency','9','gridArea',mp.grid_area_code,'legalActorId',legal,'legalSenderId',sender,'dsoActorId',dso,'legalReceiverId',mp.grid_owner_ediel_id,'customerIdentity',jsonb_build_object('id',identity,'qualifier',CASE WHEN nullif(btrim(customer.org_number),'') IS NOT NULL THEN 'SE1' ELSE 'SE2' END,'agency','260'),'effectiveAt',effective,'rulePackId',pack.id,'sourceGrammar',grammar,'sourceGrammarHash',encode(sha256(convert_to(grammar::text,'UTF8')),'hex'));
EXCEPTION WHEN invalid_text_representation OR invalid_datetime_format OR datetime_field_overflow THEN RETURN NULL;END$$;
CREATE FUNCTION public.ediel_supply_rescission_scope_v1(p_company_id uuid,p_actor_user_id uuid,p_selector jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE scope jsonb;BEGIN
 IF gridex_supply_rescission.actor_v1(p_company_id,p_actor_user_id,'read') IS NOT TRUE THEN RAISE EXCEPTION 'supply_rescission_actor_forbidden' USING ERRCODE='42501';END IF;
 scope:=gridex_supply_rescission.scope_v1(p_company_id,p_selector);IF scope IS NULL THEN RETURN jsonb_build_object('status','held','companyId',p_company_id,'missing',ARRAY['actual_current_own_supply_signed_contract_and_national_source_grammar']);END IF;
 RETURN jsonb_build_object('status','scoped','companyId',p_company_id,'scope',scope,'scopeHash',encode(sha256(convert_to(scope::text,'UTF8')),'hex'),'missing','[]'::jsonb);
END$$;
CREATE FUNCTION public.ediel_archive_supply_rescission_v1(p_company_id uuid,p_actor_user_id uuid,p_submission jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$
DECLARE selector jsonb;v_scope jsonb;bytes bytea;hash text;rh text;a gridex_supply_rescission.artifacts%rowtype;BEGIN
 IF gridex_supply_rescission.actor_v1(p_company_id,p_actor_user_id,'archive') IS NOT TRUE THEN RAISE EXCEPTION 'supply_rescission_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_submission) IS DISTINCT FROM 'object' OR p_submission-ARRAY['environment','supplyPeriodId','effectiveAt','rulePackId','source','issuerReceipt']<>'{}'::jsonb OR jsonb_typeof(p_submission->'source') IS DISTINCT FROM 'object' OR (p_submission->'source')-ARRAY['bytesBase64','mimeType','reference','version']<>'{}'::jsonb THEN RAISE EXCEPTION 'supply_rescission_archive_shape_required';END IF;
 selector:=p_submission-ARRAY['source','issuerReceipt'];v_scope:=gridex_supply_rescission.scope_v1(p_company_id,selector);IF v_scope IS NULL THEN RETURN jsonb_build_object('status','held','companyId',p_company_id,'missing',ARRAY['actual_current_own_supply_signed_contract_and_national_source_grammar']);END IF;
 bytes:=decode(p_submission#>>'{source,bytesBase64}','base64');hash:=encode(sha256(bytes),'hex');rh:=encode(sha256(convert_to(coalesce(p_submission->'issuerReceipt','null')::text,'UTF8')),'hex');
 IF octet_length(bytes) NOT BETWEEN 1 AND 8388608 OR p_submission#>>'{source,mimeType}' NOT IN('application/pdf','text/plain') OR nullif(btrim(p_submission#>>'{source,reference}'),'') IS NULL OR length(p_submission#>>'{source,reference}')>2000 OR nullif(btrim(p_submission#>>'{source,version}'),'') IS NULL OR length(p_submission#>>'{source,version}')>200 THEN RAISE EXCEPTION 'supply_rescission_original_bytes_reference_required';END IF;
 SELECT * INTO a FROM gridex_supply_rescission.artifacts WHERE company_id=p_company_id AND environment=v_scope->>'environment' AND scope_hash=encode(sha256(convert_to(v_scope::text,'UTF8')),'hex') AND source_hash=hash AND receipt_hash=rh;
 IF a.id IS NULL THEN INSERT INTO gridex_supply_rescission.artifacts(company_id,environment,selector,scope,scope_hash,source_bytes,source_hash,mime_type,source_reference,source_version,issuer_receipt,receipt_hash,submitted_by) VALUES(p_company_id,v_scope->>'environment',selector,v_scope,encode(sha256(convert_to(v_scope::text,'UTF8')),'hex'),bytes,hash,p_submission#>>'{source,mimeType}',p_submission#>>'{source,reference}',p_submission#>>'{source,version}',p_submission->'issuerReceipt',rh,p_actor_user_id) RETURNING * INTO a;END IF;
 RETURN jsonb_build_object('status','archived','companyId',p_company_id,'artifactId',a.id,'sourceHash',a.source_hash,'scopeHash',a.scope_hash,'missing',ARRAY['authentic_legal_rescission_issuer_and_separate_qualified_review']);
END$$;
CREATE FUNCTION gridex_supply_rescission.receipt_current_v1(a gridex_supply_rescission.artifacts) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$
DECLARE key gridex_supply_rescission.issuer_keys%rowtype;representation gridex_supply_rescission.issuer_representations%rowtype;payload jsonb;bytes bytea;issued timestamptz;expires timestamptz;completed timestamptz;BEGIN
 PERFORM gridex_supply_rescission.lock_v1();
 IF a.source_bytes IS NULL OR encode(sha256(a.source_bytes),'hex') IS DISTINCT FROM a.source_hash OR encode(sha256(convert_to(a.scope::text,'UTF8')),'hex') IS DISTINCT FROM a.scope_hash OR jsonb_typeof(a.issuer_receipt) IS DISTINCT FROM 'object' OR a.issuer_receipt-ARRAY['keyId','representationId','payloadBase64','signatureHex']<>'{}'::jsonb OR coalesce(a.issuer_receipt->>'signatureHex','')!~'^[a-f0-9]{64}$' THEN RETURN false;END IF;
 SELECT * INTO key FROM gridex_supply_rescission.issuer_keys WHERE id=(a.issuer_receipt->>'keyId')::uuid AND company_id=a.company_id AND environment=a.environment;
 SELECT * INTO representation FROM gridex_supply_rescission.issuer_representations WHERE id=(a.issuer_receipt->>'representationId')::uuid AND issuer_key_id=key.id AND company_id=a.company_id AND environment=a.environment AND legal_actor_id::text=a.scope->>'legalActorId' AND dso_actor_id::text=a.scope->>'dsoActorId' AND grid_area_code=a.scope->>'gridArea';
 IF key.id IS NULL OR representation.id IS NULL OR now()<greatest(key.valid_from,representation.valid_from) OR now()>=least(key.valid_to,representation.valid_to) OR EXISTS(SELECT FROM gridex_supply_rescission.issuer_revocations v WHERE v.target_kind='key' AND v.target_id=key.id OR v.target_kind='representation' AND v.target_id=representation.id) THEN RETURN false;END IF;
 bytes:=decode(a.issuer_receipt->>'payloadBase64','base64');IF octet_length(bytes) NOT BETWEEN 1 AND 65536 OR sha256(gridex_requested_changes.receipt_hmac_sha256_v1(bytes,key.receipt_signing_key)) IS DISTINCT FROM sha256(decode(a.issuer_receipt->>'signatureHex','hex')) THEN RETURN false;END IF;
 payload:=convert_from(bytes,'UTF8')::jsonb;issued:=(payload->>'issuedAt')::timestamptz;expires:=(payload->>'expiresAt')::timestamptz;completed:=(payload->>'legalPrerequisitesCompletedAt')::timestamptz;
 RETURN(payload->>'format'='ediel_national_supply_rescission_receipt_v1' AND payload->>'purpose'='national_prodat_z08h_legal_rescission' AND payload->>'issuerCode'=key.issuer_code AND payload->>'companyId'=a.company_id::text AND payload->>'environment'=a.environment AND payload->'scope'=a.scope AND payload->>'sourceHash'=a.source_hash AND payload->>'sourceReference'=a.source_reference AND payload->>'sourceVersion'=a.source_version
 AND nullif(btrim(payload->>'receiptId'),'') IS NOT NULL AND nullif(btrim(payload->>'legalCaseReference'),'') IS NOT NULL AND nullif(btrim(payload->>'legalDecisionReference'),'') IS NOT NULL AND nullif(btrim(payload->>'legalPrerequisitesReference'),'') IS NOT NULL
 AND isfinite(issued) AND isfinite(expires) AND isfinite(completed) AND completed<=issued AND issued<=now() AND completed<=(a.scope->>'effectiveAt')::timestamptz AND issued>=greatest(key.valid_from,representation.valid_from) AND expires>now() AND expires>(a.scope->>'effectiveAt')::timestamptz AND expires<=least(key.valid_to,representation.valid_to)) IS TRUE;
EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR invalid_datetime_format OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN false;END$$;
CREATE FUNCTION gridex_supply_rescission.mandate_current_v1(c uuid,mandate uuid,fresh boolean DEFAULT true) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$
DECLARE m gridex_supply_rescission.mandates%rowtype;a gridex_supply_rescission.artifacts%rowtype;r gridex_supply_rescission.reviews%rowtype;current_scope jsonb;BEGIN
 PERFORM gridex_supply_rescission.lock_v1();SELECT * INTO m FROM gridex_supply_rescission.mandates WHERE id=mandate AND company_id=c;SELECT * INTO a FROM gridex_supply_rescission.artifacts WHERE id=m.artifact_id AND company_id=c;SELECT * INTO r FROM gridex_supply_rescission.reviews WHERE id=m.review_id AND artifact_id=a.id AND company_id=c;
 IF m.id IS NULL OR a.id IS NULL OR r.id IS NULL OR r.decision IS DISTINCT FROM 'approved' OR r.reviewer_user_id=a.submitted_by OR gridex_supply_rescission.actor_v1(c,a.submitted_by,'archive') IS NOT TRUE OR gridex_supply_rescission.actor_v1(c,r.reviewer_user_id,'review') IS NOT TRUE OR gridex_supply_rescission.receipt_current_v1(a) IS NOT TRUE OR m.source_hash IS DISTINCT FROM a.source_hash OR m.scope IS DISTINCT FROM a.scope THEN RETURN false;END IF;
 IF NOT EXISTS(SELECT FROM public.tenant_ediel_profiles WHERE company_id=c AND environment=m.environment AND market='electricity' AND is_enabled AND valid_from<=now() AND(valid_to IS NULL OR now()<valid_to)) OR NOT EXISTS(SELECT FROM public.tenant_actor_roles WHERE company_id=c AND environment=m.environment AND actor_id::text=m.scope->>'legalActorId' AND role_code='electricity_supplier' AND valid_from<=now() AND(valid_to IS NULL OR now()<valid_to)) OR (SELECT count(DISTINCT(company_id,actor_id)) FROM public.tenant_actor_identifiers WHERE environment=m.environment AND identifier_type='EdielId' AND identifier_value=m.scope->>'legalSenderId' AND valid_from<=now() AND(valid_to IS NULL OR now()<valid_to))<>1 OR NOT EXISTS(SELECT FROM public.tenant_actor_identifiers WHERE company_id=c AND environment=m.environment AND actor_id::text=m.scope->>'legalActorId' AND identifier_type='EdielId' AND identifier_value=m.scope->>'legalSenderId' AND valid_from<=now() AND(valid_to IS NULL OR now()<valid_to)) OR (SELECT count(DISTINCT actor_id) FROM public.platform_actor_identifiers WHERE identifier_value=m.scope->>'legalReceiverId' AND lower(identifier_type) IN('edielid','ediel_id') AND is_verified AND(valid_from IS NULL OR valid_from<=current_date) AND(valid_to IS NULL OR current_date<=valid_to))<>1 OR NOT EXISTS(SELECT FROM public.platform_actor_identifiers WHERE actor_id::text=m.scope->>'dsoActorId' AND identifier_value=m.scope->>'legalReceiverId' AND lower(identifier_type) IN('edielid','ediel_id') AND is_verified AND(valid_from IS NULL OR valid_from<=current_date) AND(valid_to IS NULL OR current_date<=valid_to)) OR NOT EXISTS(SELECT FROM public.customer_contracts contract WHERE contract.id::text=m.scope->>'contractId' AND contract.company_id=c AND contract.customer_id::text=m.scope->>'customerId' AND contract.metering_point_id::text=m.scope->>'pointId' AND gridex_received_sources.production_contract_hash_v1(contract)=m.scope->>'contractHash') THEN RETURN false;END IF;
 IF fresh THEN current_scope:=gridex_supply_rescission.scope_v1(c,a.selector);IF current_scope IS DISTINCT FROM m.scope OR gridex_supply_rescission.calendar_cutoff_v1((m.scope->>'effectiveAt')::timestamptz,clock_timestamp()) IS NOT TRUE THEN RETURN false;END IF;END IF;
 RETURN true;
END$$;
CREATE FUNCTION public.ediel_review_supply_rescission_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_review jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$
DECLARE a gridex_supply_rescission.artifacts%rowtype;m gridex_supply_rescission.mandates%rowtype;rid uuid;missing jsonb:='[]';scope jsonb;BEGIN
 IF gridex_supply_rescission.actor_v1(p_company_id,p_actor_user_id,'review') IS NOT TRUE THEN RAISE EXCEPTION 'supply_rescission_reviewer_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO a FROM gridex_supply_rescission.artifacts WHERE id=p_artifact_id AND company_id=p_company_id;
 IF a.id IS NULL OR a.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'supply_rescission_independent_reviewer_required';END IF;
 IF jsonb_typeof(p_review) IS DISTINCT FROM 'object' OR p_review-ARRAY['sourceHash','scopeHash','decision','reason','sourceClauseLocator','sourceClauseQuote']<>'{}'::jsonb OR p_review->>'sourceHash' IS DISTINCT FROM a.source_hash OR p_review->>'scopeHash' IS DISTINCT FROM a.scope_hash OR p_review->>'decision' NOT IN('approve','hold','reject') OR nullif(btrim(p_review->>'reason'),'') IS NULL OR length(p_review->>'reason')>2000 THEN RAISE EXCEPTION 'supply_rescission_review_binding_required';END IF;
 SELECT * INTO m FROM gridex_supply_rescission.mandates WHERE artifact_id=a.id AND company_id=p_company_id;
 IF m.id IS NOT NULL THEN RETURN jsonb_build_object('status',CASE WHEN gridex_supply_rescission.mandate_current_v1(p_company_id,m.id) THEN 'authorized' ELSE 'held' END,'companyId',p_company_id,'artifactId',a.id,'mandateId',m.id,'missing',CASE WHEN gridex_supply_rescission.mandate_current_v1(p_company_id,m.id) THEN '[]'::jsonb ELSE '["current_legal_source_or_scope_held"]'::jsonb END);END IF;
 scope:=gridex_supply_rescission.scope_v1(p_company_id,a.selector);
 IF p_review->>'decision' IN('hold','reject') THEN missing:=jsonb_build_array('explicit_independent_legal_source_review_'||(p_review->>'decision'));
 ELSIF scope IS DISTINCT FROM a.scope THEN missing:='["actual_current_own_supply_contract_and_national_source_grammar"]';
 ELSIF gridex_supply_rescission.receipt_current_v1(a) IS NOT TRUE THEN missing:='["authentic_current_legal_rescission_issuer_and_prerequisites"]';
 ELSIF gridex_supply_rescission.calendar_cutoff_v1((scope->>'effectiveAt')::timestamptz,clock_timestamp()) IS NOT TRUE THEN missing:='["national_z08h_effective_calendar_day_cutoff_passed"]';
 ELSIF nullif(btrim(p_review->>'sourceClauseLocator'),'') IS NULL OR length(p_review->>'sourceClauseLocator')>2000 OR nullif(btrim(p_review->>'sourceClauseQuote'),'') IS NULL OR length(p_review->>'sourceClauseQuote')>2000 OR position(convert_to(p_review->>'sourceClauseQuote','UTF8') IN a.source_bytes)=0 THEN missing:='["actual_original_legal_source_clause_required"]';END IF;
 INSERT INTO gridex_supply_rescission.reviews(company_id,artifact_id,reviewer_user_id,decision,reason,source_clause_locator,source_clause_quote,missing) VALUES(p_company_id,a.id,p_actor_user_id,CASE WHEN missing='[]'::jsonb THEN 'approved' WHEN p_review->>'decision'='reject' THEN 'rejected' ELSE 'held' END,p_review->>'reason',p_review->>'sourceClauseLocator',p_review->>'sourceClauseQuote',missing) RETURNING id INTO rid;
 IF missing<>'[]'::jsonb THEN RETURN jsonb_build_object('status',CASE WHEN p_review->>'decision'='reject' THEN 'rejected' ELSE 'held' END,'companyId',p_company_id,'artifactId',a.id,'missing',missing);END IF;
 INSERT INTO gridex_supply_rescission.mandates(company_id,environment,artifact_id,review_id,scope,source_hash) VALUES(p_company_id,a.environment,a.id,rid,a.scope,a.source_hash) RETURNING * INTO m;
 IF gridex_supply_rescission.mandate_current_v1(p_company_id,m.id) IS NOT TRUE THEN RAISE EXCEPTION 'supply_rescission_postcommit_current_mandate_required';END IF;
 INSERT INTO public.audit_logs(company_id,actor_user_id,action,entity_type,entity_id,details) VALUES(p_company_id,p_actor_user_id,'ediel.supply_rescission.mandate_created','supply_rescission',m.id,jsonb_build_object('artifactId',a.id,'sourceHash',a.source_hash,'scopeHash',a.scope_hash,'reviewId',rid));
 RETURN jsonb_build_object('status','authorized','companyId',p_company_id,'artifactId',a.id,'mandateId',m.id,'missing','[]'::jsonb);
END$$;
CREATE FUNCTION public.ediel_read_supply_rescission_artifact_v1(p_company_id uuid,p_actor_user_id uuid,p_artifact_id uuid,p_include_bytes boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE a gridex_supply_rescission.artifacts%rowtype;m gridex_supply_rescission.mandates%rowtype;r gridex_supply_rescission.reviews%rowtype;current boolean;out jsonb;BEGIN
 IF gridex_supply_rescission.actor_v1(p_company_id,p_actor_user_id,'read') IS NOT TRUE THEN RAISE EXCEPTION 'supply_rescission_actor_forbidden' USING ERRCODE='42501';END IF;
 SELECT * INTO a FROM gridex_supply_rescission.artifacts WHERE id=p_artifact_id AND company_id=p_company_id;IF a.id IS NULL THEN RAISE EXCEPTION 'supply_rescission_artifact_unavailable';END IF;
 SELECT * INTO m FROM gridex_supply_rescission.mandates WHERE artifact_id=a.id AND company_id=p_company_id;
 SELECT * INTO r FROM gridex_supply_rescission.reviews WHERE artifact_id=a.id AND company_id=p_company_id ORDER BY reviewed_at DESC,id DESC LIMIT 1;
 current:=m.id IS NOT NULL AND gridex_supply_rescission.mandate_current_v1(p_company_id,m.id);
 out:=jsonb_build_object('status',CASE WHEN current THEN 'authorized' WHEN m.id IS NOT NULL THEN 'held' WHEN r.decision='rejected' THEN 'rejected' WHEN r.id IS NOT NULL THEN 'held' ELSE 'archived' END,'companyId',p_company_id,'artifactId',a.id,'mandateId',m.id,'sourceHash',a.source_hash,'scopeHash',a.scope_hash,'scope',a.scope,'sourceReference',a.source_reference,'sourceVersion',a.source_version,'mimeType',a.mime_type,'byteLength',octet_length(a.source_bytes),'missing',CASE WHEN current THEN '[]'::jsonb WHEN m.id IS NOT NULL THEN '["current_legal_source_or_scope_held"]'::jsonb ELSE coalesce(r.missing,'["authentic_legal_rescission_issuer_and_separate_qualified_review"]'::jsonb) END);
 IF p_include_bytes THEN IF a.source_bytes IS NULL OR encode(sha256(a.source_bytes),'hex') IS DISTINCT FROM a.source_hash THEN RAISE EXCEPTION 'supply_rescission_original_bytes_unavailable';END IF;out:=out||jsonb_build_object('bytesBase64',encode(a.source_bytes,'base64'));END IF;RETURN out;
END$$;
CREATE FUNCTION public.ediel_read_supply_rescission_mandate_v1(p_company_id uuid,p_actor_user_id uuid,p_mandate_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE m gridex_supply_rescission.mandates%rowtype;BEGIN
 IF gridex_supply_rescission.actor_v1(p_company_id,p_actor_user_id,'archive') IS NOT TRUE THEN RAISE EXCEPTION 'supply_rescission_actor_forbidden' USING ERRCODE='42501';END IF;
 IF gridex_supply_rescission.mandate_current_v1(p_company_id,p_mandate_id) IS NOT TRUE THEN RETURN NULL;END IF;
 SELECT * INTO m FROM gridex_supply_rescission.mandates WHERE id=p_mandate_id AND company_id=p_company_id;
 RETURN m.scope||jsonb_build_object('status','authorized','version',1,'owner','immutable-national-supply-rescission-mandate-v1','mandateId',m.id,'actorUserId',p_actor_user_id,'sourceHash',m.source_hash,'lineItemReference','H'||replace(m.id::text,'-',''),'documentReference','H'||replace(m.id::text,'-',''));
END$$;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA gridex_supply_rescission FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.ediel_supply_rescission_scope_v1(uuid,uuid,jsonb),public.ediel_archive_supply_rescission_v1(uuid,uuid,jsonb),public.ediel_review_supply_rescission_v1(uuid,uuid,uuid,jsonb),public.ediel_read_supply_rescission_mandate_v1(uuid,uuid,uuid),public.ediel_read_supply_rescission_artifact_v1(uuid,uuid,uuid,boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_supply_rescission_scope_v1(uuid,uuid,jsonb),public.ediel_archive_supply_rescission_v1(uuid,uuid,jsonb),public.ediel_review_supply_rescission_v1(uuid,uuid,uuid,jsonb),public.ediel_read_supply_rescission_mandate_v1(uuid,uuid,uuid),public.ediel_read_supply_rescission_artifact_v1(uuid,uuid,uuid,boolean) TO service_role;
COMMIT;
