-- Generated by pinned Supabase CLI 2.101.0 on 2026-10-10.
-- Source-bound optional PRODAT arrival date; preserve all other negative ACK guards.
-- External proposed forward only; ROOT owns fresh CLI migration construction.
-- Existing published migrations and authentic capture outputs remain immutable.
BEGIN;
DO $h_required_scope_forward$
DECLARE target_oid oid;before_definition text;after_definition text;old_body text;new_body text;before_metadata jsonb;
BEGIN
 target_oid:='gridex_ediel_header_negative_birth.assert_ack_v1(public.ediel_messages,jsonb)'::regprocedure;
 SELECT prosrc,to_jsonb(p)-'prosrc' INTO old_body,before_metadata FROM pg_proc p WHERE p.oid=target_oid;
 IF encode(sha256(convert_to(old_body,'UTF8')),'hex') IS DISTINCT FROM 'de028c4468dab67f1481c8d3509771cf6dd4a01da38201bd81d57007cef872ed' THEN
  RAISE EXCEPTION 'h_required_scope_unknown_preimage:assert_ack_v1';
 END IF;
 new_body:=$h_required_scope_body$
DECLARE source public.ediel_messages%rowtype;retained jsonb;field text:=e#>>'{negativeField,fieldCode}';t jsonb:=gridex_utilts_binding.wire_tokens_v1(m.raw_payload);a jsonb:=gridex_ack_authority.wire_v1(m.raw_payload);s jsonb;u jsonb;h jsonb;b jsonb;g jsonb;f jsonb;reply text;
BEGIN
 SELECT * INTO source FROM public.ediel_messages WHERE id=m.related_message_id FOR SHARE;retained:=gridex_ediel_header_negative_birth.evidence_v1(source);
 IF retained IS NULL OR (e-'syntaxAssessmentId') IS DISTINCT FROM retained OR field NOT IN('202','311','223') OR retained->'negativeField' IS DISTINCT FROM e->'negativeField' OR retained->'ownOccurrence' IS DISTINCT FROM e->'ownOccurrence'
  OR m.company_id IS DISTINCT FROM source.company_id OR m.environment IS DISTINCT FROM source.environment OR m.direction IS DISTINCT FROM 'outbound' OR m.message_family IS DISTINCT FROM 'APERAK' OR m.message_code IS DISTINCT FROM 'APERAK'
  OR m.canonical_rule_pack_id IS NOT NULL OR m.rule_profile_version_id IS NOT NULL OR m.rule_profile_key IS NOT NULL OR m.rule_profile_version IS NOT NULL OR m.rule_pack_checksum IS NOT NULL OR coalesce(m.rule_pack_snapshot,'{}')<>'{}'::jsonb
  OR a IS NULL OR a->>'family' IS DISTINCT FROM 'APERAK' OR a->>'function' IS DISTINCT FROM (CASE field WHEN '223' THEN '34' ELSE '27' END)
  OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='ERC')<>1 OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='FTX')<>1 THEN RAISE EXCEPTION 'assigned_prodat_negative_ack_scope_required';END IF;
 reply:=gridex_ediel_header_negative_birth.reply_application_v1(source,e);s:=gridex_ediel_header_negative_birth.source_wire_v1(source);u:=gridex_ediel_technical_ack.envelope(source.raw_payload);
 SELECT x->'elements' INTO h FROM jsonb_array_elements(t)x WHERE x->>'tag'='UNH';SELECT x->'elements' INTO b FROM jsonb_array_elements(t)x WHERE x->>'tag'='UNB';SELECT x->'elements' INTO g FROM jsonb_array_elements(t)x WHERE x->>'tag'='ERC';SELECT x->'elements' INTO f FROM jsonb_array_elements(t)x WHERE x->>'tag'='FTX';
 IF h->2 IS DISTINCT FROM e#>'{familyEdition,sourceProjection,catalog,ackConstraints,technicalProfile}' OR b->2 IS DISTINCT FROM u->'receiver' OR b->3 IS DISTINCT FROM u->'sender' OR nullif(b#>>'{7,0}','') IS DISTINCT FROM reply OR coalesce(b#>>'{11,0}','') IS DISTINCT FROM u->>'testIndicator'
  OR g->1 IS DISTINCT FROM jsonb_build_array(e#>>'{negativeField,ercCode}','','260') OR f->1 IS DISTINCT FROM '["AAO"]'::jsonb OR f->3 IS DISTINCT FROM jsonb_build_array(field,'','260') OR f->4 IS DISTINCT FROM jsonb_build_array(e#>>'{negativeField,text}')
  OR jsonb_array_length(f)>5 OR coalesce(f->2,'[]') NOT IN('[]'::jsonb,'[""]'::jsonb) OR length(f#>>'{4,0}')>(e#>>'{familyEdition,sourceProjection,catalog,ackConstraints,textMax}')::int
  OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='BGM')<>1
  -- P A205 remains unique below. P A901 is optional actual PRODAT arrival,
  -- never a second arbitrary date, UNB creation clock or sibling source clock.
  OR EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='DTM' AND (
   (x#>>'{elements,1,0}' IS DISTINCT FROM e#>>'{familyEdition,sourceProjection,catalog,commonAckConstraints,documentDate,qualifier}' AND x#>>'{elements,1,0}' IS DISTINCT FROM '178')
   OR jsonb_array_length(x->'elements') IS DISTINCT FROM 2 OR jsonb_array_length(x#>'{elements,1}') IS DISTINCT FROM 3
   OR x#>>'{elements,1,2}' IS DISTINCT FROM '203' OR gridex_ediel_ack_guide.date_time_v1(x#>>'{elements,1,1}') IS NOT TRUE))
  OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='DTM' AND x#>>'{elements,1,0}'='178')>1
  OR EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='DTM' AND x#>>'{elements,1,0}'=e#>>'{familyEdition,sourceProjection,catalog,commonAckConstraints,documentDate,qualifier}'
   AND (x->>'index')::int IS DISTINCT FROM (SELECT(z->>'index')::int+1 FROM jsonb_array_elements(t)z WHERE z->>'tag'='BGM'))
  OR EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='DTM' AND x#>>'{elements,1,0}'='178' AND (
   source.message_received_at IS NULL OR NOT isfinite(source.message_received_at)
   OR (e->>'sourceReceivedAt')::timestamptz IS DISTINCT FROM source.message_received_at
   OR x#>>'{elements,1,1}' IS DISTINCT FROM to_char((source.message_received_at AT TIME ZONE 'UTC')+interval '1 hour','YYYYMMDDHH24MI')
   OR (x->>'index')::int IS DISTINCT FROM (SELECT(z->>'index')::int+1 FROM jsonb_array_elements(t)z WHERE z->>'tag'='DTM' AND z#>>'{elements,1,0}'=e#>>'{familyEdition,sourceProjection,catalog,commonAckConstraints,documentDate,qualifier}')))
  OR EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag' NOT IN('UNB','UNH','BGM','DTM','NAD','ERC','FTX','RFF','UNT','UNZ'))
  OR (SELECT(x->>'index')::int FROM jsonb_array_elements(t)x WHERE x->>'tag'='FTX') IS DISTINCT FROM (SELECT(x->>'index')::int+1 FROM jsonb_array_elements(t)x WHERE x->>'tag'='ERC')
  OR nullif(h#>>'{1,0}','') IS NULL OR length(h#>>'{1,0}')>14
  OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='DTM' AND x#>>'{elements,1,0}'=e#>>'{familyEdition,sourceProjection,catalog,commonAckConstraints,documentDate,qualifier}' AND x#>>'{elements,1,2}'=e#>>'{familyEdition,sourceProjection,catalog,commonAckConstraints,documentDate,format}' AND gridex_ediel_ack_guide.date_time_v1(x#>>'{elements,1,1}') IS TRUE)<>1
  THEN RAISE EXCEPTION 'assigned_prodat_negative_ack_scope_required';END IF;
 IF EXISTS(SELECT FROM unnest(ARRAY['FR','DO'])role WHERE(SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='NAD' AND x#>>'{elements,1,0}'=role)<>1)
  OR EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='NAD' AND x#>>'{elements,1,0}' IN('FR','DO') AND(x->>'index')::int>=(SELECT(z->>'index')::int FROM jsonb_array_elements(t)z WHERE z->>'tag'='ERC'))
  OR NOT EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='NAD' AND x#>>'{elements,1,0}'='FR' AND x#>'{elements,2}'=e#>'{identities,legalReceiver,identityComponents}' AND x#>>'{elements,9,0}'=e#>>'{identities,legalReceiver,country}')
  OR NOT EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='NAD' AND x#>>'{elements,1,0}'='DO' AND x#>'{elements,2}'=e#>'{identities,legalSender,identityComponents}' AND x#>>'{elements,9,0}'=e#>>'{identities,legalSender,country}') THEN RAISE EXCEPTION 'assigned_prodat_negative_ack_scope_required';END IF;
 -- APP correction applies only to this actual frozen311 negative, in a local
 -- wire observation. Retained source raw/APP and the global predicate stay intact.
 IF field='311' THEN s:=jsonb_set(s,'{app}',to_jsonb(reply));END IF;
 IF NOT coalesce(gridex_ack_authority.source_match_v1(a,s),false) THEN RAISE EXCEPTION 'assigned_prodat_negative_ack_scope_required';END IF;
 IF field='223' THEN
  IF EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='RFF' AND x#>>'{elements,1,0}' IN('LI','Z07') AND(x->>'index')::int<(SELECT(z->>'index')::int FROM jsonb_array_elements(t)z WHERE z->>'tag'='FTX'))
   OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='RFF' AND x#>>'{elements,1,0}'='LI')<>1
   OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='RFF' AND x#>>'{elements,1,0}'='Z07')<>1
   OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='RFF' AND x#>>'{elements,1,0}'='LI' AND x#>>'{elements,1,1}'=e#>>'{ownOccurrence,lineItemReference}')<>1
   OR (SELECT count(*) FROM jsonb_array_elements(t)x WHERE x->>'tag'='RFF' AND x#>>'{elements,1,0}'='Z07' AND x#>>'{elements,1,1}'=e#>>'{ownOccurrence,objectId}')<>1
   OR EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='RFF' AND x#>>'{elements,1,0}' NOT IN('ACW','LI','Z07')) THEN RAISE EXCEPTION 'assigned_prodat_negative_223_own_object_required';END IF;
 ELSE
  IF EXISTS(SELECT FROM jsonb_array_elements(t)x WHERE x->>'tag'='RFF' AND x#>>'{elements,1,0}' NOT IN('ACW')) THEN RAISE EXCEPTION 'assigned_prodat_negative_ack_scope_required';END IF;
 END IF;
END $h_required_scope_body$;
 before_definition:=pg_get_functiondef(target_oid);
 IF (length(before_definition)-length(replace(before_definition,old_body,'')))/length(old_body)<>1 THEN
  RAISE EXCEPTION 'h_required_scope_unique_body_required:assert_ack_v1';
 END IF;
 after_definition:=replace(before_definition,old_body,new_body);
 IF replace(after_definition,new_body,old_body) IS DISTINCT FROM before_definition THEN
  RAISE EXCEPTION 'h_required_scope_full_definition_inverse_required:assert_ack_v1';
 END IF;
 EXECUTE after_definition;
 IF (SELECT encode(sha256(convert_to(prosrc,'UTF8')),'hex') FROM pg_proc WHERE oid=target_oid) IS DISTINCT FROM '2dd44334566e9e0d4fae7ee4afd227906f2a53c00ae053fc136d3d2c2ea51435'
  OR (SELECT to_jsonb(p)-'prosrc' FROM pg_proc p WHERE p.oid=target_oid) IS DISTINCT FROM before_metadata THEN
  RAISE EXCEPTION 'h_required_scope_postimage_or_metadata_changed:assert_ack_v1';
 END IF;
END
$h_required_scope_forward$;
COMMIT;
