-- Created with Supabase CLI2.118.0. Exact source-defined Z13 agreement and method
-- are authenticated with the existing native receipt; no historical filling.
BEGIN;
CREATE OR REPLACE FUNCTION gridex_ediel_services.evidence_terms_v1(e public.ediel_service_evidence) RETURNS jsonb LANGUAGE sql IMMUTABLE SET search_path=pg_catalog SET timezone='UTC' AS $$
 SELECT jsonb_build_object('valid_from',e.valid_from,'valid_to',e.valid_to,'permission_agreement_reference',e.permission_agreement_reference,'permission_requested_method',e.permission_requested_method,'permission_purpose_code',e.permission_purpose_code,'permission_reporting_frequency',e.permission_reporting_frequency,'permission_request_grid_area',e.permission_request_grid_area,'permission_reporting_term_kind',e.permission_reporting_term_kind,'permission_customer_classification',e.permission_customer_classification,'permission_termination_reason',e.permission_termination_reason,'permission_termination_at',e.permission_termination_at)
$$;
CREATE OR REPLACE FUNCTION public.ediel_archive_service_evidence_v1(p_company_id uuid,p_actor_user_id uuid,p_submission jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$
DECLARE a public.ediel_service_assignments%rowtype;bytes bytea;archive gridex_ediel_services.artifacts%rowtype;terms_record public.ediel_service_evidence%rowtype;terms jsonb;v_scope jsonb;sh text;v_source_hash text;kind text;missing jsonb:='["separate_qualified_reviewer_required"]';
BEGIN
 IF gridex_ediel_services.actor_current_v1(p_company_id,p_actor_user_id,false) IS NOT TRUE THEN RAISE EXCEPTION 'ediel_service_archive_actor_forbidden' USING ERRCODE='42501';END IF;
 IF jsonb_typeof(p_submission) IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission) x WHERE x NOT IN('assignmentId','scopeBasisVersion','kind','source','terms','issuerReceipt','transportRelationId','transportActorId'))
 OR jsonb_typeof(p_submission->'source') IS DISTINCT FROM 'object' OR EXISTS(SELECT FROM jsonb_object_keys(p_submission->'source') x WHERE x NOT IN('bytesBase64','mimeType','reference','version')) THEN RAISE EXCEPTION 'ediel_service_archive_shape_invalid';END IF;
 IF jsonb_typeof(p_submission->'terms') IS DISTINCT FROM 'object' OR NOT(p_submission->'terms' ? 'valid_from' AND p_submission->'terms' ? 'valid_to') OR EXISTS(SELECT FROM jsonb_object_keys(p_submission->'terms') x WHERE x NOT IN('valid_from','valid_to','permission_agreement_reference','permission_requested_method','permission_purpose_code','permission_reporting_frequency','permission_request_grid_area','permission_reporting_term_kind','permission_customer_classification','permission_termination_reason','permission_termination_at')) THEN RAISE EXCEPTION 'ediel_service_archive_evidence_terms_required';END IF;
 terms_record:=jsonb_populate_record(NULL::public.ediel_service_evidence,p_submission->'terms');terms:=gridex_ediel_services.evidence_terms_v1(terms_record);
 IF (terms_record.permission_agreement_reference IS NOT NULL AND (terms_record.permission_agreement_reference<>btrim(terms_record.permission_agreement_reference) OR length(terms_record.permission_agreement_reference) NOT BETWEEN 1 AND 35)) OR (terms_record.permission_requested_method IS NOT NULL AND gridex_metering_method_changes.requested_method_supported_v1(terms_record.permission_requested_method) IS NOT TRUE) THEN RAISE EXCEPTION 'ediel_service_archive_source_permission_terms_invalid';END IF;
 IF terms_record.valid_from IS NULL OR NOT isfinite(terms_record.valid_from) OR (terms_record.valid_to IS NOT NULL AND (NOT isfinite(terms_record.valid_to) OR terms_record.valid_to<=terms_record.valid_from)) THEN RAISE EXCEPTION 'ediel_service_archive_evidence_terms_invalid';END IF;
 SELECT * INTO a FROM public.ediel_service_assignments WHERE company_id=p_company_id AND id=(p_submission->>'assignmentId')::uuid;
 IF a.id IS NULL OR a.scope_basis_version IS DISTINCT FROM (p_submission->>'scopeBasisVersion')::bigint OR a.scope_basis_version IS NULL THEN RAISE EXCEPTION 'ediel_service_archive_current_scope_required';END IF;
 v_scope:=gridex_service_administration.scope_v1(a);sh:=encode(sha256(convert_to(v_scope::text,'UTF8')),'hex');
 IF NOT EXISTS(SELECT FROM gridex_service_administration.scope_versions s WHERE s.company_id=a.company_id AND s.assignment_id=a.id AND s.scope_basis_version=a.scope_basis_version AND s.scope=v_scope) THEN RAISE EXCEPTION 'ediel_service_archive_authentic_scope_required';END IF;
 bytes:=decode(p_submission#>>'{source,bytesBase64}','base64');kind:=p_submission->>'kind';v_source_hash:=encode(sha256(bytes),'hex');
 IF octet_length(bytes) NOT BETWEEN 1 AND 8388608 OR substring(bytes,1,5)<>decode('255044462d','hex') OR p_submission#>>'{source,mimeType}' IS DISTINCT FROM 'application/pdf'
 OR nullif(p_submission#>>'{source,reference}','') IS NULL OR length(p_submission#>>'{source,reference}')>2000 OR nullif(p_submission#>>'{source,version}','') IS NULL OR length(p_submission#>>'{source,version}')>200 THEN RAISE EXCEPTION 'ediel_service_archive_bytes_invalid';END IF;
 IF kind='transport_mandate' THEN
  IF NOT EXISTS(SELECT FROM public.tenant_counterparty_relations r WHERE r.company_id=a.company_id AND r.id=(p_submission->>'transportRelationId')::uuid AND r.counterparty_actor_id=(p_submission->>'transportActorId')::uuid AND r.environment=a.environment AND r.relation_type='ediel_transport_agent' AND r.is_enabled AND r.valid_from<=now() AND (r.valid_to IS NULL OR now()<r.valid_to)) THEN RAISE EXCEPTION 'ediel_service_archive_transport_relation_required';END IF;
 ELSIF p_submission->>'transportRelationId' IS NOT NULL OR p_submission->>'transportActorId' IS NOT NULL THEN RAISE EXCEPTION 'ediel_service_archive_transport_scope_invalid';END IF;
 SELECT * INTO archive FROM gridex_ediel_services.artifacts x WHERE x.company_id=a.company_id AND x.environment=a.environment AND x.assignment_id=a.id AND x.scope_basis_version=a.scope_basis_version AND x.evidence_kind=kind AND x.source_hash=v_source_hash AND x.source_reference=p_submission#>>'{source,reference}' AND x.source_version=p_submission#>>'{source,version}';
 IF FOUND THEN
  IF archive.evidence_terms IS DISTINCT FROM terms OR archive.issuer_receipt IS DISTINCT FROM p_submission->'issuerReceipt' OR archive.transport_relation_id IS DISTINCT FROM (p_submission->>'transportRelationId')::uuid OR archive.transport_actor_id IS DISTINCT FROM (p_submission->>'transportActorId')::uuid THEN RAISE EXCEPTION 'ediel_service_archive_receipt_conflict';END IF;
 ELSE
  INSERT INTO gridex_ediel_services.artifacts(company_id,environment,assignment_id,scope_basis_version,scope,scope_hash,evidence_kind,transport_relation_id,transport_actor_id,evidence_terms,source_bytes,source_hash,mime_type,source_reference,source_version,issuer_receipt,submitted_by)
  VALUES(a.company_id,a.environment,a.id,a.scope_basis_version,v_scope,sh,kind,(p_submission->>'transportRelationId')::uuid,(p_submission->>'transportActorId')::uuid,terms,bytes,v_source_hash,'application/pdf',p_submission#>>'{source,reference}',p_submission#>>'{source,version}',p_submission->'issuerReceipt',p_actor_user_id) RETURNING * INTO archive;
 END IF;
 IF gridex_ediel_services.receipt_current_v1(archive) IS NOT TRUE THEN missing:=missing||'"authentic_current_issuer_and_representation_receipt"'::jsonb;END IF;
 RETURN jsonb_build_object('status','archived','companyId',archive.company_id,'assignmentId',archive.assignment_id,'artifactId',archive.id,'sourceHash',archive.source_hash,'scopeHash',archive.scope_hash,'scopeBasisVersion',archive.scope_basis_version,'missing',missing);
END $$;
COMMIT;
