-- Actual Storage PDF copies have independent source captures, legal policies,
-- reviews and receipts. No source issuer, permission assignment, guessed legal
-- deadline, metadata-only physical claim or cascading byte deletion is added.
BEGIN;
GRANT CREATE ON SCHEMA public TO gridex_ediel_retention_owner;
CREATE TABLE gridex_ediel_retention.invoice_file_catalog(retention_class text PRIMARY KEY,source_table text UNIQUE NOT NULL,body_column text NOT NULL);
INSERT INTO gridex_ediel_retention.invoice_file_catalog VALUES
 ('customer_invoice_document_pdf_bytes','customer_invoice_documents','file_path'),
 ('invoice_export_document_pdf_bytes','invoice_documents','storage_path'),
 ('customer_invoice_pdf_bytes','customer_invoices','pdf_path');
CREATE TABLE gridex_ediel_retention.invoice_file_sources(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),retention_class text NOT NULL REFERENCES gridex_ediel_retention.invoice_file_catalog(retention_class),target_id uuid NOT NULL,
 target_hash text NOT NULL CHECK(target_hash~'^[a-f0-9]{64}$'),storage_object_id uuid NOT NULL,storage_bucket text NOT NULL,storage_path text NOT NULL,
 source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),byte_length bigint NOT NULL CHECK(byte_length BETWEEN 1 AND 20971520),captured_by uuid NOT NULL REFERENCES auth.users(id),captured_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(retention_class,target_id));
CREATE TABLE gridex_ediel_retention.invoice_file_decisions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES public.companies(id),retention_class text NOT NULL REFERENCES gridex_ediel_retention.invoice_file_catalog(retention_class),target_id uuid NOT NULL,source_id uuid NOT NULL REFERENCES gridex_ediel_retention.invoice_file_sources(id),
 source_hash text NOT NULL CHECK(source_hash~'^[a-f0-9]{64}$'),target_hash text NOT NULL CHECK(target_hash~'^[a-f0-9]{64}$'),scope_hash text NOT NULL CHECK(scope_hash~'^[a-f0-9]{64}$'),
 document_bytes bytea NOT NULL CHECK(octet_length(document_bytes) BETWEEN 1 AND 1048576),document_hash text NOT NULL CHECK(document_hash=encode(sha256(document_bytes),'hex')),issuer_receipt jsonb,submitted_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(source_id,target_hash,scope_hash,document_hash));
CREATE TABLE gridex_ediel_retention.invoice_file_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),decision_id uuid NOT NULL REFERENCES gridex_ediel_retention.invoice_file_decisions(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),outcome text NOT NULL CHECK(outcome IN('approved','held','rejected')),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.invoice_file_revocations(decision_id uuid PRIMARY KEY REFERENCES gridex_ediel_retention.invoice_file_decisions(id),actor_user_id uuid NOT NULL REFERENCES auth.users(id),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.invoice_file_tombstones(source_id uuid PRIMARY KEY REFERENCES gridex_ediel_retention.invoice_file_sources(id),company_id uuid NOT NULL,decision_id uuid NOT NULL REFERENCES gridex_ediel_retention.invoice_file_decisions(id),review_id uuid NOT NULL REFERENCES gridex_ediel_retention.invoice_file_reviews(id),actor_user_id uuid NOT NULL,journal_retain_until timestamptz NOT NULL,journal_purpose_reference text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE gridex_ediel_retention.invoice_file_events(source_id uuid NOT NULL REFERENCES gridex_ediel_retention.invoice_file_sources(id),kind text NOT NULL CHECK(kind IN('storage_delete_authorized','storage_object_absent')),actor_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(source_id,kind));
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['invoice_file_catalog','invoice_file_sources','invoice_file_decisions','invoice_file_reviews','invoice_file_revocations','invoice_file_tombstones','invoice_file_events'] LOOP
 EXECUTE format('ALTER TABLE gridex_ediel_retention.%I OWNER TO gridex_ediel_retention_owner',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE gridex_ediel_retention.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON gridex_ediel_retention.%I FROM PUBLIC,anon,authenticated,service_role',t);EXECUTE format('CREATE TRIGGER immutable BEFORE UPDATE OR DELETE ON gridex_ediel_retention.%I FOR EACH ROW EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);EXECUTE format('CREATE TRIGGER no_truncate BEFORE TRUNCATE ON gridex_ediel_retention.%I FOR EACH STATEMENT EXECUTE FUNCTION gridex_received_sources.reject_mutation()',t);
 END LOOP;END$$;
GRANT SELECT,UPDATE ON public.customer_invoices,public.customer_invoice_documents,public.invoice_documents,public.invoice_export_items,public.invoice_export_attempts,public.billing_underlays,public.customers,public.customer_supply_periods,storage.objects,gridex_billing_source.underlay_bindings TO gridex_ediel_retention_owner;
CREATE FUNCTION gridex_ediel_retention.invoice_file_actor_v1(c uuid,actor uuid,op text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN
 IF op='ediel.retention.read' THEN PERFORM gridex_ediel_retention.record_read_actor_v1(c,actor);ELSE PERFORM gridex_ediel_retention.actor_v1(c,actor,op);END IF;
 IF gridex_ediel_retention.permission_v1(c,actor,'ediel.retention.invoice_copy_evidence') IS NOT TRUE THEN RAISE EXCEPTION 'invoice_file_current_exact_class_required' USING ERRCODE='42501';END IF;END$$;
CREATE FUNCTION gridex_ediel_retention.invoice_file_locator_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE spec record;r jsonb;invoice jsonb;item jsonb;object jsonb;bucket text;path text;customer uuid;BEGIN
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.invoice_file_catalog WHERE retention_class=k;
 EXECUTE format('SELECT to_jsonb(x) FROM public.%I x WHERE id=$1 AND company_id=$2 FOR SHARE',spec.source_table) INTO r USING target,c;
 IF r IS NULL THEN RAISE EXCEPTION 'invoice_file_actual_scoped_target_required';END IF;
 path:=nullif(r->>spec.body_column,'');bucket:=nullif(r->>'storage_bucket','');
 IF bucket IS NULL THEN bucket:=nullif(r#>>'{metadata,bucket}','');END IF;
 IF split_part(path,'/',1) IN('customer-documents','customer-contract-documents','contract-pdfs','billing-exports') THEN
  IF bucket IS NOT NULL AND bucket<>split_part(path,'/',1) THEN RAISE EXCEPTION 'invoice_file_bucket_path_conflict';END IF;
  bucket:=split_part(path,'/',1);path:=substring(path FROM length(bucket)+2);
 END IF;
 IF bucket IS NULL OR bucket NOT IN('customer-documents','customer-contract-documents','contract-pdfs','billing-exports') OR path IS NULL OR length(path)>1024 OR path~'(^|/)\.\.?(/|$)' OR path~'(^/|//|^[A-Za-z]+:)' OR path NOT LIKE 'companies/'||c::text||'/%' THEN RAISE EXCEPTION 'invoice_file_owned_storage_locator_required';END IF;
 IF spec.source_table='customer_invoices' THEN invoice:=r;
 ELSIF spec.source_table='customer_invoice_documents' THEN SELECT to_jsonb(x) INTO invoice FROM public.customer_invoices x WHERE id=(r->>'invoice_id')::uuid AND company_id=c FOR SHARE;
 ELSE SELECT to_jsonb(x) INTO item FROM public.invoice_export_items x WHERE id=(r->>'invoice_export_item_id')::uuid AND company_id=c FOR SHARE;END IF;
 customer:=coalesce(invoice->>'customer_id',item->>'customer_id')::uuid;
 IF customer IS NULL OR NOT EXISTS(SELECT FROM public.customers WHERE id=customer AND company_id=c) OR r->>'customer_id' IS NOT NULL AND r->>'customer_id'<>customer::text THEN RAISE EXCEPTION 'invoice_file_actual_parent_customer_required';END IF;
 IF bucket='customer-documents' AND (cardinality(string_to_array(path,'/'))<>7 OR split_part(path,'/',3)<>'customers' OR split_part(path,'/',4)<>customer::text OR split_part(path,'/',5)!~'^[a-f0-9-]{36}$' OR split_part(path,'/',6)<>'grid_invoice_suggested') THEN RAISE EXCEPTION 'invoice_file_customer_document_scope_required';END IF;
 SELECT to_jsonb(x) INTO object FROM storage.objects x WHERE bucket_id=bucket AND name=path FOR SHARE;
 IF object IS NULL OR coalesce(object#>>'{metadata,size}','')!~'^[0-9]{1,9}$' OR (object#>>'{metadata,size}')::bigint NOT BETWEEN 1 AND 20971520 THEN RAISE EXCEPTION 'invoice_file_native_storage_object_required';END IF;
 RETURN jsonb_build_object('retentionClass',k,'targetId',target,'targetHash',encode(sha256(convert_to(jsonb_build_object('target',r,'storageObject',object)::text,'UTF8')),'hex'),'storageBucket',bucket,'storagePath',path,'storageObjectId',object->>'id','storageByteLength',(object#>>'{metadata,size}')::bigint,'customerId',customer,'invoiceId',invoice->>'id','exportItemId',item->>'id');END$$;
CREATE FUNCTION public.ediel_invoice_file_locator_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,'ediel.retention.submit');RETURN gridex_ediel_retention.invoice_file_locator_v1(p_company_id,p_retention_class,p_target_id);END$$;
CREATE FUNCTION public.ediel_register_invoice_file_source_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid,p_target_hash text,p_storage_object_id uuid,p_source_hash text,p_byte_length bigint) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE l jsonb;s gridex_ediel_retention.invoice_file_sources%rowtype;BEGIN
 -- Service-only producer executes after authenticated current scope and actual
 -- server Storage download; it repeats current native actor/class qualification.
 IF gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'ediel.retention.submit') IS NOT TRUE OR gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'ediel.retention.invoice_copy_evidence') IS NOT TRUE THEN RAISE EXCEPTION 'invoice_file_current_capture_actor_required' USING ERRCODE='42501';END IF;
 l:=gridex_ediel_retention.invoice_file_locator_v1(p_company_id,p_retention_class,p_target_id);
 IF l->>'targetHash' IS DISTINCT FROM p_target_hash OR l->>'storageObjectId' IS DISTINCT FROM p_storage_object_id::text OR (l->>'storageByteLength')::bigint IS DISTINCT FROM p_byte_length OR p_source_hash!~'^[a-f0-9]{64}$' OR p_byte_length NOT BETWEEN 1 AND 20971520 THEN RAISE EXCEPTION 'invoice_file_storage_capture_binding_changed';END IF;
 IF EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_sources captured JOIN gridex_ediel_retention.invoice_file_tombstones t ON t.source_id=captured.id WHERE captured.storage_bucket=l->>'storageBucket' AND captured.storage_path=l->>'storagePath') THEN RAISE EXCEPTION 'invoice_file_storage_tombstoned';END IF;
 INSERT INTO gridex_ediel_retention.invoice_file_sources(company_id,retention_class,target_id,target_hash,storage_object_id,storage_bucket,storage_path,source_hash,byte_length,captured_by) VALUES(p_company_id,p_retention_class,p_target_id,p_target_hash,p_storage_object_id,l->>'storageBucket',l->>'storagePath',p_source_hash,p_byte_length,p_actor_user_id) ON CONFLICT DO NOTHING;
 SELECT * INTO STRICT s FROM gridex_ediel_retention.invoice_file_sources WHERE company_id=p_company_id AND retention_class=p_retention_class AND target_id=p_target_id FOR SHARE;
 IF s.target_hash<>p_target_hash OR s.source_hash<>p_source_hash OR s.byte_length<>p_byte_length OR s.storage_object_id<>p_storage_object_id THEN RAISE EXCEPTION 'invoice_file_original_capture_conflict';END IF;
 RETURN jsonb_build_object('sourceId',s.id,'sourceHash',s.source_hash,'byteLength',s.byte_length,'retentionClass',s.retention_class,'targetId',s.target_id,'authority','none');END$$;
CREATE FUNCTION gridex_ediel_retention.invoice_file_basis_v1(c uuid,k text,target uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE s gridex_ediel_retention.invoice_file_sources%rowtype;spec record;r jsonb;invoice jsonb;item jsonb;underlay jsonb;binding jsonb;scope jsonb;customer uuid;start_at timestamptz;end_at timestamptz;closed boolean;BEGIN
 SELECT * INTO STRICT s FROM gridex_ediel_retention.invoice_file_sources WHERE company_id=c AND retention_class=k AND target_id=target FOR SHARE;
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.invoice_file_catalog WHERE retention_class=k;
 LOCK TABLE public.customer_invoices,public.customer_invoice_documents,public.invoice_documents,public.invoice_export_items,public.invoice_export_attempts,public.customers,public.customer_supply_periods IN SHARE MODE;
 EXECUTE format('SELECT to_jsonb(x) FROM public.%I x WHERE id=$1 AND company_id=$2 FOR SHARE',spec.source_table) INTO r USING target,c;
 IF r IS NULL THEN RAISE EXCEPTION 'invoice_file_actual_source_removed';END IF;
 IF spec.source_table='customer_invoices' THEN invoice:=r;
 ELSIF spec.source_table='customer_invoice_documents' THEN SELECT to_jsonb(x) INTO invoice FROM public.customer_invoices x WHERE id=(r->>'invoice_id')::uuid AND company_id=c FOR SHARE;
 ELSE SELECT to_jsonb(x) INTO item FROM public.invoice_export_items x WHERE id=(r->>'invoice_export_item_id')::uuid AND company_id=c FOR SHARE;END IF;
 customer:=coalesce(invoice->>'customer_id',item->>'customer_id')::uuid;
 SELECT to_jsonb(x) INTO underlay FROM public.billing_underlays x WHERE company_id=c AND id=coalesce(invoice->>'billing_underlay_id',item->>'billing_underlay_id')::uuid FOR SHARE;
 SELECT to_jsonb(x) INTO binding FROM gridex_billing_source.underlay_bindings x WHERE company_id=c AND underlay_id=(underlay->>'id')::uuid FOR SHARE;
 IF customer IS NULL OR underlay IS NULL OR binding IS NULL OR underlay->>'customer_id' IS DISTINCT FROM customer::text OR NOT EXISTS(SELECT FROM public.customers WHERE id=customer AND company_id=c) THEN RAISE EXCEPTION 'invoice_file_native_invoice_underlay_scope_required';END IF;
 IF binding->>'source_basis_hash' IS DISTINCT FROM encode(sha256(convert_to((binding->'source_basis')::text,'UTF8')),'hex') AND NOT EXISTS(SELECT FROM gridex_ediel_retention.finance_tombstones WHERE company_id=c AND retention_class='billing_underlay_source_body' AND target_id=underlay->>'id') THEN RAISE EXCEPTION 'invoice_file_actual_billing_source_required';END IF;
 start_at:=(underlay->>'billing_period_start')::timestamptz;end_at:=(underlay->>'billing_period_end')::timestamptz;
 IF isfinite(start_at) IS NOT TRUE OR isfinite(end_at) IS NOT TRUE OR end_at<=start_at THEN RAISE EXCEPTION 'invoice_file_native_closed_period_required';END IF;
 SELECT jsonb_build_object('customer',to_jsonb(x),'supplies',(SELECT coalesce(jsonb_agg(to_jsonb(sp) ORDER BY sp.id),'[]') FROM public.customer_supply_periods sp WHERE sp.company_id=c AND sp.customer_id=customer),'invoices',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',i.id,'status',i.status) ORDER BY i.id),'[]') FROM public.customer_invoices i WHERE i.company_id=c AND i.customer_id=customer),'items',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',i.id,'status',i.status,'attempts',(SELECT coalesce(jsonb_agg(to_jsonb(a) ORDER BY a.id),'[]') FROM public.invoice_export_attempts a WHERE a.company_id=c AND a.invoice_export_item_id=i.id)) ORDER BY i.id),'[]') FROM public.invoice_export_items i WHERE i.company_id=c AND i.customer_id=customer)) INTO scope FROM public.customers x WHERE id=customer AND company_id=c;
 closed:=end_at<=clock_timestamp() AND scope#>>'{customer,status}'='archived'
 AND NOT EXISTS(SELECT FROM public.customer_supply_periods WHERE company_id=c AND customer_id=customer AND (status IS NULL OR status NOT IN('cancelled','rejected','terminated','ended','closed','inactive') OR coalesce(actual_end_date,end_date) IS NULL OR coalesce(actual_end_date,end_date)>=current_date))
 AND NOT EXISTS(SELECT FROM public.customer_invoices WHERE company_id=c AND customer_id=customer AND (status IS NULL OR lower(status) NOT IN('paid','cancelled','void','credited')))
 AND NOT EXISTS(SELECT FROM public.invoice_export_items WHERE company_id=c AND customer_id=customer AND (status IS NULL OR upper(status) NOT IN('SENT','CREDITED','CANCELLED','REJECTED')))
 AND NOT EXISTS(SELECT FROM public.invoice_export_attempts a JOIN public.invoice_export_items i ON i.id=a.invoice_export_item_id WHERE i.company_id=c AND i.customer_id=customer AND (a.company_id IS DISTINCT FROM c OR a.finished_at IS NULL));
 RETURN jsonb_build_object('retentionClass',k,'targetId',target,'sourceId',s.id,'sourceHash',s.source_hash,'targetHash',encode(sha256(convert_to(jsonb_build_object('source',to_jsonb(s),'target',r)::text,'UTF8')),'hex'),'scopeHash',encode(sha256(convert_to(jsonb_build_object('scope',scope,'underlayId',underlay->>'id','sourceBasisHash',binding->>'source_basis_hash','periodStart',start_at,'periodEnd',end_at)::text,'UTF8')),'hex'),'storageBucket',s.storage_bucket,'storagePath',s.storage_path,'byteLength',s.byte_length,'periodStart',start_at,'periodEnd',end_at,'allIncludedScopesClosed',closed,'complete',false,'authority','none');END$$;
CREATE FUNCTION gridex_ediel_retention.invoice_file_receipt_v1(d gridex_ediel_retention.invoice_file_decisions) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE issuer gridex_ediel_retention.issuers%rowtype;s gridex_ediel_retention.invoice_file_sources%rowtype;p jsonb;b bytea;now_at timestamptz;issued timestamptz;expires timestamptz;retain timestamptz;journal timestamptz;BEGIN
 IF d.document_bytes IS NULL OR encode(sha256(d.document_bytes),'hex') IS DISTINCT FROM d.document_hash OR jsonb_typeof(d.issuer_receipt) IS DISTINCT FROM 'object' OR coalesce(d.issuer_receipt->>'signatureHex','')!~'^[a-f0-9]{64}$' OR length(coalesce(d.issuer_receipt->>'payloadBase64','')) NOT BETWEEN 1 AND 32768 THEN RETURN NULL;END IF;
 SELECT * INTO issuer FROM gridex_ediel_retention.issuers WHERE id=(d.issuer_receipt->>'issuerId')::uuid AND company_id=d.company_id FOR SHARE;
 SELECT * INTO s FROM gridex_ediel_retention.invoice_file_sources WHERE id=d.source_id AND company_id=d.company_id FOR SHARE;now_at:=clock_timestamp();
 IF issuer.id IS NULL OR s.id IS NULL OR now_at<issuer.valid_from OR now_at>=issuer.valid_to OR EXISTS(SELECT FROM gridex_ediel_retention.issuer_revocations WHERE issuer_id=issuer.id) OR EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_revocations WHERE decision_id=d.id) THEN RETURN NULL;END IF;
 b:=decode(d.issuer_receipt->>'payloadBase64','base64');IF encode(gridex_requested_changes.receipt_hmac_sha256_v1(b,issuer.signing_key),'hex') IS DISTINCT FROM d.issuer_receipt->>'signatureHex' THEN RETURN NULL;END IF;
 p:=convert_from(b,'UTF8')::jsonb;issued:=(p->>'issuedAt')::timestamptz;expires:=(p->>'expiresAt')::timestamptz;retain:=(p->>'retainUntil')::timestamptz;journal:=(p->>'journalRetainUntil')::timestamptz;
 IF p->>'format' IS DISTINCT FROM 'ediel_invoice_file_retention_policy_v1' OR p->>'companyId' IS DISTINCT FROM d.company_id::text OR p->>'retentionClass' IS DISTINCT FROM d.retention_class OR p->>'targetId' IS DISTINCT FROM d.target_id::text OR p->>'sourceId' IS DISTINCT FROM d.source_id::text OR p->>'sourceHash' IS DISTINCT FROM d.source_hash OR p->>'targetHash' IS DISTINCT FROM d.target_hash OR p->>'scopeHash' IS DISTINCT FROM d.scope_hash OR p->>'documentHash' IS DISTINCT FROM d.document_hash OR p->>'storageBucket' IS DISTINCT FROM s.storage_bucket OR p->>'storagePath' IS DISTINCT FROM s.storage_path OR p->>'byteLength' IS DISTINCT FROM s.byte_length::text OR p->>'operation' IS DISTINCT FROM 'delete_storage_pdf' OR p->>'issuerLegalReference' IS DISTINCT FROM issuer.legal_reference OR p->>'accessRevocationRequired' IS DISTINCT FROM 'true' OR nullif(p->>'legalBasisReference','') IS NULL OR nullif(p->>'journalPurposeReference','') IS NULL OR isfinite(issued) IS NOT TRUE OR isfinite(expires) IS NOT TRUE OR isfinite(retain) IS NOT TRUE OR isfinite(journal) IS NOT TRUE OR issued>now_at OR expires<=now_at OR issued<issuer.valid_from OR expires>issuer.valid_to OR journal<=now_at THEN RETURN NULL;END IF;
 RETURN p;EXCEPTION WHEN invalid_text_representation OR invalid_parameter_value OR datetime_field_overflow OR character_not_in_repertoire THEN RETURN NULL;END$$;
CREATE FUNCTION public.ediel_invoice_file_retention_basis_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,CASE WHEN gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'ediel.retention.read') THEN 'ediel.retention.read' ELSE 'ediel.retention.review' END);RETURN gridex_ediel_retention.invoice_file_basis_v1(p_company_id,p_retention_class,p_target_id);END$$;
CREATE FUNCTION public.ediel_submit_invoice_file_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid,p_document_base64 text,p_issuer_receipt jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE basis jsonb;b bytea;d gridex_ediel_retention.invoice_file_decisions%rowtype;BEGIN
 PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,'ediel.retention.submit');basis:=gridex_ediel_retention.invoice_file_basis_v1(p_company_id,p_retention_class,p_target_id);
 IF length(p_document_base64)>1398104 THEN RAISE EXCEPTION 'invoice_file_policy_limit';END IF;b:=decode(p_document_base64,'base64');IF octet_length(b) NOT BETWEEN 1 AND 1048576 THEN RAISE EXCEPTION 'invoice_file_policy_required';END IF;
 INSERT INTO gridex_ediel_retention.invoice_file_decisions(company_id,retention_class,target_id,source_id,source_hash,target_hash,scope_hash,document_bytes,document_hash,issuer_receipt,submitted_by) VALUES(p_company_id,p_retention_class,p_target_id,(basis->>'sourceId')::uuid,basis->>'sourceHash',basis->>'targetHash',basis->>'scopeHash',b,encode(sha256(b),'hex'),p_issuer_receipt,p_actor_user_id) ON CONFLICT DO NOTHING;
 SELECT * INTO STRICT d FROM gridex_ediel_retention.invoice_file_decisions WHERE source_id=(basis->>'sourceId')::uuid AND target_hash=basis->>'targetHash' AND scope_hash=basis->>'scopeHash' AND document_hash=encode(sha256(b),'hex') FOR SHARE;
 IF d.issuer_receipt IS DISTINCT FROM p_issuer_receipt THEN RAISE EXCEPTION 'invoice_file_original_policy_conflict';END IF;RETURN jsonb_build_object('status','submitted','decisionId',d.id,'sourceId',d.source_id,'documentHash',d.document_hash,'issuerQualified',gridex_ediel_retention.invoice_file_receipt_v1(d) IS NOT NULL);END$$;
CREATE FUNCTION public.ediel_read_invoice_file_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.invoice_file_decisions%rowtype;BEGIN SELECT * INTO STRICT d FROM gridex_ediel_retention.invoice_file_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR SHARE;PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,CASE WHEN gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'ediel.retention.read') THEN 'ediel.retention.read' ELSE 'ediel.retention.review' END);RETURN jsonb_build_object('decisionId',d.id,'sourceId',d.source_id,'retentionClass',d.retention_class,'targetId',d.target_id,'sourceHash',d.source_hash,'documentHash',d.document_hash,'issuerQualified',gridex_ediel_retention.invoice_file_receipt_v1(d) IS NOT NULL,'bytesAvailable',NOT EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_tombstones WHERE source_id=d.source_id),'authority','none');END$$;
CREATE FUNCTION public.ediel_read_invoice_file_source_v1(p_company_id uuid,p_actor_user_id uuid,p_retention_class text,p_target_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE s gridex_ediel_retention.invoice_file_sources%rowtype;BEGIN
 PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,CASE WHEN gridex_ediel_retention.permission_v1(p_company_id,p_actor_user_id,'ediel.retention.read') THEN 'ediel.retention.read' ELSE 'ediel.retention.review' END);
 SELECT * INTO STRICT s FROM gridex_ediel_retention.invoice_file_sources WHERE company_id=p_company_id AND retention_class=p_retention_class AND target_id=p_target_id FOR SHARE;
 RETURN jsonb_build_object('sourceId',s.id,'retentionClass',s.retention_class,'targetId',s.target_id,'sourceHash',s.source_hash,'byteLength',s.byte_length,'capturedAt',s.captured_at,'bytesAvailable',NOT EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_tombstones WHERE source_id=s.id),'authority','none');END$$;
CREATE FUNCTION public.ediel_review_invoice_file_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid,p_outcome text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.invoice_file_decisions%rowtype;basis jsonb;p jsonb;r uuid;outcome text;BEGIN SELECT * INTO STRICT d FROM gridex_ediel_retention.invoice_file_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,'ediel.retention.review');IF p_outcome NOT IN('approve','hold','reject') OR nullif(btrim(p_reason),'') IS NULL OR length(p_reason)>4000 THEN RAISE EXCEPTION 'invoice_file_review_shape_required';END IF;IF p_outcome='approve' AND d.submitted_by=p_actor_user_id THEN RAISE EXCEPTION 'invoice_file_separate_reviewer_required';END IF;
 basis:=gridex_ediel_retention.invoice_file_basis_v1(p_company_id,d.retention_class,d.target_id);p:=gridex_ediel_retention.invoice_file_receipt_v1(d);outcome:=CASE WHEN p_outcome='reject' THEN 'rejected' WHEN p_outcome='approve' AND p IS NOT NULL AND basis->>'allIncludedScopesClosed'='true' AND basis->>'targetHash'=d.target_hash AND basis->>'scopeHash'=d.scope_hash AND p->>'periodStart'=basis->>'periodStart' AND p->>'periodEnd'=basis->>'periodEnd' THEN 'approved' ELSE 'held' END;
 INSERT INTO gridex_ediel_retention.invoice_file_reviews(decision_id,actor_user_id,outcome,reason) VALUES(d.id,p_actor_user_id,outcome,p_reason) RETURNING id INTO r;RETURN jsonb_build_object('status',outcome,'decisionId',d.id,'reviewId',r);END$$;
CREATE FUNCTION public.ediel_revoke_invoice_file_retention_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid,p_reason text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN PERFORM id FROM gridex_ediel_retention.invoice_file_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'invoice_file_scoped_decision_required';END IF;PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,'ediel.retention.review');IF nullif(btrim(p_reason),'') IS NULL OR length(p_reason)>4000 THEN RAISE EXCEPTION 'invoice_file_revoke_reason_required';END IF;INSERT INTO gridex_ediel_retention.invoice_file_revocations(decision_id,actor_user_id,reason) VALUES(p_decision_id,p_actor_user_id,p_reason) ON CONFLICT DO NOTHING;END$$;
CREATE FUNCTION gridex_ediel_retention.invoice_file_revocation_lock_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$BEGIN PERFORM id FROM gridex_ediel_retention.invoice_file_decisions WHERE id=NEW.decision_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'invoice_file_revocation_target_required';END IF;RETURN NEW;END$$;
CREATE TRIGGER invoice_file_revocation_lock BEFORE INSERT ON gridex_ediel_retention.invoice_file_revocations FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.invoice_file_revocation_lock_v1();
CREATE FUNCTION gridex_ediel_retention.invoice_file_current_v1(d gridex_ediel_retention.invoice_file_decisions) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE r gridex_ediel_retention.invoice_file_reviews%rowtype;basis jsonb;p jsonb;BEGIN
 SELECT * INTO r FROM gridex_ediel_retention.invoice_file_reviews WHERE decision_id=d.id ORDER BY created_at DESC,id DESC LIMIT 1;
 IF r.outcome IS DISTINCT FROM 'approved' OR r.actor_user_id=d.submitted_by OR public.ediel_retention_lock_auth_actor_v1(r.actor_user_id) IS NOT TRUE OR gridex_ediel_retention.permission_v1(d.company_id,r.actor_user_id,'ediel.retention.review') IS NOT TRUE OR gridex_ediel_retention.permission_v1(d.company_id,r.actor_user_id,'ediel.retention.invoice_copy_evidence') IS NOT TRUE THEN RETURN NULL;END IF;
 basis:=gridex_ediel_retention.invoice_file_basis_v1(d.company_id,d.retention_class,d.target_id);p:=gridex_ediel_retention.invoice_file_receipt_v1(d);
 IF p IS NULL OR (p->>'retainUntil')::timestamptz>clock_timestamp() OR basis->>'targetHash' IS DISTINCT FROM d.target_hash OR basis->>'scopeHash' IS DISTINCT FROM d.scope_hash OR basis->>'sourceHash' IS DISTINCT FROM d.source_hash OR basis->>'allIncludedScopesClosed' IS DISTINCT FROM 'true' OR p->>'periodStart' IS DISTINCT FROM basis->>'periodStart' OR p->>'periodEnd' IS DISTINCT FROM basis->>'periodEnd' THEN RETURN NULL;END IF;RETURN r.id;END$$;
CREATE FUNCTION gridex_ediel_retention.invoice_file_shared_scope_v1(bucket text,path text) RETURNS SETOF gridex_ediel_retention.invoice_file_sources LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec record;row record;s gridex_ediel_retention.invoice_file_sources%rowtype;l jsonb;BEGIN
 LOCK TABLE public.customer_invoice_documents,public.invoice_documents,public.customer_invoices IN SHARE MODE;
 FOR spec IN SELECT * FROM gridex_ediel_retention.invoice_file_catalog ORDER BY retention_class LOOP
  IF EXISTS(SELECT FROM pg_class WHERE oid=('public.'||spec.source_table)::regclass) THEN
   FOR row IN EXECUTE format('SELECT id FROM public.%I x WHERE coalesce(to_jsonb(x)->>%L,'''') NOT IN($1,$2,$3) AND (position($2 IN coalesce(to_jsonb(x)->>''public_url'',''''))>0 OR position($2 IN coalesce(to_jsonb(x)->>''pdf_url'',''''))>0)',spec.source_table,spec.body_column) USING path,bucket||'/'||path,'storage://'||bucket||'/'||path LOOP RAISE EXCEPTION 'invoice_file_remote_or_ambiguous_shared_copy_held';END LOOP;
  END IF;
  FOR row IN EXECUTE format('SELECT id,company_id FROM public.%I WHERE %I=$1 OR %I=$2 OR %I=$3 ORDER BY id',spec.source_table,spec.body_column,spec.body_column,spec.body_column) USING path,bucket||'/'||path,'storage://'||bucket||'/'||path LOOP
   SELECT * INTO s FROM gridex_ediel_retention.invoice_file_sources WHERE retention_class=spec.retention_class AND target_id=row.id AND company_id=row.company_id FOR SHARE;
   IF s.id IS NULL OR s.storage_bucket<>bucket OR s.storage_path<>path THEN RAISE EXCEPTION 'invoice_file_every_shared_reference_capture_required';END IF;RETURN NEXT s;
  END LOOP;
 END LOOP;END$$;
CREATE FUNCTION public.ediel_begin_invoice_file_purge_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.invoice_file_decisions%rowtype;s gridex_ediel_retention.invoice_file_sources%rowtype;other gridex_ediel_retention.invoice_file_sources%rowtype;q gridex_ediel_retention.invoice_file_decisions%rowtype;r uuid;p jsonb;t record;BEGIN
 PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,'ediel.retention.purge');SELECT * INTO STRICT d FROM gridex_ediel_retention.invoice_file_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;SELECT * INTO STRICT s FROM gridex_ediel_retention.invoice_file_sources WHERE id=d.source_id FOR SHARE;
 -- Completed immutable receipt first: no reactivation of old policy or bytes.
 IF EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_events WHERE source_id=s.id AND kind='storage_object_absent') THEN RETURN jsonb_build_object('status','purged','sourceId',s.id,'sourceHash',s.source_hash,'byteLength',s.byte_length,'bytesAvailable',false,'replay',true);END IF;
 FOR other IN SELECT * FROM gridex_ediel_retention.invoice_file_shared_scope_v1(s.storage_bucket,s.storage_path) ORDER BY id LOOP
  IF other.company_id<>p_company_id OR other.source_hash<>s.source_hash OR other.byte_length<>s.byte_length THEN RAISE EXCEPTION 'invoice_file_shared_foreign_or_changed_bytes';END IF;
  SELECT * INTO q FROM gridex_ediel_retention.invoice_file_decisions WHERE source_id=other.id ORDER BY created_at DESC,id DESC LIMIT 1 FOR UPDATE;
  IF q.id IS NULL THEN RAISE EXCEPTION 'invoice_file_each_copy_legal_decision_required';END IF;r:=gridex_ediel_retention.invoice_file_current_v1(q);p:=gridex_ediel_retention.invoice_file_receipt_v1(q);IF r IS NULL OR p IS NULL THEN RAISE EXCEPTION 'invoice_file_each_copy_current_legal_review_required';END IF;
  INSERT INTO gridex_ediel_retention.invoice_file_tombstones(source_id,company_id,decision_id,review_id,actor_user_id,journal_retain_until,journal_purpose_reference) VALUES(other.id,p_company_id,q.id,r,p_actor_user_id,(p->>'journalRetainUntil')::timestamptz,p->>'journalPurposeReference') ON CONFLICT DO NOTHING;
 END LOOP;
 IF NOT EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_tombstones WHERE source_id=s.id) THEN RAISE EXCEPTION 'invoice_file_actual_reference_scope_required';END IF;
 RETURN jsonb_build_object('status','storage_purge_pending','sourceId',s.id,'sourceHash',s.source_hash,'byteLength',s.byte_length,'storageBucket',s.storage_bucket,'storagePath',s.storage_path,'replay',EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_tombstones WHERE source_id=s.id AND decision_id<>d.id));END$$;
CREATE FUNCTION gridex_ediel_retention.invoice_file_storage_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE s gridex_ediel_retention.invoice_file_sources%rowtype;t gridex_ediel_retention.invoice_file_tombstones%rowtype;d gridex_ediel_retention.invoice_file_decisions%rowtype;actor uuid;bucket text;path text;BEGIN
 bucket:=CASE WHEN TG_OP='INSERT' THEN NEW.bucket_id ELSE OLD.bucket_id END;path:=CASE WHEN TG_OP='INSERT' THEN NEW.name ELSE OLD.name END;
 -- An existing actual PDF reference cannot bypass custody by skipping source
 -- capture; each matching row must be represented before any physical DELETE.
 IF TG_OP='DELETE' AND bucket IN('customer-documents','customer-contract-documents','contract-pdfs','billing-exports') THEN PERFORM 1 FROM gridex_ediel_retention.invoice_file_shared_scope_v1(bucket,path);END IF;
 IF TG_OP='UPDATE' AND (NEW.bucket_id IS DISTINCT FROM OLD.bucket_id OR NEW.name IS DISTINCT FROM OLD.name) AND EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_sources WHERE storage_bucket=NEW.bucket_id AND storage_path=NEW.name) THEN RAISE EXCEPTION 'invoice_file_storage_target_immutable';END IF;
 FOR s IN SELECT * FROM gridex_ediel_retention.invoice_file_sources WHERE storage_bucket=bucket AND storage_path=path ORDER BY id FOR SHARE LOOP
  IF TG_OP<>'DELETE' THEN RAISE EXCEPTION 'invoice_file_storage_original_immutable';END IF;
  actor:=public.ediel_retention_session_actor_v1();PERFORM gridex_ediel_retention.invoice_file_actor_v1(s.company_id,actor,'ediel.retention.purge');
  SELECT * INTO t FROM gridex_ediel_retention.invoice_file_tombstones WHERE source_id=s.id;
  IF t.source_id IS NULL THEN RAISE EXCEPTION 'invoice_file_native_tombstone_required';END IF;
  SELECT * INTO STRICT d FROM gridex_ediel_retention.invoice_file_decisions WHERE id=t.decision_id FOR UPDATE;
  IF gridex_ediel_retention.invoice_file_current_v1(d) IS DISTINCT FROM t.review_id THEN RAISE EXCEPTION 'invoice_file_storage_current_legal_review_required';END IF;
  PERFORM 1 FROM gridex_ediel_retention.invoice_file_shared_scope_v1(bucket,path);
  INSERT INTO gridex_ediel_retention.invoice_file_events(source_id,kind,actor_user_id) VALUES(s.id,'storage_delete_authorized',actor) ON CONFLICT DO NOTHING;
 END LOOP;IF TG_OP='DELETE' THEN RETURN OLD;ELSE RETURN NEW;END IF;END$$;
CREATE TRIGGER invoice_file_retention_storage_guard BEFORE INSERT OR UPDATE OR DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.invoice_file_storage_guard_v1();
CREATE FUNCTION public.ediel_invoice_file_storage_delete_target_v1(p_bucket text,p_path text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE s gridex_ediel_retention.invoice_file_sources%rowtype;actor uuid:=public.ediel_retention_session_actor_v1();n int:=0;BEGIN FOR s IN SELECT * FROM gridex_ediel_retention.invoice_file_sources WHERE storage_bucket=p_bucket AND storage_path=p_path LOOP n:=n+1;IF NOT EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_tombstones WHERE source_id=s.id) OR gridex_ediel_retention.permission_v1(s.company_id,actor,'ediel.retention.purge') IS NOT TRUE OR gridex_ediel_retention.permission_v1(s.company_id,actor,'ediel.retention.invoice_copy_evidence') IS NOT TRUE THEN RETURN false;END IF;END LOOP;RETURN n>0;END$$;
CREATE POLICY invoice_file_qualified_retention_storage_delete ON storage.objects FOR DELETE TO authenticated USING(public.ediel_invoice_file_storage_delete_target_v1(bucket_id,name));
CREATE FUNCTION public.ediel_finish_invoice_file_purge_v1(p_company_id uuid,p_actor_user_id uuid,p_decision_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE d gridex_ediel_retention.invoice_file_decisions%rowtype;s gridex_ediel_retention.invoice_file_sources%rowtype;other gridex_ediel_retention.invoice_file_sources%rowtype;BEGIN
 PERFORM gridex_ediel_retention.invoice_file_actor_v1(p_company_id,p_actor_user_id,'ediel.retention.purge');SELECT * INTO STRICT d FROM gridex_ediel_retention.invoice_file_decisions WHERE id=p_decision_id AND company_id=p_company_id FOR UPDATE;SELECT * INTO STRICT s FROM gridex_ediel_retention.invoice_file_sources WHERE id=d.source_id FOR SHARE;
 IF EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_events WHERE source_id=s.id AND kind='storage_object_absent') THEN RETURN jsonb_build_object('status','purged','sourceId',s.id,'sourceHash',s.source_hash,'byteLength',s.byte_length,'bytesAvailable',false,'replay',true);END IF;
 IF EXISTS(SELECT FROM storage.objects WHERE bucket_id=s.storage_bucket AND name=s.storage_path) THEN RAISE EXCEPTION 'invoice_file_native_storage_object_still_present';END IF;
 FOR other IN SELECT * FROM gridex_ediel_retention.invoice_file_sources WHERE storage_bucket=s.storage_bucket AND storage_path=s.storage_path ORDER BY id FOR SHARE LOOP
  IF other.company_id<>p_company_id OR NOT EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_tombstones WHERE source_id=other.id) OR NOT EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_events WHERE source_id=other.id AND kind='storage_delete_authorized') THEN RAISE EXCEPTION 'invoice_file_authenticated_storage_delete_receipt_required';END IF;
  INSERT INTO gridex_ediel_retention.invoice_file_events(source_id,kind,actor_user_id) VALUES(other.id,'storage_object_absent',p_actor_user_id) ON CONFLICT DO NOTHING;
 END LOOP;RETURN jsonb_build_object('status','purged','sourceId',s.id,'sourceHash',s.source_hash,'byteLength',s.byte_length,'bytesAvailable',false,'replay',false);END$$;
CREATE FUNCTION public.ediel_require_invoice_file_copy_available_v1(p_company_id uuid,p_retention_class text,p_target_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$BEGIN IF EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_sources s JOIN gridex_ediel_retention.invoice_file_tombstones t ON t.source_id=s.id WHERE s.company_id=p_company_id AND s.retention_class=p_retention_class AND s.target_id=p_target_id) THEN RAISE EXCEPTION 'invoice_file_copy_retention_tombstoned' USING ERRCODE='23514';END IF;END$$;
CREATE FUNCTION gridex_ediel_retention.invoice_file_ref_guard_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$DECLARE spec record;r jsonb;s gridex_ediel_retention.invoice_file_sources%rowtype;BEGIN
 SELECT * INTO STRICT spec FROM gridex_ediel_retention.invoice_file_catalog WHERE source_table=TG_TABLE_NAME;r:=CASE WHEN TG_OP='INSERT' THEN to_jsonb(NEW) ELSE to_jsonb(OLD) END;
 SELECT * INTO s FROM gridex_ediel_retention.invoice_file_sources WHERE retention_class=spec.retention_class AND target_id=(r->>'id')::uuid;
 IF s.id IS NOT NULL AND (TG_OP='DELETE' OR to_jsonb(NEW)->spec.body_column IS DISTINCT FROM r->spec.body_column OR to_jsonb(NEW)->'company_id' IS DISTINCT FROM r->'company_id' OR to_jsonb(NEW)->'storage_bucket' IS DISTINCT FROM r->'storage_bucket') THEN RAISE EXCEPTION 'invoice_file_captured_reference_immutable';END IF;
 IF TG_OP='INSERT' AND EXISTS(SELECT FROM gridex_ediel_retention.invoice_file_sources x JOIN gridex_ediel_retention.invoice_file_tombstones t ON t.source_id=x.id WHERE NEW.company_id=x.company_id AND to_jsonb(NEW)->>spec.body_column IN(x.storage_path,x.storage_bucket||'/'||x.storage_path)) THEN RAISE EXCEPTION 'invoice_file_tombstoned_reference_not_reusable';END IF;IF TG_OP='DELETE' THEN RETURN OLD;ELSE RETURN NEW;END IF;END$$;
DO $$DECLARE spec record;f record;BEGIN FOR spec IN SELECT * FROM gridex_ediel_retention.invoice_file_catalog LOOP EXECUTE format('CREATE TRIGGER invoice_file_capture_ref_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION gridex_ediel_retention.invoice_file_ref_guard_v1()',spec.source_table);END LOOP;
 FOR f IN SELECT p.oid::regprocedure signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='gridex_ediel_retention' AND p.proname LIKE 'invoice_file_%' OR n.nspname='public' AND p.proname IN('ediel_invoice_file_locator_v1','ediel_register_invoice_file_source_v1','ediel_invoice_file_retention_basis_v1','ediel_submit_invoice_file_retention_v1','ediel_read_invoice_file_retention_v1','ediel_read_invoice_file_source_v1','ediel_review_invoice_file_retention_v1','ediel_revoke_invoice_file_retention_v1','ediel_begin_invoice_file_purge_v1','ediel_finish_invoice_file_purge_v1','ediel_invoice_file_storage_delete_target_v1','ediel_require_invoice_file_copy_available_v1') LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO gridex_ediel_retention_owner',f.signature);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.signature);END LOOP;END$$;
GRANT EXECUTE ON FUNCTION public.ediel_invoice_file_locator_v1(uuid,uuid,text,uuid),public.ediel_invoice_file_retention_basis_v1(uuid,uuid,text,uuid),public.ediel_submit_invoice_file_retention_v1(uuid,uuid,text,uuid,text,jsonb),public.ediel_read_invoice_file_retention_v1(uuid,uuid,uuid),public.ediel_review_invoice_file_retention_v1(uuid,uuid,uuid,text,text),public.ediel_revoke_invoice_file_retention_v1(uuid,uuid,uuid,text),public.ediel_begin_invoice_file_purge_v1(uuid,uuid,uuid),public.ediel_finish_invoice_file_purge_v1(uuid,uuid,uuid),public.ediel_invoice_file_storage_delete_target_v1(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ediel_register_invoice_file_source_v1(uuid,uuid,text,uuid,text,uuid,text,bigint),public.ediel_require_invoice_file_copy_available_v1(uuid,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ediel_read_invoice_file_source_v1(uuid,uuid,text,uuid) TO authenticated;
REVOKE CREATE ON SCHEMA public FROM gridex_ediel_retention_owner;
COMMIT;
