-- Generated by Supabase CLI migration new ediel_source_bound_business_expectations_v1.
-- Prospective source-bound internal watches. SMTP acceptance is not remote receipt.
BEGIN;
ALTER TABLE public.ediel_business_expectations ALTER COLUMN due_at DROP NOT NULL;
CREATE SCHEMA gridex_business_expectations;
REVOKE ALL ON SCHEMA gridex_business_expectations FROM PUBLIC,anon,authenticated;
GRANT USAGE ON SCHEMA gridex_business_expectations TO service_role;
CREATE TABLE gridex_business_expectations.bindings (
 expectation_id uuid PRIMARY KEY REFERENCES public.ediel_business_expectations(id) ON DELETE RESTRICT,
 company_id uuid NOT NULL REFERENCES public.companies(id), environment text NOT NULL CHECK(environment IN ('test','production')),
 source_message_id uuid NOT NULL UNIQUE REFERENCES public.ediel_messages(id) ON DELETE RESTRICT,
 transport_attempt_id uuid NOT NULL REFERENCES gridex_ediel_transport.attempts(id) ON DELETE RESTRICT,
 source_payload_hash text NOT NULL, observed_at timestamptz NOT NULL, plan jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE gridex_business_expectations.bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE gridex_business_expectations.bindings FORCE ROW LEVEL SECURITY;
REVOKE ALL ON gridex_business_expectations.bindings FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON public.ediel_business_expectations FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION gridex_business_expectations.immutable_v1() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN RAISE EXCEPTION 'ediel_business_expectation_binding_immutable'; END $$;
CREATE TRIGGER expectation_binding_immutable BEFORE UPDATE OR DELETE ON gridex_business_expectations.bindings FOR EACH ROW EXECUTE FUNCTION gridex_business_expectations.immutable_v1();
REVOKE ALL ON FUNCTION gridex_business_expectations.immutable_v1() FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION gridex_business_expectations.reconcile_v1(p_expectation uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE b gridex_business_expectations.bindings%rowtype; e public.ediel_business_expectations%rowtype;
 resolved uuid; decision text; original public.ediel_messages%rowtype; original_wire jsonb;
BEGIN
 SELECT * INTO b FROM gridex_business_expectations.bindings WHERE expectation_id=p_expectation;
 IF NOT FOUND THEN RETURN; END IF;
 SELECT * INTO e FROM public.ediel_business_expectations WHERE id=p_expectation AND company_id=b.company_id AND environment=b.environment FOR UPDATE;
 IF NOT FOUND OR e.status NOT IN ('pending','timeout','manual_review') THEN RETURN; END IF;
 IF e.expected_code='Z02' THEN
  SELECT * INTO original FROM public.ediel_messages WHERE id=b.source_message_id AND company_id=b.company_id AND environment=b.environment;
  IF NOT FOUND OR original.immutable_payload_hash IS DISTINCT FROM b.source_payload_hash OR b.source_payload_hash IS DISTINCT FROM encode(sha256(convert_to(original.raw_payload,'UTF8')),'hex') THEN RETURN; END IF;
  original_wire:=gridex_received_sources.z02_core_wire_v1(original.raw_payload);
  IF original_wire IS NULL OR jsonb_array_length(original_wire->'objects')=0 OR EXISTS(
   SELECT FROM jsonb_array_elements(original_wire->'objects') own WHERE NOT EXISTS(
    SELECT FROM gridex_received_sources.z02_core_applications tr JOIN public.ediel_messages m ON m.id=tr.source_message_id AND m.company_id=tr.company_id AND m.environment=tr.environment
    WHERE tr.company_id=b.company_id AND tr.environment=b.environment AND tr.originating_z01_message_id=b.source_message_id
     AND tr.object_id=own->>'objectId' AND tr.identity_agency=own->>'identityAgency'
     AND tr.source_payload_hash=encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex'))) THEN RETURN; END IF;
  SELECT tr.source_message_id,'fulfilled' INTO resolved,decision
   FROM gridex_received_sources.z02_core_applications tr JOIN public.ediel_messages m ON m.id=tr.source_message_id AND m.company_id=tr.company_id AND m.environment=tr.environment
   WHERE tr.company_id=b.company_id AND tr.environment=b.environment AND tr.originating_z01_message_id=b.source_message_id
    AND tr.source_payload_hash=encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex') AND m.direction='inbound'
   ORDER BY tr.applied_at DESC,tr.source_message_id LIMIT 1;
 ELSIF e.expected_code='Z14' THEN
  SELECT tr.source_message_id,CASE WHEN tr.resulting_state->>'status' IN ('rejected_active','rejected_passive_timeout') THEN 'rejected' ELSE 'fulfilled' END INTO resolved,decision
   FROM gridex_received_sources.permission_transitions tr JOIN public.ediel_messages m ON m.id=tr.source_message_id AND m.company_id=tr.company_id AND m.environment=b.environment
   WHERE tr.company_id=b.company_id AND tr.qualified_original_message_id=b.source_message_id AND tr.qualified_expected_message_code='Z14'
    AND tr.resulting_state->>'inbound_z14_message_id'=tr.source_message_id::text
    AND tr.payload_hash=encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex') AND m.direction='inbound'
   ORDER BY tr.applied_at,tr.source_message_id LIMIT 1;
 ELSIF e.expected_code='Z15' THEN
  -- The permission source owner supplies exact physical request/result
  -- correlation; a last-outbound pointer alone never qualifies a notice.
  SELECT tr.source_message_id,'fulfilled' INTO resolved,decision
   FROM gridex_received_sources.permission_transitions tr JOIN public.ediel_messages m ON m.id=tr.source_message_id AND m.company_id=tr.company_id AND m.environment=b.environment
   WHERE tr.company_id=b.company_id AND tr.qualified_original_message_id=b.source_message_id AND tr.qualified_expected_message_code='Z15'
    AND tr.resulting_state->>'inbound_z15_message_id'=tr.source_message_id::text
    AND tr.payload_hash=encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex') AND m.direction='inbound'
   ORDER BY tr.applied_at,tr.source_message_id LIMIT 1;
 END IF;
 IF resolved IS NOT NULL THEN
  UPDATE public.ediel_business_expectations SET status=decision,fulfilled_by_message_id=resolved,updated_at=now(),
   metadata=metadata||jsonb_build_object('resolvedBy','immutable_applied_business_source','resolvedAt',now()) WHERE id=e.id;
 END IF;
END $$;
REVOKE ALL ON FUNCTION gridex_business_expectations.reconcile_v1(uuid) FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION gridex_business_expectations.applied_source_v1() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE e uuid;
BEGIN
 FOR e IN SELECT b.expectation_id FROM gridex_business_expectations.bindings b WHERE b.company_id=NEW.company_id LOOP
  PERFORM gridex_business_expectations.reconcile_v1(e);
 END LOOP;
 RETURN NEW;
END $$;
CREATE TRIGGER expectation_z02_applied AFTER INSERT ON gridex_received_sources.z02_core_applications FOR EACH ROW EXECUTE FUNCTION gridex_business_expectations.applied_source_v1();
CREATE TRIGGER expectation_permission_applied AFTER INSERT ON gridex_received_sources.permission_transitions FOR EACH ROW EXECUTE FUNCTION gridex_business_expectations.applied_source_v1();
REVOKE ALL ON FUNCTION gridex_business_expectations.applied_source_v1() FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION gridex_business_expectations.mutate_v1(p_input jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c uuid:=(p_input->>'companyId')::uuid; env text:=p_input->>'environment'; actor uuid:=(p_input->>'actorUserId')::uuid;
 action text:=p_input->>'action'; mid uuid:=(p_input->>'messageId')::uuid; lim integer:=greatest(1,least(coalesce((p_input->>'limit')::integer,100),500));
 m public.ediel_messages%rowtype; a gridex_ediel_transport.attempts%rowtype; b gridex_business_expectations.bindings%rowtype;
 tokens jsonb; plan jsonb; code text; due timestamptz; expected_id uuid; e uuid; offset_value integer; result jsonb;
BEGIN
 IF c IS NULL OR actor IS NULL OR env IS NULL OR env NOT IN ('test','production') OR action IS NULL OR action NOT IN ('register','read','expire') THEN RAISE EXCEPTION 'ediel_expectation_scope_required'; END IF;
 IF NOT EXISTS(SELECT FROM public.company_memberships x WHERE x.company_id=c AND x.user_id=actor AND x.status='active' AND x.is_active AND x.accepted_at IS NOT NULL)
 OR NOT EXISTS(SELECT FROM public.user_profiles x WHERE x.id=actor AND x.user_status='active')
 OR NOT coalesce(public.gridex_actor_has_company_permission(actor,c,CASE WHEN action='read' THEN 'communication.read' ELSE 'communication.send' END),false)
 THEN RAISE EXCEPTION 'ediel_expectation_actor_not_authorized' USING ERRCODE='42501'; END IF;
 IF action='register' THEN
  SELECT * INTO STRICT m FROM public.ediel_messages WHERE id=mid AND company_id=c AND environment=env FOR UPDATE;
  IF m.direction IS DISTINCT FROM 'outbound' OR m.message_standard IS DISTINCT FROM 'edifact' OR m.immutable_rendered_at IS NULL
   OR m.immutable_payload_hash IS DISTINCT FROM encode(sha256(convert_to(m.raw_payload,'UTF8')),'hex') THEN RAISE EXCEPTION 'ediel_expectation_sealed_source_required'; END IF;
  tokens:=gridex_received_sources.wire_tokens_bounded_v1(m.raw_payload,999999);
  IF tokens IS NULL OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='UNH')<>1
   OR NOT EXISTS(SELECT FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='UNH' AND t#>>'{elements,2,0}'='PRODAT')
   OR (SELECT count(*) FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='BGM')<>1 THEN RAISE EXCEPTION 'ediel_expectation_physical_source_required'; END IF;
  SELECT t#>>'{elements,1,0}' INTO code FROM jsonb_array_elements(tokens) t WHERE t->>'tag'='BGM';
  IF code NOT IN ('Z01','Z13','Z18') THEN RETURN '[]'::jsonb; END IF;
  SELECT * INTO b FROM gridex_business_expectations.bindings WHERE source_message_id=mid;
  IF FOUND THEN
   IF b.company_id<>c OR b.environment<>env OR b.source_payload_hash IS DISTINCT FROM m.immutable_payload_hash THEN RAISE EXCEPTION 'ediel_expectation_source_changed'; END IF;
   PERFORM gridex_business_expectations.reconcile_v1(b.expectation_id);
   RETURN jsonb_build_array((SELECT to_jsonb(x) FROM public.ediel_business_expectations x WHERE x.id=b.expectation_id));
  END IF;
  SELECT * INTO a FROM gridex_ediel_transport.attempts WHERE message_id=mid AND company_id=c AND environment=env AND classification='accepted' AND observed_at IS NOT NULL AND entered_at IS NOT NULL ORDER BY observed_at,id LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'ediel_expectation_actual_smtp_acceptance_required'; END IF;
  plan:=a.binding->'businessExpectationPlan';
  IF a.binding->>'originalHash' IS DISTINCT FROM m.immutable_payload_hash OR jsonb_typeof(plan) IS DISTINCT FROM 'object'
   OR plan->>'sourceCode' IS DISTINCT FROM code OR plan->>'version' IS DISTINCT FROM '1' OR plan->>'expectedFamily' IS DISTINCT FROM 'PRODAT'
   OR plan->>'expectedCode' IS DISTINCT FROM (CASE code WHEN 'Z01' THEN 'Z02' WHEN 'Z13' THEN 'Z14' WHEN 'Z18' THEN 'Z15' END)
   OR plan->>'anchor' IS DISTINCT FROM 'actual_accepted_smtp_observed_at' OR plan->'remoteReceiptKnown' IS DISTINCT FROM 'false'::jsonb
   OR jsonb_typeof(plan#>'{policy,sourceTrace}') IS DISTINCT FROM 'array' OR nullif(plan#>>'{policy,guideRevision}','') IS NULL
   OR nullif(plan#>>'{policy,referenceDate}','') IS NULL THEN RAISE EXCEPTION 'ediel_expectation_prepared_policy_missing'; END IF;
  due:=NULL;
  IF code='Z18' THEN
   IF plan->'offset' IS DISTINCT FROM 'null'::jsonb OR plan->'unit' IS DISTINCT FROM 'null'::jsonb OR plan->>'timerKind' IS DISTINCT FROM 'untimed_business_response' THEN RAISE EXCEPTION 'ediel_expectation_unsupported_timer'; END IF;
  ELSE
   offset_value:=(plan->>'offset')::integer;
   IF offset_value IS NULL OR offset_value<=0 OR plan->>'timerKind' IS DISTINCT FROM 'internal_sender_watch'
    OR jsonb_typeof(plan->'deadlineSource') IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'ediel_expectation_deadline_authority_missing'; END IF;
   IF plan->>'unit'='minutes' THEN due:=a.observed_at+make_interval(mins=>offset_value);
   ELSIF plan->>'unit'='calendar_days' THEN due:=((a.observed_at AT TIME ZONE 'Europe/Stockholm')+make_interval(days=>offset_value)) AT TIME ZONE 'Europe/Stockholm';
   ELSE RAISE EXCEPTION 'ediel_expectation_timer_unit_invalid'; END IF;
  END IF;
  INSERT INTO public.ediel_business_expectations(company_id,environment,source_message_id,source_operation_id,expected_family,expected_code,expected_subtype,due_at,metadata)
   VALUES(c,env,mid,coalesce(nullif(m.source_operation_id,''),m.operation_id::text,'source_message:'||mid::text),'PRODAT',plan->>'expectedCode',NULL,due,
    jsonb_build_object('timerKind',plan->>'timerKind','timerRuleId',plan->'timerRuleId','anchorType','actual_accepted_smtp_observed_at','anchorAt',a.observed_at,
     'remoteReceiptKnown',false,'automaticResendAllowed',false,'preparedPolicy',plan->'policy','transportAttemptId',a.id)) RETURNING id INTO expected_id;
  INSERT INTO gridex_business_expectations.bindings(expectation_id,company_id,environment,source_message_id,transport_attempt_id,source_payload_hash,observed_at,plan)
   VALUES(expected_id,c,env,mid,a.id,m.immutable_payload_hash,a.observed_at,plan);
  -- Reconcile after insertion too: a genuine response may have won the race.
  PERFORM gridex_business_expectations.reconcile_v1(expected_id);
  RETURN jsonb_build_array((SELECT to_jsonb(x) FROM public.ediel_business_expectations x WHERE x.id=expected_id));
 END IF;
 FOR e IN SELECT x.id FROM public.ediel_business_expectations x JOIN gridex_business_expectations.bindings owned ON owned.expectation_id=x.id
  WHERE x.company_id=c AND x.environment=env AND (mid IS NULL OR x.source_message_id=mid)
   AND (action='read' OR x.status='pending' AND x.due_at IS NOT NULL AND x.due_at<=now()) ORDER BY x.created_at,x.id LIMIT lim LOOP
  PERFORM gridex_business_expectations.reconcile_v1(e);
  IF action='expire' THEN UPDATE public.ediel_business_expectations SET status='manual_review',updated_at=now(),metadata=metadata||jsonb_build_object('expiredAt',now(),'remoteReceiptKnown',false,'automaticResendAllowed',false)
   WHERE id=e AND status='pending' AND due_at IS NOT NULL AND due_at<=now(); END IF;
 END LOOP;
 SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY x.created_at,x.id),'[]') INTO result FROM
  (SELECT x.* FROM public.ediel_business_expectations x JOIN gridex_business_expectations.bindings owned ON owned.expectation_id=x.id WHERE x.company_id=c AND x.environment=env AND (mid IS NULL OR x.source_message_id=mid) ORDER BY x.created_at,x.id LIMIT lim) x;
 RETURN result;
END $$;
REVOKE ALL ON FUNCTION gridex_business_expectations.mutate_v1(jsonb) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.gridex_ediel_business_expectations_v1(p_input jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog AS $$
BEGIN
 IF current_user<>'service_role' THEN RAISE EXCEPTION 'ediel_expectation_service_required' USING ERRCODE='42501'; END IF;
 RETURN gridex_business_expectations.mutate_v1(p_input);
END $$;
REVOKE ALL ON FUNCTION public.gridex_ediel_business_expectations_v1(jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION gridex_business_expectations.mutate_v1(jsonb),public.gridex_ediel_business_expectations_v1(jsonb) TO service_role;
COMMIT;
