import {readFileSync} from 'node:fs'
import {test,expect} from '@playwright/test'
const enabled=process.env.GRIDEX_EDIEL_CASE_LOCAL_E2E==='1'&&process.env.NEXT_PUBLIC_SUPABASE_URL==='http://127.0.0.1:54321'&&!process.env.GRIDEX_E2E_BROWSER_BASE_URL&&Boolean(process.env.GRIDEX_BILATERAL_FIXTURE_PATH&&process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD)
test.skip(!enabled,'Requires actual local signed source and native current actor fixture.')
const f=enabled?JSON.parse(readFileSync(process.env.GRIDEX_BILATERAL_FIXTURE_PATH,'utf8')):null,api='/api/ediel/customer-source-agreements'
async function login(page,email){await page.goto('/login');await page.getByLabel('E-post').fill(email);await page.getByLabel('Lösenord').fill(process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD);await page.getByRole('button',{name:'Logga in'}).click();await page.waitForURL(u=>!u.pathname.startsWith('/login'))}
const detail=id=>`/admin/ediel/customer-source-agreements?artifactId=${id}`,workspace=page=>page.getByRole('region',{name:'Bilateralt kundunderlag',exact:true})
test('actual upload private original separate review and keyboard apply survive reload without Z09',async({browser},info)=>{
 const writer=await browser.newPage();await login(writer,f.actorEmail);await writer.goto('/admin/ediel/customer-source-agreements');const form=workspace(writer)
 await expect(writer.getByRole('heading',{name:'Bilateralt kundunderlag',exact:true})).toBeVisible()
 await form.getByLabel('Mottaget kundändringsmeddelande').selectOption(f.sourceMessageId);await form.getByLabel('Leveransperiod',{exact:true}).selectOption(f.periodId);await form.getByLabel('Bilateralt avtal',{exact:true}).selectOption(f.agreementId)
 await form.getByLabel('Källreferens',{exact:true}).fill(f.submission.source.reference);await form.getByLabel('Källversion',{exact:true}).fill('1');await form.getByLabel('PDF-original, högst 8 MiB').setInputFiles({name:'synthetic-bilateral.pdf',mimeType:'application/pdf',buffer:Buffer.from(f.sourceText)});await form.getByLabel('Utfärdarkvitto (JSON)').fill(JSON.stringify(f.submission.issuerReceipt))
 const pending=writer.waitForResponse(r=>r.url().endsWith(api)&&r.request().method()==='POST');await form.getByRole('button',{name:'Arkivera original',exact:true}).click();const response=await pending;expect(response.status()).toBe(201);expect(response.headers()['cache-control']).toBe('private, no-store');const archived=await response.json();expect(archived.sourceHash).toBe(f.sourceHash);await expect(form.getByText(f.sourceHash,{exact:true})).toBeVisible();await expect(form.getByRole('button',{name:'Tillämpa mottagen kundändring'})).toHaveCount(0)
 await form.getByLabel('Beslut',{exact:true}).selectOption('approve');await form.getByLabel('Skäl',{exact:true}).fill('Forbidden self review');await form.getByLabel('Klausulens plats').fill(f.clause.locator);await form.getByLabel('Ordagrant klausulcitat').fill(f.clause.quote)
 const self=writer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/review`)&&r.request().method()==='POST');await form.getByRole('button',{name:'Spara granskning'}).click();expect((await self).status()).toBe(403)
 const reviewer=await browser.newPage();await login(reviewer,f.reviewerEmail);await reviewer.goto(detail(archived.artifactId));const review=workspace(reviewer);await expect(review.getByText(f.sourceHash,{exact:true})).toBeVisible()
 const bytes=await reviewer.request.get(`${api}/${archived.artifactId}/source`);expect(bytes.status()).toBe(200);expect(bytes.headers()['cache-control']).toBe('private, no-store');expect(await bytes.text()).toBe(f.sourceText)
 await review.getByLabel('Beslut',{exact:true}).selectOption('approve');await review.getByLabel('Skäl',{exact:true}).fill('Separate review of exact synthetic original and current issuer');await review.getByLabel('Klausulens plats').fill(f.clause.locator);await review.getByLabel('Ordagrant klausulcitat').fill(f.clause.quote)
 const approved=reviewer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/review`)&&r.request().method()==='POST');await review.getByRole('button',{name:'Spara granskning'}).click();expect((await approved).status()).toBe(200)
 await writer.reload();const apply=workspace(writer).getByRole('button',{name:'Tillämpa mottagen kundändring',exact:true});await expect(apply).toBeVisible();await apply.focus();await expect(apply).toBeFocused();const applied=writer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/apply`)&&r.request().method()==='POST');await writer.keyboard.press('Enter');expect((await applied).status()).toBe(200);await expect(workspace(writer).getByRole('status')).toContainText('Kundversionen är tillämpad')
 await writer.reload();await expect(workspace(writer).getByText(f.sourceHash,{exact:true})).toBeVisible();const replay=writer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/apply`)&&r.request().method()==='POST');await workspace(writer).getByRole('button',{name:'Tillämpa mottagen kundändring'}).click();expect((await replay).status()).toBe(200)
 await info.attach('bilateral-source-archive-review-apply-reload',{body:await writer.screenshot({fullPage:true}),contentType:'image/png'});await writer.close();await reviewer.close()
})
test('actual read-only mobile and foreign source access cannot mutate or leak originals',async({browser},info)=>{
 const reader=await browser.newPage({viewport:{width:375,height:812}});await login(reader,f.readerEmail);await reader.goto(detail(f.readOnlyArtifactId));await expect(workspace(reader).getByText(f.readOnlySourceHash,{exact:true})).toBeVisible();const artifacts=await reader.request.get(`${api}/not-a-uuid`);expect(artifacts.status()).toBe(400)
 for(const name of ['Arkivera original','Spara granskning','Tillämpa mottagen kundändring'])await expect(workspace(reader).getByRole('button',{name,exact:true})).toHaveCount(0)
 await reader.addStyleTag({content:'html{zoom:2}'});expect(await reader.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true);await info.attach('bilateral-readonly-mobile-200-percent',{body:await reader.screenshot({fullPage:true}),contentType:'image/png'})
 expect((await reader.request.post(api,{data:f.submission})).status()).toBe(403)
 const foreign=await browser.newPage();await login(foreign,f.outsiderEmail);await foreign.goto(detail(f.readOnlyArtifactId));const privateBytes=await foreign.request.get(`${api}/${f.readOnlyArtifactId}/source`);expect(privateBytes.status()).toBe(403);expect(privateBytes.headers()['cache-control']).toBe('private, no-store');expect(await privateBytes.text()).not.toContain(f.readOnlySourceText);await expect(workspace(foreign).getByText(f.sourceHash,{exact:true})).toHaveCount(0);const forbidden=await foreign.request.post(api,{data:f.submission});expect(forbidden.status()).toBe(403);expect(await forbidden.text()).not.toContain(f.sourceText);await reader.close();await foreign.close()
})
