import {readFileSync} from 'node:fs'
import {test,expect} from '@playwright/test'
const enabled=process.env.GRIDEX_EDIEL_CASE_LOCAL_E2E==='1'&&process.env.NEXT_PUBLIC_SUPABASE_URL==='http://127.0.0.1:54321'&&!process.env.GRIDEX_E2E_BROWSER_BASE_URL&&Boolean(process.env.GRIDEX_REQUESTED_CUSTOMER_CHANGE_FIXTURE_PATH&&process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD)
test.skip(!enabled,'Requires actual local supply/contract/archive and current GoTrue source actors.')
const f=enabled?JSON.parse(readFileSync(process.env.GRIDEX_REQUESTED_CUSTOMER_CHANGE_FIXTURE_PATH,'utf8')):null,api='/api/ediel/requested-customer-change-sources',ui='/admin/ediel/requested-customer-changes'
const workspace=page=>page.getByRole('region',{name:'Begärd kundändring',exact:true})
async function login(page,email){await page.goto('/login');await page.getByLabel('E-post').fill(email);await page.getByLabel('Lösenord').fill(process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD);await page.getByRole('button',{name:'Logga in'}).click();await page.waitForURL(u=>!u.pathname.startsWith('/login'))}
async function open(page,id){await page.goto(`${ui}?artifactId=${id}`);const response=page.waitForResponse(r=>r.url().endsWith(`${api}/${id}`)&&r.request().method()==='GET');await workspace(page).getByRole('button',{name:'Öppna underlag',exact:true}).click();return response}
async function review(form,clause,reason){await form.getByLabel('Granskningsval',{exact:true}).selectOption('approve');await form.getByLabel('Motivering',{exact:true}).fill(reason);await form.getByLabel('Var finns avtalstexten?',{exact:true}).fill(clause.locator);await form.getByLabel('Ordagrann avtalstext',{exact:true}).fill(clause.quote)}
test('actual upload private PDF independent review keyboard queue reload and immutable retry',async({browser},info)=>{
 const writer=await browser.newPage();await login(writer,f.actorEmail);await writer.goto(ui);const form=workspace(writer)
 await expect(writer.getByRole('heading',{name:'Begärd kundändring',exact:true})).toBeVisible()
 await form.getByLabel('Bilateralt mandat',{exact:true}).selectOption(f.agreementId);await form.getByLabel('Egen leverans och avtal',{exact:true}).selectOption(f.periodId)
 await form.getByLabel('Källreferens',{exact:true}).fill(f.submission.source.reference);await form.getByLabel('Originalets version',{exact:true}).fill('1')
 await form.getByLabel('Originalavtal (PDF, högst 8 MB)',{exact:true}).setInputFiles({name:'synthetic-outgoing-original.pdf',mimeType:'application/pdf',buffer:Buffer.from(f.sourceText)})
 await form.getByLabel('Överenskommen begäran (Ediel-original, högst 1 MB)',{exact:true}).setInputFiles({name:'synthetic-agreed-request.edi',mimeType:'text/plain',buffer:Buffer.from(f.rawPayload)})
 await form.getByLabel('Utfärdarens signerade kvitto, om tillgängligt',{exact:true}).setInputFiles({name:'synthetic-issuer-receipt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(f.submission.issuerReceipt))})
 const pending=writer.waitForResponse(r=>r.url().endsWith(api)&&r.request().method()==='POST');await form.getByRole('button',{name:'Arkivera original',exact:true}).click();const response=await pending;expect(response.status()).toBe(201);expect(response.headers()['cache-control']).toBe('private, no-store');const archived=await response.json();expect(archived.sourceHash).toBe(f.sourceHash)
 await expect(form.getByText(f.submission.source.reference,{exact:false})).toBeVisible();await expect(form.getByRole('button',{name:'Kölägg kundändring',exact:true})).toBeDisabled()
 await review(form,f.clause,'Forbidden self approval');const self=writer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/review`)&&r.request().method()==='POST');await form.getByRole('button',{name:'Spara separat granskning',exact:true}).click();expect((await self).status()).toBe(403)
 const reviewer=await browser.newPage();await login(reviewer,f.reviewerEmail);expect((await open(reviewer,archived.artifactId)).status()).toBe(200);const reviewForm=workspace(reviewer)
 const bytes=await reviewer.request.get(`${api}/${archived.artifactId}/source`);expect(bytes.status()).toBe(200);expect(bytes.headers()['cache-control']).toBe('private, no-store');expect(bytes.headers()['x-content-type-options']).toBe('nosniff');expect(bytes.headers()['content-disposition']).toMatch(/^attachment;/);expect(await bytes.text()).toBe(f.sourceText)
 await review(reviewForm,f.clause,'Separate review of exact outgoing original and current issuer mandate');const approved=reviewer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/review`)&&r.request().method()==='POST');await reviewForm.getByRole('button',{name:'Spara separat granskning',exact:true}).click();expect((await approved).status()).toBe(200)
 expect((await open(writer,archived.artifactId)).status()).toBe(200);const queue=workspace(writer).getByRole('button',{name:'Kölägg kundändring',exact:true});await expect(queue).toBeEnabled();await queue.focus();await expect(queue).toBeFocused();const queued=writer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/queue`)&&r.request().method()==='POST');await writer.keyboard.press('Enter');const result=await queued;expect(result.status()).toBe(202);expect(await result.json()).toMatchObject({status:'queued'});await expect(workspace(writer).getByRole('status')).toContainText('Begäran är kölagd.')
 await writer.reload();expect((await open(writer,archived.artifactId)).status()).toBe(200);const retry=writer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/queue`)&&r.request().method()==='POST');await workspace(writer).getByRole('button',{name:'Kölägg kundändring',exact:true}).click();expect((await retry).status()).toBe(200);await expect(workspace(writer).getByRole('status')).toContainText('Den tidigare begäran finns redan.')
 await info.attach('requested-customer-source-upload-review-queue-reload',{body:await writer.screenshot({fullPage:true}),contentType:'image/png'});await writer.close();await reviewer.close()
})
test('actual read-only mobile scope holds missing issuer and rejects writes or foreign byte reads',async({browser},info)=>{
 const reader=await browser.newPage({viewport:{width:375,height:812}});await login(reader,f.readerEmail);expect((await open(reader,f.readOnlyArtifactId)).status()).toBe(200);const form=workspace(reader)
 await expect(form.getByRole('status')).toContainText('signerade kvitto saknas');for(const name of ['Arkivera original','Spara separat granskning','Kölägg kundändring'])await expect(form.getByRole('button',{name,exact:true})).toBeDisabled()
 const bytes=await reader.request.get(`${api}/${f.readOnlyArtifactId}/source`);expect(bytes.status()).toBe(200);expect(await bytes.text()).toBe(f.readOnlySourceText)
 const{environment,...submission}=f.submission;expect(environment).toBe('test');expect((await reader.request.post(api,{data:submission})).status()).toBe(403)
 await reader.addStyleTag({content:'html{zoom:2}'});expect(await reader.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true);await info.attach('requested-customer-readonly-mobile-200-percent',{body:await reader.screenshot({fullPage:true}),contentType:'image/png'})
 const foreign=await browser.newPage();await login(foreign,f.outsiderEmail);const result=await open(foreign,f.readOnlyArtifactId);expect(result.status()).toBe(403);const denied=await foreign.request.get(`${api}/${f.readOnlyArtifactId}/source`);expect(denied.status()).toBe(403);expect(denied.headers()['cache-control']).toBe('private, no-store');expect(await denied.text()).not.toContain(f.readOnlySourceText);await expect(workspace(foreign).getByText(f.submission.source.reference,{exact:false})).toHaveCount(0);await reader.close();await foreign.close()
})
