import {test,expect} from '@playwright/test'
import {readFileSync,writeFileSync} from 'node:fs'
import {createHash,createHmac} from 'node:crypto'
const enabled=Boolean(process.env.GRIDEX_DECISION_RETENTION_FIXTURE_PATH&&process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD)
test.skip(!enabled,'Requires actual disposable archive/GoTrue/current class fixture; synthetic legal competence only.')
test.describe.configure({mode:'serial',retries:0})
const f=enabled?JSON.parse(readFileSync(process.env.GRIDEX_DECISION_RETENTION_FIXTURE_PATH,'utf8')):null,api='/api/ediel/decision-evidence-retention'
const save=()=>writeFileSync(process.env.GRIDEX_DECISION_RETENTION_FIXTURE_PATH,JSON.stringify(f),{mode:0o600})
async function login(page,email){await page.goto('/login?next=%2Fretention%2Fdecision-evidence');await page.getByLabel('E-post').fill(email);await page.getByLabel('Lösenord').fill(process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD);await page.getByRole('button',{name:'Logga in',exact:true}).click();await page.waitForURL(url=>url.pathname==='/retention/decision-evidence');await expect(page.getByRole('heading',{name:'Behörig gallring',exact:true})).toBeVisible()}
async function choose(page,company){await page.getByLabel('Eget bolag för gallring',{exact:true}).selectOption(company);await page.getByRole('button',{name:'Välj eget bolag',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Bolaget är valt'})).toBeVisible();await page.reload()}
async function read(page,id){await page.getByLabel('Underlagets ID',{exact:true}).fill(id);await page.getByRole('button',{name:'Läs underlag',exact:true}).click();await expect(page.getByRole('button',{name:'Läs underlag',exact:true})).toBeEnabled();await expect(page.getByText('Underlagets hash',{exact:true})).toBeVisible()}
async function original(page,kind,target){await page.getByLabel('Originalklass',{exact:true}).selectOption(kind);await page.getByLabel('Originalets ID',{exact:true}).fill(target);await page.getByRole('button',{name:'Läs originalmetadata',exact:true}).click();await expect(page.getByTestId('decision-source-hash')).toBeVisible()}
async function archive(page,kind,target,documentBase64,receipt){await original(page,kind,target);await page.getByLabel('Rättsligt underlag',{exact:true}).setInputFiles({name:'synthetic-class-policy.txt',mimeType:'text/plain',buffer:Buffer.from(documentBase64,'base64')});await page.getByLabel('Utfärdarens signerade kvitto',{exact:true}).setInputFiles({name:'synthetic-issuer-receipt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(receipt))});await page.getByRole('button',{name:'Arkivera underlag',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Underlaget är arkiverat'})).toBeVisible();const id=await page.getByLabel('Underlagets ID',{exact:true}).inputValue();expect(id).toMatch(/^[a-f0-9-]{36}$/);return id}
async function approve(page,id){await read(page,id);await page.getByLabel('Granskarens motivering',{exact:true}).fill('SYNTHETIC separate exact source/hash/deadline review; not legal competence');await page.getByLabel('Granskarens motivering',{exact:true}).focus();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Godkänn efter separat granskning',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('status').filter({hasText:'Granskningen är registrerad'})).toBeVisible()}
async function purge(page,id){await read(page,id);await page.getByRole('button',{name:'Verkställ beslutad rensning',exact:true}).click();await expect(page.getByTestId('decision-purge-completed')).toBeVisible()}
test('archived-only actors perform actual upload/hash-exact download/separate keyboard review/revoke and physical decision-original then policy-original erasure',async({browser},info)=>{
 const writer=await browser.newPage(),reviewer=await browser.newPage();await login(writer,f.actorEmail);await choose(writer,f.companyId);await login(reviewer,f.reviewerEmail);await choose(reviewer,f.companyId)
 f.revokedPolicyId=await archive(writer,f.basis.retentionClass,f.targetId,f.revokedDocumentBase64,f.revokedIssuerReceipt);save();await approve(reviewer,f.revokedPolicyId);await reviewer.getByLabel('Granskarens motivering',{exact:true}).fill('SYNTHETIC policy withdrawn');await reviewer.getByRole('button',{name:'Återkalla underlag',exact:true}).click();await expect(reviewer.getByRole('status').filter({hasText:'Underlaget är återkallat'})).toBeVisible();await read(writer,f.revokedPolicyId);await expect(writer.getByRole('button',{name:'Verkställ beslutad rensning',exact:true})).toBeDisabled()
 f.policyId=await archive(writer,f.basis.retentionClass,f.targetId,f.documentBase64,f.issuerReceipt);save();await read(reviewer,f.policyId)
 const [download]=await Promise.all([reviewer.waitForEvent('download'),reviewer.getByRole('link',{name:'Hämta underlag för granskning',exact:true}).click()]);const bytes=readFileSync(await download.path());expect(bytes).toEqual(Buffer.from(f.documentBase64,'base64'));expect(createHash('sha256').update(bytes).digest('hex')).toBe(f.documentHash)
 await approve(reviewer,f.policyId);await purge(writer,f.policyId);await writer.reload();await read(writer,f.policyId);await expect(writer.getByTestId('decision-purge-completed')).toBeVisible()
 // The next original is the actual policy created through this browser, not a
 // private approved row. Sign only the actual protected original metadata.
 const kind='decision_evidence_policy_original_bytes',response=await reviewer.request.get(`${api}/original/${kind}/${f.policyId}`);expect(response.status()).toBe(200);const metadata=await response.json();expect(metadata).toMatchObject({companyId:f.companyId,targetId:f.policyId,documentHash:f.documentHash,bytesAvailable:true,authority:'none'})
 const document=Buffer.from('SYNTHETIC own policy-original source deadline'),payload=Buffer.from(JSON.stringify({format:'ediel_retention_decision_original_policy_v1',operation:'erase_retention_decision_original_bytes',companyId:f.companyId,retentionClass:kind,targetId:f.policyId,sourceHash:metadata.documentHash,targetMetadataHash:metadata.targetMetadataHash,documentHash:createHash('sha256').update(document).digest('hex'),issuerLegalReference:'SYNTHETIC ORIGINAL COMPETENCE ONLY',legalBasisReference:'SYNTHETIC exact policy-original deadline',journalPurposeReference:'SYNTHETIC bounded hash history',issuedAt:new Date(Date.now()-60000).toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString(),retainUntil:new Date(Date.now()-1000).toISOString(),journalRetainUntil:new Date(Date.now()+172800000).toISOString()})),receipt={issuerId:f.issuerId,payloadBase64:payload.toString('base64'),signatureHex:createHmac('sha256',Buffer.from('SYNTHETIC ONLY decision original HMAC 01234567890123456789')).update(payload).digest('hex')}
 f.subsequentPolicyId=await archive(writer,kind,f.policyId,document.toString('base64'),receipt);save();await approve(reviewer,f.subsequentPolicyId);await purge(writer,f.subsequentPolicyId);await read(writer,f.policyId);await expect(writer.getByText('Rensat – historiska metadata kvarstår',{exact:true})).toBeVisible();await purge(writer,f.policyId)
 await info.attach('decision-original-physical-history-replay',{body:await writer.screenshot({fullPage:true}),contentType:'image/png'});await writer.getByRole('button',{name:'Logga ut',exact:true}).click();await writer.waitForURL(url=>url.pathname==='/login');expect((await writer.request.post(`${api}/${f.policyId}/purge`,{data:{}})).status()).toBe(403);await writer.close();await reviewer.close()
})
test('read-only archived actor sees retained hashes/tombstones at375px and zoom2 while every mutation and document access denies',async({browser},info)=>{
 const page=await browser.newPage({viewport:{width:375,height:812}});await login(page,f.readonlyEmail);await choose(page,f.companyId);await read(page,f.policyId);await expect(page.getByText(f.documentHash,{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Hämta underlag för granskning',exact:true})).toHaveCount(0)
 for(const suffix of ['document','review','revoke','purge']){const response=suffix==='document'?await page.request.get(`${api}/${f.policyId}/${suffix}`):await page.request.post(`${api}/${f.policyId}/${suffix}`,{data:suffix==='review'?{outcome:'approve',reason:'forbidden'}:suffix==='revoke'?{reason:'forbidden'}:{}});expect(response.status()).toBe(403)}
 for(const name of ['Arkivera underlag','Godkänn efter separat granskning','Återkalla underlag','Verkställ beslutad rensning'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);await page.addStyleTag({content:'html{zoom:2}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true);await info.attach('decision-original-readonly-mobile',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});await page.close()
})
test('foreign archived membership cannot select or read another company or override scope through caller JSON',async({browser})=>{
 const page=await browser.newPage();await login(page,f.foreignEmail);expect(await page.locator(`select[name="company_id"] option[value="${f.companyId}"]`).count()).toBe(0);await choose(page,f.foreignCompanyId);const response=await page.request.get(`${api}/${f.policyId}`);expect(response.status()).toBe(403);expect(await response.text()).not.toContain(f.documentHash);expect((await page.request.post(api,{data:{companyId:f.companyId,retentionClass:f.basis.retentionClass,targetId:f.targetId,documentBase64:f.documentBase64,issuerReceipt:f.issuerReceipt}})).status()).toBe(403);await page.close()
})
