import {readFileSync,writeFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {test,expect} from '@playwright/test'
const enabled=process.env.GRIDEX_EDIEL_CASE_LOCAL_E2E==='1'&&process.env.NEXT_PUBLIC_SUPABASE_URL==='http://127.0.0.1:54321'&&!process.env.GRIDEX_E2E_BROWSER_BASE_URL&&Boolean(process.env.GRIDEX_BLOB_RETENTION_FIXTURE_PATH&&process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD)
test.skip(!enabled,'Requires actual disposable source/archive/current class owners; synthetic legal verifier only.')
test.describe.configure({mode:'serial',retries:0})
const f=enabled?JSON.parse(readFileSync(process.env.GRIDEX_BLOB_RETENTION_FIXTURE_PATH,'utf8')):null
const save=()=>writeFileSync(process.env.GRIDEX_BLOB_RETENTION_FIXTURE_PATH,JSON.stringify(f),{mode:0o600})
async function login(page,email){await page.goto('/login?next=%2Fretention%2Fmessage-content');await page.getByLabel('E-post').fill(email);await page.getByLabel('Lösenord').fill(process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD);await page.getByRole('button',{name:'Logga in',exact:true}).click();await page.waitForURL(url=>url.pathname==='/retention/message-content');await expect(page.getByRole('heading',{name:'Behörig gallring',exact:true})).toBeVisible()}
async function choose(page,company){await page.getByLabel('Eget bolag för gallring',{exact:true}).selectOption(company);await page.getByRole('button',{name:'Välj eget bolag',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Bolaget är valt'})).toBeVisible();await page.reload()}
async function read(page,id){await page.getByLabel('Besluts-ID',{exact:true}).fill(id);await Promise.all([page.waitForResponse(response=>response.url().endsWith(`/api/ediel/message-content-retention/${id}`)&&response.request().method()==='GET'),page.getByRole('button',{name:'Läs beslut',exact:true}).click()]);await expect(page.getByRole('button',{name:'Läs beslut',exact:true})).toBeEnabled();await expect(page.getByRole('heading',{name:'Beslutets faktiska underlag',exact:true})).toBeVisible()}
async function submit(page,target,revocation=false){await page.getByLabel('Innehållsklass',{exact:true}).selectOption(target.retentionClass);await page.getByLabel('Meddelande-ID eller MIME-arkivets payload-ID',{exact:true}).fill(target.targetId);await page.getByLabel('Beslutsdokument (högst 1 MiB)',{exact:true}).setInputFiles({name:'synthetic-byte-class-policy.txt',mimeType:'text/plain',buffer:Buffer.from(revocation?target.revocationDocumentBase64:target.documentBase64,'base64')});await page.getByLabel('Utfärdarens autentiserade kvitto (JSON)',{exact:true}).fill(JSON.stringify(revocation?target.revocationIssuerReceipt:target.issuerReceipt));await page.getByRole('button',{name:'Arkivera beslut',exact:true}).click();await expect(page.getByText(createHash('sha256').update(Buffer.from(revocation?target.revocationDocumentBase64:target.documentBase64,'base64')).digest('hex'),{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Beslutets faktiska underlag',exact:true})).toBeVisible();await expect(page.locator('div[aria-live="polite"]')).toContainText('Beslutet är arkiverat');const id=await page.getByLabel('Besluts-ID',{exact:true}).inputValue();expect(id).toMatch(/^[a-f0-9-]{36}$/);return id}
async function approve(page,id){await read(page,id);await page.getByLabel('Bedömning',{exact:true}).selectOption('approve');await page.getByLabel('Granskningsskäl',{exact:true}).fill('SYNTHETIC separate actual byte source/hash/deadline review; no legal approval');await page.getByLabel('Granskningsskäl',{exact:true}).focus();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Registrera separat granskning',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('div[aria-live="polite"]')).toContainText('Granskningen är godkänd');await expect(page.getByText('Kvalificerad',{exact:true})).toBeVisible()}
test('archived-only source owners perform actual upload, byte-exact legal download, separate keyboard review/revoke and physical message/MIME purge',async({browser},info)=>{
 const writer=await browser.newPage(),reviewer=await browser.newPage();await login(writer,f.actorEmail);await choose(writer,f.companyId);await login(reviewer,f.reviewerEmail);await choose(reviewer,f.companyId)
 for(const target of f.targets){
  target.revokedDecisionId=await submit(writer,target,true);save();await approve(reviewer,target.revokedDecisionId);await reviewer.getByLabel('Skäl för återkallelse',{exact:true}).fill('SYNTHETIC current source policy withdrawn');await reviewer.getByRole('button',{name:'Återkalla beslut',exact:true}).click();await expect(reviewer.locator('div[aria-live="polite"]')).toContainText('Beslutet är återkallat');await read(writer,target.revokedDecisionId);await expect(writer.getByRole('button',{name:'Genomför eller återuppta rensning',exact:true})).toBeDisabled()
  target.decisionId=await submit(writer,target);save();await read(reviewer,target.decisionId)
  const downloadLink=reviewer.getByRole('link',{name:'Läs arkiverat beslutsdokument',exact:true}),[download]=await Promise.all([reviewer.waitForEvent('download'),downloadLink.click()]);const path=await download.path();expect(path).toBeTruthy();const bytes=readFileSync(path);expect(bytes).toEqual(Buffer.from(target.documentBase64,'base64'));expect(createHash('sha256').update(bytes).digest('hex')).toBe(target.documentHash)
  await approve(reviewer,target.decisionId);await read(writer,target.decisionId);await writer.getByLabel('Jag bekräftar rensning av detta beslut och innehåll.',{exact:true}).check();await writer.getByRole('button',{name:'Genomför eller återuppta rensning',exact:true}).click();await expect(writer.locator('div[aria-live="polite"]')).toContainText('Rensningen är genomförd');await expect(writer.getByText('Fysiska bytes borttagna',{exact:true})).toBeVisible();await writer.reload();await read(writer,target.decisionId);await expect(writer.getByText('Fysiska bytes borttagna',{exact:true})).toBeVisible()
 }
 await info.attach('message-mime-retention-actual-source-keyboard-physical-reload',{body:await writer.screenshot({fullPage:true}),contentType:'image/png'});await writer.getByRole('button',{name:'Logga ut',exact:true}).click();await writer.waitForURL(url=>url.pathname==='/login');expect((await writer.request.post(`/api/ediel/message-content-retention/${f.targets[0].decisionId}/purge`,{data:{}})).status()).toBe(403);await writer.close();await reviewer.close()
})
test('read-only archived member sees immutable hashes and truthful receipts at 375px/zoom2 while all original-byte and mutation endpoints deny',async({browser},info)=>{
 const page=await browser.newPage({viewport:{width:375,height:812}});await login(page,f.readonlyEmail);await choose(page,f.companyId)
 for(const target of f.targets){await read(page,target.decisionId);await expect(page.getByText(target.documentHash,{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Läs arkiverat beslutsdokument',exact:true})).toHaveCount(0);expect((await page.request.get(`/api/ediel/message-content-retention/${target.decisionId}/document`)).status()).toBe(403);for(const action of ['review','revoke','purge'])expect((await page.request.post(`/api/ediel/message-content-retention/${target.decisionId}/${action}`,{data:action==='review'?{outcome:'approve',reason:'forbidden'}:action==='revoke'?{reason:'forbidden'}:{}})).status()).toBe(403)}
 for(const name of ['Arkivera beslut','Registrera separat granskning','Återkalla beslut','Genomför eller återuppta rensning'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);await page.addStyleTag({content:'html{zoom:2}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true);await info.attach('message-mime-retention-readonly-mobile-zoom2',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});await page.close()
})
test('foreign archived membership cannot select, read or submit another tenant through UI or caller JSON',async({browser})=>{
 const page=await browser.newPage();await login(page,f.foreignEmail);expect(await page.locator(`select[name="company_id"] option[value="${f.companyId}"]`).count()).toBe(0);await choose(page,f.foreignCompanyId)
 for(const target of f.targets){const response=await page.request.get(`/api/ediel/message-content-retention/${target.decisionId}`);expect(response.status()).toBe(403);expect(await response.text()).not.toContain(target.documentHash);expect((await page.request.post('/api/ediel/message-content-retention',{data:{companyId:f.companyId,retentionClass:target.retentionClass,targetId:target.targetId,documentBase64:target.documentBase64,issuerReceipt:target.issuerReceipt}})).status()).toBe(403)}await page.close()
})
