import {readFileSync,writeFileSync} from 'node:fs'
import {test,expect} from '@playwright/test'
const enabled=process.env.GRIDEX_EDIEL_CASE_LOCAL_E2E==='1'&&process.env.NEXT_PUBLIC_SUPABASE_URL==='http://127.0.0.1:54321'&&!process.env.GRIDEX_E2E_BROWSER_BASE_URL&&Boolean(process.env.GRIDEX_PROCESS_RETENTION_FIXTURE_PATH&&process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD)
test.skip(!enabled,'Requires actual disposable pre-market source/class owners and named synthetic external legal verifier configuration.')
test.describe.configure({mode:'serial',retries:0})
const f=enabled?JSON.parse(readFileSync(process.env.GRIDEX_PROCESS_RETENTION_FIXTURE_PATH,'utf8')):null
const label={basis:'Pröva journalens källomfattning',submit:'Arkivera klassens beslutsfil',read:'Läs arkiverad beslutsfil',review:'Registrera separat granskning',revoke:'Återkalla beslutsbehörighet',purge:'Gallra den godkända journalens kropp'}
const operation=(page,kind)=>page.locator('form').filter({has:page.getByRole('heading',{name:label[kind],exact:true})})
async function login(page,email){await page.goto('/login?next=%2Fretention%2Fprocess-journals');await page.getByLabel('E-post').fill(email);await page.getByLabel('Lösenord').fill(process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD);await page.getByRole('button',{name:'Logga in',exact:true}).click();await page.waitForURL(url=>url.pathname==='/retention/process-journals');await expect(page.getByRole('heading',{name:'Behörig gallring',exact:true})).toBeVisible()}
async function choose(page,company){await page.getByLabel('Eget bolag för gallring',{exact:true}).selectOption(company);await page.getByRole('button',{name:'Välj eget bolag',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Bolaget är valt'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Källbunden gallring av processjournaler',exact:true})).toBeVisible()}
test('archived-only current actors upload three independently bound source policies, inspect originals, review with keyboard and redact only each selected journal body',async({browser},info)=>{
 test.setTimeout(180000)
 const writer=await browser.newPage(),reviewer=await browser.newPage();await login(writer,f.actorEmail);await choose(writer,f.companyId);await login(reviewer,f.reviewerEmail);await choose(reviewer,f.companyId)
 for(const target of f.targets){
  const basis=operation(writer,'basis');await basis.getByLabel('Journalens klass',{exact:true}).selectOption(target.retentionClass);await basis.getByLabel('Källpostens id',{exact:true}).fill(target.targetId);await basis.getByRole('button',{name:label.basis,exact:true}).click();await expect(basis.getByRole('status')).toContainText('samtliga inkluderade kundomfattningar är prövade');await expect(basis.locator('pre')).toContainText(target.sourceHash)
  const form=operation(writer,'submit');await form.getByLabel('Journalens klass',{exact:true}).selectOption(target.retentionClass);await form.getByLabel('Källpostens id',{exact:true}).fill(target.targetId);await form.getByLabel('Separat beslutsfil',{exact:true}).setInputFiles({name:'synthetic-exact-class-policy.txt',mimeType:'text/plain',buffer:Buffer.from(target.documentBase64,'base64')});await form.getByLabel('Behörig utfärdares källbundna kvittens',{exact:true}).fill(JSON.stringify(target.issuerReceipt));await form.getByRole('button',{name:label.submit,exact:true}).click();await expect(form.getByRole('status')).toContainText('En annan behörig granskare');target.decisionId=(await form.innerText()).match(/[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}/i)?.[0];expect(target.decisionId).toBeTruthy();writeFileSync(process.env.GRIDEX_PROCESS_RETENTION_FIXTURE_PATH,JSON.stringify(f),{mode:0o600})
  expect((await writer.request.post('/api/ediel/process-journal-retention',{data:{action:'review',decisionId:target.decisionId,outcome:'approve',reason:'same native actor is forbidden'}})).status()).toBe(403)
  const original=operation(reviewer,'read');await original.getByLabel('Beslutets id',{exact:true}).fill(target.decisionId);await original.getByRole('button',{name:label.read,exact:true}).click();const link=original.getByRole('link',{name:'Hämta den arkiverade beslutsfilen',exact:true});await expect(link).toBeVisible();expect(Buffer.from((await link.getAttribute('href')).split(',')[1],'base64')).toEqual(Buffer.from(target.documentBase64,'base64'))
  const review=operation(reviewer,'review');await review.getByLabel('Beslutets id',{exact:true}).fill(target.decisionId);await review.getByLabel('Utfall',{exact:true}).selectOption('approve');await review.getByLabel('Motivering',{exact:true}).fill('SYNTHETIC separate exact native source/purpose/deadline review, no external legal approval');await review.getByLabel('Motivering',{exact:true}).focus();await reviewer.keyboard.press('Tab');await expect(review.getByRole('button',{name:label.review,exact:true})).toBeFocused();await reviewer.keyboard.press('Enter');await expect(review.getByRole('status')).toContainText('Den källbundna prövningen är registrerad')
  const purge=operation(writer,'purge');await purge.getByLabel('Beslutets id',{exact:true}).fill(target.decisionId);await purge.getByRole('button',{name:label.purge,exact:true}).click();await expect(purge.getByRole('status')).toContainText('Just den valda journalens kropp är gallrad');await writer.reload();const retry=await writer.request.post('/api/ediel/process-journal-retention',{data:{action:'purge',decisionId:target.decisionId}});expect(retry.status()).toBe(200);expect(await retry.json()).toMatchObject({status:'redacted',retentionClass:target.retentionClass,replay:true})
 }
 await info.attach('process-retention-three-source-keyboard-reload',{body:await writer.screenshot({fullPage:true}),contentType:'image/png'});await writer.getByRole('button',{name:'Logga ut',exact:true}).click();await writer.waitForURL(url=>url.pathname==='/login');expect((await writer.request.post('/api/ediel/process-journal-retention',{data:{action:'read',decisionId:f.targets[0].decisionId}})).status()).toBe(403);await writer.close();await reviewer.close()
})
test('actual read-only archived member reads immutable class originals at 375px and zoom2 with every mutation denied',async({browser},info)=>{
 const page=await browser.newPage({viewport:{width:375,height:812}});await login(page,f.readonlyEmail);await choose(page,f.companyId)
 for(const target of f.targets){const form=operation(page,'read');await form.getByLabel('Beslutets id',{exact:true}).fill(target.decisionId);await form.getByRole('button',{name:label.read,exact:true}).click();await expect(form.getByRole('link',{name:'Hämta den arkiverade beslutsfilen',exact:true})).toBeVisible()}
 for(const kind of ['submit','review','revoke','purge'])await expect(operation(page,kind).getByRole('button',{name:label[kind],exact:true})).toBeDisabled()
 expect((await page.request.post('/api/ediel/process-journal-retention',{data:{action:'purge',decisionId:f.targets[0].decisionId}})).status()).toBe(403);await page.addStyleTag({content:'html{zoom:2}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true);await info.attach('process-retention-readonly-mobile-zoom2',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});await page.close()
})
test('foreign accepted archived membership cannot list another company or inspect another exact class original',async({browser})=>{
 const page=await browser.newPage();await login(page,f.foreignEmail);expect(await page.locator(`select[name="company_id"] option[value="${f.companyId}"]`).count()).toBe(0);await choose(page,f.foreignCompanyId)
 for(const target of f.targets){const read=await page.request.post('/api/ediel/process-journal-retention',{data:{action:'read',decisionId:target.decisionId}});expect(read.status()).toBe(403);expect(await read.text()).not.toContain(target.documentBase64)}
 expect((await page.request.post('/api/ediel/process-journal-retention',{data:{action:'read',decisionId:f.targets[0].decisionId,companyId:f.companyId}})).status()).toBe(400);await page.close()
})
