import {readFileSync} from 'node:fs'
import {test,expect} from '@playwright/test'
const enabled=process.env.GRIDEX_EDIEL_CASE_LOCAL_E2E==='1'&&process.env.NEXT_PUBLIC_SUPABASE_URL==='http://127.0.0.1:54321'&&!process.env.GRIDEX_E2E_BROWSER_BASE_URL&&Boolean(process.env.GRIDEX_AI_PURPOSE_FIXTURE_PATH&&process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD)
test.skip(!enabled,'Requires genuine local original writers and bounded external registry issuer.')
const f=enabled?JSON.parse(readFileSync(process.env.GRIDEX_AI_PURPOSE_FIXTURE_PATH,'utf8')):null
async function login(page,email){await page.goto('/login');await page.getByLabel('E-post').fill(email);await page.getByLabel('Lösenord').fill(process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD);await page.getByRole('button',{name:'Logga in'}).click();await page.waitForURL(u=>!u.pathname.startsWith('/login'))}
const detail=id=>`/admin/ediel/network-registry-sources?artifactId=${id}`
test('actual browser dated network original intake and separate current review preserve native source hashes',async({browser},info)=>{
 const writer=await browser.newPage();await login(writer,f.networkSubmitterEmail);await writer.goto('/admin/ediel/network-registry-sources');await expect(writer.getByRole('heading',{name:'Nätregisterunderlag',exact:true})).toBeVisible()
 await writer.getByLabel('Miljö',{exact:true}).selectOption('test');await writer.getByLabel('Nätföretag',{exact:true}).selectOption(f.networkBrowser.networkActorId)
 for(const[label,value]of [['Registerversion giltig från',f.networkBrowser.validFrom.slice(0,16)],['Registerversion giltig till',f.networkBrowser.validUntil.slice(0,16)],['Originalets beteckning',f.networkBrowser.source.reference],['Version',f.networkBrowser.source.version]])await writer.getByLabel(label,{exact:true}).fill(value)
 await writer.getByLabel('PDF-original',{exact:true}).setInputFiles({name:'synthetic-dated-network-original.pdf',mimeType:'application/pdf',buffer:Buffer.from(f.networkSourceText)});await writer.getByLabel('Utfärdarintyg, om tillgängligt').setInputFiles({name:'synthetic-network-receipt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(f.networkBrowser.issuerReceipt))})
 const upload=writer.waitForResponse(r=>r.url().endsWith('/api/ediel/network-registry-sources')&&r.request().method()==='POST');await writer.getByRole('button',{name:'Arkivera nätregisterunderlag',exact:true}).click();const response=await upload;expect(response.status()).toBe(201);const archived=await response.json();expect(archived.sourceHash).toBe(f.networkBrowserSourceHash);await expect(writer.getByText(f.networkBrowserSourceHash,{exact:true})).toBeVisible()
 await writer.getByLabel('Beslut',{exact:true}).selectOption('approve');await writer.getByLabel('Motivering',{exact:true}).fill('Synthetic network self-review forbidden');await writer.getByLabel('Var finns nätregisterklausulen?').fill(f.networkClause.locator);await writer.getByLabel('Ordagrant utdrag om nätföretag och registerversion').fill(f.networkClause.quote)
 const self=writer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/review`)&&r.request().method()==='POST');await writer.getByRole('button',{name:'Registrera nätregistergranskning'}).click();expect((await self).status()).toBe(403)
 const reviewer=await browser.newPage();await login(reviewer,f.networkReviewerEmail);await reviewer.goto(detail(archived.artifactId));const source=await reviewer.request.get(`/api/ediel/network-registry-sources/${archived.artifactId}/source`);expect(source.status()).toBe(200);expect(source.headers()['cache-control']).toBe('private, no-store');expect(await source.text()).toBe(f.networkSourceText)
 await reviewer.getByLabel('Beslut',{exact:true}).selectOption('approve');await reviewer.getByLabel('Motivering',{exact:true}).fill('Synthetic independent actual dated network registry review');await reviewer.getByLabel('Var finns nätregisterklausulen?').fill(f.networkClause.locator);await reviewer.getByLabel('Ordagrant utdrag om nätföretag och registerversion').fill(f.networkClause.quote)
 const review=reviewer.waitForResponse(r=>r.url().endsWith(`/${archived.artifactId}/review`)&&r.request().method()==='POST');await reviewer.getByRole('button',{name:'Registrera nätregistergranskning'}).focus();await reviewer.keyboard.press('Enter');expect((await review).status()).toBe(200);await writer.reload();await expect(writer.getByText('Styrkt nätregisterunderlag',{exact:true})).toBeVisible();await expect(writer.getByText(f.networkBrowserSourceHash,{exact:true})).toBeVisible();await info.attach('network-original-independent-review-native-reload',{body:await writer.screenshot({fullPage:true}),contentType:'image/png'});await writer.close();await reviewer.close()
})
test('read-only mobile and foreign source scopes prevent network writes and original leakage',async({browser})=>{
 const reader=await browser.newPage({viewport:{width:375,height:812}});await login(reader,f.readerEmail);await reader.goto(detail(f.networkNativeArtifactId));await expect(reader.getByRole('heading',{name:'Nätregisterunderlag',exact:true})).toBeVisible();for(const name of ['Arkivera nätregisterunderlag','Registrera nätregistergranskning','Återkalla nätregisterunderlag'])await expect(reader.getByRole('button',{name,exact:true})).toHaveCount(0)
 expect((await reader.request.post(`/api/ediel/network-registry-sources/${f.networkNativeArtifactId}/revoke`,{data:{reason:'unauthorized'}})).status()).toBe(403);await reader.addStyleTag({content:'html{zoom:2}'});expect(await reader.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true)
 const outsider=await browser.newPage();await login(outsider,f.outsiderEmail);expect((await outsider.request.get(`/api/ediel/network-registry-sources/${f.networkNativeArtifactId}/source`)).status()).toBe(403);await outsider.goto(detail(f.networkNativeArtifactId));await expect(outsider.getByText(f.networkBrowserSourceHash,{exact:true})).toHaveCount(0);await reader.close();await outsider.close()
})
