import {readFileSync,writeFileSync} from 'node:fs'
import {test,expect} from '@playwright/test'
const enabled=process.env.GRIDEX_EDIEL_CASE_LOCAL_E2E==='1'&&process.env.NEXT_PUBLIC_SUPABASE_URL==='http://127.0.0.1:54321'&&!process.env.GRIDEX_E2E_BROWSER_BASE_URL&&Boolean(process.env.GRIDEX_RECORD_RETENTION_FIXTURE_PATH&&process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD)
test.skip(!enabled,'Requires actual disposable local source/class owners and explicitly synthetic legal verifier configuration.')
test.describe.configure({mode:'serial',retries:0})
const f=enabled?JSON.parse(readFileSync(process.env.GRIDEX_RECORD_RETENTION_FIXTURE_PATH,'utf8')):null
async function login(page,email){await page.goto('/login?next=%2Fretention%2Fcustomer-records');await page.getByLabel('E-post').fill(email);await page.getByLabel('Lösenord').fill(process.env.GRIDEX_EDIEL_CASE_TEST_PASSWORD);await page.getByRole('button',{name:'Logga in',exact:true}).click();await page.waitForURL(url=>url.pathname==='/retention/customer-records');await expect(page.getByRole('heading',{name:'Behörig gallring',exact:true})).toBeVisible()}
async function choose(page,company){await page.getByLabel('Eget bolag för gallring',{exact:true}).selectOption(company);await page.getByRole('button',{name:'Välj eget bolag',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Bolaget är valt'})).toBeVisible();await page.reload()}
test('archived-only operators use genuine source upload, original download, separate keyboard review and one class purge through the standalone workspace',async({browser},info)=>{
 const writer=await browser.newPage();await login(writer,f.actorEmail);await choose(writer,f.companyId);await expect(writer.getByRole('heading',{name:'Klassbunden gallring',exact:true})).toBeVisible()
 const form=writer.locator('form').filter({has:writer.getByRole('heading',{name:'Historisk inaktiv kundadress',exact:true})});await form.getByLabel('Exakt källpost',{exact:true}).selectOption(f.targetId);await form.getByLabel('Juridiskt beslutsunderlag (högst 750 kB)',{exact:true}).setInputFiles({name:'synthetic-source-policy.txt',mimeType:'text/plain',buffer:Buffer.from(f.documentBase64,'base64')});await form.getByLabel('Signerat utfärdarkvitto',{exact:true}).fill(JSON.stringify(f.issuerReceipt));await form.getByRole('button',{name:'Arkivera beslut',exact:true}).click()
 const reference=writer.getByRole('status').filter({hasText:'Underlaget är arkiverat'});await expect(reference).toBeVisible();const decision=(await reference.innerText()).match(/[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}/i)?.[0];expect(decision).toBeTruthy();f.decisionId=decision;writeFileSync(process.env.GRIDEX_RECORD_RETENTION_FIXTURE_PATH,JSON.stringify(f),{mode:0o600})
 const reviewer=await browser.newPage();await login(reviewer,f.reviewerEmail);await choose(reviewer,f.companyId);await reviewer.getByLabel('Beslutsreferens för läsning',{exact:true}).fill(decision);await reviewer.getByRole('button',{name:'Läs arkiverat originalbeslut',exact:true}).click();await expect(reviewer.getByRole('link',{name:'Hämta arkiverat beslutsunderlag',exact:true})).toBeVisible();const source=await reviewer.getByRole('link',{name:'Hämta arkiverat beslutsunderlag',exact:true}).getAttribute('href');expect(Buffer.from(source.split(',')[1],'base64').toString()).toBe(Buffer.from(f.documentBase64,'base64').toString())
 await reviewer.getByLabel('Beslutsreferens för granskning',{exact:true}).fill(decision);await reviewer.getByLabel('Utfall',{exact:true}).selectOption('approve');await reviewer.getByLabel('Granskningsmotivering',{exact:true}).fill('Synthetic separate source/purpose/deadline review, no external legal approval');await reviewer.getByLabel('Granskningsmotivering',{exact:true}).focus();await reviewer.keyboard.press('Tab');await expect(reviewer.getByRole('button',{name:'Registrera separat granskning',exact:true})).toBeFocused();await reviewer.keyboard.press('Enter');await expect(reviewer.getByRole('status').filter({hasText:'Granskningen är registrerad'})).toBeVisible()
 await writer.getByLabel('Beslutsreferens',{exact:true}).fill(decision);await writer.getByRole('button',{name:'Pröva och genomför ingrepp',exact:true}).click();await expect(writer.getByRole('status').filter({hasText:'Klassens personuppgifter är gallrade'})).toBeVisible();await writer.reload();expect(await writer.locator(`option[value="${f.targetId}"]`).count()).toBe(0)
 await info.attach('record-retention-archived-source-keyboard-reload',{body:await writer.screenshot({fullPage:true}),contentType:'image/png'});await writer.getByRole('button',{name:'Logga ut',exact:true}).click();await writer.waitForURL(url=>url.pathname==='/login');expect((await writer.request.post('/api/ediel/customer-record-retention',{data:{action:'purge',decisionId:decision}})).status()).toBe(403);await writer.close();await reviewer.close()
})
test('actual read-only archived member inspects the retained original at 375px and layout zoom2 while every mutation remains denied',async({browser},info)=>{
 const page=await browser.newPage({viewport:{width:375,height:812}});await login(page,f.readonlyEmail);await choose(page,f.companyId);await page.getByLabel('Beslutsreferens för läsning',{exact:true}).fill(f.decisionId);await page.getByRole('button',{name:'Läs arkiverat originalbeslut',exact:true}).click();await expect(page.getByRole('link',{name:'Hämta arkiverat beslutsunderlag',exact:true})).toBeVisible();for(const name of ['Registrera separat granskning','Återkalla beslutets behörighet','Pröva och genomför ingrepp'])await expect(page.getByRole('button',{name,exact:true})).toBeDisabled();for(const button of await page.getByRole('button',{name:'Arkivera beslut',exact:true}).all())await expect(button).toBeDisabled()
 expect((await page.request.post('/api/ediel/customer-record-retention',{data:{action:'review',decisionId:f.decisionId,outcome:'approve',reason:'forbidden read-only review'}})).status()).toBe(403);await page.addStyleTag({content:'html{zoom:2}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBe(true);await info.attach('record-retention-readonly-mobile-zoom2',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});await page.close()
})
test('a foreign archived member cannot select or read another tenant original through browser selectors or API bodies',async({browser})=>{
 const page=await browser.newPage();await login(page,f.foreignEmail);expect(await page.locator(`select[name="company_id"] option[value="${f.companyId}"]`).count()).toBe(0);await choose(page,f.foreignCompanyId);const foreignRead=await page.request.post('/api/ediel/customer-record-retention',{data:{action:'read',decisionId:f.decisionId}});expect(foreignRead.status()).toBe(403);expect(await foreignRead.text()).not.toContain(f.documentBase64);expect((await page.request.post('/api/ediel/customer-record-retention',{data:{action:'read',decisionId:f.decisionId,companyId:f.companyId}})).status()).toBe(400);await page.close()
})
