import { readFileSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { test, expect, chromium } from '@playwright/test'

const enabled = process.env.GRIDEX_CONTACT_LOCAL_E2E === '1'
  && process.env.NEXT_PUBLIC_SUPABASE_URL === 'http://127.0.0.1:54321'
  && !process.env.GRIDEX_E2E_BROWSER_BASE_URL
  && Boolean(process.env.GRIDEX_CONTACT_FIXTURE_PATH && process.env.GRIDEX_CONTACT_TEST_PASSWORD)
test.skip(!enabled, 'Requires the disposable local Supabase replay and existing synthetic Auth fixture.')
test.describe.configure({ mode: 'serial', retries: 0 })
const fixture = enabled ? JSON.parse(readFileSync(process.env.GRIDEX_CONTACT_FIXTURE_PATH, 'utf8')) : null
const card = (id) => `/admin/customers/${id}?tab=profile`
const contactForm = (page) => page.locator(`form:has(input[name="id"][value="${fixture.contactA}"])`)
const uiContactForm = (page) => page.locator(`form:has(input[name="id"][value="${fixture.contactUi}"])`)
const runtimeEvidence = new WeakMap()

function observeRuntime(page) {
  const evidence = { pageErrors: [], consoleErrors: [], failedRequests: [], serverErrors: [], actionPosts: [] }
  runtimeEvidence.set(page, evidence)
  page.on('pageerror', (error) => evidence.pageErrors.push(error.name))
  page.on('console', (message) => { if (message.type() === 'error') evidence.consoleErrors.push({ type: message.type(), path: message.location().url ? new URL(message.location().url).pathname : null }) })
  page.on('requestfailed', (request) => { if (request.failure()?.errorText !== 'net::ERR_ABORTED') evidence.failedRequests.push({ method: request.method(), path: new URL(request.url()).pathname }) })
  page.on('response', (response) => { if (response.status() >= 500) evidence.serverErrors.push({ path: new URL(response.url()).pathname, status: response.status() }) })
  page.on('request', (request) => { if (request.method() === 'POST' && new URL(request.url()).pathname.startsWith('/admin/customers/')) evidence.actionPosts.push(new URL(request.url()).pathname) })
}

async function assertCleanRuntime(page, testInfo) {
  const evidence = runtimeEvidence.get(page)
  await testInfo.attach('sanitized-browser-runtime', { body: JSON.stringify(evidence), contentType: 'application/json' })
  expect(evidence.pageErrors).toEqual([])
  expect(evidence.consoleErrors).toEqual([])
  expect(evidence.failedRequests).toEqual([])
  expect(evidence.serverErrors).toEqual([])
  await expect(page.getByText(/^(Build Error|Runtime Error|Application error:)/)).toHaveCount(0)
}

async function login(page, email) {
  observeRuntime(page)
  await page.goto('/login')
  await page.getByLabel('E-post').fill(email)
  await page.getByLabel('Lösenord').fill(process.env.GRIDEX_CONTACT_TEST_PASSWORD)
  await page.getByRole('button', { name: 'Logga in' }).click()
  await page.waitForURL((url) => !url.pathname.startsWith('/login'))
}

test('real customer editor preserves and cancels a draft; dirty link navigation is explicitly declined', async ({ page }, testInfo) => {
  await login(page, fixture.writerEmail)
  await page.goto(card(fixture.customerA))
  const form = contactForm(page)
  await page.locator(`article:has(form input[name="id"][value="${fixture.contactA}"])`).getByText('Redigera kontakt').click()
  const originalPhone = await form.locator('input[name="phone"]').inputValue()
  const originalRevision = await form.locator('input[name="expected_revision"]').inputValue()
  await form.locator('input[name="phone"]').fill('+46700000001')
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('link', { name: 'Översikt', exact: true }).last().click()
  await expect(page).toHaveURL(new RegExp(`customers/${fixture.customerA}\\?tab=profile`))
  await expect(form.locator('input[name="phone"]')).toHaveValue('+46700000001')
  await form.getByRole('button', { name: 'Avbryt', exact: true }).click()
  await expect(form.locator('input[name="phone"]')).toHaveValue(originalPhone)
  await expect(form.locator('input[name="expected_revision"]')).toHaveValue(originalRevision)
  await page.getByRole('link', { name: 'Översikt', exact: true }).last().click()
  await expect(page).toHaveURL(new RegExp(`customers/${fixture.customerA}\\?tab=overview`))
  await page.reload()
  await page.getByRole('link', { name: 'Ändra uppgifter', exact: true }).click()
  await expect(contactForm(page).locator('input[name="phone"]')).toHaveValue(originalPhone)
  await page.locator(`article:has(form input[name="id"][value="${fixture.contactA}"])`).getByText('Redigera kontakt').click()
  await contactForm(page).locator('input[name="phone"]').fill('+46700000009')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('link', { name: 'Översikt', exact: true }).last().click()
  await expect(page).toHaveURL(new RegExp(`customers/${fixture.customerA}\\?tab=overview`))
  await page.goBack()
  await expect(contactForm(page).locator('input[name="phone"]')).toHaveValue(originalPhone)
  await expect(contactForm(page).getByRole('status').filter({ hasText: 'Osparat utkast' })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('tenantservice-contact-draft-cancel.png'), fullPage: true })
  await assertCleanRuntime(page, testInfo)
})

test('mobile and a 640 CSS-pixel layout expose keyboard navigation and read-only controls', async ({ browser }, testInfo) => {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
  await login(page, fixture.readerEmail)
  await page.goto(card(fixture.customerA))
  await expect(contactForm(page)).toHaveCount(0)
  await expect(page.getByText('Läsläge – du saknar rättighet att ändra juridisk profil.')).toBeVisible()
  await page.getByText('Navigation och arbetsyta', { exact: true }).focus()
  await page.keyboard.press('Enter')
  const navigation = page.getByRole('navigation', { name: 'Tenantnavigation' }).last()
  await expect(navigation).toBeVisible()
  await navigation.getByRole('link', { name: /Kunder/ }).first().focus()
  await expect(navigation.getByRole('link', { name: /Kunder/ }).first()).toBeFocused()
  await expect(navigation.locator('a[href^="/admin/platform"],a[href^="/admin/ediel"]')).toHaveCount(0)
  await page.getByText('Navigation och arbetsyta', { exact: true }).click()
  await page.setViewportSize({ width: 640, height: 900 })
  // A 1280 CSS-pixel desktop at 200% zoom has a 640 CSS-pixel layout viewport.
  await expect(page.getByRole('link', { name: 'Visa uppgifter', exact: true })).toBeVisible()
  await expect(page.getByText('Navigation och arbetsyta', { exact: true })).toBeVisible()
  await expect(page.getByRole('main')).toContainText('Kundnummer')
  expect(await page.evaluate(() => document.body.scrollWidth > innerWidth + 1)).toBe(false)
  await page.screenshot({ path: testInfo.outputPath('tenantservice-mobile-readonly-640-css-pixels.png'), fullPage: true })
  await assertCleanRuntime(page, testInfo)
  await page.close()
})

test('browser back and forward restore only the same resource draft; cancel clears it without changing saved contact', async ({ page }, testInfo) => {
  await login(page, fixture.writerEmail)
  await page.goto(`/admin/customers/${fixture.customerA}?tab=overview`)
  await page.getByRole('link', { name: 'Ändra uppgifter', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`customers/${fixture.customerA}\\?tab=profile`))
  const form = contactForm(page)
  await page.locator(`article:has(form input[name="id"][value="${fixture.contactA}"])`).getByText('Redigera kontakt').click()
  const originalPhone = await form.locator('input[name="phone"]').inputValue()
  const originalRevision = await form.locator('input[name="expected_revision"]').inputValue()
  await form.locator('input[name="phone"]').fill('+46700000002')
  await page.goBack()
  await expect(page).toHaveURL(new RegExp(`customers/${fixture.customerA}\\?tab=overview`))
  await expect(contactForm(page)).toHaveCount(0)
  await page.goForward()
  await expect(page).toHaveURL(new RegExp(`customers/${fixture.customerA}\\?tab=profile`))
  await page.locator(`article:has(form input[name="id"][value="${fixture.contactA}"])`).getByText('Redigera kontakt').click()
  await expect(contactForm(page).locator('input[name="phone"]')).toHaveValue('+46700000002')
  await expect(contactForm(page).locator('input[name="expected_revision"]')).toHaveValue(originalRevision)
  await expect(contactForm(page).getByRole('status')).toContainText('Osparat utkast återställt')
  await contactForm(page).getByRole('button', { name: 'Avbryt', exact: true }).click()
  await expect(contactForm(page).locator('input[name="phone"]')).toHaveValue(originalPhone)
  await page.reload()
  await expect(contactForm(page).locator('input[name="phone"]')).toHaveValue(originalPhone)
  await expect(contactForm(page).locator('input[name="expected_revision"]')).toHaveValue(originalRevision)
  await page.screenshot({ path: testInfo.outputPath('tenantservice-browser-history-draft-cancel.png'), fullPage: true })
  await assertCleanRuntime(page, testInfo)
})

test('native invalid contact email preserves the entered draft and never submits a command', async ({ page }, testInfo) => {
  await login(page, fixture.writerEmail)
  await page.goto(card(fixture.customerA))
  await page.locator(`article:has(form input[name="id"][value="${fixture.contactA}"])`).getByText('Redigera kontakt').click()
  const form = contactForm(page)
  const originalPhone = await form.locator('input[name="phone"]').inputValue()
  const revision = await form.locator('input[name="expected_revision"]').inputValue()
  await form.locator('input[name="email"]').fill('invalid-email')
  await form.getByRole('button', { name: 'Spara kontakt', exact: true }).click()
  expect(await form.locator('input[name="email"]').evaluate((input) => input.validity.typeMismatch)).toBe(true)
  await expect(form.locator('input[name="email"]')).toBeFocused()
  await expect(form.locator('input[name="email"]')).toHaveValue('invalid-email')
  await expect(form.locator('input[name="phone"]')).toHaveValue(originalPhone)
  expect(runtimeEvidence.get(page).actionPosts).toEqual([])
  await form.getByRole('button', { name: 'Avbryt', exact: true }).click()
  await page.reload()
  await expect(contactForm(page).locator('input[name="expected_revision"]')).toHaveValue(revision)
  await page.screenshot({ path: testInfo.outputPath('tenantservice-contact-validation-draft.png'), fullPage: true })
  await assertCleanRuntime(page, testInfo)
})

test('two real staff sessions preserve the stale draft while a double-clicked winner persists one contact revision', async ({ browser }, testInfo) => {
  test.skip(!fixture.customerUi || !fixture.contactUi, 'Requires dedicated synthetic UI resources so retained contact/API postchecks stay isolated.')
  const winner = await browser.newPage()
  const stale = await browser.newPage()
  try {
    for (const page of [winner, stale]) {
      await login(page, fixture.writerEmail)
      await page.goto(card(fixture.customerUi))
      await page.locator(`article:has(form input[name="id"][value="${fixture.contactUi}"])`).getByText('Redigera kontakt').click()
    }
    const winnerForm = uiContactForm(winner)
    const staleForm = uiContactForm(stale)
    const revision = Number(await winnerForm.locator('input[name="expected_revision"]').inputValue())
    const email = await winnerForm.locator('input[name="email"]').inputValue()
    await staleForm.locator('input[name="phone"]').fill('+46700004444')
    await winnerForm.locator('input[name="phone"]').fill('+46700003333')
    await winnerForm.getByRole('button', { name: 'Spara kontakt', exact: true }).dblclick()
    await expect(winner.getByText(`Sparad kontaktrevision: ${revision + 1}`, { exact: true })).toBeVisible()
    expect(runtimeEvidence.get(winner).actionPosts).toHaveLength(1)
    await winner.reload()
    await expect(uiContactForm(winner).locator('input[name="phone"]')).toHaveValue('+46700003333')
    await expect(uiContactForm(winner).locator('input[name="email"]')).toHaveValue(email)
    await staleForm.getByRole('button', { name: 'Spara kontakt', exact: true }).click()
    await expect(staleForm.getByRole('alert')).toContainText('Ditt utkast är kvar')
    await expect(staleForm.getByRole('alert')).toBeFocused()
    await expect(staleForm.locator('input[name="phone"]')).toHaveValue('+46700004444')
    await expect(staleForm.locator('input[name="expected_revision"]')).toHaveValue(String(revision))
    await expect(staleForm.getByRole('button', { name: 'Spara kontakt', exact: true })).toBeDisabled()
    await staleForm.getByRole('button', { name: 'Läs in sparade uppgifter', exact: true }).click()
    await expect(stale.getByText(`Sparad kontaktrevision: ${revision + 1}`, { exact: true })).toBeVisible()
    await expect(uiContactForm(stale).locator('input[name="phone"]')).toHaveValue('+46700004444')
    await expect(uiContactForm(stale).getByRole('button', { name: 'Spara kontakt', exact: true })).toBeDisabled()
    await uiContactForm(stale).getByRole('button', { name: 'Avbryt', exact: true }).click()
    await stale.reload()
    await expect(uiContactForm(stale).locator('input[name="phone"]')).toHaveValue('+46700003333')
    await expect(uiContactForm(stale).locator('input[name="expected_revision"]')).toHaveValue(String(revision + 1))
    await stale.screenshot({ path: testInfo.outputPath('tenantservice-ui-conflict-persisted.png'), fullPage: true })
    await assertCleanRuntime(winner, testInfo)
    await assertCleanRuntime(stale, testInfo)
  } finally {
    await winner.close()
    await stale.close()
  }
})

test('billing standard uses the real editor and persists separately from primary contact after reload', async ({ page }, testInfo) => {
  test.skip(!fixture.customerUi || !fixture.contactUi, 'Requires dedicated synthetic UI customer.')
  await login(page, fixture.writerEmail)
  await page.goto(`/admin/customers/${fixture.customerUi}?tab=billing-metering`)
  const form = page.locator('form:has(button:text-is("Spara faktureringsstandard"))')
  const revision = Number(await form.locator('input[name="expected_revision"]').inputValue())
  await form.locator('input[name="recipient"]').fill('Synthetic UI Billing')
  await form.locator('select[name="distributionMethod"]').selectOption('email')
  await form.locator('input[name="email"]').fill('ui-invoice@example.invalid')
  await form.getByRole('button', { name: 'Spara faktureringsstandard', exact: true }).click()
  await expect(page.getByText(`Profilrevision: ${revision + 1}. Kontaktmejl och inloggning ändras separat.`, { exact: true })).toBeVisible()
  await page.reload()
  await expect(form.locator('input[name="recipient"]')).toHaveValue('Synthetic UI Billing')
  await expect(form.locator('input[name="email"]')).toHaveValue('ui-invoice@example.invalid')
  await expect(form.locator('input[name="expected_revision"]')).toHaveValue(String(revision + 1))
  await page.screenshot({ path: testInfo.outputPath('tenantservice-billing-standard-persisted.png'), fullPage: true })
  await page.goto(card(fixture.customerUi))
  await expect(uiContactForm(page).locator('input[name="email"]')).toHaveValue('ui-before@example.invalid')
  await expect(uiContactForm(page).locator('input[name="phone"]')).toHaveValue('+46700003333')
  await assertCleanRuntime(page, testInfo)
})

test('a separate authorized legal editor saves only the legal profile through the real form', async ({ page }, testInfo) => {
  test.skip(!fixture.customerUi || !fixture.legalEditorEmail, 'Requires separately authorized synthetic customers.write actor.')
  await login(page, fixture.legalEditorEmail)
  await page.goto(card(fixture.customerUi))
  const form = page.locator('form:has(input[name="expected_legal_profile_revision"])')
  const revision = Number(await form.locator('input[name="expected_legal_profile_revision"]').inputValue())
  await form.locator('input[name="first_name"]').fill('UiPersisted')
  await form.getByRole('button', { name: 'Spara kundprofil', exact: true }).click()
  await expect(page.getByText(`Juridisk profilrevision: ${revision + 1}.`, { exact: true })).toBeVisible()
  await page.reload()
  await expect(form.locator('input[name="first_name"]')).toHaveValue('UiPersisted')
  await expect(form.locator('input[name="expected_legal_profile_revision"]')).toHaveValue(String(revision + 1))
  await expect(page.getByText('E-post: ui-before@example.invalid', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Telefon: +46700003333', { exact: true }).first()).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('tenantservice-legal-profile-persisted.png'), fullPage: true })
  await assertCleanRuntime(page, testInfo)
})

test('the address book saves one insertion, preserves a competing draft and confirms an edit after reload', async ({ browser }, testInfo) => {
  test.skip(!fixture.customerUi, 'Requires the independent synthetic UI customer.')
  const winner = await browser.newPage()
  const stale = await browser.newPage()
  const createForm = (page) => page.locator('form:has(input[name="expected_address_revision"]):has(input[name="id"][value=""])')
  try {
    for (const page of [winner, stale]) {
      await login(page, fixture.writerEmail)
      await page.goto(card(fixture.customerUi))
      await page.getByText('Lägg till ny adress', { exact: true }).click()
    }
    const revision = Number(await createForm(winner).locator('input[name="expected_address_revision"]').inputValue())
    await createForm(winner).locator('select[name="type"]').selectOption('registered')
    await createForm(winner).locator('input[name="street_1"]').fill('Synthetic UI Street 1')
    await createForm(winner).locator('input[name="postal_code"]').fill('11122')
    await createForm(winner).locator('input[name="city"]').fill('Synthetic City')
    await createForm(stale).locator('input[name="street_1"]').fill('Unsaved Competing Street')
    await createForm(winner).getByRole('button', { name: 'Lägg till adress', exact: true }).dblclick()
    await expect(winner.getByText(`Sparad adressrevision: ${revision + 1}`, { exact: true })).toBeVisible()
    expect(runtimeEvidence.get(winner).actionPosts).toHaveLength(1)
    await winner.reload()
    const editForm = winner.locator('form:has(input[name="expected_address_revision"]):has(button:text-is("Spara adress"))')
    await expect(editForm).toHaveCount(1)
    await expect(editForm.locator('input[name="street_1"]')).toHaveValue('Synthetic UI Street 1')
    await createForm(stale).getByRole('button', { name: 'Lägg till adress', exact: true }).click()
    await expect(createForm(stale).getByRole('alert')).toContainText('Ditt utkast är kvar')
    await expect(createForm(stale).locator('input[name="street_1"]')).toHaveValue('Unsaved Competing Street')
    await expect(createForm(stale).getByRole('button', { name: 'Lägg till adress', exact: true })).toBeDisabled()
    await createForm(stale).getByRole('button', { name: 'Avbryt', exact: true }).click()
    await stale.reload()
    await expect(stale.locator('form:has(input[name="expected_address_revision"]):has(button:text-is("Spara adress"))')).toHaveCount(1)
    await winner.getByText('Redigera adress', { exact: true }).click()
    await editForm.locator('input[name="city"]').fill('Updated Synthetic City')
    await editForm.getByRole('button', { name: 'Spara adress', exact: true }).click()
    await expect(winner.getByText(`Sparad adressrevision: ${revision + 2}`, { exact: true })).toBeVisible()
    await winner.reload()
    await expect(editForm.locator('input[name="city"]')).toHaveValue('Updated Synthetic City')
    await expect(uiContactForm(winner).locator('input[name="phone"]')).toHaveValue('+46700003333')
    await winner.screenshot({ path: testInfo.outputPath('tenantservice-address-book-persisted.png'), fullPage: true })
    await assertCleanRuntime(winner, testInfo)
    await assertCleanRuntime(stale, testInfo)
  } finally {
    await winner.close()
    await stale.close()
  }
})

test('logout warns about a real dirty draft and a fresh session reads the saved contact', async ({ page }, testInfo) => {
  await login(page, fixture.writerEmail)
  await page.goto(card(fixture.customerA))
  await page.locator(`article:has(form input[name="id"][value="${fixture.contactA}"])`).getByText('Redigera kontakt').click()
  const originalPhone = await contactForm(page).locator('input[name="phone"]').inputValue()
  const originalRevision = await contactForm(page).locator('input[name="expected_revision"]').inputValue()
  await contactForm(page).locator('input[name="phone"]').fill('+46700009999')
  page.once('dialog', async (dialog) => {
    expect(dialog.message()).toContain('osparade ändringar')
    await dialog.dismiss()
  })
  await page.getByRole('button', { name: 'Logga ut', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`customers/${fixture.customerA}\\?tab=profile`))
  await expect(contactForm(page).locator('input[name="phone"]')).toHaveValue('+46700009999')
  expect(runtimeEvidence.get(page).actionPosts).toHaveLength(0)
  page.once('dialog', async (dialog) => { await dialog.accept() })
  await page.getByRole('button', { name: 'Logga ut', exact: true }).click()
  await expect(page).toHaveURL(/\/login(?:\?|$)/)
  await login(page, fixture.writerEmail)
  await page.goto(card(fixture.customerA))
  await expect(contactForm(page).locator('input[name="phone"]')).toHaveValue(originalPhone)
  await expect(contactForm(page).locator('input[name="expected_revision"]')).toHaveValue(originalRevision)
  await expect(contactForm(page).getByRole('status')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('tenantservice-logout-draft-discard.png'), fullPage: true })
  await assertCleanRuntime(page, testInfo)
})

test('actual Chromium browser zoom is 200 percent and customer controls remain accessible after reload', async ({}, testInfo) => {
  // Official browser-level API, not CSS zoom, pinch emulation or deviceScaleFactor:
  // https://developer.chrome.com/docs/extensions/reference/api/tabs#method-setZoom
  // https://playwright.dev/docs/chrome-extensions
  const temporary = mkdtempSync(join(tmpdir(), 'gridex-ui-zoom-'))
  const extension = join(temporary, 'extension')
  mkdirSync(extension)
  writeFileSync(join(extension, 'manifest.json'), JSON.stringify({
    manifest_version: 3, name: 'Disposable local Gridex zoom proof', version: '1.0',
    host_permissions: ['http://127.0.0.1/*'],
    background: { service_worker: 'worker.js' },
  }))
  writeFileSync(join(extension, 'worker.js'), 'chrome.runtime.onInstalled.addListener(() => {});')
  let context
  try {
    context = await chromium.launchPersistentContext(join(temporary, 'profile'), {
      channel: 'chromium', headless: true, baseURL: 'http://127.0.0.1:3000',
      viewport: { width: 1280, height: 900 },
      args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
    })
    const [initialWorker] = context.serviceWorkers()
    const worker = initialWorker ?? await context.waitForEvent('serviceworker')
    const page = await context.newPage()
    await login(page, fixture.readerEmail)
    await page.goto(card(fixture.customerA))
    const before = await page.evaluate(() => ({ width: innerWidth, dpr: devicePixelRatio, visualScale: visualViewport.scale }))
    const zoom = await worker.evaluate(async (url) => {
      const tabs = await chrome.tabs.query({ url })
      if (tabs.length !== 1 || !Number.isInteger(tabs[0].id)) throw new Error('local_zoom_tab_ambiguous')
      await chrome.tabs.setZoom(tabs[0].id, 2)
      return { tabId: tabs[0].id, factor: await chrome.tabs.getZoom(tabs[0].id) }
    }, page.url())
    expect(zoom.factor).toBe(2)
    await expect.poll(() => page.evaluate(() => devicePixelRatio)).toBeCloseTo(before.dpr * 2, 4)
    const after = await page.evaluate(() => ({ width: innerWidth, dpr: devicePixelRatio, visualScale: visualViewport.scale, bodyOverflow: document.body.scrollWidth > innerWidth + 1 }))
    expect(after.width).toBeLessThanOrEqual(before.width / 2 + 1)
    expect(after.visualScale).toBe(before.visualScale)
    expect(after.bodyOverflow).toBe(false)
    await expect(page.getByRole('link', { name: 'Visa uppgifter', exact: true })).toBeVisible()
    await page.getByText('Navigation och arbetsyta', { exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('navigation', { name: 'Tenantnavigation' }).last()).toBeVisible()
    await page.getByText('Navigation och arbetsyta', { exact: true }).click()
    await page.reload()
    expect(await worker.evaluate((tabId) => chrome.tabs.getZoom(tabId), zoom.tabId)).toBe(2)
    await expect(page.getByRole('link', { name: 'Visa uppgifter', exact: true })).toBeVisible()
    await expect(contactForm(page)).toHaveCount(0)
    await page.screenshot({ path: testInfo.outputPath('tenantservice-actual-browser-zoom-200-percent.png'), fullPage: true })
    await testInfo.attach('actual-browser-zoom', { body: JSON.stringify({ browser: 'bundled Chromium', api: 'chrome.tabs.setZoom/getZoom', zoomFactor: zoom.factor, before, after }), contentType: 'application/json' })
    await assertCleanRuntime(page, testInfo)
  } finally {
    await context?.close()
    rmSync(temporary, { recursive: true, force: true })
  }
})
