import { beforeEach, describe, expect, it, vi } from 'vitest';
const s = vi.hoisted(() => ({ access: vi.fn(), scope: vi.fn(), createInfo: vi.fn(), createScope: vi.fn(), createPermission: vi.fn(), queueInfo: vi.fn(), queuePermission: vi.fn(), snapshot: vi.fn(), manualSent: vi.fn(), complete: vi.fn(), selectProvider: vi.fn(), enableProvider: vi.fn(), revalidate: vi.fn(), platform: false, requestCompany: 'company-a', user: 'actor-a' }));
vi.mock('next/cache', () => ({ revalidatePath: s.revalidate }));
vi.mock('next/navigation', () => ({ redirect: (url: string) => { throw new Error('redirect:' + url); }, unstable_rethrow: () => { } }));
vi.mock('@/lib/admin/guards', () => ({ requireAdminActionAccess: s.access, isPlatformAdminContext: () => s.platform }));
vi.mock('@/lib/supabase/server', () => ({ createSupabaseServerClient: async () => ({ auth: { getUser: async () => ({ data: { user: s.user ? { id: s.user } : null } }) } }) }));
vi.mock('@/lib/supabase/service', () => ({ supabaseService: { from: () => ({ select: () => ({ eq: () => ({ maybeSingle: async () => ({ data: { company_id: s.requestCompany }, error: null }) }) }) }) } }));
vi.mock('@/lib/tenant/scope', () => ({ requireOperationalCompanyId: s.scope, getOperationalCompanyScope: async () => ({ companyId: await s.scope() }) }));
vi.mock('@/lib/onboarding/infoRequests', () => ({ createCustomerInfoRequest: s.createInfo, createAuthorizationScope: s.createScope, createMeteringPermissionDraft: s.createPermission, queueCustomerInfoRequestForDispatch: s.queueInfo, queueMeteringPermissionForZ13: s.queuePermission, applyZ14SnapshotToMeteringPermission: s.snapshot }));
vi.mock('@/lib/ediel/services/manualPermission', () => ({ parseManualServiceAssignmentSelection: (v: string | null) => ({ selection: v }) }));
vi.mock('@/lib/facility/facilityLookupWorkflow', () => ({ markFacilityLookupSentManually: s.manualSent }));
vi.mock('@/lib/customer-operations/facilityResponseOrchestrator', () => ({ completeFacilityLookupAndRunNextSteps: s.complete }));
vi.mock('@/lib/billing/providers/registry', () => ({ InvoiceProviderConfigError: class extends Error {
    }, selectTenantInvoiceProvider: s.selectProvider, setTenantInvoiceDispatchEnabled: s.enableProvider }));
vi.mock('@/lib/audit/actionLogger', () => ({}));
vi.mock('@/lib/billing/providerEventProcessor', () => ({}));
vi.mock('@/lib/integrations/billing/capway/auth', () => ({}));
vi.mock('@/lib/integrations/billing/capway/client', () => ({}));
import { createAuthorizationScopeAction, createCustomerInfoRequestAction, createMeteringPermissionDraftAction, queueCustomerInfoRequestAction, queueMeteringPermissionZ13Action, applyZ14SnapshotAction } from '@/app/admin/customer-info-requests/actions';
import { completeFacilityLookupAction, markFacilityLookupSentManuallyAction } from '@/app/admin/facility-requests/actions';
import { selectInvoiceProviderAction, setInvoiceDispatchEnabledAction } from '@/app/admin/billing/integrations/actions';
const form = (v: Record<string, string | string[]>) => { const f = new FormData(); for (const [k, x] of Object.entries(v))
    for (const value of Array.isArray(x) ? x : [x])
        f.append(k, value); return f; };
beforeEach(() => { vi.resetAllMocks(); s.platform = false; s.requestCompany = 'company-a'; s.user = 'actor-a'; s.access.mockResolvedValue({ userId: 'actor-a' }); s.scope.mockResolvedValue('company-a'); });
describe('information request buttons', () => {
    it('binds creation to the authenticated actor/company and retains repeated categories', async () => { await createCustomerInfoRequestAction(form({ customer_id: 'customer-a', company_id: 'company-forged', actor_user_id: 'forged', requested_data_categories: ['customer_masterdata', 'metering_data'], notes: '  Notering  ' })); expect(s.createInfo).toHaveBeenCalledWith(expect.objectContaining({ companyId: 'company-a', actorUserId: 'actor-a', customerId: 'customer-a', requestedDataCategories: ['customer_masterdata', 'metering_data'], notes: 'Notering' })); });
    it('preserves authorization checkboxes and validity dates', async () => { await createAuthorizationScopeAction(form({ customer_id: 'customer-a', covers_grid_owner_data: 'on', covers_metering_data: 'on', valid_from: '2026-10-05' })); expect(s.createScope).toHaveBeenCalledWith(expect.objectContaining({ companyId: 'company-a', coversGridOwnerData: true, coversCurrentSupplierContract: false, coversMeteringData: true, validFrom: '2026-10-05' })); });
    it('keeps an unconfirmed authorization as a blocker on metering permission drafts', async () => { await createMeteringPermissionDraftAction(form({ customer_id: 'customer-a' })); expect(s.createPermission).toHaveBeenCalledWith(expect.objectContaining({ lastBlocker: expect.stringContaining('Fullmakt/avtal') })); });
    it('clears only the draft blocker when authorization is confirmed', async () => { await createMeteringPermissionDraftAction(form({ customer_id: 'customer-a', authorization_confirmed: 'on' })); expect(s.createPermission).toHaveBeenCalledWith(expect.objectContaining({ lastBlocker: null })); });
    it('queues information requests in the selected company and refreshes affected views', async () => { await queueCustomerInfoRequestAction(form({ request_id: 'request-a' })); expect(s.queueInfo).toHaveBeenCalledWith({ companyId: 'company-a', actorUserId: 'actor-a', requestId: 'request-a' }); expect(s.revalidate).toHaveBeenCalledWith('/admin/outbound'); });
    it('passes the selected service assignment to Z13 preparation', async () => { await queueMeteringPermissionZ13Action(form({ permission_id: 'permission-a', service_assignment_selection: 'assignment-a' })); expect(s.queuePermission).toHaveBeenCalledWith(expect.objectContaining({ companyId: 'company-a', permissionId: 'permission-a', selection: 'assignment-a' })); });
    it('binds snapshot application to company, permission and selected source', async () => { await applyZ14SnapshotAction(form({ permission_id: 'permission-a', source_message_id: 'message-a' })); expect(s.snapshot).toHaveBeenCalledWith({ companyId: 'company-a', actorUserId: 'actor-a', permissionId: 'permission-a', sourceMessageId: 'message-a' }); });
    it.each([createCustomerInfoRequestAction, createAuthorizationScopeAction, createMeteringPermissionDraftAction])('rejects a missing customer before domain writes', async (action) => { await expect(action(new FormData())).rejects.toThrow('Välj kund'); expect(s.createInfo).not.toHaveBeenCalled(); expect(s.createScope).not.toHaveBeenCalled(); expect(s.createPermission).not.toHaveBeenCalled(); });
    it('rejects a missing authenticated actor before writes', async () => { s.user = ''; await expect(createCustomerInfoRequestAction(form({ customer_id: 'customer-a' }))).rejects.toThrow('inloggad'); expect(s.createInfo).not.toHaveBeenCalled(); });
});
describe('facility request buttons', () => {
    it('rejects a request owned by another company before sending or completion', async () => { s.requestCompany = 'company-b'; await expect(markFacilityLookupSentManuallyAction(form({ request_id: 'request-b' }))).rejects.toThrow('saknar åtkomst'); await expect(completeFacilityLookupAction(form({ request_id: 'request-b' }))).rejects.toThrow('saknar åtkomst'); expect(s.manualSent).not.toHaveBeenCalled(); expect(s.complete).not.toHaveBeenCalled(); });
    it('uses the stored request company for platform administrators', async () => { s.platform = true; s.requestCompany = 'company-b'; await markFacilityLookupSentManuallyAction(form({ request_id: 'request-b', company_id: 'company-forged', manual_channel: 'phone', note: '  Ringde  ' })); expect(s.manualSent).toHaveBeenCalledWith({ companyId: 'company-b', requestId: 'request-b', actorUserId: 'actor-a', manualChannel: 'phone', note: 'Ringde' }); });
    it('maps invalid manual channels to other', async () => { await markFacilityLookupSentManuallyAction(form({ request_id: 'request-a', manual_channel: 'invalid' })); expect(s.manualSent).toHaveBeenCalledWith(expect.objectContaining({ manualChannel: 'other' })); });
    it('passes the entered facility response through the canonical orchestrator', async () => { await completeFacilityLookupAction(form({ request_id: 'request-a', facility_id: 'facility-a', metering_point_id: 'point-a', grid_area_code: 'NET', price_area_code: 'SE3' })); expect(s.complete).toHaveBeenCalledWith(expect.objectContaining({ companyId: 'company-a', actorUserId: 'actor-a', source: 'manual', facilityId: 'facility-a', meteringPointId: 'point-a', priceAreaCode: 'SE3' })); });
});
describe('billing provider buttons', () => {
    it('uses the selected company and actor and redirects after provider selection', async () => { await expect(selectInvoiceProviderAction(form({ company_id: 'company-forged', provider: 'file_export', environment: 'test' }))).rejects.toThrow('redirect:/admin/billing/integrations?provider=selected'); expect(s.selectProvider).toHaveBeenCalledWith({ companyId: 'company-a', provider: 'file_export', environment: 'test', actorUserId: 'actor-a' }); });
    it('uses the explicit enabled flag and refreshes the integration view', async () => { await expect(setInvoiceDispatchEnabledAction(form({ enabled: 'false' }))).rejects.toThrow('provider=disabled'); expect(s.enableProvider).toHaveBeenCalledWith({ companyId: 'company-a', enabled: false, actorUserId: 'actor-a' }); expect(s.revalidate).toHaveBeenCalledWith('/admin/billing/integrations'); });
    it('requires a selected company before provider changes', async () => { s.scope.mockResolvedValue(null); await expect(selectInvoiceProviderAction(form({ provider: 'capway_aptic' }))).rejects.toThrow('Välj ett elhandelsbolag'); expect(s.selectProvider).not.toHaveBeenCalled(); });
});
