import {beforeEach,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
import {runUtiltsRuntimeForMessage,takeUtiltsRuntimeOwner} from '@/lib/ediel/utiltsEngine'
import {resolveCanonicalMessagePolicy} from '@/lib/ediel/core/messagePolicy'
import {readUtiltsIssuerIdentityAuthority} from '@/lib/ediel/utilts/issuerIdentityAuthority'
import {utiltsErrGatewayFixture} from './helpers/utiltsErrGatewayFixture'
const io=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:io.rpc}}))
function setup(){const message=utiltsErrGatewayFixture({company:'22222222-2222-4222-8222-222222222222',transactions:[{reference:'OWN',outcome:'accepted'},{reference:'SIBLING',outcome:'accepted'}]});message.id='11111111-1111-4111-8111-111111111111';return {message,policy:resolveCanonicalMessagePolicy(message)!}}
function reply(input:ReturnType<typeof setup>,extra={}){return {data:{version:1,companyId:input.message.company_id,environment:input.message.environment,sourceMessageId:input.message.id,sourcePayloadHash:createHash('sha256').update(input.message.raw_payload!).digest('hex'),status:'qualified',authorityVersionId:'33333333-3333-4333-8333-333333333333',namespaceEpoch:'2',messageReferenceCollision:false,transactionReferenceCollisions:[],holdReason:null,...extra},error:null}}
beforeEach(()=>vi.clearAllMocks())
it('a proven issuer BGM203 collision is a header42/noACW before every functional check',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{messageReferenceCollision:true}));const token=await readUtiltsIssuerIdentityAuthority(input),runtime=runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token});expect(runtime.transactionDispositions.every(tx=>tx.disposition==='guide_rejected')).toBe(true);expect(runtime.ackPlan.utiltsHeaderRejection?.applicationErrors).toEqual([expect.objectContaining({ercCode:'42',fieldCode:'203',text:expect.stringMatching(/^INCORRECT DATA .+/)})]);expect(runtime.validation.issues.filter(i=>i.severity==='error'&&i.kind==='functional')).toEqual([]);expect(runtime.ackPlan.shouldSendUtiltsErr).toBe(false)})
it('a proven issuer505 collision remains in its physical ownIDE scope, leaving sibling national scope independent',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{transactionReferenceCollisions:[{transactionIndex:0,transactionId:'OWN'}]}));const token=await readUtiltsIssuerIdentityAuthority(input),runtime=runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token});expect(runtime.transactionDispositions[0]).toMatchObject({transactionId:'OWN',disposition:'guide_rejected',responseType:'negative_aperak'});expect(runtime.transactionDispositions[1].disposition).not.toBe('guide_rejected');expect(runtime.ackPlan.aperakApplicationErrors).toEqual([expect.objectContaining({ercCode:'42',fieldCode:'505',referenceNumber:'OWN',text:'INCORRECT DATA OWN'})]);expect(runtime.ackPlan.utiltsHeaderRejection).toBeUndefined()})
it('missing issuer/history/retention proof holds eligibleIDE locally without a national code or positive response',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{status:'held',authorityVersionId:null,namespaceEpoch:null,holdReason:'ediel_utilts_identity_history_coverage_unavailable'}));const token=await readUtiltsIssuerIdentityAuthority(input),runtime=runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token});expect(runtime.transactionDispositions.every(tx=>tx.disposition==='internal_review'&&tx.responseType==='none')).toBe(true);expect(runtime.ackPlan.shouldSendAperak).toBe(false);expect(runtime.ackPlan.shouldSendUtiltsErr).toBe(false);expect(runtime.validation.issues.filter(i=>i.code==='UTILTS_ISSUER_IDENTITY_BASIS_UNAVAILABLE').every(i=>!i.aperakErcCode&&!i.utiltsErrCode)).toBe(true)})
it('keeps known own505negative while missing full historical coverage holds only the eligible sibling',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{status:'held',holdReason:'ediel_utilts_identity_history_coverage_unavailable',transactionReferenceCollisions:[{transactionIndex:0,transactionId:'OWN'}]}));const token=await readUtiltsIssuerIdentityAuthority(input),runtime=runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token});expect(runtime.transactionDispositions.map(tx=>tx.disposition)).toEqual(['guide_rejected','internal_review']);expect(runtime.ackPlan.aperakOutcome).toBe('negative')})
it('does not allow a token-free or copied-token final owner to authorize this actual runtime',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input));const token=await readUtiltsIssuerIdentityAuthority(input),runtime=runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token});expect(takeUtiltsRuntimeOwner(runtime,input.message,input.policy)).toBeNull();const genuine=runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token});expect(takeUtiltsRuntimeOwner(genuine,input.message,input.policy,token)).not.toBeNull()})
it('guideOnly remains observation and physical syntax rejection precedes namespace findings',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{messageReferenceCollision:true}));const token=await readUtiltsIssuerIdentityAuthority(input);expect(runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token,guideOnly:true}).validation.issues.some(i=>i.code==='UTILTS_ISSUER_MESSAGE_REFERENCE_DUPLICATE')).toBe(false);const malformed={...input.message,raw_payload:input.message.raw_payload+'FTX+AAI+++dangling?'};const runtime=runUtiltsRuntimeForMessage(malformed,{canonicalPolicy:input.policy,issuerIdentityAuthority:token});expect(runtime.validation.classification).toBe('syntax_rejected');expect(runtime.ackPlan.contrlOutcome).toBe('negative');expect(runtime.ackPlan.shouldSendAperak).toBe(false)})

it('keeps every earlier physical header error and stops505 after header203 rejects the message',async()=>{
 const input=setup();input.message.raw_payload=input.message.raw_payload!.replace('BGM+E66::260','BGM+E66::9');input.policy=resolveCanonicalMessagePolicy(input.message)!
 io.rpc.mockResolvedValue(reply(input,{messageReferenceCollision:true,transactionReferenceCollisions:[{transactionIndex:0,transactionId:'OWN'}]}))
 const token=await readUtiltsIssuerIdentityAuthority(input),runtime=runUtiltsRuntimeForMessage(input.message,{canonicalPolicy:input.policy,issuerIdentityAuthority:token})
 expect(runtime.ackPlan.utiltsHeaderRejection?.applicationErrors.map(error=>error.fieldCode)).toEqual(expect.arrayContaining(['202','203']))
 expect(runtime.validation.issues.some(issue=>issue.code==='UTILTS_ISSUER_TRANSACTION_REFERENCE_DUPLICATE')).toBe(false)
 expect(runtime.transactionDispositions.every(own=>own.disposition==='guide_rejected')).toBe(true)
 expect(runtime.validation.issues.filter(i=>i.severity==='error'&&i.kind==='functional')).toEqual([])
})
