import {beforeEach,expect,it,vi} from 'vitest'
import {NextRequest} from 'next/server'
const port=vi.hoisted(()=>({access:vi.fn(),archive:vi.fn(),read:vi.fn(),bytes:vi.fn(),review:vi.fn()}))
vi.mock('@/lib/admin/apiGuards',()=>({requireAdminApiAccess:port.access}))
vi.mock('@/lib/ediel/production/aiPurposeSource',()=>({archiveAiPurposeSource:port.archive,readAiPurposeSourceArtifact:port.read,readAiPurposeSourceBytes:port.bytes,reviewAiPurposeSource:port.review}))
import {POST as archive} from '@/app/api/ediel/ai-purpose-sources/route'
import {GET as read} from '@/app/api/ediel/ai-purpose-sources/[artifactId]/route'
import {GET as bytes} from '@/app/api/ediel/ai-purpose-sources/[artifactId]/source/route'
import {POST as review} from '@/app/api/ediel/ai-purpose-sources/[artifactId]/review/route'
const companyId='00000000-0000-4000-8000-000000000001',userId='00000000-0000-4000-8000-000000000002',artifactId='00000000-0000-4000-8000-000000000003',hash='a'.repeat(64),ctx={params:Promise.resolve({artifactId})}
const input={environment:'test',listType:'AI',purpose:'ediel_list_export',gdprBasis:'SYNTHETIC declared legal basis',retentionDays:30,retentionUntil:'2026-12-01',validFrom:'2026-10-01T00:00:00Z',validUntil:'2026-11-01T00:00:00Z',source:{bytesBase64:Buffer.from('%PDF-1.7\nSYNTHETIC original').toString('base64'),mimeType:'application/pdf',reference:'original',version:'1'}}
const request=(data:unknown)=>new NextRequest('http://localhost/api/ediel/ai-purpose-sources',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)})
beforeEach(()=>{vi.clearAllMocks();port.access.mockResolvedValue({guard:{companyId,userId,permissions:[],roles:[]},response:null})})
it('archives bounded original against server company and current actor',async()=>{port.archive.mockResolvedValue({status:'archived',artifactId,sourceHash:hash,claimsHash:hash,missing:['authentic_current_purpose_issuer_and_representation']});expect((await archive(request(input))).status).toBe(201);expect(port.archive).toHaveBeenCalledWith({...input,companyId,actorUserId:userId});expect(port.access).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write']})})
it.each(['companyId','actorUserId','approved','verified','legalAuthority'])('rejects caller authority field %s',async key=>{expect((await archive(request({...input,[key]:true}))).status).toBe(400);expect(port.archive).not.toHaveBeenCalled()})
it('rejects BI export before the producer',async()=>{expect((await archive(request({...input,listType:'BI'}))).status).toBe(400);expect(port.archive).not.toHaveBeenCalled()})
it('requires authorization before metadata or document bytes',async()=>{port.access.mockResolvedValue({response:new Response('{}',{status:403})});expect((await read(new NextRequest('http://localhost'),ctx)).status).toBe(403);expect(port.read).not.toHaveBeenCalled();expect((await bytes(new NextRequest('http://localhost'),ctx)).status).toBe(403);expect(port.bytes).not.toHaveBeenCalled()})
it('returns held separately reviewed exact archived hashes',async()=>{port.review.mockResolvedValue({status:'held',artifactId,missing:['authentic_current_purpose_issuer_and_representation']});const command={sourceHash:hash,claimsHash:hash,decision:'approve',reason:'Independent review',clause:{locator:'page1',quote:'original'}};expect((await review(request(command),ctx)).status).toBe(409);expect(port.review).toHaveBeenCalledWith({...command,artifactId,companyId,actorUserId:userId});expect(port.access).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write','ediel.ai_purpose.review']})})
it('downloads private PDF attachment without public caching or sniffing',async()=>{port.bytes.mockResolvedValue({bytes:Buffer.from('%PDF-1.7'),mimeType:'application/pdf',sourceHash:hash});const response=await bytes(new NextRequest('http://localhost'),ctx);expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('private, no-store');expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(response.headers.get('content-disposition')).toContain('attachment');expect(port.bytes).toHaveBeenCalledWith({artifactId,companyId,actorUserId:userId})})
it('rejects oversized declared source before streaming/native',async()=>{const req=request(input);req.headers.set('content-length','12000000');expect((await archive(req)).status).toBe(413);expect(port.archive).not.toHaveBeenCalled()})
it('sanitizes native failure',async()=>{port.archive.mockRejectedValue(Error('PRIVATE SOURCE/ISSUER SECRET'));const response=await archive(request(input));expect(response.status).toBe(403);expect(await response.text()).not.toContain('PRIVATE')})
