import { it, expect } from 'vitest';
import { prepareTgtReportingNotes } from '@/lib/ediel/testing/tgtReportingPermissionNotes';
import { prodatEscoPermissionData } from '@/lib/ediel/testing/tgtTestData.part-3';
import { readTgtProdatSourceColumns } from '@/lib/ediel/testing/tgtProdatSource';
import { reportingId, reportingNow, reportingSource } from './fixtures/prodat-reporting-permission';
const selector = { workbook: 'TGT_PRODAT_Bilaga_1-Testdata_per_testkund_version_el_4-0-5.xlsx', sheet: 'Testkund 70 - 76 - ESCO', entityLabel: 'Testkund 73', columnName: 'Testdata - Z13VH', columnIndex: 2 };
function input(notes: string | null = null) { let n = 30; return { run: { id: reportingId(11), company_id: reportingId(10), role_code: 'esco' as const, test_case_code: '8.1.3', test_suite: 'PRODAT' as const, notes }, stepNo: 1, actorId: reportingId(12), source: { identity: reportingSource().source, data: prodatEscoPermissionData('8.1.3') }, route: reportingSource().route, clock: { nowUtcMs: () => reportingNow }, newId: () => reportingId(n++), command: { operation: 'save', resolution: 'retain', sourceNote: 'Original 8.1.3 synthetic assessment', objects: [{ selector, term: { kind: 'bounded_source', minuteOfDay: '0000' }, classification: 'nonprivate', classificationRationale: 'Original workbook business scenario8.1.3', purpose: { kind: 'assessed', code: 'B72', rationale: 'Test contract scenario8.1.3' } }] } }; }
it('original8.1.1 request has no209 and sender-chosen authorization reference', () => { const c = readTgtProdatSourceColumns(prodatEscoPermissionData('8.1.1'), 'Z13')[0]; expect(c.fields['209']).toBeUndefined(); expect(c.fields['261']).toBe('sätts av avsändaren'); });
it('server creates identityless scoped synthetic notes from original business scenario', () => { const notes = JSON.parse(prepareTgtReportingNotes(input())); const entry = notes.prodatReportingPermission.steps['1']; expect(entry.objects[0].object).toMatchObject({ code: 'Z13', installation: null, term: { kind: 'bounded', endMinute: '202608010000' }, classification: { kind: 'nonprivate' }, purpose: { kind: 'assessed', code: 'B72' } }); expect(entry.objects[0].object.li).toMatch(/^L[0-9a-f]{32}$/); expect(entry.objects[0].object.anj).toMatch(/^A[0-9a-f]{32}$/); });
it('rebuild/no-op save retains request identity and frozen month anchor', () => { const first = prepareTgtReportingNotes(input()); const again = input(first); again.clock.nowUtcMs = () => Date.parse('2026-10-20T11:00Z'); expect(prepareTgtReportingNotes(again)).toBe(first); });
it('explicit refresh updates revision/bound while retaining request key', () => { const first = JSON.parse(prepareTgtReportingNotes(input())); const next = input(JSON.stringify(first)); next.command.resolution = 'refresh'; next.clock.nowUtcMs = () => Date.parse('2026-10-20T11:00Z'); let n = 100; next.newId = () => reportingId(n++); const result = JSON.parse(prepareTgtReportingNotes(next)); const before = first.prodatReportingPermission.steps['1'], after = result.prodatReportingPermission.steps['1']; expect(after.factsRevision).not.toBe(before.factsRevision); expect(after.objects[0].object.requestKey).toBe(before.objects[0].object.requestKey); expect(after.objects[0].object.term.endMinute).toBe('202609010000'); });
it('clear leaves tombstone without active facts and preserves unrelated notes', () => { const first = prepareTgtReportingNotes({ ...input(), run: { ...input().run, notes: 'original operator text' } }); const base = input(first); const cleared = JSON.parse(prepareTgtReportingNotes({ ...base, command: { operation: 'clear', sourceNote: 'test revoked' } })); expect(cleared.text).toBe('original operator text'); expect(cleared.prodatReportingPermission.steps['1']).toMatchObject({ state: 'cleared' }); expect(cleared.prodatReportingPermission.steps['1']).not.toHaveProperty('objects'); });
for (const extra of ['actorId', 'source', 'route', 'clock', 'requestKey'])
    it(`operator cannot supply ${extra}`, () => expect(() => prepareTgtReportingNotes({ ...input(), command: { ...input().command, [extra]: 'forged' } })).toThrow());
it('unknown declarations remain readable during exact no-op saves', () => { const base = input(); const command = { ...base.command, objects: base.command.objects.map(o => ({ ...o, term: { kind: 'unknown' } })) }; const first = prepareTgtReportingNotes({ ...base, command }); expect(prepareTgtReportingNotes({ ...input(first), command })).toBe(first); });
it('no-op save evaluates historical end against the fresh server clock', () => { const first = prepareTgtReportingNotes(input()); const next = input(first); next.clock.nowUtcMs = () => Date.parse('2026-07-01T00:00Z'); expect(() => prepareTgtReportingNotes(next)).toThrow(); });
