import {beforeEach,describe,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
const io=vi.hoisted(()=>({rpc:vi.fn(),actor:vi.fn(),source:vi.fn()}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:io.rpc}}))
vi.mock('@/lib/ediel/services/authorization',()=>({assertEdielTenantActor:io.actor}))
vi.mock('@/lib/ediel/core/ackSourceRulePackEvidence',()=>({readSourceBoundOutboundAckRulePackEvidence:io.source}))
import {EdifactEnvelopeCodec} from '@/lib/ediel/core/edifactEnvelopeCodec'
import {readReceivedErrApplicationResponseAuthority,receivedErrApplicationResponseQualification} from '@/lib/ediel/ack/receivedErrApplicationResponseAuthority'
import type {EdielMessageRow} from '@/lib/ediel/types'
const uuid=(n:number)=>`00000000-0000-4000-8000-${n.toString().padStart(12,'0')}`
const raw=EdifactEnvelopeCodec.encode({sender:'REMOTE',receiver:'LOCAL',interchangeReference:'ERR-I',applicationReference:'23-DDQ-E66-T',environment:'test',acknowledgementRequest:true,messages:[{messageReference:'ERR-M',messageTypeToken:'UTILTS:D:02B:UN:E5SE5A',businessSegments:['BGM+ERR::260+ERR-D+9+AB','NAD+MS+52100:SVK:260','NAD+MR+52101:SVK:260','IDE+24+OWN?:A?+B??C','RFF+TN:ORIGINAL-T']}]})
const message={id:uuid(1),company_id:uuid(2),environment:'test',direction:'inbound',message_family:'UTILTS_ERR',message_standard:'edifact',raw_payload:raw} as EdielMessageRow
const evidence={rulePackId:uuid(3),messageProfileId:uuid(4),profileKey:'synthetic-own-source',version:'opaque-original',sourceHash:'a'.repeat(64),snapshot:{rulePack:{guide_version:'25-A-3'},version:'opaque-original'}}
const data=()=>({version:1,sourceMessage:message,sourceRulePackEvidence:evidence,sourceHash:createHash('sha256').update(raw).digest('hex'),canonicalAssessmentId:uuid(5),correlatedOriginalMessageId:uuid(6),transactions:[{transactionIndex:0,transactionId:'OWN:A+B?C'}],authorizesBusinessEffect:false})
beforeEach(()=>{io.rpc.mockReset();io.actor.mockReset();io.source.mockReset();io.rpc.mockResolvedValue({data:data(),error:null});io.source.mockResolvedValue({sourceMessage:message,evidence});io.actor.mockResolvedValue(undefined)})
describe('actual accepted ERR response read capability, modeled native IO boundaries',()=>{
 it('preserves exact own escaped transaction and protected original without granting business effects',async()=>{const authority=await readReceivedErrApplicationResponseAuthority({message,actorUserId:uuid(7)});expect(authority.transactions).toEqual([{transactionIndex:0,transactionId:'OWN:A+B?C'}]);expect(authority.authorizesBusinessEffect).toBe(false);expect(receivedErrApplicationResponseQualification({authority,message})).toBe(authority);expect(receivedErrApplicationResponseQualification({authority:{...authority},message})).toBeNull();expect(Object.isFrozen(authority.transactions[0])).toBe(true);expect(io.actor).toHaveBeenCalledWith({companyId:uuid(2),actorUserId:uuid(7),permissionAnyOf:['communication.write']})})
 it.each(['wrong raw','wrong tenant','wrong environment','wrong own transaction','missing accepted owner','business permission'])('holds %s from the native reader',async(kind)=>{const result=data();if(kind==='wrong raw')result.sourceMessage={...message,raw_payload:raw+' '};if(kind==='wrong tenant')result.sourceMessage={...message,company_id:uuid(99)};if(kind==='wrong environment')result.sourceMessage={...message,environment:'production'};if(kind==='wrong own transaction')result.transactions[0].transactionId='ORIGINAL-T';if(kind==='missing accepted owner')result.canonicalAssessmentId='';if(kind==='business permission')result.authorizesBusinessEffect=true;io.rpc.mockResolvedValue({data:result,error:null});await expect(readReceivedErrApplicationResponseAuthority({message,actorUserId:uuid(7)})).rejects.toThrow('utilts_err_application_response_authority_unavailable')})
 it('does not accept copied status/evidence when the actual protected own source read disagrees',async()=>{io.source.mockResolvedValue({sourceMessage:message,evidence:{...evidence,version:'today'}});await expect(readReceivedErrApplicationResponseAuthority({message,actorUserId:uuid(7)})).rejects.toThrow('utilts_err_application_response_authority_unavailable')})
 it('keeps established authority bound to exact source bytes and scope',async()=>{const authority=await readReceivedErrApplicationResponseAuthority({message,actorUserId:uuid(7)});expect(receivedErrApplicationResponseQualification({authority,message:{...message,raw_payload:raw+' '}})).toBeNull();expect(receivedErrApplicationResponseQualification({authority,message:{...message,company_id:uuid(99)}})).toBeNull()})
})
