import { beforeEach, it, expect, vi } from 'vitest';
import { tgtDateRun, tgtDateData, tgtDateRuntime } from './fixtures/tgt-date-events';
import type { CreateEdielMessageInput } from '@/lib/ediel/types';
import {createHash} from 'node:crypto'
import {segmentComposite,tokenizeEdifact} from '@/lib/ediel/core/edifactTokenizer'
const io = vi.hoisted(() => ({ from: vi.fn(),rpc:vi.fn(), scoped: vi.fn(), access: vi.fn(), company: vi.fn(), operational: vi.fn(), source: vi.fn(), runtime: vi.fn(), create: vi.fn(), attach: vi.fn(), runs: vi.fn(), messages: vi.fn(), links: vi.fn(), byIds: vi.fn() }));
vi.mock('@/lib/supabase/service', () => ({ supabaseService: { from: io.from,rpc:io.rpc } }));
// Explicit synthetic native registry boundary. Actual canonical/date policy,
// current actor reader, positive-source WeakMap, one-use prepare port and both
// real manual/autopilot consumers still run; this is not native approval proof.
vi.mock('@/lib/ediel/rulebook/canonicalRulePackRegistry',()=>({resolveCanonicalRulePack:async()=>({databaseProfileKey:'SYNTHETIC-Z09D',profileKey:'SYNTHETIC-Z09D',messageProfileId:'00000000-0000-4000-8000-000000000013',originalVersion:'26.A:r3',sourceHash:'a'.repeat(64),originalSnapshot:{rulePack:{id:'00000000-0000-4000-8000-000000000012',source_hash:'a'.repeat(64),guide_version:'26.A',guide_revision:3},messageProfile:{id:'00000000-0000-4000-8000-000000000013',profile_key:'SYNTHETIC-Z09D'},guideSources:[]}})}))
vi.mock('next/cache', () => ({ revalidatePath: vi.fn() }));
vi.mock('@/lib/admin/guards', () => ({ requireCompanyScopedActionAccess: io.company, isPlatformAdminContext: () => false, requirePlatformAdminActionAccess: io.access }));
vi.mock('@/lib/ediel/actionAccess', () => ({ requireEdielWriteActionAccess: io.access, requireEdielSendActionAccess: io.access }));
vi.mock('@/lib/tenant/governance', () => ({ requireCompanyOperationalForWrites: io.operational }));
vi.mock('@/lib/ediel/systemTestSettings', () => ({ requireEdielSystemTestRuntimeContext: io.runtime, getEdielSystemTestSettings: vi.fn() }));
vi.mock('@/lib/ediel/testing/tgtTestDataStore', () => ({ getEdielTgtDynamicTestDataForCase: io.source, upsertEdielTgtDynamicTestData: vi.fn() }));
vi.mock('@/lib/ediel/db', () => ({ createEdielMessage: io.create, attachEdielMessageToTestRun: io.attach, listEdielTestRuns: io.runs, listEdielMessages: io.messages, listEdielMessagesByIds: io.byIds, listEdielTestRunMessages: io.links, createEdielMessageEvent: vi.fn(), getEdielMessageById: vi.fn(), createEdielTestRun: vi.fn(), listAckMessagesForSource: vi.fn(), updateEdielMessageStatus: vi.fn(), updateEdielTestRunStatus: vi.fn() }));
vi.mock('@/app/admin/ediel/actions.part-1', () => ({ requireScopedEdielTestRunForAction: io.scoped, formString: (v: unknown) => typeof v === 'string' ? v.trim() || null : null, formNumber: (v: unknown) => Number(v) || null, parseEdielTestSuite: (v: unknown) => v, parseEdielTestRoleCode: (v: unknown) => v, revalidateEdiel: vi.fn(), revalidateRelatedMessage: vi.fn() }));
import { createEdielTgtDraftAction, saveEdielTgtRegisterFactsAction } from '@/app/admin/ediel/actions.part-2';
import { runTgtAutopilotForRun } from '@/lib/ediel/testing/tgtAutopilot';
let run: ReturnType<typeof tgtDateRun>, runtime: ReturnType<typeof tgtDateRuntime>, created: CreateEdielMessageInput[];
const companyId='00000000-0000-4000-8000-000000000001',actorUserId='00000000-0000-4000-8000-000000000002'
const form = () => { const f = new FormData(); for (const [k, v] of Object.entries({ testRunId: 'RUN', testSuite: 'PRODAT', roleCode: 'supplier', testCaseCode: '2.5.3', stepNo: '1', sourceNote: 'Independent contract signing', registerFacts: JSON.stringify({ market: 'electricity', dateEventObjects: [{ meteringPointId: 'A', identityAgency: '9', kind: 'production_contract', direction: 'production', contract: { reference: 'contract', revision: '1' }, event: { kind: 'signed', reference: 'event', revision: '1' }, supplyBoundaryAt: '202610010000' }] }) }))
    f.set(k, v); return f; };
beforeEach(() => { vi.resetAllMocks(); run = tgtDateRun(); run.company_id=companyId; run.route_profile_id = null; run.created_at = '2026-09-19T00:00:00Z'; runtime = tgtDateRuntime(); runtime.companyId=companyId;runtime.settings!.companyId=companyId; runtime.settings!.routeProfileId = null; created = []; io.scoped.mockResolvedValue(run); io.access.mockResolvedValue({ userId: actorUserId }); io.company.mockResolvedValue({ userId: actorUserId }); io.runtime.mockResolvedValue(runtime); io.source.mockResolvedValue(tgtDateData()); io.runs.mockResolvedValue([run]); io.messages.mockResolvedValue([]); io.links.mockResolvedValue([]); io.byIds.mockResolvedValue([]); io.create.mockImplementation(async (input: CreateEdielMessageInput) => { created.push(input); return { id: 'MSG', company_id: companyId, direction: 'outbound', environment: 'test' }; }); io.from.mockImplementation((table: string) => { let update: Record<string, unknown> | undefined; const q = { update: (v: Record<string, unknown>) => { update = v; return q; }, eq: () => q, select: () => q,not:()=>q, maybeSingle: async () => { if(table==='company_memberships')return{data:{company_id:companyId,user_id:actorUserId,status:'active',is_active:true,accepted_at:'2026-09-01T00:00Z'},error:null};if(table==='user_profiles')return{data:{id:actorUserId,user_status:'active'},error:null};if (table !== 'ediel_test_runs')
        throw new Error('Unexpected table'); if (update)
        run.notes = String(update.notes); return { data: { id: 'RUN' }, error: null }; } }; return q; });io.rpc.mockImplementation(async(name:string,args:Record<string,unknown>)=>{if(name==='gridex_actor_has_company_permission'){expect(args).toMatchObject({p_actor_user_id:actorUserId,p_company_id:companyId});return{data:true,error:null}}const context=args.p_context as Record<string,unknown>;if(name==='gridex_ediel_positive_fixture_read_v1'){const hash=createHash('sha256').update(String(context.rawPayload),'latin1').digest('hex');return{data:{kind:'source_qualified_positive_fixture',version:1,registrationId:'00000000-0000-4000-8000-000000000014',companyId,runId:run.id,roleCode:'supplier',caseCode:'2.5.3',suite:'PRODAT',revision:'1',stepNo:context.stepNo,wireSha256:hash,originalFileSha256:hash,expectedOutcome:'positive',expectedDiagnosticCodes:[],testReceiverEdielId:'54321',validUntil:'2027-01-01T00:00Z',sourceReference:'SYNTHETIC source original',ownerDecisionReference:'SYNTHETIC independent fixture owner',authorizesBusinessEffect:false},error:null}}if(name==='gridex_ediel_positive_fixture_prepare_v1'){const read=await io.rpc('gridex_ediel_positive_fixture_read_v1',{p_context:context});return{data:{witnessId:'00000000-0000-4000-8000-000000000015',qualification:read.data},error:null}}if(name==='ediel_prepare_outbound_owner_witness_v1'){const input=args.p_input as Record<string,unknown>;return{data:{version:1,witnessId:'00000000-0000-4000-8000-000000000016',evidence:input.rulePackEvidence},error:null}}throw Error('unexpected_native_port:'+name)}); });
it('authorized action saves domain assertion then actual manual draft retains verified scope', async () => { await saveEdielTgtRegisterFactsAction(form()); expect(JSON.parse(run.notes!).prodatRegisterFacts.steps['1'].facts.dateEventSource).toMatchObject({ kind: 'tgt', runId: 'RUN', actorId: actorUserId, route: { settingsId: 'SETTINGS' } }); await createEdielTgtDraftAction(form()); expect(created).toHaveLength(1); expect(created[0].rawPayload).toContain('DTM+92:202610010000:203'); expect(created[0].parsedPayload?.readyForDownload).toBe(true);
 const wire=tokenizeEdifact(created[0].rawPayload!),unb=wire.segments.find(s=>s.tag==='UNB')!;
 // Independent T §5 envelope positions:0031=9,0032=10,0035=11.
 expect(segmentComposite(unb,9,wire.una)[0]).toBe('1');expect(segmentComposite(unb,10,wire.una)[0]??'').toBe('');expect(segmentComposite(unb,11,wire.una)[0]).toBe('1');expect(created[0].processType).toBe('masterdata');
 expect(io.rpc).toHaveBeenCalledWith('gridex_ediel_positive_fixture_prepare_v1',expect.objectContaining({p_context:expect.objectContaining({companyId,actorUserId,rawPayload:created[0].rawPayload})}));expect(created[0].executionContextSnapshot).toMatchObject({sourceQualifiedPositiveFixtureWitnessId:'00000000-0000-4000-8000-000000000015'});
});
it('actual autopilot resolves the same independently saved source before persistence', async () => { await saveEdielTgtRegisterFactsAction(form()); await runTgtAutopilotForRun({ actorUserId, companyId, testRunId: 'RUN' }); expect(created).toHaveLength(1); expect(created[0].parsedPayload?.readyForDownload).toBe(true); });
it('revoked current test runtime prevents both constructors from persisting', async () => { await saveEdielTgtRegisterFactsAction(form()); runtime.settings!.isActive = false; await expect(createEdielTgtDraftAction(form())).rejects.toThrow('PRODAT_DATE_EVENT_SOURCE_CONTEXT_INVALID'); await expect(runTgtAutopilotForRun({ actorUserId, companyId, testRunId: 'RUN' })).rejects.toThrow('PRODAT_DATE_EVENT_SOURCE_CONTEXT_INVALID'); expect(created).toEqual([]); });
it('write denial precedes source stamping and persistence', async () => { io.company.mockRejectedValue(new Error('DENIED')); await expect(saveEdielTgtRegisterFactsAction(form())).rejects.toThrow('DENIED'); expect(run.notes).toBeNull(); expect(created).toEqual([]); });
it('current native actor permission denial stops both actual consumers before source witness or persistence',async()=>{await saveEdielTgtRegisterFactsAction(form());io.rpc.mockImplementation(async(name:string)=>{if(name==='gridex_actor_has_company_permission')return{data:false,error:null};throw Error('unexpected_source_read_after_actor_denial')});await expect(createEdielTgtDraftAction(form())).rejects.toThrow('tenant_permission_forbidden');await expect(runTgtAutopilotForRun({actorUserId,companyId,testRunId:'RUN'})).rejects.toThrow('tenant_permission_forbidden');expect(created).toEqual([]);expect(io.rpc.mock.calls.some(([name])=>name==='gridex_ediel_positive_fixture_prepare_v1')).toBe(false)})
function utiltsForm(stepNo=2){run.test_suite='UTILTS';run.test_case_code='U2.1';io.source.mockResolvedValue(null);runtime.settings!.messageFamily='UTILTS';const f=form();f.set('testSuite','UTILTS');f.set('testCaseCode','U2.1');f.set('stepNo',String(stepNo));return f}
for(const stepNo of [2,3])it(`manual UTILTS ACK step${stepNo} uses source case profile`,async()=>{
 const f=utiltsForm(stepNo);const stop=new Error('EXPECTED_RUNTIME_BOUNDARY');io.runtime.mockRejectedValue(stop)
 await expect(createEdielTgtDraftAction(f)).rejects.toBe(stop)
 expect(io.runtime).toHaveBeenCalledWith(expect.objectContaining({companyId,messageFamily:'UTILTS'}));expect(created).toEqual([])
})
it('autopilot UTILTS ACK inherits source profile after actual inbound step match',async()=>{
 utiltsForm();io.messages.mockResolvedValue([{id:'INBOUND',company_id:'tenant',direction:'inbound',environment:'test',message_family:'UTILTS',message_code:'E66',status:'received',created_at:'2026-09-19T00:01:00Z'}]);const stop=new Error('EXPECTED_RUNTIME_BOUNDARY');io.runtime.mockRejectedValue(stop)
 await expect(runTgtAutopilotForRun({actorUserId,companyId,testRunId:'RUN'})).rejects.toBe(stop)
 expect(io.runtime).toHaveBeenCalledWith(expect.objectContaining({companyId,messageFamily:'UTILTS'}));expect(created).toEqual([])
})
it('invalid requested step is rejected before runtime profile lookup',async()=>{const f=form();f.set('stepNo','999');await expect(createEdielTgtDraftAction(f)).rejects.toThrow('TGT_STEP_CONTEXT_INVALID');expect(io.runtime).not.toHaveBeenCalled()})
