import { describe, expect, it } from 'vitest'
import { getPortalDataRows } from '@/lib/ediel/testing/tgtEdifact.part-2'
import { buildPortalProdatSegments } from '@/lib/ediel/testing/tgtEdifact.part-3'
import { nowRefs, type EdielTgtDraftBuildParams } from '@/lib/ediel/testing/tgtEdifact.part-1'
import { parseProdatMessage } from '@/lib/ediel/prodat/parser'
import { resolveTgtExpectedProdatContext } from '@/lib/ediel/testing/prodatExpectedContext'
import { validateParsedProdatAgainstExpected } from '@/lib/ediel/testing/prodatValidators'
import { compareInboundPayloadToTgtTestData } from '@/lib/ediel/testing/tgtAutoMatcher'
import type { EdielTgtCaseTestData } from '@/lib/ediel/testing/tgtTestData'
import type { EdielTgtExpectedStep } from '@/lib/ediel/testing/tgtRegistry'
import type { EdielMessageRow } from '@/lib/ediel/types'
import { raw, line, qty, characteristic, alphabets } from './fixtures/prodat-register'

// Source oracle: P26.A pp47,114-116; identities/indices below are literals,
// never generated by the implementation being tested. All data is synthetic.
type SourceRow = { name: string; fields: Record<string,string> }
function source(groups: SourceRow[][]): EdielTgtCaseTestData {
 return {suite:'PRODAT',roleCode:'supplier',testCaseCode:'SYNTHETIC-REGISTER',title:'Synthetic',sourceNote:'Not portal approval',groups:groups.map((rows,g)=>{
  const columns=rows.map((r,i)=>({name:r.name,index:i+1,sourceOrder:i+1,testCase:'SYNTHETIC-REGISTER'}))
  const fields=[...new Set(rows.flatMap(r=>Object.keys(r.fields)))].map(fieldCode=>({fieldCode,fieldName:fieldCode,values:Object.fromEntries(rows.map(r=>[r.name,r.fields[fieldCode]??'']))}))
  const block={kind:'PRODAT' as const,sourceWorkbook:'synthetic',sourceSheet:`sheet-${g}`,entityLabel:`object-${g}`,entityNumbers:[String(g)],columns,fields}
  return {block,columns,fields}
 })}
}
const first = (id:string,n='10'):Record<string,string> => ({'209':id,'210':'202610010000','508':'15:806','213':n,'214':'1','218':'6','259':'111','217':'Z03','222':'D','223':'Z22','224':`M:${id}`,'260':`N:${id}`,'227':`U:${id}`,'228':`Customer ${id}`,'231':'12345','232':'Town','316':'SE','233':id,'234':'Street','262':'12345'})
const step = {code:'Z04',family:'PRODAT',stepNo:1,actor:'gridex',direction:'outbound',outcome:'positive',title:'Synthetic'} as EdielTgtExpectedStep
const params = (testData:EdielTgtCaseTestData) => ({actorUserId:'user',testSuite:'PRODAT',roleCode:'supplier',testCaseCode:testData.testCaseCode,stepNo:1,importedTestData:testData,systemTestContext:{companyId:'tenant-A',actorEdielId:'12345',testPortalEdielId:'54321'}} as EdielTgtDraftBuildParams)
const build=(td:EdielTgtCaseTestData)=>buildPortalProdatSegments(params(td),step,nowRefs('SYNTHETIC',1,true))
const parsedBuild=(td:EdielTgtCaseTestData)=>parseProdatMessage("UNH+M+PRODAT:D:97A:UN:E2SE6A'"+build(td).bodySegments.join("'")+"'UNT+1+M'")
const multi=()=>source([
 [{name:'Z04L register 1',fields:first('A:local')},{name:'Z04L register nr 2',fields:{'209':'A:local','213':'20','214':'2','218':'7','259':'112','260':'IGNORE'}}],
 [{name:'Z04L register 1',fields:first('B:local','30')}],
])

describe('actual TGT source grouping and rendering',()=>{
 it('keeps same-named columns in different groups and groups registers under their own identity',()=>{
  const rows=getPortalDataRows(params(multi()),step)
  expect(rows).toHaveLength(2)
  expect(rows.map(r=>r.meteringPointId)).toEqual(['A:local','B:local'])
  expect(rows.map(r=>r.registers.map(v=>v.annualEnergyKwh))).toEqual([['10','20'],['30']])
 })
 it('renders global314=1,2,3 independently from per-object258=1,2,omitted',()=>{
  expect(parsedBuild(multi()).lineItems).toMatchObject([
   {meteringPointId:'A:local',lineSequenceNumber:'1',registerIndex:'1',annualConsumption:'10',gridAreaId:'N:A:local'},
   {meteringPointId:'A:local',lineSequenceNumber:'2',registerIndex:'2',annualConsumption:'20',meterConstant:'2',gridAreaId:'N:A:local'},
   {meteringPointId:'B:local',lineSequenceNumber:'3',registerIndex:null,annualConsumption:'30',gridAreaId:'N:B:local'},
  ])
 })
 it('does not filter an empty register or borrow its measurements',()=>{
  const td=multi(); const group=td.groups[0]; const fields=group.fields.map(f=>({...f,values:{...f.values,'Z04L register nr 2':f.fieldCode==='209'?'A:local':''}}))
  const testData={...td,groups:[{...group,fields}]}
  const rows=getPortalDataRows(params(testData),step)
  expect(rows[0].registers).toHaveLength(2)
  const actual=parsedBuild(testData)
  expect(actual.lineItems).toHaveLength(2)
  expect(actual.lineItems[1].annualConsumption).toBeNull()
 })
 it('keeps register 2 even when only register 1 has a transaction-type score',()=>{
  const td=source([[{name:'Z04L register 1',fields:{...first('A'),'223':'Z04L'}},{name:'register 2',fields:{'209':'A','213':'20'}}]])
  expect(getPortalDataRows(params(td),step)[0].registers).toHaveLength(2)
 })
 it('does not discard an unlabelled register whose required object identity is missing',()=>{
  const td=source([[{name:'Z04 register 1',fields:first('A')},{name:'register 2',fields:{'213':'20'}}]])
  expect(()=>build(td)).toThrow(/register/)
 })
 it('does not pull a differently labelled function into this message',()=>{
  const td=source([[{name:'Z04L',fields:first('A')},{name:'Z06F',fields:{...first('B'),'216':'202610010000'}}]])
  expect(parsedBuild(td).lineItems.map(l=>l.meteringPointId)).toEqual(['A'])
 })
 for(const rows of [
  [{name:'Z04 register 1',fields:first('A')},{name:'Z04 register 3',fields:{'209':'A','213':'20'}}],
  [{name:'Z04 register 1',fields:{...first('A'),'258':'2'}},{name:'Z04 register 2',fields:{'209':'A','258':'2','213':'20'}}],
  [{name:'Z04 x',fields:first('A')},{name:'Z04 y',fields:{'209':'A','213':'20'}}],
 ]) it(`rejects ambiguous/missing/conflicting source indices ${rows.map(r=>r.name)}`,()=>expect(()=>build(source([rows]))).toThrow(/register/i))
 it('preserves punctuation rather than changing a local object ID or reference',()=>{
  const parsed=parsedBuild(source([[{name:'Z04',fields:first("A:+?'(local)")}]]))
  expect(parsed.lineItems[0]).toMatchObject({meteringPointId:"A:+?'(local)",meterNumber:"M:A:+?'(local)",gridAreaId:"N:A:+?'(local)"})
 })
})

for (const alphabet of alphabets) describe(`both TGT comparators ${alphabet.join('')}`,()=>{
 const compare=(payload:string,td:EdielTgtCaseTestData)=>{
  const parsed=parseProdatMessage(payload)
  return [compareInboundPayloadToTgtTestData({message:{raw_payload:payload,message_family:'PRODAT',message_code:'Z04'} as EdielMessageRow,testData:td}),validateParsedProdatAgainstExpected({parsed,expected:resolveTgtExpectedProdatContext({parsed,testData:td})})]
 }
 const td=()=>source([[{name:'Z04 register 1',fields:{'209':'A:local','213':'10 (optional)'}},{name:'Z04 register 2',fields:{'209':'A:local','213':'20','214':'1.2'}}],[{name:'Z04',fields:{'209':'B:local','213':'30'}}]])
 const payload=()=>raw([line('1','A:local','1'),qty('10'),line('2','A:local','2'),qty('20'),...characteristic('Z02','1.2',3),line('3','B:local'),qty('30')],'Z04',alphabet)
 it('accepts exact register values, explicit source labels and known optional annotation',()=>expect(compare(payload(),td())).toEqual([[],[]]))
 it('rejects a changed second-register value in both actual comparison entry points',()=>{
  const p=raw([line('1','A:local','1'),qty('10'),line('2','A:local','2'),qty('999'),line('3','B:local'),qty('30')],'Z04',alphabet)
  for(const issues of compare(p,td())) expect(issues.some(i=>i.fieldCode==='213')).toBe(true)
 })
 it('scopes a singleton register-1 label by both object ID and identity agency',()=>{
  const testData=source([[{name:'Z04 register 1 GS1',fields:{'209':'A','209.AGENCY':'9','213':'10'}},{name:'Z04 register 1 local',fields:{'209':'A','209.AGENCY':'89','213':'20'}}]])
  for(const issues of compare(raw([line('1','A',undefined,'9'),qty('10'),line('2','A',undefined,'89'),qty('20')],'Z04',alphabet),testData)) expect(issues).toEqual([])
 })
 it('reports a whole missing object, not only mismatching present objects',()=>{
  for(const issues of compare(raw([line('1','A:local'),qty('10')],'Z04',alphabet),td())) expect(issues.some(i=>i.fieldCode==='209')).toBe(true)
 })
 it('reports invalid duplicate register chains even for partial unindexed expectations',()=>{
  for(const issues of compare(raw([line('1','A:local','1'),qty('10'),line('2','A:local','1'),qty('10')],'Z04',alphabet),source([[{name:'Z04',fields:{'209':'A:local'}}]]))) expect(issues.some(i=>i.fieldCode==='258')).toBe(true)
 })
 it('does not normalize local identity punctuation or fall back by ordinal',()=>{
  for(const issues of compare(raw([line('1','Alocal'),qty('10')],'Z04',alphabet),source([[{name:'Z04',fields:{'209':'A:local','213':'10'}}]]))) expect(issues.some(i=>i.fieldCode==='209')).toBe(true)
 })
})


describe('source columns cannot silently choose one of several functions',()=>{
 it('rejects an unqualified register column in a mixed-function group',()=>{
  const td=source([[{name:'Z04L register 1',fields:first('A')},{name:'Z06F register 1',fields:first('B')},{name:'register 2',fields:{'209':'A','213':'20'}}]])
  expect(()=>getPortalDataRows(params(td),step)).toThrow('prodat_register_source_function_ambiguous')
 })
 it('rejects an unsupported explicit function rather than treating it as an unlabelled column',()=>{
  const td=source([[{name:'Z04L register 1',fields:first('A')},{name:'Z99 register 2',fields:{'209':'A','213':'20'}}]])
  expect(()=>getPortalDataRows(params(td),step)).toThrow('prodat_register_source_function_invalid')
 })
 it('uses the Z05 expected identity in233 for local IDs as well as GS1 IDs',()=>{
  const td=source([[{name:'Z05L',fields:{'209':'SENT:local','233':'EXPECTED:local'}}]])
  const message={message_family:'PRODAT',message_code:'Z05',raw_payload:raw([line('1','SENT:local')],'Z05')} as EdielMessageRow
  expect(compareInboundPayloadToTgtTestData({message,testData:td}).some(issue=>issue.fieldCode==='209')).toBe(true)
 })
})
