import {expect,it} from 'vitest'
import {renderAperakEdiel} from '@/lib/ediel/aperakEngine'
import {EdifactEnvelopeCodec} from '@/lib/ediel/core/edifactEnvelopeCodec'
import {tokenizeEdifact} from '@/lib/ediel/core/edifactTokenizer'
function input(scope:'two'|'single'='two'){const raw=EdifactEnvelopeCodec.encode({sender:'12345',receiver:'54321',environment:'test',applicationReference:'23-DDQ-PRODAT',interchangeReference:'I',acknowledgementRequest:true,messages:[{messageReference:'M',messageTypeToken:'PRODAT:D:97A:UN:E2SE6A',businessSegments:['BGM+Z04+D+9+AB','DTM+137:202609301200:203','DTM+ZZZ:1:805','NAD+FR+12345:160:SVK+++++++SE','NAD+DO+54321:160:SVK+++++++SE','LIN+1++A:::9','RFF+LI:OWN-A',...(scope==='two'?['LIN+2++B:::9']:[])]}]});return {source:{id:'source',messageFamily:'PRODAT',messageCode:'Z04',rawPayload:raw},refs:{documentReference:'D'},externalReference:'ACK-D',transactionReference:'ACK-T',outcome:'positive' as const}}
it('holds a partial caller-selected BGM34 without inventing an outcome or borrowing missing sibling LI',()=>{const params=input(),wire=tokenizeEdifact(params.source.rawPayload),own=wire.segments.filter(t=>t.tag==='LIN');expect(()=>renderAperakEdiel({...params,prodatAcknowledgementLineIndices:[own[0].index]})).toThrow('APERAK_PRODAT_OBJECT_OUTCOME_MISSING');expect(()=>renderAperakEdiel(params)).toThrow('own_line_reference_required')})
it('renders a genuine single physical first-register object while retaining both own refs for the separate strict grammar gate',()=>{const params=input('single');const own=tokenizeEdifact(params.source.rawPayload).segments.find(t=>t.tag==='LIN')!;const result=renderAperakEdiel({...params,prodatAcknowledgementLineIndices:[own.index]});expect(result.segments.filter(s=>s.startsWith('RFF+LI:'))).toEqual(['RFF+LI:OWN-A']);expect(result.segments).toContain('RFF+Z07:A');expect(result.segments).not.toContain('RFF+Z07:B')})
it.each([[[]],[[-1]],[[999]]])('refuses empty/unknown caller projection %j',selection=>{expect(()=>renderAperakEdiel({...input(),prodatAcknowledgementLineIndices:selection})).toThrow('selected_scope_invalid')})
it('refuses a duplicate physical selection and a later register index',()=>{const params=input(),index=tokenizeEdifact(params.source.rawPayload).segments.find(t=>t.tag==='LIN')!.index;expect(()=>renderAperakEdiel({...params,prodatAcknowledgementLineIndices:[index,index]})).toThrow('selected_scope_invalid');params.source.rawPayload=params.source.rawPayload.replace('LIN+1++A','LIN+1+1:1+A').replace("LIN+2++B:::9'", "LIN+2+1:2+A:::9'");const later=tokenizeEdifact(params.source.rawPayload).segments.filter(t=>t.tag==='LIN')[1].index;expect(()=>renderAperakEdiel({...params,prodatAcknowledgementLineIndices:[later]})).toThrow('selected_scope_invalid')})
