import{beforeEach,expect,it,vi}from'vitest'
const rpc=vi.hoisted(()=>vi.fn());vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc}}))
import{readCustomerLifeEventPatches}from'@/lib/ediel/production/customerLifeEventPatches'
const input={companyId:'company-A',customerId:'customer-A',actorUserId:'actor-A',from:'2026-09-01T00:00:00Z',to:'2026-10-01T00:00:00Z',cutoff:'2026-10-01T01:00:00Z'}
const p={effectiveAt:'2026-09-30T00:00:00Z',sourceMessageId:'00000000-0000-4000-8000-000000000030',sourcePayloadHash:'a'.repeat(64),customerVersion:2,primaryAssessmentId:'00000000-0000-4000-8000-000000000230',primaryFactsHash:'b'.repeat(64),appliedAt:'2026-09-30T11:00:00Z',availableAt:'2026-09-30T12:00:00Z',customerFields:{full_name:'Own new name'},endUserMasterdata:{name:['Own new name']}}
const result={status:'authorized',companyId:input.companyId,customerId:input.customerId,from:input.from,to:input.to,cutoff:input.cutoff,authorizesInitialCustomer:false,patches:[p]}
beforeEach(()=>rpc.mockReset())
it('returns same protected deltas without making empty history initial authority',async()=>{rpc.mockResolvedValue({data:result,error:null});expect(await readCustomerLifeEventPatches(input)).toEqual([p]);rpc.mockResolvedValue({data:{...result,patches:[]},error:null});expect(await readCustomerLifeEventPatches(input)).toEqual([])})
it.each([{authorizesInitialCustomer:true},{patches:[{...p,availableAt:'2026-10-01T01:00:01Z'}]},{patches:[{...p,customerFields:{billing_street:'wrong owner'}}]},{patches:[{...p,endUserMasterdata:{name:'flattened'}}]},{patches:[p,p]}])('holds a changed source/epoch/type %j',async changed=>{rpc.mockResolvedValue({data:{...result,...changed},error:null});await expect(readCustomerLifeEventPatches(input)).rejects.toThrow('patch_result_invalid')})
it('accepts true effective order of retrospectively received immutable versions',async()=>{const prior={...p,effectiveAt:'2026-09-29T00:00:00Z',customerVersion:3,sourceMessageId:'00000000-0000-4000-8000-000000000031'};rpc.mockResolvedValue({data:{...result,patches:[prior,p]},error:null});expect(await readCustomerLifeEventPatches(input)).toEqual([prior,p])})
it('does not substitute an older projection when availability is held',async()=>{rpc.mockResolvedValue({data:{status:'held',missing:['customer_event_available_at_same_export_cutoff']},error:null});await expect(readCustomerLifeEventPatches(input)).rejects.toThrow('patch_source_held')})
