import {describe,expect,it} from 'vitest'
import {assertCapturedServiceRequestTiming} from '@/lib/ediel/services/requestTiming'
import {serviceEvidenceArchiveSchema} from '@/lib/ediel/services/evidenceReview'
const original={code:'Z13' as const,mode:'V' as const,scopeBasisVersion:1,requestTiming:{version:1,evidenceId:'00000000-0000-4000-8000-000000000001',sourceHash:'a'.repeat(64),sourceReference:'Declared synthetic native RPC boundary; no legal approval',sourceVersion:'v1',networkStart:'2026-03-29',networkEnd:null,reviewId:'00000000-0000-4000-8000-000000000002',reviewerUserId:'00000000-0000-4000-8000-000000000003',reviewSequence:1,scopeBasisVersion:1,requestDay:'2026-03-29'},objects:[{reportStart:'2026-03-28T23:00:00Z',reportEnd:null}]}
describe('protected timing DTO verification with the actual canonical calendar; no native authority claim',()=>{
 it('retains the captured server day regardless of a later wall clock',()=>{expect(()=>assertCapturedServiceRequestTiming(original)).not.toThrow();expect(original.requestTiming.requestDay).toBe('2026-03-29')})
 it('preserves Ediel fixed UTC+1 source days across Stockholm DST',()=>{expect(()=>assertCapturedServiceRequestTiming({...original,objects:[{reportStart:'2026-03-28T23:30:00Z',reportEnd:null}]})).not.toThrow();expect(()=>assertCapturedServiceRequestTiming({...original,objects:[{reportStart:'2026-03-28T22:30:00Z',reportEnd:null}]})).toThrow('outside_captured_bounds')})
 it('rejects a public result without the actual native timing receipt',()=>expect(()=>assertCapturedServiceRequestTiming({...original,requestTiming:undefined})).toThrow())
 it('rejects a mismatched scope version without interpreting source hash as authority',()=>expect(()=>assertCapturedServiceRequestTiming({...original,scopeBasisVersion:2})).toThrow('timing_scope_mismatch'))
 it.each(['2026-03-29T01:00:00Z','2026-03-28T23:00:00Z'])('rejects continuous nonfuture end %s',end=>expect(()=>assertCapturedServiceRequestTiming({...original,objects:[{reportStart:original.objects[0].reportStart,reportEnd:end}]})).toThrow('outside_captured_bounds'))
 it('allows an authentic future V end inside the same captured network period',()=>expect(()=>assertCapturedServiceRequestTiming({...original,requestTiming:{...original.requestTiming,networkEnd:'2026-04-01'},objects:[{reportStart:original.objects[0].reportStart,reportEnd:'2026-03-31T23:00:00Z'}]})).not.toThrow())
 it('holds a future end outside the DSO period',()=>expect(()=>assertCapturedServiceRequestTiming({...original,requestTiming:{...original.requestTiming,networkEnd:'2026-03-30'},objects:[{reportStart:original.objects[0].reportStart,reportEnd:'2026-03-31T23:00:00Z'}]})).toThrow('outside_captured_bounds'))
 it('requires VH end and both dates before captured request day',()=>{expect(()=>assertCapturedServiceRequestTiming({...original,mode:'VH',requestTiming:{...original.requestTiming,networkStart:'2026-03-01'},objects:[{reportStart:'2026-03-27T23:00:00Z',reportEnd:null}]})).toThrow();expect(()=>assertCapturedServiceRequestTiming({...original,mode:'VH',requestTiming:{...original.requestTiming,networkStart:'2026-03-01'},objects:[{reportStart:'2026-03-27T23:00:00Z',reportEnd:'2026-03-28T23:00:00Z'}]})).toThrow('outside_captured_bounds')})
 it('matches clamped leap-year three-year boundary',()=>{const basis={...original,requestTiming:{...original.requestTiming,requestDay:'2024-02-29',networkStart:'2000-01-01'},objects:[{reportStart:'2021-02-28T00:00:00Z',reportEnd:null}]};expect(()=>assertCapturedServiceRequestTiming(basis)).not.toThrow();expect(()=>assertCapturedServiceRequestTiming({...basis,objects:[{reportStart:'2021-02-27T00:00:00Z',reportEnd:null}]})).toThrow('outside_captured_bounds')})
 it('preserves the separate Z18 termination owner',()=>expect(()=>assertCapturedServiceRequestTiming({...original,code:'Z18',requestTiming:undefined})).not.toThrow())
 it('accepts strict original DSO calendar dates, excluding guessed timestamps and impossible dates',()=>{const terms=serviceEvidenceArchiveSchema.shape.terms;expect(terms.parse({valid_from:'2000-01-01T00:00:00Z',valid_to:null,permission_network_contract_start:'2026-03-29',permission_network_contract_end:null}).permission_network_contract_start).toBe('2026-03-29');for(const value of ['2026-02-30','03/29/2026','2026-03-29T00:00:00Z'])expect(()=>terms.parse({valid_from:'2000-01-01T00:00:00Z',valid_to:null,permission_network_contract_start:value})).toThrow()})
})
