import {createHash} from 'node:crypto'
import {beforeEach,expect,it,vi} from 'vitest'
const rpc=vi.hoisted(()=>vi.fn())
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc}}))
import {readSupplyRescissionMandate,isQualifiedSupplyRescissionBasis} from '@/lib/ediel/production/supplyRescissionOperation'
import {requiresNationalSupplyRescissionOwner,qualifyBilateralProdatOutboundDraft,bilateralProdatOutboundDraftQualified,createAtomicBilateralProdatOriginal,qualifyPersistedBilateralProdatOutboundOriginal} from '@/lib/ediel/production/bilateralProdatOutboundDraft'
import type {CreateEdielMessageInput} from '@/lib/ediel/types'
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,input={companyId:id(1),actorUserId:id(2),mandateId:id(3)},reference='H'+id(3).replaceAll('-','')
const raw=`UNB+UNOC:3+12345:14+54321:14+261001:1200+I'UNH+M+PRODAT:D:97A:UN:E2SE6A'BGM+Z08+${reference}+9'LIN+1++735123456789012345:::9'CCI++Z13'CAV+Z25'RFF+LI:${reference}'UNT+7+M'UNZ+1+I'`
const draft:CreateEdielMessageInput={actorUserId:input.actorUserId,companyId:input.companyId,environment:'test',direction:'outbound',messageStandard:'edifact',messageFamily:'PRODAT',messageCode:'Z08',rawPayload:raw,sourceOperationId:input.mandateId}
const basis=()=>({status:'authorized',version:1,owner:'immutable-national-supply-rescission-mandate-v1',...input,environment:'test',periodId:id(4),rulePackId:id(5),customerId:id(6),siteId:id(7),pointId:id(8),contractId:id(9),contractHash:'a'.repeat(64),externalPoint:'735123456789012345',identityAgency:'9',gridArea:'TES',legalActorId:id(10),legalSenderId:'12345',legalReceiverId:'54321',balanceResponsibleId:'33333',sourceHash:'b'.repeat(64),sourceGrammarHash:'c'.repeat(64),effectiveAt:'2026-10-16T12:30:00Z',lineItemReference:reference,documentReference:reference,customerIdentity:{id:'199001011234',qualifier:'SE2',agency:'260'}})
const capability=()=>({version:1,owner:'immutable-national-supply-rescission-original-v1',...input,environment:'test',payloadHash:createHash('sha256').update(raw).digest('hex'),messageCode:'Z08',objects:[{objectId:'735123456789012345',identityAgency:'9',firstLineIndex:0,lineItemReference:reference,mandateId:input.mandateId,process:'national_supply_rescission',sourceHash:'a'.repeat(64),sourceGrammarHash:'b'.repeat(64),rulePackId:id(4),messageProfileId:id(5),pointId:id(6),customerId:id(7),siteId:id(8),contractId:id(9),contractHash:'c'.repeat(64),eventAt:'2026-10-16T12:30:00Z'}]})
// Finite RPC decoder contracts. No fixture data qualify native legal authority.
beforeEach(()=>rpc.mockReset())
it('missing current legal mandate holds, and caller copies cannot mint a renderer capability',async()=>{rpc.mockResolvedValueOnce({data:null,error:null});expect((await readSupplyRescissionMandate(input)).status).toBe('held');rpc.mockResolvedValueOnce({data:basis(),error:null});const b=await readSupplyRescissionMandate(input);expect(isQualifiedSupplyRescissionBasis(b)).toBe(true);expect(isQualifiedSupplyRescissionBasis({...b})).toBe(false);expect(Object.isFrozen(b)).toBe(true)})
it.each([{companyId:id(20)},{actorUserId:id(20)},{mandateId:id(20)},{owner:'approved'},{rulePackId:null},{lineItemReference:'OTHER'},{effectiveAt:'2026-10-16T12:30:01Z'},{customerIdentity:{id:'199001011234',qualifier:'SE2',agency:'9'}},{balanceResponsibleId:null},{balanceResponsibleId:''}])('rejects malformed or foreign legal scope %j',async change=>{rpc.mockResolvedValue({data:{...basis(),...change},error:null});await expect(readSupplyRescissionMandate(input)).rejects.toThrow('supply_rescission_operation_result_invalid')})
it('selects national owner from physical Z08/Z25 and fails before a native call when mandate selector is absent',async()=>{expect(requiresNationalSupplyRescissionOwner(draft)).toBe(true);expect(requiresNationalSupplyRescissionOwner({...draft,rawPayload:raw.replace('Z25','Z23')})).toBe(false);await expect(qualifyBilateralProdatOutboundDraft({draft:{...draft,sourceOperationId:undefined},actorUserId:input.actorUserId})).rejects.toThrow('actual_mandate_required');expect(rpc).not.toHaveBeenCalled()})
it('shared gateway redeems exactly this native mandate and binds the physical draft without a public approved flag',async()=>{rpc.mockResolvedValue({data:capability(),error:null});const q=await qualifyBilateralProdatOutboundDraft({draft,actorUserId:input.actorUserId});expect(rpc).toHaveBeenCalledExactlyOnceWith('ediel_qualify_supply_rescission_draft_v1',{p_company_id:input.companyId,p_actor_user_id:input.actorUserId,p_environment:'test',p_raw_payload:raw,p_mandate_id:input.mandateId});expect(bilateralProdatOutboundDraftQualified({draft,actorUserId:input.actorUserId,qualification:q})).toBe(true);expect(bilateralProdatOutboundDraftQualified({draft,actorUserId:input.actorUserId,qualification:{...q!}})).toBe(false)})
it('a different returned mandate cannot qualify an own physical original',async()=>{rpc.mockResolvedValue({data:{...capability(),mandateId:id(20)},error:null});await expect(qualifyBilateralProdatOutboundDraft({draft,actorUserId:input.actorUserId})).rejects.toThrow('actual_mandate_receipt_unqualified')})
it('shared atomic adapter calls national native owner once; tenant/source bytes and creator are validated',async()=>{const message={id:id(11),company_id:input.companyId,environment:'test',direction:'outbound',message_family:'PRODAT',message_code:'Z08',raw_payload:raw,created_by:input.actorUserId,immutable_payload_hash:createHash('sha256').update(raw).digest('hex')};rpc.mockResolvedValue({data:{version:1,message},error:null});expect(await createAtomicBilateralProdatOriginal(draft,input.actorUserId)).toEqual(message);expect(rpc).toHaveBeenCalledExactlyOnceWith('ediel_create_national_supply_rescission_original_v1',{p_company_id:input.companyId,p_actor_user_id:input.actorUserId,p_draft:draft})})

it('persisted national send requires its supplied current executor and retains original creator as independent provenance',async()=>{
 const current=id(30),message={id:id(11),company_id:input.companyId,environment:'test',direction:'outbound',message_standard:'edifact',message_family:'PRODAT',message_code:'Z08',raw_payload:raw,created_by:input.actorUserId,source_operation_id:input.mandateId}
 await expect(qualifyPersistedBilateralProdatOutboundOriginal(message as never)).rejects.toThrow('current_execution_actor_required');expect(rpc).not.toHaveBeenCalled()
 rpc.mockResolvedValue({data:{...capability(),actorUserId:current,originalActorUserId:input.actorUserId},error:null})
 const qualified=await qualifyPersistedBilateralProdatOutboundOriginal(message as never,current)
 expect(rpc).toHaveBeenCalledExactlyOnceWith('ediel_qualify_persisted_prodat_outbound_source_v1',{p_company_id:input.companyId,p_actor_user_id:current,p_message_id:message.id});expect(qualified.actorUserId).toBe(current);expect(bilateralProdatOutboundDraftQualified(qualified)).toBe(true)
 rpc.mockResolvedValue({data:{...capability(),actorUserId:current},error:null});await expect(qualifyPersistedBilateralProdatOutboundOriginal(message as never,current)).rejects.toThrow('original_actor_provenance_required')
 rpc.mockResolvedValue({data:null,error:{message:'prodat_outbound_current_sender_required'}});await expect(qualifyPersistedBilateralProdatOutboundOriginal(message as never,current)).rejects.toMatchObject({message:'prodat_outbound_current_sender_required'})
})

it('native prepare replay keeps immutable historic creator while requiring the actual protected write command',async()=>{
 const current=id(30),message={id:id(11),company_id:input.companyId,environment:'test',direction:'outbound',message_family:'PRODAT',message_code:'Z08',raw_payload:raw,created_by:input.actorUserId,immutable_payload_hash:createHash('sha256').update(raw).digest('hex')}
 rpc.mockResolvedValue({data:{version:1,message,replayed:true},error:null});expect(await createAtomicBilateralProdatOriginal(draft,current)).toEqual(message)
 rpc.mockResolvedValue({data:{version:1,message,replayed:false},error:null});await expect(createAtomicBilateralProdatOriginal(draft,current)).rejects.toThrow('atomic_original_receipt_unqualified')
})
