import {beforeEach,describe,expect,it,vi} from 'vitest'
const rpc=vi.hoisted(()=>vi.fn())
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc}}))
import {readBilateralClosureOperation,prepareBilateralClosureOperation,isQualifiedBilateralClosureBasis} from '@/lib/ediel/production/bilateralProdatClosureOperation'
// Exact finite native RPC decoder boundary only. These data do not authorize a
// database write or declare an authentic archived issuer/reviewer/market state.
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,input={companyId:id(1),actorUserId:id(2),operationId:id(3)}
function row(){return{status:'authorized',version:1,owner:'immutable-bilateral-prodat-closure-operation-v1',...input,environment:'test',periodId:id(4),profileId:id(5),customerId:id(6),siteId:id(7),pointId:id(8),contractId:id(9),contractHash:'a'.repeat(64),externalPoint:'735123456789012345',identityAgency:'9',gridArea:'TES',legalActorId:id(10),legalSenderId:'12345',legalReceiverId:'54321',sourceHash:'b'.repeat(64),sourceGrammarHash:'c'.repeat(64),effectiveAt:'2026-10-16T12:30:00Z',lineItemReference:'LK'+id(3).replaceAll('-',''),documentReference:'LK'+id(3).replaceAll('-',''),customerIdentity:{id:'199001011234',qualifier:'SE2',agency:'260'}}}
beforeEach(()=>rpc.mockReset())
describe('protected LK operation decoder; finite authority port, not native legal proof',()=>{
 it('missing current native own supply/agreement holds without creating an intent or original',async()=>{rpc.mockResolvedValue({data:null,error:null});expect(await readBilateralClosureOperation(input)).toEqual({status:'held',missing:['actual_current_own_supply_and_authenticated_reviewed_lk_agreement']});expect(rpc).toHaveBeenCalledOnce()})
 it('exact native tuple is immutable, while a copied caller JSON has no renderer capability',async()=>{rpc.mockResolvedValue({data:row(),error:null});const value=await readBilateralClosureOperation(input);expect(value.status).toBe('authorized');expect(isQualifiedBilateralClosureBasis(value)).toBe(true);expect(isQualifiedBilateralClosureBasis({...value})).toBe(false);expect(Object.isFrozen(value)).toBe(true);if(value.status==='authorized')expect(Object.isFrozen(value.customerIdentity)).toBe(true)})
 it.each([['tenant',{companyId:id(11)}],['actor',{actorUserId:id(11)}],['operation',{operationId:id(11)}],['owner',{owner:'caller-ready'}],['version',{version:2}],['period',{periodId:'OTHER'}],['profile',{profileId:null}],['source hash',{sourceHash:'other'}],['grammar hash',{sourceGrammarHash:'other'}],['physical LI',{lineItemReference:'SIBLING'}],['document',{documentReference:'SIBLING'}],['minute',{effectiveAt:'2026-10-16T12:30:01Z'}],['ambiguous clock',{effectiveAt:'2026-10-16T12:30:00'}],['identity agency',{customerIdentity:{id:'199001011234',qualifier:'SE2',agency:'9'}}]])('rejects malformed %s before authority can be bound',async(_name,change)=>{rpc.mockResolvedValue({data:{...row(),...change},error:null});await expect(readBilateralClosureOperation(input)).rejects.toThrow('bilateral_closure_operation_result_invalid')})
 it('preparation rereads the actual protected operation and matches its own period/time',async()=>{rpc.mockResolvedValueOnce({data:{status:'prepared',companyId:input.companyId,operationId:input.operationId},error:null}).mockResolvedValueOnce({data:row(),error:null});expect((await prepareBilateralClosureOperation({...input,supplyPeriodId:id(4),effectiveAt:'2026-10-16T12:30:00Z'})).status).toBe('authorized');expect(rpc).toHaveBeenNthCalledWith(2,'ediel_read_bilateral_prodat_closure_operation_v1',{p_company_id:input.companyId,p_actor_user_id:input.actorUserId,p_operation_id:input.operationId})})
 it('wrong returned own period holds no implicit replacement relation',async()=>{rpc.mockResolvedValueOnce({data:{status:'prepared',companyId:input.companyId,operationId:input.operationId},error:null}).mockResolvedValueOnce({data:row(),error:null});await expect(prepareBilateralClosureOperation({...input,supplyPeriodId:id(12),effectiveAt:'2026-10-16T12:30:00Z'})).rejects.toThrow('bilateral_closure_operation_prepare_scope_mismatch')})
 it('native reviewer/current supply hold stays held without a positive copied read',async()=>{rpc.mockResolvedValue({data:{status:'held',companyId:input.companyId,missing:['reviewer_denied']},error:null});expect(await prepareBilateralClosureOperation({...input,supplyPeriodId:id(4),effectiveAt:'2026-10-16T12:30:00Z'})).toEqual({status:'held',missing:['reviewer_denied']});expect(rpc).toHaveBeenCalledOnce()})
})
