import {beforeEach,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:vi.fn()}}))
import {supabaseService} from '@/lib/supabase/service'
import {archiveBilateralCustomerSource,readBilateralCustomerSourceArtifact,readBilateralCustomerSourceBytes,reviewBilateralCustomerSourceArtifact,type BilateralCustomerSourceSubmission} from '@/lib/ediel/production/bilateralCustomerSource'
import {applyConfirmedCustomerSource} from '@/lib/ediel/production/confirmedCustomerSource'
const rpc=vi.mocked(supabaseService.rpc),scope={companyId:'own-company',actorUserId:'actual-actor',artifactId:'opaque-artifact'}
const bytes=Buffer.from('%PDF-1.7\nSYNTHETIC mechanism only: customer clause.\n%%EOF'),sourceHash=createHash('sha256').update(bytes).digest('hex'),claimsHash='b'.repeat(64)
const submission:BilateralCustomerSourceSubmission={sourceMessageId:'actual-original',agreementId:'own-agreement',supplyPeriodId:'own-supply',contractId:'own-contract',source:{bytesBase64:bytes.toString('base64'),mimeType:'application/pdf',reference:'SYNTHETIC',version:'1'}}
beforeEach(()=>rpc.mockReset())
it('archives only original bytes/selectors and preserves authentic bilateral authority hold',async()=>{rpc.mockResolvedValueOnce({data:{status:'archived',artifactId:scope.artifactId,sourceHash,claimsHash,missing:['authentic_current_bilateral_dso_receipt_and_representation']},error:null} as never);expect((await archiveBilateralCustomerSource({...submission,companyId:scope.companyId,actorUserId:scope.actorUserId})).status).toBe('archived');expect(rpc).toHaveBeenCalledWith('ediel_archive_bilateral_customer_source_v1',{p_company_id:scope.companyId,p_actor_user_id:scope.actorUserId,p_submission:submission});expect(JSON.stringify(rpc.mock.calls)).not.toContain('authorizedFields')})
it.each(['','%%%','AA==\n','AB==',Buffer.from('fake PDF').toString('base64')])('rejects invalid bytes before native custody: %j',async encoded=>{await expect(archiveBilateralCustomerSource({...submission,companyId:scope.companyId,actorUserId:scope.actorUserId,source:{...submission.source,bytesBase64:encoded}})).rejects.toThrow('source_bytes_invalid');expect(rpc).not.toHaveBeenCalled()})
it('rejects more than8MB before effects',async()=>{await expect(archiveBilateralCustomerSource({...submission,companyId:scope.companyId,actorUserId:scope.actorUserId,source:{...submission.source,bytesBase64:Buffer.alloc(8*1024*1024+1).toString('base64')}})).rejects.toThrow('source_bytes_invalid');expect(rpc).not.toHaveBeenCalled()})
it('metadata refuses foreign or raw-byte exposure',async()=>{rpc.mockResolvedValueOnce({data:{status:'held',artifactId:'foreign'},error:null} as never);await expect(readBilateralCustomerSourceArtifact(scope)).rejects.toThrow('scope_invalid');rpc.mockResolvedValueOnce({data:{status:'held',artifactId:scope.artifactId,sourceMessageId:submission.sourceMessageId,sourceHash,claimsHash,byteLength:bytes.length,missing:[],bytesBase64:bytes.toString('base64')},error:null} as never);await expect(readBilateralCustomerSourceArtifact(scope)).rejects.toThrow('metadata_invalid')})
it('binary read verifies scoped original hash and propagates current revoked access',async()=>{rpc.mockResolvedValueOnce({data:{status:'held',artifactId:scope.artifactId,mimeType:'application/pdf',sourceHash,byteLength:bytes.length,bytesBase64:bytes.toString('base64')},error:null} as never);expect(Buffer.from((await readBilateralCustomerSourceBytes(scope)).bytes)).toEqual(bytes);rpc.mockResolvedValueOnce({data:null,error:Error('bilateral_customer_source_read_actor_forbidden')} as never);await expect(readBilateralCustomerSourceBytes(scope)).rejects.toThrow('actor_forbidden')})
it('separate review returns incoming original authority and creates no death/outbound event',async()=>{const review={sourceHash,claimsHash,decision:'approve' as const,reason:'SYNTHETIC separate review',clause:{locator:'page1',quote:'customer clause'}};rpc.mockResolvedValueOnce({data:{status:'authorized',artifactId:scope.artifactId,sourceMessageId:submission.sourceMessageId},error:null} as never);const result=await reviewBilateralCustomerSourceArtifact({...scope,...review});expect(result).not.toHaveProperty('eventId');expect(rpc).toHaveBeenCalledWith('ediel_review_bilateral_customer_source_v1',{p_company_id:scope.companyId,p_actor_user_id:scope.actorUserId,p_artifact_id:scope.artifactId,p_review:review})})
it('incoming actual owner accepts only a distinct native bilateral receipt with committed availability',async()=>{rpc.mockResolvedValueOnce({data:{applied:true,owner:'confirmed-customer-source-v1',sourceMessageId:submission.sourceMessageId,appliedCount:1,payloadHash:sourceHash,eventId:null,authority:{kind:'bilateral',artifactId:scope.artifactId},objects:[{meteringPointId:'actual-point',siteId:'own-site',effectiveAt:'2026-10-01T12:00Z',sourceReceivedAt:'2026-10-01T12:01Z'}]},error:null} as never).mockResolvedValueOnce({data:{owner:'confirmed-customer-source-availability-v1',sourceMessageId:submission.sourceMessageId,payloadHash:sourceHash,availableAt:'2026-10-01T12:03Z'},error:null} as never);const result=await applyConfirmedCustomerSource({companyId:scope.companyId,actorUserId:scope.actorUserId,sourceMessageId:submission.sourceMessageId});expect(result.applied).toBe(true);expect(rpc).toHaveBeenCalledTimes(2)})
