import {beforeEach,expect,it,vi} from 'vitest'
const state=vi.hoisted(()=>({rpc:vi.fn(),queue:vi.fn()}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:state.rpc}}))
vi.mock('@/lib/ediel/flows/prodatCustomerLifeEvent',()=>({prepareAndQueueCustomerLifeEventZ09:state.queue}))
import {archiveRequestedCustomerChangeSource,readRequestedCustomerChangeSourceArtifact,readRequestedCustomerChangeSourceBytes,reviewRequestedCustomerChangeSourceArtifact} from '@/lib/ediel/production/requestedCustomerChangeSource'
import {prepareAndQueueRequestedCustomerChange} from '@/lib/ediel/flows/prodatRequestedCustomerChange'
import {requestedCustomerChangeSubmission} from '@/lib/ediel/production/requestedCustomerChangeHttp'
const c='00000000-0000-4000-8000-000000000001',actor='00000000-0000-4000-8000-000000000002',artifact='00000000-0000-4000-8000-000000000003',event='00000000-0000-4000-8000-000000000004'
const scope={companyId:c,actorUserId:actor,artifactId:artifact},pdf=Buffer.from('%PDF-1.7\nSYNTHETIC original only\n%%EOF')
const input={companyId:c,actorUserId:actor,environment:'test' as const,agreementId:c,supplyPeriodId:c,contractId:c,rawPayload:"UNH+1+PRODAT:D:97A:UN:E2SE6A'",source:{bytesBase64:pdf.toString('base64'),mimeType:'application/pdf' as const,reference:'synthetic original',version:'1'}}
beforeEach(()=>{state.rpc.mockReset();state.queue.mockReset()})
it('archives bounded original bytes and selectors through native owner without caller authority flags',async()=>{state.rpc.mockResolvedValue({data:{status:'archived',artifactId:artifact,sourceHash:'a'.repeat(64),claimsHash:'b'.repeat(64),missing:[]},error:null});await archiveRequestedCustomerChangeSource(input);expect(state.rpc).toHaveBeenCalledWith('ediel_archive_requested_customer_change_v1',{p_company_id:c,p_actor_user_id:actor,p_submission:{...input,companyId:undefined,actorUserId:undefined}})})
it('rejects malformed or oversized source bytes before RPC',async()=>{await expect(archiveRequestedCustomerChangeSource({...input,source:{...input.source,bytesBase64:Buffer.from('bad').toString('base64')}})).rejects.toThrow('bytes_invalid');await expect(archiveRequestedCustomerChangeSource({...input,rawPayload:'x'.repeat(1048577)})).rejects.toThrow('raw_invalid');expect(state.rpc).not.toHaveBeenCalled()})
it('metadata never accepts raw party/source bytes from native response',async()=>{state.rpc.mockResolvedValue({data:{status:'archived',artifactId:artifact,bytesBase64:input.source.bytesBase64},error:null});await expect(readRequestedCustomerChangeSourceArtifact(scope)).rejects.toThrow('metadata_invalid')})
it('actual bytes require same source hash/length and actor-scoped RPC each time',async()=>{state.rpc.mockResolvedValue({data:{status:'archived',artifactId:artifact,bytesBase64:input.source.bytesBase64,sourceHash:'a'.repeat(64),mimeType:'application/pdf',byteLength:pdf.length},error:null});await expect(readRequestedCustomerChangeSourceBytes(scope)).rejects.toThrow('bytes_invalid');expect(state.rpc.mock.calls[0][1]).toMatchObject({p_actor_user_id:actor,p_include_bytes:true})})
it('review binds exact current artifact/hash/actor and has no approved client selector',async()=>{state.rpc.mockResolvedValue({data:{status:'held',artifactId:artifact,missing:['authentic_current_outgoing_customer_mandate']},error:null});expect(await reviewRequestedCustomerChangeSourceArtifact({...scope,sourceHash:'a'.repeat(64),claimsHash:'b'.repeat(64),decision:'approve',reason:'review exact original'})).toMatchObject({status:'held'});expect(state.rpc.mock.calls[0][1]).toMatchObject({p_actor_user_id:actor,p_artifact_id:artifact})})
it('held current native source never reaches actual life-event queue',async()=>{state.rpc.mockResolvedValue({data:{status:'held',artifactId:artifact,missing:['authentic_current_outgoing_customer_mandate']},error:null});expect(await prepareAndQueueRequestedCustomerChange(scope)).toMatchObject({status:'held'});expect(state.queue).not.toHaveBeenCalled()})
it('only native artifact→event binding reaches the existing atomic native original gateway',async()=>{state.rpc.mockResolvedValue({data:{status:'authorized',artifactId:artifact,eventId:event},error:null});state.queue.mockResolvedValue({status:'queued',message:{id:c}});await prepareAndQueueRequestedCustomerChange({...scope,preferredRouteId:c});expect(state.queue).toHaveBeenCalledWith({companyId:c,actorUserId:actor,eventId:event,preferredRouteId:c})})
it('native wrong artifact or incoming-source ID cannot authorize an outgoing queue',async()=>{state.rpc.mockResolvedValue({data:{status:'authorized',artifactId:c,sourceMessageId:event},error:null});await expect(prepareAndQueueRequestedCustomerChange(scope)).rejects.toThrow('scope_invalid');expect(state.queue).not.toHaveBeenCalled()})
it('strict HTTP body rejects company/actor/death/approved/source capability assertions',()=>{const body={agreementId:input.agreementId,supplyPeriodId:input.supplyPeriodId,contractId:input.contractId,rawPayload:input.rawPayload,source:input.source};expect(requestedCustomerChangeSubmission.safeParse(body).success).toBe(true);for(const extra of ['companyId','actorUserId','environment','approved','death','bilateralCapabilityVerified'])expect(requestedCustomerChangeSubmission.safeParse({...body,[extra]:true}).success).toBe(false)})
