import {beforeEach,describe,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
const mocks=vi.hoisted(()=>({guard:vi.fn(),operational:vi.fn(),rpc:vi.fn(),method:vi.fn(),production:vi.fn()}))
vi.mock('@/lib/admin/guards',()=>({requireAdminActionAccess:mocks.guard}))
vi.mock('@/lib/tenant/governance',()=>({requireCompanyOperationalForWrites:mocks.operational}))
vi.mock('@/lib/supabase/server',()=>({createSupabaseServerClient:async()=>({rpc:mocks.rpc})}))
vi.mock('@/lib/ediel/flows/prodatMeteringMethodChange',()=>({prepareAndQueueMeteringMethodChangeZ09:mocks.method}))
vi.mock('@/lib/ediel/flows/prodatProductionContract',()=>({prepareAndQueueProductionContractZ09:mocks.production}))
import {archiveContractOriginalSource,prepareContractOriginalSource,reviewContractOriginalSource} from '@/lib/ediel/production/contractOriginalSourceIntake'
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex')
const artifact={status:'authorized',artifactId:id(4),kind:'metering_method_event',contractId:id(5),environment:'test',sourceId:id(6),sourceHash:'a'.repeat(64),agreementHash:'b'.repeat(64),claimsHash:'c'.repeat(64),nativeScope:{},claims:{},submittedBy:id(7),capturedAt:'2026-10-01',missing:[]}
beforeEach(()=>{vi.clearAllMocks();mocks.guard.mockResolvedValue({companyId:id(1),userId:id(2)});mocks.rpc.mockResolvedValue({data:artifact,error:null});mocks.method.mockResolvedValue({status:'queued',message:{id:id(8)}});mocks.production.mockResolvedValue({status:'queued',message:{id:id(8)}})})
describe('contract original authenticated producer adapter',()=>{
 it('derives tenant/session actor and routes the native re-read ID to the established F/G producer',async()=>{await prepareContractOriginalSource(id(4));expect(mocks.rpc).toHaveBeenCalledWith('ediel_read_contract_original_source_v1',{p_company_id:id(1),p_actor_user_id:id(2),p_artifact_id:id(4)});expect(mocks.method).toHaveBeenCalledWith({companyId:id(1),actorUserId:id(2),eventId:id(6)});expect(mocks.production).not.toHaveBeenCalled()})
 it('routes production source through existing protected production producer',async()=>{mocks.rpc.mockResolvedValue({data:{...artifact,kind:'production_contract_event'},error:null});await prepareContractOriginalSource(id(4));expect(mocks.production).toHaveBeenCalledWith({companyId:id(1),actorUserId:id(2),eventId:id(6)})})
 it('honors revoked or held qualification at the actual prepare call',async()=>{mocks.rpc.mockResolvedValue({data:{...artifact,status:'held',sourceId:null,missing:['current_qualified_contract_original']},error:null});expect(await prepareContractOriginalSource(id(4))).toEqual({status:'held',missing:['current_qualified_contract_original']});expect(mocks.method).not.toHaveBeenCalled();expect(mocks.production).not.toHaveBeenCalled()})
 it('stops before RPC with no current tenant and before producer on a crossed artifact result',async()=>{mocks.guard.mockResolvedValue({companyId:null,userId:id(2)});await expect(prepareContractOriginalSource(id(4))).rejects.toThrow('current_tenant');expect(mocks.rpc).not.toHaveBeenCalled();mocks.guard.mockResolvedValue({companyId:id(1),userId:id(2)});mocks.rpc.mockResolvedValue({data:{...artifact,artifactId:id(9)},error:null});await expect(prepareContractOriginalSource(id(4))).rejects.toThrow('read_result');expect(mocks.method).not.toHaveBeenCalled()})
 it('submits exact immutable bytes and verifies the native archive hashes',async()=>{const pdf=Buffer.from('SYNTHETIC PDF'),source=Buffer.from('SYNTHETIC signed original'),input={contractId:id(5),environment:'test' as const,kind:'masterdata_declaration' as const,agreementBase64:pdf.toString('base64'),sourceBase64:source.toString('base64'),issuerKeyId:null,representationId:null,signatureHex:null};mocks.rpc.mockResolvedValue({data:{status:'archived',artifactId:id(4),kind:input.kind,sourceHash:hash(source),agreementHash:hash(pdf),claimsHash:'c'.repeat(64),missing:['issuer']},error:null});await archiveContractOriginalSource(input);expect(mocks.rpc).toHaveBeenCalledWith('ediel_archive_contract_original_source_v1',expect.objectContaining({p_company_id:id(1),p_actor_user_id:id(2),p_submission:{agreementBase64:input.agreementBase64,sourceBase64:input.sourceBase64,issuerKeyId:null,representationId:null,signatureHex:null}}));mocks.rpc.mockResolvedValue({data:{status:'archived',artifactId:id(4),kind:input.kind,sourceHash:'d'.repeat(64),agreementHash:hash(pdf),claimsHash:'c'.repeat(64),missing:[]},error:null});await expect(archiveContractOriginalSource(input)).rejects.toThrow('archive_result')})
 it('reviews the exact archive hashes through authenticated native RPC without caller actor flags',async()=>{mocks.rpc.mockResolvedValue({data:{status:'authorized',artifactId:id(4),kind:'masterdata_declaration',sourceId:id(6),replay:false},error:null});const input={artifactId:id(4),sourceHash:'a'.repeat(64),agreementHash:'b'.repeat(64),claimsHash:'c'.repeat(64),decision:'approve' as const,reason:'Independent source review'};await reviewContractOriginalSource(input);expect(mocks.guard).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write','ediel.source.review']});expect(mocks.rpc).toHaveBeenCalledWith('ediel_review_contract_original_source_v1',{p_company_id:id(1),p_actor_user_id:id(2),p_artifact_id:id(4),p_review:{sourceHash:input.sourceHash,agreementHash:input.agreementHash,claimsHash:input.claimsHash,decision:'approve',reason:input.reason}})})
})
