import {beforeEach,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
import {EdifactEnvelopeCodec} from '@/lib/ediel/core/edifactEnvelopeCodec'
import type {EdielMessageRow} from '@/lib/ediel/types'
const io=vi.hoisted(()=>({endpoint:vi.fn(),actor:vi.fn(),rpc:vi.fn()}))
vi.mock('@/lib/ediel/ack/technicalSyntaxAuthority',()=>({readEdielTechnicalSourceEndpoint:io.endpoint}))
vi.mock('@/lib/ediel/services/authorization',()=>({assertEdielTenantActor:io.actor}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:io.rpc}}))
import {readExistingAckBeforeDraft} from '@/lib/ediel/core/ackDraftSource'
const company='22222222-2222-4222-8222-222222222222',id='11111111-1111-4111-8111-111111111111'
const source={id,company_id:null,environment:'test',direction:'inbound',message_standard:'edifact',message_family:'PRODAT',raw_payload:"UNB+UNOC:3+REMOTE:14+LOCAL:14+260930:1200+I++23-DDQ-PRODAT++++1'UNH+M+PRODAT:D:97A:UN:E2SE6A'BGM+BAD+D+9+AB'UNT+3+M'UNZ+1+I'"} as EdielMessageRow
const hash=createHash('sha256').update(source.raw_payload!).digest('hex')
function endpoint(extra={}){return {kind:'technical_endpoint_only',companyId:company,environment:'test',sourceMessageId:id,sourceHash:hash,authorizesBusinessEffect:false,...extra}}
function result(ackFamily='APERAK',resultCompany=company){const raw=EdifactEnvelopeCodec.encode({sender:'LOCAL',receiver:'REMOTE',environment:'test',applicationReference:'23-DDQ-PRODAT',interchangeReference:'ACKI',acknowledgementRequest:false,messages:[{messageReference:'A',messageTypeToken:ackFamily==='CONTRL'?'CONTRL:2:2:UN':'APERAK:D:96A:UN:E2SE6A',businessSegments:ackFamily==='CONTRL'?['UCI+I+REMOTE:14+LOCAL:14+4']:['BGM+++27','RFF+ACW:D','ERC+42::260','FTX+AAO++202::260+Felaktigt Meddelandenamn BAD']}]});return {data:{version:2,executionActorUserId:'actor',executionPhase:'prepare',sourceMessageId:id,sourcePayloadHash:hash,companyId:resultCompany,environment:'test',originals:[{status:'qualified',message:{id:'retained',direction:'outbound',company_id:resultCompany,environment:'test',message_family:ackFamily,status:'failed',raw_payload:raw},payloadHash:createHash('sha256').update(raw).digest('hex')}]},error:null}}
beforeEach(()=>{vi.clearAllMocks();io.endpoint.mockResolvedValue(endpoint());io.actor.mockResolvedValue(undefined);io.rpc.mockResolvedValue(result())})
it('reads the protected common P27 original via actual technical company while leaving source company null',async()=>{expect(await readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:source,ackFamily:'APERAK',outcome:'negative',ackScope:'message'})).toMatchObject({id:'retained',status:'failed',ack_outcome:'negative'});expect(io.actor).toHaveBeenCalledWith({companyId:company,actorUserId:'actor',permission:'communication.write'});expect(source.company_id).toBeNull()})
it('keeps a retained C response on the same exact endpoint and current local WRITE gate (no test alias, as native 124000)',async()=>{io.rpc.mockResolvedValue(result('CONTRL'));expect(await readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:source,ackFamily:'CONTRL',outcome:'negative'})).toMatchObject({id:'retained'});expect(io.actor).toHaveBeenCalledWith({companyId:company,actorUserId:'actor',permission:'communication.write'})})
it.each([{sourceHash:'a'.repeat(64)},{environment:'production'},{sourceMessageId:'other'}])('refuses a mismatching technical original before tenant authorization',async wrong=>{io.endpoint.mockResolvedValue(endpoint(wrong));await expect(readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:source,ackFamily:'APERAK'})).rejects.toThrow('source_scope_mismatch');expect(io.actor).not.toHaveBeenCalled();expect(io.rpc).not.toHaveBeenCalled()})
it('refuses a different protected original company and cannot override actor denial',async()=>{io.rpc.mockResolvedValue(result('APERAK','33333333-3333-4333-8333-333333333333'));await expect(readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:source,ackFamily:'APERAK'})).rejects.toThrow('original_source_mismatch');io.actor.mockRejectedValue(new Error('actor denied'));await expect(readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:source,ackFamily:'APERAK'})).rejects.toThrow('actor denied')})
it('holds null-company ERR rather than treating a technical endpoint as a legal business issuer',async()=>{await expect(readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:source,ackFamily:'UTILTS_ERR'})).rejects.toThrow('source_scope_mismatch');expect(io.endpoint).not.toHaveBeenCalled()})

it('does not widen the ordinary company-attributed business ACK actor gate',async()=>{await readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:{...source,company_id:company},ackFamily:'APERAK'});expect(io.actor).toHaveBeenCalledWith({companyId:company,actorUserId:'actor',permission:'communication.write'});expect(io.endpoint).not.toHaveBeenCalled()})
it('passes the actual actor and prepare phase to the V2 native reader',async()=>{await readExistingAckBeforeDraft({actorUserId:'actor',sourceMessage:source,ackFamily:'APERAK',outcome:'negative',ackScope:'message'});expect(io.rpc).toHaveBeenCalledWith('gridex_read_outbound_acks_for_source_v2',{p_source_message_id:id,p_ack_family:'APERAK',p_actor_user_id:'actor',p_phase:'prepare'})})
