import{beforeEach,expect,it,vi}from'vitest'
const rpc=vi.hoisted(()=>vi.fn());vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc}}))
import{prepareCustomerMasterdataSource,bindCustomerMasterdataValidationContext,isQualifiedCustomerMasterdataValidationContext}from'@/lib/ediel/production/customerMasterdataSource'
const input={companyId:'company-A',customerId:'customer-A',actorUserId:'actor-A',environment:'test' as const,asOf:'2026-10-01T12:00:00Z'}
const result={status:'authorized',companyId:input.companyId,customerId:input.customerId,environment:input.environment,asOf:input.asOf,sourceKind:'registered_customer_address',sourceReference:'address-A',sourceDigest:'a'.repeat(64),sourceContextId:'00000000-0000-4000-8000-000000000001',customerIdentity:{id:'5566778899',qualifier:'SE1',agency:'260'},endUserMasterdata:{nameParts:['Literal name'],streetParts:['Own registered street'],postalCode:'12345',city:'Own city',country:'SE'}}
beforeEach(()=>rpc.mockReset())
it('passes exact owned source instant and preserves literal UD separately from site/invoice',async()=>{rpc.mockResolvedValue({data:result,error:null});expect(await prepareCustomerMasterdataSource(input)).toEqual(result);expect(rpc).toHaveBeenCalledWith('ediel_prepare_customer_masterdata_v1',{p_company_id:input.companyId,p_customer_id:input.customerId,p_actor_user_id:input.actorUserId,p_as_of:input.asOf,p_environment:'test'})})
it.each([{companyId:'other'},{customerId:'other'},{environment:'production'},{asOf:'2026-10-02T12:00:00Z'},{sourceContextId:null},{endUserMasterdata:{...result.endUserMasterdata,country:''}},{endUserMasterdata:{...result.endUserMasterdata,streetParts:['x'.repeat(36)]}},{customerIdentity:{...result.customerIdentity,qualifier:'SE3'}}])('holds a changed source tuple %j',async changed=>{rpc.mockResolvedValue({data:{...result,...changed},error:null});await expect(prepareCustomerMasterdataSource(input)).rejects.toThrow('source_result_invalid')})
it('keeps absent/ambiguous own source held and propagates native failures',async()=>{rpc.mockResolvedValueOnce({data:{status:'held',missing:['unique_owned_registered_customer_address']},error:null});await expect(prepareCustomerMasterdataSource(input)).rejects.toThrow('source_held:unique_owned');const error=Error('source_epoch_changed');rpc.mockResolvedValueOnce({data:null,error});await expect(prepareCustomerMasterdataSource(input)).rejects.toBe(error)})
it('does not ask for source with an unbound local DATE',async()=>{await expect(prepareCustomerMasterdataSource({...input,asOf:'2026-10-01'})).rejects.toThrow('source_date_required');expect(rpc).not.toHaveBeenCalled()})

it('keeps prepared projection and validation context opaque across JSON/caller copies',async()=>{rpc.mockResolvedValue({data:structuredClone(result),error:null});const projection=await prepareCustomerMasterdataSource(input);const values={kind:'customer_masterdata' as const,companyId:input.companyId,customerId:input.customerId,environment:input.environment,rawPayload:'exact raw',intentId:'own intent',routeId:'own route',projection};const context=bindCustomerMasterdataValidationContext(values);expect(isQualifiedCustomerMasterdataValidationContext(context)).toBe(true);expect(isQualifiedCustomerMasterdataValidationContext({...context})).toBe(false);expect(()=>bindCustomerMasterdataValidationContext({...values,projection:structuredClone(projection)})).toThrow('context_unqualified');expect(()=>bindCustomerMasterdataValidationContext({...values,companyId:'other'})).toThrow('context_unqualified')})
