import {beforeEach,expect,it,vi} from 'vitest'
const rpc=vi.hoisted(()=>vi.fn())
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc}}))
// Pure dated projection mechanism fixtures; no native approval is asserted.
vi.mock('@/lib/ediel/sources/structuralSourceReadset',async()=>{const actual=await vi.importActual<typeof import('@/lib/ediel/sources/structuralSourceReadset')>('@/lib/ediel/sources/structuralSourceReadset');return {...actual,reviewedBusinessFor:(r:{sources:{sourceMessageId:string;objects:{business:unknown}[]}[]},id:string)=>r.sources.find(s=>s.sourceMessageId===id)?.objects[0].business}})
import {projectAiListHistory,type AiListHistoryScope,type AiListSupplyPeriod} from '@/lib/ediel/aiListHistory'
import {readConfirmedCustomerHistory,type ConfirmedCustomerHistory} from '@/lib/ediel/production/confirmedCustomerHistory'
import {emptySourceDecisionTimeline} from '@/lib/ediel/sources/receivedSourceDecisionTimeline'
import type {StructuralReadset} from '@/lib/ediel/sources/structuralSourceReadset'
import {prodatMarketMinuteToUtc} from '@/lib/ediel/prodat/render/dates'
const at=(day:string)=>prodatMarketMinuteToUtc(`${day}0000`)!
const scope:AiListHistoryScope={companyId:'company',environment:'test',customerId:'customer',siteId:'site',legalSupplier:'12345',legalNetwork:'54321',fromDate:'20261001',toDate:'20261101',cutoffAt:'2026-11-02T12:00:00.000000Z'}
const object={messageIndex:0,messageReference:'M',objectId:'735123456789012345',identityAgency:'9',registers:[]},period:AiListSupplyPeriod={id:'period',company_id:'company',customer_id:'customer',metering_point_id:'point',start_date:'2026-10-01',end_date:null}
function fixture():StructuralReadset{
 const versions=['baseline','customer'].map((id,n)=>({sourceMessageId:id,payloadHash:'a'.repeat(64),assessmentId:`${id}-assessment`,factsHash:'b'.repeat(64),availableAt:at('20261001'),disposition:n?'unavailable':'accepted',replaces:null,
 coverage:n?null:{kind:'post_ledger_supply',baselineSourceMessageId:'baseline',baselineAssessmentId:'baseline-assessment',baselineFactsHash:'b'.repeat(64),supplyPeriodId:'period',switchRequestId:'switch',switchCreatedAt:at('20260930'),outboundSourceMessageId:'outbound',outboundCreatedAt:at('20260930'),validFrom:at('20261001'),validTo:null},
 wire:{object,messageCode:n?'Z06':'Z04',businessCase:n?'customer_only':'supply_baseline',functionCode:'9',documentReference:id,caseReference:'case',effectiveFrom:{fieldNumber:n?'216':'210',marketMinute:n?'202610100000':'202610010000',utc:at(n?'20261010':'20261001')},contractStartMinute:'202610010000',legalSender:'54321',legalReceiver:'12345',transportSender:'54321',transportReceiver:'12345',meterNumber:'old',oldMeterNumber:null,registers:[{position:1,registerId:'901'}]}}))
 return {timeline:{...emptySourceDecisionTimeline(),status:'inspected',boundedReadComplete:true,snapshotId:'snapshot',readsetHash:'c'.repeat(64),cutoffAt:scope.cutoffAt,ledgerStartedAt:at('20260901')},versions,closures:[],closureBlockers:[],correctionContextBlockers:[],unresolvedSources:false,
 sources:versions.map((v,n)=>({sourceMessageId:v.sourceMessageId,payloadHash:v.payloadHash,asOf:null,assessments:[],rawPayload:`UNB+UNOC:3+54321:14+12345:14+261001:1200+I+23-DDQ-PRODAT'UNH+M+PRODAT:D:97A:UN:E2SE6A'BGM+${v.wire.messageCode}+${v.sourceMessageId}+9'LIN+1++735123456789012345:::9'RFF+Z05:NET'RFF+MG:old'NAD+UD+199001011234:SE2:260++${n?'Person Estate':'Original Person'}'NAD+IT+SITE+++Original Street+City++12345+SE'NAD+Z02+BRP:160:SVK'UNT+10+M'UNZ+1+I'`,objects:[{object,disposition:n?'unavailable':'accepted',reasons:[],party:null,business:n?null:{companyId:'company',environment:'test',customerId:'customer',meteringPointId:'point',siteId:'site'}}]}))} as unknown as StructuralReadset
}
function receipt():ConfirmedCustomerHistory{return{owner:'confirmed-customer-facet-snapshot-v1',companyId:'company',environment:'test',customerId:'customer',siteId:'site',snapshotId:'snapshot',readsetHash:'c'.repeat(64),cutoffAt:scope.cutoffAt,versions:[{sourceMessageId:'customer',payloadHash:'a'.repeat(64),companyId:'company',environment:'test',customerId:'customer',siteId:'site',meteringPointId:'point',supplyPeriodId:'period',objectId:object.objectId,identityAgency:'9',legalSender:'54321',legalReceiver:'12345',effectiveAt:at('20261010'),marketMinute:'202610100000',availableAt:at('20261011'),party:{id:'199001011234',qualifier:'SE2',agency:'260',name:'Person Estate'}}]}}
beforeEach(()=>rpc.mockReset())
async function read(data=receipt(),readset=fixture()){rpc.mockResolvedValue({data,error:null});return readConfirmedCustomerHistory({scope,actorUserId:'actor',readset})}
it('real server reader binds the same snapshot and preserves structural state/address through a dated customer split',async()=>{const sources=fixture(),proof=await read(receipt(),sources),r=projectAiListHistory(scope,[period],sources,proof);expect(r.details.map(x=>[x.elanvandarNamn,x.franDatum,x.tillDatum,x.anlaggningsAdress])).toEqual([['Original Person',null,'20261010','Original Street'],['Person Estate','20261010',null,'Original Street']]);expect(r.evidence.rowSources[1].customerSourceMessageId).toBe('customer');expect(r.evidence.sourceMessageIds).toContain('customer');expect(rpc).toHaveBeenCalledWith('ediel_confirmed_customer_snapshot_v1',{p_company_id:'company',p_actor_user_id:'actor',p_snapshot_id:'snapshot',p_readset_hash:'c'.repeat(64),p_customer_id:'customer',p_site_id:'site'})})
it('unowned, copied and mutated JSON cannot remove the dated customer hold',async()=>{const sources=fixture(),proof=await read(receipt(),sources);expect(()=>projectAiListHistory(scope,[period],sources,JSON.parse(JSON.stringify(proof)))).toThrow('dated_customer_change_owner_missing');proof.versions[0].party.name='FORGED';expect(()=>projectAiListHistory(scope,[period],sources,proof)).toThrow('dated_customer_change_owner_missing');expect(()=>projectAiListHistory(scope,[period],sources,receipt())).toThrow('dated_customer_change_owner_missing')})
it('holds an actual missing/current revoked facet rather than exporting the old customer',async()=>{const sources=fixture(),proof=await read({...receipt(),versions:[]},sources);expect(()=>projectAiListHistory(scope,[period],sources,proof)).toThrow('dated_customer_change_owner_missing')})
it('rejects foreign/native snapshot scope before the projection',async()=>{await expect(read({...receipt(),siteId:'foreign'})).rejects.toThrow('history_unconfirmed');await expect(read({...receipt(),versions:[{...receipt().versions[0],payloadHash:'b'.repeat(64)}]})).rejects.toThrow('facet_invalid')})
it('retains minute/date representability and original identity fences',async()=>{const sources=fixture(),r=receipt();r.versions[0].marketMinute='202610101200';r.versions[0].effectiveAt=prodatMarketMinuteToUtc('202610101200')!;sources.versions[1].wire.effectiveFrom={fieldNumber:'216',marketMinute:'202610101200',utc:r.versions[0].effectiveAt};const proof=await read(r,sources);expect(()=>projectAiListHistory(scope,[period],sources,proof)).toThrow('date_only_customer_boundary_unrepresentable')})
