import {beforeEach,describe,expect,it,vi} from 'vitest'
import {NextRequest} from 'next/server'
const io=vi.hoisted(()=>({access:vi.fn(),archive:vi.fn(),read:vi.fn(),bytes:vi.fn(),review:vi.fn(),apply:vi.fn()}))
vi.mock('@/lib/admin/apiGuards',()=>({requireAdminApiAccess:io.access}))
vi.mock('@/lib/ediel/production/bilateralCustomerSource',()=>({archiveBilateralCustomerSource:io.archive,readBilateralCustomerSourceArtifact:io.read,readBilateralCustomerSourceBytes:io.bytes,reviewBilateralCustomerSourceArtifact:io.review}))
vi.mock('@/lib/ediel/safeApplyReview',()=>({approveSafeMasterdataChanges:io.apply}))
import {POST as archive} from '@/app/api/ediel/customer-source-agreements/route'
import {POST as review} from '@/app/api/ediel/customer-source-agreements/[artifactId]/review/route'
import {POST as apply} from '@/app/api/ediel/customer-source-agreements/[artifactId]/apply/route'
import {GET as source} from '@/app/api/ediel/customer-source-agreements/[artifactId]/source/route'
const id='00000000-0000-4000-8000-000000000001',sourceId='00000000-0000-4000-8000-000000000002',hash='a'.repeat(64),ctx={params:Promise.resolve({artifactId:id})}
const submission={sourceMessageId:sourceId,agreementId:id,supplyPeriodId:id,contractId:id,source:{bytesBase64:Buffer.from('%PDF-1.7 Original').toString('base64'),mimeType:'application/pdf',reference:'Original agreement',version:'1'}}
const request=(body:unknown)=>new NextRequest('http://localhost/api/ediel/customer-source-agreements',{method:'POST',body:JSON.stringify(body)})
beforeEach(()=>{vi.clearAllMocks();io.access.mockResolvedValue({guard:{companyId:'current-company',userId:'current-user'}});io.archive.mockResolvedValue({status:'archived',artifactId:id,sourceHash:hash,claimsHash:hash,missing:[]});io.read.mockResolvedValue({status:'authorized',artifactId:id,sourceMessageId:sourceId,missing:[]});io.review.mockResolvedValue({status:'authorized',artifactId:id,sourceMessageId:sourceId});io.apply.mockResolvedValue({status:'applied',messageId:sourceId,appliedCount:1});io.bytes.mockResolvedValue({mimeType:'application/pdf',bytes:Buffer.from('%PDF-1.7 Original'),sourceHash:hash})})
describe('private bilateral customer source HTTP consumers',()=>{
 it('binds archive to authenticated current company/actor and returns private metadata',async()=>{const r=await archive(request(submission));expect(r.status).toBe(201);expect(r.headers.get('cache-control')).toBe('private, no-store');expect(io.access).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write']});expect(io.archive).toHaveBeenCalledExactlyOnceWith({...submission,companyId:'current-company',actorUserId:'current-user'})})
 it.each([{companyId:'foreign'},{actorUserId:'forged'},{environment:'production'},{verified:true},{eventId:id},{customerIdentity:{id:'other'}},{provenance:{approved:true}},{allowedFields:['billing_city']}])('refuses caller authority before any archive %j',async extra=>{const r=await archive(request({...submission,...extra}));expect(r.status).toBe(400);expect(io.archive).not.toHaveBeenCalled()})
 it('bounds a streaming body even without Content-Length',async()=>{const r=await apply(request({padding:'x'.repeat(2048)}),ctx);expect(r.status).toBe(413);expect(io.read).not.toHaveBeenCalled();expect(io.apply).not.toHaveBeenCalled()})
 it('requires separate review grants and immutable original hashes',async()=>{const command={sourceHash:hash,claimsHash:hash,decision:'approve',reason:'Independent review',clause:{locator:'page 1',quote:'Exact original clause'}};expect((await review(request(command),ctx)).status).toBe(200);expect(io.access).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write','ediel.source.review']});expect(io.review).toHaveBeenCalledExactlyOnceWith({...command,companyId:'current-company',actorUserId:'current-user',artifactId:id})})
 it('resolves apply source from current private artifact without caller source/message/event',async()=>{const r=await apply(request({}),ctx);expect(r.status).toBe(200);expect(io.read).toHaveBeenCalledExactlyOnceWith({companyId:'current-company',actorUserId:'current-user',artifactId:id});expect(io.apply).toHaveBeenCalledExactlyOnceWith({actorUserId:'current-user',edielMessageId:sourceId});expect(await r.json()).toEqual({status:'applied',messageId:sourceId,appliedCount:1})})
 it.each([{sourceMessageId:'foreign'},{eventId:id},{force:true}])('rejects injected apply authority before any current-source read %j',async body=>{expect((await apply(request(body),ctx)).status).toBe(400);expect(io.read).not.toHaveBeenCalled();expect(io.apply).not.toHaveBeenCalled()})
 it('holds unreviewed archive and never calls the customer writer',async()=>{io.read.mockResolvedValue({status:'held',missing:['issuer_required']});const r=await apply(request({}),ctx);expect(r.status).toBe(409);expect(io.apply).not.toHaveBeenCalled()})
 it('rejects execution-time private source/grant revocation without exposing SQL',async()=>{io.read.mockRejectedValue(Error('PRIVATE SQL original'));const r=await apply(request({}),ctx);expect(r.status).toBe(403);expect(await r.text()).not.toContain('PRIVATE');expect(io.apply).not.toHaveBeenCalled()})
 it('downloads actual hash-checked bytes with private headers and no shared caching',async()=>{const r=await source(new NextRequest('http://localhost/source'),ctx);expect(r.headers.get('cache-control')).toBe('private, no-store');expect(r.headers.get('x-content-type-options')).toBe('nosniff');expect(r.headers.get('etag')).toBe(`"${hash}"`);expect(await r.text()).toBe('%PDF-1.7 Original');expect(io.bytes).toHaveBeenCalledExactlyOnceWith({companyId:'current-company',actorUserId:'current-user',artifactId:id})})
 it('does no domain work when current selected company is absent',async()=>{io.access.mockResolvedValue({guard:{companyId:null,userId:'current-user'}});expect((await archive(request(submission))).status).toBe(403);expect(io.archive).not.toHaveBeenCalled()})
 it('reports unavailable authentication without falling back to service authority',async()=>{io.access.mockRejectedValue(Error('PRIVATE auth'));const r=await archive(request(submission));expect(r.status).toBe(503);expect(await r.text()).not.toContain('PRIVATE');expect(io.archive).not.toHaveBeenCalled()})
})
