import {readFileSync} from 'node:fs'
import ts from 'typescript'
import {it,expect,vi} from 'vitest'
import {msg,prior,object,alphabets,scopeRecords} from './fixtures/prodat-prior-flow'
import {loadPriorPermissionFlow} from '@/lib/ediel/prodat/loadPriorPermissionFlow'
import {assertPriorPermissionContext,type PriorScopeRecords} from '@/lib/ediel/prodat/prodatPriorPermissionFlow'
import {validateProdatPermissionMessage} from '@/lib/ediel/testing/prodatPermissionEngine'
import {assertIncomingProdatEnergyProductReview} from '@/lib/ediel/prodat/prodatEnergyProduct'
import {buildAckDraftForSource} from '@/lib/ediel/ack'
import type {EdielMessageRow} from '@/lib/ediel/types'
vi.mock('@/lib/supabase/service',()=>({supabaseService:{from:()=>{throw Error('NO_LIVE_DB')}}}))
function extract(path:string,names:string[],deps:Record<string,unknown>){const f=ts.createSourceFile(path,readFileSync(path,'utf8'),ts.ScriptTarget.Latest,true),code=f.statements.filter(s=>ts.isFunctionDeclaration(s)&&names.includes(s.name?.text??'')).map(s=>s.getText(f).replace(/^export /,'')).join('\n'),js=ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;return new Function(...Object.keys(deps),js+';return '+names[0])(...Object.values(deps))}
function resolver(rows:EdielMessageRow[],records=scopeRecords(),failure?:'null'|'error'){
 const reads:{table:string;ops:unknown[][];returned:string[]}[]=[]
 const metadata:Record<string,unknown[]>={tenant_ediel_profiles:records.profiles,tenant_actor_identifiers:records.identifiers,tenant_actor_roles:records.roles,tenant_counterparty_relations:records.relations,platform_actor_identifiers:records.actors}
 const db={from:(table:string)=>{const ops:unknown[][]=[],read={table,ops,returned:[] as string[]};reads.push(read);const q:Record<string,unknown>={then:(done:(v:unknown)=>unknown)=>{let data=((table==='ediel_messages'?rows:metadata[table]) as Record<string,unknown>[]).filter(row=>ops.every(([op,k,v])=>op==='eq'?row[String(k)]===v:op==='in'?(v as unknown[]).includes(row[String(k)]):op==='lte'?String(row[String(k)])<=String(v):op==='not'?!['cancelled','failed'].includes(String(row[String(k)])):true));const range=ops.find(o=>o[0]==='range');if(range)data=data.slice(Number(range[1]),Number(range[2])+1);read.returned=data.map(r=>String(r.id));return done({data:table==='ediel_messages'&&failure==='null'?null:data,error:table==='ediel_messages'&&failure==='error'?{message:'synthetic'}:null})}};for(const op of ['select','eq','in','not','lte','order','limit','range'])q[op]=(...v:unknown[])=>{ops.push([op,...v]);return q};return q}}
 return {reads,run:extract('app/admin/ediel/actions.part-3.ts',['resolveProdatPermissionContextForAck'],{supabaseService:db,loadPriorPermissionFlow}) as (m:EdielMessageRow)=>ReturnType<typeof loadPriorPermissionFlow>}
}
const check=async(m=msg(),rows=[prior()],records=scopeRecords(),failure?:'null'|'error')=>resolver(rows,records,failure).run(m)
it('A1 excludes another company before retrieving raw candidates',async()=>{const r=resolver([prior('Z13','CASE-ALPHA',{company_id:'OTHER'})]);const result=await r.run(msg());const read=r.reads.find(r=>r.table==='ediel_messages')!;expect(read.ops).toContainEqual(['eq','company_id',msg().company_id]);expect(read.returned).toEqual([]);expect(result).toMatchObject({kind:'internal_review'})})
it('A1 ownerless source cannot query raw candidates',async()=>{const r=resolver([prior()]);await r.run({...msg(),company_id:null});expect(r.reads).toEqual([])})
for(const li of ['PREFIX-CASE-ALPHA','case-alpha'])it('A3 exact LI rejects '+li,async()=>expect(await check(msg('Z14','Z96'),[prior('Z13',li)])).toMatchObject({kind:'internal_review'}))
it('A6 empty history is internal and never national105',async()=>{const context=await check(msg(),[]);expect(context).toMatchObject({kind:'internal_review',reason:'unmatched'});expect(()=>assertPriorPermissionContext(msg(),context,null)).toThrow('PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED')})
for(const status of ['draft','prepared','queued'] as const)it('A6 '+status+' is not dispatch evidence',async()=>expect(await check(msg(),[prior('Z13','CASE-ALPHA',{status,message_sent_at:null})])).toMatchObject({kind:'internal_review'}))
it('A4 distinct exact candidates are ambiguous',async()=>expect(await check(msg(),[prior(),prior('Z13','CASE-ALPHA',{id:'SECOND'})])).toMatchObject({kind:'internal_review',reason:'ambiguous'}))
it('A8 caller-authored success cannot qualify permission relation',()=>expect(()=>assertPriorPermissionContext(msg(),{hasMatchingPriorPermissionFlow:true,matchReason:'unchecked'},null)).toThrow('PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED'))
for(const a of alphabets)for(const reason of ['S17','S18','Z96'])it('A3 decoded own LI '+a.join('')+reason,async()=>{const li='CASE'+a.join(''),m=msg('Z14',reason,li,undefined,a),p=prior('Z13',li,{},a);if(reason==='S18')p.raw_payload=p.raw_payload!.replace('S17','S18');const c=await check(m,[p]);expect(c.kind).toBe('correlated');expect(validateProdatPermissionMessage({message:m}).outcome).toBe('positive')})
for(const patch of [{company_id:'OTHER'},{environment:'production'},{direction:'inbound'},{sender_ediel_id:'OTHER'},{receiver_ediel_id:'OTHER'},{application_reference:'27-DGI-PRODAT'}] as Partial<EdielMessageRow>[])it('A2 query excludes '+JSON.stringify(patch),async()=>{const r=resolver([prior('Z13','CASE-ALPHA',patch)]);expect((await r.run(msg())).kind).toBe('internal_review');expect(r.reads.find(r=>r.table==='ediel_messages')?.returned).toEqual([])})
for(const kind of ['owner','environment','receipt','identity','role','profile','counterparty','expired','ambiguous'] as const)it('A2 missing historical '+kind+' stops raw read',async()=>{const m=msg(),r=scopeRecords();if(kind==='owner')m.company_id=null;if(kind==='environment')m.environment=null as never;if(kind==='receipt')m.message_received_at=null;if(kind==='identity')r.identifiers=[];if(kind==='role')r.roles=[];if(kind==='profile')r.profiles=[];if(kind==='counterparty')r.actors=[];if(kind==='expired')r.identifiers[0].valid_from='2026-09-21T00:00:00Z';if(kind==='ambiguous')r.identifiers.push({...r.identifiers[0],id:'other'});const loader=resolver([prior()],r);expect(await loader.run(m)).toMatchObject({kind:'internal_review',reason:'scope_unavailable'});expect(loader.reads.filter(r=>r.table==='ediel_messages')).toEqual([])})
it('A2 historical own transport representation is explicit and preserved',async()=>{const m=msg(),p=prior(),r=scopeRecords();m.raw_payload=m.raw_payload!.replace('54321:ZZ','77777:ZZ');m.receiver_ediel_id='77777';p.raw_payload=p.raw_payload!.replace('54321:ZZ','77777:ZZ');p.sender_ediel_id='77777';r.relations=[{...r.profiles[0],id:'relation',relation_type:'ediel_transport_agent',counterparty_actor_id:'AGENT'}];r.actors.push({...r.actors[0],id:'agent-id',actor_id:'AGENT',identifier_value:'77777'});expect((await check(m,[p],r)).kind).toBe('correlated');r.relations=[];expect(await check(m,[p],r)).toMatchObject({kind:'internal_review',reason:'scope_unavailable'})})
for(const kind of ['source-cache','candidate-cache','wire-party','wire-market','wire-environment','headerless','ftx','later-unh'] as const)it('A3 own wire authority '+kind,async()=>{const m=msg('Z14','Z96'),p=prior();if(kind==='source-cache')m.message_code='Z04';if(kind==='candidate-cache')p.raw_payload=p.raw_payload!.replace('BGM+Z13','BGM+Z18');if(kind==='wire-party')p.raw_payload=p.raw_payload!.replace('NAD+FR+54321','NAD+FR+99999');if(kind==='wire-market')p.raw_payload=p.raw_payload!.replace('23-DGI','27-DGI');if(kind==='wire-environment')p.raw_payload=p.raw_payload!.replace('PRODAT++++1','PRODAT');if(kind==='headerless')p.raw_payload=null;if(kind==='ftx')p.raw_payload=p.raw_payload!.replace('LI:CASE-ALPHA','LI:OTHER')+"FTX+AAI+++CASE-ALPHA'";if(kind==='later-unh')p.raw_payload=p.raw_payload!.replace('LI:CASE-ALPHA','LI:OTHER').replace("UNZ+1+I'",prior().raw_payload!.slice(prior().raw_payload!.indexOf('UNH+'),prior().raw_payload!.indexOf('UNZ+'))+"UNZ+2+I'");const c=await check(m,[p]);expect(c.kind).toBe(kind==='source-cache'?'correlated':'internal_review')})
for(const which of ['first','second','both','shared'])it('A4 independent physical occurrences '+which,async()=>{const m=msg('Z14','S17','',[...object('Z14','S17','CASE-ALPHA'),...object('Z14','S17',which==='shared'?'CASE-ALPHA':'CASE-B','2')]),rows=which==='first'||which==='shared'?[prior()]:which==='second'?[prior('Z13','CASE-B')]:[prior(),prior('Z13','CASE-B',{id:'B'})];const c=await check(m,rows);expect(c.objects).toHaveLength(2);expect(c.objects.map(o=>o.source.lineIndex)).toEqual([0,1]);expect(c.objects.map(o=>o.kind)).toEqual(which==='first'?['correlated_request','internal_review']:which==='second'?['internal_review','correlated_request']:['correlated_request','correlated_request'])})
it('A4 duplicate candidate physical LI is ambiguous',async()=>{const p=prior();p.raw_payload=p.raw_payload!.replace('UNT+',"LIN+2'RFF+LI:CASE-ALPHA'UNT+");expect(await check(msg('Z14','Z96'),[p])).toMatchObject({reason:'ambiguous'})})
for(const kind of ['exact','permission','object','customer','namespace','grid','end','mode'])it('A5 Z15 response tuple '+kind,async()=>{const p=prior('Z18');const replacement:Record<string,[string,string]>={permission:['Z09:PERMISSION','Z09:OTHER'],object:['735123456789012345','735123456789012352'],customer:['UD+001','UD+002'],namespace:['001::89','001:SE1:260'],grid:['Z05:NET','Z05:XXX'],end:['202610010000','202610020000'],mode:['CAV+S17','CAV+S18']};if(kind!=='exact')p.raw_payload=p.raw_payload!.replace(...replacement[kind]);const c=await check(msg('Z15'),[p]);expect(c.kind).toBe(kind==='exact'?'correlated':'internal_review')})
it('A5 Z15C uses same-direction prior Z15 and cancelled end',async()=>{const p={...msg('Z15'),id:'prior-cancel',created_at:'2026-09-19T00:00:00Z',message_received_at:'2026-09-19T00:00:00Z'};const r=resolver([p]);expect((await r.run(msg('Z15','Z24'))).objects[0].kind).toBe('correlated_cancellation');expect(r.reads.find(r=>r.table==='ediel_messages')?.ops).toContainEqual(['in','message_code',['Z15']]);p.raw_payload=p.raw_payload!.replace('202610010000','202610020000');expect((await check(msg('Z15','Z24'),[p])).kind).toBe('internal_review')})
for(const reason of ['S17','S18'])it('A5 unsolicited Z15 '+reason+' cannot borrow state from Z14/Z13',async()=>expect(await check(msg('Z15',reason),[prior(),prior('Z14')])).toMatchObject({reason:'state_authority_unavailable'}))
for(const code of ['Z13','Z18'])it('A5 nonconsuming '+code+' has no query',async()=>{const r=resolver([]);expect(await r.run(msg(code))).toMatchObject({kind:'not_applicable'});expect(r.reads).toEqual([])})
for(const failure of ['null','error'] as const)it('A6 unavailable '+failure,async()=>expect(await check(msg(),[],scopeRecords(),failure)).toMatchObject({reason:'history_unavailable'}))
it('A6 finite deterministic paging recovers older request and reports cap',async()=>{const rows=Array.from({length:51},(_,i)=>prior('Z13','OTHER'+i,{id:'noise'+i}));const r=resolver([...rows,prior()]);expect((await r.run(msg())).kind).toBe('correlated');const reads=r.reads.filter(r=>r.table==='ediel_messages');expect(reads).toHaveLength(2);expect(reads[0].ops).toContainEqual(['order','id',{ascending:false}]);expect(await check(msg(),Array.from({length:200},(_,i)=>prior('Z13','OTHER'+i,{id:'noise'+i})))).toMatchObject({reason:'search_incomplete'})})
it('A6 insertion window and actual dispatch time cannot be bypassed',async()=>{for(const p of [prior('Z13','CASE-ALPHA',{created_at:'2026-09-21T00:00:00Z'}),prior('Z13','CASE-ALPHA',{message_sent_at:'2026-09-21T00:00:00Z'}),prior('Z13','CASE-ALPHA',{message_sent_at:null})])expect((await check(msg(),[p])).kind).toBe('internal_review')})
it('A8 source-bound evidence cannot be replayed or forged',async()=>{const m=msg(),c=await check(m);expect(()=>assertPriorPermissionContext(m,c,null)).not.toThrow();for(const changed of [{...m,company_id:'OTHER'},{...m,environment:'production' as const},{...m,raw_payload:m.raw_payload!.replace('LI:CASE-ALPHA','LI:OTHER')}])expect(()=>assertPriorPermissionContext(changed,c,null)).toThrow('PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED');expect(()=>assertPriorPermissionContext(m,{...c},null)).toThrow('PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED')})
function manual(rows:EdielMessageRow[],records:PriorScopeRecords=scopeRecords()){
 const events:unknown[]=[],drafts:unknown[]=[],r=resolver(rows,records as ReturnType<typeof scopeRecords>)
 const run=extract('app/admin/ediel/actions.part-3.ts',['resolveBackendAperakDecision'],{assertIncomingProdatEnergyProductReview,validateProdatPermissionMessage,assertPriorPermissionContext,resolveAndStoreProdatAperakErrors:()=>{throw Error('REGISTRY_BYPASS')},resolveTgtTestDataForAckAction:async()=>({testData:null,selectedRow:null}),resolveProdatPermissionContextForAck:r.run,createEdielMessageEvent:async(e:unknown)=>events.push(e)})
 return {events,drafts,run:async(m:EdielMessageRow)=>{const d=await run({actorUserId:'synthetic',sourceMessage:m,roleCode:'energy_service_company',fallbackOutcome:'positive'});drafts.push(buildAckDraftForSource({sourceMessage:m,ackFamily:'APERAK',outcome:d.outcome,applicationErrors:d.applicationErrors}));return d}}
}
for(const field of ['322','324'])it('A7 actual manual internal hold retains ready '+field+' before event/draft',async()=>{const m=msg(field==='322'?'Z14':'Z15');m.raw_payload=m.raw_payload!.replace(field==='322'?'CAV+A74':'CAV+B79','CAV+X99');const r=manual([]);await expect(r.run(m)).rejects.toMatchObject({permissionFieldAssessment:{applicationErrors:[{ercCode:'42',fieldCode:field}]}});expect(r.events).toEqual([]);expect(r.drafts).toEqual([])})
it('A8 actual manual positive follows correlation and real draft',async()=>{const r=manual([prior()]);expect((await r.run(msg())).outcome).toBe('positive');expect(r.events).toHaveLength(1);expect(r.drafts).toHaveLength(1)})
it('A8 manual null cannot bypass via submitted positive or TGT',async()=>{const run=extract('app/admin/ediel/actions.part-3.ts',['resolveBackendAperakDecision'],{assertIncomingProdatEnergyProductReview,validateProdatPermissionMessage,assertPriorPermissionContext,resolveAndStoreProdatAperakErrors:()=>{throw Error('REGISTRY')},resolveTgtTestDataForAckAction:async()=>({testData:{testCaseCode:'1.2.1'},selectedRow:null}),resolveProdatPermissionContextForAck:async()=>null,createEdielMessageEvent:()=>{throw Error('EVENT')}});await expect(run({sourceMessage:msg(),actorUserId:'synthetic',roleCode:'energy_service_company',fallbackOutcome:'positive'})).rejects.toThrow('PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED')})
it('A8 unrelated qualified national40 still builds Swedish105',()=>{const d=buildAckDraftForSource({sourceMessage:msg(),ackFamily:'APERAK',outcome:'negative',applicationErrors:[{ercCode:'40',fieldCode:'105',text:'Anläggningen kan inte identifieras',lineItemReference:'CASE-ALPHA'}]});expect(d.rawPayload).toContain('ERC+40');expect(d.rawPayload).toContain('105');expect(d.rawPayload).toContain('Anläggningen kan inte identifieras')})
it('A8 issued internal result cannot be mutated into success',async()=>{const m=msg(),c=await check(m,[]);c.kind='correlated';expect(()=>assertPriorPermissionContext(m,c,null)).toThrow('PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED')})
for(const entry of ['createAckDraftAction','createAndSendAckAction','createAndSendRecommendedAckAction'])for(const contextKind of ['unmatched','null','unchecked'])it('A8 actual '+entry+' stops '+contextKind+' before event/draft/send',async()=>{
 const m=msg(),effects:string[]=[],r=resolver([])
 const backend=extract('app/admin/ediel/actions.part-3.ts',['resolveBackendAperakDecision'],{assertIncomingProdatEnergyProductReview,validateProdatPermissionMessage,assertPriorPermissionContext,resolveAndStoreProdatAperakErrors:()=>{effects.push('registry');throw Error('REGISTRY')},resolveTgtTestDataForAckAction:async()=>({testData:{testCaseCode:'1.2.1'},selectedRow:null}),resolveProdatPermissionContextForAck:contextKind==='unmatched'?r.run:async()=>contextKind==='null'?null:{kind:'correlated',hasMatchingPriorPermissionFlow:true},createEdielMessageEvent:async()=>effects.push('event')})
 const action=extract('app/admin/ediel/actions.part-3.ts',[entry],{requireEdielWriteActionAccess:async()=>({userId:'actor',isPlatformAdmin:true}),requireEdielSendActionAccess:async()=>({userId:'actor',isPlatformAdmin:true}),formString:(v:unknown)=>String(v??''),collectAperakApplicationErrors:()=>[],parseEdielTestSuite:()=> 'PRODAT',parseEdielTestRoleCode:()=> 'energy_service_company',requireScopedEdielMessageForAction:async()=>m,resolveBackendAperakDecision:backend,listAckMessagesForSource:async()=>[],resolveTgtTestDataForAckAction:async()=>({testData:{testCaseCode:'1.2.1'}}),resolveRecommendedAckForInboundMessage:()=>({action:{ackFamily:'APERAK',outcome:'positive'}}),createAckDraftForMessage:async()=>effects.push('draft'),sendEdielMessage:async()=>effects.push('send'),createEdielMessageEvent:async()=>effects.push('event')})
 const form=new FormData();form.set('sourceMessageId',m.id);form.set('ackType','APERAK');form.set('outcome','positive');await expect(action(form)).rejects.toThrow('PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED');expect(effects).toEqual([])
})
it('A5 timestamp format is part of the cancelled-end identity',async()=>{const p=prior('Z18');p.raw_payload=p.raw_payload!.replace('164:202610010000:203','164:202610010000:102');expect((await check(msg('Z15'),[p])).kind).toBe('internal_review')})
it('A2 transport identifier namespace cannot be substituted',async()=>{const m=msg();m.raw_payload=m.raw_payload!.replace('12345:ZZ','12345:14');const r=resolver([prior()]);expect((await r.run(m)).kind).toBe('internal_review');expect(r.reads.filter(r=>r.table==='ediel_messages')).toEqual([])})
it('A6 business timestamp after the actual source receipt is contradictory',async()=>{const m=msg();m.raw_payload=m.raw_payload!.replace('137:202609171200','137:202609211200');expect((await check(m)).kind).toBe('internal_review')})

// R-PF-1: P43 DTM137/203 is own message time; arrival time is separate.
for(const [response,mode,request] of [['Z14','S17','Z13'],['Z15','S17','Z18'],['Z15','Z24','Z15']])for(const [chronology,ownDate] of [['earlier','202609171200'],['equal-minute','202609181200'],['later','202609191200']])it(`R-PF-1 ${request} to ${response}/${mode} ${chronology} own message chronology at actual manual boundary`,async()=>{
 const m=msg(response,mode);m.raw_payload=m.raw_payload!.replace('137:202609171200','137:202609181200')
 const p=request==='Z15'?{...msg('Z15'),id:'prior-cancel',created_at:'2026-09-19T00:00:00Z',message_received_at:'2026-09-19T12:00:00Z'}:prior(request,'CASE-ALPHA',{message_sent_at:'2026-09-19T12:00:00Z'})
 p.raw_payload=p.raw_payload!.replace('137:202609171200','137:'+ownDate)
 const r=manual([p])
 if(chronology==='later'){
  await expect(r.run(m)).rejects.toMatchObject({message:'PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED',reason:'wire_conflict',permissionFieldAssessment:{applicationErrors:[]}})
  expect(r.events).toEqual([]);expect(r.drafts).toEqual([])
 }else{
  expect((await r.run(m)).outcome).toBe('positive');expect(r.events).toHaveLength(1);expect(r.drafts).toHaveLength(1)
 }
})
it('R-PF-1 contradictory later exact LI cannot hide beside an earlier match',async()=>{
 const m=msg();m.raw_payload=m.raw_payload!.replace('137:202609171200','137:202609181200')
 const late=prior('Z13','CASE-ALPHA',{id:'later-own-date',message_sent_at:'2026-09-19T12:00:00Z'});late.raw_payload=late.raw_payload!.replace('137:202609171200','137:202609191200')
 const r=manual([prior(),late]);await expect(r.run(m)).rejects.toMatchObject({message:'PRODAT_PERMISSION_PRIOR_REVIEW_REQUIRED'});expect(r.events).toEqual([]);expect(r.drafts).toEqual([])
})
