import {beforeEach,expect,it,vi} from 'vitest'
import {NextRequest} from 'next/server'
const f=vi.hoisted(()=>({guard:vi.fn(),db:vi.fn(),archive:vi.fn(),read:vi.fn(),bytes:vi.fn(),review:vi.fn(),queue:vi.fn()}))
vi.mock('@/lib/admin/apiGuards',()=>({requireAdminApiAccess:f.guard}))
vi.mock('@/lib/supabase/server',()=>({createSupabaseServerClient:f.db}))
vi.mock('@/lib/ediel/production/requestedCustomerChangeSource',()=>({REQUESTED_CUSTOMER_CHANGE_MAX_SOURCE_BYTES:8*1024*1024,REQUESTED_CUSTOMER_CHANGE_MAX_RAW_BYTES:1024*1024,archiveRequestedCustomerChangeSource:f.archive,readRequestedCustomerChangeSourceArtifact:f.read,readRequestedCustomerChangeSourceBytes:f.bytes,reviewRequestedCustomerChangeSourceArtifact:f.review}))
vi.mock('@/lib/ediel/flows/prodatRequestedCustomerChange',()=>({prepareAndQueueRequestedCustomerChange:f.queue}))
import {POST as archive} from '@/app/api/ediel/requested-customer-change-sources/route'
import {GET as metadata} from '@/app/api/ediel/requested-customer-change-sources/[artifactId]/route'
import {GET as bytes} from '@/app/api/ediel/requested-customer-change-sources/[artifactId]/source/route'
import {POST as review} from '@/app/api/ediel/requested-customer-change-sources/[artifactId]/review/route'
import {POST as queue} from '@/app/api/ediel/requested-customer-change-sources/[artifactId]/queue/route'
const company='00000000-0000-4000-8000-000000000001',actor='00000000-0000-4000-8000-000000000002',id='00000000-0000-4000-8000-000000000003'
const params={params:Promise.resolve({artifactId:id})},request=(body:unknown)=>new NextRequest('http://localhost/api/ediel/requested-customer-change-sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
const submission={agreementId:id,supplyPeriodId:id,contractId:id,rawPayload:"UNH+1+PRODAT:D:97A:UN:E2SE6A'",source:{bytesBase64:'JVBERi0xLjc=',mimeType:'application/pdf',reference:'SYNTHETIC original',version:'1'}}
beforeEach(()=>{for(const mock of Object.values(f))mock.mockReset();f.guard.mockResolvedValue({guard:{companyId:company,userId:actor},response:null});const query={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data:{environment:'test'},error:null})};query.select.mockReturnValue(query);query.eq.mockReturnValue(query);f.db.mockResolvedValue({from:()=>query})})
it('derives actual selected company/actor/environment on server and bounds original intake',async()=>{f.archive.mockResolvedValue({status:'archived',artifactId:id});expect((await archive(request(submission))).status).toBe(201);expect(f.archive).toHaveBeenCalledWith({...submission,companyId:company,actorUserId:actor,environment:'test'});expect(f.guard).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write']})})
it('rejects caller company/environment/approval fields without archive',async()=>{for(const key of ['companyId','actorUserId','environment','approved','sourceCapability'])expect((await archive(request({...submission,[key]:true}))).status).toBe(400);expect(f.archive).not.toHaveBeenCalled()})
it('company scoped metadata receives native actor and no client selected company',async()=>{f.read.mockResolvedValue({artifactId:id,status:'held',missing:[]});const response=await metadata(new NextRequest('http://localhost'),params);expect(response.status).toBe(200);expect(f.read).toHaveBeenCalledWith({artifactId:id,companyId:company,actorUserId:actor});expect(response.headers.get('cache-control')).toBe('private, no-store')})
it('original download is permission scoped attachment with nosniff/no-store',async()=>{f.bytes.mockResolvedValue({bytes:new Uint8Array([37,80,68,70,45]),mimeType:'application/pdf'});const response=await bytes(new NextRequest('http://localhost'),params);expect(response.status).toBe(200);expect(response.headers.get('content-disposition')).toContain('attachment;');expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(response.headers.get('cache-control')).toBe('private, no-store')})
it('separate review requires explicit current review permission and preserves held409',async()=>{f.review.mockResolvedValue({artifactId:id,status:'held',missing:['authentic_current_outgoing_customer_mandate']});const command={sourceHash:'a'.repeat(64),claimsHash:'b'.repeat(64),decision:'approve',reason:'Inspect actual source'};expect((await review(request(command),params)).status).toBe(409);expect(f.guard).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write','ediel.source.review']});expect(f.review).toHaveBeenCalledWith({...command,artifactId:id,companyId:company,actorUserId:actor})})
it('native cross company/revoked actor error is sanitized with no source bytes/key details',async()=>{f.review.mockRejectedValue(Error('PRIVATE issuer key/party details'));const response=await review(request({sourceHash:'a'.repeat(64),claimsHash:'b'.repeat(64),decision:'approve',reason:'Inspect actual source'}),params);expect(response.status).toBe(403);expect(JSON.stringify(await response.json())).not.toContain('PRIVATE')})
it('queue rechecks native source, held409 and queued202 expose only safe result IDs',async()=>{f.queue.mockResolvedValueOnce({status:'held',missing:['current_outgoing_customer_mandate_unavailable']}).mockResolvedValueOnce({status:'queued',message:{id,raw_payload:'PRIVATE SOURCE'}});expect((await queue(request({}),params)).status).toBe(409);const response=await queue(request({}),params);expect(response.status).toBe(202);expect(await response.json()).toEqual({status:'queued',messageId:id})})
it('queue unknown caller source/event authority rejected before native command',async()=>{expect((await queue(request({eventId:id,approved:true}),params)).status).toBe(400);expect(f.queue).not.toHaveBeenCalled()})
it('missing current own company blocks all read/write work',async()=>{f.guard.mockResolvedValue({guard:{companyId:null,userId:actor},response:null});expect((await metadata(new NextRequest('http://localhost'),params)).status).toBe(403);expect(f.read).not.toHaveBeenCalled()})
