import {beforeEach,expect,it,vi} from 'vitest'
import {renderToStaticMarkup} from 'react-dom/server'
const io=vi.hoisted(()=>({guard:vi.fn(),access:vi.fn(),read:vi.fn()}))
vi.mock('@/lib/admin/guards',()=>({requireAdminPageAccess:io.guard}))
vi.mock('@/lib/ediel/incidents/freshBusinessIncident',()=>({readFreshEdielBusinessIncidentAccess:io.access,readFreshEdielBusinessIncident:io.read}))
import Page from '@/app/admin/ediel/business-incidents/page'
const company='00000000-0000-4000-8000-000000000001',actor='00000000-0000-4000-8000-000000000002'
const render=async(incidentId?:string)=>renderToStaticMarkup(await Page({searchParams:Promise.resolve({incidentId})}))
beforeEach(()=>{vi.clearAllMocks();io.guard.mockResolvedValue({companyId:company,userId:actor,permissions:[],isPlatformAdmin:true});io.access.mockResolvedValue({companyId:company,canRead:true,canReport:false})})
it('platform page guard cannot reveal a form without current native own-company mutation grants',async()=>{const html=await render();expect(io.guard).toHaveBeenCalledWith({allOf:['communication.read']});expect(io.access).toHaveBeenCalledWith({companyId:company,actorUserId:actor});expect(html).toContain('Du kan läsa bolagets incidenter.');expect(html).not.toContain('Registrera incident');expect(html).not.toContain('name="sourceMessageId"');expect(html).toContain('Incidentens ID')})
it('explicit native write and send authority permits the report controls',async()=>{io.access.mockResolvedValue({companyId:company,canRead:true,canReport:true});expect(await render()).toContain('Registrera incident')})
it('missing selected company and denied native reader authority render no incident or mutation controls',async()=>{io.guard.mockResolvedValue({companyId:null,userId:actor,isPlatformAdmin:true});expect(await render()).not.toContain('Incidentens ID');expect(io.access).not.toHaveBeenCalled();io.guard.mockResolvedValue({companyId:company,userId:actor,isPlatformAdmin:true});io.access.mockRejectedValue(Error('native current DENY'));expect(await render()).not.toContain('Registrera incident');expect(io.read).not.toHaveBeenCalled()})
it('read-only current actor may reload its minimal incident while foreign or revoked source remains sanitized',async()=>{io.read.mockResolvedValue({incidentId:'00000000-0000-4000-8000-000000000003',finding:{summary:'Actual bounded report receipt'}});const html=await render('00000000-0000-4000-8000-000000000003');expect(io.read).toHaveBeenCalledWith({companyId:company,actorUserId:actor,incidentId:'00000000-0000-4000-8000-000000000003'});expect(html).toContain('Actual bounded report receipt');expect(html).not.toContain('Registrera incident');io.read.mockRejectedValue(Error('PRIVATE foreign raw original'));const denied=await render('00000000-0000-4000-8000-000000000003');expect(denied).not.toContain('PRIVATE');expect(denied).not.toContain('Actual bounded report receipt');expect(denied).toContain('Incidenten är inte tillgänglig')})
