import {beforeEach,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
const io=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:io.rpc}}))
import {readProdatRecoveryWorkspace} from '@/lib/ediel/recovery/operatorWorkspace'
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const scope={companyId:id(1),actorUserId:id(2)},row={id:id(3),environment:'test',label:'actual native original'},record={messageId:id(3),operationId:id(4),originalMessageId:id(5),environment:'test',status:'draft',code:'Z01',rawPayload:'persisted normalized',payloadHash:createHash('sha256').update('persisted normalized').digest('hex'),contentCurrent:true,sourceCurrent:'qualified',contrl:'pending',aperak:'pending'}
const snapshot={...scope,originals:[row],acks:[],corrections:[{...row,status:'draft'}],attempts:[{id:id(6),messageId:id(3),label:'actual native attempt'}],record:null}
function respond(workspace:unknown,ack?:unknown,error:unknown=null){io.rpc.mockImplementation(async(name:string,args:Record<string,unknown>)=>name==='ediel_read_business_ack_status_v1'?{data:ack??{version:1,companyId:id(1),sourceMessageId:args.p_source_message_id,environment:'test',ackFamily:null,sourceDirection:'outbound',sourceSnapshot:null,sourceReceipt:null,messages:[],heldOriginalIds:[]},error}:{data:workspace,error:null})}
const unproven={state:'ack_status_unproven',contrl:'ack_status_unproven',aperak:'ack_status_unproven',utiltsErr:'ack_status_unproven'}
const projectedRecord=()=>{const r={...record};Reflect.deleteProperty(r,'contrl');Reflect.deleteProperty(r,'aperak');return{...r,ack:unproven}}
beforeEach(()=>{vi.resetAllMocks();respond(snapshot)})
it('uses the protected current native read port and returns own private journal discovery',async()=>{expect(await readProdatRecoveryWorkspace(scope)).toEqual(snapshot);expect(io.rpc).toHaveBeenCalledExactlyOnceWith('ediel_prodat_recovery_workspace_v1',{p_company_id:id(1),p_actor_user_id:id(2),p_message_id:null})})
it('reloads selected persisted correction with exact physical wire hash and private source status',async()=>{respond({...snapshot,record});expect((await readProdatRecoveryWorkspace({...scope,messageId:id(3)})).record).toEqual(projectedRecord())})
it.each([{companyId:id(99)},{actorUserId:id(99)},{attempts:[{id:id(6),messageId:'claimed-id',label:'claimed'}]},{originals:[{...row,environment:'client-env'}]},{record}])('rejects changed native discovery %j',async changed=>{respond({...snapshot,...changed});await expect(readProdatRecoveryWorkspace(scope)).rejects.toThrow(/result_invalid|record_invalid/)})
it.each([{messageId:id(99)},{payloadHash:'b'.repeat(64)},{operationId:'claimed-op'},{sourceCurrent:'verified'},{contentCurrent:false}])('rejects changed selected immutable readback %j',async changed=>{respond({...snapshot,record:{...record,...changed}});await expect(readProdatRecoveryWorkspace({...scope,messageId:id(3)})).rejects.toThrow('record_invalid')})
it('represents custody-held bytes as unavailable and preserves native current policy denial',async()=>{respond({...snapshot,record:{...record,rawPayload:null,contentCurrent:false,sourceCurrent:'held'}});expect((await readProdatRecoveryWorkspace({...scope,messageId:id(3)})).record?.rawPayload).toBeNull();const error=Error('read_revoked');io.rpc.mockResolvedValue({data:null,error});await expect(readProdatRecoveryWorkspace(scope)).rejects.toBe(error)})

it('cached positive workspace status cannot become green without qualified immutable native ACK evidence',async()=>{respond({...snapshot,record:{...record,contrl:'positive',aperak:'positive'}});const r=(await readProdatRecoveryWorkspace({...scope,messageId:id(3)})).record;expect(r?.ack).toEqual(unproven);expect(r).not.toHaveProperty('contrl');expect(r).not.toHaveProperty('aperak');expect(io.rpc).toHaveBeenLastCalledWith('ediel_read_business_ack_status_v1',{p_source_message_id:id(3),p_actor_user_id:id(2),p_company_id:id(1),p_environment:'test',p_ack_family:null})})
it('uses the same qualified source snapshot/receipt presentation and never reinterprets cached family flags',async()=>{respond({...snapshot,record:{...record,contrl:'positive',aperak:'positive'}},{version:1,companyId:id(1),sourceMessageId:id(3),environment:'test',ackFamily:null,sourceDirection:'outbound',sourceSnapshot:{id:id(3),company_id:id(1),environment:'test',direction:'outbound',contrl_status:'negative',aperak_status:'positive',utilts_err_status:'not_required'},sourceReceipt:{sourceAccepted:false,finalAckReached:true,wholeSourceRejected:false},messages:[],heldOriginalIds:[]});expect((await readProdatRecoveryWorkspace({...scope,messageId:id(3)})).record?.ack).toEqual({state:'ack_completed_with_rejections',contrl:'negative',aperak:'positive',utiltsErr:'not_required'})})
it('held originals cannot expose cached positive family status',async()=>{respond({...snapshot,record:{...record,contrl:'positive',aperak:'positive'}},{version:1,companyId:id(1),sourceMessageId:id(3),environment:'test',ackFamily:null,sourceDirection:'outbound',sourceSnapshot:null,sourceReceipt:null,messages:[],heldOriginalIds:[id(9)]});const a=(await readProdatRecoveryWorkspace({...scope,messageId:id(3)})).record?.ack;expect(a).toEqual({state:'ack_status_held',contrl:'ack_status_held',aperak:'ack_status_held',utiltsErr:'ack_status_held'})})
it('late native ACK READ denial explicitly holds presentation and withholds raw disclosure',async()=>{respond({...snapshot,record},undefined,Error('current_read_revoked'));const r=(await readProdatRecoveryWorkspace({...scope,messageId:id(3)})).record;expect(r?.ack.state).toBe('ack_status_held');expect(r?.rawPayload).toBeNull();expect(r?.contentCurrent).toBe(false)})
