import{beforeEach,expect,it,vi}from'vitest'
import{createHash}from'node:crypto'
const rpc=vi.hoisted(()=>vi.fn());vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc}}))
import{prepareCustomerMasterdataSource,prepareRecoveryCustomerMasterdataContext,bindCustomerMasterdataValidationContext,isQualifiedCustomerMasterdataValidationContext}from'@/lib/ediel/production/customerMasterdataSource'
const input={companyId:'company-A',customerId:'customer-A',actorUserId:'actor-A',environment:'test' as const,asOf:'2026-10-01T12:00:00Z'}
const result={status:'authorized',companyId:input.companyId,customerId:input.customerId,environment:input.environment,asOf:input.asOf,sourceKind:'registered_customer_address',sourceReference:'address-A',sourceDigest:'a'.repeat(64),sourceContextId:'00000000-0000-4000-8000-000000000001',customerIdentity:{id:'5566778899',qualifier:'SE1',agency:'260'},endUserMasterdata:{nameParts:['Literal name'],streetParts:['Own registered street'],postalCode:'12345',city:'Own city',country:'SE'}}
beforeEach(()=>rpc.mockReset())
it('passes exact owned source instant and preserves literal UD separately from site/invoice',async()=>{rpc.mockResolvedValue({data:result,error:null});expect(await prepareCustomerMasterdataSource(input)).toEqual(result);expect(rpc).toHaveBeenCalledWith('ediel_prepare_customer_masterdata_v1',{p_company_id:input.companyId,p_customer_id:input.customerId,p_actor_user_id:input.actorUserId,p_as_of:input.asOf,p_environment:'test'})})
it.each([{companyId:'other'},{customerId:'other'},{environment:'production'},{asOf:'2026-10-02T12:00:00Z'},{sourceContextId:null},{endUserMasterdata:{...result.endUserMasterdata,country:''}},{endUserMasterdata:{...result.endUserMasterdata,streetParts:['x'.repeat(36)]}},{customerIdentity:{...result.customerIdentity,qualifier:'SE3'}}])('holds a changed source tuple %j',async changed=>{rpc.mockResolvedValue({data:{...result,...changed},error:null});await expect(prepareCustomerMasterdataSource(input)).rejects.toThrow('source_result_invalid')})
it('keeps absent/ambiguous own source held and propagates native failures',async()=>{rpc.mockResolvedValueOnce({data:{status:'held',missing:['unique_owned_registered_customer_address']},error:null});await expect(prepareCustomerMasterdataSource(input)).rejects.toThrow('source_held:unique_owned');const error=Error('source_epoch_changed');rpc.mockResolvedValueOnce({data:null,error});await expect(prepareCustomerMasterdataSource(input)).rejects.toBe(error)})
it('does not ask for source with an unbound local DATE',async()=>{await expect(prepareCustomerMasterdataSource({...input,asOf:'2026-10-01'})).rejects.toThrow('source_date_required');expect(rpc).not.toHaveBeenCalled()})

it('keeps prepared projection and validation context opaque across JSON/caller copies',async()=>{rpc.mockResolvedValue({data:structuredClone(result),error:null});const projection=await prepareCustomerMasterdataSource(input);const values={kind:'customer_masterdata' as const,companyId:input.companyId,customerId:input.customerId,environment:input.environment,rawPayload:'exact raw',intentId:'own intent',routeId:'own route',projection};const context=bindCustomerMasterdataValidationContext(values);expect(isQualifiedCustomerMasterdataValidationContext(context)).toBe(true);expect(isQualifiedCustomerMasterdataValidationContext({...context})).toBe(false);expect(()=>bindCustomerMasterdataValidationContext({...values,projection:structuredClone(projection)})).toThrow('context_unqualified');expect(()=>bindCustomerMasterdataValidationContext({...values,companyId:'other'})).toThrow('context_unqualified')})

const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const recoveryInput={companyId:uuid(1),customerId:uuid(2),actorUserId:uuid(3),operationId:uuid(4),intentId:uuid(5),routeId:uuid(6),environment:'test' as const,rawPayload:'exact corrected raw'}
const recoveryResult={...result,companyId:recoveryInput.companyId,customerId:recoveryInput.customerId,sourceContextId:uuid(7),recoveryBinding:{...recoveryInput,originalMessageId:uuid(8),sourceOriginMessageId:uuid(9),payloadHash:createHash('sha256').update(recoveryInput.rawPayload).digest('hex')}}
it('binds a fresh native current-actor preparation to the exact correction/intent/route',async()=>{rpc.mockResolvedValue({data:structuredClone(recoveryResult),error:null});const context=await prepareRecoveryCustomerMasterdataContext(recoveryInput);expect(isQualifiedCustomerMasterdataValidationContext(context)).toBe(true);expect(context?.projection.sourceContextId).toBe(uuid(7));expect(rpc).toHaveBeenCalledExactlyOnceWith('ediel_prepare_customer_masterdata_recovery_v1',{p_company_id:uuid(1),p_operation_id:uuid(4),p_actor_user_id:uuid(3),p_intent_id:uuid(5),p_route_id:uuid(6)})})
it.each(['operationId','actorUserId','intentId','routeId','environment','originalMessageId','sourceOriginMessageId','payloadHash'])('rejects a native preparation with changed recovery %s',async field=>{rpc.mockResolvedValue({data:{...recoveryResult,recoveryBinding:{...recoveryResult.recoveryBinding,[field]:'foreign'}},error:null});await expect(prepareRecoveryCustomerMasterdataContext(recoveryInput)).rejects.toThrow('recovery_binding_invalid')})
it('uses only native physical no-UD nonapplicability and fails closed on missing actor scope',async()=>{rpc.mockResolvedValueOnce({data:null,error:null});expect(await prepareRecoveryCustomerMasterdataContext(recoveryInput)).toBeUndefined();rpc.mockClear();await expect(prepareRecoveryCustomerMasterdataContext({...recoveryInput,actorUserId:'client-actor'})).rejects.toThrow('scope_required');expect(rpc).not.toHaveBeenCalled()})
it('preserves native current-source hold and denial before producing a credential',async()=>{rpc.mockResolvedValueOnce({data:{status:'held',missing:['current_issuer']},error:null});await expect(prepareRecoveryCustomerMasterdataContext(recoveryInput)).rejects.toThrow('source_held:current_issuer');const error=Error('current_actor_revoked');rpc.mockResolvedValueOnce({data:null,error});await expect(prepareRecoveryCustomerMasterdataContext(recoveryInput)).rejects.toBe(error)})
