import {beforeEach,expect,it,vi} from 'vitest'
const io=vi.hoisted(()=>({guard:vi.fn(),operational:vi.fn(),read:vi.fn(),prepare:vi.fn(),queue:vi.fn(),retry:vi.fn(),revalidate:vi.fn()}))
vi.mock('@/lib/admin/guards',()=>({requireAdminActionAccess:io.guard}))
vi.mock('@/lib/tenant/governance',()=>({requireCompanyOperationalForWrites:io.operational}))
vi.mock('@/lib/ediel/recovery/operatorWorkspace',()=>({readProdatRecoveryWorkspace:io.read}))
vi.mock('@/lib/ediel/recovery/prodatRecovery',()=>({prepareProdatRecoveryDraft:io.prepare,queuePersistedProdatRecovery:io.queue,prepareAndQueueProdatRecovery:io.retry}))
vi.mock('next/cache',()=>({revalidatePath:io.revalidate}))
import {prodatRecoveryAction} from '@/app/admin/ediel/prodat-recovery/actions'
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const idle={status:'idle' as const,message:''},session={companyId:id(1),userId:id(2),permissions:['communication.read','communication.write','communication.send']}
const record={messageId:id(5),operationId:id(6),originalMessageId:id(3),environment:'test',status:'draft',code:'Z01',rawPayload:'native persisted normalized raw',payloadHash:'a'.repeat(64),contentCurrent:true,sourceCurrent:'qualified',ack:{state:'ack_status_unproven',contrl:'ack_status_unproven',aperak:'ack_status_unproven',utiltsErr:'ack_status_unproven'}}
function form(action:string,fields:Record<string,string>){const f=new FormData();f.set('action',action);for(const[key,value]of Object.entries(fields))f.set(key,value);return f}
const prepare=()=>form('prepare',{originalMessageId:id(3),sourceAckMessageId:id(4),operationId:id(6),correctedRawPayload:'operator proposed correction'})
beforeEach(()=>{vi.resetAllMocks();io.guard.mockResolvedValue(session);io.operational.mockResolvedValue(undefined);io.read.mockImplementation(async i=>({record:{...record,messageId:i.messageId}}));io.prepare.mockResolvedValue({status:'prepared',operationId:id(6),messageId:id(5)});io.queue.mockResolvedValue({status:'queued',operationId:id(6),messageId:id(5)});io.retry.mockResolvedValue({status:'queued',operationId:id(6),messageId:id(3)})})
it('WRITE-only preparation binds current server session and rereads native persisted bytes after commit',async()=>{io.guard.mockResolvedValue({...session,permissions:['communication.read','communication.write']});expect(await prodatRecoveryAction(idle,prepare())).toMatchObject({status:'prepared',record});expect(io.guard).toHaveBeenCalledExactlyOnceWith({allOf:['communication.read','communication.write']});expect(io.prepare).toHaveBeenCalledExactlyOnceWith({companyId:id(1),actorUserId:id(2),originalMessageId:id(3),sourceAckMessageId:id(4),operationId:id(6),correctedRawPayload:'operator proposed correction'});expect(io.read).toHaveBeenLastCalledWith({companyId:id(1),actorUserId:id(2),messageId:id(5)});expect(io.prepare.mock.invocationCallOrder[0]).toBeLessThan(io.read.mock.invocationCallOrder[1]);expect(io.queue).not.toHaveBeenCalled()})
it('SEND-only queue uses actual own persisted message without preparation, caller environment or operation',async()=>{io.guard.mockResolvedValue({...session,permissions:['communication.read','communication.send']});expect(await prodatRecoveryAction(idle,form('queue',{messageId:id(5)}))).toMatchObject({status:'queued',record});expect(io.queue).toHaveBeenCalledExactlyOnceWith({companyId:id(1),actorUserId:id(2),messageId:id(5)});expect(io.prepare).not.toHaveBeenCalled();expect(io.guard).toHaveBeenCalledExactlyOnceWith({allOf:['communication.read','communication.send']})})
it('READ-only reload selection uses current native read port without mutation',async()=>{io.guard.mockResolvedValue({...session,permissions:['communication.read']});expect(await prodatRecoveryAction(idle,form('read',{messageId:id(5)}))).toMatchObject({status:'read',record});expect(io.operational).not.toHaveBeenCalled();expect(io.prepare).not.toHaveBeenCalled();expect(io.queue).not.toHaveBeenCalled()})
it.each(['companyId','actorUserId','environment','verified','sourceCurrent'])('rejects a caller authority field %s before any command',async key=>{const f=prepare();f.set(key,'forged');expect((await prodatRecoveryAction(idle,f)).status).toBe('unavailable');expect(io.guard).not.toHaveBeenCalled();expect(io.prepare).not.toHaveBeenCalled()})
it('rejects duplicate identity fields and missing current phase permission even for a platform administrator',async()=>{const f=prepare();f.append('operationId',id(99));expect((await prodatRecoveryAction(idle,f)).status).toBe('unavailable');io.guard.mockResolvedValue({...session,isPlatformAdmin:true,permissions:['communication.read','communication.send']});expect((await prodatRecoveryAction(idle,prepare())).status).toBe('unavailable');expect(io.prepare).not.toHaveBeenCalled()})
it('a foreign/current-read denial cannot reach preparation or queue',async()=>{io.read.mockRejectedValue(Error('workspace_message_unavailable'));expect((await prodatRecoveryAction(idle,prepare())).status).toBe('unavailable');expect(io.prepare).not.toHaveBeenCalled();expect(io.queue).not.toHaveBeenCalled()})
it('does not report rollback when mutation committed but current read authority was revoked',async()=>{io.read.mockResolvedValueOnce({record}).mockRejectedValueOnce(Error('current_read_revoked'));expect(await prodatRecoveryAction(idle,prepare())).toMatchObject({status:'unavailable',message:expect.stringContaining('beständigt meddelande')});expect(io.prepare).toHaveBeenCalledOnce()})
it('requires separate write/send gates for actual failed transport replay and binds source proof selection',async()=>{const f=form('retry',{originalMessageId:id(3),operationId:id(6),previousAttemptId:id(8)});expect((await prodatRecoveryAction(idle,f)).status).toBe('queued');expect(io.guard).toHaveBeenCalledExactlyOnceWith({allOf:['communication.read','communication.write','communication.send']});expect(io.retry).toHaveBeenCalledExactlyOnceWith({companyId:id(1),actorUserId:id(2),originalMessageId:id(3),operationId:id(6),previousAttemptId:id(8)})})
