import {describe,it,expect} from 'vitest'
import {compareUtiltsStructure} from '@/lib/ediel/utilts/structuralComparison'
import {comparisonInput,structureVersion,utiltsStructureWire,STRUCTURE_POINT} from './helpers/structuralComparisonFixtures'
const check=(options:Parameters<typeof utiltsStructureWire>[0]={},versions=[structureVersion()])=>compareUtiltsStructure(comparisonInput(utiltsStructureWire(options),versions))
describe('original UTILTS against independently selected structure (pure)',()=>{
  it('counts two registers, not four reads or the energy sequence',()=>expect(check()).toMatchObject({status:'matched',codes:[],transactionId:'TX'}))
  it.each([['201'],['202'],['201','202','901'],['201','203'],['201 ','202'],['201','202 ']].map(ids=>[ids]))('detects missing/extra/wrong register inventory %j',ids=>expect(check({ids})).toMatchObject({status:'mismatch',codes:['E62']}))
  it.each(['WRONG','old',' OLD','OLD '])('does not normalize the wrong meter %s',meter=>expect(check({meter})).toMatchObject({status:'mismatch',codes:['E61']}))
  it('does not borrow the first register meter for another register',()=>expect(check({meters:['OLD',null]})).toMatchObject({status:'unavailable',codes:[]}))
  it('checks each explicitly sent register meter',()=>expect(check({meters:['OLD','WRONG']})).toMatchObject({status:'mismatch',codes:['E61']}))
  it('emits both genuine comparison errors without inventing an APERAK',()=>expect(check({ids:['901'],meter:'WRONG'})).toMatchObject({status:'mismatch',codes:['E61','E62']}))
  it('does not substitute incoming IDs for missing source inventory',()=>expect(check({},[])).toMatchObject({status:'unavailable',codes:[]}))
  it.each(['readComplete','unresolvedSources'] as const)('keeps %s uncertainty internal',field=>{const input=comparisonInput();input[field]=field==='unresolvedSources';expect(compareUtiltsStructure(input)).toMatchObject({status:'unavailable',codes:[]})})
  it('requires a witnessed accepted version',()=>{const version=structureVersion();version.disposition='unavailable';expect(check({},[version])).toMatchObject({status:'unavailable',codes:[]})})
  it('requires known expected register identifiers',()=>{const version=structureVersion();version.wire.registers[1].registerId=null;expect(check({},[version])).toMatchObject({status:'unavailable',codes:[]})})
  it('requires known expected meter identifier',()=>{const version=structureVersion();version.wire.meterNumber=null;expect(check({},[version])).toMatchObject({status:'unavailable',codes:[]})})
  it.each(['sender','receiver','point'] as const)('does not cross the %s scope',field=>expect(check({[field]:'99999'})).toMatchObject({status:'unavailable',codes:[]}))
  it('does not borrow agency9 structure for89',()=>expect(compareUtiltsStructure(comparisonInput(utiltsStructureWire().replace(`${STRUCTURE_POINT}::9`,`${STRUCTURE_POINT}::89`)))).toMatchObject({status:'unavailable',codes:[]}))
  it('keeps closing interval readings on the OLD meter at the exchange boundary',()=>expect(check({period:'202610010000202610150000'},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'matched',selected:[{meterNumber:'OLD'}]}))
  it('uses the NEW meter after the exchange',()=>expect(check({period:'202610150000202611010000',meter:'NEW'},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'matched',selected:[{meterNumber:'NEW'}]}))
  it('rejects old meter in the new interval',()=>expect(check({period:'202610150000202611010000'},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'mismatch',codes:['E61']}))
  it('does not turn an unresolved inside-transaction exchange into E61/E62',()=>expect(check({},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'unavailable',codes:[]}))
  it('selects E30 last stand on the old side without looking at the sent meter',()=>expect(check({code:'E30',period:'',reason:'E24'},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'matched',selected:[{meterNumber:'OLD'}]}))
  it.each(['E20','E77'])('selects E30 %s ending stand on the closing side',reason=>expect(check({code:'E30',period:'',reason},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'matched',selected:[{meterNumber:'OLD'}]}))
  it('selects E30 first stand on the new side without looking at the sent meter',()=>expect(check({code:'E30',period:'',reason:'E25',meter:'NEW'},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'matched',selected:[{meterNumber:'NEW'}]}))
  it('selects E30 E67 first stand on the current side',()=>expect(check({code:'E30',period:'',reason:'E67',meter:'NEW'},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'matched',selected:[{meterNumber:'NEW'}]}))
  it('does not guess an ambiguous point side from the incoming identifier',()=>expect(check({code:'E30',period:'',reason:'E64'},[structureVersion(),structureVersion(2,'NEW')])).toMatchObject({status:'unavailable',codes:[]}))
  it('permits quarter energy without register readings',()=>expect(check({noReadings:true,highResolution:true},[])).toMatchObject({status:'not_applicable',codes:[]}))
  it('permits prior hourly energy without register readings',()=>expect(compareUtiltsStructure(comparisonInput(
    utiltsStructureWire({noReadings:true,highResolution:true}).replace('DTM+354:15:806','DTM+354:60:806'),[]
  ))).toMatchObject({status:'not_applicable',codes:[]}))
  it('does not silently accept absent monthly registers',()=>expect(check({noReadings:true})).toMatchObject({status:'mismatch',codes:['E62']}))
  it.each(['E31','S01','S02','S03','S04','E72','E73','ERR'])('does not apply E61/E62 to %s',code=>expect(check({code})).toMatchObject({status:'not_applicable',codes:[]}))
  it('does not use RFF+LI P or wrong case as a national comparison check',()=>{
    for(const value of ['P','WRONG',''])expect(check({before:[`RFF+LI:${value}`]})).toMatchObject({status:'matched',codes:[]})
  })
  it('retains EDIFACT escaped register identity',()=>{const version=structureVersion(1,'OLD',['A+B','202']);expect(check({ids:['A+B','202']},[version])).toMatchObject({status:'matched'})})
  it('retains EDIFACT escaped meter identity',()=>{const version=structureVersion(1,'A:B+?');expect(check({meter:'A:B+?'},[version])).toMatchObject({status:'matched'})})
  it('does not take a meter reference from the transaction header',()=>expect(check({meters:[null,null],before:['RFF+MG:OLD']})).toMatchObject({status:'unavailable',codes:[]}))
  it('does not take a meter reference following a quantity as SG8 evidence',()=>expect(check({meters:[null,null],after:['RFF+MG:OLD']})).toMatchObject({status:'unavailable',codes:[]}))
  it('does not silently fix malformed composite identifiers',()=>expect(compareUtiltsStructure(comparisonInput(utiltsStructureWire().replace('RFF+AES:201','RFF+AES:201:EXTRA')))).toMatchObject({status:'unavailable',codes:[]}))
  it('keeps observation times outside the selected period internal',()=>expect(check({readingEnd:'202611150000'})).toMatchObject({status:'unavailable',codes:[]}))
  it('does not infer dates from receipt when period/reading date is invalid',()=>expect(check({period:'202602300000202611010000'})).toMatchObject({status:'unavailable',codes:[]}))
})
