import {beforeEach,expect,it,vi} from 'vitest'
import {randomUUID} from 'node:crypto'
import {NextRequest,NextResponse} from 'next/server'
const io=vi.hoisted(()=>({rpc:vi.fn(),guard:vi.fn()}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:io.rpc}}))
vi.mock('@/lib/admin/apiGuards',()=>({requireAdminApiAccess:io.guard}))
import {reportFreshEdielBusinessIncident,readFreshEdielBusinessIncident} from '@/lib/ediel/incidents/freshBusinessIncident'
import {POST,GET} from '@/app/api/ediel/business-incidents/route'
const company=randomUUID(),actor=randomUUID(),incident=randomUUID(),command={commandId:randomUUID(),sourceMessageId:randomUUID(),ackMessageId:randomUUID(),scopeReference:'OWN-IDE',finding:{code:'late_internal_business_error',summary:'Observed later internal issue'}}
const receipt={incidentId:incident,commandId:command.commandId,companyId:company,environment:'test',sourceMessageId:command.sourceMessageId,ackMessageId:command.ackMessageId,scope:{scope:'transaction',reference:command.scopeReference,outcome:'positive'},reportedAt:'2026-10-01T00:00:00Z',finding:command.finding,status:'reported',findingValidated:false,ackHistoryChanged:false,contactStatus:'held',correctionStatus:'held',trafficAuthorized:false}
const request=(body:unknown)=>new NextRequest('http://localhost/api/ediel/business-incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
beforeEach(()=>{vi.clearAllMocks();io.guard.mockResolvedValue({guard:{companyId:company,userId:actor}});io.rpc.mockResolvedValue({data:receipt,error:null})})
it('explicit fresh report redeems exact actor/company/source/scope at the native port and grants no outcome or traffic authority',async()=>{expect(await reportFreshEdielBusinessIncident({companyId:company,actorUserId:actor,command})).toEqual(receipt);expect(io.rpc).toHaveBeenCalledExactlyOnceWith('ediel_report_fresh_business_incident_v1',{p_company_id:company,p_actor_user_id:actor,p_input:command})})
it.each([{companyId:randomUUID()},{actorUserId:randomUUID()},{approved:true},{trafficAuthorized:true},{correctionRawPayload:'APERAK+100'},{outcome:'negative'}])('rejects injected command authority %j before any RPC',async extra=>{await expect(reportFreshEdielBusinessIncident({companyId:company,actorUserId:actor,command:{...command,...extra}})).rejects.toBeDefined();expect(io.rpc).not.toHaveBeenCalled()})
it.each([{companyId:randomUUID()},{sourceMessageId:randomUUID()},{ackMessageId:randomUUID()},{scope:{scope:'transaction',reference:'FOREIGN',outcome:'positive'}},{trafficAuthorized:true},{findingValidated:true}])('rejects foreign or authority-bearing native receipt %j',async delta=>{io.rpc.mockResolvedValue({data:{...receipt,...delta},error:null});await expect(reportFreshEdielBusinessIncident({companyId:company,actorUserId:actor,command})).rejects.toBeDefined()})
it('POST derives company/actor from authenticated selected context and returns private response',async()=>{const r=await POST(request(command));expect(r.status).toBe(201);expect(io.guard).toHaveBeenCalledWith({allOf:['communication.write','communication.send']});expect(r.headers.get('cache-control')).toBe('private, no-store');expect(r.headers.get('x-content-type-options')).toBe('nosniff');expect(await r.json()).toEqual(receipt)})
it('GET reads one exact incident and cannot select another tenant',async()=>{expect((await GET(new NextRequest('http://localhost/api/ediel/business-incidents?incidentId='+incident))).status).toBe(200);expect(io.rpc).toHaveBeenCalledExactlyOnceWith('ediel_read_fresh_business_incident_v1',{p_company_id:company,p_actor_user_id:actor,p_incident_id:incident});io.rpc.mockClear();expect((await GET(new NextRequest('http://localhost/api/ediel/business-incidents?incidentId='+incident+'&companyId=foreign'))).status).toBe(400);expect(io.rpc).not.toHaveBeenCalled()})
it('authentication deny/missing company prevents every incident port',async()=>{io.guard.mockResolvedValue({response:NextResponse.json({error:'denied'},{status:403})});expect((await POST(request(command))).status).toBe(403);io.guard.mockResolvedValue({guard:{companyId:null,userId:actor}});expect((await POST(request(command))).status).toBe(403);expect(io.rpc).not.toHaveBeenCalled()})
it('current native revocation is sanitized and no receipt is returned',async()=>{io.rpc.mockResolvedValue({data:null,error:Error('PRIVATE SQL role revoked')});const r=await POST(request(command));expect(r.status).toBe(403);expect(await r.text()).not.toContain('PRIVATE')})
it('bounds streamed bytes before calling the native owner',async()=>{expect((await POST(request({summary:'x'.repeat(17000)}))).status).toBe(413);expect(io.rpc).not.toHaveBeenCalled()})
it('explicit read rejects a foreign receipt rather than exposing it',async()=>{io.rpc.mockResolvedValue({data:{...receipt,companyId:randomUUID()},error:null});await expect(readFreshEdielBusinessIncident({companyId:company,actorUserId:actor,incidentId:incident})).rejects.toThrow('receipt_scope_mismatch')})
