import {beforeEach,expect,it,vi} from 'vitest'
import {NextRequest,NextResponse} from 'next/server'
const io=vi.hoisted(()=>({access:vi.fn(),archive:vi.fn(),read:vi.fn(),bytes:vi.fn(),review:vi.fn(),scope:vi.fn()}))
vi.mock('@/lib/admin/apiGuards',()=>({requireAdminApiAccess:io.access}))
vi.mock('@/lib/ediel/production/bilateralProdatProfileIntake',()=>({BILATERAL_PRODAT_SOURCE_MAX_BYTES:8*1024*1024,archiveBilateralProdatGround:io.archive,readBilateralProdatGroundArtifact:io.read,readBilateralProdatGroundBytes:io.bytes,reviewBilateralProdatGround:io.review,readBilateralProdatGroundScope:io.scope}))
import {POST as archive} from '@/app/api/ediel/bilateral-prodat-sources/route'
import {GET as metadata} from '@/app/api/ediel/bilateral-prodat-sources/[artifactId]/route'
import {GET as source} from '@/app/api/ediel/bilateral-prodat-sources/[artifactId]/source/route'
import {POST as review} from '@/app/api/ediel/bilateral-prodat-sources/[artifactId]/review/route'
const id='11111111-1111-4111-8111-111111111111',hash='a'.repeat(64),params={params:Promise.resolve({artifactId:id})}
const request=(body?:unknown)=>new NextRequest('http://localhost/api/ediel/bilateral-prodat-sources',{method:body===undefined?'GET':'POST',...(body===undefined?{}:{body:JSON.stringify(body)})})
const submission=()=>({environment:'test',kind:'normal_start_h',rulePackId:id,gridAreaCode:'TES',bilateralAgreementId:id,validFrom:'2026-01-01T00:00:00Z',validTo:'2099-01-01T00:00:00Z',source:{bytesBase64:'VEVTVA==',mimeType:'text/plain',reference:'SYNTHETIC',version:'1'}})
beforeEach(()=>{vi.clearAllMocks();io.access.mockResolvedValue({guard:{companyId:'current-company',userId:'current-user'}});io.archive.mockResolvedValue({status:'archived',artifactId:id,sourceHash:hash,scopeHash:hash,missing:['separate_qualified_source_review_required']});io.read.mockResolvedValue({status:'held',artifactId:id,missing:['authentic_current_issuer_representation_and_legal_ground_receipt']});io.bytes.mockResolvedValue({mimeType:'text/plain',sourceHash:hash,bytes:Uint8Array.from([84,69,83,84])});io.review.mockResolvedValue({status:'held',artifactId:id,missing:['authentic_current_issuer_representation_and_legal_ground_receipt']})})
it('uses current server actor/company and own communication/contract/metering permissions',async()=>{
 expect((await archive(request(submission()))).status).toBe(201);expect(io.archive).toHaveBeenCalledExactlyOnceWith({...submission(),companyId:'current-company',actorUserId:'current-user'});expect(io.access).toHaveBeenCalledWith({allOf:['communication.write','contracts.read','metering.write']})
})
it.each(['companyId','actorUserId','verified','approved','profileVersionId','sourceHash','scopeHash'])('rejects public authority field %s before native effects',async key=>{expect((await archive(request({...submission(),[key]:'forged'}))).status).toBe(400);expect(io.archive).not.toHaveBeenCalled()})
it('requires separate review permission and returns actual issuer hold without source/ground fabrication',async()=>{const cmd={sourceHash:hash,scopeHash:hash,decision:'approve',reason:'Review actual original'};const response=await review(request(cmd),params);expect(response.status).toBe(409);expect(await response.json()).not.toHaveProperty('profileVersionId');expect(io.review).toHaveBeenCalledExactlyOnceWith({...cmd,artifactId:id,companyId:'current-company',actorUserId:'current-user'});expect(io.access).toHaveBeenCalledWith({allOf:['communication.write','contracts.read','metering.write','ediel.bilateral_profile.review']})})
it('binary original read is private attachment and scoped to server current company',async()=>{const response=await source(request(),params);expect(await response.text()).toBe('TEST');expect(response.headers.get('content-disposition')).toBe(`attachment; filename="underlag-${id}.txt"`);expect(response.headers.get('cache-control')).toBe('private, no-store');expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(io.bytes).toHaveBeenCalledExactlyOnceWith({companyId:'current-company',actorUserId:'current-user',artifactId:id})})
it('denied/unselected scope/invalid selector performs no read or native write',async()=>{io.access.mockResolvedValue({response:NextResponse.json({error:'Denied'},{status:403})});expect((await source(request(),params)).status).toBe(403);io.access.mockResolvedValue({guard:{companyId:null,userId:'current-user'}});expect((await metadata(request(),params)).status).toBe(403);expect(io.read).not.toHaveBeenCalled();expect(io.bytes).not.toHaveBeenCalled()})
it('streamed body is bounded and native reviewer revocation errors do not disclose raw data',async()=>{const oversized=new NextRequest('http://localhost/api/ediel/bilateral-prodat-sources',{method:'POST',headers:{'content-length':'99999999'},body:'{}'});expect((await archive(oversized)).status).toBe(413);expect(io.archive).not.toHaveBeenCalled();io.review.mockRejectedValue(Error('PRIVATE CUSTOMER SQL'));const response=await review(request({sourceHash:hash,scopeHash:hash,decision:'approve',reason:'Review'}),params);expect(response.status).toBe(403);expect(await response.text()).not.toContain('PRIVATE')})
