import {beforeEach,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
import {resolveCanonicalMessagePolicy} from '@/lib/ediel/core/messagePolicy'
import {utiltsErrGatewayFixture} from './helpers/utiltsErrGatewayFixture'
const io=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('@/lib/supabase/service',()=>({supabaseService:{rpc:io.rpc}}))
import {readUtiltsIssuerIdentityAuthority,utiltsIssuerIdentityFacts,type UtiltsIssuerIdentityAuthority} from '@/lib/ediel/utilts/issuerIdentityAuthority'
function setup(){const message=utiltsErrGatewayFixture({company:'22222222-2222-4222-8222-222222222222',transactions:[{reference:'OWN-REF',outcome:'processability_rejected'}]});message.id='11111111-1111-4111-8111-111111111111';const policy=resolveCanonicalMessagePolicy(message)!;return {message,policy}}
function reply(input:ReturnType<typeof setup>,extra={}){return {data:{version:1,companyId:input.message.company_id,environment:input.message.environment,sourceMessageId:input.message.id,sourcePayloadHash:createHash('sha256').update(input.message.raw_payload!).digest('hex'),status:'qualified',authorityVersionId:'33333333-3333-4333-8333-333333333333',namespaceEpoch:'2',messageReferenceCollision:false,transactionReferenceCollisions:[],holdReason:null,...extra},error:null}}
beforeEach(()=>vi.clearAllMocks())
it('does not turn missing legal issuer evidence into a national collision',async()=>{const input=setup();io.rpc.mockResolvedValue({data:null,error:{message:'missing'}});const authority=await readUtiltsIssuerIdentityAuthority(input);expect(utiltsIssuerIdentityFacts({...input,authority})).toMatchObject({status:'held',messageReferenceCollision:false,transactionReferenceCollisions:[]})})
it('binds an observed collision to the same physical own IDE and original policy',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{transactionReferenceCollisions:[{transactionIndex:0,transactionId:'OWN-REF'}]}));const authority=await readUtiltsIssuerIdentityAuthority(input);expect(utiltsIssuerIdentityFacts({...input,authority}).transactionReferenceCollisions).toEqual([{transactionIndex:0,transactionId:'OWN-REF'}]);expect(()=>utiltsIssuerIdentityFacts({...input,policy:{...input.policy},authority})).toThrow('authority_invalid');expect(()=>utiltsIssuerIdentityFacts({...input,message:{...input.message,raw_payload:input.message.raw_payload+' '},authority})).toThrow('authority_invalid');expect(()=>utiltsIssuerIdentityFacts({...input,authority:{...authority} as UtiltsIssuerIdentityAuthority})).toThrow('authority_invalid')})
it('refuses wrong raw/hash/source and another sibling rather than borrowing its reference',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{transactionReferenceCollisions:[{transactionIndex:0,transactionId:'FOREIGN'}]}));await expect(readUtiltsIssuerIdentityAuthority(input)).rejects.toThrow('read_scope_invalid');io.rpc.mockResolvedValue(reply(input,{sourcePayloadHash:'a'.repeat(64)}));await expect(readUtiltsIssuerIdentityAuthority(input)).rejects.toThrow('read_scope_invalid')})
it('can retain a known authenticated collision while missing historical absence evidence remains held',async()=>{const input=setup();io.rpc.mockResolvedValue(reply(input,{status:'held',messageReferenceCollision:true,holdReason:'ediel_utilts_identity_history_coverage_unavailable'}));const authority=await readUtiltsIssuerIdentityAuthority(input);expect(utiltsIssuerIdentityFacts({...input,authority})).toMatchObject({status:'held',messageReferenceCollision:true,holdReason:'ediel_utilts_identity_history_coverage_unavailable'})})
