import {beforeEach,expect,it,vi} from 'vitest'
import {createHash} from 'node:crypto'
vi.mock('server-only',()=>({}))
const io=vi.hoisted(()=>({rpc:vi.fn(),user:vi.fn(),guard:vi.fn()}))
vi.mock('@/lib/supabase/server',()=>({createSupabaseServerClient:async()=>({auth:{getUser:io.user},rpc:io.rpc})}))
vi.mock('@/lib/admin/apiGuards',()=>({requireAdminApiAccess:io.guard}))
import {archiveSignedBrpDeclaration,previewSignedBrpDeclaration,readSignedBrpDeclaration,reviewSignedBrpDeclaration,revokeSignedBrpDeclaration} from '@/lib/ediel/production/signedBrpDeclarationIntake'
import {POST as archivePost} from '@/app/api/ediel/signed-brp-declarations/route'
import {POST as reviewPost} from '@/app/api/ediel/signed-brp-declarations/[artifactId]/review/route'
import {GET as originalGet} from '@/app/api/ediel/signed-brp-declarations/[artifactId]/original/route'
import {NextRequest} from 'next/server'
const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,company=uuid(1),actor=uuid(2),contract=uuid(3),ground=uuid(4),artifactId=uuid(5),declaration=uuid(6),digest=(b:Buffer)=>createHash('sha256').update(b).digest('hex')
const agreement=Buffer.from('%PDF-SYNTHETIC unit boundary signed-agreement bytes only'),source=Buffer.from('SYNTHETIC unit boundary BRP source bytes only'),agreementHash=digest(agreement),sourceHash=digest(source),claimsHash='a'.repeat(64)
const selector={environment:'test' as const,contractId:contract,registryGroundId:ground,identityAgency:'89' as const,agreementHash},submission={environment:'test' as const,contractId:contract,registryGroundId:ground,identityAgency:'89' as const,agreementBase64:agreement.toString('base64'),sourceBase64:source.toString('base64'),sourceReference:'SYNTHETIC TEST ONLY',sourceVersion:'1'}
const saved={status:'archived',artifactId,agreementHash,sourceHash,claimsHash,issuerQualified:false,authority:'none'},claims={companyId:company,environment:'test',contractId:contract,agreementHash},metadata={artifactId,companyId:company,environment:'test',contractId:contract,claims,claimsHash,agreementHash,sourceHash,sourceReference:submission.sourceReference,sourceVersion:'1',agreementByteLength:agreement.length,sourceByteLength:source.length,bytesAvailable:true,issuerQualified:false,status:'held',declarationId:null,missing:['authentic_current_brp_purpose_issuer_representation_receipt'],authority:'none'}
const command={agreementHash,sourceHash,claimsHash,decision:'approve' as const,reason:'SYNTHETIC separate review',clause:{locator:'SYNTHETIC paragraph',quote:'SYNTHETIC clause'}}
beforeEach(()=>{vi.resetAllMocks();io.user.mockResolvedValue({data:{user:{id:actor}},error:null});io.guard.mockResolvedValue({guard:{companyId:company},response:null})})
it('binds the actual authenticated actor and preserves a missing authentic issuer as a hold',async()=>{
 io.rpc.mockResolvedValue({data:saved,error:null});expect((await archiveSignedBrpDeclaration(company,submission)).issuerQualified).toBe(false)
 expect(io.rpc).toHaveBeenCalledWith('ediel_archive_signed_brp_declaration_v1',{p_company_id:company,p_actor_user_id:actor,p_submission:submission})
})
it.each([null,{id:actor,user_metadata:{must_change_password:true}}])('refuses an unavailable current session before any native command',async user=>{io.user.mockResolvedValue({data:{user},error:null});await expect(archiveSignedBrpDeclaration(company,submission)).rejects.toThrow('authenticated_actor');expect(io.rpc).not.toHaveBeenCalled()})
it('does not trust an errored Auth read',async()=>{io.user.mockResolvedValue({data:{user:{id:actor}},error:Error('auth unavailable')});await expect(archiveSignedBrpDeclaration(company,submission)).rejects.toThrow('authenticated_actor');expect(io.rpc).not.toHaveBeenCalled()})
it.each(['approved','actorUserId','verified'])('rejects caller authority fields: %s',async key=>{await expect(archiveSignedBrpDeclaration(company,{...submission,[key]:true})).rejects.toThrow();expect(io.rpc).not.toHaveBeenCalled()})
it.each(['%%%','AA==\n','AB=='])('rejects noncanonical original bytes %j',async encoded=>{await expect(archiveSignedBrpDeclaration(company,{...submission,sourceBase64:encoded})).rejects.toThrow();expect(io.rpc).not.toHaveBeenCalled()})
it('requires exact signed PDF original before archive effects',async()=>{await expect(archiveSignedBrpDeclaration(company,{...submission,agreementBase64:source.toString('base64')})).rejects.toThrow('signed_pdf');expect(io.rpc).not.toHaveBeenCalled()})
it.each(['agreementHash','sourceHash'])('refuses native archive hash mismatch: %s',async key=>{io.rpc.mockResolvedValue({data:{...saved,[key]:'b'.repeat(64)},error:null});await expect(archiveSignedBrpDeclaration(company,submission)).rejects.toThrow('hash_mismatch')})
it('derives source preview from native actual own scope without producing approval',async()=>{io.rpc.mockResolvedValue({data:{status:'scope_available',claims,claimsHash,authority:'none'},error:null});expect((await previewSignedBrpDeclaration(company,selector)).authority).toBe('none');io.rpc.mockResolvedValue({data:{status:'scope_available',claims:{...claims,companyId:uuid(99)},claimsHash,authority:'none'},error:null});await expect(previewSignedBrpDeclaration(company,selector)).rejects.toThrow('scope_mismatch')})
it('reads metadata with current session and refuses unrequested source bytes',async()=>{io.rpc.mockResolvedValue({data:metadata,error:null});expect((await readSignedBrpDeclaration(company,artifactId)).status).toBe('held');expect(io.rpc).toHaveBeenCalledWith('ediel_read_signed_brp_declaration_v1',{p_company_id:company,p_actor_user_id:actor,p_artifact_id:artifactId,p_include_bytes:false});io.rpc.mockResolvedValue({data:{...metadata,sourceBase64:source.toString('base64')},error:null});await expect(readSignedBrpDeclaration(company,artifactId)).rejects.toThrow('unrequested_original')})
it.each(['companyId','artifactId'])('refuses a foreign native read scope: %s',async key=>{io.rpc.mockResolvedValue({data:{...metadata,[key]:uuid(99)},error:null});await expect(readSignedBrpDeclaration(company,artifactId)).rejects.toThrow('scope_mismatch')})
it('verifies both returned originals and refuses retirement, byte substitution or incorrect lengths',async()=>{
 const exact={...metadata,agreementBase64:agreement.toString('base64'),sourceBase64:source.toString('base64')};io.rpc.mockResolvedValue({data:exact,error:null});expect((await readSignedBrpDeclaration(company,artifactId,true)).sourceBase64).toBe(exact.sourceBase64)
 for(const delta of [{bytesAvailable:false},{sourceHash:'b'.repeat(64)},{agreementByteLength:1}]){io.rpc.mockResolvedValue({data:{...exact,...delta},error:null});await expect(readSignedBrpDeclaration(company,artifactId,true)).rejects.toThrow(/original_unavailable|hash_mismatch/)}
})
it('preserves native source hold and current reviewer revocation rather than minting approval',async()=>{io.rpc.mockResolvedValue({data:{status:'held',artifactId,missing:metadata.missing},error:null});expect((await reviewSignedBrpDeclaration(company,artifactId,command)).status).toBe('held');expect(io.rpc).toHaveBeenCalledWith('ediel_review_signed_brp_declaration_v1',{p_company_id:company,p_actor_user_id:actor,p_artifact_id:artifactId,p_review:command});io.rpc.mockResolvedValue({data:null,error:Error('source_review_actor_revoked')});await expect(reviewSignedBrpDeclaration(company,artifactId,command)).rejects.toThrow('actor_revoked')})
it('accepts only a native exact scoped declaration and preserves replay result',async()=>{io.rpc.mockResolvedValue({data:{status:'authorized',artifactId,declarationId:declaration,replay:true},error:null});expect((await reviewSignedBrpDeclaration(company,artifactId,command)).status).toBe('authorized');io.rpc.mockResolvedValue({data:{status:'authorized',artifactId:uuid(99),declarationId:declaration,replay:true},error:null});await expect(reviewSignedBrpDeclaration(company,artifactId,command)).rejects.toThrow('scope_mismatch')})
it('revokes through current native authority while retaining source identity',async()=>{io.rpc.mockResolvedValue({data:{status:'held',artifactId,missing:['source_revoked']},error:null});expect((await revokeSignedBrpDeclaration(company,artifactId,'SYNTHETIC revoke')).status).toBe('held');expect(io.rpc).toHaveBeenCalledWith('ediel_revoke_signed_brp_declaration_v1',{p_company_id:company,p_actor_user_id:actor,p_artifact_id:artifactId,p_reason:'SYNTHETIC revoke'})})
it('HTTP archive uses current write rights, bounded input and private no-store result',async()=>{io.rpc.mockResolvedValue({data:saved,error:null});const response=await archivePost(new NextRequest('http://localhost/api/ediel/signed-brp-declarations',{method:'POST',body:JSON.stringify(submission)}));expect(response.status).toBe(201);expect(response.headers.get('cache-control')).toBe('private, no-store');expect(io.guard).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write']})})
it('HTTP separate reviewer needs actual additional source-review permission',async()=>{io.rpc.mockResolvedValue({data:{status:'held',artifactId,missing:metadata.missing},error:null});const response=await reviewPost(new NextRequest('http://localhost/api/ediel/signed-brp-declarations/review',{method:'POST',body:JSON.stringify(command)}),{params:Promise.resolve({artifactId})});expect(response.status).toBe(409);expect(io.guard).toHaveBeenCalledWith({allOf:['communication.write','customers.write','contracts.write','ediel.source.review']})})
it('HTTP original downloads are actual verified bytes with private content headers',async()=>{io.rpc.mockResolvedValue({data:{...metadata,agreementBase64:agreement.toString('base64'),sourceBase64:source.toString('base64')},error:null});const response=await originalGet(new NextRequest('http://localhost/api/ediel/signed-brp-declarations/original?kind=agreement'),{params:Promise.resolve({artifactId})});expect(response.status).toBe(200);expect(Buffer.from(await response.arrayBuffer())).toEqual(agreement);expect(response.headers.get('content-type')).toBe('application/pdf');expect(response.headers.get('cache-control')).toBe('private, no-store');expect(response.headers.get('x-content-type-options')).toBe('nosniff')})
it('HTTP read hides native authority details when current session has been revoked',async()=>{io.rpc.mockResolvedValue({data:null,error:Error('signed_brp_read_actor_forbidden')});const response=await originalGet(new NextRequest('http://localhost/api/ediel/signed-brp-declarations/original?kind=source'),{params:Promise.resolve({artifactId})});expect(response.status).toBe(403);expect(await response.text()).not.toContain('signed_brp_read_actor')})
