import { randomUUID } from 'node:crypto'
import { inspect } from 'node:util'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

type Row = Record<string, unknown>
const f = vi.hoisted(() => ({
  rpc: vi.fn(), context: vi.fn(), after: vi.fn(), rows: [] as Row[], writes: [] as string[],
}))
vi.mock('server-only', () => ({}))
vi.mock('next/server', async original => ({ ...await original<typeof import('next/server')>(), after: f.after }))
vi.mock('@/lib/platform/schemaReadiness', () => ({ assertPlatformSchemaReady: async () => undefined }))
vi.mock('@/lib/integrations/tenantContext', async original => ({
  ...await original<typeof import('@/lib/integrations/tenantContext')>(), loadExternalTenantContext: f.context,
}))
vi.mock('@/lib/supabase/service', () => ({ supabaseService: {
  rpc: f.rpc,
  from(table: string) {
    let row: Row | null = null
    const q = {
      update: () => q, eq: () => q,
      insert: (value: Row) => { row = value; return q },
      then: (resolve: (value: unknown) => unknown) => {
        if (row) { f.writes.push(table); f.rows.push(structuredClone(row)) }
        return Promise.resolve({ data: null, error: null }).then(resolve)
      },
    }
    return q
  },
} }))

import { NextRequest } from 'next/server'
import { logIntegrationApiRequest, type IntegrationApiClient } from '@/lib/integrations/apiAuth'
import { customerPortalJson } from '@/lib/customer-portal/externalApi'
import { GET as integrationContext } from '@/app/api/v1/integration/context/route'

const companyId = '00000000-0000-4000-8000-000000000083'
const clientId = '00000000-0000-4000-8000-000000000084'
const client: IntegrationApiClient = {
  id: clientId, company_id: companyId, name: 'Synthetic client', status: 'active', key_prefix: 'synthetic',
  secret_hash: 'synthetic', scopes: ['integration_context.read'], allowed_ips: [], rate_limit_per_minute: 60, expires_at: null,
}
const canaries = ['correlation-canary@example.invalid', '+46 70 123 45 67', 'Correlation Canary Fullname',
  'Correlation Canary Street 41', 'capway_api_key_canary_correlation_123456', 'sb_secret_canary_correlation_123456']
const raw = canaries.join(' | ')
const absent = (value: unknown) => {
  for (const canary of canaries) expect(inspect(value, { depth: 12 })).not.toContain(canary)
}
const request = (header: string | null = null) => new NextRequest('http://localhost/api/v1/integration/context', {
  headers: { Authorization: 'Bearer synthetic-current-api-token', ...(header ? { 'X-Request-ID': header } : {}) },
})
const log = (input: { serverRequestId?: string | null; metadata?: Row; header?: string | null; status?: number } = {}) => {
  // The explicit argument is generated by this server caller. Neither a
  // header nor arbitrary metadata is its producer.
  const current = {
    client, request: request(input.header ?? null), startedAt: Date.now() - 20, statusCode: input.status ?? 503,
    errorCode: 'PUBLIC_CONTRACT_SCHEMA_OUTDATED', serverRequestId: input.serverRequestId, metadata: input.metadata,
  }
  return logIntegrationApiRequest(current)
}
let errorLog: ReturnType<typeof vi.spyOn>
beforeEach(() => {
  vi.clearAllMocks(); f.rows = []; f.writes = []
  f.after.mockImplementation(() => { throw new Error('outside_request_scope') })
  f.rpc.mockResolvedValue({ data: [{
    auth_outcome: 'allowed', error_code: null, tenant_status: 'active', client_id: clientId, company_id: companyId,
    client_name: client.name, client_status: 'active', key_prefix: 'synthetic', secret_hash: 'synthetic',
    scopes: client.scopes, allowed_ips: [], allowed_origins: [], metadata: {}, expires_at: null,
    rate_limit_per_minute: 60, request_count: 1, route_limit: 60, reset_at: new Date(Date.now() + 60000).toISOString(),
  }], error: null })
  f.context.mockRejectedValue({ code: '42P01', message: raw, details: raw })
  errorLog = vi.spyOn(console, 'error').mockImplementation(() => undefined)
})
afterEach(() => errorLog.mockRestore())

describe('actual integration request correlation and diagnostic projection', () => {
  it('binds an explicitly generated server ID to actual helper persistence and canonical body/header despite contradictory client input', async () => {
    const serverRequestId = randomUUID(), header = randomUUID(), metadataId = randomUUID()
    const response = customerPortalJson({ error: { code: 'PUBLIC_CONTRACT_SCHEMA_OUTDATED', message: 'The schema is unavailable.' }, request_id: serverRequestId }, { status: 503 })
    await log({ serverRequestId, header, metadata: { request_id: metadataId, request_id_source: 'attacker_claim', result_count: 0, database_code: '42P01', operation: 'webhook.create.preflight' } })
    const body = await response.json()
    expect(body.request_id).toBe(serverRequestId); expect(response.headers.get('X-Request-ID')).toBe(serverRequestId)
    expect(f.rows[0]).toMatchObject({ company_id: companyId, api_client_id: clientId, status_code: 503, request_id: serverRequestId,
      error_code: 'PUBLIC_CONTRACT_SCHEMA_OUTDATED', metadata: { request_id: serverRequestId, request_id_source: 'server_explicit', result_count: 0, database_code: '42P01', operation: 'webhook.create.preflight' } })
  })

  it('actual exported route binds its reviewed generated body/header/log/metadata ID without trusting the incoming header', async () => {
    const response = await integrationContext(request(raw)), body = await response.json()
    expect(response.status).toBe(503); expect(body.error.code).toBe('PUBLIC_CONTRACT_SCHEMA_OUTDATED')
    expect(body.request_id).toMatch(/^[a-f0-9-]{36}$/); expect(body.request_id).not.toBe(raw)
    expect(response.headers.get('X-Request-ID')).toBe(body.request_id)
    expect(errorLog.mock.calls[0][1]).toMatchObject({ requestId: body.request_id })
    expect(f.rows[0].request_id).toBe(body.request_id)
    expect(f.rows[0].metadata).toMatchObject({ request_id: body.request_id, request_id_source: 'server_explicit' })
    absent(f.rows); absent(body); absent(errorLog.mock.calls)
    expect(f.rpc).toHaveBeenCalledOnce(); expect(f.context.mock.calls[0][0]).toMatchObject({ id: clientId, company_id: companyId })
  })

  it('never promotes even UUID-shaped header or arbitrary metadata IDs into authoritative top-level correlation', async () => {
    const header = randomUUID(), candidate = randomUUID()
    await log({ header, metadata: { request_id: candidate } })
    expect(f.rows[0].request_id).toBeNull()
    expect(f.rows[0].metadata).toEqual({ request_id: candidate, request_id_source: 'unverified_metadata' })
  })

  it('does not manufacture a new unrelated ID when this caller lacks an explicit server binding', async () => {
    await log()
    expect(f.rows[0].request_id).toBeNull()
    expect(f.rows[0].metadata).not.toHaveProperty('request_id')
  })

  it('minimizes actual persisted metadata to supported technical fields and never takes tenant/actor authority from it', async () => {
    const serverRequestId = randomUUID(), idempotencyRecordId = randomUUID()
    await log({ serverRequestId, metadata: {
      result_count: 2, channel: 'website', decision: 'denied', api_surface: 'partner_v1_canonical',
      operation: 'customer.get', access_mode: 'json_payload',
      idempotency_replay: true, idempotency_record_id: idempotencyRecordId, database_code: '23505', field: 'customer_type',
      error_stage: 'validation', error_code: 'customer_type_invalid', unknown_label: raw, details: { secret: raw },
      portal_sync_error: raw, external_customer_id: raw, error_path: raw, offer_reference: raw,
      company_id: randomUUID(), actor_user_id: randomUUID(), status_code: 200, request_id_source: 'attacker_claim',
    } })
    expect(f.rows[0]).toMatchObject({ company_id: companyId, api_client_id: clientId, status_code: 503, request_id: serverRequestId })
    const metadata = f.rows[0].metadata as Row
    expect(metadata).toMatchObject({ result_count: 2, channel: 'website', decision: 'denied', api_surface: 'partner_v1_canonical',
      operation: 'customer.get', access_mode: 'json_payload',
      idempotency_replay: true, idempotency_record_id: idempotencyRecordId, database_code: '23505', field: 'customer_type',
      error_stage: 'validation', error_code: 'customer_type_invalid', request_id_source: 'server_explicit' })
    for (const key of ['unknown_label', 'details', 'portal_sync_error', 'external_customer_id', 'error_path', 'offer_reference', 'company_id', 'actor_user_id', 'status_code']) expect(metadata).not.toHaveProperty(key)
    absent(f.rows)
  })

  it('rejects free text hidden in known technical keys without guessing that arbitrary strings are safe', async () => {
    await log({ metadata: { request_id: raw, trace_id: raw, database_code: raw, field: raw, error_code: raw,
      error_stage: raw, api_surface: raw, operation: raw, access_mode: raw, channel: raw,
      decision: raw, result_count: raw, idempotency_replay: raw } })
    expect(f.rows[0].metadata).toEqual({ request_id_source: 'unavailable' }); absent(f.rows)
  })

  it('rejects an invalid explicit ID without falling back to header or untrusted metadata authority', async () => {
    const candidate = randomUUID()
    await log({ serverRequestId: raw, header: randomUUID(), metadata: { request_id: candidate } })
    expect(f.rows[0].request_id).toBeNull(); expect(f.rows[0].metadata).toMatchObject({ request_id: candidate, request_id_source: 'unverified_metadata' }); absent(f.rows)
  })

  it('captures projected correlation and technical metadata before deferred persistence and ignores later caller mutation', async () => {
    f.after.mockImplementation(() => undefined)
    const serverRequestId = randomUUID(), metadata: Row = { result_count: 1, database_code: '42P01', operation: 'contract.status' }
    await log({ serverRequestId, metadata })
    expect(f.rows).toEqual([]); expect(f.after).toHaveBeenCalledOnce()
    metadata.result_count = 999; metadata.database_code = raw; metadata.unknown_label = raw
    await f.after.mock.calls[0][0]()
    expect(f.rows[0]).toMatchObject({ request_id: serverRequestId, metadata: { result_count: 1, database_code: '42P01', operation: 'contract.status', request_id: serverRequestId, request_id_source: 'server_explicit' } }); absent(f.rows)
  })

  it('preserves anonymous 401 no-target behavior before any telemetry scheduling or write', async () => {
    await logIntegrationApiRequest({ client: null, request: request(raw), statusCode: 401, startedAt: Date.now(), metadata: { anything: raw } })
    expect(f.rows).toEqual([]); expect(f.after).not.toHaveBeenCalled()
  })
})
