'use client'
import {useState,useRef,type FormEvent} from 'react'
import type {FreshEdielBusinessIncident} from '@/lib/ediel/incidents/freshBusinessIncident'
/** An explicit new business check, separate from retrying an existing ACK. */
export default function BusinessIncidentsPage(){
 const operation=useRef<{key:string;id:string}|null>(null)
 const [receipt,setReceipt]=useState<FreshEdielBusinessIncident|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false)
 async function report(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError('');const form=new FormData(event.currentTarget)
  try{const input={sourceMessageId:form.get('sourceMessageId'),ackMessageId:form.get('ackMessageId'),scopeReference:form.get('scopeReference'),finding:{code:'late_internal_business_error',summary:form.get('summary')}},key=JSON.stringify(input);if(operation.current?.key!==key)operation.current={key,id:crypto.randomUUID()};const response=await fetch('/api/ediel/business-incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:operation.current!.id,...input})});const data=await response.json();if(!response.ok)throw Error(data.error??'Incidenten kunde inte registreras.');setReceipt(data)}catch(reason){setError(reason instanceof Error?reason.message:'Incidenten kunde inte registreras.')}finally{setPending(false)}}
 async function reload(){if(!receipt)return;setPending(true);setError('');try{const response=await fetch(`/api/ediel/business-incidents?incidentId=${encodeURIComponent(receipt.incidentId)}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error??'Incidenten kunde inte läsas.');setReceipt(data)}catch(reason){setError(reason instanceof Error?reason.message:'Incidenten kunde inte läsas.')}finally{setPending(false)}}
 return <main className="mx-auto max-w-3xl space-y-6 p-6"><h1 className="text-2xl font-semibold">Nytt affärsfel efter kvittens</h1><p>Registrera en ny observation för ett tidigare positivt kvitterat objekt eller en transaktion. Originalets kvittens bevaras. Kontakt och rättelse väntar på en separat granskning.</p><form onSubmit={report} className="grid gap-4"><label>Originalets meddelande-ID<input name="sourceMessageId" required className="block w-full rounded border p-2"/></label><label>Den accepterade kvittensens meddelande-ID<input name="ackMessageId" required className="block w-full rounded border p-2"/></label><label>Originalets objekt- eller transaktionsreferens<input name="scopeReference" required maxLength={100} className="block w-full rounded border p-2"/></label><label>Den nya observationen<textarea name="summary" required maxLength={2000} rows={4} className="block w-full rounded border p-2"/></label><button type="submit" disabled={pending} className="rounded border px-4 py-2">{pending?'Registrerar…':'Registrera incident'}</button></form><p role="alert">{error}</p>{receipt&&<section aria-live="polite" className="space-y-2 rounded border p-4"><h2 className="font-semibold">Incident registrerad</h2><p className="break-all">{receipt.incidentId}</p><p>{receipt.finding.summary}</p><p>Kontakt: väntar på granskning. Rättelse: väntar på granskning.</p><button type="button" onClick={reload} disabled={pending} className="rounded border px-4 py-2">Läs registrerad incident</button></section>}</main>
}
