'use client'
import {useState,useRef,type FormEvent} from 'react'
import type {FreshEdielBusinessIncident} from '@/lib/ediel/incidents/freshBusinessIncident'
/** The server derives current company rights. Every API operation reauthorizes. */
export default function BusinessIncidentWorkspace({canReport,initialReceipt,initialIncidentId,initialError}:{canReport:boolean;initialReceipt:FreshEdielBusinessIncident|null;initialIncidentId:string;initialError:string}){
 const operation=useRef<{key:string;id:string}|null>(null)
 const [receipt,setReceipt]=useState(initialReceipt),[error,setError]=useState(initialError),[pending,setPending]=useState(false)
 const inputClass='block min-h-11 w-full min-w-0 rounded border p-2',buttonClass='min-h-11 rounded border px-4 py-2'
 async function report(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!canReport||pending)return;setPending(true);setError('');const form=new FormData(event.currentTarget)
  try{const input={sourceMessageId:form.get('sourceMessageId'),ackMessageId:form.get('ackMessageId'),scopeReference:form.get('scopeReference'),finding:{code:'late_internal_business_error',summary:form.get('summary')}},key=JSON.stringify(input);if(operation.current?.key!==key)operation.current={key,id:crypto.randomUUID()};const response=await fetch('/api/ediel/business-incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:operation.current!.id,...input})});const data=await response.json();if(!response.ok)throw Error(data.error??'Incidenten kunde inte registreras.');setReceipt(data)}catch(reason){setError(reason instanceof Error?reason.message:'Incidenten kunde inte registreras.')}finally{setPending(false)}}
 async function read(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setPending(true);setError('');const id=String(new FormData(event.currentTarget).get('incidentId')??'')
  try{const response=await fetch(`/api/ediel/business-incidents?incidentId=${encodeURIComponent(id)}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error??'Incidenten kunde inte läsas.');setReceipt(data)}catch(reason){setReceipt(null);setError(reason instanceof Error?reason.message:'Incidenten kunde inte läsas.')}finally{setPending(false)}}
 return <div className="min-w-0 space-y-6" aria-busy={pending}>{canReport?<section aria-labelledby="report-title"><h2 id="report-title" className="mb-4 text-xl font-semibold">Registrera en ny observation</h2><form onSubmit={report} className="grid min-w-0 gap-4"><label>Originalets meddelande-ID<input aria-label="Originalets meddelande-ID" name="sourceMessageId" required className={inputClass}/></label><label>Den accepterade kvittensens meddelande-ID<input aria-label="Den accepterade kvittensens meddelande-ID" name="ackMessageId" required className={inputClass}/></label><label>Originalets objekt- eller transaktionsreferens<input aria-label="Originalets objekt- eller transaktionsreferens" name="scopeReference" required maxLength={100} className={inputClass}/></label><label>Den nya observationen<textarea aria-label="Den nya observationen" name="summary" required maxLength={2000} rows={4} className={inputClass}/></label><button type="submit" disabled={pending} className={buttonClass}>{pending?'Registrerar…':'Registrera incident'}</button></form></section>:<p>Du kan läsa bolagets incidenter. Registrering kräver aktuella skriv- och sändrättigheter.</p>}
 <form onSubmit={read} className="grid min-w-0 gap-4"><label>Incidentens ID<input aria-label="Incidentens ID" name="incidentId" required defaultValue={initialIncidentId} className={inputClass}/></label><button type="submit" disabled={pending} className={buttonClass}>Läs registrerad incident</button></form><p role="alert" className="break-words">{error}</p>{receipt&&<section aria-live="polite" aria-labelledby="receipt-title" className="min-w-0 space-y-2 rounded border p-4"><h2 id="receipt-title" className="font-semibold">Registrerad observation</h2><p className="break-all">{receipt.incidentId}</p><p className="break-words">{receipt.finding.summary}</p><p>Observationen är ännu inte verifierad. Kvittenshistoriken är bevarad.</p><p>Kontakt: väntar på granskning. Rättelse: väntar på granskning.</p></section>}</div>
}
